### ISSUE TITLE
Add an example on how to sort the results from HEK

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1005]
The result from HEK is that it is sorted by date, which make sense as that's what HEK provides. To sort it by magnitude this works:

```python
>>> result = client.search(hek.attrs.Time(tstart, tend), hek.attrs.EventType(event_type), hek.attrs.FL.GOESCls > 'X1', hek.attrs.OBS.Observatory == 'GOES')
>>> mag_sorted = sorted(result, key=lambda x: ord(x['fl_goescls'][0])*100+float(x['fl_goescls'][1:]))
>>> for r in mag_sorted:
...  print('type {} on {}'.format(r['fl_goescls'], r['event_starttime']))

type X1.1 on 2003-10-19T16:29:00
type X1.1 on 2003-10-23T19:50:00
type X1.2 on 2003-10-26T05:57:00
type X1.2 on 2003-10-26T17:21:00
type X2.7 on 2003-11-03T01:09:00
type X3.9 on 2003-11-03T09:43:00
type X5.4 on 2003-10-23T08:19:00
type X8.3 on 2003-11-02T17:03:00
type X10. on 2003-10-29T20:37:00
type X17. on 2003-10-28T09:51:00
type X28. on 2003-11-04T19:29:00
```
This gives the same result and it's more robust (we've got tests):

```python
>>> from sunpy.instr.goes import flareclass_to_flux
>>> mag_sorted = sorted(result, key=lambda x: flareclass_to_flux(x['fl_goescls']))
```

Maybe we could put this as an example on the gallery.

**Comment by dpshelio** [comment]
I'm confused with this issue that I've opened... The result it's sorted by date, which make sense as that's what HEK provides. To sort it by magnitud this works:

```python
>>> result = client.search(hek.attrs.Time(tstart, tend), hek.attrs.EventType(event_type), hek.attrs.FL.GOESCls > 'X1', hek.attrs.OBS.Observatory == 'GOES')
>>> mag_sorted = sorted(result, key=lambda x: ord(x['fl_goescls'][0])*100+float(x['fl_goescls'][1:]))
>>> for r in mag_sorted:
...  print('type {} on {}'.format(r['fl_goescls'], r['event_starttime']))

type X1.1 on 2003-10-19T16:29:00
type X1.1 on 2003-10-23T19:50:00
type X1.2 on 2003-10-26T05:57:00
type X1.2 on 2003-10-26T17:21:00
type X2.7 on 2003-11-03T01:09:00
type X3.9 on 2003-11-03T09:43:00
type X5.4 on 2003-10-23T08:19:00
type X8.3 on 2003-11-02T17:03:00
type X10. on 2003-10-29T20:37:00
type X17. on 2003-10-28T09:51:00
type X28. on 2003-11-04T19:29:00
```
This gives the same result and it's more robust (we've got tests):

```python
from sunpy.instr.goes import flareclass_to_flux
mag_sorted = sorted(result, key=lambda x: flareclass_to_flux(x['fl_goescls']))
```

I believe we can close this, maybe we could put this as an example on the gallery.

**Comment by wafels** [comment]
More generally it would be good to have an HEK event class that holds event
information. Would the current way map is implemented work for events too?

**Comment by Telomelonia** [comment]
I have added the PR for this issue
Suggest any changes required.

**Comment by Telomelonia** [comment]
> This gives the same result and it's more robust (we've got tests):
> 
> ```python
> >>> from sunpy.instr.goes import flareclass_to_flux
> >>> mag_sorted = sorted(result, key=lambda x: flareclass_to_flux(x['fl_goescls']))
> ```

@nabobalis 
Is the instrument package removed? cause I wanted to use the `flareclass_to_flux` tool in the example.
