### ISSUE TITLE
sunpy.wcs.pixel_to_data doesn't work for negative pixel values.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1071]
This is wrong, calculating a data coord of a pixel out of your image can sometimes be useful

**Comment by agneet42** [comment]
@Cadair, sunpy.wcs.pixel_to_data is now deprecated by sunpy.map.GenericMap.pixel_to_data, does this function still need a update to accomodate +ve values?

**Comment by Cadair** [comment]
No. It's been replaced.
