### ISSUE TITLE
Deprecate python 2.6

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1087]
At the moment we may be spending quite a lot of time to maintain backwards compatibility with Python 2.6.  Probably none of our users is using it (though mail has been sent around asking about it).

What does it needs to be done:
- [x] look through the code base for backwards compatibility hacks (and fix them)
- [x] remove it from Travis 
- [ ] change stuff from pypi
- [ ] Remove `Counter` and `OrderedDict` backports from `sunpy.util` (Import them from `collections`).

**Comment by nabobalis** [comment]
#MINE #TOTHEFUTURE

**Comment by aringlis** [comment]
Is this issue closeable? IIRC we have dropped support for 2.6 now.
