### ISSUE TITLE
VSOClient.get(qr[1]) fails because qr[1] is not iterable.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1137]
`VSOClilent.get()` needs to deal with this by making it a list, or the `QueryResponse` object slicing needs overloading to make it always return a list.

**Comment by wtbarnes** [comment]
@Cadair can you confirm this still is/not a problem?

**Comment by Cadair** [comment]
It might still be an issue, but as `Fido` is now our interface to `VSOClient` and it doesn't have this issue, do we care?
