### ISSUE TITLE
database.download should accept a QueryResponse object.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1139]

**Comment by dumindux** [comment]
Hi I am a GSOC aspirant this year. Is this still a valid issue to work on?

**Comment by Cadair** [comment]
yeah, go for it!

**Comment by dumindux** [comment]
@Cadair in the module there is a method called ```download_from_vso_query_result``` now(derdon has mentioned it above). So still should this functionality be added to download method?

**Comment by Cadair** [comment]
@dumindux the `download_from_query_result` method needs writing, at the moment there is only the functionality to add the meta data from the query result, not download the data.

**Comment by Cadair** [comment]
Yep, this functionality appears to already be in place: https://github.com/sunpy/sunpy/blob/master/sunpy%2Fdatabase%2Fdatabase.py#L650
