### ISSUE TITLE
Maps using the CD matrix are not correctly modified by resample

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1147]
resample only changes the CDELT flags not CD if present.

**Comment by dpshelio** [comment]
@Cadair - is this still the case?

**Comment by Cadair** [comment]
yes, this is quite non-trivial to fix, our abstraction dosen't really facilitate it.

**Comment by wtbarnes** [comment]
Example? What files are these that don't have the `CDELT` keywords? Could we at least add a warning in `resample()` that is raised if the CD matrix (tbh, I don't even know what this is) is present?

**Comment by Cadair** [comment]
I am not sure I have an example of a file, but it's a perfectly legitimate to have a `CD` matrix instead of `CDELT` + `PCi_j`.

**Comment by dstansby** [comment]
This should at least raise a warning or `NotImplemented` error. Can someone provide a self contained example that causes this un-wanted behaviour?

**Comment by dstansby** [comment]
`resample` currently modifies the `CD` header values, so I'm not sure this is broken? Unless anyone can provide a simple self contained reproducible example I am minded to close this...
