### ISSUE TITLE
parse_time does not always return a datetime object

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#1152]
Hi guys,
Having spoken to @Cadair last week at SIPwork, we realised that parse_time() does not return a datetime object when a pandas Timestamp is input.  It simply returns the Timestamp object.  We think it should always give the same type of answer so that it can be consistently used.  Until we move to astropy time objects, this should be a datetime object.  So it would be good to get this changed in the meantime.

**Comment by Cadair** [comment]
I think this is fixed by #1229. @DanRyanIrish Can you confirm?

**Comment by DanRyanIrish** [comment]
@Cadair, #1229 indeed seems to have solved this issue.
