### ISSUE TITLE
Make Map (and other datatypes) have setters for metadata

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1155]
I know when @rhewett and I were building the new `Map` class we chose not to do this because we didn't want to encourage the user to break things, however, if we are to maintain the ability to save out files using similar meta data to the file read in, implementing setters so that the metadata -> property mapping works both ways would be very useful.

Also I see a situation where the user will want to manually update the metadata, because they have written a function to do something custom, and having to manually know what the keys in the dicts are rather than being able to use instrument independent setters seems a little silly.

**Comment by abit2** [comment]
@Cadair do all the metadata need setters?

**Comment by samaloney** [comment]
I guess with great power comes great responsibility - how would implicitly related keywords be handled I'm specifically thinking of `DATE_OBS`, `DATE_BEG`, DATE_AVG`, `DATE_END` that all SolarOrbiter files will have and some current fit files have `DATE_OBS` and `DATE_END`?

**Comment by dstansby** [comment]
As a slight aside, regardless of setting properties, should we be adding properties for all of these extra FITS keywords?

**Comment by dstansby** [comment]
Closing this as per https://github.com/sunpy/sunpy/pull/3911#issuecomment-614728637
