### ISSUE TITLE
VSO Quicklook attribute must use 1 or 0, not True or False

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1169]
This call:

qr = client.query(vso.attrs.Time('2009/1/1', '2015/1/2'), vso.attrs.Instrument('aia'), vso.attrs.Sample(3600*6), vso.attrs.Wave(193, 193), vso.attrs.Provider('SDAC'), vso.attrs.Quicklook(True))

does not give the correct number of query results, but this one

qr = client.query(vso.attrs.Time('2009/1/1', '2015/1/2'), vso.attrs.Instrument('aia'), vso.attrs.Sample(3600*6), vso.attrs.Wave(193, 193), vso.attrs.Provider('SDAC'), vso.attrs.Quicklook(1))

does.  This should at least be noted somewhere.  Or perhaps vso.attrs.Quicklook should detect the value True and reset it to 1 when actually making the query.  The IDL version of this query uses /quicklook keyword, which sets the quicklook keyword equal to 1.  Note that IDL does not have a boolean type, and so 1 is equivalent to True, and 0 is equivalent to False.

**Comment by nabobalis** [comment]
Solved by #2087
