### ISSUE TITLE
VSO download filenames end with _fts not .fts

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#1171]
Executing the following code:

    from sunpy.net import vso
    client = vso.VSOClient()
    tstart, tend = '2011-06-07 05:30', '2011-06-07 06:30'
    lasco_query = client.query(vso.attrs.Time(tstart, tend), vso.attrs.Instrument('lasco'))
    pathformat = '/Users/ainglis/physics/sodawg/{file}'
    results = client.get(lasco_query, path = pathformat)

gives me filenames that end with _fts, e.g. 22375019_fts. But the filenames on the server end in .fts, e..g:

    lasco_query[0]
    (QueryResponseBlock){
    source = "SOHO"
    provider = "SDAC"
    physobs = "intensity"
    fileid = "/archive/soho/private/data/processed/lasco/level_05/110607/c2/22375019.fts"
    time = 
      (Time){
         end = "20110607053548"
         start = "20110607053523"
      }
    instrument = "LASCO"
    size = 2059.0
    wave = 
      (Wave){
         waveunit = None
         wavemin = None
         wavemax = None
      }
    extent = 
      (Extent){
         width = None
         y = None
         length = None
         type = "CORONA"
         x = None
      }
     }

Is this known or a bug?

**Comment by dumindux** [comment]
@Cadair @segfaulthunter In this situation it seems that slugify method replaces all periods with "delim" which is set default to "_". How about we keep the last period(which delimits filename and the extension) and only replace periods before that with "delim"?
Example:
if text to slugify is "asdf.fdg.df.fts"
We make it "asdf_fdg_df.fts"

I think this will solve the problem.

**Comment by Cadair** [comment]
@dumindux I think that makes sense. I doubt that would cause too many side effects.

**Comment by dumindux** [comment]
Hm yeah I am not sure about side effects too. If you have another suggestion about this I would like to work on this.

**Comment by Cadair** [comment]
@dumindux I think your approach should work. Give it a try and see if anything breaks.

**Comment by dumindux** [comment]
Ok great :) .
