### ISSUE TITLE
Achieve 80% test coverage

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1175]
This is a general coverall issue, at the time of writing we need another 5%, progress can be found here:

https://coveralls.io/r/sunpy/sunpy?branch=master

There are some parts which are very much in need:

* sunpy/sun/position.py - https://coveralls.io/files/333354154
* sunpy/sun/models.py - https://coveralls.io/files/333354153

Check the latest coveralls report for more 0% files!

However, the main thing that needs doing to improve our coverage percent (massively) is for someone to write a mechanism for us to do comparison tests on plots. See the implementation in astrofrog/wcsaxes#41 as potential inspiration for anyone taking this on.

**Comment by ehsteve** [comment]
Currently at ~76%.

**Comment by ehsteve** [comment]
Let's try to make sure that we keep test quality in mind when striving to achieve this.

**Comment by ayshih** [comment]
> However, the main thing that needs doing to improve our coverage percent (massively) is for someone to write a mechanism for us to do comparison tests on plots.

See also #410

**Comment by wafels** [comment]
just a note to store this idea - ayshih just suggested using hashes of
images, instead of the images themselves, when testing plot output.

**Comment by ehsteve** [comment]
First priority should be that we check to see if plots return actual matplotlib objects.
Second priority is to check plot images png hashes with hashes that are stored under version control.

**Comment by ehsteve** [comment]
Can use the standard python library hash lib https://docs.python.org/2/library/hashlib.html
