### ISSUE TITLE
Fix doctests and enable them on Travis

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1177]
doctests are a way of running the code in the code examples in the documentation, this is an excellent way to make sure the documentation stays upto date with API changes.

Doctests can be run using `sphinx-build -t doctest -b doctest ./ _build`  from within the `doc/source` directory of the sunpy repo.

Once all the doctests are passing then we can enable them by adding the command to the `travis.yml` file to enable the testing on Travis-CI.

**Comment by bsipocz** [comment]
It seems that 236/434 doctest fail. 
Would you prefer to see a monster PR that tries to address most of it, or smaller ones that possibly can be reviewed and merged faster? I'm down to 97/434 but not sure how fast I can fix up the rest.

**Comment by bsipocz** [comment]
@dpshelio -  This or a similar "Fix all code examples in doc" could be part of project #4. Most of it is much novice friendly task, but needs lots of muscle work...

**Comment by nabobalis** [comment]
Already done by Cadair.
