### ISSUE TITLE
Prevent the offline tests accessing the internet.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1196]
Astropy do this, we should make offline tests fail if they try and access the internet.

See this file: https://github.com/astropy/astropy/blob/master/astropy/tests/disable_internet.py we might even be able to import it from them rather than maintaining our own version.

**Comment by souravsingh** [comment]
I have put up a pull request.Here it is-https://github.com/sunpy/sunpy/pull/1579

**Comment by abit2** [comment]
Need help getting started

**Comment by souravsingh** [comment]
There is already a PR for this issue at #1586. I am trying to figure out how to hook it to the test build.

**Comment by abit2** [comment]
Can you suggest some other issue.Novice preferably.

**Comment by Cadair** [comment]
closed by #1902

**Comment by Cadair** [comment]
fix for this in #1904
