### ISSUE TITLE
Support conversion from Solar coordinates to astrophysical coordinates

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1231]
Due to the way the `astropy.coordinates` transformation graph works, we would only need to define one transformation, probably from heliocentric to an astropy coordinate frame. We could probably also convert from helioprojective to a similar astrophysical frame if one exists as well.

See astropy/astropy#3217 and astropy/astropy#3219 for things that might be relevant.

@mhvk @eteq @astrofrog Do you have suggestions as to which frames are best for this, implemented or otherwise in Astropy?

**Comment by ayshih** [comment]
Closed via #2186
