### ISSUE TITLE
Document Quantities in SunPy

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1236]
We should probably have a whole guide section on units and quantities and how they pertain to SunPy.

There needs to be a section on how to use Quantities, as well as further reading links to the main Astropy docs, and an explanation of how functions in SunPy should always accept Quantities and only Quantities and always return them.

As well as this there needs to be a developer section describing the key points of [SEP 3](https://github.com/sunpy/sunpy-SEP/blob/master/SEP-0003.md) and the `astropy.units.quantity_input` decorator.

**Comment by wafels** [comment]
I'll have a stab at this.
