### ISSUE TITLE
Fix default database url under windows.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1240]

**Comment by ayshih** [comment]
See #1219 and the offending `os.path.join`

**Comment by ayshih** [comment]
Despite `os.path.join` putting backslashes into the URL, `sqlalchemy` appears to handle it fine (tested on Windows 8), much as Python is fine with mixed forward slashes and backslashes for file paths.  I'm closing this issue pending a report for a Windows setup actually not working.  If it needs to be fixed, #1249 shows how to do it.
