### ISSUE TITLE
LYRALightCurve Timestamps incorrect

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#1256]
When a LYRALightcurve object is created using level 2 (nominally 20 Hertz temporal resolution), all measurements within the same second have the same time stamps.  This needs to be fixed to reflect the subsecond time differences between measurements.

**Comment by Rishabhmishra328** [comment]
Is this issue closed?
As i would like to look into it.

**Comment by DanRyanIrish** [comment]
Hi @Rishabhmishra328.  I believe that this particular issue was sorted out by @aringlis.  Is this true @aringlis?  If this is true then we should mark it as closed.

**Comment by Rishabhmishra328** [comment]
@DanRyanIrish 
I found a simlilar issue #1307, where the solution is merged but the issue still says open.
Can you please mark that as close too.
Thanks.

**Comment by DanRyanIrish** [comment]
Hmmm.  Interesting.  At the top of #1307 it says open but if you look at the bottom it says it's been closed.  And I believe that issue is closed.  We should make that clearer.

**Comment by aringlis** [comment]
Hi guys - this issue was resolved with PR #1355, so it can be closed now.

**Comment by DanRyanIrish** [comment]
Great.  Thanks @aringlis.  @Cadair, can you close this issue?  Cheers.
