### ISSUE TITLE
LYRALightCurve returns level 2 data even when "lev" kwarg is set to 3.

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#1257]
The LYRALightCurve "lev" kwarg is supposed to allow the user to create a lightcurve object with level 2 (sub-second resolution) or level 3 (1-minute resolution).  At the moment, level 2 data is used even if lev=3.

**Comment by aringlis** [comment]
The code seems to correctly download level 3 files, but with the keyword level=3, rather than lev=3. Is this therefore a documentation issue? The SunPy API reference doesn't seem to indicate what the allowed kwargs are.

**Comment by DanRyanIrish** [comment]
@aringlis You're right!  This is good news!

**Comment by aringlis** [comment]
Is this closable? It's not really a bug as the code does work - it's more a documentation issue, since the correct keyword to use isn't written down anywhere obvious.

**Comment by Cadair** [comment]
well it should be documented!

It's probably worth waiting till we merge unidown

**Comment by Famguy** [comment]
Hey! Could you tell me where exactly should the API kwargs be added?
