### ISSUE TITLE
A client to obtain data from the SDO Cutout service

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1259]
The SDO cutout service

http://www.lmsal.com/get_aia_data/

is a web application that allows users to select regions of interest in AIA and HMI data.  On completion of the request, an email is sent to the user informing them that the data is ready.  A piece of SSWIDL code is provided that allows the user to download the cutouts locally.

The relevant SSWIDL code is ssw_service_get_data.pro.  Each request to the cutout service generates an identifier which is used by ssw_service_get_data.pro . To get the data from the cutout service users type something like

SSWIDL> ssw_service_get_data,"ssw_service_150113_120434_79087",/loud

where 'ssw_service_150113_120434_79087' is the identifier.  The details of the request are available on a webpage: 

http://sdowww.lmsal.com/sdomedia/ssw/media/ssw/ssw_client/data/ssw_service_150113_120434_79087/

At the bottom of the page are lists of the locations of the actual files generated by the SDO cutout service.

http://sdowww.lmsal.com/sdomedia/ssw/ssw_client/data/ssw_service_150113_120434_79087/ssw_cutout_20120923_000000_AIA_171_.list

Given the identifier, it should be possible to write a routine that scrapes the relevant webpages for the file list, and from there to download the data.  This would allow users of sunpy to use the cutout service and acquire the cutout data without having to use SSWIDL.

There's some information in [this script](http://jsoc.stanford.edu/ajax/exportfile.csh) that could be useful, like the [url](http://jsoc.stanford.edu/cgi-bin/ajax/show_series?) to obtain all the series and their keywords (I don't know which parameters need to be set for filtering it as in the website).

I suspect the effort to implement this would be quite high. In the meantime, could we at least provide an example of how to use the job id (the thing that you get in the email after you make the cutout request) to download the data?

We also have a new JSOCClient that uses `sunpy/drms`. This might be possible using that as a base and submitting the feature to that package.

**Comment by Cadair** [comment]
Cann the JSOC export data service also do this? Which with a few tweaks to the JSOCClient it could probably make calls to that.

**Comment by wafels** [comment]
I'm not sure.  I have been unable to find a cutout service at the JSOC pages, but I may have missed it.  I'll ask around.

**Comment by wafels** [comment]
In any case, we still might want the capability to download cutout files from the LMSAL cutout service.   I'll cook up something, as I want this for myself anyway.

**Comment by Cadair** [comment]
If you go into export data, put in a series (hmi.Ic_720s) and then click processing, then im_patch there are the options.

**Comment by Cadair** [comment]
it looks like the lmsal service can request the data from JSOC, although not at the moment.

**Comment by wafels** [comment]
Does that also work with AIA data?

**Comment by Cadair** [comment]
@wafels yeah, I was just giving an example series.

**Comment by wafels** [comment]
Well, that is good news.

**Comment by Cadair** [comment]
I will have a look into what is needed to support it in the `JSOCClient`, I already need to look into that as they require an email, and I think the current interface doesn't allow one.

**Comment by dpshelio** [comment]
There's some information in [this script](http://jsoc.stanford.edu/ajax/exportfile.csh) that could be useful, like the [url](http://jsoc.stanford.edu/cgi-bin/ajax/show_series?) to obtain all the series and their keywords (I don't know which parameters need to be set for filtering it as in the website).

**Comment by nabobalis** [comment]
@Cadair should start on this.

**Comment by Cadair** [comment]
It was you I was talking to about the JSOC one right @nabobalis ?

**Comment by nabobalis** [comment]
#YesItWas

**Comment by wtbarnes** [comment]
Has there been any progress on this? Would the [drms](https://github.com/sunpy/drms) package make this easier?

It seems that the only way to do cutouts is via the LMSAL page that @wafels links to above. 

I suspect the effort to implement this would be quite high. In the meantime, could we at least provide an example of how to use the job id (the thing that you get in the email after you make the cutout request) to download the data?

**Comment by wtbarnes** [comment]
I need to correct my comment above. JSOC does offer a way to do cutouts via the [export data](http://jsoc.stanford.edu/ajax/exportdata.html) page. See Stuart's comment above. The question is how exactly to get at that API.

I think the first step will be doing this in the drms package and then adding the ability to propagate that query through `Fido`.

**Comment by wtbarnes** [comment]
So there seem to be many ways to specify a cutout via the `im_patch` command in DRMS, but I think, at least to start, we should just allow a cutout to be specified in the same way that a rectangle or submap is specified. For example, this could be done with a new `attr` where one specifies the width, height, and lower left corner as a `SkyCoord` and, for example, whether tracking should be turned on.

The tricky thing is, this really has nothing to do with the query (you can't do a search on something that doesn't yet exist). It makes more sense for this to be supplied to `request_data` though I'm not completely sure if this really makes sense in terms of how `request_data` works. As an example of what I have in mind,

```python
c = sunpy.net.jsoc.JSOCClient()
resp = c.search(
    attrs.Time('2015-10-17T04:33:30.000', '2015-10-17T04:34:30.000'),
    attrs.jsoc.Series('aia.lev1_euv_12s),
    attrs.jsoc.Segment('image'),
   attrs.Wavelength(171*u.angstrom),
)
frame = Helioprojective(obstime=astropy.time.Time('2015-10-17T04:33:30.000')
lower_left = SkyCoord(Tx=-517.2*u.arcsec, Ty=-246*u.arcsec, frame=frame, obstime=frame.obstime)
req = c.request_data(
    resp,
    attrs.jsoc.Patch(lower_left, width=345.6*u.arcsec, height=345.6*u.arcsec, tracking=True)
)
```

where the first coord is the lower left corner of the patch.
```
