### ISSUE TITLE
Resuming Stalled Download

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#1280]
When downloading a large series of images using the VSO client, the JSOC server sometimes stalls mid way through the series. Aborting the code forces the download to start over, but vso.VSOClient.get() doesn't process the query results in the same order, which means restarting the data download from the beginning and getting several duplicate files. Any way to force vso.VSOClient.get() to retrieve sorted results (e.g. chronologically)?

**Comment by Cadair** [comment]
@MSKirk Not that I know of, this would probably require some serious improvement to our download manager (which could probably use some improvement anyway).

**Comment by MSKirk** [comment]
Thanks @Cadair I will see if I can come up with a workaround for the time being.

**Comment by Cadair** [comment]
@MSKirk you could look into using the database module, it might be possible to add this kind of functionality there.

**Comment by ehsteve** [comment]
This should be an easy fix as the VSO has given you the filenames as a result of the search query, right? Could just check to see if the file already exists in the download dir and skip it if it does.

**Comment by Cadair** [comment]
@ehsteve but if the download failed mid-file that will lead to incomplete files.

**Comment by MSKirk** [comment]
@ehsteve in the ssw VSO module there is an automatic check of filename and size before downloading the requested data. This is slow, but works well for weeding out incomplete files.

**Comment by Cadair** [comment]
@MSKirk I wonder where the file size comes from, if it is the HTTP response or the VSO result. We should probably move our downloader to using something external and more featurefull.
