### ISSUE TITLE
Indexing the mapcube

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1290]
PR #1289 returns a mapcube object when indexing a mapcube object, except in the case when a single mapcube layer is requested.  In this case, a map object is returned.  Mapcube indexing therefore can return two different objects.  This seems problematic.

Perhaps it would be better if indexing a mapcube always returned a mapcube.  Individual maps can always be accessed using the mapcube's maps properties.  This property allows the user to iterate through the individual maps in the mapcube.  Any thoughts?

**Comment by ayshih** [comment]
Is it really a problem if MapCube indexing can return two different objects?  After all, ndarray has analogous behavior.  The user can then choose between using `x[1]` to get a single lower-level object and using `x[1:2]` to get the higher-level object with just one lower-level object.

**Comment by wafels** [comment]
Closed.
