### ISSUE TITLE
Remove the NDData compatibility layer

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1302]
We should align map to the new astropy NDData API by removing the compatibility layer.

The new NDData API is described here: https://github.com/astropy/astropy-APEs/blob/master/APE7.rst

SunPy uses NDData as the base class for [map](https://github.com/sunpy/sunpy/blob/master/sunpy%2Fmap%2Fmapbase.py#L47).

Due to the API changes in astropy 1.0 we implemented a compatibility layer that makes the 1.0 NDData class behave more like the version in 0.4.x. [here](https://github.com/sunpy/sunpy/blob/master/sunpy%2Fmap%2Fnddata_compat.py).

This layer should be removed and the necessary modifications made to the `GenericMap` class so that it supports the new API. The main changes that need to be made is that the public properties `.data` and `.meta` are no longer writeable and therefore changes to these will have to be made to the private attributes `_data` and `_meta`.

**Comment by gcetusic** [comment]
@Cadair Hi, I'm a potential GSOC student and would like to working on this issue because it's marked as Novice. I haven't had experience with SunPy until now but have a lot of experience in Python. Mind if I take a stab at this?

**Comment by Cadair** [comment]
@gcetusic please feel free! If you want a hand, I will be in IRC.

**Comment by gcetusic** [comment]
@Cadair I have a suggestion. Astropy already 90% of the stuff NDDaataCompat has except 2 setters. Rather than changing a million files to use _meta and _data, why not send a PR to astropy that adds the two setters required to make sunpy work, wait until it gets merged and THEN remove the compatibility layer along with bumping the astropy requirement to whichever version it'll be on pypi? It's obviously been done before and I've tried just adding @meta.setter and @data.setter to astropy and all tests pass.
A lot of code accesses meta and data attributes so it doesn't make sense to access them as 'private' variables.

**Comment by Cadair** [comment]
@gcetusic The compatibility layer is there as a way of supporting old code. The new API design for Astropy is the API we should aim to support. Correct me if I am wrong, but the most common place where we set the value of `.meta` and `.data` is when we are copying an object so that we can modify it. It might be a good idea to wrap that operation in a helper function.

On another note, the reason the new astropy API dosen't allow setting the meta and data attributes is that the philosophy behind it is that it is immutable once it is created, and we should discourage users from changing the NDData object in that way.

**Comment by sunilk747** [comment]
@Cadair  Is this issue has been solved ?

**Comment by Cadair** [comment]
@sunilk747 no this still needs fixing.

**Comment by abit2** [comment]
@Cadair Can you please explain how the compatibility layer works. I would like to work on this.

**Comment by Cadair** [comment]
Basically the issue is that the old NDData API had the ability to set `.data` and `.meta`the new one doesn't.

All instances of assigning to .data and .meta need to be replaced. The basic replace operation would be replacing `data` and `meta` with `_data` and `_meta` however, it would be better if instead of doing the copy operation we created a new Map object with the modified data and meta instead, if that makes any sense?

**Comment by abit2** [comment]
So removing the setters of data and meta should it, right?
