### ISSUE TITLE
Two GOES test fail due to default behaviour of sun-earth distance calculation.

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1307]
The tests 

test_goes_lx_nokwargs

and

test_goes_lx_obstime

are failing due to the time-dependent calculation of goes._goes_lx  .  These tests call goes._goes_lx with date=None.  This eventually causes goes._calc_xraylum to be called with date=None, which means the sun.sunearth_distance gets called with its default value, t='now', which passes in the current UT time.  This means that the tests are time dependent, and therefore will only pass at most twice a year.

Suggested fixes: make date required for  goes._calc_xraylum.  Also make time a required parameter for all the functions in the sun.sun module.  Finding the value of these functions at the current UT would still be easily possible through passing in the current UT explicitly, i.e., sun.print_params(parse_time('now')).

**Comment by Cadair** [comment]
ping @danryanirish

The goes tests need changing, the changes to `sunpy.sun` would need to be considered, to see if that would break API anywhere else.

**Comment by DanRyanIrish** [comment]
OK.  I'll look into this tomorrow.

**Comment by DanRyanIrish** [comment]
@wafels @Cadair I think the best solution is to use ```sunpy.sun.constants.au``` when no date is input.  This should give the mean value of 1AU when the user does not want to specify or does not care about the time.  This was in fact the original intention of the function.  Then these tests can be made the pass consistently again.  Is there any reason why this might not be a good fix?

**Comment by Cadair** [comment]
@DanRyanIrish makes sense to me as long as it is made clear what it is defaulting to.

**Comment by wafels** [comment]
@DanRyanIrish I agree with the proposed solution. And I agree with Stuart
that it should be clear what the default is, and what it means. Thanks!

**Comment by aringlis** [comment]
Close?

**Comment by wafels** [comment]
I think has been fixed. See
https://github.com/sunpy/sunpy/commit/43f7a037bc5c88cd2c1bec6c70b4dc27f82c6d03

**Comment by DanRyanIrish** [comment]
Yep.  @wafels is right.
