### ISSUE TITLE
sunpy.lightcurve.GOESLightCurve.create() broken

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#1320]
Hi guys,
I've discovered that ```sunpy.lightcurve.GOESLightCurve.create()``` is currently raises a ```ValueError``` when you call it without an input because it is trying to read the GOES fits file for 2015 March 6 which doesn't exist.  I haven't able to find where the the ```.create``` attribute is written and so haven't been able to understand what it does when you don't give it input, and hence fix it.  Any suggestions?

**Comment by Cadair** [comment]
Should be in `_get_default_uri` or similar in goes.py

**Comment by ehsteve** [comment]
@DanRyanIrish let's get rid of this functionality ``_get_default_uri``. Also I would vote that we get rid of ``create`` as well if anyone has time to do it.

**Comment by Cadair** [comment]
@ehsteve we can get rid of `create` when we write a factory. As for `_get_default_uri` we can remove it in 0.6 but we should fix it in 0.5.

**Comment by aringlis** [comment]
I also vote for removing the _get_default_uri functionality in 0.6.

**Comment by DanRyanIrish** [comment]
Fine by me, so long as we fix it for 0.5.

**Comment by Rishabhmishra328** [comment]
Hi,
Is this issue fixed? because i called the create method with no value input and it didn't give any value error.

**Comment by aringlis** [comment]
I think the PR to fix this is still open (#1361). Probably on the occasion you tried it you didn't receive a value error because the file you requested was actually available - it depends on what the lag time is for data files appearing on the GOES data server.

**Comment by aringlis** [comment]
I think this can be closed.
