### ISSUE TITLE
Setup a SunPy affiliated package template

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1321]
Astropy have a very successful affiliated package system, which will also work very well in the solar physics community. Seeing how we use astropy packaging for SunPy, we should probably make a version of the astropy affiliated package template for SunPy https://github.com/astropy/package-template/, because imitation is the highest form of flattery.

The task will be to remove the astropy branding and replace with SunPy branding. Also the layout of the astropy documentation is a little different to the way we have approached it with SunPy so it should be easy to adopt either layout (separate or integrated API docs).

I have made this repository https://github.com/sunpy/package-template which is a copy of the astropy one.

**Comment by mdmueller** [comment]
Seeing as AstroPy has the [astropy-helpers](https://github.com/astropy/astropy-helpers) repo, do we want to simply use that or create a SunPy repo named sunpy-helpers?

**Comment by Cadair** [comment]
@mdmueller we will be using astropy-helpers (as sunpy does now). The package template is a boilerplate for other pacakges to put things like setup.py and sphinx inplace.

**Comment by souravsingh** [comment]
I will work on the issue.

**Comment by laxmena** [comment]
Can I work on this issue ?

**Comment by laxmena** [comment]
Is this issue still open? Can I work on it?

**Comment by Cadair** [comment]
@laxmena yes, you could work on this. I think what is needed is an excellent set of documentation on how to set up an affiliated package using the Astropy template: https://github.com/astropy/package-template/ but changing the branding to be SunPy and also documenting some of the information in https://github.com/sunpy/sunpy-SEP/blob/master/SEP-0004.md
