### ISSUE TITLE
sunpy.net.download.download() failing silently

### ISSUE THREAD

**Issue by ghost** [sunpy/sunpy#1331]
The `download` function in sunpy.net.download fails silently if unable to download file. It should either throw an error and stop execution or at least log this error occcurence somewhere. Reference at: https://github.com/sunpy/sunpy/blob/master/sunpy/net/download.py#L61

**Comment by sunilk747** [comment]
Hello rajul, I would like to work on this issue.

**Comment by rajul** [comment]
@sunilk747 of course, you are more than welcome to take a look and work at this.....you will be required to fix things here....
https://github.com/rajul/sunpy/blob/download_different_filenames/sunpy/net/download.py#L61

**Comment by Rishabhmishra328** [comment]
@rajul hey, can you tell me what this function downloads? And when it is run?

**Comment by rajul** [comment]
@Rishabhmishra328 As you can see, it part of the sunpy.net.Downloader class, any call for downloading files fallback to this class for ultimately multi-threaded downloading of files to the local machine, from the various sources supported in the sunpy.net module like VSO, HEK, etc.

**Comment by wafels** [comment]
This one is pretty annoying.  We need to keep a track of which files have a successful download.  Files that have not been successfully downloaded can have multiple attempts at downloading with some limit (that the user can set but has some small-value default).  If at the end of it all some files have not been downloaded, the .get should return a list of query objects that refer to those non-downloaded files so the user can do something with them.
