### ISSUE TITLE
Add guide for rebasing in the developer section

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1339]
You want it so teach us!

**Comment by nabobalis** [comment]
We can just link to rebase guides?

**Comment by Cadair** [comment]
I thought you added a section on this already? and yes we should link things.

**Comment by nabobalis** [comment]
I couldn't find the word rebase in the docs.

**Comment by Cadair** [comment]
maybe it's in a PR, or maybe I am dreaming of SunPy doc PRs now...

**Comment by dpshelio** [comment]
It's in #2561 - though by the title doesn't seem obvious.

**Comment by nabobalis** [comment]
It is in a PR now, there wasn't any before that I could find. 

That title is deliberate.
