### ISSUE TITLE
database complains of EIT non-existent wavelengths units

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1342]
Without any reason I've been able to find, `database.fetch` fails with some EIT files... not always the same, with the following error message:
```
WaveunitNotFoundError: the wavelength unit cannot be found in ~/sunpy/data/efz20000912.203610
```
That was from this query:
```python
db.fetch(vso.attrs.Time('2000/9/12T20:30:00', '2000/9/12T22:00:00'),
vso.attrs.Instrument('EIT'))
```

**Comment by Cadair** [comment]
@dpshelio yes, some EIT data does not have waveunit info in the header, you need to init the database with the `default_waveunit` kwarg.

**Comment by dpshelio** [comment]
That's right! Thanks @Cadair

**Comment by Cadair** [comment]
We should probably document this better, if even you didn't work it out. Maybe even change the error message.

**Comment by dumindux** [comment]
@Cadair How about we change the exception message to "the wavelength unit cannot be found in xxxx and deffault_waveunit not specified" ?

**Comment by Cadair** [comment]
@dumindux Yeah that sounds good. Maybe say "the wavelength unit cannot be found in xxxx and deffault_waveunit not specified when opening the database"

**Comment by dumindux** [comment]
Changed the error message :).
