### ISSUE TITLE
Fix the mpl_normaliser in Map

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1370]
Currently in `__init__` `_get_default_mpl_normalizer` is called to set up the default image norm. What should happen is that we should have a property called `mpl_normalizer` which calls the `_get_default_mpl_normaliser` method and provide a setter for the property which sets a private variable which defaults to `None` and the property checks for and returns if present (as opposed to doing the computation).

**Comment by Cadair** [comment]
ping @alex_ian_hamilton

**Comment by Cadair** [comment]
Also, we should make the property default to returning a linear `Normalize` instance between the min and max of the data, to make the API the same over all sources.

**Comment by sunilk747** [comment]
Hello 
If this issue has not been solved I would like to work on it.

**Comment by Cadair** [comment]
@sunilk747 This has been fixed, well at least made redunadant by other changes.
