### ISSUE TITLE
Lightcurve data files can contain out-of-order elements, leading to a crash in LightCurve with KeyError

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#1371]
Data files (e.g. GOES, LYRA) for lightcurves are not always written with the data elements in sequential order, ie. the time data may not be monotonically increasing. 

This causes a crash in lightcurve creation because the pandas.truncate() method gets called on the newly-created pandas Dataframe. If the Dataframe elements are not in sequential order, this function will crash with a KeyError (see #1337).

For example:

```
from astropy.io import fits
import pandas
import datetime
from numpy import floor
from sunpy.time import parse_time
import numpy as np

hdu = fits.open('go06850317.fits')
h1 = hdu[0]
xrsb = h1.data[2,:]
xrsa = h1.data[1,:]
start_time = parse_time(h1.header['TIMEZERO'])
times = [start_time + datetime.timedelta(seconds=int(floor(s)),
        microseconds=int((s - floor(s)) * 1e6)) for s in seconds_from_start]
dat = pandas.DataFrame({'xrsa': xrsa, 'xrsb': xrsb},index = times)
```

and then:

```
test = dat.truncate(parse_time('1985-03-17 02:00'),parse_time('1985-03-17 04:00'))
ERROR: KeyError: 479872800000000000 [IPython.core.interactiveshell]
```

You can see that the time indices are out of order:

```
difftimes = times[1:-1] - times[0:-2]  
np.min(difftimes) 
Out[76]: -6.0    
```

What happens is that the indices in the pandas dataframe need to be in sequential order for the pandas truncate function to work, otherwise it throws this (pretty unhelpful) KeyError. This can be worked around by sorting the Dataframe first, e.g.

```
dat.sort(inplace=True)
test = dat.truncate(parse_time('1985-03-17 02:00'),parse_time('1985-03-17 04:00'))
```

I think this can be solved easily by adding a dat.sort(inplace=True) command where the dataframe is first created. Usually this is in the _parse_fits function of whatever source is being used.

**Comment by wafels** [comment]
Do you have a LYRA example?

**Comment by aringlis** [comment]
Actually no - I shouldn't have singled out LYRA, I don't have an example of it. But, in principle it could be an issue for any lightcurve source.

**Comment by Rishabhmishra328** [comment]
@aringlis @dpshelio 
Can you please review this request?
Thanks.

**Comment by aringlis** [comment]
Re-opened this a while back due to #1508  - @hayesla any interest in tackling this one? We should fix this for all lightcurve sources.

**Comment by hayesla** [comment]
Yep, I'll give it a go, I've already fixed it for Fermi in my own branch, I'll take a look at the others too.
