### ISSUE TITLE
Callisto test failures

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1376]
The `test_download` test in `sunpy/spectra/tests/test_callisto.py` is failing with the following traceback:

``` python
    @pytest.mark.online
    def test_download():
        directory = mkdtemp()
        try:
            result = query(
                datetime(2011, 9, 22, 5), datetime(2011, 9, 22, 6), set([("BIR", 1)])
            )
            RESULTS = [
                "BIR_20110922_050000_01.fit.gz",
                "BIR_20110922_051500_01.fit.gz",
                "BIR_20110922_053000_01.fit.gz",
            ]
>           download(result, directory)
sunpy/spectra/tests/test_callisto.py:108: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sunpy/spectra/sources/callisto.py:105: in download
    return [download_file(url, directory) for url in urls]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
start = datetime.datetime(2011, 9, 22, 5, 0)
end = datetime.datetime(2011, 9, 22, 6, 0), instruments = set([('BIR', 1)])
url = 'http://soleil.i4ds.ch/solarradio/data/2002-20yy_Callisto/'
    def query(start, end, instruments=None, url=DEFAULT_URL):
        """ Get URLs for callisto data from instruments between start and end.

        Parameters
        ----------
        start : parse_time compatible
        end : parse_time compatible
        instruments : sequence
            Sequence of instruments whose data is requested.
        url : str
            Base URL for the request.
        """
        day = datetime.datetime(start.year, start.month, start.day)
        while day <= end:
            directory = url + day.strftime('%Y/%m/%d/')
            opn = urllib2.urlopen(directory)
            try:
                soup = BeautifulSoup(opn)
                for link in soup.find_all("a"):
                    href = link.get("href")
                    for prefix, parser in PARSERS:
>                       if href.startswith(prefix):
E                       AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by dumindux** [comment]
@Cadair @ehsteve I have run this test in my local environment(master branch) and it seemed to pass. Are there any specific conditions for this to fail?

**Comment by ayshih** [comment]
I can't reproduce it locally either.  Has this test ever succeeded on Travis?  From a cursory look, it appears as if BeautifulSoup is finding an anchor tag (`<a>`) that doesn't contain an `href` URL.  This suggests that the server is providing a different page to Travis, possibly a 30x or 40x return page?

Loosely related code comments from looking at the traceback:
* The docstring claims that `query()` accepts `parse_time`-compatible inputs, but the code immediately assumes that they are already `datetime` objects.
* Shouldn't `urlparse.urljoin()` be used to build URLs rather than just concatenating strings?

**Comment by ehsteve** [comment]
I concur. Let's just xfail for this 0.6. Cool?

**Comment by ehsteve** [comment]
Created a PR to ignore this for now to enable the release of 0.6 (#1380).

**Comment by ayshih** [comment]
Ugh, a different Callisto test (`test_extend`) failed on a recent Travis run (https://travis-ci.org/sunpy/sunpy/jobs/58267452).  I'm guessing that the Callisto webserver sometimes times out or returns garbage.  The Callisto `query()` function needs to have some form of error-catching!

**Comment by Cadair** [comment]
I am going to leave this open, to promote a long-term solution.

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#4
