### ISSUE TITLE
24 failures from selft_test on OS X local install

### ISSUE THREAD

**Issue by SamuelTun** [sunpy/sunpy#1387]
Hello,
I installed SunPy on a fresh and upgraded Anaconda Python install, using OS X Mavericks. Everything seemed to go ok, then I ran sunpy.self_test(). I attach image of the entire output of that test. It gives me several errors, some of which I do see are noted (like the Callisto self test issue). However, there are several more I wasn't able to find a discussion on so I post in the hopes that someone could tell me if the install is OK and there are only errors in accessing the test databases, or something simple like that. 

Couldn't find a post with the same errors I get, so am posting as a new issue. Did find something similar for Windows install but it has been resolved, as opposed to my issue. 

![slftstout](https://cloud.githubusercontent.com/assets/11927512/7121352/fe1511f4-e1e1-11e4-9476-57a0cb93d56b.png)

**Comment by Cadair** [comment]
@SamuelTun Thanks for the bug report. It looks like most of these failures are the online tests, which might fail if the server side behaviour changes.

The first thing to try is to run the offline tests only:

```python
import sunpy.tests
sunpy.self_test(online=sunpy.tests.EXCLUDE_ONLINE)
```

If that doesn't pass it is probably a real bug in SunPy / your install. (This is going to be the default behaviour for `self_test` in 0.6).

**Comment by SamuelTun** [comment]
Thank you much, Cadair. You are correct, as the offline tests all passed. I had tried the offline test before, as explained in http://docs.sunpy.org/en/latest/guide/installation/advanced.html#testing-sunpy
but it didn't work so I thought I'd go ahead with a full test. Now I see what the real code should have been. 
Thanks again
