### ISSUE TITLE
Installation of SunPy can unnecessarily trigger NumPy build

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1396]
Context: I normally perform a developer installation of my local SunPy repo using `pip install -e .`.

It looks like the keyword argument `setup_requires=['numpy>1.7.1']` in our `setup.py` can trigger a from-source build of NumPy even if the dependency is already satisfied.  From my brief investigation, it looks to be a result of quirks in NumPy's setup and setuptools.  See this detailed post from NumPy's issue tracker: https://github.com/numpy/numpy/issues/2434#issuecomment-77898051.  Despite what is claimed in that issue, I'm still having the issue with setuptools 15.1.

My workaround is to comment out the `setup_requires` if the dependency is already known to be satisfied.

This bug may not crop up depending on installation history (i.e., the order that modules were installed/upgraded) – I didn't encounter it when I initially installed SunPy on this machine – and I don't know whether it affects other ways of installation (developer or otherwise).

**Comment by Cadair** [comment]
The setup_requires has been removed now.
