### ISSUE TITLE
TimeRange duration methods are not consistent 

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1397]
`TimeRange` has several methods to retrieve the elapsed duration: `days()`, `minutes()`, and `seconds()`.  However, the first of those three only returns the number of *full* days elapsed (i.e., fractional days are ignored).  This seems silly.

```python
>>> from sunpy import TimeRange
>>> t1 = datetime(2000, 1, 1)
>>> t2 = datetime(2000, 1, 2, 0, 0, 30, 75)
>>> tr = TimeRange(t1, t2)
>>> tr.days()
1
>>> tr.minutes()
1440.50000125
>>> tr.seconds()
86430.000075
```

On a related note, why is there no `hours()`?

**Comment by ayshih** [comment]
Oops, I was on the `0.5` branch.  I don't know whether it'd be appropriate to make such a change of behavior on the stable branch.  Perhaps it would be better to simply add clarifications to the docstrings for the methods (and tweak the `__repr__` too).

**Comment by antonio19812** [comment]
so should we add hours, could be a task?

**Comment by anchitjain1234** [comment]
Is it still an issue? Because now it is working correctly.
