### ISSUE TITLE
HEK event properties returned as the appropriate SunPy object

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1398]
The required properties of the HEK events

http://www.lmsal.com/hek/VOEvent_Spec.html

should be returned as the appropriate SunPy object where possible.  This will make HEK events play better with the rest of SunPy.

**Comment by Cadair** [comment]
do they actually return VOTables?

**Comment by wafels** [comment]
I spoke to someone involved with running the HEK and apparently they return a VOEvent with some tweaks.  There is also a file somewhere that specifies the types of data that are returned for each event property.

**Comment by nabobalis** [comment]
Superseded by #5006
