### ISSUE TITLE
improve the JSOC documentation or the API

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1399]
As dicussed [on the mailing list](https://groups.google.com/d/topic/sunpy/KoB5dVnj-EA/discussion) certain queries to JSOC needs some "hacking" on the way to make it to make it work.

For example, if we want to query SHARP data products we need to  do a query such the harpnumber field is inserted after the series:

```
response = client.query(jsoc.Time('2014-01-01T00:00:00', '2014-01-01T01:00:00'), jsoc.Series('hmi.sharp_720s[3535]'))

```

or empty if we don't know it we could do:

```
response = client.query(jsoc.Time('2014-01-01T00:00:00', '2014-01-01T01:00:00'), jsoc.Series('hmi.sharp_720s[]'))

```

Another query but imputing another field that is not a primary field we could do:

```
response = client.query(jsoc.Time('2014-01-01T00:00:00', '2014-01-01T01:00:00'), jsoc.Series('hmi.sharp_720s[? NOAA_AR=11936 ?][]'))
```

A solution to this issue, to have a better API could be to label all the fields with they key,value pair, so it is not position dependent, in a way that:

``` python
response = client.query(jsoc.Time('2014-01-01T00:00:00', '2014-01-01T01:00:00'), jsoc.Series('hmi.sharp_720s'),harpnum=3535))
```

produces a query like:

```
hmi.sharp_720s[T_REC=2014.01.01_00:00:00_TAI-2014.01.01_01:00:00_TAI][HARPNUM=3535]'
```

If the harpnum field is not imput it would provide all the harpnum available for these dates.

**Comment by dpshelio** [comment]
We need to keep in mind the [document that explains how the DRMS format](http://hmi.stanford.edu/doc/JSOC/DRMS_dataset_names.pdf) works. Catalogues and DSDS are or not implemented or obsoleted (Phil on the mailing list).

**Comment by nabobalis** [comment]
I think this is kind of solved with the jsoc attrs and we have more documentation pages on the JSOCCient and via the DRMS package.
