### ISSUE TITLE
HEK default spatial extent is too small to report CME detections

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1411]
A user has reported that no CMEs are returned when searching for CMEs using the HEK client.  The problem seems to be that the default spatial extent attribute is too small to encompass the spatial location of CMEs held by the HEK.

https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/attrs.py#L120-L129
(see also https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L38-L52)

The SSWIDL HEK client reports the same number of results (i.e., none) when the search is restricted to the SunPy spatial extent.  The fix is to change the default spatial extent.

**Comment by wafels** [comment]
See also https://github.com/sunpy/sunpy/blob/master/tools/hektemplate.py

**Comment by ayshih** [comment]
Original email thread: https://groups.google.com/forum/#!topic/sunpy/iJIQC5sWnjg
