### ISSUE TITLE
Convert Sample files to named tuple instead of module parameters

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1417]
This would allow people to do a for loop over all of the files if needed and would be cleaner code for developers.

**Comment by Cadair** [comment]
true, but this would not work:

```python
from sunpy.data.sample import AIA_171_IMAGE
```

**Comment by ehsteve** [comment]
That's true. Maybe we should just create another variable that is a named tuple so you can import that like

```from sunpy.data.sample import files```
