### ISSUE TITLE
Need consensus on axes names for Map properties

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1422]
See PR #1416 for much relevant discussion

Map properties with values for each axes are (currently) named tuples with the field names `.x` and `.y` for the two axes of the Map.  It has been suggested that other names may be appropriate given that maps may not have an "X" axis or "Y" axis or, in an extreme case, have the "X" and "Y" axes swapped.  Here is the current explanation in the docstring:

```
A number of the properties of this class are returned as two-value named
tuples that can either be indexed by position ([0] or [1]) or be accessed by
name (.x or .y).  The names "x" and "y" here refer to the first and second
axes of the map, and may not necessarily correspond to any similarly named
axes in the coordinate system.
```

Here are some alternative naming conventions that have been suggested (again, see #1416 for discussion):

```
a1 a2
x1 x2
lat lon
h v
first second
xaxis yaxis
xax yax
```

**Comment by Cadair** [comment]
My vote is for `xaxis` and `yaxis` as in #1416.

**Comment by Cadair** [comment]
#1975 proposes a change to this, but it's not in it's final form.
