### ISSUE TITLE
Add support for DISCOVR data

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1442]
More than 100 days after it launched, NOAA’s Deep Space Climate Observatory (DSCOVR) satellite has reached its orbit position about one million miles from Earth.

Once final instrument checks are completed, DSCOVR, which will provide improved measurements of solar wind conditions to enhance NOAA’s ability to warn of potentially harmful solar activity, will be the nation’s first operational space weather satellite in deep space. Its orbit between Earth and the sun is at a location called the Lagrange point 1, or L1, which gives DSCOVR a unique vantage point to see the Earth and sun.

DISCOVR includes the the Plasma-Magnetometer (PlasMag) which measures solar wind activity, including the magnetic field and the velocity distribution (magnitude and direction) of solar wind particles with higher time resolution than existing instruments.

PlasMag is a comprehensive space weather suite consisting of three parts: (1) a fluxgate vector Magnetometer, (2) a Faraday Cup solar wind positive ion detector and (3) a top-hat Electron Spectrometer.

Working on getting info on this.

**Comment by dstansby** [comment]
This would be quite a nice addition to HelioPy if SunPy doesn't mind it being stolen. Last I remember trying to get DISCOVR data it involved a horrible online form though, so I'm not too sure how easy it'll be to automate downloading the data.

**Comment by dstansby** [comment]
We've started adding support in HelioPy (https://github.com/heliopython/heliopy/pull/546), so I guess this can be closed?

**Comment by Cadair** [comment]
I think we had some WIP support for this somewhere? @Punyaslok ?
