### ISSUE TITLE
Auto-generate images for docs

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#1455]
@Cadair - Have you considered generating the images rather than using the canned version in the docs? I mean if something changes in the code the users may get a different results following the examples than what is shown there.

I'm looking at e.g. ``doc/source/guide/data_types/spectra.rst``

**Comment by Cadair** [comment]
It would be good to do.

**Comment by ehsteve** [comment]
I agree. I've been wanting this for a long time now.

**Comment by Cadair** [comment]
I am not particularly up on the sphinx magic. Is this easy enough to do?

**Comment by bsipocz** [comment]
It's pretty easy, we do it with e.g. ``photutils``, too.

It's just pasting the plotting script (a full one) after a ``.. plot::``
instead of the ``.. image::``
I'll give it a try in ``spectra.rst`` while I'm at it.

**Comment by ehsteve** [comment]
@bsipocz might be easier to start out with maps.rst as spectra is the most beta of the datatypes.

**Comment by ehsteve** [comment]
@bsipocz I am actually working on updating that file right now. Can you show me how to add the code to the docs so that this works? Thanks.

**Comment by Cadair** [comment]
@ehsteve I suggest we do this in a separate PR ;)

**Comment by ehsteve** [comment]
well i am writing the code to generate new images right now anyway sooooo...

**Comment by Cadair** [comment]
well you should include the code in the docs anyway. So surely the only thing that would need to change for the autogenerated images is to use the magic sphinx incantation and delete the included file.

I will however leave it up to you ;)

**Comment by ehsteve** [comment]
@Cadair that's fine. you are right. no need to bloat this PR anymore than it already is.

**Comment by bsipocz** [comment]
Here is an example at the bottom of this [file] (https://raw.githubusercontent.com/astropy/photutils/master/docs/photutils/getting_started.rst)  Basically it needs to be a standalone script (unlike for the doctest, here it's not enough that all the statements were in the code examples above). Obviously there can be several separate plot code blocks, but all of them has to be a self contained script with all the imports, etc..


Rendered version: http://photutils.readthedocs.org/en/latest/photutils/getting_started.html

**Comment by Cadair** [comment]
Interesting, where does the `plot` directive live? I wonder if we are going to need to enable it in our sphinx `conf.py` or if it is included from the astropy version we inherit.

Thanks a lot for your help @bsipocz!

**Comment by bsipocz** [comment]
in photutils it goes under ``docs/_build/html/_images/``, so I guess it
will be ``doc/source/_build/html/_images`` for sunpy. I guess it works out
of the box, but haven't tried it yet.

Btw it's a bit confusing that the builded docs goes under the source
directory...

**Comment by bsipocz** [comment]
ahh, sorry I misunderstood. ``plot`` is a matplotlib extension. This should work out of the box with the astropy_helpers.

**Comment by bsipocz** [comment]
and it works:
![screen shot 2015-06-18 at 15 46 19](https://cloud.githubusercontent.com/assets/6788290/8233990/3e329cf2-15d1-11e5-8ba8-ea29be60442e.png)

**Comment by Cadair** [comment]
amazing!!

**Comment by ehsteve** [comment]
Great!

**Comment by ehsteve** [comment]
@bsipocz Could you submit a PR for this (I would encourage you to also fix the location of the _build directory if you can as well)? That way I can use it in my PR.

**Comment by Cadair** [comment]
what exactly is wrong with the location of the _build dir?

**Comment by ehsteve** [comment]
@Cadair it is inside source which is weird because it is obviously not source.

**Comment by Cadair** [comment]
That is more a problem with the directory being called source than anything else. It is just the root Sphinx dir.

If you want to move it I suggest it gets done separately. As there is quite a lot of things that would need changing.

**Comment by ehsteve** [comment]
@bsipocz I've started using this new feature #1432 :)

**Comment by bsipocz** [comment]
:+1:

**Comment by bsipocz** [comment]
@ehsteve - look what I've found. If you use the ``:include-source:`` option after ``.. plot::``, the source is included in the generated docs, no need to repeat it.

**Comment by Cadair** [comment]
@ehsteve can this be closed now?

**Comment by ehsteve** [comment]
yes
