### ISSUE TITLE
Enabling the astropy_helpers doctest directives

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#1456]
Somehow I cannot make the doctest directives from `astropy_helpers`, such as `doctest-skip` work with sunpy. I guess it is related to using a different test suite setup, etc.
I tried to add `astropy_helpers.sphinx.ext.doctest` as an extension, but it didn't solve it.

Anyway a workaround until it's solved is to add `#doctest: +SKIP` to the end of each affected line.

**Comment by bsipocz** [comment]
The most important/useful directive would be ``+FLOAT_CMP``, of course.

**Comment by Cadair** [comment]
I do not really know anything about this. Let's ask @astrofrog or @embray nicely if they know how to solve this?

**Comment by astrofrog** [comment]
Did you add ``doctest_plus = enabled`` in ``setup.cfg``?

**Comment by bsipocz** [comment]
Yes, that was the first thing I tried, still not picking them up. 

If my understanding is right, sunpy overrides the astropy/astropy_helpers testing scheme and uses it's own. There is also a ``pytest.ini``, and I can't make the testing to pick up the doctests the usual way at all, but can only run them separately with this hack: ``python setup.py build_sphinx -b doctest``, or individual file with ``python -m doctest filename``.

**Comment by Cadair** [comment]
have you tried removing this line: https://github.com/sunpy/sunpy/blob/master/pytest.ini#L4 ?

**Comment by nabobalis** [comment]
Superseded by #2381
