### ISSUE TITLE
Weak time limit in sunpy.spectra.sources.callisto

### ISSUE THREAD

**Issue by itztli** [sunpy/sunpy#1466]
Hi all!

I am working with Callisto dynamic spectra. I am join several file spectrum using the example from the API:

import sunpy.spectra
from sunpy.spectra.sources.callisto import CallistoSpectrogram
c0 = CallistoSpectrogram.read(path+'fits/20150618/MEXART_20150618_170000_59.fit')
c1 = CallistoSpectrogram.read(path+'fits/20150618/MEXART_20150618_171500_59.fit')
c2 = CallistoSpectrogram.read(path+'fits/20150618/MEXART_20150618_173000_59.fit')

d = CallistoSpectrogram.join_many([c0,c1,c2])
nobg = d.subtract_bg()
nobg.peek(vmin=0)

However, I got the following error:

Traceback (most recent call last):
  File "./plot-spectrum.py", line 39, in <module>
    d = CallistoSpectrogram.join_many([c0,c1,c2])
  File "/usr/local/lib/python2.7/dist-packages/sunpy-0.7.dev5723-py2.7-linux-x86_64.egg/sunpy/spectra/spectrogram.py", line 972, in join_many
    raise ValueError("Too large gap.")
ValueError: Too large gap.

The interval time is only of 45 minutes. Actually, the size of each file is around 700 Kb.

**Comment by Cadair** [comment]
ping @dpshelio @segfaulthunter

**Comment by segfaulthunter** [comment]
Will look at after work.

**Comment by segfaulthunter** [comment]
max_gap defaults to 0. If you want the gaps to be left out, specify `nonlinear=True`. Otherwise, you can specify maxgap to be larger than 0 and and it automatically fill the gap by repeating the nearby data-points. To change this behaviour, set `fill` to whatever sentinel value you want.

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#5
