### ISSUE TITLE
Add ability to download files from AIA cutout service

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1469]
Here is the equivalent IDL code 

http://darts.isas.jaxa.jp/pub/ssw/vobs/ontology/idl/ssw_service_get_data.pro

and here is a page with actual data and the code used to download the data.

http://www.lmsal.com/solarsoft/ssw_service/queue/finished/ssw_service_150623_062824_33488.html

**Comment by Cadair** [comment]
you can do this through JSOC right? Also is there not already an issue for this?

**Comment by Cadair** [comment]
duplicate of #1259

**Comment by ehsteve** [comment]
No, this is not related to JSOC. Thanks for noticing the duplicate.

**Comment by Cadair** [comment]
@ehsteve I know there is a separate service, but JSOC can also do AIA & HMI cutouts.

**Comment by Cadair** [comment]
see #1259 for a similar discussion with @wafels
