### ISSUE TITLE
Remove PowerNorm

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1485]
PowerNorm was only included matplotlib 1.4. The solution is to use astropy PowerStretch

http://astropy.readthedocs.org/en/latest/api/astropy.visualization.PowerStretch.html#astropy.visualization.PowerStretch

**Comment by ayshih** [comment]
This would sove #1484

**Comment by ehsteve** [comment]
Currently being used in
* maps.rst
* soho.py
* stereo.py
* yohkoh.py
