### ISSUE TITLE
Doc fix installation+others guides

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1487]
* [Installation](http://docs.sunpy.org/en/latest/guide/installation/index.html)
* [Customizing SunPy](http://docs.sunpy.org/en/latest/guide/customization.html)
* [Troubleshooting](http://docs.sunpy.org/en/latest/guide/troubleshooting.html)

**Comment by ehsteve** [comment]
@ayshih make sure to add some instruction on how to rebase.

**Comment by ayshih** [comment]
> @ayshih make sure to add some instruction on how to rebase.

That should fall in `dev.rst`, which is part of #1490, not this issue

**Comment by ehsteve** [comment]
Done.
