### ISSUE TITLE
Doc fix misc

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1490]
* tour.rst
* plotting.rst
* roi.st
* time.rst
* dev.rst
* ssw.rst

**Comment by ayshih** [comment]
For `ssw.rst`, note that there's a superfluous `exp(1)` and that some of the matched commands have blatant disregard for number types.

**Comment by aringlis** [comment]
Also, technically there is nothing about SSW in the SSW section (it's all just IDL...)
