### ISSUE TITLE
Spectra time_freq bug

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1492]
The following code does not work

``` python
    import sunpy.data.sample
    from sunpy.spectra.sources.callisto import CallistoSpectrogram
    image = CallistoSpectrogram.read(sunpy.data.sample.CALLISTO_IMAGE)
    fig = image.peek()
    time_freq = fig.time_freq()
    time_freq.peek(marker='o', linestyle='--')
```

It fails with the following error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-2df93fded4b2> in <module>()
----> 1 time_freq = fig.time_freq()

AttributeError: 'AxesSubplot' object has no attribute 'time_freq'

In [24]:     time_freq.peek(marker='o', linestyle='--')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-24-c2c0d9acc518> in <module>()
----> 1 time_freq.peek(marker='o', linestyle='--')

NameError: name 'time_freq' is not defined
```

**Comment by ayshih** [comment]
Hmm, curious implementation.  The code snippet is expecting `peek()` to return a `SpectroFigure` object rather than a normal matplotlib figure, but instead it returns axes (via `plot()`).  This is a mess, and clearly no one has been using this functionality.

**Comment by Cadair** [comment]
we should make `peek()` return the `SpectroFigure` object, because that is the way it was built. Of course it can be re-engineered at some point.

**Comment by agneet42** [comment]
I've been trying my way around this. Is [this](https://github.com/sunpy/sunpy/blob/master/sunpy/spectra/spectrogram.py#L179) `return` statement, where we're expecting a SpectroFigure object to be returned instead of `figure` ?

**Comment by agneet42** [comment]
@Cadair  [this](https://github.com/sunpy/sunpy/blob/master/sunpy/spectra/spectrogram.py#L244) needs to return a `SpectroFigure` , in place of the matplotlib figure, if I am not mistaken?

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#6
