### ISSUE TITLE
Move the travis build onto the docker infrastructure.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1494]
see: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

The important bit is getting the ubuntu packages installed.

ping @mwcraig @astrofrog

**Comment by mwcraig** [comment]
@Cadair -- this is implemented for astropy in astropy/astropy#3944

The list of apt packages you can install is at: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Comment by Cadair** [comment]
@mwcraig thanks for the info.

**Comment by bsipocz** [comment]
This can be closed now.
