### ISSUE TITLE
The recent changes to norm seem to break helioviewer jp2 files 

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1495]
hello,

I have this code snippet in my Thesis and the colour scaling seems wrong for these JPEG 2000 images:

``` python
from sunpy.net import helioviewer
from sunpy.time import parse_time
import sunpy.map

hv = helioviewer.HelioviewerClient()
filepath = hv.download_jp2('2015/12/31 00:00:00', observatory='SDO',
                           instrument='AIA', detector='AIA', measurement='171',
                           directory=ch1.data_dir)
# Add the file to the pytex data
ch1.pytex.add_created(filepath)

aia171 = sunpy.map.Map(filepath)
fig = aia171.peek(basic_plot=True)
```

![jpeg2000_aia](https://cloud.githubusercontent.com/assets/1391051/8670525/d1480a24-2a15-11e5-981a-873fb4f1d4c1.png)

**Comment by wafels** [comment]
Compared to the FITS file values, the actual image values in all
Helioviewer JPEG2000 files are clipped, nonlinearly-scaled so they look
good (for some value of good), then byte scaled and heavily compressed. The
assumptions behind the new color normalization do not apply to Helioviewer
JPEG2000 files.  I think we need a whole new set of colormaps just to make
Helioviewer images look good in SunPy.

I'd say that this is a bug that does not block the release of SunPy 0.6.  I
can generate RGB values from the Helioviewer code that should work.  A
bugfix for 0.6.1 !

**Comment by Cadair** [comment]
@wafels yeah, this needs some thought, I agree that it is not critical though.

**Comment by wafels** [comment]
See #1935
