### ISSUE TITLE
Update the glymur / openjpeg installation instructions

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1498]
Anaconda installations don't come with glymur, and glymur itself relies on the installation of openjpeg.  A user (thanks!) sent the description below on how he managed to install openjpeg to the mailing list.  These are included below for reference to make it easy to update the sunpy docs.

Okay.  After a couple false starts I was able to install the latest openjpeg library and get glymur to find it.  In case this comes up again, what I did was:
- download openjpeg-2.1.0.tar.gz, untar it (tar xvzf ..., of course)
- in the openjpeg-2.1.0 directory I then did:
- cmake . -DCMAKE_INSTALL_PREFIX='/export/slavin/python/anaconda'
  (note the dot after cmake) so setting the install prefix to the root of my anaconda distribution (I found that setting the DESTDIR environment variable to /export/slavin/python/anaconda resulted in an install under /export/slavin/python/anaconda/usr/local). 
- make
- make install
  I then needed to create a configuration file for glymur to ensure that it could find the library. So I created a /home/jslavin/.config/glymur directory and a file in it named glymurrc into which I put:
  [library]
  openjp2:/export/slavin/python/anaconda/lib/libopenjp2.so

**Comment by Cadair** [comment]
glymur is installed when you do `conda install sunpy` if you follow the install instructions.

The 'correct' solution for this is for us to build a openjpeg conda package, however, these instructions should provide a stop gap.

**Comment by wafels** [comment]
Ah, that's good.  Does that happen through

https://conda.binstar.org/sunpy

now?

**Comment by Cadair** [comment]
yep.

**Comment by wafels** [comment]
I agree that some stop gap instructions are worthwhile.  For example, I had
to install cmake on my mac to get started.

**Comment by Cadair** [comment]
@wafels if you have time, feel free to try and get a recipe working for conda...

**Comment by Cadair** [comment]
https://github.com/conda/conda-recipes

https://github.com/sunpy/conda-package-builder

**Comment by nabobalis** [comment]
This can be closed now? Glymur is in conda-forge, I would have to check the build documentation to see if that needs updating though.
