### ISSUE TITLE
Spectrum class should check that freq and data are same dimension on creation

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1501]

**Comment by sudk1896** [comment]
Hi,
I went through the Spectrum class. When you say frequency and data axis dimensions should be same, you mean you want the lengths of both arrays (frequency and data) should be same, If not  then you want to raise an error/exception. Correct me If I am wrong ?

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#14
