### ISSUE TITLE
the differential rotation code in solar_rotation does not update meta data

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1506]
The `mapcube_solar_derotate()` function should adjust the header information so that the axes are correct when plotted.

**Comment by Cadair** [comment]
hmmm, it seems like it is doing this, more investigation required.

**Comment by wafels** [comment]
What was the problem?  I've been meaning to take a second look at this
myself.  I suspect the code may not be updating the correct metadata.

**Comment by Cadair** [comment]
@wafels It seems that when you run derotate and then plot the image using `peek()` the sun is still moving underneath the plot. Which is wrong. Also wcsaxes frames on individual plots seem to indicate the pointing is incorrect.

**Comment by wafels** [comment]
On Thu, Jul 23, 2015 at 9:40 AM, Stuart Mumford <notifications@github.com>
wrote:

> @wafels <https://github.com/wafels> It seems that when you run derotate
> and then plot the image using peek() the sun is still moving underneath
> the plot. Which is wrong.
>

features move across the FOV?  Features should be (relatively) stationary
and the co-ordinate values should change.


> Also wcsaxes frames on individual plots seem to indicate the pointing is
> incorrect.
>
Since I haven't made use of wcsaxe much, I can't comment on this.

**Comment by Cadair** [comment]
yeah features move across the FOV

**Comment by Cadair** [comment]
I think.
