### ISSUE TITLE
Fermi Light Curve truncate issue 

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#1508]
Truncating FERMI time series an issue due to order or times from FITS files (Andy)

```
In [1]: from sunpy import lightcurve as lc

In [2]: date = '2013-10-28'

In [3]: t_start = '2013-10-28 01:00'

In [4]: t_end = '2013-10-28 03:00'

In [5]: gbm = lc.GBMSummaryLightCurve.create(date)

In [6]: gbm.truncate(t_start, t_end)
```

KeyError: 1382922000000000000

**Comment by aringlis** [comment]
Thanks @hayesla - good catch. This is a recurrence of #1371 where the data from the source FITS file are not necessarily in order (i.e. time may not be monotonically increasing). so I'll re-open that issue. It should be easy to fix for all lightcurve data sources by adding a DataFrame.sort(inplace=True) command to each source.

**Comment by ehsteve** [comment]
@aringlis don't add it to each source just add it to LightCurve if you can.
