### ISSUE TITLE
findpeaks code is wrong and is not used anywhere

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1511]
The findpeaks function in sunpy.sunpy.util claims to find local maxima in the data.  The test code

data = np.array([1.0, 3.5, 3.0, 4.0, -9.0, 0.0, 0.5, 0.3, 9.5])
assert np.array_equal(util.findpeaks(data), np.array([0, 2, 5]))

passes. However, the local maxima (by inspection) in the array data are at indices [1,3,6].  The findpeaks code is only used in sunpy.util.util and in the tests for sunpy.util.util .  If it is not used anywhere, and is wrong, it should be removed from the code until time as it is needed.

**Comment by Cadair** [comment]
BURN IT WITH FIRE.

**Comment by rhewett** [comment]
Plus np.infty
