### ISSUE TITLE
Remove VSO qr.num_records() in favour of len(qr)

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1514]
This can be confirmed with the following code 
```
from sunpy.net import vso
client=vso.VSOClient()
qr = client.query(vso.attrs.Time('2014/12/01 06:55', '2014/12/01 06:56'), vso.attrs.Instrument('hmi'))
qr.num_records
```

Or perhaps we should get rid of num_records completely for 0.7

**Comment by Cadair** [comment]
yeah it should probably go in favour of `len(qr)`

**Comment by wafels** [comment]
I agree.  non-pythonic.

**Comment by Cadair** [comment]
This should be modified for 0.6.1 so that it returns an int and not a table, but removed for 0.7.

**Comment by Cadair** [comment]
This is not actually a bug. `num_records` is a method not a property. The correct invocation is:

```python
In [7]: qr.num_records()
Out[7]: 6
```

the reason that

```python
In [6]: qr.num_records
```

prints a table is that it is the same as doing:

```python
In [5]: qr
```

where it returns the _repr_ of the table.
