### ISSUE TITLE
Create a Unit Range object

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1515]
Should be able to handle any kind of quantities including times such as wavelength, dimensions (e.g. arcsec).

TimeRange would subclass this object.

**Comment by wafels** [comment]
This might also be useful when creating a general Region of Interest object.

**Comment by wafels** [comment]
One that is more general than the one we already have.

**Comment by ehsteve** [comment]
Agreed

**Comment by Cadair** [comment]
I don't think so.

**Comment by Raahul-Singh** [comment]
Could you please give more information about the attributes that this object should have? Also where should this class be ? In `utils` ?

**Comment by nabobalis** [comment]
Putting it in a new file under utils would make sense to me. I would imagine it would need similar attributes to what TimeRange has: start,end, delta, contains (?).

**Comment by dstansby** [comment]
This should probably go upstream to https://github.com/astropy/astropy/
