### ISSUE TITLE
Link from docs to sunpy.org ?

### ISSUE THREAD

**Issue by cdeil** [sunpy/sunpy#1517]
How about linking back from the docs?
It looks like sunpy.org isn't mentioned in the docs at the moment:
http://docs.sunpy.org/en/latest/search.html?q=sunpy.org&check_keywords=yes&area=default
This would make it easier to go back / forth and would be useful IMO.

Not sure what the best place is ... maybe mention http://sunpy.org/ on the top-level docs page http://docs.sunpy.org/en/latest/index.html ?

**Comment by Cadair** [comment]
Thanks @cdeil good spot.

**Comment by souravsingh** [comment]
I would like to work on the issue.How do I start?

**Comment by Cadair** [comment]
Have you got yourself setup with a development environment already?

If so you should edit the rst files that comprise our documentation. I think the index page would be a good place to have a link: https://github.com/sunpy/sunpy/blob/master/doc/source/index.rst.

**Comment by souravsingh** [comment]
I have sent in a Pull Request for the index page.Here is the PR-https://github.com/souravsingh/sunpy/pull/1

**Comment by Cadair** [comment]
@souravsingh When you create the pull request, you need to point it at sunpy/master rather than souravsingh/master.

**Comment by souravsingh** [comment]
I Didnt Notice that.I am really sorry

**Comment by Cadair** [comment]
@souravsingh not a problem :)

**Comment by souravsingh** [comment]
I have sent a PR but the build tests failed.Here is the link to PR-https://github.com/sunpy/sunpy/pull/1577

**Comment by souravsingh** [comment]
I believe this issue can be closed
