### ISSUE TITLE
IRIS Colour Maps

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1518]
See this IDL file for how they are generated (I think):

http://sohowww.nascom.nasa.gov/solarsoft/iris/idl/lmsal/calibration/iris_lct.pro

**Comment by ehsteve** [comment]
I've already done this see this branch. https://github.com/ehsteve/sunpy/tree/iris_update
@Cadair I'll break it out and submit it as PR soon.

**Comment by Cadair** [comment]
sweet!

**Comment by ehsteve** [comment]
@Cadair Is there any kind of urgency to this?

**Comment by Cadair** [comment]
@ehsteve it would be nice to be able to use them in the ginga project.

**Comment by ehsteve** [comment]
okay, i can prob do this today or latest this week.

**Comment by Cadair** [comment]
no mad panic. :)

**Comment by ayshih** [comment]
@Cadair close if you're happy
