### ISSUE TITLE
submap for MDI doesn't work in arcseconds

### ISSUE THREAD

**Issue by SallyDa** [sunpy/sunpy#1523]
Using [this MDI file](http://sohodata.nascom.nasa.gov//archive/soho/private/data/processed/mdi/fd_M_96m_01d/fd_M_96m_01d.6192/fd_M_96m_01d.6192.0007.fits) as shown below, it returns a zero size submap.

```python
>>> import sunpy.map
>>> import astropy.units as u
>>> m=sunpy.map.Map('fd_M_96m_01d.6192.0007.fits')
>>> sm=m.submap([200, 500]*u.arcsec, [500, 700]*u.arcsec)
>>> sm
SunPy MDIMap
---------
Observatory:	 SOHO
Instrument:	 MDI
Detector:	 MDI
Measurement:	 continuum
Wavelength:	 nan nm
Obs Date:	 2009-12-15 11:15:01
dt:		 0.000000 s
Dimension:	 [ 0.  0.] pix
scale:		 [ 1.9856276  1.9856276] arcsec / pix

array([], shape=(0L, 0L), dtype=float32)
```

Using pixels, a submap is created as expected.

**Comment by aringlis** [comment]
Weirdly, if I specify degrees instead of arcseconds, it returns a submap with the cutout as if I had input arcseconds, e.g.:

    sm = m.submap([200,500]*u.deg,[500,700]*u.deg)
    sm
    Out[40]: 
    SunPy MDIMap
    ---------
    Observatory:	 SOHO
    Instrument:	 MDI  
    Detector:	 MDI
    Measurement:	 continuum
    Wavelength:	 nan nm
    Obs Date:	 2009-12-15 11:15:01
    dt:		 0.000000 s
    Dimension:	 [ 151.  101.] pix
    scale:		 [ 1.9856276  1.9856276] arcsec / pix

    array([[  4.58389521,  -1.76515663,  -2.67140007, ..., -10.90181923,
        -15.0991478 ,  -1.63621914],
       [ 14.55300617, -11.73341656,  -9.0122385 , ..., -14.25753403,
         -0.79558939,  -9.19369221],
       [ 28.13309669,  10.01152515,  13.63101578, ..., -11.72318745,
        -15.91242409,  -2.47236705],
       ...,

**Comment by aringlis** [comment]
I tried out the same procedure on an AIA map and it behaves normally. Seems like the coordinate system information is somehow getting mixed up in the MDI maps.

@cadair @ehsteve, maps aren't really my area - but I do notice that the MDI meta doesn't seem to have a 'cunit1' or 'cunit2' keyword, unlike AIA maps...

**Comment by wafels** [comment]
MDI level 1.5 has an arcsec per pixel keyword IM_SCALE

http://soi.stanford.edu/sssc/doc/keywords.html

So, the information on the unit is in the header, just in a different
place.  Suggest a fix in the map source for MDI.

**Comment by wafels** [comment]
Confirmed bug (using master) and the linked file.

**Comment by Cadair** [comment]
Well the `units` are correct (even if they are just default). 

I am investigating.

**Comment by wafels** [comment]
yeah, by default in mapbase.... not sure my earlier suggestion would help

**Comment by aringlis** [comment]
In mapbase ```pixel_to_data``` seems to be assuming that ```wcs.wcs_pix2world``` always returns degrees. But, I just tested this on my map, and it looks like it returns arcseconds:

    m.wcs.wcs_pix2world(600,600,0)
    Out[154]: [array(175.2710869565762), array(177.37874337930018)]

**Comment by Cadair** [comment]
oh not this again! I thought I fixed this!

**Comment by Cadair** [comment]
so, this is looking like a 0.6.1 worthy bug...

**Comment by Cadair** [comment]
ok, so I fixed @aringlis `pixel_to_data` issue, but that isn't the direct cause of the issue in submap.

**Comment by Cadair** [comment]
This is related to #1524, but that PR does not solve this issue.
