### ISSUE TITLE
Add a shift() method to GenericMap

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1537]
In order to easily fix any translation errors in the map location.

**Comment by Cadair** [comment]
Would you want it to move the reference coordinate or the reference pixel? Or decide which one should be shifted based on the unit of the input?

**Comment by ehsteve** [comment]
decide based on input would be best I think.

**Comment by wafels** [comment]
There already is a shift function in sunpy/image/coalignment.py called
apply_shifts.  It was written with specific applications in mind, namely
image coalignment by template matching and derotating submaps assuming that
the derotation time-interval, or the size of the submap relative to the Sun
is small (for a user defined value of small).  It should be relatively easy
to adapt that to what you want.

**Comment by wafels** [comment]
Note that the current apply_shifts function in master incorrectly
calculates the positioning information.  #1534 fixes that.

**Comment by ehsteve** [comment]
Would be good for shift to be a property (defaulted to zero) so that it is kept around and added to the reference coordinate. You want to keep the information about what the shift is and be able to tweak it easily. To tell whether a shift has been applied you would just what the value of shift is.

**Comment by Famguy** [comment]
Hi! I would like to work on this. Could anyone please tell me more about it?

**Comment by ehsteve** [comment]
This functionality has already been written and is awaiting review and acceptance. See the note right above your comment which references an open pull request.

**Comment by ehsteve** [comment]
@Famguy if you are looking for something to do might I suggest #1257 which should be fairly easy to address.

**Comment by Famguy** [comment]
Thanks @ehsteve for suggesting the issue! I didn't check the PR properly and thought this issue was still open.

**Comment by ayshih** [comment]
Closed by #1566
