### ISSUE TITLE
GenericMap.pixel_to_data returns Latitude/Longitude when in helioprojective

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1539]
This is super confusing.

**Comment by Cadair** [comment]
Why is this confusing. It is correct.

**Comment by ehsteve** [comment]
Longitude/Latitude is only correct for heliographic following the standard and accepted definition in our field. It should be labelled as Solar-X/Solar-Y.

**Comment by Cadair** [comment]
no it's not. Helioprojective is a spherical coordinate system.

The Latitude and Longitude are astropy objects, subclassed from angle with extras for representing coordinates in a spherical coordinate system. They are the correct types of object to return, and they integrate correctly with the coordinates module.

**Comment by ehsteve** [comment]
How then do we label heliographic coordinates?

**Comment by Cadair** [comment]
they would also be returned as Latitude and Longitude.

Obviously, after #1210 is merged `pixel_to_data` will return a `SkyCoord` object, which will be fully frame-aware.

**Comment by ehsteve** [comment]
so heliographic coordinates would also look like a SkyCoord?

**Comment by Cadair** [comment]
yes,

**Comment by ehsteve** [comment]
well that would also be confusing...as a coordinate on the surface of the Sun is clearly not the sky especially if the coordinate is behind the Sun and cannot even be viewed in the sky (so no transform even possible to SkyCoord).

**Comment by dpshelio** [comment]
I don't see why not... you could get a  the projection of a "dark side of the sun" into "solar x/y" and compare it with the farside images from gong.
In any case, I don't see what's the confusing bit... SkyCoord is just the name, right? I just see it as sphere coordinates... which is pretty much all we use.

**Comment by ehsteve** [comment]
I think we have to work within the conventions/naming schemes that our community is familiar with. Referring to both helioprojective coordinates as well as heliographic coordinates as longitude/latitude is technically correct but unnecessarily confusing for users. We should continue to use the same back-end but we should provide a "solar friendly" API to our users most of whom will never need to coordinate with astrophysical coordinate systems.

**Comment by Cadair** [comment]
@ehsteve Take a look at #1210 for the nomenclature used for the different frames. It uses `Tx` and `Ty` as the latitude and longitude in helioprojective (following the notation of Thompson).

**Comment by dpshelio** [comment]
@ehsteve I agree partly with  you, but not using helioprojective or heliographic or the proper names could bring quite a lot of problems if people is going to use solar_x and solar_y with other things like solar orbiter or solar probe+ where we will be looking at the sun at different distances.  So my vote is towards "enforcing" correct nomenclature more than just keep with past habits.

**Comment by ehsteve** [comment]
if that is going to be our stance (which I'm not sure I really agree with) we really need to beef up our docs on this subject.

**Comment by Cadair** [comment]
@ehsteve You should checkout the coordinates branch and have a look at the nomenclature in it and comment there as you feel fit. I think there was also a SEP about this at some point...
