### ISSUE TITLE
import sunpy.map does not work

### ISSUE THREAD

**Issue by kkozarev** [sunpy/sunpy#1550]
Hello, I tried running "from sunpy import map", and I get the following error. I just updated sunpy yesterday. Running on MacOS X 10.10 in ipython.

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a1adac5bf47a> in <module>()
----> 1 from sunpy import map

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/map/__init__.py in <module>()
      6 
      7 
----> 8 from sunpy.map.mapbase import GenericMap
      9 
     10 from sunpy.map.header import MapMeta

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/map/mapbase.py in <module>()
     23 
     24 import sunpy.io as io
---> 25 import sunpy.wcs as wcs
     26 from sunpy.visualization import toggle_pylab
     27 from sunpy.sun import constants

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/wcs/__init__.py in <module>()
     45 from __future__ import absolute_import
     46 
---> 47 from sunpy.wcs.wcs import *

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/wcs/wcs.py in <module>()
      2 
      3 import numpy as np
----> 4 import sunpy.sun as sun
      5 
      6 import astropy.units

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/sun/__init__.py in <module>()
     13 from __future__ import absolute_import
     14 
---> 15 from sunpy.sun.sun import *
     16 
     17 from . import _constants

/usr/local/anaconda/lib/python2.7/site-packages/sunpy-0.6.dev5636-py2.7-macosx-10.5-x86_64.egg/sunpy/sun/sun.py in <module>()
     26 
     27 import astropy.units as u
---> 28 from astropy.coordinates import Angle, Longitude, Latitude
     29 
     30 from sunpy.time import parse_time, julian_day, julian_centuries

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     15 from .earth import *
     16 from .transformations import *
---> 17 from .builtin_frames import *
     18 from .name_resolve import *
     19 from .matching import *

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py in <module>()
     26 
     27 from .icrs import ICRS
---> 28 from .fk5 import FK5
     29 from .fk4 import FK4, FK4NoETerms
     30 from .galactic import Galactic

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py in <module>()
      8                          TimeFrameAttribute, RepresentationMapping)
      9 from ..transformations import DynamicMatrixTransform
---> 10 from .. import earth_orientation as earth
     11 
     12 from .utils import EQUINOX_J2000

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py in <module>()
     17 from .. import units as u
     18 
---> 19 jd1950 = Time('B1950', scale='tai').jd
     20 jd2000 = Time('J2000', scale='utc').jd
     21 _asecperrad = u.radian.to(u.arcsec)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in __init__(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
    206                 self._set_scale(scale)
    207         else:
--> 208             self._init_from_vals(val, val2, format, scale, copy)
    209 
    210         if self.location:

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _init_from_vals(self, val, val2, format, scale, copy)
    248 
    249         # Parse / convert input values into internal jd1, jd2 based on format
--> 250         self._time = self._get_time_fmt(val, val2, format, scale)
    251         self._format = self._time.name
    252 

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _get_time_fmt(self, val, val2, format, scale)
    288                 pass
    289         else:
--> 290             raise ValueError('Input values did not match {0}'.format(err_msg))
    291 
    292     @classmethod

ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']
```

**Comment by Cadair** [comment]
What version of Astropy do you have installed? Can you share the output of `sunpy.system_info()`?

I would guess you need to update Astropy.

**Comment by kkozarev** [comment]
==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
Time : Saturday, 19. September 2015 10:12AM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : Missing version.py; re-run setup.py
SunPy_git : N/A
OS: Mac OS X 10.10.5 (i386)


###########
 Required Libraries 
###########
Python: 2.7.10
NumPy: 1.9.2
SciPy: 0.16.0
matplotlib: 1.4.3
Astropy: 1.0.4
Pandas: 0.16.2


###########
 Recommended Libraries 
###########
beautifulsoup: 4.3.2
PyQt: 4.11.3
SUDS: 0.6
Sqlalchemy: 1.0.8
Requests: 2.7.0

**Comment by kkozarev** [comment]
I believe Astropy 1.0.4 is the latest stable version?

**Comment by Cadair** [comment]
@kkozarev yes it is.

Can you try opening up a clean session and running:

```python
import astropy.coordinates
```

**Comment by kkozarev** [comment]
In [1]: import astropy.coordinates
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e74b6aa471e4> in <module>()
----> 1 import astropy.coordinates

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/__init__.py in <module>()
     15 from .earth import *
     16 from .transformations import *
---> 17 from .builtin_frames import *
     18 from .name_resolve import *
     19 from .matching import *

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py in <module>()
     26 
     27 from .icrs import ICRS
---> 28 from .fk5 import FK5
     29 from .fk4 import FK4, FK4NoETerms
     30 from .galactic import Galactic

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py in <module>()
      8                          TimeFrameAttribute, RepresentationMapping)
      9 from ..transformations import DynamicMatrixTransform
---> 10 from .. import earth_orientation as earth
     11 
     12 from .utils import EQUINOX_J2000

/usr/local/anaconda/lib/python2.7/site-packages/astropy/coordinates/earth_orientation.py in <module>()
     17 from .. import units as u
     18 
---> 19 jd1950 = Time('B1950', scale='tai').jd
     20 jd2000 = Time('J2000', scale='utc').jd
     21 _asecperrad = u.radian.to(u.arcsec)

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in __init__(self, val, val2, format, scale, precision, in_subfmt, out_subfmt, location, copy)
    206                 self._set_scale(scale)
    207         else:
--> 208             self._init_from_vals(val, val2, format, scale, copy)
    209 
    210         if self.location:

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _init_from_vals(self, val, val2, format, scale, copy)
    248 
    249         # Parse / convert input values into internal jd1, jd2 based on format
--> 250         self._time = self._get_time_fmt(val, val2, format, scale)
    251         self._format = self._time.name
    252 

/usr/local/anaconda/lib/python2.7/site-packages/astropy/time/core.pyc in _get_time_fmt(self, val, val2, format, scale)
    288                 pass
    289         else:
--> 290             raise ValueError('Input values did not match {0}'.format(err_msg))
    291 
    292     @classmethod

ValueError: Input values did not match any of the formats where the format keyword is optional [u'astropy_time', u'datetime', u'jyear_str', u'iso', u'isot', u'yday', u'byear_str']

In [2]: import astropy

In [3]:

**Comment by Cadair** [comment]
@kkozarev it seems your issue is inside of astropy. Perhaps you could reinstall astropy? If that doesn't work you might have more luck asking on their mailing list / github page. I don't really understand the inside workings of astropy.time where this bug is stemming from.

**Comment by ehsteve** [comment]
Closing this issue as it is not relevant to sunpy.
