### ISSUE TITLE
Map xrange, yrange and centre do not use astropy wcs

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1554]
They should use Astropy WCS

**Comment by ehsteve** [comment]
Had a long discussion with @ayshih @wafels about this and it is not so clear how we want to proceed because for rotated maps the definition for these values are unclear.

**Comment by Cadair** [comment]
this is addressed in #1975, by deprecating these attributes and replacing them with `bottom_left_coord` and `top_left_coord` which contain the same information under a linear mapping.

**Comment by Cadair** [comment]
I am going to remove the affects-released label, as while it is technically true, a fix is not possible.

**Comment by nabobalis** [comment]
If a fix is not possible, time to close this?

**Comment by Cadair** [comment]
I would say that #1975 will close this, because it deprecates the broken API.
