### ISSUE TITLE
What the HEK? Flares number changes

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1572]
We have had problems since a while while testing the database and hek (for example #1570). The problem has not been found yet, however HEK returns two different types of results, one where anything that happens between the time range given, or the other - named `temporalmode=strict` - that just returns the values that starts and ends within the time range given.

In any case, the results for these two modes in HEK give [11](https://www.lmsal.com/hek/her?cosec=2&&cmd=search&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T007:23:56&event_endtime=2011-08-09T07:24:00&return=event_starttime,event_endtime results) or [0](https://www.lmsal.com/hek/her?cosec=2&&cmd=search&temporalmode=strict&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T007:23:56&event_endtime=2011-08-09T07:24:00&return=event_starttime,event_endtime results), but never in the order of thousands...

I've also tried using [QHEK](https://github.com/dmlabdmlab/QueryHEK) and I can confirm they produce 0 results for that time interval (as the strict mode shows), however for a different time range the results between HEK and QHEK also differs (dmlabdmlab/QueryHEK#1).

**Comment by dstansby** [comment]
I think this really needs a self contained example to demonstrate what the problem is. Feel free to open with an example/more info.
