### ISSUE TITLE
Figure tests need a way of displaying the figures

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1610]
An incremental update to the figure hash problem would be if there was a way of running the tests and saving the pngs to a certain directory. This could be used to easily validate that the tests are producing "correct" if subtly different output.

**Comment by ehsteve** [comment]
Figures should be placed in a different repository as discussed and agreed upon in dev meeting 11-Jan-2015.

**Comment by dpshelio** [comment]
@Cadair should we close this?

**Comment by Cadair** [comment]
yaarrpp
