### ISSUE TITLE
Don't clone into $HOME/sunpy

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1618]
The fact that cloning and installing sunpy in $HOME/sunpy is a bad idea because it conflicts with the default data dir needs documenting better, and potentially we could check for this in `config.py`.

**Comment by dpshelio** [comment]
That's annoying... should now we have a `.sunpy` place for the config? and maybe a check around before writing into `$HOME/sunpy` to see whether it's the sunpy path?

**Comment by Cadair** [comment]
@dpshelio yeah that check thing is possible, in `config.py` when it checks the $HOME/sunpy dir it could check if `__file__` is in that dir.

**Comment by agneet42** [comment]
@dpshelio @Cadair I've looked into https://github.com/sunpy/sunpy/blob/master/sunpy/util/config.py. 
Do I need to check the the above condition in def _get_home(): ?
