### ISSUE TITLE
Unidown branch: Fido: what is the anticipated behavior of Fido when acquiring RHESSI data?

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1625]
Should the following request have downloaded three daily summary files and not just one?

```python
from sunpy.net.vso.attrs import Time, Instrument
from sunpy.net.dataretriever import Fido
unifresp = Fido.search(Time('2012/3/4','2012/3/6'), Instrument('rhessi'))
unifresp
[<Table masked=False length=1>
     Start Time           End Time       Source Instrument
     string152           string152      string8  string48 
------------------- ------------------- ------- ----------
2012-03-04 00:00:00 2012-03-06 00:00:00             rhessi]

d =Fido.fetch(unifresp)
[========================================]

d
['/Users/ireland/sunpy/data/hsi_obssumm_20120304_042.fits']
```

**Comment by ehsteve** [comment]
You are right. Should be getting 3 not just one.

**Comment by Cadair** [comment]
as @DanRyanIrish pointed out this should only return data for the two days as '2012/3/6' evaulates to midnight '00:00:00'.

**Comment by wafels** [comment]
I think the issue might lie in sunpy/instr/rhessi.py.  The Fido RHESSI client has a method _get_url_for_timerange that relies on the get_obssum_filename function of sunpy/instr/rhessi.py  get_obssumm_filename relies on get_obssumm_dbase_file to find the right files.  It looks like get_obssumm_dbase_file is not finding the correct files; for example,

In [10]: import sunpy.instr.rhessi as rhessi
In [11]: f = rhessi.get_obssumm_dbase_file(('2011/03/06', '2011/04/26'))
In [12]: f
Out[12]: 
('/var/folders/bg/fwz5qlq1657f9yh53dc5t9xc0000gn/T/tmpUgWOPa.txt',
 <httplib.HTTPMessage instance at 0x10cf4ee60>)

In [13]: result = rhessi.parse_obssumm_dbase_file(f[0])

In [14]: result['filename']
Out[14]: 
['hsi_obssumm_20110301_030.fit',
 'hsi_obssumm_20110302_025.fit',
 'hsi_obssumm_20110303_030.fit',
 'hsi_obssumm_20110304_029.fit',
 'hsi_obssumm_20110305_031.fit',
 'hsi_obssumm_20110306_054.fit',
 'hsi_obssumm_20110307_061.fit',
 'hsi_obssumm_20110308_047.fit',
 'hsi_obssumm_20110309_030.fit',
 'hsi_obssumm_20110310_035.fit',
 'hsi_obssumm_20110311_038.fit',
 'hsi_obssumm_20110312_035.fit',
 'hsi_obssumm_20110313_030.fit',
 'hsi_obssumm_20110314_031.fit',
 'hsi_obssumm_20110315_022.fit',
 'hsi_obssumm_20110316_030.fit',
 'hsi_obssumm_20110317_029.fit',
 'hsi_obssumm_20110318_041.fit',
 'hsi_obssumm_20110319_033.fit',
 'hsi_obssumm_20110320_021.fit',
 'hsi_obssumm_20110321_024.fit',
 'hsi_obssumm_20110322_042.fit',
 'hsi_obssumm_20110323_065.fit',
 'hsi_obssumm_20110324_049.fit',
 'hsi_obssumm_20110325_016.fit',
 'hsi_obssumm_20110326_017.fit',
 'hsi_obssumm_20110327_027.fit',
 'hsi_obssumm_20110328_018.fit',
 'hsi_obssumm_20110329_026.fit',
 'hsi_obssumm_20110330_033.fit',
 'hsi_obssumm_20110331_031.fit']

I've also attached the file downloaded by get_obssumm_dbase_file.  There is also an issue in get_obssumm_filename in that these lines: https://github.com/sunpy/sunpy/blob/unidown/sunpy/instr/rhessi.py#L188-L190 - mean that only one filename is ever returned to the Fido RHESSI client.

[tmpxEhyam.txt](https://github.com/sunpy/sunpy/files/114617/tmpxEhyam.txt)

**Comment by Cadair** [comment]
@wafels can this be closed?

**Comment by wafels** [comment]
yes
