### ISSUE TITLE
Carrington rotation number

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1646]
The SunPy and SSWIDL Carrington rotation numbers differ, and the difference is significant.

In [2]: import sunpy.sun
In [3]: sunpy.sun.carrington_rotation_number('2015-12-25 11:57:00')
Out[3]: 2172.011791498784

In [4]: sunpy.sun.carrington_rotation_number('2015-12-25 04:13:54')
Out[4]: 2172.0000007128997

IDL> print, tim2carr('2015-12-25 11:57:00',/dc)
       2172.0001

For reference, 
http://alpo-astronomy.org/solar/rotn_nos.html
http://umtof.umd.edu/pm/crn/

The SunPy Carrington rotation numbers appear to be the minority opinion.

**Comment by Cadair** [comment]
Awkward...

**Comment by wafels** [comment]
I'm taking a look at this.

**Comment by dpshelio** [comment]
That's being also part of the #1070 - hopefully in the next weeks I can get that PR up to speed and end with it.

**Comment by Cadair** [comment]
Looks like we have our own UTC->Julian Date conversion which we really should replace with http://docs.astropy.org/en/stable/time/index.html

**Comment by Cadair** [comment]
see #1647

**Comment by bla1089** [comment]
Any updates on this?

**Comment by Cadair** [comment]
@bla1089 have you verified this is still an issue? I would think that #1647 should've helped. If it's still a problem we can have a look into it.

**Comment by ayshih** [comment]
See also #2224 for some of my frustrations with definitions of Carrington longitude (and correspondingly Carrington rotation numbers).

**Comment by ayshih** [comment]
With PR #3178, we should be calculating the Carrington rotation number more accurately than any of the above sources that @wafels points to.  (The first of the two links actually disagrees with the *Astronomical Almanac* to printed precision.)
