### ISSUE TITLE
Errors while running SunPy tests

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#1651]
Hi I installed SunPy on Anaconda 2 and running the tests it shows several errors.  It's quite a bit of text so I don't know if to copy it all here.   One of the most common errors looks like this:

        >>> np.lib.pad(a, 2, padwithtens)
        array([[10, 10, 10, 10, 10, 10, 10],
               [10, 10, 10, 10, 10, 10, 10],
               [10, 10,  0,  1,  2, 10, 10],
               [10, 10,  3,  4,  5, 10, 10],
               [10, 10, 10, 10, 10, 10, 10],
               [10, 10, 10, 10, 10, 10, 10]])
        """
        if not np.asarray(pad_width).dtype.kind == 'i':
>           raise TypeError('`pad_width` must be of integral type.')
E           TypeError: `pad_width` must be of integral type.

please let me know if this is of interest to you and how best to report it.

**Comment by Cadair** [comment]
Hello @amunozj,

This is a known bug in the latest release, (0.6.1) it has already been fixed in master and the 0.6 branches, we should be doing a 0.6.2 release shortly.

If I remember correctly, downgrading numpy to 1.9 will avoid the problem.

Thanks for the report.
