### ISSUE TITLE
Default color table for Proba2/SWAP

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1662]
What is it?

[Proba2](http://proba2.oma.be/)/SWAP page does not have any default colour in their images, just black and white[*].
So [helioviewer](http://helioviewer.org).

[SolarMonitor](http://solarmonitor.org/full_disk.php?date=20160216&type=swap_00174), uses the blue (1 on IDL, is that equivalent to "blues" in IDL?), which is different than the eit171 (used for EIT and TRACE).

Can we get any official preference on this?
- In their [gallery](http://proba2.oma.be/highlight/gallery) and [news](http://proba2.oma.be/node) there are a variety of yellows and even red...

**Comment by dpshelio** [comment]
@DavidBerghmans - could you comment on this?

**Comment by bogdanni** [comment]
If SWAP images have to be coloured, the preference is for the AIA 171 colormap.

**Comment by nabobalis** [comment]
Se
