### ISSUE TITLE
SDO/AIA response functions

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#1663]
Are there plans to implement the SDO/AIA response functions (a la `aia_get_response()` in SSW) in SunPy? I noticed that this was mentioned as a [GSOC project in 2015](http://openastronomy.org/gsoc/gsoc2015/ideas.html) and was wondering if any progress had been made on this front. Looking at [Boerner et al. (2012)](http://adsabs.harvard.edu/abs/2012SoPh..275...41B), it seems this might require significant integration with CHIANTI/ChiantiPy.

**Comment by Cadair** [comment]
hey @wtbarnes thanks for the issue.

It is something we have been wanting to do for a while, but have never had the time. I know that @drewleonard42 looked into doing it during his PhD, but there were licencing issues with ChiantiPy at the time, which are now resolved.

We didn't get anyone taking up the project last year, but I have suggested to @drewleonard42 that he could re-write it and see if we can get a student interested in it. Do you have any time to help with the work?

If you have some time perhaps you could drop into our IRC channel #sunpy on freenode? http://sunpy.org/help/#chat

**Comment by wtbarnes** [comment]
Thanks for the response @Cadair. 

I actually have a project coming up where this would be a really useful tool so I think I could devote some time to working on it. I think that Ken Dere is in the process of moving all development of ChiantiPy over to GitHub as well which will make integration with the project a bit easier.

I will be sure to check out the #sunpy channel on IRC. I'm still very new to SunPy so I'm sure I will have a lot of questions!

**Comment by wtbarnes** [comment]
This functionality does not belong in sunpy core so I'm going to close this. Anyone interested in this functionality should have a look at [this issue](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/issues/10)
