### ISSUE TITLE
Truncated test data should have header updated to refelect new size.

### ISSUE THREAD

**Issue by gmlaghari** [sunpy/sunpy#1686]
```WARNING:astropy:File may have been truncated: actual file length (538688) is smaller than the expected size (541440)```

I think all these warnings are expected as we are using truncated data for testing purposes. Mainly so that we don't fill up the repo with extra data. The header information in these files should be updated to remove these warnings.

**Comment by Cadair** [comment]
I think all these warnings are expected as we are using truncated data for testing purposes. Mainly so that we don't fill up the repo with extra data. The header information in these files could be updated to remove these warnings.

**Comment by agneet42** [comment]
@Cadair for this /sunpy/database/tests/test_attrs.py 

the header files are:
from datetime import datetime

import pytest
from astropy import units as u

from sunpy.database.database import Database
from sunpy.database import tables
from sunpy.database.attrs import walker, Starred, Tag, Path, DownloadTime,\
    FitsHeaderEntry
from sunpy.net.attr import DummyAttr, AttrAnd, AttrOr
from sunpy.net import vso
from sunpy.extern.six.moves import range




Could you tell me which header is to be updated to take care of the warnings? I'd like to work on this. Thanks.

**Comment by nitinkgp23** [comment]
Hey @agneet42 I guess you took it wrong. These are not header files, those happen to be in C. The header information that is being talked about lies inside FITS files, which can be accessed by Map.meta

**Comment by yashkgp** [comment]
Hey @Cadair , What needs to be updated in header information in these files ?

**Comment by nabobalis** [comment]
Does this even still happen?

**Comment by yashkgp** [comment]
Yeah , I ran the tests locally ,it's still giving the same warning.

**Comment by nabobalis** [comment]
I would guess that the `NAXIS` information is what needs updating.

**Comment by yashkgp** [comment]
Hey, @nabobalis  I tried doing that. It's still the warnings. Could we just catch the warnings and ignore them as these warnings are only for test data?

**Comment by nabobalis** [comment]
I am not a fan of catching those warnings, we would have probably have to do it for each test. 

Updating the header must surely be the way to fix it.

**Comment by dstansby** [comment]
What's the action here? Is it updating the FITS headers in our sample test data? If so this issue should be moved to the test data repo.

**Comment by Cadair** [comment]
This is test data in `sunpy/data/test` rather than sample data which is in it's own repo and downloaded.

**Comment by nabobalis** [comment]
This won't be needed anymore when https://github.com/sunpy/sunpy/pull/5261 is merged in.
