### ISSUE TITLE
Sunpy_Spectrogram Error in a simple code

### ISSUE THREAD

**Issue by gmlaghari** [sunpy/sunpy#1687]
Below is my code and I am getting an error on Sunpy 0.6.1

``` python
import matplotlib.pyplot as plt
%matplotlib
import sunpy.spectra
from sunpy.spectra.sources.callisto import CallistoSpectrogram
image = CallistoSpectrogram.read('/home/ghulam/caldata/MUPK_20150822_064500_59.fit')
image.peek()

Using matplotlib backend: Qt4Agg

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-9113c813a1c3> in <module>()
      4 from sunpy.spectra.sources.callisto import CallistoSpectrogram
      5 image = CallistoSpectrogram.read('/home/ghulam/caldata/MUPK_20150822_064500_59.fit')
----> 6 image.peek()

/home/ghulam/anaconda2/lib/python2.7/site-packages/sunpy/spectra/spectrogram.py in peek(self, *args, **kwargs)
    435         """
    436         figure()
--> 437         ret = self.plot(*args, **kwargs)
    438         plt.show()
    439         return ret

/home/ghulam/anaconda2/lib/python2.7/site-packages/sunpy/spectra/spectrogram.py in plot(self, figure, overlays, colorbar, vmin, vmax, linear, showz, yres, max_dist, **matplotlib_args)
    563                 get_day(self.start).strftime("%d %b %Y"),
    564                 'Radio flux density',
--> 565    566             ])
    567         )

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 3: ordinal not in range(128)
              '(' + ', '.join(self.instruments) + ')',
```

 Please guide. The plot doesn't show colorbar as well.

**Comment by gmlaghari** [comment]
How do I know whether you will have fixed this bug or not?

**Comment by Cadair** [comment]
hey @gmlaghari is it possible you can provide the file you are using so we can recreate the error?

**Comment by gmlaghari** [comment]
@Cadair Fits file is attached please.
[MUPK_20150822_064500_59.fit.zip](https://github.com/sunpy/sunpy/files/156489/MUPK_20150822_064500_59.fit.zip)

**Comment by Cadair** [comment]
@gmlaghari I will try and look at it, but I am rather busy at the moment, so I can't promise when.

**Comment by gmlaghari** [comment]
@Cadair Try it when you get time. I am stuck here little here. Although SunPy is giving error, but plotting spectrogram without colorbar. 
Your effort is highly appreciated.

**Comment by gmlaghari** [comment]
@Cadair Any progress? I am getting same error even on older version.

**Comment by gmlaghari** [comment]
@Cadair How to add color in Sunpy spectrogram map?

**Comment by agneet42** [comment]
@Cadair with Python3 and Matplotlib 2.0, I get this image with the given fits file. 
![ ](https://github.com/agneet42/sunpy_images/blob/master/Image1.jpg)

**Comment by Cadair** [comment]
looks like this could be a python 2 specific unicode error from the original traceback.

**Comment by agneet42** [comment]
If the default encoding of Python is utf8, I guess this error won't come across?

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#7
