### ISSUE TITLE
Install documentation should suggest a Python version

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1704]
It is not clear to new users whether they should install anaconda with Python 2.7 or Python 3.x. We are striving to support both but right now we support 2.7 and that should be made clear in the documentation so that new users are not confused by this.

Specifically this is the file that needs to be fixed
https://github.com/sunpy/sunpy/blob/stable/doc/source/guide/installation/index.rst

**Comment by theaverageguy** [comment]
I am on it. 
I also would like to express my interest in SOCIS 2016 under sunpy with some bug fixes initially. 
Thanks.

**Comment by theaverageguy** [comment]
This can be closed @ehsteve . I fixed the PR earlier.

**Comment by ayshih** [comment]
An issue shouldn't be closed when the PR has not yet been accepted

**Comment by Gbear605** [comment]
Since Python 3 support has been merged, is there any reason for this issue to not be closed at this time?

**Comment by wafels** [comment]
The installation guide should explicitly say that SunPy is 2.7.x, 3.4 and
3.5 compatible.  I was asked about this issue just yesterday.

**Comment by agneet42** [comment]
hi. this issue has been resolved, as per my belief. why is it still open then? if i'm wrong, let me know about what more to do to resolve this. Thanks.

**Comment by Cadair** [comment]
The install guide should explicitly state that sunpy supports 2.7, and 3.4+
