### ISSUE TITLE
[unidown] Indexing Fido UnifiedResponse does not return a UnifiedResponse object

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1708]
Let's say you make a search request using Fido.search, but you only want to download a portion of the files returned.  The natural way of doing this is to index the UnifiedResponse.  Indexing the UnifiedResponse does not return a UnifiedResponse object.  Since Fido.fetch needs a UnifiedResponse object on input, the indexed UnifiedResponse causes an error.  

A solution to this is to create a `__getitem__` method for the UnifiedResponse object that returns a UnifiedResponse object.

**Comment by sudk1896** [comment]
@wafels: UnifiedResponse object would be a list of QueryResponse objects ordered by their time. Each QueryResponse object corresponds to the fits file for a particular date. To get a single file, you would have to sort the UnifiedResponse (sort a list, assuming it is unsorted), this would have to be done via  creating a custom sort function for the QueryResponse Object (maybe I'm wrong here). If you just wanted a single file (for a single particular date) you're better off querying directly for that date. Again, I might be wrong here. Why would you want to index here ?

**Comment by wafels** [comment]
If I wanted to get only the first file in the output, then 

data = Fido.fetch(results[0][0])

does not work - it errors out.  This is because Fido.fetch only takes UnifiedResponse objects and results[0][0] is not a UnifiedResponse object.  To get the data (the first file) I would need to make another query asking for that data only.  That might be the ultimate solution - just make better queries to begin with, but it does seem a bit inconvenient that I can't take arbitrary portions out of the UnifiedResponse object and get still use those bits in Fido.fetch.
