### ISSUE TITLE
Create citation file

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1712]
We should add a `CITATION` file in our [repository](http://blog.rtwilson.com/encouraging-citation-of-software-introducing-citation-files/)

**Comment by drewleonard42** [comment]
That file will mostly consist of the information [here](http://sunpy.org/about/#acknowledging) I assume?

**Comment by theaverageguy** [comment]
Can I break this into 2 PRs for easy review?

**Comment by ehsteve** [comment]
This sounds like a great idea though to limit the number of places that this information resides we should update the website to point to this file.

**Comment by tdwilkinson** [comment]
Hello, I am helping with this for GSOC. Would it be best if this CITATION file printed the information that is to be cited as suggested in the blog or just contained the information as text like below?

[CITATION.txt](https://github.com/sunpy/sunpy/files/189779/CITATION.txt)
