### ISSUE TITLE
Helioviewer is not working, homepage is downloaded instead of the requested image.

### ISSUE THREAD

**Issue by itztli** [sunpy/sunpy#1724]
Few days ago, the helioviewer interface not download the image requested.

```
from sunpy.net.helioviewer import HelioviewerClient
hv = HelioviewerClient()
hv.download_png('2012/07/16 10:08:00', 4.8, "[SDO,AIA,AIA,171,1,100],[SOHO,LASCO,C2,white-light,1,100]", x1=-2800, x2=2800, y1=-2800, y2=2800, directory='~/Desktop')   # doctest: +SKIP
```
The file downloaded is the homepage from helioviewer!

**Comment by Cadair** [comment]
@wafels what did you break?!

I think Helioviewer have done a large update, it will probably take us a while to catch up.

**Comment by wafels** [comment]
helioviewer.org now uses version 2 of the API.  Version 1 is still operating, but at a different location.  It should be possible to change the sunpy client to use version 1 of the helioviewer API at the new location.  I'll take a look.
