### ISSUE TITLE
Uncertainties on constants

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1748]
Our `sun.constants.uncertainty()` claims to return "relative" uncertainties, but it seems evident that the Astropy constants we use carry absolute uncertainties.  For example, a relative uncertainty of 5e+25 in the mass of the Sun would be ludicrous.  Do we just need to change our docstring?

Also, it would be nice if our `sun.constants.uncertainty()` actually returned a `Quantity` rather than just the number, further clarifying that the uncertainty is absolute rather than relative.

**Comment by dstansby** [comment]
It's not clear what astropy expects as an uncertainty (relative or absolute), so I've opened an issue upstream: https://github.com/astropy/astropy/issues/10102

**Comment by dstansby** [comment]
Part of this is fixed as `sunpy.sun.constants` returns `~astropy.constants.Constant`s. We still need to convert the uncertainties to `Qauntity`s though.

**Comment by dstansby** [comment]
I had more of  a look into this, and I don't think there's anything to fix now - we're construction `Constant` instances for each constant, which mandates an undertainty, so I think any requests for functionality/features should be sent upstream to astropy.
