### ISSUE TITLE
Rename Map unit parameter

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1751]
Maps use NDData which carries a units parameter (with an s) and map currently holds the units of the axis in the unit parameter (no s). We should rename the unit parameter to reduce confusion.

**Comment by Cadair** [comment]
The question is @sunpy/sunpy-developers what should we name it to? `world_units` `axes_units` `spatial_units`?

**Comment by nabobalis** [comment]
I like `spatial_units`.

**Comment by Cadair** [comment]
Yes that's my preference as well.

**Comment by drewleonard42** [comment]
`spatial units` seems reasonable.

**Comment by wafels** [comment]
Is  world_units better, for consistency with WCS?

**Comment by ehsteve** [comment]
Would it be better to drop this keyword completely and only have the WCS object hold this meta data?

**Comment by Cadair** [comment]
@ehsteve no, that would break the model, these properties abstract the meta data (currently FITS-WCS metadata) from the `meta` the WCS object is then build from these properties.

**Comment by Cadair** [comment]
@wafels `world_units` is maybe more technically correct, but seeing how `Map` is spatial only `spatial_units` makes the possible distinction from `spectral_units` in the future or similar. Of course that could work both ways.

I, however, forsee a future multi-dim object which has `spatial_units`, `spctral_units` and `temporal_units` all extracted from the metadata?

**Comment by wafels** [comment]
spatial_units +1

**Comment by dpshelio** [comment]
`spatial_units` :+1:

**Comment by DanRyanIrish** [comment]
```spatial_units``` 👍
