### ISSUE TITLE
Add more items in the gallery

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1752]
The [gallery](http://docs.sunpy.org/en/latest/generated/gallery/index.html) needs expanding, currently we have two sections:
- `gallery` - short (single plot) demos, designed to show one thing and be a quick reference.
- `tutorials` - longer walkthroughs of an analysis or showing how multiple parts of SunPy work together.

This issue is a list of suggestions for additions to the gallery, if you have a suggestion add it as a comment and we will try and keep the following list upto date.
- [ ] WCSAxes and plotting tutorial

**Comment by nabobalis** [comment]
I would this would be a good place to keep a list of what people would like to add to the gallery.

**Comment by Cadair** [comment]
yes.
