### ISSUE TITLE
Add support for Map's units parameter

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1753]
Since Map uses [NDData](http://docs.astropy.org/en/latest/api/astropy.nddata.NDData.html) they can carry a units parameter which is currently not filled in when a file is opened. 

This information could be stored in the file header and could be passed into Map when we load a file.

**Comment by nadgeri14** [comment]
I would like to work on this problem. Could I get some details on how to proceed forward ?

**Comment by agneet42** [comment]
@ehsteve I'd like to work on this. Could you help me by letting me know which file to start looking at?

**Comment by swapsha96** [comment]
@Cadair @dpshelio I would like to fix this issue. Can you suggest me which unit should I set as default? An example in [NDData documentation](http://docs.astropy.org/en/stable/api/astropy.nddata.NDData.html) uses 'u.cm'. Should I create a PR setting default as u.cm?

**Comment by swapsha96** [comment]
@ehsteve @Cadair I would like to work on this.

**Comment by dstansby** [comment]
Is there a standard FITS keyword for data units?

**Comment by Cadair** [comment]
`BUNIT`?

**Comment by dstansby** [comment]
I'll take a look at this for 2.1. There's a couple of places (e.g. contouring) where it would be good to add support for unitful-data, so I think some sort of global review of this will be helpful.
