### ISSUE TITLE
convert_data_to_pixel issue

### ISSUE THREAD

**Issue by thothsartre** [sunpy/sunpy#1763]
This line in convert_data_to_pixel:
  pixelx = (x - crval[0]) / cdelt[0] + (crpix[1] - 1)
should be:
  pixelx = (x - crval[0]) / cdelt[0] + (crpix[0] - 1)

I found the problem using 0.6.3, but looking at the source, it persists in 0.6.4.

**Comment by Cadair** [comment]
Can you provide a link to the source code please? If you click on the line number on github it will give you a link.

Thanks for the bug report.

**Comment by wafels** [comment]
https://github.com/sunpy/sunpy/blob/2052149cdd85e600ac4ec2724eab852e30bb255e/sunpy/wcs/wcs.py#L136

**Comment by Cadair** [comment]
yes, that is a bug. What's noteworthy is that we don't use that code in map anymore.

@thothsartre What are you using that implementation of `data_to_pixel` doing that conversion through `Map.data_to_pixel()` is better as it accounts for rotation correctly.

**Comment by thothsartre** [comment]
Thanks for the pointer to Map.data_to_pixel(); looks like it'll take a bit more code to set up, but should work well.  I'm extracting portions of data read from FITS files given data coordinates, and convert_data_to_pixel was used to get the corresponding image coordinates.

**Comment by Cadair** [comment]
@thothsartre If you want to extract a sub section of an image from a larger image you can use [`Map.submap()`](http://docs.sunpy.org/en/stable/code_ref/map.html#sunpy.map.mapbase.GenericMap.submap) where you can specify the arguments in either data or image coordinates. HTH.

**Comment by thothsartre** [comment]
@Cadair  Many thanks!  That's very helpful.
