### ISSUE TITLE
Database does not store HDU index

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1771]
When constructing entries from a fits file the HDU index is not stored in the record meaning you can not do the reverse mapping from DatabaseEntry -> HDU.

**Comment by Cadair** [comment]
ping @derdon

**Comment by abit2** [comment]
@Cadair Can you tell me about HDU index.

**Comment by agneet42** [comment]
@Cadair in DatabaseEntry Class[in tables.py], the docs don't mention storing the hdu_index. Should I open a PR making this change in the doc and then work on it further, by **saving** it in the database?

**Comment by Cadair** [comment]
One file path can be in multiple records, but a combination of HDU index and file path should be unique.

I can't remember the table layout though.

**Comment by agneet42** [comment]
@Cadair shouldn't this[[https://github.com/sunpy/sunpy/blob/master/sunpy/database/tables.py#L224](url) doc mention that hdu_index is being stored in the database? This is missing if I am correct.

**Comment by Cadair** [comment]
The point of this issue is that it isn't being stored.

**Comment by agneet42** [comment]
Yes. But after [this](https://github.com/sunpy/sunpy/pull/1952) PR, this(https://github.com/sunpy/sunpy/blob/master/sunpy/database/tables.py#L253) line was added, but the DataBase Class Parameters were not upgraded (https://github.com/sunpy/sunpy/blob/master/sunpy/database/tables.py#193). I hope I am getting through?

**Comment by Cadair** [comment]
That is a good point.

**Comment by Cadair** [comment]
Also, the map factory should be updated to use hdu index.

**Comment by agneet42** [comment]
Okay @Cadair , I'll work on it.
