### ISSUE TITLE
Add tests for memory mapping in sunpy.io

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1774]
We forgot to add tests in the #1750

**Comment by akash5100** [comment]
I want to work on this issue. Can I get more details? Test for all the functions in [#1750](https://github.com/sunpy/sunpy/pull/1750/files#diff-d36b7bf5746105cca76c92359e41bae3bafe8c2bb0b55f1a0483f52e891acca3)?

**Comment by nabobalis** [comment]
I would assume to test that memmap is passed correctly and implemented.

**Comment by akash5100** [comment]
This will be a test for the `read_file` function to test `memmap` as an argument.

**Comment by nabobalis** [comment]
Sounds like a good place to start.
