### ISSUE TITLE
Update the meta information when using aiaprep

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1778]
After running `aiaprep` we should create/update the `HISTORY` tag on the header, so if the file is saved it contains which modification has been done.

I believe this should include not just `aiaprep run` but also the version of SunPy used, and maybe other information that could be helpful to trace the file backwards to its origins.

**Comment by swapsha96** [comment]
@dpshelio Can you suggest how to amend this change?

**Comment by wtbarnes** [comment]
I'm going to close this as `aiaprep` will be removed in the near future in favor of using the [aiapy package](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy). See #3282

**Comment by dpshelio** [comment]
@wtbarnes did you add that issue into `aiapy`? I quickly checked the `prep.py` and the issue list and I didn't find anything about this. This is important as support reproducibility.

**Comment by wtbarnes** [comment]
Hmm it looks like I didn’t😅I’ll create one now. 

Is there a standard way to format what goes in HISTORY? Do we update this keyword anywhere else in sunpy? 

I’ve run into cases before where stuff in COMMENT or HISTORY has caused headaches when reading files so I just want to make sure we’re being FITS compliant when modifying or appending to these keys.

**Comment by wtbarnes** [comment]
See https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/56
