### ISSUE TITLE
Test failures with the developer version of Numpy

### ISSUE THREAD

**Issue by astrofrog** [sunpy/sunpy#1805]
Numpy has made rules on slice indices more strict in the latest developer version - in particular, float indices are no longer allowed. Currently quite a few tests fail with errors like:

```
E       TypeError: slice indices must be integers or None or have an __index__ method
```

So it would be good to fix those for compatibility with Numpy 1.12 once it comes out.

Note that you can easily add a build with numpy dev on Travis using ``NUMPY_VERSION=dev`` - you could mark it as an allowed failure for now.

**Comment by sanskar-modi** [comment]
Can someone help me reproducing it. I want to solve this.

**Comment by Cadair** [comment]
did you install sunpy using conda?

**Comment by sanskar-modi** [comment]
no, i install it from source.

**Comment by Cadair** [comment]
sorry, badly worded question, did you install python using conda? or do you have virtual envs?

anyway you can either install numpy from source by doing `pip install git+http://github.com/numpy/numpy` or by cloning it and installing using `pip install -e .` from within the checkout.

**Comment by sanskar-modi** [comment]
@Cadair #1808

**Comment by sanskar-modi** [comment]
@Cadair i think it should be closed ??

**Comment by Cadair** [comment]
Thanks again @sanskar-modi
