### ISSUE TITLE
Sunpy.time.parse_time Doesn't Work With Leap Seconds

### ISSUE THREAD

**Issue by mjpauly** [sunpy/sunpy#1845]
I encountered this bug when trying to do aiaprep where 'date-obs' (in the original fits file header) had a value that included a leap second. Here's an example fits file: http://jsoc.stanford.edu/SUM51/D337548770/S00000/image_lev1.fits.
`ValueError: 2012-06-30T23:59:60.62 is not a valid time string!`

**Comment by Cadair** [comment]
Hi @mjpauly Thanks for the bug.

I will investigate tomorrow.

**Comment by ayshih** [comment]
That's because our implementation still depends on `datetime`, which does not handle leap seconds.  We need to switch to `astropy.time`.  See issue #993 (which highlights the same leap second, unsurprisingly).

**Comment by Cadair** [comment]
I suspected that was the problem. We should fix that...

**Comment by wafels** [comment]
using astropy.time is slated for the 0.8 release...

**Comment by Cadair** [comment]
closing as a duplicate of #993. Thanks @mjpauly
