### ISSUE TITLE
`peek()` on HMI map reverses axes

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#1847]
Using the `peek()` method on a `sunpy.map.Map` causes both the x and y axes to be flipped, i.e. +1030 shows up on the left on the x-axis and -1030 shows up on the top on the y-axis. A similarly constructed AIA map does __not__ have this problem.

A minimal working example (from a [solarbextrapolation example](http://docs.sunpy.org/projects/solarbextrapolation/en/latest/auto_examples/plot_potential_extrapolation_of_hmi_data.html)) is included below with an AIA map for comparison.

Using release 0.7 on Mac OS X

## MWE
```Python
from sunpy.net import vso
from sunpy.map import Map
client = vso.VSOClient()
result_hmi = client.query(
   vso.attrs.Time((2011, 2, 14, 20, 34, 0), (2011, 2, 14, 21, 0, 0)), 
   vso.attrs.Instrument('HMI'),              
   vso.attrs.Physobs('LOS_magnetic_field'),  
   vso.attrs.Sample(4000 * u.s)
 )
data_hmi = client.get(result_hmi, methods=('URL-FILE_Rice', 'URL-FILE')).wait()
result_aia = client.query(
   vso.attrs.Time((2011, 2, 14, 20, 34, 0), (2011, 2, 14, 21, 0, 0)), 
   vso.attrs.Instrument('AIA'), 
   vso.attrs.Physobs('intensity'), 
   vso.attrs.Sample(4000 * u.s) 
)
data_aia = client.get(result_aia, methods=('URL-FILE_Rice', 'URL-FILE')).wait()
Map(data_hmi[0]).peek()
Map(data_aia[0]).peek()
```
![hmi_bug_ex](https://cloud.githubusercontent.com/assets/8676141/16477344/794e6cea-3e56-11e6-911a-766efb94ac6a.png)
![aia_not-bug_ex](https://cloud.githubusercontent.com/assets/8676141/16477348/85a9898e-3e56-11e6-91c8-52d3bb77ddd2.png)

**Comment by Cadair** [comment]
This is due to the fact that HMI data is rotated ~180 deg from AIA data at level 1. So map represents the data as it is in the file, which is rotated ~180 deg.

**Comment by wtbarnes** [comment]
Oh ok. I see now. Apologies for the unwarranted issue.

**Comment by Cadair** [comment]
Not a problem :)
