### ISSUE TITLE
Calling `.resample()` on HMI submap reverses sign on x- and y-axis 

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#1855]
I don't know whether this is a bug or I am just not understanding what is going on here. 

I understand that HMI data is rotated 180 deg. (relative to say, AIA) (per #1847). When a submap is created, the results are expected, with just the direction of the axes reversed. However, when the same submap is resampled, the x and y axes change signs though the ROI is the same. See example below.

## MWE
```Python
from sunpy.net import vso
from sunpy.map import Map
client = vso.VSOClient()
result_hmi = client.query(
   vso.attrs.Time((2011, 2, 14, 20, 34, 0), (2011, 2, 14, 21, 0, 0)), 
   vso.attrs.Instrument('HMI'),              
   vso.attrs.Physobs('LOS_magnetic_field'),  
   vso.attrs.Sample(4000 * u.s)
 )
data_hmi = client.get(result_hmi, methods=('URL-FILE_Rice', 'URL-FILE')).wait()
hmi_map = sunpy.map.Map(data_hmi[0])
hmi_submap = hmi_map.submap(u.Quantity([50,300]*u.arcsec),u.Quantity([-350,-100]*u.arcsec))
hmi_submap_resampled = hmi_submap.resample(u.Quantity([20,20]*u.pixel),method='linear')
hmi_map.peek()
hmi_submap.peek()
him_submap_resampled.peek()
```
![image](https://cloud.githubusercontent.com/assets/8676141/17190836/f04656f2-540c-11e6-989e-40fc6ffd4fb2.png)
![image](https://cloud.githubusercontent.com/assets/8676141/17191092/08f00b20-540e-11e6-9fe5-f7e94424ee62.png)
![image](https://cloud.githubusercontent.com/assets/8676141/17191095/0d2af04c-540e-11e6-8135-61d5f8daa7db.png)

**Comment by Cadair** [comment]
I think this was raised in IRC on Monday. It smells of bug.

**Comment by wtbarnes** [comment]
For what it's worth, if you first resample and then crop, this problem does __not__ occur.

**Comment by Cadair** [comment]
ok, so there is something wonky in the resample code.

**Comment by Cadair** [comment]
I knew this day would come. It is time to work out what `map.center` does because it's broken: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L446

According to this: https://github.com/sunpy/sunpy/blob/master/sunpy/wcs/wcs.py#L80 it "returns the centre of the image in data coordinates", so is that not the same as doing `map.pixel_to_data(map.dimensions/2)` ??

**Comment by wtbarnes** [comment]
To add to the confusion, this problem does not _seem_ to show up in AIA maps. So maybe this is a result of the reversal of the HMI axes to account for the 180 deg. rotation?

**Comment by larrymanley** [comment]
Is submap making an assumption about axis orientation?  See beginning at line 1146 of mapbase.py

**Comment by wtbarnes** [comment]
@larrymanley that seems likely since calling `.rotate(angle=180.*u.degree)` on the HMI map before resampling/cropping (in either order) fixes this problem.

**Comment by Cadair** [comment]
I ran your example above and #1863 seems to fix this.
