### ISSUE TITLE
Use a logger for messages and prints

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1859]
The idea would be to remove the prints and change them by log entries, probably using a logging system that astropy has (linked above). We haven't thought much on the implementation, but we could also follow astropy on that.

I think we should use `logging` instead of `print` within the module, so users can choose the amount of information they want to see in their screens.
- [Logging documentation](https://docs.python.org/3.5/library/logging.html)
- [why using logging](http://stackoverflow.com/a/6918596/1087595)
- [stop using `print`](http://inventwithpython.com/blog/2012/04/06/stop-using-print-for-debugging-a-5-minute-quickstart-guide-to-pythons-logging-module/)
- [astropy loggin](http://docs.astropy.org/en/stable/logging.html)

The big thing we should use the logger for imo is warnings, much like astropy do [here](https://github.com/astropy/astropy/blob/51c619e5ffe7aaf748e7c34d08c6336762decc74/astropy/logger.py#L139).

**Comment by Cadair** [comment]
Do we use print that much? I thought we mostly used warnings?

**Comment by dpshelio** [comment]
I've seen it here and there, and I was thinking we should write some "rules" in the documentation about it.

**Comment by Cadair** [comment]
for info see this: http://docs.astropy.org/en/stable/logging.html

**Comment by Gbear605** [comment]
Print is used in https://github.com/sunpy/sunpy/blob/master/sunpy/util/sysinfo.py, https://github.com/sunpy/sunpy/blob/master/sunpy/conftest.py, https://github.com/sunpy/sunpy/blob/master/sunpy/sun/sun.py, https://github.com/sunpy/sunpy/blob/master/sunpy/util/config.py, https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py, https://github.com/sunpy/sunpy/blob/master/sunpy/net/helio/hec.py, https://github.com/sunpy/sunpy/blob/master/sunpy/data/_sample.py, https://github.com/sunpy/sunpy/blob/master/sunpy/spectra/sources/swaves.py, https://github.com/sunpy/sunpy/blob/master/sunpy/lightcurve/sources/fermi_gbm.py, https://github.com/sunpy/sunpy/blob/master/sunpy/instr/lyra.py, https://github.com/sunpy/sunpy/blob/master/sunpy/roi/chaincode.py, https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py, https://github.com/sunpy/sunpy/blob/master/sunpy/instr/rhessi.py, https://github.com/sunpy/sunpy/blob/master/sunpy/map/compositemap.py, https://github.com/sunpy/sunpy/blob/master/sunpy/image/coalignment.py. It should be noted that not all of these actually should be changed, and there may also be some that I missed.

Print is also used in a large number of tests, examples, and tutorials that don't need to be changed.

**Comment by swapsha96** [comment]
@dpshelio Could you please guide me through this?

**Comment by dpshelio** [comment]
@swapsha96 The idea would be to remove the prints and change them by log entries, probably using a logging system that astropy has (linked above). I haven't thought much on the implementation, but we could also follow astropy on that.

**Comment by Cadair** [comment]
The big thing we should use the logger for imo is warnings, much like astropy do [here](https://github.com/astropy/astropy/blob/51c619e5ffe7aaf748e7c34d08c6336762decc74/astropy/logger.py#L139).
