### ISSUE TITLE
Use logger for messages

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1860]
I think we should use `logging` instead of `print` within the module, so users can choose the amount of information they want to see in their screens.

- [Logging documentation](https://docs.python.org/3.5/library/logging.html)
- [why using logging](http://stackoverflow.com/a/6918596/1087595)
- [stop using `print`](http://inventwithpython.com/blog/2012/04/06/stop-using-print-for-debugging-a-5-minute-quickstart-guide-to-pythons-logging-module/)

**Comment by ehsteve** [comment]
@dpshelio why was this closed?

**Comment by Cadair** [comment]
It's a duplicate of #1859
