### ISSUE TITLE
Update dimensions metadata when resampling a map

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#1870]
Currently, after resampling a map, the `naxis1` and `naxis2` entries in the metadata, which hold the dimension of each axis, are not updated. See [the resample method in `sunpy/map/mapbase.py`](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L821). 

This should be just a matter of adding two lines in the update metadata section of the resample method.

See example below

Map from sample data. Note that the metadata gives the x and y dimensions as 1024 and that it gives the same output as the `dimensions` property.
```Python
>>> import sunpy.map                                                         
>>> import sunpy.data.sample                                                 
>>> aia_test_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
>>> aia_test_map.dimensions
... Pair(x=<Quantity 1024.0 pix>, y=<Quantity 1024.0 pix>)            
>>> aia_test_map.meta['naxis1']
... 1024
>>> aia_test_map.meta['naxis2']
... 1024
```

Now resample the map to 100-by-100 pixels
```Python
>>> import astropy.units as u
>>> aia_test_map_resampled = aia_test_map.resample([100,100]*u.pixel)
>>> aia_test_map_resampled.dimensions
... Pair(x=<Quantity 100.0 pix>, y=<Quantity 100.0 pix>)
>>> aia_test_map_resampled.meta['naxis1']
... 1024
>>> aia_test_map_resampled.meta['naxis2']
... 1024
```

So after resampling, the metadata remains unchanged though the dimensions are updated with the resampling. 

Though maybe the original resolution of the map should be preserved in the metadata.

**Comment by Cadair** [comment]
out of interest, what are you doing with these keys where this matters?

**Comment by wtbarnes** [comment]
I was creating a meshgrid from the X and Y ranges of the map and needed the corresponding ranges of each. I ended up just using the `.dimensions` property which is better anyway.

It just seemed strange to me that these weren't updated when the dimensions were changed.

**Comment by dpshelio** [comment]
would this affect when writing it into a fits file? if not we should hide `naxisX` so people don't get the habit to check for them, or update them accordingly.

**Comment by Cadair** [comment]
@dpshelio I think  astropy.io.fits will overwrite any NAXIS keys with the actual correct values on save.

**Comment by prateekiiest** [comment]
what is needed to be changed here, in the code??

**Comment by prateekiiest** [comment]
you mean to say that the dimension ranges for x axis (900 to -900) be changed also similarly for the y axis?
![sphx_glr_map_resampling_and_superpixels_002](https://cloud.githubusercontent.com/assets/16035442/22537817/adb63a20-e933-11e6-9fdc-170b63620be6.png)

**Comment by wtbarnes** [comment]
Not the ranges but the dimensions of the map (i.e. the number of pixels in the x/y direction) listed in the metadata. See example below

Map from sample data. Note that the metadata gives the x and y dimensions as 1024 and that it gives the same output as the `dimensions` property.
```Python
>>> import sunpy.map                                                         
>>> import sunpy.data.sample                                                 
>>> aia_test_map = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
>>> aia_test_map.dimensions
... Pair(x=<Quantity 1024.0 pix>, y=<Quantity 1024.0 pix>)            
>>> aia_test_map.meta['naxis1']
... 1024
>>> aia_test_map.meta['naxis2']
... 1024
```

Now resample the map to 100-by-100 pixels
```Python
>>> import astropy.units as u
>>> aia_test_map_resampled = aia_test_map.resample([100,100]*u.pixel)
>>> aia_test_map_resampled.dimensions
... Pair(x=<Quantity 100.0 pix>, y=<Quantity 100.0 pix>)
>>> aia_test_map_resampled.meta['naxis1']
... 1024
>>> aia_test_map_resampled.meta['naxis2']
... 1024
```

So after resampling, the metadata remains unchanged though the dimensions are updated with the resampling. 

Though maybe the original resolution of the map should be preserved in the metadata...

**Comment by Cadair** [comment]
is it worth just removing the 'naxis' keywords from the metadata completely?

**Comment by wtbarnes** [comment]
Well 'naxis1' and 'naxis2' are used in the [`reference_pixel` property](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L568). It is probably easiest to just add two lines in the `resample` method to update them.

**Comment by prateekiiest** [comment]
@Cadair , @wtbarnes  created a PR related to this --  #2010

**Comment by wtbarnes** [comment]
Given that the general consensus (for now at least) is that we don't want to much with header keywords, I'm going to close this very old issue.
