### ISSUE TITLE
Test coverage for XRT and TRACE

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1891]
The map sources for XRT and TRACE need to have tests.

**Comment by abit2** [comment]
Map creates a empty list when using tri fits files (writing tests for Trace Map)
http://pastebin.com/GctWBNDN

**Comment by abit2** [comment]
should i make a PR but it's failing tests @Cadair

**Comment by abit2** [comment]
@Cadair as we discussed in chat that it needs some test data for trace instrument can you please add some.

**Comment by wafels** [comment]
Only TRACE JP2 Helioviewer files are supported.

**Comment by wafels** [comment]
There are tests for XRT - see https://github.com/sunpy/sunpy/blob/master/sunpy/map/sources/tests/test_xrt_source.py .
