### ISSUE TITLE
SunPy to Intensity sensitivity for CallistoSpectrogram

### ISSUE THREAD

**Issue by gmlaghari** [sunpy/sunpy#1898]
@Cadair Is it possible in SunPy that it can show only those files where we have radio signature in Callisto fits data and reject the rest files on the basis of intensity sensitive algorithm! As Callisto data for 10 Years is too large to look for each file.

**Comment by dpshelio** [comment]
@gmlaghari SunPy, at the moment, doesn't have any automated detection tools. However, you can create a program using any python library that detects what you want and use sunpy for querying and reading the Callisto data. For example, you could use some kind of thresholding (does this file has a value larger than X) for each file. That will be too simple to do what you want, but it's a starting point.
Nevertheless, you will have to download all the data, analyse it, and then filter what bits you want.

A more systematic approach would be to get a list of flares of these 10 years, filter them to the day-hours of the station you want to study, and then download the files within a range before and after the flare time. You can get flare lists from within sunpy using `hek` and `helio`. Similarly you could do with CMEs or other phenomena you are interested.

**Comment by gmlaghari** [comment]
@dpshelio Thank u so much. One more please, could you tell how to use tstart, tend commands in SunPy to merge files for the particular date in one spectral plot? Eg: I have files present in the path /home/astro/caldata/ how to use this path in tstart, tend and merge them, let's say 10 files in one spectral plot.

**Comment by dpshelio** [comment]
@gmlaghari - you could use `read_many` or `join_many` as shown at the end of the [spectra section on the documentation](http://docs.sunpy.org/en/stable/guide/data_types/spectra.html). So, you can load the files you want and visualise them. If you want to use the `tstart` and `tend` from the `from_range` will try to download the data again.

I would suggest you to use the [mailing list](http://groups.google.com/group/sunpy) for questions on how to use the tools as that's more appropriate than in here as you are more likely to get a quicker response by other users than in here.

**Comment by dpshelio** [comment]
@gmlaghari please refer to the [documentation](http://docs.sunpy.org/en/stable/guide/data_types/spectra.html#spectrograms) and use the [mailing list](http://groups.google.com/group/sunpy) for questions about how to use sunpy - you are more likely to get a quicker response. Issues (i.e. here) it's mostly aimed to notify problems/bugs/feature requests.

To answer your question, I imagine you could do the following:
```python
import os

from sunpy.spectra.sources.callisto import CallistoSpectrogram

callistofiles = os.listdir('/home/astro/caldata/')
callistodata = CallistoSpectrogram.read_many(callistofiles)
all_callisto = CallistoSpectrogram.join_many(callistodata)

all_callisto.peek()
```
I've not tried the above with files, but I imagine this should do what you want. I'm closing the issue now, please, refer to the mailing list for further questions. Thank you.
