### ISSUE TITLE
Add narrative documentation, API documentation and gallery examples for Fido and net refactor

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1900]
We should add a good set of examples to the `unidown` branch both as a way to test sanity of the API and for documentation.

**Comment by prateekiiest** [comment]
I would like to work on this.

**Comment by prateekiiest** [comment]
@Cadair , @dpshelio  can I take up with this issue?

**Comment by Cadair** [comment]
@prateekiiest of course!
