### ISSUE TITLE
convert_hcc_hg using wrong longitude definition

### ISSUE THREAD

**Issue by ZachWerginz** [sunpy/sunpy#1905]
The function convert_hcc_hg() in the wcs module of sunpy references equation 12 in Thompson. In the sunpy docs it says that L0 is "Carrington longitude of central meridian as seen from Earth. Default is 0." whereas in the Thompson it says "B0 and Φ0 are the Stonyhurst heliographic latitude and
longitude of the observer". Considering the fits files I work with use L0 as defined by Carrington rotation, I thought I would use that fits keyword with the function. Now I think that the function is not correct.

**Comment by Cadair** [comment]
Hey @ZachWerginz thanks for opening the issue.

From having a quick look at `convert_hcc_hg` the `L0` argument seem to be an arbitrary longitude offset. For an Earth-based observer this would be equivalent to the `L0` defined in Thompson as the Carrington longitude of central meridian as seen from Earth. If you wanted to calculate the HG Stonyhurst coordinates for a non-Earth based observer this `L0` would be the same as Φ0, if you wanted to calculate the Carrington HG coordinates for a non-Earth based observer this `L0` argument would need to be L0 + Φ0 from Thompson.

I would highly recommend having a look at the new (in 0.7) coordinates module http://docs.sunpy.org/en/stable/code_ref/coordinates.html as it is *much* improved over the `sunpy.wcs` module and we will be removing `sunpy.wcs` in a release or two so we don't have to maintain multiple versions of the same code. In `sunpy.coordinates` when you define a `HelioprojectiveFrame` there is an argument called `L0` in `sunpy.coordinates` this is exactly the same as Φ0 from Thompson and the conversion to Carrington HG is done using only the time of the observation using this function: http://docs.sunpy.org/en/stable/generated/api/sunpy.sun.heliographic_solar_center.html

**Comment by ZachWerginz** [comment]
So if I wanted the HG Stonyhurst coordinates for a earth bases observer does this mean I should not pass the L0 keyword to these functions? This wording seems confusing.

**Comment by Cadair** [comment]
yes in that case `L0 = 0` would be the correct call.

**Comment by ZachWerginz** [comment]
Ok that makes sense, sorry for the confusion then. I was so caught up in the vocabulary that I though something might have been wrong. Thanks for the clarification!

**Comment by Cadair** [comment]
@ZachWerginz not a problem it's not very clear. Having a quick look over the documentation it's not much clearer in `sunpy.coordinates` either so I will have to improve that.
