### ISSUE TITLE
Improve support for local data

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#191]
Many of the recently-added SunPy classes have the ability to download data for the user, and users can now control where that data gets saved to by modifying a configuration parameter in their sunpyrc file. SunPy users will also likely already have some data downloaded via SSW, etc.

Support should be added to SunPy to both make use of this existing data, and to store newly downloaded data in such a way that it can be easily accessed and re-used in the future.

Some issues to consider:
- [x] Default path to store data? (e.g. data/<instrument>/<measurement>/)
- [x] Support for users to override the default directory structure -- for example, perhaps a config parameter could enable them to construct their preferred organization using a set of parameters like "<observatory>", "<detector>", "<year>", "<month>", etc?
- [x] Storing data in multiple locations - perhaps user can provide a list of locations to scan for data?
- [ ] Compatibility with SSW data archives
- [ ] Finding existing data from SSW, etc. if it is likely to be stored in a known place?
- [ ] Allowing users to set a limit on how much data should be stored? (e.g. data archive functions like a cache).

**Comment by dpshelio** [comment]
I think we got point 1 and 2 already. 3 looks useful and I think the db can handle that. 4 and 5 may be attractive for some people.
6 can be helpful too, but it would need to set a list of rules regarding when to delete old files or pause the download.

I propose to break this issue in smaller ones, so they are easier to track.

**Comment by wtbarnes** [comment]
Point 3 is covered by the database subpackage?

Points 4 and 6 seem like they're covered by #3124? 

If I understand it correctly, I'm not sure point 5 is something we even want to do at this point.

**Comment by Cadair** [comment]
Yeah I think we have got as far as we want to for now with this as well.
