### ISSUE TITLE
VSOClient.query returns no result in Python 3.5

### ISSUE THREAD

**Issue by ArcturusB** [sunpy/sunpy#1912]
When using the canonical example from the documentation on [how to use the VSO client](http://docs.sunpy.org/en/stable/guide/acquiring_data/vso.html) : 

``` python
from sunpy.net import vso
client=vso.VSOClient()
qr = client.query(vso.attrs.Time('2001/1/1', '2001/1/2'), vso.attrs.Instrument('eit'))
```

**Python 2.7**: 122 elements are returned as they should:

``` python
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sunpy.net import vso
/usr/lib/python2.7/site-packages/matplotlib/__init__.py:1041: UserWarning: Duplicate key in file "/home/gabriel/.config/matplotlib/matplotlibrc", line #161
  (fname, cnt))
>>> client=vso.VSOClient()
>>> qr = client.query(vso.attrs.Time('2001/1/1', '2001/1/2'), vso.attrs.Instrument('eit'))
>>> len(qr)
122
```

**Python 3.5**: no elements are returned:

``` python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sunpy.net import vso
>>> client=vso.VSOClient()
>>> qr = client.query(vso.attrs.Time('2001/1/1', '2001/1/2'), vso.attrs.Instrument('eit'))
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://virtualsolar.org/VSO/VSOi" xmlns:ns2="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <SOAP-ENV:Header/>
   <ns0:Body>
      <ns1:Query>
         <body>
            <block>
               <time>
                  <start>20010101000000</start>
                  <end>20010102000000</end>
               </time>
               <instrument>eit</instrument>
            </block>
         </body>
      </ns1:Query>
   </ns0:Body>
</SOAP-ENV:Envelope>
>>> len(qr)
0
```

Thus, `sunpy.net.VSOClient.query` appears to be broken in python 3.5.

**Comment by Cadair** [comment]
I can not reproduce this:

```python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: >>> from sunpy.net import vso
   ...: >>> client=vso.VSOClient()
   ...: >>> qr = client.query(vso.attrs.Time('2001/1/1', '2001/1/2'), vso.attrs.Instrument('eit'))
   ...:

In [2]: len(qr)
Out[2]: 122
```

can you provide the output of `sunpy.system_info()` please?

**Comment by ArcturusB** [comment]
Sure: 

~~~
==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
Time : Wednesday, 12. October 2016 07:32am UT
System : Linux
Processor : 
Arch : 64bit
SunPy : 0.8.dev7104
SunPy_git : 2669902928df32c543480e735d93c7c205c10c0e
OS: arch   (Linux 4.7.6-1-ARCH )


###########
 Required Libraries 
###########
Python: 3.5.2
NumPy: 1.11.2
SciPy: 0.18.1
matplotlib: 1.5.2
Astropy: 1.1.2
Pandas: 0.19.0


###########
 Recommended Libraries 
###########
beautifulsoup: 4.5.1
PyQt: NOT INSTALLED
SUDS: 1.3.2.0
Sqlalchemy: 1.1.0
Requests: 2.11.1
~~~

**Comment by Cadair** [comment]
I still can't reproduce this, are you still having the problem? does it happen for other / all date ranges?

**Comment by Cadair** [comment]
@ArcturusB You still suffering from this?

**Comment by ArcturusB** [comment]
Sorry for the late answer. Yes, I'm still experiencing this issue, even after upgrading (see new `sunpy.system_info()` below). 

The issue happens with any date I choose, and with instrument EIT or AIA. 

~~~
###########
 General
###########
Time : Thursday, 03. November 2016 09:12am UT
System : Linux
Processor : 
Arch : 64bit
SunPy : 0.8.dev7144
SunPy_git : 86d7586b628a542b78a302792e37e15d790ba335
OS: arch   (Linux 4.7.6-1-ARCH )

###########
 Required Libraries 
###########
Python: 3.5.2
NumPy: 1.11.2
SciPy: 0.18.1
matplotlib: 1.5.2
Astropy: 1.2.1
Pandas: 0.19.0

###########
 Recommended Libraries 
###########
beautifulsoup: 4.5.1
PyQt: NOT INSTALLED
SUDS: 1.3.2.0
Sqlalchemy: 1.1.1
Requests: 2.11.1
~~~

**Comment by Cadair** [comment]
I unknowingly managed to reproduce this yesterday. I will investigate.

**Comment by Cadair** [comment]
@ArcturusB How did you install SunPy? Am I interpreting you system_info output correctly in that you are running Arch Linux?

I managed to replicate this on system python on arch.

**Comment by Cadair** [comment]
@ArcturusB if you are on Arch do you get this:
```
 ❯ pip freeze | grep suds
suds-py3==1.3.2.0
```
?

**Comment by nabobalis** [comment]
ITS FINE WE CAN FIX THIS. JUST WAIT FOR PACKAGE AUR UPDATE COMING SOON #ARCH #LINUX #SNOWEDIN #MAGA

**Comment by Cadair** [comment]
So further investigation (real time thread updating here) leads me to conclude the issue is in that under arch we used the already packaged https://github.com/cackharot/suds-py3 library while when installing from pip or conda we have been using https://bitbucket.org/jurko/suds.

I uninstalled `python-suds` from the AUR and installed `suds-jurko` from pip to verify this. As my eccentric friend @nabobalis says, he will update the AUR package soon.

**Comment by nabobalis** [comment]
Having spoken to the relevant parties and many who were not relevant to anything. The AUR packages have been updated, so this issue should now be fixed. You might have to run pacman -Rdd python-suds before the update since the two suds will conflict and pacman will break due to dependencies. 

I re-ran the test code at the top and it worked out issues.

**Comment by Cadair** [comment]
You shouldn't have to `-Rdd` as you put conflicts here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-suds-jurko#n12 it should prompt you to swap them out.

**Comment by nabobalis** [comment]
Yes, but the conflict is on the sunpy dependency.  Since to remove suds conflicts as the old version of sunpy has it as a hard dependency.

**Comment by ArcturusB** [comment]
Hello, I’ve updated the dependency from `python-suds` to `python-suds-jurko` in AUR package [`python-sunpy-git`][1], which fixed the issue.

It is sufficient to reinstall `python-sunpy-git`. Since `python-suds` conflicts with `python-suds-jurko`, the user is prompted to swap these two versions. 

[1]: https://aur.archlinux.org/packages/python-sunpy-git/

**Comment by Cadair** [comment]
Thanks @ArcturusB, for both the report and updating the AUR package :)

**Comment by ArcturusB** [comment]
Thanks to you for the the diagnostic! ;)
