### ISSUE TITLE
Fix or remove fermi tests

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1918]
in #1902 one of the fermi tests was removed, because the numbers appear to have changed. This needs investigating by someone who knows more about the instrument and a proper fix developing.

**Comment by aringlis** [comment]
@Cadair I will try to look at this.

**Comment by Cadair** [comment]
thanks!

**Comment by nabobalis** [comment]
If lightcurve is dead, does this need to be open? Does it affect time series?

Should I add a timeseries label?

**Comment by Cadair** [comment]
the code this is referring to is actually in `instr`

**Comment by dstansby** [comment]
This seems to have been un-skipped and fixed at some point.
