### ISSUE TITLE
Provide ability to read IDL genx files

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1927]
Most of the files in SSW are genx files which contain a lot of data which would be useful for SunPy. It may be useful to provide this capability to help migrate from IDL. Discuss below whether this is worthwhile for SunPy to provide this.

**Comment by Cadair** [comment]
@wtbarnes @dpshelio Can you link to the relevant IDL code and other info here please?

**Comment by wtbarnes** [comment]
Here's just a few to get started. I haven't had much luck finding good examples about how to actually read an xdr file (though see last bullet point) though it seems that once you know the structure of the file, it should be relatively easy (though perhaps a bit tedious). 

* [SSW directory with relevant read/write functions](https://darts.isas.jaxa.jp/pub/ssw/gen/idl/io/)
* [Docs for `xdrlib` in Python](https://docs.python.org/2/library/xdrlib.html)
* [Some general (but ancient) info about the eXternal Data Representation (XDR) standard](https://tools.ietf.org/html/rfc1832.html)
* [Old mailing list discussion about reading xdr files with `xdrlib`](https://mail.python.org/pipermail/python-list/2010-August/585550.html)

Haven't had time to mess around with this much yet, but

```Python
>>> import xdrlib
>>> f = open('/path/to/ssw/sdo/aia/response/aia_V6_all_fullinst.genx','rb').read()
>>> up = xdrlib.Unpacker(f)
```
seems to be a good place to start.

**Comment by Cadair** [comment]
Wow 15 day turn around on a major feature request. Good work @dpshelio :D

**Comment by joyvelasquez** [comment]
Hello all,

Question, how would one read geny files into a python editor?
Would ( import xdrlib ) be they was to go? I am having trouble with the structure of data once I read it in.
'/path/to/ssw/sdo/xrt/response/channels/xxxxx.geny

**Comment by nabobalis** [comment]
Hi @joyvelasquez, sunpy has a reader for these kind of files here: https://docs.sunpy.org/en/stable/code_ref/io.html#module-sunpy.io.special.genx 

If this doesn't work, please open an issue and we can try to debug it.
