### ISSUE TITLE
Helioviewer JP2 files look terrible using map.peek()

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#1935]
SunPy maps read the header information and apply stretching assuming that the origin was a FITS file, not a JP2 file.  However  helioviewer JP2 images have already been stretched appropriately for use with helioviewer clients.   SunPy maps made from helioviewer JP2 files would look acceptable using the astropy LinearStretch() function.

**Comment by Cadair** [comment]
Is there something in the header which encodes this fact? Something we can check in the meta dict to know if it's been scaled? Once the Map get's the file, it has no idea what file it came from.

**Comment by wafels** [comment]
Doesn't seem to be anything in the map meta which indicates that the map
came from a helioviewer JP2 file.

However, every Helioviewer JP2 file header contains a <helioviewer> XML
tag.  We could look for that when reading the file in.  The ideal behavior
after this (I think) is that the Helioviewer JP2 file would pass through
the map object transparently except the plot normalization changes to
LinearStretch().

**Comment by Cadair** [comment]
either the JP2 reader or helioviewer will need to add something to meta so we can do this.

**Comment by wafels** [comment]
It's going to have to be in the JP2 reader because we're not going to take
the risk to edit all our files... I'll take a look

**Comment by wafels** [comment]
So I put in a flag to test if the input JPEG2000 file is a Helioviewer
Project JPEG2000 file:

*https://github.com/wafels/sunpy/blob/hvjp2norm/sunpy/io/jp2.py#L69
<https://github.com/wafels/sunpy/blob/hvjp2norm/sunpy/io/jp2.py#L69>*

I'm thinking that the simplest place to change the color normalization is
on a source by source basis.  For example in

*https://github.com/wafels/sunpy/blob/hvjp2norm/sunpy/map/sources/stereo.py
<https://github.com/wafels/sunpy/blob/hvjp2norm/sunpy/map/sources/stereo.py>*

the EUVI and COR1 classes could look for the presence of the Helioviewer
flag and change color normalization as appropriate.  Helioviewer does not
have any HI maps

Would this be an appropriate solution?

**Comment by Cadair** [comment]
The change to io makes sense. I am not so sure about the norm thing. I don't like the repetition of changing every source to be the same "if helioviewer then" thing, I feel as though we should be able to do that in `GenericMap`. However, with the way the `plot_settings` dict is implemented there is no real way of doing that.

**Comment by wafels** [comment]
I agree - I don't like the "if helioviewer then"... idea.  But as an
example I implemented it here

*https://github.com/wafels/sunpy/tree/hvjp2norm/sunpy/map/sources
<https://github.com/wafels/sunpy/tree/hvjp2norm/sunpy/map/sources>*

and in the EUVI STEREO source map.  As an argument in support of this
approach, you could say that the concept of source has been extended from
"instrument that made the observation" to "instrument that made the
observation" plus "representation of the data".  The addition of the notion
of repesentation might be a good one, but the implementation is not the
best.

**Comment by wafels** [comment]
So if the map is instantiated  from a JP2 file then 'helioviewer' is in meta.keys().
