### ISSUE TITLE
UnicodeDecodeError With Querying sunpy.net.hek.HEKClient() on Particular Dates

### ISSUE THREAD

**Issue by mjpauly** [sunpy/sunpy#1950]
I'm trying to query HEK using sunpy.net.hek.HEKClient(), but I'm getting a UnicodeDecodeError when I try to query some dates. Example query with traceback:

```python
In [13]: from datetime import timedelta

In [14]: start = sunpy.time.parse_time('2013/12/23')

In [15]: end = start + timedelta(days=1)

In [16]: from sunpy.net import hek

In [17]: client = hek.HEKClient()

In [18]: result = client.query(hek.attrs.Time(start, end),hek.attrs.EventType('FL'))
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-18-5488d4f586ca> in <module>()
----> 1 result = client.query(hek.attrs.Time(start, end),hek.attrs.EventType('FL'))

/Users/pauly/anaconda3/lib/python3.5/site-packages/sunpy/net/hek/hek.py in query(self, *query)
     92 
     93         if len(ndata) == 1:
---> 94             return self._download(ndata[0])
     95         else:
     96             return self._merge(self._download(data) for data in ndata)

/Users/pauly/anaconda3/lib/python3.5/site-packages/sunpy/net/hek/hek.py in _download(self, data)
     68                 self.url, urllib.parse.urlencode(data).encode('utf-8'))
     69             try:
---> 70                 result = json.load(reader(fd))
     71             finally:
     72                 fd.close()

/Users/pauly/anaconda3/lib/python3.5/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    263 
    264     #"""
--> 265     return loads(fp.read(),
    266         cls=cls, object_hook=object_hook,
    267         parse_float=parse_float, parse_int=parse_int,

/Users/pauly/anaconda3/lib/python3.5/codecs.py in read(self, size, chars, firstline)
    499                 break
    500             try:
--> 501                 newchars, decodedbytes = self.decode(data, self.errors)
    502             except UnicodeDecodeError as exc:
    503                 if firstline:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 94615: invalid continuation byte
```

It only seems to occur on certain dates, but it does that consistently with the dates it does fail on. I can provide a list of some of the dates that it fails on if it would be helpful. I am using Sunpy 0.7.3.

**Comment by simonmack** [comment]
Hi @mjpauly, have you found solution of this issue?

This isue is now present while using a basic query from tutorial: https://docs.sunpy.org/en/stable/guide/acquiring_data/hek.html.

Steps to reproduce:
-> Execute following commands:
`
from sunpy.net import hek
client = hek.HEKClient()

tstart = '2011/08/09 07:23:56'
tend = '2011/08/09 12:40:29'
event_type = 'FL'
result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
`

-> Actual results:
`---------------------------------------------------------------------------

UnicodeDecodeError                        Traceback (most recent call last)

<ipython-input-31-56d50caa6ca4> in <module>()
      5 event_type = 'FL'
      6 
----> 7 result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))

3 frames

/usr/local/lib/python3.6/dist-packages/sunpy/net/hek/hek.py in search(self, *query)
     96 
     97         if len(ndata) == 1:
---> 98             return self._download(ndata[0])
     99         else:
    100             return self._merge(self._download(data) for data in ndata)

/usr/local/lib/python3.6/dist-packages/sunpy/net/hek/hek.py in _download(self, data)
     68                 self.url, urllib.parse.urlencode(data).encode('utf-8'))
     69             try:
---> 70                 result = json.load(reader(fd))
     71             finally:
     72                 fd.close()

/usr/lib/python3.6/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    294 
    295     """
--> 296     return loads(fp.read(),
    297         cls=cls, object_hook=object_hook,
    298         parse_float=parse_float, parse_int=parse_int,

/usr/lib/python3.6/codecs.py in read(self, size, chars, firstline)
    501                 break
    502             try:
--> 503                 newchars, decodedbytes = self.decode(data, self.errors)
    504             except UnicodeDecodeError as exc:
    505                 if firstline:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 15296: invalid continuation byte

`
-> Expected result:
The events should be obtained for the specified time interval.

**Comment by nabobalis** [comment]
Hi @simonmack, that is a bug in release versions that is fixed on github but has not yet rolled out to users. Hopefully by the weekend we can get that fixed.

**Comment by dstansby** [comment]
Can this be closed as fixed?

**Comment by nabobalis** [comment]
Yeah, the bugfix have been released. IF there are any more problems, please reopen this!
