### ISSUE TITLE
sunpy fails documented self-test procedure

### ISSUE THREAD

**Issue by drzowie** [sunpy/sunpy#1959]
Here "http://docs.sunpy.org/en/stable/guide/installation/advanced.html#testing-sunpy" is the instruction to self-test Sunpy with the command "sunpy.self_test(online=False)".  Doing so yields the error message 

    >>> sunpy.self_test(online=True)               
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/sunpy/tests/__init__.py", line 78, in main
        raise ValueError(errmsg)
    ValueError: `online` parameter must have one of the following values: sunpy.tests.INCLUDE_ONLINE, sunpy.tests.EXCLUDE_ONLINE, sunpy.tests.ONLY_ONLINE

Using one of those values ,e.g. 

>>> sunpy.self_test(online=sunpy.tests.INCLUDE_ONLINE)

starts the self-test suite.

**Comment by drzowie** [comment]
(works for "online=False" also)

**Comment by Cadair** [comment]
Hello!

What version of SunPy do you have installed?

**Comment by Cadair** [comment]
Looking through the history you are at at least two versions out of date ;)

**Comment by wafels** [comment]
I tried this on a mac, using Anaconda Python 3.5.2 with SunPy versions
0.7.5 and master and was not able to reproduce the error.

**Comment by wafels** [comment]
Recommend that this is closed.
