### ISSUE TITLE
RTD docs missing links to generated indices

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#1960]
As far as I can tell, the SunPy docs on Read the Docs are missing the usual Sphinx links to generated indices ("Index" and "Modules") that can usually found in page headers (for example, see [Astropy's documentation](http://docs.astropy.org/en/stable/index.html)).  The indices are in fact being generated, just apparently not being linked to:

http://docs.sunpy.org/en/latest/genindex.html
http://docs.sunpy.org/en/latest/py-modindex.html

This may be a failing of the theme we are using in Sphinx (RTD's own), or there is some configuration setting I'm not familiar with, but I think these useful indices should be made easily accessible.

(As an aside, `modindex` needs to have its configuration fixed so that it ignores the leading `sunpy.` when grouping by letter.)

**Comment by nabobalis** [comment]
How about I add them to the front page?
