### ISSUE TITLE
suds-py3 does not work with VSO whereas suds-jurko does

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1964]
There are (at least) two Python 3 compatible forks of the suds Python library:

* https://bitbucket.org/jurko/suds
* https://github.com/cackharot/suds-py3

The `suds-jurko` fork works with VSO and `suds-py3` does not. We need to make it clear in the documentation that we depend on `suds-jurko` we should also work on debugging why `suds-py3` does not work.

#1912 is the original bug report for `suds-py3`.

**Comment by nabobalis** [comment]
I would agree with debugging why suds-py3 does not work. Since Jurko's fork has not seen an update for about 4 months now. Long term, moving might be necessary.

**Comment by nabobalis** [comment]
Closed by #2073
