### ISSUE TITLE
Helper function to open fits file based on filename and HDU

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#1970]
After #1952 is merged, the user will still have to open the file and then extract the particular desired HDU.

A helper function that would return the data and the header of that particular HDU would be useful.

**Comment by Cadair** [comment]
More specifically each database [entry](https://github.com/sunpy/sunpy/blob/master/sunpy/database/tables.py#L184) corresponds to a `data, meta` pair as long as the entry has a valid `path` attribute.

A helper method on the `DatabaseEntry` class to parse the `path` and `hdu_index` from the entry to `sunpy.io.read_file` and return the `data, meta` pair would make it easier to read the files from a database query.

**Comment by abit2** [comment]
@Cadair i would like to work on this

**Comment by shaswats007** [comment]
Is this issue still open? I'd like to work on it.

**Comment by nabobalis** [comment]
Yes and sure go ahead.

**Comment by Telomelonia** [comment]
@nabobalis @Cadair @dpshelio 
Can we achieve the same task with [`get_entry_by_id`](https://github.com/sunpy/sunpy/blob/df66b46e224199de12ea623aafb20ecc6a10c94f/sunpy/database/database.py#L637)

**Comment by nabobalis** [comment]
Hi @Telomelonia, I don't think we want to actually do this.

The plan is to remove database anyway, so there is no point on working on it. I did not go through the issues. I am sorry.
