### ISSUE TITLE
Optimizing travis CI

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#1993]
Looking at the travis runs they seem to run for an awful long time (+2hours), and I think there must be some ways to optimize it a bit more.

E.g. why are the egg_info tests install numpy? those tests should take only ~1min rather than 3+

Also one could imagine cutting back on the number of builds here and there without really loosing any coverage.

I can come up with a PR if you like the idea.

**Comment by Cadair** [comment]
@bsipocz I think the `egg_info` builds install numpy because to run `egg_info` for sunpy you need astropy. If that isn't supposed to be the case we should fix it.

I would be happy to see any suggestions for reduction in build time, thanks.

**Comment by bsipocz** [comment]
As far as I understand the process, we don't need astropy for any of the affiliates during building the egg, in fact there shouldn't be any dependencies for that process. I'll check whether I can make that work.

**Comment by bsipocz** [comment]
How frequently do you fail on with numpy dev? How do you feel about removing that from the allowed failures and combining with the astropy dev build?

**Comment by bsipocz** [comment]
@Cadair - Yes, that's the change I mentioned that I want to add to ci-helpers. Once that's done, it will work out of the box for sunpy, and I'll need to adjust ``.travis.yml`` for the rest of the packages.

**Comment by bsipocz** [comment]
Btw, I'm closing as #1994 got merged meaning a ~30mins shorter building time.
