### ISSUE TITLE
sunpy.util.net.get_filename(...) not catching correct exception when unable to find "filename" in 'Content-Disposition'

### ISSUE THREAD

**Issue by m-charlton** [sunpy/sunpy#1999]
I think that `sunpy.util.net.get_filename(...)` may be attempting to catch the 
wrong exception when a filename can't be found in the 'Content-Disposition'.

If `sunpy.util.net.get_content_disposition(...)` is called with an argument which 
does *not* include a `filename` (for example `form-data; name="fieldName"`) then
`parser.close().get_filename()` will return `None`. When we attempt to call the 
`decode()` method on a `NoneType` then an `AttributeError` is raised. But 
`sunpy.util.net.get_filename(...)` is expecting an `IndexError` to be raised if 
a filename is not found.

```python
# In sunpy/util/net.py

50  def get_content_disposition(content_disposition):
51      """ Get content disposition filename from given header. Do not include
52          "Content-Disposition:". Returns a unicode string! """
53      parser = FeedParser()
54      parser.feed('Content-Disposition: ' + content_disposition)
55      name = parser.close().get_filename()
56      if not isinstance(name, six.text_type):
56          name = name.decode('latin1', 'ignore')
58      return name
...
61  def get_filename(sock, url):
...
68        cd = sock.headers.get('Content-Disposition', None)
69        if cd is not None:
70        try:
71            name = get_content_disposition(cd)
72        except IndexError:
73            pass
74
75        if not name:
76            parsed = urlparse(url)
77            name = parsed.path.rstrip('/').rsplit('/', 1)[-1]
78        return six.text_type(name)
```

So we could make an explicit check and raise an exception in `get_content_disposition(...)`:

```python
def get_content_disposition(content_disposition):
    """ Get content disposition filename from given header. Do not include
      "Content-Disposition:". Returns a unicode string! """
      parser = FeedParser()
      parser.feed('Content-Disposition: ' + content_disposition)
      name = parser.close().get_filename()

      if name is None:
        raise ... # 'Unable to find "filename" in "Content-Disposition" "{0}"'.format(content_disposition)
        
      if not isinstance(name, six.text_type):
          name = name.decode('latin1', 'ignore')
      return name
```

Looking at the descriptions for the builtin exception [ValueError](https://docs.python.org/2/library/exceptions.html): 

> Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value, ...

May be the most appropriate one to raise.

### Or

We can do away with raising an exception and let `get_content_disposition(...)` return `None` when it can't find a "filename" then allow `sunpy.util.net.get_filename(...)`
to deal with the missing "filename", as it is currently designed to do.

Thinking about the name of `get_content_disposition(...)`, it might be more accurate to call
it something along the lines of `get_filename_from_content_disposition(...)` but that would
involve a change to the API which is not a good idea.

**Comment by m-charlton** [comment]
Looking more closely at the code I think I've a better understanding of the
intent:

```
#pseudocode

get_system_filename(sock, url, default)

    filename = get_filename(sock, url)

    if filename is valid
       return filename
    
    return default

get_filename(sock, url)

  filename = get_content_disposition(sock)

  if filename is valid
     return filename

  if filename is in url
      return filename
      
  return None

```

I'll start by writing unit tests for the following functions:

- `get_system_filename(...)`
- `get_filename(...)`
- `get_content_disposition()`

There's a lot of encoding/decoding going no so I'll have to be careful of any 
string/byte/unicode conversion issues and make sure that all tests pass on 
both 2.x & 3.x

**Comment by m-charlton** [comment]
May have found a few issues:

#### `slugify(...)`

```python
>>> from sunpy.util.net import slugify
>>> slugify('Cáfe.txt')
'cáfe.txt'
```

The default encoding is 'ascii' so I think the output of the above should be:

```
cafe.txt
```

Looking at the code, the encoding argument is not used in the function and in an
existing unit test this check is not taking place:

```
# sunpy/net/tests/test_util.py

18 def test_slugify():
19    assert sunpy.util.net.slugify(u"äb c", u"b_c")
20    assert sunpy.util.net.slugify(u"file.greg.fits") == u"file_greg.fits"
```

I've a fix, which I can submit with unit tests.

Furthermore if you pass in an 'exotic' unicode character as the delimiter, it 
is not converted.

```python
>>> slugify('with spaces.txt', delim='ø')
'withøspaces.txt'
```

I'm working on a fix for this. If unable to convert the delimiter to a 'conventional'
character then we can use the existing default '\_'.

#### `download_fileobj(...)`

If the `opn` object does *not* contain a filename but the URL does then
`shutil.copyfileobj(...)` always attempts to read from the `opn` HTTP connection
resulting in the HTML from `opn` being written to a file with the name given
in `url` or, if the url does not have a file name, to `default`.

If the `opn` does not contain a filename but, the `url` does then the file
contents from url should be used.

```python
def download_fileobj(opn, directory, url='', default=u"file", overwrite=False):
    """ Download file from url into directory. Try to get filename from
    Content-Disposition header, otherwise get from path of url if given.
    Fall back to default if both fail. Only overwrite existing files when
    overwrite is True. """
    filename = get_system_filename(opn, url, default)
    ...
    with open(path, 'wb') as fd:
        shutil.copyfileobj(opn, fd)
    return path
```

I'm working on a fix for this paying special attention to the existing API.

**Comment by dstansby** [comment]
Is there a real world-example that exercises this issue? Am tempted to close this since it hasn't had any activity for a couple of years.

**Comment by dstansby** [comment]
I have closed since it's not clear to me what exactly is broken; feel free to comment or re-open with a self contained example that demonstrates the bug.
