### ISSUE TITLE
Map.rotate is broken

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2003]
It's dead jim. http://docs.sunpy.org/en/latest/generated/gallery/gallery/map_rotation.html

It seems that the reference pixel post-rotation is wrong.

ping @SolarDrew @ayshih

**Comment by ayshih** [comment]
<whimper>

**Comment by nitinkgp23** [comment]
Can you please elaborate on the issue a little bit? The example code works fine, so what is broken?

**Comment by prateekiiest** [comment]
Is the peek() function not working in this case??

**Comment by prateekiiest** [comment]
@Cadair can I correct this in the documentation part?  I have already got the image.

**Comment by Cadair** [comment]
The image is auto-generated with the documentation. Interesting that it's not reproducible.

**Comment by Cadair** [comment]
So I have traced this to the padding set where crpix1 and crpix2 is modified.

**Comment by Cadair** [comment]
I traced the issue back to this patch: https://github.com/sunpy/sunpy/pull/1929/files#diff-9eadd681e99c7419c431865d29b5ca1dR1003

Fix incoming.
