### ISSUE TITLE
HelioprojectiveFrame should default to Earth location if dateobs is set

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2004]
Currently the distance from the observer to the sun-centre is set as one AU. (https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/frames.py#L288) this should instead use the Sun-Earth distance calculation available `sunpy.sun.sunearth_distance(date)` if the dateobs property is set.

This is also true for the B angle as well, we should use the dateobs to default to the correct inclination from the ecliptic as well as distance.

Also B0 should use the `sunpy.sun.heliographic_solar_center(date)[1]` calculation if dateobs is set so we assume that the observation is from Earth.

**Comment by curiousrohan** [comment]
I'd like to work on this bug. I'm new here and have already set up develop environment. Can someone help me?

**Comment by nitinkgp23** [comment]
@curiousrohan Are you working on this bug?

**Comment by Cadair** [comment]
I think this is more complex than I first suspected. The issue is that the `FrameAttribute` classes used for defining these attributes of the frames can't handle calculating a default value based on the value of another attribute.

**Comment by prateekiiest** [comment]
If  the FrameAttribute classes are removed and instead assign D0 and B0 to the `sunpy.sun.sunearth_distance(date)` and `sunpy.sun.heliographic_solar_center(date)`, then I hope there would not be a problem. I am looking into this @Cadair

**Comment by prateekiiest** [comment]
And should this sunearth_distance take dataobs as argument for calculating D0?

**Comment by Cadair** [comment]
You can't remove the `FrameAttribute` classes as they are important for the functioning of `SkyCoord` amongst other things. Also `date` is not defined until inside the `__init__`.

**Comment by Cadair** [comment]
yes `dateobs` is the important part of calculating `D0` and `B0`.

**Comment by nitinkgp23** [comment]
We can have our own `SkyCoord` which inherits from astropy. Then, we will be able to pass `dateobs` to the respective frame.

**Comment by Cadair** [comment]
No, I would rather make any changes needed to make this work in astropy than subclass `SkyCoord`.

**Comment by nitinkgp23** [comment]
Then, maybe we should open an issue in astropy asking for a function that passes `dateobs` to the respective frame?

**Comment by Cadair** [comment]
I have just posted on the mailing list here: https://groups.google.com/forum/#!topic/astropy-dev/5rz55yCKj38

**Comment by Cadair** [comment]
I don't think we should back port this, it should be a new feature in 0.8.
