### ISSUE TITLE
It should be possible to instantiate Map with an array and a WCS object 

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2005]
This should be possible:
```python
import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
from astropy.wcs import WCS
from astropy.io import fits

wcs = WCS(AIA_171_IMAGE)
array = fits.getdata(AIA_171_IMAGE)

aia = sunpy.map.Map(array, wcs)
```

**Comment by nitinkgp23** [comment]
Hey @Cadair , I am a newbie and want to work on this issue. Can you give some more details?

**Comment by Naman9639** [comment]
This is working for me


import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
from astropy.wcs import WCS
from astropy.io import fits

wcs = WCS(AIA_171_IMAGE)
array = fits.getdata(AIA_171_IMAGE)
header = wcs.to_header()

aia = sunpy.map.Map(array, header)
