### ISSUE TITLE
Add support for GOES-R SUVI Solar EUV images

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#2013]
SUVI is an EUV imager on the [GOES-R](http://www.goes-r.gov) satellite that was launched on November 19, 2016. A description of the instrument can be found [here](http://www.goes-r.gov/products/baseline-solar-xray-imagery.html).

Data  available at

https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes16/l1b/

**Comment by Cadair** [comment]
What is going to be needed here? A new `GenericMap` subclass presumably, what about acquisition? is this data going to be in the VSO or are we going to need our own downloader client?

**Comment by wafels** [comment]
We plan on making SUVI images available via Helioviewer Project clients
too, so we'll be working on the colour tables for that.

**Comment by agneet42** [comment]
I want to take up this issue. Could you someone guide me what exactly I'd have to do?

**Comment by wafels** [comment]
As far as I am aware, data from this instrument is not generally available yet, so there is not much to do just now that would be useful.  This issue is more of a placeholder at the moment.

**Comment by agneet42** [comment]
@wafels. Okay.

**Comment by wafels** [comment]
Data now available at

 https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes16/l1b/

**Comment by hayesla** [comment]
Would be great to have a fido client for getting SUVI data!

**Comment by ehsteve** [comment]
@hayesla Created a issue #3300.
