### ISSUE TITLE
reshape_image_to_4d_superpixel array seems broken

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy#2020]
http://docs.sunpy.org/en/latest/generated/api/sunpy.image.rescale.reshape_image_to_4d_superpixel.html

This should be like this and not like in the docs.

`x = np.array([[0, 0, 0, 1, 1, 1],
[0, 0, 1, 1, 0, 0], [1, 1, 0, 0, 1, 1], [0, 0, 0, 0, 1, 1], [1, 0, 1, 0, 1, 1], [0, 0, 1, 0, 0, 0]])`

Same with
`array([[0, 3, 2],
[2, 0, 4], [1, 2, 2]])`

Not much of an issue, I guess.

**Comment by prateekiiest** [comment]
#2022 PR

**Comment by wafels** [comment]
The reason the arrays are formatted the way they are in the docs is to make it easy for the reader to understand what the function is doing.  Reformatting as suggested reduces understanding in my opinion.

**Comment by prateekiiest** [comment]
Then should we change it back to normal?

**Comment by wafels** [comment]
Yes, please change it back.

**Comment by prateekiiest** [comment]
http://docs.sunpy.org/en/latest/generated/api/sunpy.image.rescale.reshape_image_to_4d_superpixel.html
@wafels 
I think its looks good. But still can you tell me where to change the part specifically?
