### ISSUE TITLE
Remove extract_time function

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2024]
the `extract_time` function seems quite dangerous... as it can understand as times things that are not.

**Comment by m-charlton** [comment]
I can do this. Just to clarify: Does it need to be deprecated, using the @deprecated decorator, or physically removed, and the change log updated?

**Comment by prateekiiest** [comment]
@dpshelio  PR #2029

**Comment by nabobalis** [comment]
Fixed by #2029
