### ISSUE TITLE
`sunpy.net.helio.parser.wsdl_retriever()` ignores previously discovered Taverna links

### ISSUE THREAD

**Issue by m-charlton** [sunpy/sunpy#2032]
Found this while writing unit tests for `sunpy.net.helio.parser`.

I think there might be a bug in the `wsdl_retriever` function:

```python
# sunpy/net/helio/parser.py

192 def wsdl_retriever(service='HEC'):
...
226    service_links = webservice_parser(service=service)
227    wsdl = None
228    wsdl_links = None
229    if service_links is None:
230        return None
231    for link in service_links:
232        wsdl_links = taverna_parser(link)
233    if wsdl_links is None:
234        return None
235    for end_point in wsdl_links:
236        if end_point is not None and link_test(end_point) is not None:
237            wsdl = end_point
238            break
239    return wsdl
```

On line 232 we assign any Taverna links, to `wsdl_links`. The problem is that 
`wsdl_links` is reset on each iteration. The worst case scenario is the very 
last `link` could yield `None`, no Taverna links found, and all previously 
found links would be ignored.

I think it should be do something like the following:
 
```python
      for link in service_links:
          taverna_links = taverna_parser(link)

          if bool(taverna_links):
              for taverna_link in taverna_links:
                  if taverna_link not in wsdl_links:
                      wsdl_links.appended()
```

It's quite ugly and I think it could be simplified by using a `set` to hold the
`wsdl_links`:

```python
      wsdl_links = set()
      ...
      for link in service_links:
          taverna_links = taverna_parser(link)
          if bool(taverna_links):
              wsdl_links.update(taverna_links)
      if len(wsdl_links) == 0:
          return None
```

The only limitation is that when we iterate over a set the order in which we 
retrieve items is non-deterministic. Is this a problem?

I've a PR ready if this is a bug.

**Comment by Cadair** [comment]
@dpshelio This is your domain!
