### ISSUE TITLE
Spectrogram  Attributes not Documented Well

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy#2033]
Some of the documentation is not clear in http://docs.sunpy.org/en/stable/generated/api/sunpy.spectra.spectrogram.Spectrogram.html

in the attribute section table, like for `COPY_Properties` and `shape`.

Also there is some mismatch in the font.

**Comment by prateekiiest** [comment]
I will be sending a PR regarding this

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#9
