### ISSUE TITLE
Remove usage of deprecated wcs functions (differential rotation)

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#2039]
Sunpy is already deprecated ``convert_hg_hpc``, yet there is usage of it in quite many places.

A good task for a novice to get rid of these, and use sunpy.coordinates instead.

**Comment by nitinkgp23** [comment]
Already working on it. Will send the PR soon. :)

**Comment by bsipocz** [comment]
Looking at it a bit more, there are other similar functions, so would be great if you could remove the usage of those, too (look for the ones that generate an ``AstropyDeprecatonWarning`` when building the docs).

**Comment by nitinkgp23** [comment]
Yeah. Sure. I have seen a lot of `AstropyDeprecatonWarning` too. Will fix them.

**Comment by prateekiiest** [comment]
So, the function just needs to be removed? Or should we replace it with the function using sunpy.coordinates from transformations.py?

**Comment by Cadair** [comment]
@prateekiiest Things that use functionality from `sunpy.wcs` need re-writing to use sunpy.coordinates. This is not a simple case of switching one function out for another, the other functionality needs to be re-written to use sunpy.coordinates properly.

In master at the moment there is as lot of stuff in sunpy.map which is still using sunpy.wcs, I have an open PR to remove all of that (#1975).

**Comment by bsipocz** [comment]
@prateekiiest - The deprecated functions should stay in place, but their usage within the same codebase should be limited and their alternatives should be used instead.

**Comment by bsipocz** [comment]
@Cadair - Fair enough, I haven't seen your PR. Sorry for the noise...

**Comment by Cadair** [comment]
@bsipocz There is a lot of use of sunpy.wcs in other places as well, but the map stuff I am working on :)

**Comment by prateekiiest** [comment]
Ok, looking into it.

**Comment by prateekiiest** [comment]
I checked through sunpy.wcs but it didnt find hg to hpc.

The all function under sunpy/wcs/transformations is 
`__all__ = ['hgs_to_hgc', 'hgc_to_hgs', 'hcc_to_hpc',
           'hpc_to_hcc', 'hcc_to_hgs', 'hgs_to_hcc']`

**Comment by prateekiiest** [comment]
So should we do like this 
`hgc_to_hgs` => `hgs_to_hcc` =>`hcc_to_hpc`

**Comment by nitinkgp23** [comment]
We have to use transform_to() for changing into frames. These functions are not be used generally. See SkyCoord.transform_to().

**Comment by Cadair** [comment]
@prateekiiest the functions in sunpy.coordinates.transformations should never be called directly as @nitinkgp23 says.

**Comment by prateekiiest** [comment]
.transform_to() is actually from a different module under astropy.coordinates.transformations, i think
So defining that way would be a problem i think

**Comment by Cadair** [comment]
@prateekiiest nope, doing it using astropy specifically either `SkyCoord.transform_to` or `BaseCoordinateFrame.transform_to` is the correct approach.

**Comment by bsipocz** [comment]
@prateekiiest - The whole point of this issue is to remove all usage of the functions of sunpy.wcs (as those are deprecated), ``convert_hg_hpc`` was really just an example of these functions.
