### ISSUE TITLE
Code not showing up in maps.rst for plotting keywords and colormap section

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy#2046]
Some codework is not being showed up in the maps.rst section - https://github.com/sunpy/sunpy/blob/master/doc/source/guide/data_types/maps.rst#plotting-keywords

which is present in the current documents http://docs.sunpy.org/en/latest/guide/data_types/maps.html#plotting-keywords.

Also I think it would be better if we could upload the generated plots and the images in the .rst files.

**Comment by Cadair** [comment]
Look at the raw rst file: https://raw.githubusercontent.com/sunpy/sunpy/master/doc/source/guide/data_types/maps.rst the code is there. 

Because it's a plot directive block to automatically generate the code and the plot it does not show up on GitHub's rubbish rst renderer.

**Comment by prateekiiest** [comment]
But shouldn't we show the code snippet as a preview under the doc/source file.
I saw the code is there, but its not showing up in the preview.

**Comment by Cadair** [comment]
that's a limitation of github, not something we have control over. We put a lot of effort into the docs so that they keep up to date with code changes as automatically as possible, which is why we generate these scripts at build time.
