### ISSUE TITLE
VSO moving to https

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2047]
The VSO is moving to using https on 2017 May 15.

http://spd.stanford.edu/SolarNews/current.html#section_gurman

The VSO client should be updated to reflect this change.

**Comment by Cadair** [comment]
There was some effort on this a little while ago, I think it should be a relatively easy switch.

**Comment by Cadair** [comment]
All the roadblocks to using a full https stack for VSO should have been removed in #2866, however, I believe we are waiting for some upstream fixes in the VSO before we can migrate to the https only SDAC endpoint.
