### ISSUE TITLE
Broken link on github page

### ISSUE THREAD

**Issue by DuyguKeskek** [sunpy/sunpy#2057]
SunPy website link is broken on the [github page](https://github.com/sunpy/sunpy) and needs to be fixed.
Broken link :  http://www.sunpy.org
Correct one : http://sunpy.org/

**Comment by Cadair** [comment]
Ok, that is less of a problem with the GitHub page and more a DNS setup issue left over from our recent domain registrar swap.

**Comment by Cadair** [comment]
I fixed this by fixing the DNS www.sunpy.org should now work.
