### ISSUE TITLE
Warning boxes for sunpy.wcs deprecated functions in documentation

### ISSUE THREAD

**Issue by swapsha96** [sunpy/sunpy#2072]
As mentioned in issue #2039 various sunpy.wcs functions are deprecated using `@deprecated` (total 11 in [wcs.py](https://github.com/sunpy/sunpy/blob/master/sunpy/wcs/wcs.py)) but this is not mentioned in the documentation ([example](http://docs.sunpy.org/en/stable/generated/api/sunpy.wcs.convert_hg_hpc.html#sunpy.wcs.convert_hg_hpc)). It can be done using  [`.. warning::`](http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#colored-boxes-note-seealso-todo-and-warnings) as warning boxes are implemented in [SunPy net](http://docs.sunpy.org/en/stable/code_ref/net.html). Can I create a PR adding all warnings for WCS functions in documentation?

**Comment by Cadair** [comment]
Your link to the docs is to the released version not the version built from master.

It's not a warning box but it is added from the decorator to the top of the documentation: http://docs.sunpy.org/en/latest/generated/api/sunpy.wcs.convert_hcc_hg.html#sunpy.wcs.convert_hcc_hg
