### ISSUE TITLE
Replace suds-jurko

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2089]
The package [suds-jurko](https://bitbucket.org/jurko/suds) is a SOAP client and it is used by SunPy to access the VSO. suds-jurko is not being maintained.  Therefore a critical part of SunPy's functionality relies on software that is not being maintained.  The functionality that suds-jurko provides should be replaced by using another package (or packages), for example [zeep](http://docs.python-zeep.org/en/master/). See also issue #2047 .

Note that #2047 is a critical, time-sensitive issue and it is not clear at the moment that suds-jurko can handle the switching of the VSO to https.

**Comment by Cadair** [comment]
After a bunch of research it seems that Zeep is the best contender for replacing suds. It would be good to get this done for 0.9 so we do not have to maintain the version with the `suds-jurko` dependancy till ~2020

**Comment by Cadair** [comment]
This was closed by #2866
