### ISSUE TITLE
Affiliated package for calculating differential emission measure (DEM) distributions

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2090]
Calculating the DEM from observed intensities is a common task in solar physics. There are many different codes for computing the DEM, including (but not limited to),

* [Monte Carlo Markov Chain (MCMC)](http://adsabs.harvard.edu/abs/1998ApJ...503..450K)
* [Regularized inversion](http://adsabs.harvard.edu/abs/2012A%26A...539A.146H)
* [XRT algorithm](https://hesperia.gsfc.nasa.gov/ssw/hinode/xrt/idl/util/xrt_dem_iterative2.pro)

Most of these live (somewhere) in SolarSoft though the Hannah & Kontar regularized DEM code, [`demreg`](https://github.com/ianan/demreg), does live on GitHub. See [Aschwanden et al. (2015)](http://adsabs.harvard.edu/abs/2015SoPh..290.2733A) for a pretty comprehensive list of the many available methods. Many of them are undocumented outside of their respective papers and comments in the code.

Is there any interest in developing a SunPy-affiliated package that would a) re-implement many of the commonly-used DEM algorithms (i.e. translating from IDL to Python) and b) provide a common interface to these models? 

It would be really nice to finally document all of these codes and collect them all in one place. I think having a package like this would also help to convince a lot of solar physicists to begin the switch from IDL to Python if the interface to all of these methods was simplified and better documented.

**Comment by Cadair** [comment]
@SolarDrew ??

**Comment by SolarDrew** [comment]
Sounds like a good idea to me, I'm definitely interested.

**Comment by kdere** [comment]
there are two good Python packages for doing Bayesian analysis:  pymc and pymc3.  I have used pymc but I have not yet figures out pymce3 which is the upgrade to pymc

**Comment by wtbarnes** [comment]
@kdere yes I think those would make implementing the MCMC code much easier. There's also Dan Foreman-Mackey's [emcee](http://dan.iel.fm/emcee/current/) package. 

The emcee algorithm (though not the Python implementation) was also recently used in *yet another DEM code* by [Warren et al](http://iopscience.iop.org/article/10.3847/1538-4357/aa5c34/meta). To my knowledge, the code for this last method has not yet been published (it might be in C++?) so perhaps they would be interested in implementing a Python version using the existing emcee package.

**Comment by wtbarnes** [comment]
@DanRyanIrish is this something you'd be interested in? I noticed you are one of the co-authors on the Aschwanden paper I linked to above.

**Comment by wtbarnes** [comment]
For anyone interested in this, I've started an outline of what a package like this might look like [in this gist](https://gist.github.com/wtbarnes/e2014389834d1afbefa4941fc61d9779).

I really like this idea. While implementing every existing DEM code in Python is an enormous (impossible?!) undertaking, I think implementing a common framework for DEM models is very doable and would make implementing **a finite number** of these codes feasible.

**Comment by kdere** [comment]
My recommendation would  be to make a new solver from the ground up using PyMC or PyMC3.  These packages provide the statistics of the search and allow you to determine the confidence levels of the results.  It is my experience that these packages give you more detailed results than the data can support

**Comment by DanRyanIrish** [comment]
Hi @wtbarnes.  I think this looks like I great idea!  Not sure how I missed your ping in April.  I don't have the time at the moment to work on it myself but would encourage anyone else who does have time.  It would be a terrific resource.

**Comment by wtbarnes** [comment]
@kdere I think that is a good idea. Though I haven't looked at them closely, I suspect a lot of the DEM solvers in SSW are hand-coded. If we could replace them with one of these well-maintained MCMC packages, the amount of code to rewrite would probably be minimal. 

@DanRyanIrish No worries. My main goal in creating this issue was just to get the idea out there and hopefully inspire someone to take up the torch!

**Comment by wtbarnes** [comment]
@wafels Do you have any thoughts on this?

**Comment by wafels** [comment]
I think this is a good idea, and an interesting engineering problem.  A
survey of what the existing algorithms need in order to work would be a
start. And then maybe try implementing an existing algorithm following the
basic notion of the gist
<https://gist.github.com/wtbarnes/e2014389834d1afbefa4941fc61d9779>.

Such a framework could spur the development of more DEM inversion
algorithms.

**Comment by dpshelio** [comment]
@amandashack don't leave us telling about a sweet but without showing it :wink:  - are you building a package or have some repository? That would help people to collaborate.

**Comment by wtbarnes** [comment]
For anyone interested in this effort, see [sunpy/sunkit-dem](https://github.com/sunpy/sunkit-dem)

**Comment by wtbarnes** [comment]
I'm going to close this as the package has now been created and all related issues should be tracked there.
