### ISSUE TITLE
Wrong units on surface gravity constant

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2091]
`sunpy.sun.constants` gives surface gravity in length over time (velocity). Should be length over time squared (acceleration).

Problem is [here](https://github.com/sunpy/sunpy/blob/master/sunpy/sun/_constants.py#L75).

## MWE
```Python
>>> import sunpy.sun.constants as sun_const
>>> print(sun_const.surface_gravity)
 'Name   = Surface gravity
  Value  = 274
  Uncertainty  = 0
  Unit  = m / s
  Reference = Allen's Astrophysical Quantities 4th Ed.'
>>> print(sun_const.surface_gravity.unit)
 'm / s'
```

**Comment by nabobalis** [comment]
Closed by #2092
