### ISSUE TITLE
Ability to query jsoc2.stanford.edu with JSOCClient?

### ISSUE THREAD

**Issue by mjpauly** [sunpy/sunpy#2096]
There are a few AIA and HMI data series that are not publicly available and that are not visible from jsoc.stanford.edu. Instead, the query has to go through jsoc2.stanford.edu, which serves requests internally. At LMSAL, we have our own python modules for querying the jsoc but we would like to migrate to Sunpy's JSOCClient. Having functionality to query jsoc2 would allow that.

I tried submitting a pull request but ran into some issues getting things working, so I'm just opening this as a feature request. Querying jsoc2.stanford.edu is as simple as adding that "2" to the url.

Thanks!

**Comment by Cadair** [comment]
We are going to be re-writing the JSOC client this summer, so we will keep this in mind.
I *think* the following will work:

```python
from sunpy.net import jsoc

jsoc.BASE_DL_URL = 'http://jsoc2.stanford.edu'

jc = jsoc.JSOCClent...
```

**Comment by mjpauly** [comment]
Yes, that should work for data download. Would it be possible to do the same for `JSOC_INFO_URL` so you can look up records as well?

**Comment by abhijeetmanhas** [comment]
It is dependent upon drms package, and JSOC2 has already been discussed here, some authentication issues. https://github.com/sunpy/drms/issues/18

**Comment by nabobalis** [comment]
So we should probably close this?

**Comment by wtbarnes** [comment]
Hmm. The way I understand it, using drms by itself, one can easily target other servers other than just the public JSOC at Stanford. However, the JSOCClient in sunpy hardcodes the server as JSOC such that one cannot use Fido to search any DRMS server except JSOC. See also #3297
