### ISSUE TITLE
Links in the inheritance diagrams don't work

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2097]
see: http://docs.sunpy.org/en/latest/code_ref/timeseries.html#class-inheritance-diagram

**Comment by Cadair** [comment]
ping @Alex-Ian-Hamilton

**Comment by mirca** [comment]
@Cadair FYI: https://github.com/astropy/photutils/issues/345

**Comment by wtbarnes** [comment]
And the original astropy issue: astropy/astropy#4935 though the consensus seems to be this is an upstream issue with Sphinx.

Either way, not unique to SunPy.

**Comment by swapsha96** [comment]
If this issue is with Sphinx, we can implement the same using [HTML <area> Tag](https://www.w3schools.com/tags/tag_area.asp). The link gives an ugly example but same can be implemented with simple HTML.

**Comment by bsipocz** [comment]
This is somewhat related to our automodapi, as apparently it still works with pure sphinx:
sphinx-doc/sphinx#2484

**Comment by ayshih** [comment]
For completeness in cross-referencing: astropy/sphinx-automodapi#48

**Comment by ayshih** [comment]
My PR to finally fix this issue: astropy/sphinx-automodapi#152

**Comment by ayshih** [comment]
While sphinx-doc/sphinx#10576 will fix in bug in Sphinx, I doubt the bugfix will be backported to releases prior to 5.0.  Something in our dependency tree for the docs build is keeping Sphinx back at 4.5.

**Comment by nabobalis** [comment]
> While [sphinx-doc/sphinx#10576](https://github.com/sphinx-doc/sphinx/pull/10576) will fix in bug in Sphinx, I doubt the bugfix will be backported to releases prior to 5.0. Something in our dependency tree for the docs build is keeping Sphinx back at 4.5.

I am sure we can work out what is causing that and deal with it.

**Comment by ayshih** [comment]
The bug fixes have been merged upstream (sphinx-doc/sphinx#10614 and astropy/sphinx-automodapi#172), so will presumably show up in respective new releases, but the inheritance diagrams will continue to be broken in our documentation until our theme no longer pins us to an old version of Sphinx (see sunpy/sunpy-sphinx-theme#188).

**Comment by ayshih** [comment]
@Cadair has updated the theme, so this issue can finally be closed
