### ISSUE TITLE
AttributeError: module 'pandas.tseries' has no attribute 'index'

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#2098]
Hi Guys!  I am trying to make a map using an AIA fits files and giving me the following error

AttributeError: module 'pandas.tseries' has no attribute 'index'

when I run sunpy.self_test(online=False) I get the following output.  Any idea what am I doing wrong?

thanks a lot for your help!

============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy, inifile:
collected 841 items / 3 errors

=================================== ERRORS ====================================
__________________ ERROR collecting instr/tests/test_aia.py ___________________
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\instr\tests\test_aia.py:13: in <module>
    prep_map = aiaprep(original)
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\instr\aia.py:53: in aiaprep
    tempmap = aiamap.rotate(recenter=True, scale=scale_factor.value, missing=aiamap.min())
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\map\mapbase.py:966: in rotate
    origin=0)).value
C:\Users\anmunoz\Anaconda3\lib\site-packages\astropy\utils\decorators.py:874: in data_to_pixel
    func = make_function_with_signature(func, name=name, **wrapped_args)
C:\Users\anmunoz\Anaconda3\lib\site-packages\astropy\units\decorators.py:130: in wrapper
    return wrapped_function(*func_args, **func_kwargs)
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\map\mapbase.py:698: in data_to_pixel
    x, y = self.wcs.wcs_world2pix(x.to(u.deg).value, y.to(u.deg).value, origin)
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\map\mapbase.py:242: in wcs
    w2.wcs.dateobs = self.date.isoformat()
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\map\mapbase.py:377: in date
    time = parse_time(self.meta.get('date-obs', 'now'))
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\time\time.py:186: in parse_time
    elif isinstance(time_string, pandas.tseries.index.DatetimeIndex):
E   AttributeError: module 'pandas.tseries' has no attribute 'index'
------------------------------- Captured stderr -------------------------------
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
_______________ ERROR collecting lightcurve/tests/test_noaa.py ________________
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\lightcurve\tests\test_noaa.py:10: in <module>
    timerange_a = TimeRange('2004/01/01', '2007/01/01')
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\time\timerange.py:64: in __init__
    x = parse_time(a)
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\time\time.py:186: in parse_time
    elif isinstance(time_string, pandas.tseries.index.DatetimeIndex):
E   AttributeError: module 'pandas.tseries' has no attribute 'index'
________________ ERROR collecting time/tests/test_timerange.py ________________
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\time\tests\test_timerange.py:17: in <module>
    start = sunpy.time.parse_time(tbegin_str)
C:\Users\anmunoz\Anaconda3\lib\site-packages\sunpy\time\time.py:186: in parse_time
    elif isinstance(time_string, pandas.tseries.index.DatetimeIndex):
E   AttributeError: module 'pandas.tseries' has no attribute 'index'
=========================== pytest-warning summary ============================
WC1 None pytest_funcarg__foostrwrap: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__client: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__eit: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__iclient: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__oddeven: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!
============================ 110 tests deselected =============================
========= 110 deselected, 5 pytest-warnings, 3 error in 4.81 seconds ==========
Out[40]:
2

**Comment by wafels** [comment]
Andres,

I think this error is the same as the one noted in
*https://github.com/sunpy/sunpy/pull/2095
<https://github.com/sunpy/sunpy/pull/2095>*.  To be sure, on the IPython
command line, could you try

*import pandas*

and then type

*pandas.__version__*

and report the version number?

Also, which version of sunpy are you running?  You can find this out on the
IPython command line using


*import sunpy*
*sunpy.__version__*

Thanks,

Jack

**Comment by amunozj** [comment]
Hi Jack!  typing the commands you told me shows me:

Pandas: '0.20.1'
Sunpy: '0.7.7'

It seems it matches the error in that thread

**Comment by nabobalis** [comment]
Yeah, currently the master version of SunPy is broken under the newest version of Pandas. 

I hadn't even considered it was broken under the current release version. PR #2095 fixes this. The fix will be backported and a new release sometime in the next week. 

For the mean time, I would recommend downgrading to pandas 0.19.1

**Comment by amunozj** [comment]
Thank you guys that solved the problem.
