### ISSUE TITLE
Opening compressed AIA images

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#2099]
Hi Guys!

I'm not being able to open AIA images properly and I don't know what I'm doing wrong.  I'm trying to open this file:

https://www.dropbox.com/s/al5pxxix4p7c5kt/aia.lev1_euv_12s.2012-10-20T210004Z.193.image_lev1.fits?dl=0

but I get something that doesn't make sense.  I'm using a windows-based Anaconda with Python 3.

I'm doing the following:

import matplotlib.pyplot as plt
import sunpy.map
my_map = sunpy.map.Map('aia.lev1_euv_12s.2012-10-20T210004Z.193.image_lev1.fits')
my_map
np.max(my_map.data)
np.min(my_map.data)

fig = plt.figure()
my_map.plot(cmap=plt.cm.Greys_r)
plt.colorbar()
plt.show()

the outcome is:

SunPy AIAMap
---------
Observatory:	 SDO
Instrument:	 AIA 2
Detector:	 AIA
Measurement:	 193.0 Angstrom
Wavelength:	 193.0 Angstrom
Obs Date:	 2012-10-20 21:00:04
dt:		 0.000000 s
Dimension:	 [ 4096.  4096.] pix
scale:		 [ 0.600714  0.600714] arcsec / pix

array([[ 2, -2,  1, ...,  0,  0,  0],
       [ 2, -1, -1, ...,  0,  0, -3],
       [ 0,  1, -1, ...,  2,  0,  0],
       ..., 
       [ 1, -1,  0, ...,  0,  0,  0],
       [-1, -2,  1, ...,  2,  1, -1],
       [ 0,  3,  2, ..., -1,  0,  0]], dtype=int16)

max: 28
min: -16

and an image that has just random noise.  Any idea what am I doing wrong?  I get exactly the same result if I use Matlab. 

I'm attaching a jupyter notebook with this code.  Thanks in advance for your help!

[AIA_read.zip](https://github.com/sunpy/sunpy/files/990550/AIA_read.zip)

**Comment by prateekiiest** [comment]
Hi @amunozj 
The input you gave , then corresponding output looks all right.
What's wrong in it?

**Comment by larrymanley** [comment]
Looks like the exposure time (dt) is 0.0 - check the QUALITY keyword (my_map.meta['quality']).  If it's non-zero then it's a bad file.  The 193 channel in particular is very noisy when the automatic exposure control kicks in during high-flux events.

**Comment by pymilo** [comment]
Hi Andres,

I used DS9 to open the file you give as an input and I only see noise... Is this the image you expect to see? 

https://drive.google.com/file/d/0BxUeyZIz9CG4N0ZVTXhKZmxQajA/view?usp=sharing

**Comment by amunozj** [comment]
Hi Guys!

Thank you so much for your very quick answers and for giving the image a try.  I figured out what was the problem:  This is the first time in my life I load AIA data and I just happened to pick at random the first image in an hour, which is always taken with the shutter off so there is no Sun in it.   This is what happens when you are such a n00b ;)

**Comment by larrymanley** [comment]
QUALITY keyword is 65536, bit 16 set means "Dark image flag is set."
