### ISSUE TITLE
Increase test coverage for sunpy.cm

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#210]
Unit tests missing are basically ones that make sure that the error messages get triggered correctly. 

The missing lines that need a unittest are:

https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/cm.py#L147
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L76
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L267
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L345
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L373
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L533
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L1025
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L1078
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L1102
https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/cm/color_tables.py#L1359

**Comment by swapsha96** [comment]
@Cadair @nabobalis Currently, I am writing tests for `sunpy.cm`. I've written [something](https://github.com/swapsha96/sunpy/blob/test-cm/sunpy/cm/tests/test_cm.py), but that's nothing. Can you help me with this?
