### ISSUE TITLE
Saving AIA images (or sections of them) as pngs in native resolution

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#2100]
Hi Guys!

I have been trying to find a way of saving AIA data in native resolution, but cannot find a way to do it.  Trying to guess a combination of inches and DPI still leaves me with a lot of artifacts.  Does anyone know how to do it?   Ideally saving the entire image would result on a figure area of 4096x4906 plus the padding necessary for the titles and labels.  If one picks one quadrant then the resulting figure area would be 1024x1024 plus padding for titles and labels.   In other words, the size of the resulting png image would be completely determined by the amount of pixels that are chosen form the original array.

Thanks a lot for your help!

**Comment by lowderchris** [comment]
If you wanted to keep axes, you should be able to grab the final axis coordinates (after all plotting and rearrangement) and generate a dpi from that:

```
import sunpy.map

maia = sunpy.map.Map('aia.lev1.193A_2015-02-19T23_59_54.84Z.image_lev1.fits')

fsz = 5
f, (ax) = subplots(1, figsize=[fsz,fsz])
ax.set_xlabel('X (pixels)')
ax.set_ylabel('Y (pixels)')
ax.imshow(maia.data)
axpos = ax.get_position()
dpi = maia.data.shape[0] / (axpos.x1-axpos.x0) / fsz
savefig('aia-figsave.png', dpi=dpi)
```

![aia](https://cloud.githubusercontent.com/assets/3028588/25948062/eec2b2ec-3649-11e7-85f0-828302c399dc.png)

Alternatively, if you just want the array itself, it can be saved directly with:

`imsave(arr = maia.data, fname='aia-imsave.png')`
