### ISSUE TITLE
Add tests for dateobs in HGC<>HGS Transformations

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2105]
See #2063  and there was a previous pull request with lots of comments here: #2360

**Comment by ayush1999** [comment]
@Cadair I'd love to work on this. Can you tell me how to start? And how can I assign this issue to myself?
Thanks!

**Comment by Cadair** [comment]
Hi @ayush1999 there have been a lot of changes in the coordinates module in the last few weeks, you should run the existing tests and see if there are gaps in the coverage.

**Comment by sapnamish** [comment]
I'd love to work on this.can you tell me how to start? And how can i assign this issue to myself.Thanks!

**Comment by nabobalis** [comment]
@sapnamish I don't know much about the coordinate stuff, there was a previous PR with lots of comments here: https://github.com/sunpy/sunpy/pull/2360

**Comment by ayshih** [comment]
Closing this issue because I think it's moot given our current implementation for `obstime` (previously `dateobs`)
