### ISSUE TITLE
Normalize SunPy sample data

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#211]
The current sample data for SunPy (e.g. sunpy.AIA_171_IMAGE, sunpy.RHESSI_IMAGE, etc) were chosen somewhat arbitrarily and have do not share anything in common.

I think it would be useful to take a more systematic approach to selecting sample data to include with SunPy.

Things to consider:
1. Choose data for same time period to allow for meaningful overlay and combination examples.
2. Decide which data sets should be included -- unless we decide we should have one sample image for each type of data supported, we should probably decide before-hand which types of data to include. Probably one sample image for each _type_ of data (disk image, coronagraph, single light-curve, multi-column lightcurve, etc) would be sufficient.
3. Since users will have to download all of these, make sure the files are relatively small.

**Comment by nabobalis** [comment]
Is this done now?

**Comment by ehsteve** [comment]
Not done but a time has been identified it looks like!

**Comment by ehsteve** [comment]
![goes_rhessi_20110607](https://cloud.githubusercontent.com/assets/739053/14506980/8302ba20-018e-11e6-8712-31189b399762.png)

**Comment by ehsteve** [comment]
http://sprg.ssl.berkeley.edu/~tohban/browser/?show=grth1&date=20110607&time=064933

**Comment by ehsteve** [comment]
http://bit.ly/1oYBT50

**Comment by ehsteve** [comment]
![2011_06_07_06_24_32_aia_171](https://cloud.githubusercontent.com/assets/739053/14508404/50024cce-0195-11e6-8573-cf70338a2c17.png)

**Comment by Cadair** [comment]
ping @Alex-Ian-Hamilton

**Comment by swapsha96** [comment]
@nabobalis I would like to work on 3 functions mentioned above: 
- sunpy.load_sample('xxx')
- sunpy.list_samples()
- sunpy.download_sample('yyy')

Can you guide me through this? Where do you want me to start from?

**Comment by nabobalis** [comment]
@swapsha96 Thanks! But the original issue was solved (in the sunpy/sample-data repo) and I do not agree with khughitt on having separate functions to list and download the sample data. I am in favour of only being able to download the entire sample data set. 

So I will close this issue and I think it is solved.
