### ISSUE TITLE
Should Fido UnifiedResponse objects support concatenation?

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2141]
If you have two `UnifiedResponse` objects you should be able to concatenate them (probably using the `+` operator) and then pass the result to `Fido.fetch`.

ping @dpshelio

**Comment by vit1-irk** [comment]
Why does nobody care about this?

It is still a pain to download results from VSO if the UnifiedResponse contains broken data blocks inside. If you could index and concatenate these objects properly, it will be much easier to avoid errors

**Comment by nabobalis** [comment]
> Why does nobody care about this?
> 
> It is still a pain to download results from VSO if the UnifiedResponse contains broken data blocks inside. If you could index and concatenate these objects properly, it will be much easier to avoid errors

Hi @vit1-irk, some initial work had gone into this but we quickly realised it brought up a ton of scenarios and edge cases we did not plan for. 

From what I recall, it is possible to pass multiple `UnifiedResponse` into `Fido.fetch`, so I wonder (from my personal side) if we would actually still want to add this feature.   

I am quite interested in your use case and how you are working around these broken data blocks.
Could you share some code examples (searches and all)?

**Comment by sashank27** [comment]
@vit1-irk I guess #3675 would kinda help in creating `QueryResponse` as `astropy.table.Table` and then can be used easily for concatenation and indexing

**Comment by vit1-irk** [comment]
@nabobalis 
> I am quite interested in your use case and how you are working around these broken data blocks. Could you share some code examples (searches and all)?

I have prepared a sample Jupyter Notebook file with all problems explained and workaround I use at the moment, see <https://gist.github.com/vit1-irk/a3891d0948c3aff347fd5a82c9ece79f>

@sashank27 
QueryResponse and QueryResponseBlock objects are relatively easy to access read-only way, but when you try to build them up together to download the data, QueryResponse or UnifiedResponse constructors crashes or Fido.fetch fails due to unability to figure out how to download the elements.

**Comment by Cadair** [comment]
hey @vit1-irk Could you open a new issue for the `start_time: None` issues you are seeing there, that looks like something we should investigate with the VSO team. In general I agree that improvements to post-search filtering would be great, but there are a lot of things which should be improved with `Fido` and few people who have the time to work on it.

**Comment by Cadair** [comment]
(Also, it's not actually the `size: -1` thing which is an issue, I think that's just VSOs way of saying it doesn't have that info and I have seen some valid data like that. It's actually the lack of start time which is the real killer.)

**Comment by nabobalis** [comment]
> @nabobalis
> 
> > I am quite interested in your use case and how you are working around these broken data blocks. Could you share some code examples (searches and all)?
> 
> I have prepared a sample Jupyter Notebook file with all problems explained and workaround I use at the moment, see https://gist.github.com/vit1-irk/a3891d0948c3aff347fd5a82c9ece79f

Thank you for this.

**Comment by vit1-irk** [comment]
@Cadair, @nabobalis 
I have updated the gist to include more debug info and to use the suggested way to filter out wrong VSO provider: <https://gist.github.com/vit1-irk/a3891d0948c3aff347fd5a82c9ece79f>

Opened this bug as another issue: #3734

**Comment by Cadair** [comment]
great thanks @vit1-irk please do open issues if you have any other trouble using `Fido` with any of the data sources :smile:

**Comment by nabobalis** [comment]
I think until we work out what we require from concatenation of UnifiedResponse objects, let alone if we want to actually support this, I will be closing this.

**Comment by Cadair** [comment]
We discussed this as part of the GSOC project this summer, we didn't actually do anything about it tho right?

**Comment by nabobalis** [comment]
I think we decided to not allow it.
