### ISSUE TITLE
Update to allow use of newer astropy constant values

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2143]
As of 2.0 Astropy implemented versioned constants, we are currently only using the 1.3 versions. 

For example:

Two different values of R_sun with two different descriptions -
IAU2012 (6.95508e8 m, "solar radius") and IAU2015 (6.957e8 m, "nominal solar radius").  

Do want to update the values or keep using the older ones?

**Comment by wafels** [comment]
Two different values of R_sun with two different descriptions -
IAU2012 (6.95508e8
m, "solar radius") and IAU2015 (6.957e8 m, "nominal solar radius").  Note
that the difference in these radius values correspond to about 1 AIA
pixel.  SunPy's image co-alignment algorithm can estimate changes in image
co-alignment down to about 0.1 to 0.2 AIA pixels.

**Comment by Cadair** [comment]
Oh look it's the new solar radius number that we were discussing. Of course if you are using AIA data it's better to use the value in the AIA header for solar radius because they just round it off.

**Comment by Cadair** [comment]
https://travis-ci.org/sunpy/sunpy/jobs/244253515#L1183

**Comment by nabobalis** [comment]
Highjacking this.

Astropy now has versioned units. This has been temp fixed in master and in 0.7.
The issue now becomes this. Do want SunPy versioned units?

I open the floor. @Cadair

**Comment by nabobalis** [comment]
This was closed by #3001
