### ISSUE TITLE
Do we still need CompositeMap?

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2150]
As far as I can tell it doesn't do anything that a matplotlib script could do just as well.  How about deprecating it in 0.8 and removing it in 0.9, and replacing it with a gallery example using Map objects and matplotlib?

**Comment by Cadair** [comment]
I am always happy to remove code, we could write tools to overplot different maps in a mapcube.

**Comment by nabobalis** [comment]
I am happy to git rm anything at any time. 

I thought the idea of CompositeMap was to allow easy overlaying of images with WCS information. 
Do we have examples of this anywhere?

**Comment by wafels** [comment]
I don't think we need new tools in mapcube either.

All CompositeMap does is plot stuff, nothing else.  If it is just plotting,
then why not just use matplotlib and wcsaxes?  A tutorial replacing the
current example in the CompositeMap docstring would be sufficient.

**Comment by Cadair** [comment]
Fair enough, I didn't completely mean new tools *in* mapcube, just tools that take a mapcube as input. Or just a list of maps maybe.

**Comment by wafels** [comment]
#2745 suggests functionality that is not in the current CompositeMap object.  I suggest that more use cases be collected for what CompositeMap could do **uniquely** that cannot already be done with Map or with an extensive matplotlib plotting tutorial.

**Comment by wtbarnes** [comment]
I'm closing this in favor of the more up-to-date discussion that is happening in #6375
