### ISSUE TITLE
Some 'Edit on Github' links on the top of the documentation pages point to a non existing page (error 404) 

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#2169]
So on this [page](http://docs.sunpy.org/en/stable/code_ref/lightcurve.html) the edit on git hub link (with the Github logo) in the header works but in this [page](http://docs.sunpy.org/en/stable/generated/api/sunpy.lightcurve.EVELightCurve.html#sunpy.lightcurve.EVELightCurve) it links to a non existent page leading to a 404

**Comment by samaloney** [comment]
There must be flag or something to signal when to add link or not if you look [here](http://docs.astropy.org/en/stable/stats/lombscargle.html) (at the bottom this time) the link works as expected and then [here](http://docs.astropy.org/en/stable/api/astropy.stats.LombScargle.html#astropy.stats.LombScargle) in the generated docs there is no link.

**Comment by swapsha96** [comment]
The latest documentation doesn't have this feature. Instead of closing it right now, it's better to enable it first.

**Comment by samaloney** [comment]
Seems to be fixed in on RTD latest

**Comment by nabobalis** [comment]
Does not work on the versioned RTD versions.

**Comment by nabobalis** [comment]
It works now that I backported #2614.
