### ISSUE TITLE
Use astropy deprecated decorator customized for sunpy

### ISSUE THREAD

**Issue by bsipocz** [sunpy/sunpy#2190]
Currently a copy of the astropy decorator is used, but ideally it should be used directly with some minor customization.

See failed attempt here: #2038

**Comment by Cadair** [comment]
This probably needs a PR to astropy. Would be good to convert the deprecated decorator to a class with a class attr that is the class of warning to raise.

**Comment by ayshih** [comment]
This should be closed, right?  We have our own decorator (now).

**Comment by nabobalis** [comment]
We have a copy and paste of the astropy one that ideally we shouldn't.

**Comment by ayshih** [comment]
Yup, I misunderstood the issue.

**Comment by bsipocz** [comment]
The astropy one is much more customizable now than it was 2 years ago, so now it might be already possible to fully switch to use that one instead.
