### ISSUE TITLE
Fido clients should not be case sensitive for instrument names

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2192]
I am looking at you GOES.

The string comparisons in the `_is_source_for` methods of the clients just need the addition of a few `.lower()` calls.

**Comment by Misara** [comment]
I'd like to work on this, where is the file located? Sorry, I'm new to the package.

**Comment by Cadair** [comment]
Ok, I can no longer reproduce this, I assume that when I opened it I was running on an out-of-date version of master.

@Misara Thanks for your interest in contributing, feel free to ask for advice on tacking another issue.
