### ISSUE TITLE
Add a "What's New in 0.8" Page to the Docs

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2199]
Should be a very high level intro to what has changed, not just a re-hash of the changelog, short code snippets are essential.

**Comment by nabobalis** [comment]
How about we leave it as a surprise for the users?

**Comment by Cadair** [comment]
Fido

New interface for downloading data
Supports VSO, JSOC and other sources of data
Replaces the individual downloaders used to obtain timeseries data.

Coordinates

Spatial locations using solar physics coordinate systems are now represented by SunPy coordinate objects.
Transformation of coordinates between solar physics coordinate systems, and between all SunPy and Astropy-supported coordinate systems.
Specification of observer at any major solar system body

Timeseries

LightCurve object is now replaced by the TimeSeries object
File header information is stored as TimeSeries metadata, and is managed when merging and stacking timeseries data.
Factory interface

**Comment by Cadair** [comment]
@wafels see above edit for my thoughts on what are the key things from the changelog / my brain. Feel free to drop things that you think are to technical or not interesting.
