### ISSUE TITLE
Increase test coverage for sunpy.map.mapsequence

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#220]
See our test coverage: https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/map/mapsequence.py

**Comment by sunilk747** [comment]
hello,
I tried to get a brief idea of the sunpy  code base  and as a beginner, I would like to work upon this issue to get some more idea of the code base .

**Comment by Cadair** [comment]
@sunilk747 please do! 

You can expand the tests in this file: https://github.com/sunpy/sunpy/blob/master/sunpy/map/tests/test_mapcube.py

if you run the tests for the map package like this: `python setup.py test -P map --cov` it will tell you how many lines of the `mapcube.py` are covered and give you some idea where to start.
