### ISSUE TITLE
MapSequence needs a save method

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2210]
MapSequence does not have a save method.  I suggest saving each map as an individual FITS file using the map save method, with appropriate numbering as part of the output file name.

See https://github.com/sunpy/sunpy/pull/2301 for a previous attempt.

**Comment by jerinphilip** [comment]
Hey, I'd like to try this.

From what I understannd `GenericMap.save(...)` is what I should use internally.

Do you have any signature for this function in mind - as in, what should be the parameters supplied - perhaps a `prefix_path` or something so I can just name the files as `prefix_path + indexof map`?

**Comment by wafels** [comment]
+1 
Initially, I think a prefix path is the only parameter that needs to be passed in.

**Comment by dstansby** [comment]
I don't think mapcube exists anymore and has ended up as ndcube? Feel free to re-open if this is incorrect.

**Comment by Cadair** [comment]
`MapCube` got renamed `MapSequence` and it still does not have a save method.

**Comment by SnehVachhani** [comment]
hello,
i want to help
plzz someone navigate me

**Comment by nabobalis** [comment]
Hi @SnehVachhani, what would you like help on? I would suggest first reading https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html to get started.

**Comment by SnehVachhani** [comment]
Hey @nabobalis  I have read the documentation that you mentioned and want to give it a start. Please can you guide me which file/s function/s i have to check.

**Comment by nabobalis** [comment]
> Hey @nabobalis I have read the documentation that you mentioned and want to give it a start. Please can you guide me which file/s function/s i have to check.

The code for MapSequence lives here: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapsequence.py
It lacks a save option that MapBase has here: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L1200

So we would want to create a similar method that can save out the maps in a map sequence as individual files.

**Comment by jeffreypaul15** [comment]
Is this still a requirement?

**Comment by nabobalis** [comment]
I don't see why not, I don't see any mention of a PR addressing this.

**Comment by jeffreypaul15** [comment]
> I don't see why not, I don't see any mention of a PR addressing this.

Do you reckon creating a method `all_data() for retrieving all the data similar to `all_meta()`
https://github.com/sunpy/sunpy/blob/f936e59738aa43829f1da21451945886b074c9e5/sunpy/map/mapsequence.py#L509
 would be useful?

**Comment by nabobalis** [comment]
Won't "as_array" do that already?

The first decision to make is the save out format. Is it just a file per map in the sequence or is it combined.

**Comment by jeffreypaul15** [comment]
> Won't "as_array" do that already?
> 
> The first decision to make is the save out format. Is it just a file per map in the sequence or is it combined.

yeah, I forgot about that. 
Could they be saved together in one `fits` file?
If not then we can save each map separately right?

**Comment by nabobalis** [comment]
The original issue mentions saving them one at a time.

**Comment by nabobalis** [comment]
Closed by https://github.com/sunpy/sunpy/pull/5145
