### ISSUE TITLE
map.date() doesn't behave as "wanted" by the code

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2241]
The condition https://github.com/sunpy/sunpy/blob/5ea7fe6bee8accc0f9c08da943c112a32549c419/sunpy/map/mapbase.py#L409

will never happen... and if it does, the following statement after the `warning` will fail
 https://github.com/sunpy/sunpy/blob/5ea7fe6bee8accc0f9c08da943c112a32549c419/sunpy/map/mapbase.py#L414

So, I would either remove the `warning` or implement better the preferred behaviour. As it is now can just make us believe there's a net protecting the users... when there's not.

The [coverage](https://coveralls.io/builds/12747866/source?filename=sunpy%2Fmap%2Fmapbase.py#L406) shows that too.

**Comment by kiendang** [comment]
I think can change to `self.meta.get('date-obs', None)` and then inside the condition assign `time = 'now'`. That way the warning will show.
Also `parse_time` is called twice which is kind of redundant. I suggest leaving out the first one.
