### ISSUE TITLE
Increase test coverage sunpy.util

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#225]
Coverage for `sunpy.util` is quite low. 

https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/util

There are some files we do not to test coverage for like `towncrier.py`. Ideally these changes should be pushed upstream.

**Comment by wtbarnes** [comment]
`sunpy.util` has ~90% test coverage. Can we close this? If we want better test coverage on `towncrier.py`, we should create a specific issue for that.
