### ISSUE TITLE
[0.8] tests in net/tests/test_helio fail

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#2272]
On Debian, all tests in `sunpy/net/tests/test_helio.py` fail with the following error:
```
_____________ ERROR at setup of test_webservice_parser_no_content ______________
file /build/sunpy-0.8.0/sunpy/net/tests/test_helio.py, line 125
  @mock.patch('sunpy.net.helio.parser.link_test', return_value=None)
  def test_webservice_parser_no_content(mock_link_test):
E       fixture 'mock_link_test' not found
>       available fixtures: cache, capfd, capsys, doctest_namespace, mock, mocker, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/build/sunpy-0.8.0/sunpy/net/tests/test_helio.py:125
```
I am also not sure whether these would require internet access, or if I missed the installation of a python package?

**Comment by nabobalis** [comment]
The last time I saw that error I did not have ``mock`` installed. Maybe that could be the issue for you.

**Comment by olebole** [comment]
The mock package(s) are installed: `python-mock`, `python-pytest-mock`, `python3-mock`, `python3-pytest-mock` (Debian package names). Do I need more?

**Comment by nabobalis** [comment]
No, that should be enough. 

I might have to spin up a Debian VM and test this myself. I didn't think we would have issues with Debian!

**Comment by nabobalis** [comment]
I just installed a VM of Debian and can replicate this test failure on Py3 but not Py2.
The other issue I can not replicate regardless of python version. 

My process was:

1. Installed sunpy 0.7 from the main repository 
2. Downloaded the 0.8 release (in this case I used current master but thats the same as 0.8 bar the version bump)
3. Install: ```python3-pytest-mock python3-mock python-pytest-mock python-mock``` and ```python-hypothesis python3-hypothesis```.
4. I ran pip2 install -e .[all] to check dependencies which installed astropy 2 and pytest-rerunfailures via pip.

Result when I ran self_test() was:

Py2:```platform linux2 -- Python 2.7.13, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /usr/local/lib/python2.7/dist-packages/sunpy-0.9.dev0-py2.7-linux-x86_64.egg/sunpy, inifile: 
plugins: rerunfailures-3.0, mock-1.3.0, cov-2.4.0, hypothesis-3.6.1```

```192 tests deselected 1136 passed, 16 skipped, 192 deselected, 1 xpassed in 93.09 seconds```


Py3: ```platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /usr/local/lib/python3.5/dist-packages/sunpy, inifile: 
plugins: rerunfailures-3.0, mock-1.3.0, cov-2.4.0, hypothesis-3.6.1```

```
E       fixture 'mock_link_test' not found
>       available fixtures: cache, capfd, capsys, cov, doctest_namespace, mock, mocker, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

To fix this I had to update the python3 versions of pytest-mock using pip which did:

```bash
Collecting pytest>=2.7 (from pytest-mock)
  Downloading pytest-3.2.1-py2.py3-none-any.whl (186kB)
    100% |████████████████████████████████| 194kB 91kB/s 
Collecting py>=1.4.33 (from pytest>=2.7->pytest-mock)
  Downloading py-1.4.34-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 131kB/s 
Collecting setuptools (from pytest>=2.7->pytest-mock)
  Downloading setuptools-36.2.7-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 377kB/s 
```

```platform linux -- Python 3.5.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /usr/local/lib/python3.5/dist-packages/sunpy, inifile:
plugins: rerunfailures-3.0, mock-1.6.2, cov-2.4.0, hypothesis-3.6.1

192 tests deselected 1145 passed, 7 skipped, 192 deselected, 1 xpassed, 793 warnings in 87.15 seconds
```

Honestly, I am not sure how to deal with this. Maybe we need to have minimum versions of some of our dependencies listed.

**Comment by olebole** [comment]
Comparing versions between Debian (unstable) and upstream:

* pytest: both 3.2.1
* mock: both 2.0.0
* pytest-mock: Debian 1.3, upstream (git) 1.6.2

So I would assume that we need a higher pytest-mock package? I could ask to update our package (and temporarily disable the affected tests), if this is the cause.

> The other issue I can not replicate regardless of python version.

I still think it is connected with network access. You may try to do `export http_proxy=127.0.0.1:9` before running the tests; this should disable network access.

**Comment by nabobalis** [comment]
It would look like, as it why it doesn't happen on Py2 is an odd one. 

Should I enable Debian (unstable) and try it there?

**Comment by nabobalis** [comment]
So I enabled testing and updated. I got this error when i removed the updated pytest-mock package. 

So it seems that we need that updated.

**Comment by olebole** [comment]
For referece: the Bug report on Debian is [#872618](https://bugs.debian.org/872618). I am going to disable these tests until we have the new version in Debian.

**Comment by Cadair** [comment]
Thanks @olebole I will close this as it's not a direct issue with SunPy.

**Comment by olebole** [comment]
Yep, thanks, forgot to do this myself.
