### ISSUE TITLE
Ensure Helioviewer client uses Helioviewer API version 2 exclusively

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2280]
Version 2 of the Helioviewer API is the version that is being updated (version 1 is largely deprecated).  SunPy's helioviewer client - the actual code and the tests - should use version 2 of the API exclusively.

**Comment by nabobalis** [comment]
This is already true.

**Comment by wafels** [comment]
Need to put in 

https://api.helioviewer.org/v2/

somewhere.
