### ISSUE TITLE
Prepare for diff-rotations from different points of view.

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2282]
I've got this from a [draft document](https://issues.cosmos.esa.int/solarorbiterwiki/download/attachments/5801215/Triplet-TN%20SOL-SGS-TN-0020%20v0_2.pdf?version=1&modificationDate=1499950338000&api=v2) from [Solar Orbiter team](https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/SOC+Documents):

> 4.3 SOC handling of the differential rotation
> SOC will use the following model of differential rotation to propagate from the triplet
> epoch:
> ω(Φ) = A + B sin2(Φ) + C sin4(Φ)
> Where ω is the rotation rate (in deg/day)
>  And Φ is the solar latitude
>
> SOC will choose one of two sets of parameters:
> For magnetic features, meaning sunspots/active regions (derived from “Magnetic”
> in [DIFF])
> 
> A = 14.252
> B = -1.678
> C = -2.401
> For non-magnetic features, e.g. coronal holes
> A = 14.705
> B = 0.0
> C = 0.0
> Note that this is a “rigid” rotation corresponding to 26.24 day synodic period from
> Earth (=> 24.48 day sidereal period).

None of the current values we've got matches what they are planing.

```python
>>> howard.to(u.deg / u.day)
<Quantity [ 14.32632838, -2.11875209, -1.83163148] deg / d>
>>> snodgrass.to(u.deg / u.day)
<Quantity [ 14.1134631 , -1.69797189, -2.34646844] deg / d>
>>> allen.to(u.deg / u.day)
<Quantity [ 14.44, -3.  ,  0.  ] deg / d>
```

We do have a `synodic` correction as an option: `rotation -= 0.9856 * u.deg / u.day * duration`

**Comment by wafels** [comment]
See also #2864
