### ISSUE TITLE
Coordinates: sunpy.sun.solar_north() and sunpy.coordinates.get_sun_P() give different answers

### ISSUE THREAD

**Issue by dianamorosan** [sunpy/sunpy#2286]
I am trying to get the position angle of the solar north pole and in an older version of sunpy where sunpy.sun.solar_north() was still working I seem to get what looks like the correct result but after upgrading sunny to 0.8.1 I need to use sunpy.coordinates.get_sun_P() which gives a completely different value.

sunpy.sun.solar_north(t='now')
-15.188641163767306

After upgrading:

sunpy.coordinates.get_sun_P()
 <Angle 23.704631981838013 deg>

Which version is right?

**Comment by ayshih** [comment]
Checking outside of SunPy, the position angle right now is approximately 23.8 degrees, and the calculations in SunPy 0.8.1 agree with that.  Can you elaborate why you think the position angle should instead be approximately -15 degrees right now?  It looks like such a position angle corresponds to the start of June (and the second week of February), so did you run the first command ~three months ago (or have a misconfigured system time)?

**Comment by dianamorosan** [comment]
So I've double checked this myself against ssw and the position angle is indeed 23.7 degrees in both the new sunny version and ssw. -15 degrees was definitely the value I obtained in the old version but looks like new version is accurate. Thank you for confirming!
