### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2287]
This is the meta issue for dropping Python 2 in SunPy. This is scheduled to be done *after* the 0.9 release.

# Cleaning and Tidying

- ~`sunpy.extern.six` can be removed and all six imports in the code can be replaced by the Python 3 only ones.~
- ~All `__future__` imports.~
- ~Search for and remove any if `six.PY2` blocks and also search for `sys.version_info` or any usage of `minversion` or `Looseversion`.~
- Remove the Python 2 / 3 compatibility checks in the ANA C-API code..
- Search the code for comments mentioning Python to see if changes can be made under 3 only.

# Code Improvements / Style Changes

- ~Replace all instances of `u.quantity_input(keyword=unit)` with the function annotiation equivalent. (This means it will form part of the function definition and be documented by sphinx).~

See astropy/astropy#6234 for their version of this issue.

**Comment by prateekiiest** [comment]
@Cadair , working on this issue

**Comment by Cadair** [comment]
we won't be merging any work on this for at least 6 months probably, as we are going to do the 0.9 release first then work on this a little way into the next release cycle.

**Comment by prateekiiest** [comment]
Ok, we can make it as ready as possible till then

**Comment by Cadair** [comment]
revert this commit: https://github.com/sunpy/sunpy/pull/2463/commits/a71c32e8624205ef6b4e0c77fbe419e8f19bf3c5

**Comment by nabobalis** [comment]
DROP IT. 

Also did you revert that commit?

**Comment by Cadair** [comment]
I did.

**Comment by dpshelio** [comment]
When will we be closing this issue?

**Comment by nabobalis** [comment]
When we do more changes.
