### ISSUE TITLE
Ticklabel Control for ImageAnimatorWCS

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#2288]
Add the following functionalities to ```ImageAnimatorWCS```:
1. Allow user to define the units they want the axes to appear in.
2. Either make ImageAnimator show tick labels with a reasonable format (e.g. adjust scientific notation, significant figures, etc.) and/or allow user to define the format.  This could prevent ticklabels overlapping and being unreadable.

The ```unit_x_axis``` will not necessarily be length.  It will depend on the WCS object.  It's probably easiest if the default units are ```None``` which means the data values will automatically be in the wcs object's units.  Then if the units are set by the user, the appropriate conversion must be done.

The wcs object's units I think can be found in the ```wcs.cunitX``` attributes where ```X``` is the axis number.

**Comment by tosalonijain** [comment]
I want to take up this issue.

**Comment by tosalonijain** [comment]
I want to take up this issue.

**Comment by prateekiiest** [comment]
@DanRyanIrish what's the default unit for unit_x_axis ?
`u.m` or `u.km`

**Comment by DanRyanIrish** [comment]
Hi @prateekiiest and @tosalonijain.  Apologies for the delay in replying but I've only just returned from holiday and am catching up with things.

The ```unit_x_axis``` will not necessarily be length.  It will depend on the WCS object.  It's probably easiest if the default units are ```None``` which means the data values will automatically be in the wcs object's units.  Then if the units are set by the user, the appropriate conversion must be done.

The wcs object's units I think can be found in the ```wcs.cunitX``` attributes where ```X``` is the axis number.

Hope this helps.

**Comment by nabobalis** [comment]
I think we can close this, WCSAxis, allows a user to tidy up their plot by calling a range of functions. I do not think we need a function to do this now. 

Unless you have any objections @DanRyanIrish.
