### ISSUE TITLE
Installed SunPy and ran self_test

### ISSUE THREAD

**Issue by apsv** [sunpy/sunpy#2290]
Hi, 
I am very new to Python. I do not know if the following errors affect me in anyway. But a few things like read or read_file (while trying to read a fits file) aren't working (gives a read not defined NameError) (may be there are similar dependencies that the following test programs are using). Any advice/help is appreciated. 

============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: ... inifile: 
plugins: hypothesis-3.23.0
collected 1168 items / 2 errors 
==================================== ERRORS ====================================
 ERROR collecting anaconda2/lib/python2.7/site-packages/sunpy/net/tests/test_helio.py 
ImportError while importing test module '/nfs/morgan/users/aparna/anaconda2/lib/python2.7/site-packages/sunpy/net/tests/test_helio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../../anaconda2/lib/python2.7/site-packages/sunpy/net/tests/test_helio.py:10: in <module>
    import mock
E   ImportError: No module named mock
 ERROR collecting anaconda2/lib/python2.7/site-packages/sunpy/util/tests/test_util.py 
ImportError while importing test module '/nfs/morgan/users/aparna/anaconda2/lib/python2.7/site-packages/sunpy/util/tests/test_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../../anaconda2/lib/python2.7/site-packages/sunpy/util/tests/test_util.py:9: in <module>
    from pytest_mock import mocker
E   ImportError: No module named pytest_mock
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!

**Comment by prateekiiest** [comment]
From what I understood, some modules weren't installed/
You can simply do 
`pip install -i https://pypi.anaconda.org/pypi/simple pytest-mock`
or
`pip install pytest-mock`

and with that `pip install mock` for python < 3.3 in your case 2.7.

Check if its working and let us know if it still shows an error.

**Comment by Cadair** [comment]
Hi @apsv it looks like you installed with conda so @prateekiiest's solution is almost right but using `conda install mock pytest-mock` would be better.

Also, what version of SunPy have you got installed? I thought we had fixed these issues with 0.8.1.

**Comment by alwilliams2433** [comment]
I just downloaded sunpy test received almost identical error.  ran pip install pytest mock as well... help

================================== ERRORS ====================================
___________ ERROR collecting coordinates/tests/test_offset_frame.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\coordinates\tests\test_offset_frame.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\coordinates\tests\test_offset_frame.py:3: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis.strategies'
____________ ERROR collecting net/dataretriever/tests/test_eve.py _____________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_eve.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_eve.py:14: in <module>
    from hypothesis import given, settings
E   ImportError: cannot import name 'given'
__________ ERROR collecting net/dataretriever/tests/test_goes_ud.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_goes_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_goes_ud.py:11: in <module>
    from hypothesis import given, example
E   ImportError: cannot import name 'given'
__________ ERROR collecting net/dataretriever/tests/test_lyra_ud.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_lyra_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_lyra_ud.py:12: in <module>
    from hypothesis import given
E   ImportError: cannot import name 'given'
____________ ERROR collecting net/dataretriever/tests/test_norh.py ____________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_norh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_norh.py:13: in <module>
    from hypothesis import given
E   ImportError: cannot import name 'given'
___________________ ERROR collecting net/tests/test_fido.py ___________________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\tests\test_fido.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\tests\test_fido.py:6: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis.strategies'
!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!
============================ 163 tests deselected =============================
================== 163 deselected, 6 error in 67.65 seconds ===================

**Comment by nabobalis** [comment]
@alwilliams2433 Unfortunately right now, the latest conda package for hypothesis is broken. 

I would suggest a downgrade from 3.33, but hypothesis broken should not affect the usage of core sunpy, just the tests.
