### ISSUE TITLE
Mapcube animation is not tested

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2296]
#2295 points out the fact we don't have a test suite for the plotting capability of MapSequence.
That's not good.
So we need a MapSequence plot test.

https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapsequence.py
https://github.com/sunpy/sunpy/blob/master/sunpy/map/tests/test_mapsequence.py

MapSequence  animation relies on https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/animator/mapsequenceanimator.py 

This code has no tests - see https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/animator/tests 

Tests for MapSequenceAnimator go in this subdirectory.
All the methods for the MapSequenceAnimator object will need tests.

A previous attempt was made here (when it was called MapCube): https://github.com/sunpy/sunpy/pull/2564

**Comment by yashkgp** [comment]
Hey @wafels  Can i get more information on this issue?

**Comment by wafels** [comment]
Mapcube animation relies on https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/mapcubeanimator.py .  This code has no tests - see the subdirectory https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/tests . Tests for mapcubeanimator go in this subdirectory.  All the methods for the MapCubeAnimator object will need tests.

**Comment by jeffreypaul15** [comment]
After it was renamed to ```MapSequence```, are there still absent here?

**Comment by nabobalis** [comment]
They should still be.

**Comment by jeffreypaul15** [comment]
> They should still be.

Any leads on how to go about testing this? Seems intriguing considering I just worked on this.

**Comment by nabobalis** [comment]
Similar to the arrayanimator ones?

**Comment by jeffreypaul15** [comment]
> Similar to the arrayanimator ones?

Should the sliders and buttons be tested as well? They are inherited from ```BaseFuncAnimator``` which is already tested while ```ArrayAnimator``` is being tested

**Comment by nabobalis** [comment]
Should probably make sure that the sliders work.
