### ISSUE TITLE
Some docstrings for net.vso.attrs are not showing up correctly on RTD

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#2299]
Example: http://docs.sunpy.org/en/latest/api/sunpy.net.vso.attrs.Resolution.html#sunpy.net.vso.attrs.Resolution

It looks like the docstrings are not being parsed by sphinx correctly, possibly not in the correct format?

**Comment by wafels** [comment]
My bad. Provider, Source, Physobs, Level, Resolution, Detector, Quicklook and PScale are all affected.  The fix is pretty simple.  Putting "Notes" and the appropriate number of minus signs underneath "Notes" should fix this.

**Comment by samaloney** [comment]
Yea I wasn't sure what it was suppose to look like in my PR #2309 an examples below from my local build. The reference section needs to be updated/removed as well as notes section.

<img width="818" alt="screen shot 2017-10-19 at 19 25 42" src="https://user-images.githubusercontent.com/24570854/31787485-d34fa6a8-b503-11e7-8481-974a8630c443.png">

<img width="812" alt="screen shot 2017-10-19 at 19 31 26" src="https://user-images.githubusercontent.com/24570854/31787605-302a65ca-b504-11e7-9740-a1f1fe5e3f76.png">

**Comment by wafels** [comment]
Yous looks better than mine.  I've closed my PR and approved yours.

Sorry about that.

**Comment by samaloney** [comment]
No bother, cheers.

On 19 Oct 2017, at 20:48, Jack Ireland <notifications@github.com<mailto:notifications@github.com>> wrote:

Yous looks better than mine. I've closed my PR and approved yours.

Sorry about that.

**Comment by wafels** [comment]
Closed by #2309
