### ISSUE TITLE
Example gallery: how to get fine-grained control of the Stonyhurst grid

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2307]
A user has asked about achieving fine-grained control of overplotted Stonyhurst grid.  @Cadair has provided an example of how this can be achieved.  I suggest that an addition to the example gallery be made to show how this can be done.

**Comment by Cadair** [comment]
The example I provided is this: https://groups.google.com/d/msg/sunpy/Mxo8f9PKMdw/cm_DuJvwAQAJ for reference.

**Comment by wafels** [comment]
closed by #2435
