### ISSUE TITLE
Changelog not updated from 0.8 to 0.8.2

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2311]
There is no changelog entry with entries for 0.8.1 or 0.8.2.

**Comment by Cadair** [comment]
are you looking on the 0.8 branch?

**Comment by nabobalis** [comment]
They exist in the 0.8 branch.

**Comment by wafels** [comment]
Why are they not in master?

**Comment by nabobalis** [comment]
I can fix that, I just felt that updating the Log in the 0.8 branch was the way forward leaving people to add new stuff for 0.9 into master.
