### ISSUE TITLE
Some multi-line code samples in the documentation don't render properly

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2315]
There are some examples in the documentation that when clicked on `>>>` on the top right corner of the code block for copy/paste the other lines disappear. This is to do with not having `...` in the multiple lines.

**Comment by Cadair** [comment]
links to examples?

**Comment by dpshelio** [comment]
I'm working on it, PR coming soon.

**Comment by wafels** [comment]
Closed by #2317.
