### ISSUE TITLE
Hypothesis will not import under conda

### ISSUE THREAD

**Issue by alwilliams2433** [sunpy/sunpy#2323]
I just downloaded sunpy test received almost identical error to the one on 9/21. I ran pip install pytest mock as well... help!!

================================== ERRORS ====================================
___________ ERROR collecting coordinates/tests/test_offset_frame.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\coordinates\tests\test_offset_frame.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\coordinates\tests\test_offset_frame.py:3: in 
import hypothesis.strategies as st
E ModuleNotFoundError: No module named 'hypothesis.strategies'
____________ ERROR collecting net/dataretriever/tests/test_eve.py _____________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_eve.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_eve.py:14: in 
from hypothesis import given, settings
E ImportError: cannot import name 'given'
__________ ERROR collecting net/dataretriever/tests/test_goes_ud.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_goes_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_goes_ud.py:11: in 
from hypothesis import given, example
E ImportError: cannot import name 'given'
__________ ERROR collecting net/dataretriever/tests/test_lyra_ud.py ___________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_lyra_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_lyra_ud.py:12: in 
from hypothesis import given
E ImportError: cannot import name 'given'
____________ ERROR collecting net/dataretriever/tests/test_norh.py ____________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_norh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\dataretriever\tests\test_norh.py:13: in 
from hypothesis import given
E ImportError: cannot import name 'given'
___________________ ERROR collecting net/tests/test_fido.py ___________________
ImportError while importing test module 'c:\Anaconda3\lib\site-packages\sunpy\net\tests\test_fido.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\Anaconda3\lib\site-packages\sunpy\net\tests\test_fido.py:6: in 
import hypothesis.strategies as st
E ModuleNotFoundError: No module named 'hypothesis.strategies'
!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!
============================ 163 tests deselected =============================
================== 163 deselected, 6 error in 67.65 seconds ===================

**Comment by prateekiiest** [comment]
are you on python 3?

**Comment by alwilliams2433** [comment]
yes. 3.6.1

**Comment by prateekiiest** [comment]
the import formats in python 3 and 2 are different. So you are getting an error since your using py3 and the import format there is in py2

**Comment by prateekiiest** [comment]
we have an issue which you can check here https://github.com/sunpy/sunpy/issues/2287

@Cadair, what do you say?

**Comment by alwilliams2433** [comment]
ok I thought I was using py3 installation.  Thank you soooo much!

**Comment by Cadair** [comment]
This is an issue with the latest version of the hypothesis conda package.

@alwilliams2433 your sunpy installation will work fine as we only use hypothesis for tests. We are working on a fix for this with the hypothesis package maintainers.

**Comment by Cadair** [comment]
The broken package has now been flagged as such on conda-forge so this should not affect any new users.

**Comment by alwilliams2433** [comment]
Thank you all for responding...

**Comment by Cadair** [comment]
@alwilliams2433 thank you for the bug report. :)
