### ISSUE TITLE
Enhancing off-limb emission - wrong legend

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2328]
The existing legend in the "Enhancing off-limb emission" example describing the function that is fit is wrong.  The function should be an exponential decay with radius, not a power law.  Also, the x-axis caption should read "radius (R_sun)", since the units are solar radii.  The scale_factor function is wrong too, and so the resulting enhanced map is not right.

**Comment by wafels** [comment]
Example fixed version

![figure_3](https://user-images.githubusercontent.com/983575/32339825-4478d932-bfcf-11e7-8f8c-a5ea06d366d8.png)

**Comment by nabobalis** [comment]
Closed via #2329
