### ISSUE TITLE
Use aiaprep with maps besides AIA

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2331]
[There is a line in `sunpy.instr.aia.aiaprep`](https://github.com/sunpy/sunpy/blob/master/sunpy/instr/aia.py#L45) that throws an error if `aiaprep()` is called on any Map other than an AIA map. However, this function is still useful for centering and derotating other maps, e.g. if one were to overplot AIA emission on an HMI map.

Could this check be removed so that aiaprep can be called on maps besides AIA? It does not seem that anything AIA-specific is being done in this function and that it could be applicable to other maps as well.

**Comment by larrymanley** [comment]
It is AIA-specific because it adjusts the plate scale (arcsec/pixel) to 0.6.  Keep in mind that AIA is 0.6, but HMI is 0.5.  Take a look at the code in issue #1697 for an example of compositing AIA and HMI

**Comment by wtbarnes** [comment]
Ah ok. Forgot about the plate scale values. 

The example in that PR should really be added to the gallery example then. I've tried using masked Numpy arrays with composite maps, but for whatever reason the mask is completely ignored once the composite map is created. So if clipping works, then this should be advertised.
