### ISSUE TITLE
FIDO XRSClient query results are mislabeled

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#2335]
When using FIDO to search for and download GOES XRS data, the results from a FIDO.search() are mislabeled, although the actual downloaded files are correct. For example:

    from sunpy.net import Fido
    from sunpy.net import attrs

    files = Fido.search(attrs.Time('2011-06-07','2011-06-09'),attrs.Instrument('goes'))
    files
    
    <sunpy.net.fido_factory.UnifiedResponse object at 0x1155c7ed0>
    Results from 1 Provider:

    3 Results from the XRSClient:
     Start Time           End Time      Source Instrument Wavelength
       str19               str19         str4     str4       str3   
    ------------------- ------------------- ------ ---------- ----------
    2011-06-07 00:00:00 2011-06-09 00:00:00   nasa       goes        nan
    2011-06-07 00:00:00 2011-06-09 00:00:00   nasa       goes        nan
    2011-06-07 00:00:00 2011-06-09 00:00:00   nasa       goes        nan

There are three entries, all with the same start and end time, which is misleading. But, if you download the actual files they are correct.

    Fido.fetch(files)
    [========================================] 
    ['/Users/ainglis/sunpy/data/go1520110608.fits',
     '/Users/ainglis/sunpy/data/go1520110607.fits',
     '/Users/ainglis/sunpy/data/go1520110609.fits']

The actual functionality is correct, so it's mainly a quality of life issue.

**Comment by Cadair** [comment]
@dpshelio didn't you do some work on making it possible to fix this? I am sure we have talked about this before somewhere.
