### ISSUE TITLE
Figure out how .peek() should behave 

### ISSUE THREAD

**Issue by himanshukgp** [sunpy/sunpy#2352]
Currently peek() works does not display in Ipython Notebook inline.

peek should not block the execution of a script.  It should display in an interactive session and allow the code to continue.

In non-interactive scripts, `plt.show` should be used. 

Also check to make sure it works in iPython notebooks or whatever they are called now.

**Comment by CaptainDaVinci** [comment]
The call to `show()` should be made on `pyplot` object not on a `Figure` object.

**Comment by yudhik11** [comment]
You can simply use matplotlib to overcome this bug

import numpy as np
import matplotlib.pyplot as plt
import sunpy.data.sample
import sunpy.timeseries as ts
my_timeseries = ts.TimeSeries(sunpy.data.sample.GOES_XRS_TIMESERIES, source='XRS')
#my_timeseries.peek()
fig = plt.figure()
my_timeseries.plot()
plt.show()

now after running python test.py the plot won't disappear

**Comment by yudhik11** [comment]
@CaptainDaVinci  @himanshukgp  can you check that your problem is now resolved

**Comment by nabobalis** [comment]
@yudhik11 While that might work around the issue, we still need to solve the original problem.
