### ISSUE TITLE
Post Python 2: Refactor `parse_time` to use the singledispatch module

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2383]
The list of if statements in `parse_time` is a perfect usecase for the generic programming style provided by the [singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch) module in the standard library.

*This can not be done until after 0.9*

**Comment by vermashresth** [comment]
Hi @Cadair
I would like to work on this but I have some doubts. Singledispatch works with dispatching on arument based on type but here, in some cases, we are using specific values like `elif time_string is 'now':` and also some cases have an additional boolean condition like `elif isinstance(time_string, pandas.Series) and 'datetime64' in str(time_string.dtype)`. Can you please suggest how should we handle that?

**Comment by Cadair** [comment]
@vermashresth I am not entirely sure, I would imagine that some of the functions will have to have extra conditionals and checks inside the functions.

**Comment by abhayjindal51** [comment]
Hi @Cadair 
I would like to work on this issue.

**Comment by nabobalis** [comment]
Closed by #2408
