### ISSUE TITLE
Post Python 2: Refactor Map and Timeseries factory to use singledispatch in `__call__`

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2384]
This would remove the large amount of nested if statements, and also allow user code and other packages to add extra argument parsing to the factories.

[singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch)

*This can not be done until after 0.9*

**Comment by talsperre** [comment]
Hi @Cadair. 
I was looking at this issue and wanted to work on it. Are you referring to the nested if statements in ```_parse_args``` that is called in ```__call__``` function? Some of the conditionals here require the use of ```self``` i.e. class methods such as:
```
# A URL
elif (isinstance(arg, six.string_types) and
      _is_url(arg)):
    url = arg
    path = download_file(url, get_and_create_download_dir())
    pairs = self._read_file(path, **kwargs)
    data_header_pairs += pairs
```
 How should ```functools.singledispatch``` be used with instance methods?  Would something like [this](https://stackoverflow.com/a/24602374) do?
