### ISSUE TITLE
Incorrect date string format

### ISSUE THREAD

**Issue by swapsha96** [sunpy/sunpy#2392]
The string in line [317](https://en.wikipedia.org/wiki/ISO_8601) of [differential_rotation.py](https://github.com/sunpy/sunpy/blob/master/sunpy/physics/differential_rotation.py) doesn't follow ISO-8601 representation that is widely accepted. Below is the examples from [wikipedia](https://en.wikipedia.org/wiki/ISO_8601):
```
2018-01-08T02:09:30+00:00
2018-01-08T02:09:30Z
20180108T020930Z
```
The second one is mostly used to display `datetime` in isoformat. THe change is minor but is necessary in order to make parsing easier.
I've come across to this file only. Please let me know if there are more files where similar change is required.

**Comment by swapsha96** [comment]
@Cadair @dpshelio @nabobalis

**Comment by Cadair** [comment]
@swapsha96 Sorry to be the bearer of bad news on this one, but it shouldn't have the `Z` on the end.

The metadata dicts used in map are reformulated FITS headers, and therefore need to maintain compatibility with the [FITS standard](https://fits.gsfc.nasa.gov/fits_standard.html), to quote from the FITS time standard paper:

> As specified by Bunclark & Rots (1997), time zones are explicitly not supported in FITS and, consequently, appending the letter ‘Z’ to a FITS ISO-8601 string is not allowed. The rationale for this rule is that its role in the ISO standard is that of a time zone indicator, not a time scale indicator. As the concept of a time zone is not supported in FITS, the use of time zone indicator is inappropriate. 

[[1]](https://www.aanda.org/articles/aa/full_html/2015/02/aa24653-14/aa24653-14.html#S3)

What are you using to parse a time that wants the 'Z' on the end? I don't think that `datetime` has any issues with it, and `sunpy.time.parse_time` certaintly won't.
