### ISSUE TITLE
New NumPy update breaks some of the documentation tests

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2394]
NumPy v1.14.0 updates the way that arrays and numbers are printed to the terminal. As we use this alot in the documentation testing, we have a problem. 

Fixing this will mean running the documentation tests locally, checking the print out and changing the current results to the now expected results. Probably just to simpler to run the documentation code in a terminal and then copy and paste terminal output to the places it needs changing.

**Comment by yashkgp** [comment]
Hey @nabobalis, I want to work on this issue. Will I have run all the codes in the documentation?

**Comment by nabobalis** [comment]
@yashkgp, you would have to run the SunPy test suite locally using `pytest -k-figure` after having configured the local python environment with all our test depencides and having the main repo cloned locally. That should print out to your terminal all the test failures (you could pipe it to a file instead).

You could also have a look at the travis jobs and see the output there.  But I have not checked the CI in a while now. 

If you are unsure how to do any of these we do have some guides, [here](http://docs.sunpy.org/en/stable/dev_guide/newcomers.html) and [here](http://docs.sunpy.org/en/stable/dev_guide/tests.html) which hopefully would be useful.

**Comment by yashkgp** [comment]
@nabobalis I ran the test locally with NumPy v1.14 , Its passing all the test . The result of the test was : 
```
============================= 28 tests deselected ==============================
 1246 passed, 168 skipped, 28 deselected, 1 xpassed, 743 warnings in 381.21 seconds 
```
Numpy version that I am using 
```
numpy                     1.14.0           py36h3dfced4_0    anaconda
```

**Comment by nabobalis** [comment]
@yashkgp I suspect you used the wrong method to call the doctests. 
`sunpy.self_test()` or the `python setup.py test` do not call the doctests. It is a known issue that will hopefully be fixed eventually. You have to call pytest directly with `pytest -k-figure` from the main sunpy folder. 

You should see 1500+ tests and these [results.](https://travis-ci.org/sunpy/sunpy/jobs/328136830) Note that as I write this, its running but on my fork of sunpy, I see ~10 doctest failures.

**Comment by yashkgp** [comment]
Hey @nabobalis 
I have send a PR .Can you give it a look?

**Comment by nabobalis** [comment]
@yashkgp Sure
