### ISSUE TITLE
Fido.fetch should accept pathlib.Path objects.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2400]
i.e.:

```python
path = Path('/home/stuart/sunpy/data/jsocflare/')
results = Fido.search(...)
files = Fido.fetch(results, path=path)
```

**Comment by jnanjekye** [comment]
Would love to work on this.

**Comment by Cadair** [comment]
@jnanjekye feel free. Ask here or in our matrix channel if you need any pointers.

**Comment by getsanjeev** [comment]
@Cadair If it is still not assigned, I would love to give it a try. Should I start?
