### ISSUE TITLE
Coordinate transformation chart too wide for page

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2406]
http://docs.sunpy.org/en/stable/code_ref/coordinates.html - scroll the to the bottom, and the transformation chart is too wide for the page. It's also not possible to scroll right to see the rest - the only way is to make the browser window possible or zooming out.

**Comment by dpshelio** [comment]
Could a solution be that we show a thumbnail that expands when clicked?

**Comment by dstansby** [comment]
Possibly - on the corresponding astropy page scrolling to the right is possible, so maybe that could be changed on the sunpy website too?

**Comment by getsanjeev** [comment]
@dpshelio @dstansby  I would love to do it, following any method (either thumbnail option or adding a horizontal scroller). I would prefer the former to preserve uniformity. May I start?

One third option can be to add Horizontal scroller to the this section only, as done above in the layout.
![selection_086](https://user-images.githubusercontent.com/20872683/35225226-bbb9ad32-ffad-11e7-99e3-cf46b677608b.png)

**Comment by getsanjeev** [comment]
An obvious quick fix is to set width = 100 % in object tag. But it is somewhat less clear, It would look like this : 
![77e75d94-f2be-4ccd-ae36-e3d2b960ecfd](https://user-images.githubusercontent.com/20872683/35226093-43aed5ee-ffb0-11e7-9e6a-695c5a945b9a.jpeg)

**Comment by getsanjeev** [comment]
An obvious quick fix is to set width = 100% in object tag. This would look like - 

![option_2](https://user-images.githubusercontent.com/20872683/35226885-9d98338c-ffb2-11e7-9125-f7e716a947c6.jpeg)

But this is somewhat less clear, So I would suggest going with the third option (putting a horizontal scroll bar in the section) would be better. This results in : 

![horizontal_scroll_bar](https://user-images.githubusercontent.com/20872683/35227069-0e032d02-ffb3-11e7-9df0-539a955e7e43.gif)

**Comment by nabobalis** [comment]
This is most likely only fixable at the [sunpy-sphinx-theme](https://github.com/sunpy/sunpy-sphinx-theme).

**Comment by getsanjeev** [comment]
@nabobalis I did not get that. Can you please elaborate it?

**Comment by nabobalis** [comment]
The documentation is built using a custom theme. So if html or CSS changes are required, it's mostly going to be made there and not here. However, that's a guess since I've never dealt with those images directly.

**Comment by nabobalis** [comment]
Send a PR, I'd go for a slider myself and apply it to all the graphs if we can.

**Comment by nabobalis** [comment]
But we can change things around if need be.

**Comment by getsanjeev** [comment]
@nabobalis I am making PR in sunpy-sphinx-theme and astropy which addresses this issue. I will let you know when it gets merged in astropy, only after that we should merge it in sunpy-sphinx-theme. Is that alright?

**Comment by dstansby** [comment]
It scrolls nicely now, thanks to whoever fixed it!
