### ISSUE TITLE
Some coordinate frames aren't well defined

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2419]
I'm trying to understand some of the coordinate frames build in to SunPy, but some of the documentation doesn't give enough information to understand how the frames are defined:

- [ ] [HeliographicCarrington](http://docs.sunpy.org/en/latest/api/sunpy.coordinates.frames.HeliographicCarrington.html#sunpy.coordinates.frames.HeliographicCarrington):
Not clear what the zero-longitude is defined as. ("defined using an offset which is a time-dependent scalar value." makes no sense to me, because the offset isn't defined)
- [ ] [Heliocentric](http://docs.sunpy.org/en/latest/api/sunpy.coordinates.frames.Heliocentric.html#sunpy.coordinates.frames.Heliocentric):
I think the origin is at the center of the Sun, but which direction do the coordinate axes point in?

**Comment by Cadair** [comment]
@dstansby I am painfully aware of the deficiencies in the SunPy docs with respect to the definitions of the frames. I should really get back to working on my documentation of that.

To answer your questions:

1. The offset in heliographic is the longitude offset 0-306 deg based on the time in the current carrington rotation. i.e. it's 0 every 27 days.

2. Yes, the origin is at the centre of the Sun and the the "x" axis points towards the obsever. (with the z axis being 90 degrees offset to x in the same plane, and the y axis being perpendicular to the other two.)

**Comment by wtbarnes** [comment]
@dstansby If you haven't already, take a look at the [Thompson (2006)](http://adsabs.harvard.edu/abs/2006A%26A...449..791T) paper. It defines the all of the coordinate frames/systems quite clearly. Of course this still doesn't solve the problem of the documentation being a bit difficult to parse. Continually pointing people towards a paper is not a great solution...

@Cadair It'd probably be helpful to include a few diagrams in the coordinate system descriptions in the docs. An accompanying example in the gallery would probably also be really helpful.

**Comment by Cadair** [comment]
I have been working on a detailed description of the frames for a number of years! I have a draft of the prose, I am still working on the diagrams though.

**Comment by dstansby** [comment]
Ah, sorry I didn't realise. If you have something better I'm happy to close my PR?

**Comment by Cadair** [comment]
No! Yours is very welcome, I have been attempting to write some decent narrative docs to explain them to people. At this point it might never actually happen 😁
