### ISSUE TITLE
timeseries/sources/* peek functions sometimes accept kwargs but don't pass them to plot

### ISSUE THREAD

**Issue by jmason86** [sunpy/sunpy#2420]
Some of the files under timeseries/sources/ accept ```**kwargs``` for the ```peek``` function but do not then pass them to the plot function. 
It looks like this is presently the case for: 

- fermi_gbm.py
- goes.py (this peek function doesn't accept ```kwargs``` at all but does include it in the docstring
- noaa.py
- norh.py
- rhessi.py

**Comment by dstansby** [comment]
Looking through the code this has been fixed at some point.
