### ISSUE TITLE
python setup.py build_sphinx throws DBAccessError error while generating gallery 

### ISSUE THREAD

**Issue by getsanjeev** [sunpy/sunpy#2428]
While generating gallery with the command given in documentation : 
    python setup.py build_sphinx -o
The following erro is thrown -
WARNING: /home/sherlock/miniconda3/sunpy-git/examples/hmi_synoptic_maps.py failed to execute correctly: Traceback (most recent call last):
  File "/home/sherlock/miniconda3/sunpy-git/examples/hmi_synoptic_maps.py", line 26, in <module>
    'http://jsoc.stanford.edu/data/hmi/synoptic/hmi.Synoptic_Mr.2191.fits', cache=True)
  File "/usr/local/lib/python2.7/dist-packages/astropy/utils/data.py", line 1056, in download_file
    with _open_shelve(urlmapfn, True) as url2hash:
  File "/usr/local/lib/python2.7/dist-packages/astropy/utils/data.py", line 1354, in _open_shelve
    shelf = shelve.open(shelffn, protocol=2)
  File "/usr/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/usr/lib/python2.7/dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "/usr/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
DBAccessError: (13, 'Permission denied')

Exception occurred:
  File "/usr/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
DBAccessError: (13, 'Permission denied')
The full traceback has been saved in /tmp/sphinx-err-hF24q7.log, if you want to report the issue to the developers.
[sphinx-err-hF24q7.log](https://github.com/sunpy/sunpy/files/1661488/sphinx-err-hF24q7.log)

**Comment by nabobalis** [comment]
Are you using anaconda or system python?

**Comment by getsanjeev** [comment]
I have setup miniconda environment (just a chance - not well setup), but I followed sunpy documentation and have ensured that I am in my sunpy-dev environment.

Any quick way to check my environment? I am also looking at internet to understand it better.

**Comment by nabobalis** [comment]
Well your error stems from a python 2.7 issue from your system python. You seem to have a anaconda 3 setup, so it should error from within that.

**Comment by getsanjeev** [comment]
Yes right, error stems from python 2.7. And yes my conda version is 3.

**Comment by getsanjeev** [comment]
@nabobalis yeah everything is working! I am closing the issue.

**Comment by nabobalis** [comment]
I'm happy you fixed the issue!
