### ISSUE TITLE
Map not recognizing EIT coordinates.

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#2430]
Something is messed up with the EIT map coordinates. The meta data and WCS looks OK at first glance, but the coordinate grid isn't being translated properly. 

`from sunpy.map import Map`
`eit=Map(sunpy.data.sample.EIT_195_IMAGE)`
`eit.peek()`

![eit_example](https://user-images.githubusercontent.com/5497326/35360322-5ac25432-012b-11e8-8554-218c427f171d.png)

**Comment by Cadair** [comment]
This should be fixed by #2398

**Comment by MSKirk** [comment]
I am using version 0.8.2, was it back-ported?

**Comment by nabobalis** [comment]
Yes to the next release which I have not released yet.

**Comment by MSKirk** [comment]
In `mapbase.py`,  `pixel_to_world` also returns `SkyCoord` using `frame=self.coordinate_frame` causing similar issues.

**Comment by MSKirk** [comment]
Does #2398 also fix "Warning: Missing metadata for Carrington longitude: assuming Earth-based observer" when querying the `eit.wcs`?

**Comment by nabobalis** [comment]
No it probably only fixes the plotting issue.

**Comment by nabobalis** [comment]
So we might need to change it in mapbase as well?

**Comment by MSKirk** [comment]
@wafels and I are looking into what exactly needs to be changed.

**Comment by Cadair** [comment]
> In mapbase.py, pixel_to_world also returns SkyCoord using frame=self.coordinate_frame causing similar issues.

Can you elaborate on that? If there is something wrong with that it's a very different bug.

**Comment by MSKirk** [comment]
The ephemeris generated by the current coordinate frame (e.g. distance to sun, solar radius, center) is about 0.1% - 1% different than using the EIT image header keywords `HEC_X`, `HEC_Y`, and `HEC_Z`. This means coordinate calculations can be off by about as much as a few pixels, especially near the limb of the sun.

**Comment by Cadair** [comment]
Interesting. I would be interested to know the source of that discrepancy. Also we should find a way to load the info from the header. 

What coordinate system is HEC?

**Comment by wafels** [comment]
The HEC co-ordinate system is defined here:

https://soho.nascom.nasa.gov/data/ancillary/index.html#orbitcoordinates

**Comment by Cadair** [comment]
> The Heliocentric Ecliptic coordinate system is defined as follows: the origin is Sun centered, with the Z axis parallel to the ecliptic pole with positive north of the ecliptic plane; the X-Y plane lies in the ecliptic plane and the X axis points towards the first point of Aries; the Y axis completes a right-handed orthogonal coordinate system.

That is one bonkers coordinate system...

**Comment by Cadair** [comment]
So other than an observer location error, is the plot bug in the original comment fixed?

**Comment by MSKirk** [comment]
Fortunately `astropy.coordinates` supports it!

**Comment by wafels** [comment]
That's as may be, but it is one that Astropy has apparently...

http://docs.astropy.org/en/stable/api/astropy.coordinates.HeliocentricTrueEcliptic.html#astropy.coordinates.HeliocentricTrueEcliptic

**Comment by wafels** [comment]
So we think that we can read in the HEC co-ordinate info for EIT and then
use the co-ordinate transformation graph to get the right Stonyhurst
observer location.

**Comment by Cadair** [comment]
@wafels you don't need to explicitly do the transform, just pass the HEC coordinate object in to frame and it will get transformed for you.

**Comment by wafels** [comment]
Yes - I think that is what I meant.

**Comment by MSKirk** [comment]
The major difference is that `astropy.coordinates` needs {Lat, Lon, Radius} coordinates and the EIT header has {X,Y,Z}.

**Comment by Cadair** [comment]
Construct a `CartesianRepresentation` object and pass that in as the only argument, should do the rest for you.

**Comment by wafels** [comment]
I came up with something.... the final result is




*In [4]: hgs_coordOut[4]: <HeliographicStonyhurst Coordinate
(obstime=2011-06-07 20:37:52.600000): (lon, lat, radius) in (deg, deg,
km)    (-0.24687872,  0.06050496,   1.50358425e+08)>*

As a sanity check:


*In [6]: np.sqrt(hec_x**2 + hec_y**2 + hec_z**2)Out[6]: <Quantity
150358424.9714794 km>*

So that looks OK.  The *lon* and *lat* values of *hgs_coord* are
reassuringly small, as they should be since SOHO orbits close to Earth/Sun
line.
Other sanity checks are in the code below.

If this checks out, we can use the code below to calculate the Sun/Earth
distance for EIT

*https://github.com/sunpy/sunpy/blob/master/sunpy/map/sources/soho.py#L82
<https://github.com/sunpy/sunpy/blob/master/sunpy/map/sources/soho.py#L82>*

and also explicitly meta entries for hglt_obs and hgln_obs

#
# Example EIT HEC to HGS conversion
#
import astropy.units as u
from astropy.coordinates import CartesianRepresentation,
HeliocentricTrueEcliptic

from sunpy.coordinates import HeliographicStonyhurst, get_sunearth_distance
from sunpy.data.sample import EIT_195_IMAGE
import sunpy.map

m = sunpy.map.Map(EIT_195_IMAGE)

hec_x = m.meta['hec_x'] * u.km
hec_y = m.meta['hec_y'] * u.km
hec_z = m.meta['hec_z'] * u.km

cr = CartesianRepresentation(hec_x, hec_y, hec_z)

hte = HeliocentricTrueEcliptic(cr, obstime=m.date)

hgs_frame = HeliographicStonyhurst(obstime=m.date)

hgs_coord = hte.transform_to(hgs_frame)

hec_distance = np.sqrt(hec_x**2 + hec_y**2 + hec_z**2)

# Should be around 0.99, since SOHO is about 1% closer to
# the Sun than the Earth is
print(hec_distance/get_sunearth_distance(m.obstime))

# Should be very very close to each other, since the two
# co-ordinate systems represent the same co-ordinate in space
print(hec_distance, hgs_coord.radius)

# Should be close to zero since SOHO sits close to the Earth/Sun line
print(hgs_coord.lon, hgs_coord.lat)

**Comment by Cadair** [comment]
That looks very hopeful! I will have a proper read up on it.

I think the best thing to do would be to have the SOHO map sources override the `observer_coordinate` property and just return a HEC coordinate object. That should then do all the work 😁

**Comment by Cadair** [comment]
To complete the API they could then use that property to return `observer_longitude ` and `observer_latitude`

**Comment by MSKirk** [comment]
This issue seems to be related to issue #2445

**Comment by wafels** [comment]
From Bill: 

> What EIT calls HEC, SunSPICE calls HAE, for Heliocentric Aries Ecliptic.  That's a more common name in the literature. Heliocentric Earth Equatorial (HEEQ or HEQ) is the x,y,z equivalent of Stonyhurst heliographic.

Hmmm - the SOHO SPICE HAE values are not the same as the EIT FITS header HEC values for the date 2017-03-08 01:13:46.667000.  Seems like the EIT FITS header heliographic longitude value always zero, and the EIT FITS header heliographic latitude header is approximately that given by converting either the SOHO SPICE HAE values or the EIT FITS header HEC values to HGS values.

**Comment by wafels** [comment]
Using SPICE to transform the Cartesian EIT HEC values to their lon, lat, radius equivalent give values almost identical to the HeliocentricTrueEcliptic values (with equinox set the observation date) when passing in the Cartesian EIT HEC values as a CartesianRepresentation object.  This confirms that EIT coordinates need the equinox property set.

**Comment by ayshih** [comment]
I don't understand what you just wrote above.  It sounds like you're just converting between Cartesian and spherical representations without any frame transformation?  I don't get why the equinox matters in what you wrote.

**Comment by wafels** [comment]
That's right - no frame transformation.  When I convert the EIT HEC Cartesian representation to its spherical equivalent in SSWIDL / SPICE, I get the same answers as converting the EIT HEC Cartesian representation to HeliocentricTrueEcliptic with the equinox property set to the observation date.  It adds more information to the definition of the EIT HEC representation as described in https://soho.nascom.nasa.gov/data/ancillary/index.html#orbitcoordinates .

**Comment by MSKirk** [comment]
I just had a conversation with Dean Pesnell who said that the team using MDI to do helioseismology realized that the ephemeris from SOHO was not accurate enough for their purposes. They have been using the SPICE kernels for the last 15 years or so which has improved their science quality over using the MDI header information. I think this means in order to get the _right_ answer, an implementation of `spiceypy` is necessary.

**Comment by ayshih** [comment]
> That's right - no frame transformation. When I convert the EIT HEC Cartesian representation to its spherical equivalent in SSWIDL / SPICE, I get the same answers as converting the EIT HEC Cartesian representation to HeliocentricTrueEcliptic with the equinox property set to the observation date. It adds more information to the definition of the EIT HEC representation as described in https://soho.nascom.nasa.gov/data/ancillary/index.html#orbitcoordinates .

I disagree with the conclusion you draw here.  If you're not doing a frame transformation, the equinox attribute doesn't factor in.

**Comment by ayshih** [comment]
> I think this means in order to get the right answer, an implementation of spiceypy is necessary.

See https://github.com/sunpy/sunpy/issues/2445#issuecomment-364531159 for my confirmation that SunPy/Astropy agrees with SunSPICE.

**Comment by wafels** [comment]
You are right about my comment _That's right - no frame transformation. When I convert the EIT HEC Cartesian representation to its spherical equivalent in SSWIDL / SPICE, I get the same answers as converting the EIT HEC Cartesian representation to HeliocentricTrueEcliptic with the equinox property set to the observation date. It adds more information to the definition of the EIT HEC representation as described in https://soho.nascom.nasa.gov/data/ancillary/index.html#orbitcoordinates ._ - it is erroneous.  Following on from #2445 it is unclear if the EIT HEC vector is using the J2000 coordinate system or the observation date.

**Comment by MSKirk** [comment]
From Bill Thompson: 

> I took a look at some old EIT files that I had on my computer, and 
> compared them against SunSPICE values for heliographic coordinates.  It 
> appears that the radial distance from the Sun is good to about 3-4 
> significant figures, heliographic longitude is good to about a degree, 
> and heliographic latitude (B0) is good to about 0.1 degrees.
> 
> Looking at some data from 2008, I find that the agreement is excellent, 
> particularly if I assume that the EIT values are unprecessed.  With that 
> assumption, the radial distance is good to 6 significant figures, the 
> longitude is good to 0.003 degrees, and the latitude (B0) is good to 
> 0.001 degrees.
>
