### ISSUE TITLE
SWAP Map coordinate defaults 

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#2441]
Loading a stacked SWAP image into Map doesn't have a `ctype` specified in the header. The default value is set to `CTYPE : 'HPLN-   '  'HPLT-   '`, which causes problems in the `wcs` object. 

SWAP images that are unstacked (normal ones) have a `.coordinate_system` specified as  `SpatialPair(axis1='HPLN-TAN', axis2='HPLT-TAN')`. The SWAP Map source should be modified to assume a `HPLN-TAN` ctype when the filename attribute has "swap_stack" in it. 

The plotting also should be modified to add in `ImageNormalize` function like the EIT map source.

**Comment by Cadair** [comment]
What's the problem with defaulting to `HPLN-` rather than `HPLN-TAN`? If that is causing problems it's a bug that's bigger than just SWAP.

**Comment by wafels** [comment]
Maybe in the SWAPMap module we should detect the fact the file is a stacked file and then take the appropriate action to fix it so it acts like a proper sunpy map.

**Comment by dstansby** [comment]
Could someone post a link to an example SWAP file that has this issue?

**Comment by MSKirk** [comment]
They come in compressed .tar.gz files each containing a Carrington rotation worth of fits images. `http://proba2.sidc.be/swap/data/carrington_rotations/`

**Comment by MSKirk** [comment]
In each of these fits files, the header is abbreviated since they are created from a stack of level-1 processed SWAP images.

**Comment by Cadair** [comment]
> What's the problem with defaulting to `HPLN-` rather than `HPLN-TAN`? If that is causing problems it's a bug that's bigger than just SWAP.

I ran into issues with this when doing some of the recent submap work, so I think we might have a bigger issue on our hands with default to no projection. We probably want to default to `-TAN`.

**Comment by dstansby** [comment]
Just having a read of the README in that data directory (http://proba2.sidc.be/swap/data/carrington_rotations/about_these_files.txt), and it says

> not all of the files have compatible FITS headers, and not every file was prepared using the same algorithm. It is the intention of the SWAP team to replace all of these files with a self-consistent archive as soon as possible, but users should exercise caution when comparing images from one CR to another.

Does anyone know if the self-consistent archive now exists, or if there are plans for it? It seems silly to put it effort to support files that are self-described as not having compatible FITS headers if a better option is on the way or exists.

**Comment by MSKirk** [comment]
I am reaching out to the current SWAP team... the answer is not as simple as one would like.

**Comment by dstansby** [comment]
Since I don't think we want to be attempting to be compatible with a moving target (ie. a range of different headers in the current SWAP files) I'm going to close this as "won't fix" - if a self-consistent archive appears, and those files don't work with sunpy, then we can re-open this.
