### ISSUE TITLE
Possible Bug in MapcubeAnimator updatefig method

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy#2444]
## Problem

`MapcubeAnimator` class has a method called `updatefig`.

The bug is produced in the following manner.

                  from sunpy.map import MapCube
                  from sunpy.map import Map
                  import sunpy.map
                  from sunpy.data.sample import AIA_193_IMAGE

                  cube = Map(AIA_193_IMAGE, cube=True)   
                  z = MapCubeAnimator(cube)

                  MapCubeAnimator.updatefig(z,10,z.im,slider =2) 

returns error as this

                                       i = int(val)
                  ---> 77         im.set_array(self.data[i].data)
                       78              im.set_cmap(self.mapcube[i].plot_settings['cmap'])
                    

                      IndexError: list index out of range

Error in line : https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/mapcubeanimator.py#L77

## Possible Reason

This is because `z = MapCubeAnimator(cube)` returns `z.data` as

                [SunPy Map
                 ---------
                 Observatory:		 SDO
                 Instrument:		 AIA 2
                 Detector:		 AIA
                 Measurement:		 193.0 Angstrom
                 Wavelength:		 193.0 Angstrom
                 Observation Date:	 2011-06-07 06:33:07
                 Exposure Time:		 1.999683 s
                 Dimension:		 [ 1024.  1024.] pix
                 Coordinate System:	 helioprojective
                 Scale:			 [ 2.403032  2.403032] arcsec / pix
                 Reference Pixel:	 [ 512.5  512.5] pix
                 Reference Coord:	 [ 2.81709782  0.4292916 ] arcsec

                 array([[  4.,   3.,  -1., ...,   1.,   8.,  -4.],
                        [  1.,  -3.,   4., ...,  -2.,  -3.,  -9.],
                        [  8.,   0.,   3., ...,  -3.,   1., -11.],
                        ..., 
                        [  7.,  -8.,   7., ...,  -8.,   3.,   3.],
                        [  3.,  -1.,   4., ...,  -4.,   1.,  -8.],
                        [  6.,  -2.,   5., ...,   8.,  -4.,   0.]], dtype=float32)]

so `self.data[i]` or `z.data[i]` will work only when i = 0.

##  Possible Solution

Here https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/mapcubeanimator.py#L77
It should have been something like this `z.data[0].data[i]` or `self.data[0].data[i]`

**Comment by nabobalis** [comment]
Isn't the issue that `AIA_193_IMAGE` is just 2D data?

**Comment by prateekiiest** [comment]
yes `AIA_193_IMAGE` is a 2d data.

So does MapcubeAnimator operate only on 1D data?

**Comment by nabobalis** [comment]
It works on a sequence of 2D data.

**Comment by nabobalis** [comment]
I think that `MapCubeAnimator.updatefig(z,0,z.im,slider =2)` might work.

**Comment by prateekiiest** [comment]
will work, I used that too but it returns NoneType and BaseFuncAnimator fails

**Comment by prateekiiest** [comment]
since `BaseFuncAnimator` has some code saying `            if len(slider_functions) != len(slider_ranges):
                        raise ValueError("You must specify the same number of functions "
                                         "as extents")`

**Comment by prateekiiest** [comment]
updatefig works on the aiamap data I suppose, but self.data[0] is not that data

**Comment by nabobalis** [comment]
But to update the figure you would need another timestep no?

**Comment by prateekiiest** [comment]
which timestep you are talking about?

**Comment by nabobalis** [comment]
Well your updating figure, so there has to be something to update to. Generally MapCube is a sequence of Maps, so you are moving from the original Map to another one in that sequence.

**Comment by prateekiiest** [comment]
Is somewhere I am going wrong while defining the Mapcube function in the above code

**Comment by nabobalis** [comment]
No, I think the problem is your input data being 2D and trying to create a MapCube out of that.

**Comment by prateekiiest** [comment]
could you give an example of 1D array as input for MapCube?

**Comment by nabobalis** [comment]
Well the input generally isn't 1D array. 

It would be something like:

```python
a_list_of_data_files = glob.glob('/path/*.fits')
cube = Map(a_list_of_data_files, cube=True)
````

**Comment by prateekiiest** [comment]
Then I think there should be a raising an error while trying to pass 2D data in MapcubeAnimator

**Comment by nabobalis** [comment]
I'm not sure what it checks for. I'd assume that the input was a mapcube at least

**Comment by prateekiiest** [comment]
so I guess then we can close this
