### ISSUE TITLE
Heliocentric True Ecliptic to Heliographic Stonyhurst

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2445]
The gist here:

https://gist.github.com/wafels/c04bbea5d3beff3558497cb90f75c647

is some code that downloads EIT data, reads in the Heliocentric True Ecliptic position of SOHO from the FITS header, and attempts to calculate the position of SOHO in Heliographic Stonyhurst (HGS) co-ordinates.

Strangely, the distance of SOHO from the Sun changes depending on which co-ordinate system is used, and in one case SOHO is further away from the Sun than the Earth.  So either there is flaw in my code, or a flaw in how HGS is being calculated.  Any help is greatly appreciated!

**Comment by wafels** [comment]
See also https://umbra.nascom.nasa.gov/eit/eit_guide/headers.htm and https://soho.nascom.nasa.gov/data/ancillary/index.html#orbitcoordinates .

**Comment by ayshih** [comment]
I pointed out that `HeliocentricTrueEcliptic` needs to have its `equinox` specified, but apparently that doesn't fix the problem.

**Comment by MSKirk** [comment]
`HeliocentricTrueEcliptic` defaults to the J2000 location of the vernal equinox which is the definition that EIT is using the the header.

**Comment by ayshih** [comment]
Okay, good to know.

**Comment by dstansby** [comment]
Can you isolate a single coordinate point in `HTE` that when transformed to `HGS` goes wrong?

**Comment by ayshih** [comment]
I've done some testing entirely within Astropy's frames and transformations, and the bug doesn't appear to be on "our" side.  The origin of `HCRS` is not the same as the origin of `HeliocentricTrueEcliptic`.  Needs more investigation.

**Comment by ayshih** [comment]
Ah, bugs with Astropy's ecliptic transformations were fixed in December and released in Astropy 2.0.3.  However, I can only get Astropy 2.0.2 via conda?

**Comment by MSKirk** [comment]
`conda update astropy` brought me up to 2.0.3...  @wafels what version of Astropy are you running?

**Comment by wafels** [comment]
2.0.2.... will update to 2.0.3 and let you know.

**Comment by ayshih** [comment]
Okay, I figured out the issue I was having with the priority of conda channels, and now I'm running Astropy 2.0.3, so the ecliptic transformations are definitely looking sane again.  Before I resume investigating, @wafels can you confirm whether you're running Astropy 2.0.3 to get the weird results?

**Comment by ayshih** [comment]
Oops, heh, didn't see your posts!

**Comment by wafels** [comment]
HeliocentricTrueEcliptic now gets an obstime parameter that must be set in
order to use it for my purposes.

Astropy 2.0.3 fixes the Sun-SOHO distance issue.  However, the calculated
Heliographic Stonyhurst lat and lon seem to be out, with a maximum
difference of about 0.5 to 1 degrees compared to those in the FITS files/

**Comment by wafels** [comment]
Bill Thompson has been helping me with calculating HGS lat and lon using
the SSWIDL SunSPICE code and SOHO SPICE kernels.  Just to keep things
interesting, the HGS lat lon values from SSWIDL differ from the FITS file
values and the SunPy HGS values.👌

**Comment by wafels** [comment]
Certainly the fact that the Sun-SOHO distance is now preserved through the
co-ordinate round trip in SunPy is re-assuring.  I don't know *exactly* how
the EIT HGS lat, lon values are calculated, but I can find out (I suspect
that lon has a fixed value of zero).  I'll push on the SunSPICE part too
with Bill.  Understanding SPICE will help us in the future with Solar
Orbiter and Probe.

**Comment by dstansby** [comment]
Sounds like adding the transform roundtrip would be a nice test to have for coordinate transforms.

**Comment by wafels** [comment]
A roundtrip test may have caught this bug if the test had looked at the
intermediate step.  The roundtrip with the bug produces consistent answers
indicating that the forward and reverse transformations are operating
correctly as inverses of each other.  But you have to look at the
intermediate step to see that the transformation calculations are wrong.

It would be worth adding in some tests that test the correctness of
transformations between sunpy co-ordinate systems and astropy co-ordinate
systems for times at which we have an independent source to check against.
This would help bring issues like this one to the fore.

**Comment by wafels** [comment]
Anyway, yes to roundtrip tests against independently known values with
testing of sensibleness of the intermediate steps.

**Comment by ayshih** [comment]
@wafels Because the Heliocentric True Ecliptic coordinates in the FITS header are given in J2000, you actually need to do an additional transformation in SunPy/Astropy that I don't think you are doing.  The Heliocentric True Ecliptic coordinates need to be in the true-time equinox before being transformed to HGS.  In Astropy, directly transforming between two `HeliocentricTrueEcliptic` frames with different equinoxes doesn't appear to precess correctly, so you'll need to walk it through ICRS first.

**Comment by ayshih** [comment]
As an aside, we *do* have some tests that (implicitly) test the accuracy of SunPy/Astropy transformations (`test_ephemeris.py`).  I wrote them!  We need more for sure, but it's not like we're flying blind.

**Comment by wafels** [comment]
Ok, good to know about the tests.  I'll have a bunch more questions @ayshih after I read a little more about ICRS. Thanks!

**Comment by ayshih** [comment]
The specifics of ICRS don't particularly matter here, but Astropy transforms directly from `HeliocentricTrueEcliptic` to `ICRS`.  You just need to do `HeliocentricTrueEcliptic`(J2000)->`ICRS`->`HeliocentricTrueEcliptic`(true)->`HeliographicStonyhurst`.  You just need something to calculate the precession of the equinox before crossing from Astropy to SunPy.

**Comment by Cadair** [comment]
I am siting in room with @eteq and he points out that the lack of equinox conversion in astropy is bug we should report upstream if it is indeed true

**Comment by ayshih** [comment]
> I am siting in room with @eteq and he points out that the lack of equinox conversion in astropy is bug we should report upstream if it is indeed true

It's not a lack of equinox conversion in the sense that it's giving an incorrect answer, but rather it's not reporting the answer in the equinox that is presumably intended.  I can report the bug Later (TM).

**Comment by wafels** [comment]
So,  HeliocentricTrueEcliptic has a settable equinox property.  Let's use that to calculate the position of EIT at the image time of 2002-03-07 22:36:11.176000

```
[0] Coordinate Round trip
    (a) original Cartesian ( -1.42618976e+08,  35659708., -43472.35) km
     
    (b) distance 147009486.01970914 km
     
    (c) heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=2002-03-07 22:36:11.176000, obstime=2002-03-07 22:36:11.176000): (lon, lat, distance) in (deg, deg, km)
    ( 165.96187962, -0.016943,   1.47009486e+08)>
     
    (d) transformed to HGS <HeliographicStonyhurst Coordinate (obstime=2002-03-07 22:36:11.176000): (lon, lat, radius) in (deg, deg, km)
    ( 358.7669113, -7.26869163,   1.47009486e+08)>
     
    (e) back to heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=2002-03-07 22:36:11.176000, obstime=2002-03-07 22:36:11.176000): (lon, lat, distance) in (deg, deg, km)
    ( 165.96187962, -0.016943,   1.47009486e+08)>
 
```
And if you don't....

```
[0] Coordinate Round trip
    (a) original Cartesian ( -1.42618976e+08,  35659708., -43472.35) km
     
    (b) distance 147009486.01970914 km
     
    (c) heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=J2000.000, obstime=2002-03-07 22:36:11.176000): (lon, lat, distance) in (deg, deg, km)
    ( 165.96187962, -0.016943,   1.47009486e+08)>
     
    (d) transformed to HGS <HeliographicStonyhurst Coordinate (obstime=2002-03-07 22:36:11.176000): (lon, lat, radius) in (deg, deg, km)
    ( 358.79761779, -7.26863517,   1.47009486e+08)>
     
    (e) back to heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=J2000.000, obstime=2002-03-07 22:36:11.176000): (lon, lat, distance) in (deg, deg, km)
    ( 165.96187962, -0.016943,   1.47009486e+08)>

```

**Comment by MSKirk** [comment]
@wafels can you try a different example further away from the year 2000? I don't expect the Earth's precession to be much of an issue in 2 years. The earth only precesses about 0.014 degrees per year.

**Comment by wafels** [comment]
Good idea.

With the equinox keyword set...
```
 EIT 195 image time 2017-03-08 01:13:46.667000
 
[0] Coordinate Round trip
    (a) original Cartesian ( -1.43616960e+08,  32425350.,  76691.63) km
     
    (b) distance 147231927.25720266 km
     
    (c) heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=2017-03-08 01:13:46.667000, obstime=2017-03-08 01:13:46.667000): (lon, lat, distance) in (deg, deg, km)
    ( 167.27727131,  0.0298448,   1.47231927e+08)>
     
    (d) transformed to HGS <HeliographicStonyhurst Coordinate (obstime=2017-03-08 01:13:46.667000): (lon, lat, radius) in (deg, deg, km)
    ( 359.61046809, -7.22039924,   1.47231927e+08)>
     
    (e) back to heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=2017-03-08 01:13:46.667000, obstime=2017-03-08 01:13:46.667000): (lon, lat, distance) in (deg, deg, km)
    ( 167.27727131,  0.0298448,   1.47231927e+08)>
 
```
without the equinox keyword set

```
 EIT 195 image time 2017-03-08 01:13:46.667000
 
[0] Coordinate Round trip
    (a) original Cartesian ( -1.43616960e+08,  32425350.,  76691.63) km
     
    (b) distance 147231927.25720266 km
     
    (c) heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=J2000.000, obstime=2017-03-08 01:13:46.667000): (lon, lat, distance) in (deg, deg, km)
    ( 167.27727131,  0.0298448,   1.47231927e+08)>
     
    (d) transformed to HGS <HeliographicStonyhurst Coordinate (obstime=2017-03-08 01:13:46.667000): (lon, lat, radius) in (deg, deg, km)
    ( 359.85240104, -7.21935342,   1.47231927e+08)>
     
    (e) back to heliocentric true ecliptic <HeliocentricTrueEcliptic Coordinate (equinox=J2000.000, obstime=2017-03-08 01:13:46.667000): (lon, lat, distance) in (deg, deg, km)
    ( 167.27727131,  0.0298448,   1.47231927e+08)>

```

**Comment by MSKirk** [comment]
The distance did not change (good), but the [Lon,Lat] changed in HGS depending on the equinox date set in HCTE. This is what we expected, right?

**Comment by wafels** [comment]
Looking at just the values in lon with and without the equinox correction you get 359.61046809 - 359.85240104 = -0.24191284, and divide by 17 (17 years since the year 2000) you get -0.014230167 degrees/year, which is close to the value you said.  So at least the correction due to equinox precession seems right.

**Comment by wafels** [comment]
We need to know a value to a HeliocentricTrueEcliptic Coordinate its corresponding HeliographicStonyhurst Coordinate value to test the transformation for a fknown time.  These values should be obtained independently of sunpy/astropy and SSWIDL.

**Comment by ayshih** [comment]
Now that I understand Astropy's transformation stack better, the back and forth that I suggested before isn't actually needed.  HTE->HGS has to go through ICRS anyway, so the equinox precession will be computed correctly.  (I confused myself by testing HTE->HTE.)

@wafels Can you provide what SunSPICE says the HGS coordinates are for the examples you gave above?

**Comment by wafels** [comment]
OK:

```
2017-03-08 01:13:46.667000
SunSPICE SOHO Heliocentric Aries Ecliptic coordinates   -1.4361853e+08       32418846.       76685.075
Distance from Sun =    1.4723202e+08
Longitude =      -0.14497297
Latitude =       -7.2193390
```

**Comment by ayshih** [comment]
> We need to know a value to a HeliocentricTrueEcliptic Coordinate its corresponding HeliographicStonyhurst Coordinate value to test the transformation for a fknown time. These values should be obtained independently of sunpy/astropy and SSWIDL.

Woo hoo, I have just confirmed that the SunPy/Astropy conversion from HGS to heliocentric ecliptic agrees with tabulated values in the Astronomical Almanac to within a few arcseconds, with the remaining discrepancy perhaps attributable to the true/mean equinox difference.

Now to look into SunPy/Astropy versus SunSPICE...

**Comment by ayshih** [comment]
@wafels SunPy/Astropy appears to match the SunSPICE values to the ~1e-5 level (hundredths of arcsec).

```python
>>> from astropy.coordinates import CartesianRepresentation, SkyCoord, HeliocentricTrueEcliptic
>>> import astropy.units as u
>>> from sunpy.coordinates import HeliographicStonyhurst

>>> vector = CartesianRepresentation(-1.4361853e8, 32418846, 76685.075)*u.km
>>> soho = SkyCoord(vector, frame=HeliocentricTrueEcliptic, obstime='2017-03-08 01:13:46.667')

>>> soho
<SkyCoord (HeliocentricTrueEcliptic: equinox=J2000.000, obstime=2017-03-08 01:13:46.667): (lon, lat, distance) in (deg, deg, km)
    ( 167.27987478,  0.02984223,   1.47232026e+08)>
>>> soho.transform_to(HeliographicStonyhurst)
<SkyCoord (HeliographicStonyhurst: obstime=2017-03-08 01:13:46.667): (lon, lat, radius) in (deg, deg, km)
    (-0.14497469, -7.21934724,   1.47232026e+08)>
```

**Comment by ayshih** [comment]
Note that I have to specify that the HTE coordinates are in J2000.0 to get the right answer.  This indicates that SunSPICE thinks you are specifying HAE coordinatse in J2000.0.  Whether EIT's HEC coordinates are in J2000.0 or in `date_obs` equinox` is for someone else to answer.

**Comment by wafels** [comment]
Ok, because of the comment above _Woo hoo, I have just confirmed that the SunPy/Astropy conversion from HGS to heliocentric ecliptic agrees with tabulated values in the Astronomical Almanac to within a few arcseconds, with the remaining discrepancy perhaps attributable to the true/mean equinox difference._ - we should probably close this issue since this comment is pertinent to the title of the issue.  The remaining discussion regarding EIT coordinates will occur at #2430.
