### ISSUE TITLE
Refactoring maps by removing waveunit keyword which seems to have no use currently

### ISSUE THREAD

**Issue by getsanjeev** [sunpy/sunpy#2450]
As discussed with #2427 the 'waveunit' keyword should also be removed from the header for GenericMap does not require this.

**Comment by getsanjeev** [comment]
@wtbarnes My apologies for what I am asking looks trivial. Can you please elaborate on it?
In previous issue we were setting 'wavelnth' to nan (which made it useless) & was actually causing a bug so its okay to remove it. Also missing 'wavelnth' is handled through defaults.
Now in any map (derived form genericmap) when we set waveunit to something and call _measurement or _wavelength methods, we should be able to get wavelnth as default value (for we havent set it) but should be able to get waveunit (for I have set it).

**Comment by getsanjeev** [comment]
I had initially thought that as 'wavelnth' has been removed, there is no physical significance of 'wave unit' so should be removed. Am I correct?

**Comment by Cadair** [comment]
I thought the point of this issue is that we shouldn't be injecting waveunit in the header where we are not injecting wavelength. As if it's missing it will fall back to the default in [`measurement`](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L457).

**Comment by getsanjeev** [comment]
#2456 resolves this.

**Comment by getsanjeev** [comment]
@wtbarnes I would fix it today just when my classes are over.
