### ISSUE TITLE
timeseries/sources/rhessi peek function does not change title on passing title as keyword argument, doesn't return figure

### ISSUE THREAD

**Issue by talsperre** [sunpy/sunpy#2471]
Despite passing the title as keyword argument to the peek function, the plot always has the same title. The [docs](http://docs.sunpy.org/en/stable/api/sunpy.timeseries.RHESSISummaryTimeSeries.html#sunpy.timeseries.RHESSISummaryTimeSeries)  mention that it does have a title parameter.  Also, does not return figure as mentioned by docs.
Test Code:
```
import sunpy.data.sample
import sunpy.timeseries
rhessi = sunpy.timeseries.TimeSeries(sunpy.data.sample.RHESSI_TIMESERIES, source='RHESSI')
rhessi.peek(title="New Plot")
```

Output: Plot with title "RHESSI Observing Summary Count Rates"
Soln: Maybe call ```set_title``` in peek function

**Comment by nabobalis** [comment]
Fixed by #2477
