### ISSUE TITLE
Create pytest sample-data flag

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#2472]
Currently there a number of tests within SunPy that require the sample data to be downloaded. This is a problem since these are not marked as online tests and thus any build or packager requires an online connection which is not the case normally. This will cause the tests to fail.

What we need is to create a pytest flag (similar to how `# doctest: +SKIP +REMOTE_DATA` exist) that is called SAMPLE_DATA.

Its purpose is to first check if the sample-data is present, if so, run the test. If not, check if the internet is available and if so, download the data but if there is no internet, to skip the test without failing. 

Should be at least these tests that need marking. 

```
sunpy/coordinates/utils.py:74
sunpy/database/tables.py:642
sunpy/instr/lyra.py:111
sunpy/map/compositemap.py:68
sunpy/map/map_factory.py:57
sunpy/map/mapbase.py:103
sunpy/map/mapbase.py:1207
sunpy/physics/solar_rotation.py:118
sunpy/timeseries/timeseries_factory.py:64
sunpy/timeseries/sources/eve.py:49
sunpy/timeseries/sources/goes.py:40
sunpy/timeseries/sources/lyra.py:51
sunpy/timeseries/sources/noaa.py:41
sunpy/timeseries/sources/noaa.py:194
sunpy/timeseries/sources/norh.py:45
sunpy/timeseries/sources/rhessi.py:50
```

Also, changing the CI to make sure we offline-test without the sample data. 

I had a quick chat with @drdavella about this. It would require some reasonably significant changes to pytest-doctestplus.

**Comment by nabobalis** [comment]
So what seems to have happened is that the `sample data` has not downloaded when the doctests were run.

It normally downloads when the import is called but it seems to be ignored when called via the doctest. I wonder if that is a bug.

**Comment by olebole** [comment]
The tests in Debian run disconnected; therefore no download may happen in our test environment.

**Comment by nabobalis** [comment]
Then we need to mark those sample tests as remote-data then and that is a bug. 
I would probably just skip those doctests then. 

Having just run the tests without the sample data locally gives me 16 fails.
I need to make sure we do a real offline test for our CI.

Sorry about this!

**Comment by olebole** [comment]
Marking them as remote-data is  the best solution, agreed. Thank you for investigating this!

**Comment by Cadair** [comment]
I think marking them as remote data is a good stop gap. I think we should probably have a sperate mark for sample data as you only need the remote data for the initial download not the actual test run.

**Comment by Cadair** [comment]
I had a quick chat with @drdavella about this. It would require some reasonably significant changes to pytest-doctestplus.

**Comment by Cadair** [comment]
@olebole your initial issue here is now fixed, as we have marked all the SunPy sample data doctests as remote_data.

We should keep this issue open to let them have a separate mark.

**Comment by dstansby** [comment]
I think the action here is now just to create a new mark and apply it to the relevant test functions, which shouldn't be too hard.

**Comment by nabobalis** [comment]
Looking back at this, do we gain anything from adding a new sample_data mark instead of just having a remote data flag for the sample_data doctests?

**Comment by olebole** [comment]
For me, using `REMOTE_DATA` is OK, as it implemented now.
