### ISSUE TITLE
Replace astropy-helpers with sphinx-astropy

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2489]
Currently we use the astropy-helpers submodule to build our documentation.
Recently astropy created a sphinx package called [`sphinx-astropy`](https://github.com/astropy/sphinx-astropy) to do this job instead. 

We would need at least (and off the top of my head) the `docs/conf.py` to be changed, the requirements.txt file updated, the read the docs yaml file and the travis and appveyor CI files updated.  
 
If you are stuck, you can see the work-in-progress pull request for astropy [here](https://github.com/astropy/astropy/pull/7139).

**Comment by yashkgp** [comment]
Hey @nabobalis, I am working on it .

**Comment by nabobalis** [comment]
Closed by #2494
