### ISSUE TITLE
Handling invalid user input in ROI

### ISSUE THREAD

**Issue by prateekiiest** [sunpy/sunpy#2498]
This issue pertains to the code present under sunpy/roi/roi.py.

https://github.com/sunpy/sunpy/issues/164
https://github.com/sunpy/sunpy/pull/655

The ROI object has provision for taking user inputs in the form of start,end time , description and source.
Since we are using `parse_time` to take input for start time and end time, so for any invalid time string from user side, an exception will be raised.

`result = roi(times=['2011-02-15 04:34:09','2011-02-15 04:48:21'], description='UV occult.',source='LYRA LYTAF')
`

But if any invalid, source or description is passed, no such exception will be raised, and a new ROI object will be created with the invalid ones. This is not expected.

Hence as a solution some registry of  valid source and description names may be implemented and let the user input be checked with the names in the registry before passing into the function.

The ROI is still in its initial stage and it can be a simple enhancement to the current working of ROI.

**Comment by nabobalis** [comment]
As ROI has been deprecated and slated for removal, I will be closing this.
