### ISSUE TITLE
Add support for search attribute value discovery

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2500]
This feature would allow users to get a list of all the possible values for search attributes like `a.Instrument` or `a.Source`.

It would be nice if you could also find out extra information about certain values, for example finding the times of operation of "AIA" or the pass bands available.

This feature needs some careful planning and interface design.

**Comment by abhijeetmanhas** [comment]
@nabobalis is this issue partly resolved by attrs registration #3637 ?
We can get all possible values an attribute can take for a client, by printing that client.

**Comment by nabobalis** [comment]
Yes.
