### ISSUE TITLE
SunPy colormaps - in reverse!

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2510]
How about using

_https://stackoverflow.com/questions/3279560/invert-colormap-in-matplotlib_

to create reverse versions of the SunPy colormaps?  Users sometime use reverse colormaps to better see features in the data.

**Comment by dstansby** [comment]
There's functionality to do this baked into Matplotlib: https://matplotlib.org/api/_as_gen/matplotlib.colors.ListedColormap.html?highlight=reverse#matplotlib.colors.ListedColormap.reversed

**Comment by wafels** [comment]
Thanks @dstansby !  I didn't know about that.  I'll close the issue.
