### ISSUE TITLE
Add a method to quickly visualize HEK query results

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#253]
It would be useful to be able to call something like "hek_result.show()" to display a Grid of the sun with the HEK events overlaid on it.

**Comment by wafels** [comment]
Now that there is the rot_hpc function in sunpy, it should be easy to rotate the event to the map time.  Perhaps a better API is required so that it is easy to plot and animate the HEK results as necessary.

**Comment by wafels** [comment]
This is now in the sunpy docs.
