### ISSUE TITLE
Provide a simple mechanism to overlay HEK results on a SunPy plot

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#254]
For example, suppose you have some HEK query result "hek_result", it would be nice to be able to do something like:

```
aia = sunpy.make_map(sunpy.AIA_171_IMAGE)
aia.show(overlays=[hek_result])
```

or

```
events = hek_result.to_overlays()
aia.show(overlays=events)
```

**Comment by wafels** [comment]
This is in sunpy docs.

**Comment by Cadair** [comment]
I think other improvements in the returns from HEK would improve this more than this API. For instance if HEK returned skycoords it would be a simple `ax.plot_coord` in a for loop.
