### ISSUE TITLE
PlotInteractor from PySST

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2554]
In the now defunct PySST package is an extension of the ImageAnimator class called [PlotInteractor](https://github.com/nabobalis/PySST/blob/master/pysst/visualisation/cube_explorer.py) that enables some basic analysis or viewing of 4D or 5D cubes.

Question is, do we want to move it here in some form?

**Comment by Cadair** [comment]
ping @DanRyanIrish

**Comment by Cadair** [comment]
:+1: on moving it into `sunpy.visualization`

**Comment by DanRyanIrish** [comment]
Sure.  Looks like it might be useful for IRIS!

**Comment by nabobalis** [comment]
Note it has no support for WCS. It might be alot of effort to port/move.

**Comment by dstansby** [comment]
I'm going to close this, as it is probably in scope of NDCube and not SunPy
