### ISSUE TITLE
Adding `python setup.py test --figure-only`

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2556]
We have several flags that can be passed into `python setup.py test` to trigger tests.
There are several tests that create figures and we would like to be able to run just those instead of the entire test suite. 

This is a guess:
It would require the combination of adding support for the flag (`--figure-only`) within this [file.](https://github.com/sunpy/sunpy/blob/master/sunpy/tests/__init__.py)

Also figuring out the correct combination to pass to pytest in order to just run the figure tests. This could be made setting flags [here](https://github.com/sunpy/sunpy/blob/master/sunpy/tests/setup_command.py) or something much more complicated.

**Comment by himanshukgp** [comment]
I'll take up this issue.

**Comment by Cadair** [comment]
@himanshukgp as @nabobalis said, you first need to make it work in `sunpy.self_test` and then worry about the setup command.

**Comment by ayshih** [comment]
> Also figuring out the correct combination to pass to pytest in order to just run the figure tests. This could be made setting flags here or something much more complicated.

Wouldn't this just be passing in the option `-kfigure` (or `-mfigure`)?

**Comment by ayshih** [comment]
Incidentally, I ask that the existing option (`--figure`) to be renamed to something like `--include-figure` because it's always seemed odd to me that `--figure` did more than only the figure tests.

**Comment by Cadair** [comment]
> Wouldn't this just be passing in the option -kfigure (or -mfigure)?

Yes although the modifications required to the test runner to do this are not completely trivial. There is however an exact analogue in the way we handle online tests.
