### ISSUE TITLE
Create a Map Differential Rotation example 

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2565]
[This feels like this issue should already be open]

Using @dpshelio's example he made for this diffrot PR:
https://gist.github.com/dpshelio/43b301ff7418f569adadda495c3487a7

Creating examples is more than just copy and pasting code, you need to have some understanding of that the code is doing.

It is important to explain the reason behind the example, any parts of the code that are confusing for first time readers and explaining the outcome from each code snippet.

**Comment by nabobalis** [comment]
diffrot_map was removed(?), we also now have several examples with reproject.

**Comment by ayshih** [comment]
`sunpy.physics.differential_rotation.differential_rotate()` – which still exists – is how to differentially rotate a map without using `RotatedSunFrame`.  The example (https://docs.sunpy.org/en/stable/generated/gallery/differential_rotation/reprojected_map.html) does not use `differential_rotate()`.  The two approaches now give the same answer (see #3931), but there is arguably still value in creating an example that uses `differential_rotate()`.

**Comment by wtbarnes** [comment]
`differential_rotate` should be refactored first (see #5292) before we add an example.

**Comment by wtbarnes** [comment]
Closing as this now exists: https://docs.sunpy.org/en/stable/generated/gallery/differential_rotation/reprojected_map.html#sphx-glr-generated-gallery-differential-rotation-reprojected-map-py.
