### ISSUE TITLE
Improve documentation in GenericMap.rotate for NaN handling with default order kwarg

### ISSUE THREAD

**Issue by ghost** [sunpy/sunpy#2571]
```python
file_name = file-name-date.fits   # magnetogram file for 02-04-2018.
smap_orig = sunpy.map.Map(file_name)

smap = smap_orig.rotate(angle = ang1 * u.deg)
smap.draw_grid(grid_spacing=10* u.deg,missing=0.0)
smap.draw_limb()
plt.show()
```

I was trying to plot a Magnetogram for 02-Apr-2018. The Image is rotated by about 26'. after applying the map.rotate function, the missing values are replaced by 0.0. Is there any way of dealing with this issue! 
![figure_1](https://user-images.githubusercontent.com/31451151/38194040-d007cff0-3692-11e8-8abe-b505edc8722f.png)

**Comment by Cadair** [comment]
I *think* the best thing to do is to set the `order=3` keyword argument.

**Comment by Cadair** [comment]
I just tested this and setting the `order=3` keyword argument does indeed stop the `NaN` being replaced by 0. I will edit this to be a documentation issue to make this clearer.

@ehsteve @ayshih grumble grumble `order=4` as the default grumble grumble.

**Comment by wafels** [comment]
Use masks?

**Comment by Cadair** [comment]
@wafels would you not have to rotate the mask as well? which doubles the compute time, and you might get some weird non-binary numbers out of the end. What even happens to masks on map if you do a `.rotate()`?

**Comment by wtbarnes** [comment]
Given that the default order for `rotate` is 3 *and* the default fill value is now `NaN`, I'm going to close this. Feel free to reopen if anyone feels this is still an issue.

**Comment by ayshih** [comment]
Heh, good call!
