### ISSUE TITLE
aiaprep is throwing a submap warning.

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2578]
The function aiaprep working on full disk images is throwing a submap warning.

> /home/ireland/anaconda3/lib/python3.6/site-packages/sunpy-0.9.dev9495-py3.6-linux-x86_64.egg/sunpy/map/mapbase.py:1290: Warning: GenericMap.submap now takes pixel values as `bottom_left` and `top_right` not `range_a` and `range_b`
>   " and `top_right` not `range_a` and `range_b`", Warning)
> 

I don't think it should be throwing this warning even although it appears that the code is working as intended.  It may be a case of bad instance checking in submap, or poorly specified co-ordinates in aiaprep.

**Comment by sapnamish** [comment]
i want to work on this issue

**Comment by nabobalis** [comment]
@sapnamish Go ahead!

**Comment by jairideout** [comment]
Alternatively, `aiaprep` could filter/ignore the `Warning` issued by `GenericMap.submap`, but that might silence other warnings in `submap` that actually need attention. Does anyone have thoughts on how to move forward with this issue?

**Comment by nabobalis** [comment]
Shouldn't that warning just be removed on master?

**Comment by jairideout** [comment]
👍, I'll submit a PR to remove the warning.

**Comment by jairideout** [comment]
Here's a small PR to fix this issue: https://github.com/sunpy/sunpy/pull/2833
