### ISSUE TITLE
Appveyor Python 2.7 Disabled

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2579]
We have a problem with Python 2.7 builds under Windows.

Looking at the log [here](https://ci.appveyor.com/project/nabobalis/sunpy/build/1.0.316/job/ux88alp5lp9i6x6w#L1545). It seems that for some reason under Windows and Python 2.7, the sample data download is being tried. This does not happen under Linux with Python 2.7.

Why? Not a clue.

**Comment by Cadair** [comment]
We should really fix this for the 0.9 release cycle.
