### ISSUE TITLE
Importing sunpy.coordinates.frames requires pytest to be installed

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2580]
`sunpy.coordinates.frames` has the line `from astropy.tests.helper import quantity_allclose`. This import fails if `pytest` isn't installed. It would be good to replace this with something else, so using coordinate frames doesn't require an installation of pytest.

**Comment by Cadair** [comment]
see astropy/astropy#7235

**Comment by nabobalis** [comment]
This has been fixed.
