### ISSUE TITLE
Clarify ImageAnimator Axes Input API and Plotting Conventions

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#2581]
Currently ```ImageAnimator``` supports of number of APIs for defining its axes' coordinate values, for both image axes and slider axes, via the ```axis_ranges``` kwarg.  These include:
* None
* Min, Max pair
* list/array of same length as axis giving value of each pixel.
In certain cases -- e.g. when the axis length is two, or whether the axis is an image or slider axis -- these different APIs can lead to conflicting and unintuitive behaviour.  Therefore, the supported APIs and consequent plotting behaviour should re-examined and defined.

Before we can do this however, we must first agree on a convention of where in the pixel the coordinate values along the image axes should be located:
* In the middle of the pixel?
* At the lower edge of the pixel?

This should be informed by the convention employed by ```WCSAxes```.  Once this is agreed, we can clarify the API of the ```axis_ranges```.  In the case of the pixel values array API, I see two options:
* Array denotes pixel values and so must be of same length as the number of pixels along the axis.
* Array denotes pixel edges and so must be of length 1 longer than the number of pixels in the axes.

When applied to image axes, the former API is viable if the pixel coordinates are plotted in the middle of the pixel.  However, it becomes ambiguous if the pixel coordinates are plotted at the lower edge of the pixels.  What should the value of the extreme upper edge of the axis be?  An assumption must be made to derive it.  On the other hand, the latter API can lead to unambiguous result in either case.  The pixel coordinate values used in setting the axis data are determined by taking the midpoint between each pair of pixel edge values.

When applied to slider axes, both APIs can lead to unambiguous results.  In the former case, the values supplied before the slider pixel values.  In the latter, if pixel coordinate values are located in the middle of the pixel, the midpoint between each pair of pixel edge values become the slider pixel values.  Whereas if the pixel coordinate values are plotted on the pixel's lower edge the ```pixel_edges[:-1]``` become the slider pixel values.

Next, let us examine the min, max pair API.  In the case of image axes, the min, max pair must be used to set the extent of the image and so must effectively represent the lower edge of the first pixel and the upper edge of last pixel.  In the case of slider axes, if pixel coordinate values are plotted at the lower edge of a pixel, the slider pixel values can be given by ```np.linspace(min, max, len_axis-1)[:-1]``` in order to maintain a consistent meaning of the min and max.  If however, the pixel values are plotted in the middle of pixel, there is no trivial way of calculating the correct pixel coordinate values without changing the meaning of the min, max pair relative to the image axis case.

If these two APIs (pixel value arrays and min, max pairs) are to be maintained, I suggest redefining the pixel value array API to represent the pixel edges, so that a consistent behaviour is maintained whether the axis is an image or slider axis.  It also has the advantage of not causing an ambiguity when the axis length is 2.  In the old APIs, does the user mean a min, max pair, or an array of pixel values.  In the new API, the ambiguous case occurs when the axes length is 1.  But here, the pixel edge array and min, max pair APIs are equivalent.  So there is in fact no ambiguity.  This new API can be introduced by introducing a new kwarg, say ```axis_edges``` to replace ```axis_ranges``` and ```DeprecationWarning``` raised in ```axis_ranges``` is detected in the ```**kwargs```.

**Comment by DanRyanIrish** [comment]
ping @Cadair @nabobalis

**Comment by nabobalis** [comment]
Don't look at me. This is too technical for the janitor of Sunpy to handle. @cadair, stop reading that book and check your notifications.

**Comment by DanRyanIrish** [comment]
😆

**Comment by prateekiiest** [comment]
Will this involve the current changes in the `ImageAnimatorWCS` also?

**Comment by prateekiiest** [comment]
It uses it here https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/imageanimator.py#L1027

**Comment by prateekiiest** [comment]
Ok, I will be diving deep into that and will let you know about it

**Comment by Cadair** [comment]
The one comment I have at the moment is that I don't think it matters to WCSAxes what axes ranges are. I think it just uses the pixel size of the array.

**Comment by prateekiiest** [comment]
Going by this 

```
cube = smap.Map(AIA_171_IMAGE, AIA_193_IMAGE,cube=True)
cube = cube.as_array()
# So the last two axes are the image
# The shape is (10, 4096, 4096
cube = np.rollaxis(cube,-1)

wcs_input_dict = {
'CTYPE1': 'Time    ', 'CUNIT1': 's', 'CDELT1': 12,
'CTYPE2': 'HPLN-TAN', 'CUNIT2': 'arcsec', 'CDELT2': 0.6, 
'CTYPE3': 'HPLT-TAN', 'CUNIT3': 'arcsec', 'CDELT3': 0.6}

WCS = astropy.wcs.WCS(wcs_input_dict)

s = ImageAnimatorWCS(cube, wcs=WCS, vmax=1000)
```

if `axis_ranges = None`

I get this 
`s.axis_ranges` = `[array([0., 2.]), [0, 1024], [0, 1024]]`

**Comment by prateekiiest** [comment]
The corresponding plot
![old](https://user-images.githubusercontent.com/16035442/38508109-e41a7962-3c3b-11e8-9d29-2d41599724c4.png)

**Comment by Cadair** [comment]
@prateekiiest your numbering in the header is reversed from the correct order. The headers are in reverse order to the numpy array (so CTYPE1 is the last dimension).

**Comment by prateekiiest** [comment]
But the ordering in WCS remains the same

```
WCS Keywords

Number of WCS axes: 3
CTYPE : 'Time'  'HPLN-TAN'  'HPLT-TAN'  
CRVAL : 0.0  0.0  0.0  
CRPIX : 0.0  0.0  0.0  
PC1_1 PC1_2 PC1_3  : 1.0  0.0  0.0  
PC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0  
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0  
CDELT : 12.0  0.00016666666666666666  0.00016666666666666666  
NAXIS : 0  0
```

**Comment by DanRyanIrish** [comment]
Regarding @Cadair's comment about ```WCSAxes``` not caring about the ```axis_ranges```, I think that's the case too.  If so, we shouldn't need to change ```ImageAnimatorWCS``` due to this proposed API change.  But if this is true, we should probably remove the ```axis_ranges``` kwarg from the ```ImageAnimatorWCS``` API if it is not used.

Another question, what is ```WCSAxes```'s convention for plotting the tickmarks of a pixel coordinate?  If pixel 10 has a value of 10 arcsec, does the 10 arcsec tick go in the middle of pixel 10 or at the lower edge?

**Comment by DanRyanIrish** [comment]
*Decision from weekly meeting* (11 April 2018): Let's go with pixel edge API.
*Still to determine*: whether pixel labelling convention in ```WCSAxes``` is center or lower edge convention.

**Comment by DanRyanIrish** [comment]
As part of this refactor, Issue #2567

**Comment by DanRyanIrish** [comment]
@Cadair.  An idea for this Animator API.  Currently it's agreed that going forward the ```axis_ranges``` will provide the pixel edges along each axis (or ```None``` if the user does not want to define them themselves.  This has a numbers of advantages regarding generalisation and non-ambiguity as outlined above.  However, if a user prefers to supply the pixel centres -- as will often be the case, especially with ```LineAnimator``` -- what about an ```assume_pixel_edges_from_centers``` bool kwarg which makes the ```axis_ranges``` be converted (with a couple assumptions) to pixel_edges.  Then if users want to be explicit they can supply their own pixel_edges with this kwarf set to ```False```.  ```False``` can be the default.

The API isn't exceedingly pretty but I could see it being very useful.

**Comment by Cadair** [comment]
@DanRyanIrish is this closed by #2867 ?

**Comment by Cadair** [comment]
and / or the array animator refactor?

**Comment by kakirastern** [comment]
@Cadair Yeah, I think #2867 fixes this issue, but @DanRyanIrish used the wording "address" instead...
