### ISSUE TITLE
User warning when creating and instance of helio hec client

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#2588]
Get the following warning when creating a instance of the client, code works as expected just ugly warning and possibly worse performance.

    from sunpy.net.helio import hec
    hc = hec.HECClient()
    /Users/shane/.virtualenvs/gen/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

Fix make parser explicit since I think lxml is already a sunpy dependency use it or python's builtin

This [line](https://github.com/sunpy/sunpy/blob/master/sunpy/net/helio/parser.py#L107)

    soup = BeautifulSoup(endpoint_page)
could be change to

    soup = BeautifulSoup(endpoint_page, 'lxml')
or

    soup = BeautifulSoup(endpoint_page, 'html.parser')

**Comment by samaloney** [comment]
Seem's that even though lxml is used [here](https://github.com/sunpy/sunpy/blob/master/sunpy/util/scraper.py) is not part of the dependencies in either setup.py or in any of the requirement files?

**Comment by Cadair** [comment]
Yeah I don't really want to pick up a lxml dep just for this if we can avoid it.

**Comment by samaloney** [comment]
So would you think leave as is or change to `BeautifulSoup(endpoint_page, 'html.parser')`?

**Comment by vn-ki** [comment]
This
https://github.com/sunpy/sunpy/blob/ae70bda1893f7129605d5dfc3357ba4281f3adbe/sunpy/util/scraper.py#L228
was added in https://github.com/sunpy/sunpy/commit/6675309a5b471991a1b24ccf745d168dd6265682 for fixing #1619. So maybe we do need `lxml`.
