### ISSUE TITLE
Add a "What's new in 0.9?" page in the docs

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2591]
Please send me what you think I should highlight for 0.9.

**Comment by wafels** [comment]
See https://github.com/wafels/sunpy/blob/whatsnewin09/docs/whatsnew/0.9.rst for a start to this.  More edits to come.

**Comment by Cadair** [comment]
For clarity:

Python 2 will not be maintained *after* 2019, Guido has said it dies on 2020-01-01 00:00.
