### ISSUE TITLE
Support for differential derotation in mapcubes

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2596]
At the moment, `mapcube_solar_derotate` assumes that the patch of Sun you are are derotating is "small" enough that differential derotation of each map in the mapcube need not be used.  In this case "small" means a small spatial extent and for small durations.  However, this is not always the case.

Therefore either the existing `mapcube_solar_derotate` should be expanded to optionally use differential derotation or a new function `mapcube_solar_differential_derotate` should be created to apply differential derotation to each map in the mapcube.

**Comment by wafels** [comment]
See also #2864.

**Comment by wtbarnes** [comment]
Given that `mapsequence_solar_derotate` has now been deprecated and removed (see #6433), I'm going to close this. As this code now lives in `sunkit-image`, any related issues should be opened there.
