### ISSUE TITLE
The name `MapCube` is misleading

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#2602]
Based on the discussion coming out of the Riot chat room (https://matrix.to/#/!MeRdFpEonLoCwhoHeT:matrix.org/$15248435701356875aoRtJ:matrix.org), the name `MapCube` does not describe the data structure that actually created. MapCube is not a cube, it is an ordered list of maps.

A name change will give us room in the namespace in the future to develop an actual `MapCube` object based on `NDCube.` We could also then have a `MapCubeSequence` object based on `NDCubeSequence.`

All the while we can preserve the existence of the current `MapCube` class under the new name of `MapSequence.` If the `NDCube` and `NDCubeSequence` objects become successful and the great parts of the `MapSequence` API have been adopted in, we can eventually stop supporting `MapSequence.`

We could have `MapSequence` literally be a copy of current `MapCube` and then add a DeprecationWarning to `MapCube.` By the time we will have developed an NDCube-based Map object, we can have removed current `MapCube` altogether in favor of `MapSequence.`

**Comment by DanRyanIrish** [comment]
Here is the open SEP advocating this exact name change: https://github.com/sunpy/sunpy-SEP/pull/21

It also proposes renaming ```CompositeMap``` to ```MapCollection``` which I'm happy with.

**Comment by wafels** [comment]
Note that a `CompositeMap` is ordered. You need an order to get the plotting transparency and layering correct - a z-order.  In general this type of ordering is not a physical ordering, but one that is required for plotting only.  So by the definition in the SEP, the existing `CompositeMap` is a `MapSequence` not a `MapCollection`.  Should `Sequence` imply an ordering based on a physical quantity?

**Comment by nabobalis** [comment]
We renamed MapCube, so is it safe to close this?
