### ISSUE TITLE
Make tseries['colname'] return column data with units?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2605]
Currently, in order to use the units part of `TimeSeries` I think you have to do
```python
with_units = tseries.data['colname'].values * tseries.units['colname']
```

It would be nice if instead a `__getitem__` method could be implemented, so that
```python
with_units = tseries['colname']
```
automatically returns the data with units attached. Is this a good idea? Would implementing it be welcomed? If so, it would definitely fall within the scope of the GSOC project I'm running over at HelioPy.

See https://docs.python.org/3.6/reference/datamodel.html#object.__getitem__ for information on `__getitem__`

**Comment by Cadair** [comment]
Seems like a good idea to me. :+1:

**Comment by dstansby** [comment]
Great! I plan on getting HelioPy's GSOC student to work on this.

**Comment by dstansby** [comment]
I'm going to close this since development is ongoing up in astropy for a `TimeSeries` object.
