### ISSUE TITLE
edit on github button does not work

### ISSUE THREAD

**Issue by Punyaslok** [sunpy/sunpy#2612]
In the api/code reference section, the **edit on github** button points to a broken link.

For example, go to [http://docs.sunpy.org/en/stable/api/sunpy.net.dataretriever.QueryResponseBlock.html#sunpy.net.dataretriever.QueryResponseBlock](http://docs.sunpy.org/en/stable/api/sunpy.net.dataretriever.QueryResponseBlock.html#sunpy.net.dataretriever.QueryResponseBlock) and click on **edit on github**

**Comment by Cadair** [comment]
This is hopefully fixed, but we will need to wait till 0.9.1 to know for sure.

**Comment by Cadair** [comment]
It was not fixed.

**Comment by StegSchreck** [comment]
I would like to have a look on this. Can you point me to the line where the link is generated?

**Comment by nabobalis** [comment]
@StegSchreck As far as I am aware it is here: https://github.com/sunpy/sunpy/blob/master/docs/conf.py#L209

**Comment by nabobalis** [comment]
The problem seems to be that the link created is: `https://github.com/sunpy/sunpy/tree/v0.9.x/sunpy/net/dataretriever/client.py#L46` but it should be `https://github.com/sunpy/sunpy/blob/0.9/sunpy/net/dataretriever/client.py#L46`

**Comment by nabobalis** [comment]
Should be noted that master works. It justs the released version.

**Comment by StegSchreck** [comment]
I already figured out, that the issue is about the version number. I also noticed, that `.../tree/...` will be redirected to `.../blob/...` when it is referencing a single file.

**Comment by StegSchreck** [comment]
Sorry if I ask an obvious question. But the change https://github.com/sunpy/sunpy/commit/28df923383fc05210e9c2a53b3ee9626ace8f0f0 looks actually correct to me. Are you sure it was deployed?
I still don't quite understand where the local version number is retrieved from though. So I can't reproduce it locally.
This shows a different approach for retrieving the version number: https://github.com/sunpy/sunpy/blob/master/docs/conf.py#L135

**Comment by nabobalis** [comment]
It looks like the PR that was first opened to address this wasn't backported.

**Comment by nabobalis** [comment]
I just pushed it to stable and to the 0.9 branch. Hopefully once RTD build we will know if its fixed.

**Comment by nabobalis** [comment]
It works now that I backported #2614.
