### ISSUE TITLE
Migrate to using __init_subclass__ instead of Metaclasses

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2625]
This would require 1.0 being >=3.6 but I don't think that's a problem. See https://www.python.org/dev/peps/pep-0487/#subclass-registration for more info

**Comment by ritiek** [comment]
This can be closed by #2655 if that's all. :smile:

**Comment by Cadair** [comment]
There is one left in `GenericClient` but @nabobalis  is working on it!

**Comment by ritiek** [comment]
Oh, I see.

**Comment by nabobalis** [comment]
IT WILL ARRIVE SOON(TM)
