### ISSUE TITLE
Zoomed HMI continuum image has no axes on plot

### ISSUE THREAD

**Issue by adamsml** [sunpy/sunpy#2633]
I am trying to reproduce the last example on the plotting page (http://docs.sunpy.org/en/stable/guide/plotting.html), using HMI continuum data.  I can reproduce the plot with AIA data.  I found hmilibrary.py that will rotate the data and adjust the plate scale, but there is apparently something missing in the FITS header, because I am getting this apparently wcs-related error:

"File "/run/media/mladams1/solar1/anaconda3/lib/python3.6/site-packages/astropy/wcs/wcs.py", line 2160, in <lambda>
    lambda xy, o: self.wcs.s2p(xy, o)['pixcrd'],
astropy.wcs._wcs.InconsistentAxisTypesError: ERROR 4 in wcss2p() at line 2881 of file cextern/wcslib/C/wcs.c:
ncoord and/or nelem inconsistent with the wcsprm."

![continuum](https://user-images.githubusercontent.com/39315843/40081779-a2c016a4-5854-11e8-8bb8-27ab75f71d3d.png)

[bug001.txt](https://github.com/sunpy/sunpy/files/2006832/bug001.txt)

**Comment by mbobra** [comment]
If you query and correctly pass in the FITS header keywords, it should work. Thanks to @kbg for coming up with that solution :) 

(It is true that `submap.draw_grid()` gave me an error -- it is somehow not getting the correct WCS keys).

```python
import matplotlib.pyplot as plt
from matplotlib import patches
import astropy.units as u
from astropy.coordinates import SkyCoord
import os
import numpy as np
from sunpy.instr.aia import aiaprep
from matplotlib import mlab, cm
import matplotlib.colors as colors
import drms
import sunpy.map
from astropy.io import fits

# Establish a connection to the database
c = drms.Client()

# Define a region of interest
width = (105) * u.arcsec
height = (75) * u.arcsec
x0 = -65 * u.arcsec
y0 = 310 * u.arcsec

# Grab the data
keys_hmi, segments = c.query('hmi.Ic_45s[2016.03.04_03:00:45_TAI]', key=drms.const.all, seg='continuum')
url_hmi = 'http://jsoc.stanford.edu' + segments.continuum[0]   # add the jsoc.stanford.edu suffix to the segment name
photosphere_full_image = fits.getdata(url_hmi)                 # download the data

# Create a header (with WCS keywords)
header_hmi = dict(keys_hmi.iloc[0])
header_hmi['DATE-OBS'] = keys_hmi.DATE__OBS[0] # Add a DATE-OBS keyword which seems to be required by sunpy.map.Map.
header_hmi['HGLN_OBS'] = 0.0                   # Add HGLN_OBS keyword to avoid a warning in sunpy.map.Map.

# Set the color table
hmimag = plt.get_cmap('hinodesotintensity')

# Make the figure
smap = sunpy.map.Map(photosphere_full_image, header_hmi)
fig = plt.figure(figsize=(5,12))

# Add a first Axis, using the WCS from the map.
# (2,1,1) = 2 rows, first column, first image
ax1 = fig.add_subplot(2,1,1, projection=smap)

# Plot the Map on the axes with default settings.
smap.plot()
plt.show()

# Set bottom left and top right (-90,270) and (70,410)
bottom_left = SkyCoord(x0, y0, frame=smap.coordinate_frame)
top_right = SkyCoord(x0 + width, y0 + height, frame=smap.coordinate_frame)
submap = smap.submap(bottom_left, top_right)

# Draw a box on the image
smap.draw_rectangle(bottom_left, width, height, color='black')

# Create a second axis on the plot.
ax2 = fig.add_subplot(2,1,2, projection=submap)
submap.plot()

# Change the title.
ax2.set_title('Zoomed View')

plt.show()
```

**Comment by dstansby** [comment]
I'm going to close this since it's seems to be an issue with the FITS file and not sunpy. Perhaps we could provide a more useful error or warning - if you can provide the file that you're using for the plot, the code being used for the plot, and any warnings/errors thrown when running it feel free to re-open this.
