### ISSUE TITLE
Should we rename TimeSeries.columns to TimeSeries.column_names

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2645]
Currently the `.columns` attribute returns [the names](http://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries.columns) of the columns. Given that astropy table uses columns gives you an iterable like of the column objects.

If we are going to do this, now is the time.

**Comment by ishanisri** [comment]
hi! I would like to contribute to the issue.
 So in this issue, just the `.columns` attribute has to be changed to `.column_names` in TimeSeries?

**Comment by nabobalis** [comment]
We should probably match astropy which use .colnames if I recall.

**Comment by ishanisri** [comment]
Yeah I checked it is `.colnames` in astropy . So I will change that and make a PR?

**Comment by nabobalis** [comment]
Sure. It probably needs to be changed anywhere it is used in text as well.

**Comment by ishanisri** [comment]
The documentation?

**Comment by nabobalis** [comment]
Yeah.

**Comment by nabobalis** [comment]
Probably should be done in one PR?

**Comment by ishanisri** [comment]
No issues. I will make a single PR then

**Comment by ishanisri** [comment]
No issues. I will make a single PR then...But I had something else to ask too, since I forked and cloned this repo, is there a way to check after making changes that this works and does not break at any point before committing it and making a PR?

**Comment by nabobalis** [comment]
Yes, you can run the tests we have locally. 

`python setup.py test` or running `pytest` (with all the dependencies installed.

**Comment by ishanisri** [comment]
I ran the tests using `python setup.py test ` as you mentioned, but I get this error. It does not seem to me due to the changes made in timeseries.

The error is :
`home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/file.py:334: in readarray
    buffer=self._mmap)
E   TypeError: buffer is too small for requested array `

**Comment by nabobalis** [comment]
No that should not error, its just a warning message.

**Comment by ishanisri** [comment]
Yeah so I get the following 2 errors in red when I run the test:
`=================================================================== ERRORS ===================================================================
________________________________________ ERROR collecting sunpy/map/sources/tests/test_xrt_source.py _________________________________________
sunpy/map/sources/tests/test_xrt_source.py:19: in <module>
    xrt = Map(fitspath)
sunpy/map/map_factory.py:279: in __call__
    data_header_pairs, already_maps = self._parse_args(*args, **kwargs)
sunpy/map/map_factory.py:203: in _parse_args
    pairs = self._read_file(path, **kwargs)
sunpy/map/map_factory.py:127: in _read_file
    pairs = read_file(fname, **kwargs)
sunpy/io/file_tools.py:84: in read_file
    return _readers[readername].read(filepath, **kwargs)
sunpy/io/fits.py:86: in read
    pairs.append(HDPair(hdu.data, header))
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/utils/decorators.py:726: in __get__
    val = self.fget(obj)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py:243: in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py:709: in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py:475: in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/file.py:334: in readarray
    buffer=self._mmap)
E   TypeError: buffer is too small for requested array
-------------------------------------------------------------- Captured stderr ---------------------------------------------------------------
WARNING: File may have been truncated: actual file length (49152) is smaller than the expected size (541440) [astropy.io.fits.file]
________________________________________ ERROR collecting sunpy/map/sources/tests/test_xrt_source.py _________________________________________
sunpy/map/sources/tests/test_xrt_source.py:19: in <module>
    xrt = Map(fitspath)
sunpy/map/map_factory.py:279: in __call__
    data_header_pairs, already_maps = self._parse_args(*args, **kwargs)
sunpy/map/map_factory.py:203: in _parse_args
    pairs = self._read_file(path, **kwargs)
sunpy/map/map_factory.py:127: in _read_file
    pairs = read_file(fname, **kwargs)
sunpy/io/file_tools.py:84: in read_file
    return _readers[readername].read(filepath, **kwargs)
sunpy/io/fits.py:86: in read
    pairs.append(HDPair(hdu.data, header))
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/utils/decorators.py:726: in __get__
    val = self.fget(obj)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py:243: in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py:709: in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py:475: in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
/home/ishani/anaconda3/envs/sunpy-dev/lib/python3.7/site-packages/astropy/io/fits/file.py:334: in readarray
    buffer=self._mmap)
E   TypeError: buffer is too small for requested array
`

**Comment by nabobalis** [comment]
So looking at `test_xrt_source.py:19`, (the file needs to be rewritten it seems) the file should output a warning but I do not understand why its causing an error on collection like that. 

At this point, I would open the pull request and we can discuss more there.

**Comment by Cadair** [comment]
We are going to punt this for a few months until we have a better idea about the Timeseries API in astropy and if that is the API we wish to be closest to.

**Comment by dstansby** [comment]
Any more thoughts? We could at least add a `column_names` property alongside `columns` for now?

**Comment by kakirastern** [comment]
Just doing a bit of triaging: Any follow up on this discussion? Could be a good `Hacktoberfest` issue if a decision can be made by then.

**Comment by dstansby** [comment]
I don't think there has been much discussion about this, and I don't think we'll be moving from storing the data as a `DataFrame` underneath for at least while, so I don't think this is urgent? I'm tempted to close this since I think we really need some higher level planning for `TimeSeries` to happen before we change anything.
