### ISSUE TITLE
Add STEREO/SWAVES Functionality

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#266]
This task needs to be done before October in order for it to be presented at a demo at the Solar Probe Science Meeting. Adding this functionality is likely in three parts,
- Adding the downloader (TMLib)
- Adding processing to turn the raw data to radio spectragrams (TDAS)
- Add functionality to the GUI and command line to analyze this data (e.g. tplot/TDAS)

The downloader has already been developed for many platforms (though not in python) and can be found here
- for Mac:  https://www.dropbox.com/s/o8ivrcm2xa5v303/TMlib_Client-1.7.3350.pkg.zip
- for Linux:  https://www.dropbox.com/s/bcru63ckexaqs88/TMlib_Client-1.6.2906-1.i386.rpm https://www.dropbox.com/s/xp4i5hr6qcb7mbr/README.linux.txt
- some documentation:  https://www.dropbox.com/s/l8s8twn0akxtjlo/TMlib_User_Guide.pdf

The IDL version of TDAS can be found on this [webpage](http://themis.ssl.berkeley.edu/software.shtml) and can be downloaded [here](http://themis.ssl.berkeley.edu/socware/tdas_7_00/tdas_7_00.zip)

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#12
