### ISSUE TITLE
RHESSI FIDO Queries Give Warnings and Exclude The Last Day from Results

### ISSUE THREAD

**Issue by Alex-Ian-Hamilton** [sunpy/sunpy#2672]
When querying FIDO for RHESSI data spanning multiple days the following warning is showed:

> "UserWarning: Currently only support providing data from one whole day."
 
But the function then returns the correct days. minus the last day of the sequence.

For example, the following gives a user warning but works, with the exception of giving the last days result:
```
from sunpy.net import Fido, attrs as a
import sunpy.timeseries as ts
results = Fido.search(a.Time('2017/09/06 11:00', '2017/09/09 12:00'), a.Instrument('rhessi'))
print('Results:\n',results)
lis_downloaded_files = Fido.fetch(results)
print('downloaded:\n',lis_downloaded_files)
ts_rhessi = ts.TimeSeries(lis_downloaded_files, source='rhessi', concatenate=True)
print('Result from',ts_rhessi.data.index[0],'to',ts_rhessi.data.index[-1])
```

This is independent of [Issue #2382](https://github.com/sunpy/sunpy/issues/2382)

**Comment by aringlis** [comment]
Hi @Alex-Ian-Hamilton  - I think the offending code is in ```sunpy.instr.rhessi. get_obssum_filename``` here:

    dbase_file_name, _ = get_obssumm_dbase_file(time_range)
    dbase_dat = parse_obssumm_dbase_file(dbase_file_name)

    index_number_start = time_range.start.day - 1
    # If end is 0 set it to 1 so we always have at least one record.
    index_number_end = time_range.end.day - 1 or index_number_start + 1

    filenames = dbase_dat.get('filename')[index_number_start:index_number_end]

It should be ```index_number_end =  time_range.end.day``` without the -1, which looks an inadvertent indexing error. 

I'll try to put together a quick PR for that - should be a simple fix.

**Comment by aringlis** [comment]
Btw, @ehsteve, is there any reason now for the user warning/limitation Alex described above to still exist for RHESSI data? ```rhessi.get_obssum_filename()``` returns a list of all the relevant files, but ```rhessi.get_obssum_file()``` is still coded to only return the first file in the list - I don't know why. Besides that, if you go through FIDO you get different behaviour and all files are returned, so the warning doesn't make much sense in that context.
