### ISSUE TITLE
Add  SUVI FITS files

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2683]
To add it as a fido client, data available at:
https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes16/l1b/

Related with #2619 

Requested by [Jon Eckberg via the mailing list](https://groups.google.com/forum/#!topic/sunpy/qoq5Jwfk9ZA).

**Comment by Cadair** [comment]
Duplicate of #2013
