### ISSUE TITLE
Document the use of world_to_pixel and pixel_to_world in the Units and Coordinates Section of the SunPy Guide

### ISSUE THREAD

**Issue by DonkeyShot21** [sunpy/sunpy#2685]
Hi, thanks for the awesome tool. I'm working on sunspot detection and I'm trying to build ground truth masks using hek events. 

I followed this [tutorial](http://docs.sunpy.org/en/v0.9.0/generated/gallery/overplot_hek_polygon.html).
My problem is that I'm not able to get pixel coordinates after the rotation. That is:

`ch_boundary = SkyCoord(
    [(float(v[0]), float(v[1])) * u.arcsec for v in p3],
    obstime=ch_date,
    frame=frames.Helioprojective)`

then:

`rotated_ch_boundary = solar_rotate_coordinate(ch_boundary, aia_map.date)`

I have a SkyCoord object now, how can I get the boundary in px so I can print it on an image and save it? I've seen SkyCoord has a method `to_pixel()` but I can't figure out the projection I have to apply.

My purpose is to create a black image with a white polygon highlighted. The polygon should be in the exact same position as the sunspot in the corresponding image, let's say an SDO HMI intensitygram of the same day I downloaded from helioviewer.

I posted on stackoverflow as well [here](https://stackoverflow.com/questions/51330028/overplot-sunpy-hek-polygon-mask-on-custom-numpy-array-instead-of-sunpy-map)

**Comment by fraserwatson** [comment]
If you want to get the pixel coordinates of a SkyCoord object, and you have a Map object to compare them to, you would use the world_to_pixel method to convert the SkyCoord locations to pixel locations. Add this line to your example and see how it works.

`aia_map.world_to_pixel(rotated_ch_boundary)`

**Comment by DonkeyShot21** [comment]
@fraserwatson Thanks a lot, that did the job

**Comment by Cadair** [comment]
I am glad you found a solution @DonkeyShot21 ! Thanks @fraserwatson :)

I am going to re-purpose this issue to better document `Map.world_to_pixel` in the [Units and Coordinates](http://docs.sunpy.org/en/v0.9.0/guide/units-coordinates.html) section of the SunPy docs.

(also, you could do  `rotated_ch_boundary.to_pixel(aia_map.wcs)` if you *really* wanted to)

**Comment by pkj-m** [comment]
@Cadair can we close this issue after #3776 or do we need to add more than just an example to the documentation explaining the `world_to_pixel` function?

**Comment by nabobalis** [comment]
#3776 added an example.
