### ISSUE TITLE
Suds not installed? 

### ISSUE THREAD

**Issue by yujin512** [sunpy/sunpy#2686]
Hi! 

I just installed a fresh python with miniconda, and I'm getting the following error: 
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib.pyplot as plt
   ...: from sunpy.net import Fido, attrs as a
   ...: from sunpy.map import Map
   ...: 
   ...: 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3d59f1e14a3d> in <module>()
      1 import matplotlib.pyplot as plt
----> 2 from sunpy.net import Fido, attrs as a
      3 from sunpy.map import Map

/anaconda3/lib/python3.6/site-packages/sunpy/net/__init__.py in <module>()
      3 __all__ = ["Fido"]
      4 
----> 5 from sunpy.net.fido_factory import Fido

/anaconda3/lib/python3.6/site-packages/sunpy/net/fido_factory.py in <module>()
     18 from sunpy.util.datatype_factory_base import MultipleMatchError
     19 
---> 20 from sunpy.net.dataretriever.clients import CLIENTS
     21 from sunpy.net.dataretriever.client import QueryResponse
     22 from sunpy.net.vso import VSOClient, QueryResponse as vsoQueryResponse

/anaconda3/lib/python3.6/site-packages/sunpy/net/dataretriever/__init__.py in <module>()
      9 """
     10 
---> 11 from .client import QueryResponseBlock, QueryResponse, GenericClient
     12 
     13 from . import clients

/anaconda3/lib/python3.6/site-packages/sunpy/net/dataretriever/client.py in <module>()
     33 
     34 from sunpy.net.download import Downloader, Results
---> 35 from sunpy.net.vso.attrs import Time, Wavelength, _Range
     36 
     37 TIME_FORMAT = config.get("general", "time_format")

/anaconda3/lib/python3.6/site-packages/sunpy/net/vso/__init__.py in <module>()
      2 
      3 # for exposure to from sunpy.net.vso import *
----> 4 from sunpy.net.vso.vso import VSOClient, InteractiveVSOClient, QueryResponse
      5 
      6 # Delete this in 0.9

/anaconda3/lib/python3.6/site-packages/sunpy/net/vso/vso.py in <module>()
     23 from functools import partial
     24 from collections import defaultdict
---> 25 from suds import client, TypeNotFound
     26 
     27 import astropy.units as u

ModuleNotFoundError: No module named 'suds'

In [2]: 

In [2]: 
```
CC @bmorris3 @Cadair

**Comment by bmorris3** [comment]
Hey @Cadair, we're swirling in a Python package dependency nightmare and we're hopeful you can dig us out. We just installed miniconda, and then sunpy via `conda install -c conda-forge sunpy`, and we're getting this error. Any tips? Thanks!

**Comment by Cadair** [comment]
hey @yujin512 @bmorris3 Sorry I didn't get to this, I have been at SciPy. It's weird this happened on a clean conda install, suds shouldv'e been installed obviously :/

**Comment by ix-** [comment]
I installed the version available from my distribution (funtoo linux) which is 0.8.0
```
[I] dev-python/sunpy [1]
     Available versions:  (~)0.8.0 {jpeg2k test PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  0.8.0(09:24:20 PM 08/14/2018)(jpeg2k -test PYTHON_TARGETS="python2_7
python3_6 -python3_4 -python3_5")
```
There, the problem is not present.
Also `from sunpy.database import Database` does not throw the error, although it does in the virtualenv 0.9.2 version.
Best regards,
ix

**Comment by Cadair** [comment]
@ix- if you are installing from pip and you don't want a minimal installation you should run `pip install sunpy[all]` to install all the optional dependencies.

(I wonder if this needs clarifying in the install docs)

**Comment by ix-** [comment]
Sorry, my bad! I did not read far enough and when.I saw the issue report, I jumped to the conclusion that there was a bug rather than own incompetence...

On 15 August 2018 12:15:07 CEST, Stuart Mumford <notifications@github.com> wrote:
>@ix- if you are installing from pip and you don't want a minimal
>installation you should run `pip install sunpy[all]` to install all the
>optional dependencies.
>
>(I wonder if this needs clarifying in the install docs)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sunpy/sunpy/issues/2686#issuecomment-413154294

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yujin512** [comment]
Sorry I didn't jump in earlier. I uninstalled sunpy and installed sunpy[net], and it worked! Thanks!

**Comment by Cadair** [comment]
No worries on either count, I think we might change around the optional dependencies for the 1.0 release to reduce this kind of confusion.

Thanks for the issue and the comments :)
