### ISSUE TITLE
Handle discrepancy between contour and imshow kwargs like linewidths in CompositeMap

### ISSUE THREAD

**Issue by elastufka** [sunpy/sunpy#2696]
Hi, 
I think it would be pretty easy to enable passing the plt.contour "linewidths" argument into CompositeMaps. Right now I am using a copy of .plot() where I include the "linewidths" argument in .plot_settings enabled in the case of levels = True. I think it would be pretty easy to work this into the plot function to enable users to make the contour lines more visible.

Here's the basic modification I made to plot():

        if m.levels is False:
              #etc
        else:
            params = {
                "origin": "lower",
                "extent": x_range + y_range,
                "cmap": m.plot_settings['cmap'],
                "norm": m.plot_settings['norm'],
                "linewidths":m.plot_settings['linewidths'], #add matplotlib contour kwarg linewidths
                "alpha": m.alpha,
                "zorder": m.zorder,
            }
            params.update(matplot_args)

            # Check for the presence of masked map data
            if m.mask is None:
                ret.append(axes.contour(m.data, m.levels, **params))
            else:
                ret.append(axes.contour(np.ma.array(np.asarray(m.data), mask=m.mask), m.levels, **params))

**Comment by Cadair** [comment]
The `plot` method of composite map accepts all the keywords the `axes.contour` method does. So you should be able to do `CompositeMap.plot(..., linewidths=)`.

**Comment by Cadair** [comment]
Composite map will try and plot as an image by default, unless `compmap.set_levels` is called first. Which I think is the root of this error.

**Comment by elastufka** [comment]
I tried a few things and found out that including linewidths in the plot() call only works if set_levels has first been applied to _all_ maps. Which makes sense because naturally there should be such an error in plt.imshow() as opposed to plt.contour(). So you're right that it does work to set_levels first, but I don't think this is the ideal use case; I'd argue that most users want to overlay contours on an image, not just plot contours alone. 
Either this error needs to be caught before imshow() is called or it should be passed to contour() through plot_settings (although if the **params are inherited from plot_settings in the first place for both the imshow and contour calls, the linewidths keyword will still have to be ignored for non-contour maps).
Thanks for looking into this.

**Comment by Swapnil99007** [comment]
I would like to work on this issue. 
I think this issue is a bit more complex than it seems because it is bit difficult to understand how to incorporate the 'Linewidth' argument inside the plot() function, which is then receiving an 'axes' argument, which again calls the 'imshow' function and this would continue until a matplotlib function is called, meaning we have to pass the linewidth argument to that matplotlib function finally. Since, the plot() function in matplotlib already incorporates the 'Linewidth' argument, our work would be done and plotting would be according to our needs.
