### ISSUE TITLE
Default output observer for solar_rotate_coordinate?

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2707]
Looking at `solar_rotate_coordinate` i am left to wonder if the default output observer should be the input observer (here: https://github.com/sunpy/sunpy/blob/master/sunpy/physics/differential_rotation.py#L100).

It seems weird to default that to "earth" when I would expect a more natural assumption to be the location of the observer in the input coordinate frame? i.e. if I were STEREO B, would I not want the default output to be where my input coordinates are from?

@wafels ?

**Comment by wafels** [comment]
When you do the solar rotation you should also take in to account the
motion of the observer.

The reason the default output observer is the Earth is that there are many
instruments orbiting Earth, and Astropy knows the motion of the Earth.

It may be more sensible to default to the location of the observer in the
input coordinate frame.  Doing this makes the assumption that the error
caused assuming a stationary observer is small.

**Comment by wafels** [comment]
The fix to #2713 will implement the suggestion that the default output observer will be the input observer.

**Comment by Cadair** [comment]
> Doing this makes the assumption that the error caused by assuming a stationary observer is small.

This is a better assumption than assuming the observer is Earth ;)

**Comment by wafels** [comment]
The suggestion to make the default output observer the same as the input observer has not been implemented in #2972.  This suggestion is probably worse than what #2972 does right now (which is to assume an Earth-based observer if the observer keyword. is not specified).
