### ISSUE TITLE
solar_rotate_coordinate not giving same results as SSW rot_xy

### ISSUE THREAD

**Issue by tiagopereira** [sunpy/sunpy#2709]
I compared the values obtained by `solar_rotate_coordinate` using different rotation types, and the result is always somewhat different from SSW's `rot_xy`:

##### xy: (0, 0), (2017-07-26 15:00:00 -> 2017-07-26 16:00:00) [1 hour]:
* Sunpy Howard: (9.826233, -0.05129015)
* Sunpy Snodgrass: (9.68254832, -0.05142909)
* Sunpy Allen: (9.89909709, -0.05121892)
* SSW: (9.14941, -0.0520418)

##### xy: (0, 0), (2017-07-26 15:00:00 -> 2017-07-27 15:00:00) [1 day]:
* Sunpy Howard:  (233.3814198, 1.44737544)
* Sunpy Snodgrass: (230.03929158, 1.36703847)
* Sunpy Allen: (235.0750499, 1.4885578)
* SSW: (217.612, 1.07694)

The difference in x between Sunpy and SSW is significant (much more than the internal difference between sunpy's `rot_type`), and I don't know where it's coming from. SSW should be using Howard by default, and I checked the coefficients in `diff_rot.pro` and they are the same as in `differential_rotation.diff_rot`.

The code to produce the above was based on:

* Sunpy:

```
>>> solar_rotate_coordinate(
              SkyCoord(0*u.arcsec, 0*u.arcsec, obstime="2017-07-26 15:00", 
                       frame='helioprojective', observer='earth'), 
              "2017-07-26 16:00", rot_type='howard'
)
```

* SSW:
```
IDL> xy = rot_xy(0, 0, tstart='2017-07-26 15:00', tend='2017-07-26 16:00')
```

**Comment by wafels** [comment]
The SSWIDL function `rot_xy` selects synodic frame time.  By default, the SunPy function `solar_rotate_coordinate` uses whatever SunPy's `diff_rot` function has as a default.  The default happens to be sidereal time, not synodic time.  Passing the correct value to the `frame_time` keyword explains the difference.  For example:

```
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord
from sunpy.coordinates import frames
from sunpy.physics.differential_rotation import solar_rotate_coordinate
from sunpy.coordinates.ephemeris import get_earth
t1 = '2017-07-26 15:00:00'
t2 = '2017-07-26 16:00:00'
c = SkyCoord(0*u.arcsec, 0*u.arcsec, obstime=t1, observer=get_earth(Time(t1)), frame=frames.Helioprojective)
solar_rotate_coordinate(c, t2, frame_time='synodic')
<SkyCoord (Helioprojective: obstime=2017-07-26 16:00:00, rsun=695508.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2017-07-26 16:00:00): (lon, lat, radius) in (deg, deg, AU)
    (0., 5.37151768, 1.01560496)>): (Tx, Ty, distance) in (arcsec, arcsec, km)
    (9.14936287, -0.05192676, 1.51236864e+08)>
t3 =  '2017-07-27 15:00:00'
solar_rotate_coordinate(c, t3, frame_time='synodic')
<SkyCoord (Helioprojective: obstime=2017-07-27 15:00:00, rsun=695508.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2017-07-27 15:00:00): (lon, lat, radius) in (deg, deg, AU)
    (0., 5.44871169, 1.01550102)>): (Tx, Ty, distance) in (arcsec, arcsec, km)
    (217.61054969, 1.07906331, 1.51239917e+08)>
```

**Comment by wafels** [comment]
Although using `frame_time='synodic'` fixes the equivalency to SSW results, the `solar_rotate_coordinate` is in general incorrect - see #2713 for the underlying issue.  
Closing this issue since using `frame_time='synodic'` fixes the equivalency to SSW results, thereby answering the issue.  Further discussion on fixing `solar_rotate_coordinate` in general should be added to #2713.
