### ISSUE TITLE
[0.9] fermi.met_to_utc does not account for leap seconds

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#2710]
@Cadair, @wafels, @ehsteve. 

Fermi Mission Elapsed Time (MET) is the number of seconds elapsed since a pre-defined fiducial, or base time, in this case 2001 January 01 00:00 UT. The current version of the function fermi.met_to_utc is incorrect. It does not account for leap seconds that have occurred since the fiducial.

The in-development version of this function that uses Astropy.time appears to be correct, it accounts for the leap seconds, and gives the same answer provided by XTIME (https://heasarc.gsfc.nasa.gov/cgi-bin/Tools/xTime/xTime.pl). It's possible that XTIME also uses AstroPy, but importantly the same time is returned by tools in SolarSoftWare written by Kim Tolbert and Richard Schwartz.

For example:

Fermi MET = 390009602.0

The current fermi_met_to_utc function will return this as 2013-05-12 00:00:02.000 UTC, but the correct answer is actually 2013-05-11 23:59:59.000 UTC. This is because datetime does not know that three of the elapsed seconds were leap seconds.

This whole situation is complicated by the fact that the headers in Fermi GBM data files show the incorrect time in string format. Their string headers also do not seem to account for leap seconds, which I think is why I didn't catch this error in the first place. When testing this, I saw that the times returned matched the file headers and assumed it to be correct.

This could be fixed by incorporating a lookup table of leap seconds, but if the switch to Astropy.time fixes this anyway it may not be worth it.

---

Note: This is fixed in the 1.0 branch due to the transition to `astropy.time`. 
This is now labelled as `Wont Fix` because we are not fixing it in the 0.9 series.

**Comment by aringlis** [comment]
To fix this in the current version without use of Astropy.time requires use of a lookup table of leap seconds. 6-monthly bulletins are provided by IERS (International Earth Rotation and Reference Service) dictating whether there will be a leap-second added or not. The full list of leap seconds is stored in text form here:

http://maia.usno.navy.mil/ser7/tai-utc.dat

Looking up this info appears to be how AstroPy handles leap seconds as well.

**Comment by Cadair** [comment]
> This whole situation is complicated by the fact that the headers in Fermi GBM data files show the incorrect time in string format. Their string headers also do not seem to account for leap seconds, which I think is why I didn't catch this error in the first place. When testing this, I saw that the times returned matched the file headers and assumed it to be correct.

:man_facepalming: :woman_facepalming: :woman_facepalming: 

That will be all.

**Comment by nabobalis** [comment]
Sure but the fix is probably not gonna be backported.

**Comment by Cadair** [comment]
I would be ok with wont-fix'ing this as long as we document it in the 0.9 branch somewhere prominent.

**Comment by nabobalis** [comment]
I can do that.

**Comment by Cadair** [comment]
@aringlis if you get a chance to test this out on the master branch and make sure it's all ok sometime that would be great :smile:

**Comment by aringlis** [comment]
@Cadair I tried to check this but got a whole load of merge conflicts when pulling the 0.9 branch?!

**Comment by nabobalis** [comment]
You mean pulling master into the 0.9 branch?

**Comment by aringlis** [comment]
Ugh, I think I misread - where is this bug fixed? In master?

**Comment by nabobalis** [comment]
Yeah It is fixed (at least we think so) in master.

**Comment by aringlis** [comment]
Ok, @Cadair @nabobalis I tested the ```fermi.met_to_utc``` function in master and it appears to correctly account for leap seconds now.

**Comment by nabobalis** [comment]
That is good news. I added a warning to the function in the 0.9 branch but I don't think we can backport a fix.
