### ISSUE TITLE
Incorrect transformation between HCC and HPC with different observers

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2712]
There seems to be a bug when transforming between a Heliocentric Cartesian (HCC) frame and a Helioprojective (HPC) frame, where the two frames are defined by different observers. 

Best illustrated by example (see below).

```python
>>> from astropy.coordinates import SkyCoord
>>> import astropy.units as u
>>> import astropy.constants as const
>>> from sunpy.coordinates import Heliocentric,Helioprojective
# First observer
>>> obs_1 = SkyCoord(lon=0*u.deg, lat=0*u.deg, radius=const.au, frame='heliographic_stonyhurst')
# HCC frame defined by first observer
>>> hcc_frame = Heliocentric(observer=obs_1)
# Point on the surface of the Sun in the new HCC frame
>>> p = SkyCoord(x=0*u.m,y=0*u.m,z=const.R_sun,frame=hcc_frame)
# Second observer rotated 90 deg in longitude
>>> obs_2 = SkyCoord(lon=90*u.deg, lat=0*u.deg, radius=const.au, frame='heliographic_stonyhurst')
# HPC frame defined by second observer
>>> hpc_frame = Helioprojective(observer=obs_2)
```

Because this second observer is rotated by 90 degrees, we would expect `p`, expressed in the HPC frame, to be on the limb and to the left, i.e. theta_x <0. 

```python
>>> p.transform_to(hpc_frame)
<SkyCoord (Helioprojective: obstime=None, rsun=695508.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=None): (lon, lat, radius) in (deg, deg, m)
    (90., 0., 1.49597871e+11)>): (Tx, Ty, distance) in (arcsec, arcsec, km)
    (0., 0., 1.48902171e+08)>
```

This is not the case. It stays at the center of the disk for some reason. However, if we do an intermediate transform to an HGS frame, we get the expected result,

```python
>>> p.transform_to('heliographic_stonyhurst').transform_to(hpc_frame)
<SkyCoord (Helioprojective: obstime=None, rsun=695508.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=None): (lon, lat, radius) in (deg, deg, m)
    (90., 0., 1.49597871e+11)>): (Tx, Ty, distance) in (arcsec, arcsec, km)
    (-959.22081361, 0., 1.49599488e+08)>
```

So it seems there is some bug in the HCC->HPC transform that does not come up when we add the intermediate HGS transform, i.e. HCC->HGS->HPC

**Comment by wtbarnes** [comment]
So it seems this is due to the fact that the `hcc_to_hpc` transformation (see [here](https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/transformations.py#L102)) does not account for the two frames having different observers. This problem can be traced back to Eqs. 15 and 16 of Thompson (2006).

One proposed solution: remove the explicit `hpc_to_hcc` and `hcc_to_hpc` transformations, add explicit `hgs_to_hpc`, `hpc_to_hgs` transformations. HPC<->HCC should then be done via the transformation graph by doing an intermediate HGS transformation and thus accounting for the change in observer. 

Thoughts @wafels,@Cadair?

**Comment by wtbarnes** [comment]
After some discussion with @wafels and @Cadair, one possible plan would be to provide an `hcc_to_hcc` transformation between two HCC frames with different observers. Then, in the HCC<->HPC transformations, we can add a check for whether the two frames are equal. If they are not, the `hcc_to_hcc` transformation is applied.

This `hcc_to_hcc` could also be used in the `hpc_to_hpc` transformation where currently HGS is used as an intermediate.

**Comment by Cadair** [comment]
I am going to close this as fixed by #2725 and we can continue any discussion about the implementation of the transform in #2754

**Comment by wtbarnes** [comment]
Wait I thought you reverted #2725? Or was that only part of it?

I'm fine with this though I think we should probably create an additional issue to note that #2754 is just a stopgap.

**Comment by Cadair** [comment]
It was only part of it (the part that prevented a do nothing transform between HPC<>HPC when there was only string observers)
