### ISSUE TITLE
Rotation of solar co-ordinate does not take account of new observer location

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2713]
Currently, the `solar_rotate_coordinate`  function creates a new coordinate by adding the calculated solar rotation (found by calculating the amount of solar rotation at a given latitude between the input coordinate time and the requested time) to the input solar co-ordinate and then setting the observer property.

This is incorrect.  What the function should do is to create a new coordinate by adding the calculated solar rotation to the input solar co-ordinate as seen from the input observer, and then transform that new coordinate to a coordinate as seen by an observer at the requested time.

**Comment by wtbarnes** [comment]
Ok so this should solve #2712 as well then, correct? 

And it makes sense why adding an intermediate HGS frame, which is independent of observer, gives the correct answer.

**Comment by Cadair** [comment]
for the record I think this is independent of #2712
