### ISSUE TITLE
LASCO C3 Maps from JP2 sources are badly stretched

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2724]
See attached: probably need to fix the stretching.

![figure_1](https://user-images.githubusercontent.com/983575/44162559-b65abc00-a08e-11e8-8f6d-0ae9ebb026dd.png)

**Comment by wafels** [comment]
This is where LASCO C3 gets the square root scaling - https://github.com/sunpy/sunpy/commit/55610e9cad745033a19b41c1ecf26e472df9da3b#diff-62c564e29c6769deb57b644d7414de74

**Comment by Cadair** [comment]
we have already fixed this for other map sources like AIA right?

**Comment by wafels** [comment]
Yes we have.  For AIA sources, the image stretching is replaced by the LinearStretch.  The linear stretching replacement is working.  When you just plot the data using imshow you get a perfectly reasonable looking plot.  I think in this case the colormap should be changed, say to the matplotlib bone color table - see attached.
![figure_1](https://user-images.githubusercontent.com/983575/44205970-2ff1b900-a126-11e8-931d-95ed37073eae.png)

**Comment by Cadair** [comment]
frankly that looks much better than the original cm imo

**Comment by wafels** [comment]
i agree. the standard colortables are not great for LASCO or COR1,2.
