### ISSUE TITLE
Return type of observer is inconsistent

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2732]
The return type of the `observer` property on a `SkyCoord` is different for the default frame ('earth') and a user-defined frame. As an example,

```python
# Define HCC frame
>>> obs = SkyCoord(lon=0*u.deg,lat=0*u.deg,frame='heliographic_stonyhurst')
>>> hcc = Heliocentric(observer=obs)
# Point in this frame
>>> p1 = SkyCoord(x=0*u.cm,y=0*u.cm,z=const.au,frame=hcc)
>>> p1.observer
<HeliographicStonyhurst Coordinate (obstime=None): (lon, lat, radius) in (deg, deg, m)
    (0., 0., 1.49597871e+11)>
# Point in default HCC frame
>>> p2 = SkyCoord(x=0*u.cm,y=0*u.cm,z=const.au,frame='heliocentric')
>>> p2.observer
'earth'
```
I would expect `.observer` to always return a `SkyCoord` (though there is also #2723).

**Comment by Cadair** [comment]
It should only be a string in the case where obstime is not specified so the position can not be calculated.

**Comment by Cadair** [comment]
It raises an exception at the point where you need to know the concrete observer location (inside the transformations). Its perfectly functional to use a HPC coordinate object without ever knowing the observer location relative to anything else, i.e. overplotting on a HPC map etc.

**Comment by wtbarnes** [comment]
Ok. I guess this can be closed.

I actually opened this because some tests on #2725 were failing due to `.observer` being a string in some cases, but it turns out I was running some old tests on accident...
