### ISSUE TITLE
show_colormaps() is not big enough to show the colormap names

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2734]
See attached picture.  This affects the gallery too - see http://docs.sunpy.org/en/stable/generated/gallery/plotting/sunpy_colormaps_reference.html#sphx-glr-generated-gallery-plotting-sunpy-colormaps-reference-py
![figure_1](https://user-images.githubusercontent.com/983575/44535050-2983b400-a6c7-11e8-8bb1-771a40228c83.png)

**Comment by manasbedmutha98** [comment]
Is this issue still open?

**Comment by jairideout** [comment]
I opened a PR (#2824) to fix the issue.

**Comment by ebuchlin** [comment]
I guess that this should be reopened because of the long Solar Orbiter/EUI/HRI names, on https://docs.sunpy.org/en/stable/guide/data_types/maps.html#colormaps-and-normalization:

![image](https://user-images.githubusercontent.com/3624676/141250298-ab071b4d-0c72-46e0-87ce-9edb40243614.png)
