### ISSUE TITLE
We should return an astropy table from the HEK search method

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2740]
The list of dicts is really ugly in comparison to an astropy table.

**Comment by wafels** [comment]
Interesting idea - HEK object returns could be a lot more useful.  For
example, if we return sunpy co-ordinates then plotting of bounding boxes
and object outlines becomes much easier.

*http://www.lmsal.com/hek/VOEvent_Spec.html
<http://www.lmsal.com/hek/VOEvent_Spec.html>*

See also #1792 and #1398

**Comment by souravghosh97** [comment]
I want to work on this issue as well as #1792 . What i want to know is why it was suggested that the ```parse_hek_response_to_quantities()``` is applied inside get_voevent() and not on results of HEKClient search. What that features requests need?

**Comment by souravghosh97** [comment]
@Cadair I think for this one have to implement an HEKTable, HEKColumn, HEKRow. because as of now HEKClient.search() method returns response object which in turn can be used to get voe event (by ```get_voevent``` method of Response object)
```
from sunpy.net import hek
tend = '2011/08/09 12:40:29'
tstart = '2011/08/09 07:23:56'
event_type = 'FL'
client = hek.HEKClient()
result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
print(result[0].get_voevent())
```
while if anyone astropy table return result[0] will be an astropy Row Object with no get_voevent method

**Comment by nitish705702** [comment]
it should return an astropy table from the HEK search method.
not present any error.

**Comment by nabobalis** [comment]
Are you saying it is not returning a table?

**Comment by nitish705702** [comment]
means There are no  issues in the file  sunpy/net/hek/hek.py.

**Comment by nabobalis** [comment]
Yes, that should be correct. Which is why this issue is closed (the large red box that the top). I would suggest looking at open issues (https://github.com/sunpy/sunpy/issues?q=is%3Aissue+is%3Aopen+label%3A%22Package+Novice%22).
