### ISSUE TITLE
Add a HMI overplotting on AIA example

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2741]
Should use Composite map to over plot the magnetic field strength contours on an AIA image.

**Comment by Chicrala** [comment]
The idea is to create an example like the ones that are accessible via tutorial from a sample data or make a general routine for this?

I'm currently making plots of Poynting flux over HMI Br component so I may be able to help with this if I understand it correctly.

**Comment by Cadair** [comment]
We already have this functionality in `sunpy.map.compositemap`, the issue is to write an example like [this](http://docs.sunpy.org/en/stable/generated/gallery/maps/map_rotation.html#sphx-glr-generated-gallery-maps-map-rotation-py) which live in the [`examples/`](https://github.com/sunpy/sunpy/tree/master/examples) directory.

**Comment by Cadair** [comment]
(note: composite map will only over plot if the data is already aligned, so both the AIA and HMI image should be thrown through `aiaprep` first)

(note, note: we don't actually have any HMI data in our sample data at the moment, so we should really add that as well)

**Comment by Chicrala** [comment]
I think I understood.
May I try to solve this then?

**Comment by Cadair** [comment]
Just open the Pull Request, it makes it a lot easier to give feedback on :smiley:

**Comment by Chicrala** [comment]
I haven't thought on this haha
