### ISSUE TITLE
Integrate Metadata searching with Fido

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2744]
The `Fido` interface is a very powerful and extensible search API for a wide variety of possible data sources. However, we currently do not have a cohesive solution for metadata (not file) search and retrieval.

SunPy currently has the following metadata search facilities:

* HEK Client
* Helio Client
* JSOC Client (also does files through Fido)

We should design extensions to Fido (primarily I would image this being a change in what is returned from `.search` to support rich display of metadata and not just simple file based records.

**Comment by abhijeetmanhas** [comment]
@Cadair I would like to work on it, is it similar to `search_metadata()` function in JSOC Client? We only want metadata searches, say for egs. query things given in header of fits file?
But the metadata will also depend upon format of file,

I just want further elaboration what exactly metadata integration will make Fido capable of, a simple example will do.

**Comment by nabobalis** [comment]
This issue will be tackled as part of the FIDO GSoC project.

**Comment by abhijeetmanhas** [comment]
So can this issue be divided into subtasks so that it can be worked upon?

**Comment by nabobalis** [comment]
Yes but I expect nothing to happen regarding this issue until the GSoC project starts (if it is picked).
