### ISSUE TITLE
Improvements to composite map

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2745]
Composite map really needs some upgrades, and seeing how some of them would be API breaking (the fist one on the following list especially so) we should probably do it before 1.0.

Things I can think of without actually looking over the code:

1. The `get_` and `set_` methods should be changed to be properties.
1. The contouring routines should use the WCSAxes support for [overlaying contours in different coordinate systems](http://docs.astropy.org/en/stable/visualization/wcsaxes/overlays.html#contours).
1. It should use reproject to automatically overplot two unaligned images
1. It should use reproject to align any two arbitrary images with flux conservation for analysis

It is also worth having a larger discussion about where `CompositeMap` fits into our general roadmap. Maybe even with a long-term eye on ndcube.

@wafels ping

**Comment by nabobalis** [comment]
See #2696, #463, #218.

**Comment by Cubostar** [comment]
If we still need CompositeMap, I would love to work on this.

**Comment by wtbarnes** [comment]
Also see #4492

**Comment by wtbarnes** [comment]
I'm closing this as it appears all of the original asks have been addressed by issues that are now closed. If anyone disagrees, feel free to reopen.
