### ISSUE TITLE
Maintain coherence between keycomments and the metadict

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2750]
See #2748 

This is probably best implemented by adding the functionality to our `MetaDict` object or something, so that we don't have to do it manually everywhere.

**Comment by ritesh99rakesh** [comment]
Can I pick this up?

**Comment by nabobalis** [comment]
@ritesh99rakesh Sure!

**Comment by FeruzOripov** [comment]
How to contribute ?

**Comment by jairideout** [comment]
Can I work on this issue?

**Comment by nabobalis** [comment]
Sure.

**Comment by jairideout** [comment]
The `MetaDict` class is fairly general: it's an `OrderedDict` subclass with case-insensitive `str` keys. Is it okay to have `MetaDict` manage its `KEYCOMMENTS` dictionary (if it has one)? This may introduce knowledge of the FITS header format to `MetaDict`, and I wanted to double-check that this is acceptable before implementing the feature. 

Also, I noticed that `sunpy.io.header.FileHeader` is another general `OrderedDict` subclass used to store header key-value data. Do we also want `FileHeader` to manage `KEYCOMMENTS`?

**Comment by dstansby** [comment]
Just to add a note that `KEYCOMMENTS` being removed by SunPy can cause some odd side effects/bugs when using `KEYCOMMENTS` in map source classes, which is what pfsspy does at https://github.com/dstansby/pfsspy/blob/322429eec62be7c699a58df651d35a919fb379db/pfsspy/map.py#L10
