### ISSUE TITLE
Plot is missing from the end of the units and coordinates section of the docs

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2756]
See here: http://docs.sunpy.org/en/v0.9.0/guide/units-coordinates.html#using-coordinates-with-sunpy-map

**Comment by IpshitaC** [comment]
Hi @Cadair 
Can I take this up for hacktoberfest? Could you give me some idea as to what needs to be done?

**Comment by camilosalazar98** [comment]
Hey @Cadair I'm also interested in fixing this issue. Once I have the plot where do I add it?

**Comment by nabobalis** [comment]
I think for this issue, (I could be wrong) Is that the last example has a matplotlib plot that is not displayed.

**Comment by camilosalazar98** [comment]
I got it but where do I add it?

**Comment by nabobalis** [comment]
Well it's not a hard plot that is added. It have to be generated at the build of the documentation.

**Comment by camilosalazar98** [comment]
So I found the place where I add the code to generate the graph but I get this error messageThe configuration file (or one of the modules it imports) called sys.exit()
Sphinx Documentation subprocess failed with return code 1.

**Comment by nabobalis** [comment]
Is there any more to that message? You might not have the packages installed to build the documentation. We have some fiddly requirements for our docs.

**Comment by camilosalazar98** [comment]
I get type this  python3 setup.py build_sphinx -l
<img width="971" alt="screen shot 2018-10-03 at 1 51 51 pm" src="https://user-images.githubusercontent.com/10333493/46429064-89806800-c713-11e8-860b-dc9e4907ea2e.png">

**Comment by nabobalis** [comment]
Ah ok! The error is actually above the red text. You will need to either pip or conda install `sphinx-astropy`

**Comment by camilosalazar98** [comment]
It seem that solve the issue but I got something new.

<img width="1145" alt="screen shot 2018-10-03 at 3 17 40 pm" src="https://user-images.githubusercontent.com/10333493/46433738-ab7fe780-c71f-11e8-818f-02633df65f81.png">

Got this message..
open-docs-in-browser option was given, but the builder is not html! Ignoring.

Is there a special browser that you guys use?

**Comment by nabobalis** [comment]
Oh, I use `python setup.py build_docs`, I don't know what happens if you use `build_sphinx`

**Comment by camilosalazar98** [comment]
Yeah I have no idea. Theres no errors which is funny. I'm assuming when you run the application a application should open.

When I use:
python setup.py build_docs
<img width="965" alt="screen shot 2018-10-03 at 3 38 54 pm" src="https://user-images.githubusercontent.com/10333493/46434953-1f6fbf00-c723-11e8-90e0-0286481ea461.png">



python setup.py build_sphinx
<img width="972" alt="screen shot 2018-10-03 at 3 49 13 pm" src="https://user-images.githubusercontent.com/10333493/46435247-ea17a100-c723-11e8-9b1a-8aae731d7abc.png">



Welp. It better to deal with this now unless someone had the same issue and found a solution.
But yeah this is odd.

Is it like flask? A webpage should pop up once the build is done?

**Comment by nabobalis** [comment]
Oh a webpage has never opened after a build for me. I always do it manually by using  the command line. `firefox docs/_build/html/index.html` or similar.

**Comment by camilosalazar98** [comment]
Yeah been looking around and I have no clue how to fix the "open-docs-in-browser option was given, but the builder is not html! Ignoring." @Cadair @nabobalis

**Comment by nabobalis** [comment]
Open the built html files using a browser of your choice and then navigate to the correct page.
