### ISSUE TITLE
Problem running the SunPy tests on Mac

### ISSUE THREAD

**Issue by Spartan1988** [sunpy/sunpy#2758]
I've obtained the following while trying to run the SunPy tests

In [3]: sunpy.self_test(online=False)

============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/_**My_Path**_/.hypothesis/examples')
rootdir: /Users/Andres, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, mock-1.10.0, doctestplus-0.1.3, arraydiff-0.2, hypothesis-3.71.9
collected 1263 items / 1 errors / 27 deselected                                

==================================== ERRORS ====================================
 ERROR collecting anaconda/lib/python3.6/site-packages/sunpy/image/tests/test_transform.py 
ImportError while importing test module '/Users/_**My_Path**_/anaconda/lib/python3.6/site-packages/sunpy/image/tests/test_transform.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda/lib/python3.6/site-packages/sunpy/image/tests/test_transform.py:6: in <module>
    import skimage.data as images
anaconda/lib/python3.6/site-packages/skimage/data/__init__.py:16: in <module>
    from ..io import imread, use_plugin
anaconda/lib/python3.6/site-packages/skimage/io/__init__.py:7: in <module>
    from .manage_plugins import *
anaconda/lib/python3.6/site-packages/skimage/io/manage_plugins.py:28: in <module>
    from .collection import imread_collection_wrapper
anaconda/lib/python3.6/site-packages/skimage/io/collection.py:12: in <module>
    from PIL import Image
anaconda/lib/python3.6/site-packages/PIL/Image.py:64: in <module>
    from . import _imaging as core
E   ImportError: dlopen(/Users/_**My_Path**_/anaconda/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
E     Referenced from: /Users/_**My_Path**_/anaconda/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
E     Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 13.0.0 or later, but libjpeg.9.dylib provides version 12.0.0
=============================== warnings summary ===============================
None
  Module already imported so cannot be rewritten: pytest_remotedata
  Module already imported so cannot be rewritten: pytest_openfiles
  Module already imported so cannot be rewritten: _pytest_mock_version
  Module already imported so cannot be rewritten: pytest_mock
  Module already imported so cannot be rewritten: pytest_doctestplus
  Module already imported so cannot be rewritten: pytest_arraydiff

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
============== 27 deselected, 6 warnings, 1 error in 0.81 seconds ==============
Out[3]: 2

**Comment by nabobalis** [comment]
Hi @Spartan1988, I do not have a mac to debug this myself but I could find a [link here](https://github.com/python-pillow/Pillow/issues/3115) from a different project that had a similar issue.

[Or maybe some of the instructions might be useful.](https://stackoverflow.com/questions/22728468/osx-pillow-incompatible-library-version-libtiff-5-dylib-libjpeg-8-dylib)

Sorry about this! I will ask some mac people I know for more advice.

**Comment by nabobalis** [comment]
I am going to close this issue, if you have no fixed it, re-open this and we can try to debug it again!
