### ISSUE TITLE
Add support to download the header information from helioviewer

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2762]
Currently our HelioViewer Client (https://github.com/sunpy/sunpy/blob/master/sunpy/net/helioviewer.py) allows us to download jpeg files from the service. They (Helioviewer) have an a better API now (v2 which is linked in the original post) that allows us to also download the metadata of the jpeg files with a seperate function. We do not have that seperate function, which is what this issue is tracking. 

The API returns XML data so we want to convert it to a nicer dictionary format.

**Comment by Cadair** [comment]
also related to #2744

**Comment by Naman9639** [comment]
I would like to work on this. Can you explain it a bit?

**Comment by nabobalis** [comment]
Currently our HelioViewer Client allows us to download jpeg files from the service. They (Helioviewer) have an a better API now (v2 which is linked in the original post) that allows us to also download the metadata of the jpeg files with a seperate function. We do not have that seperate function, which is what this issue is tracking. 

This is also related to https://github.com/sunpy/sunpy/issues/2280 since we currently use v1 of the API and need to move to V2.

**Comment by Naman9639** [comment]
Ok got it

**Comment by ishanisri** [comment]
Is this issue still open? If yes, I would like to work on it.

**Comment by Naman9639** [comment]
Yes this issue is still open but before working on this we need to shift our API to version 2 and we are working on that. There are a lot of changes in the helioviewer code and that code still needs to be reviewed. We can only add that support after our API exclusive support the version 2 because downloading header features is supported on by the version 2 of the API

**Comment by nabobalis** [comment]
@ishanisri It is possible to do if you base your work off @Naman9639 code.

**Comment by Naman9639** [comment]
But that code still needs review right? @nabobalis

**Comment by Naman9639** [comment]
I have a doubt. In what format do we want the data to be downloaded because the API returns XML data. So do want to download the .xml file or we want it some other format?

**Comment by nabobalis** [comment]
Probably convert it to a dictionary.

**Comment by Naman9639** [comment]
ok

**Comment by ishanisri** [comment]
Okay, so as I am new to this, will I have to clone @Naman9639's fork of this repo to work on this issue?

**Comment by Naman9639** [comment]
@ishanisri are you still working on this issue?

**Comment by nabobalis** [comment]
That's no problem. The only update is that the API changes occurred.

**Comment by Naman9639** [comment]
Um, is this issue still open and may I work on this?

**Comment by nabobalis** [comment]
Yes.

**Comment by Naman9639** [comment]
We want the header information to be in XML format or do we want to print it on the terminal?

**Comment by nabobalis** [comment]
We probably want it to returned in a dictionary format.

**Comment by Naman9639** [comment]
Ok I will do that.
