### ISSUE TITLE
Need a clear tutorial on downloading and viewing data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2772]
Although there seem to be some examples/tutorials in the documentation that use the sample data, there are no obvious examples on how to download and then view/analyse non-sample data. The ones I can find are

- http://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/2011_06_07_sampledata_overview.html#sphx-glr-generated-gallery-acquiring-data-2011-06-07-sampledata-overview-py - only has sample data
- http://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/skip_searching_vso.html#sphx-glr-generated-gallery-acquiring-data-skip-searching-vso-py - only shows how to search for data
- http://docs.sunpy.org/en/stable/guide/tour.html#obtaining-data - only shows how to search for data
- http://docs.sunpy.org/en/stable/guide/tour.html#maps only has sample data.

And that's it really... A linked up tutorial on searching for, downloading, and plotting some data, which assumes no previous knowledge of SunPy would be much appreciated.

**Comment by Cadair** [comment]
I think this would be best written into the Guide section of the docs, with plenty of description about why things are done like they are etc.

**Comment by Chicrala** [comment]
I can create one for HMI and AIA.
