### ISSUE TITLE
Fido progress bar doesn't work properly in Jupyter notebook

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2773]
The progress bar used by Fido doesn't work very well in a Jupyter notebook:
![screenshot 2018-10-08 at 14 36 07](https://user-images.githubusercontent.com/6197628/46612162-aa77fd00-cb07-11e8-8c92-60ad56799f73.png)

Example code:
```python
from sunpy.net import Fido, attrs as a
timerange = a.Time('1996/05/24 11:00', '1996/05/24 12:00')
instrument = a.Instrument('C3')
result = Fido.search(timerange, instrument)
downloaded_files = Fido.fetch(result)
```

**Comment by Cadair** [comment]
Yes, the progress bar *sucks* but is surprisingly hard to change because it's wedged into our weird threaded downloader. I am working on a branch which replaces the downloader with something based on asyncio, but it's a big project and is taking it's time.
