### ISSUE TITLE
LineAnimator display of small y-axis values

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#2777]
The aspect ratio of `LineAnimator` appears to be determined through absolute scaling of x and y values. For example if y ~ 10^-9 and x ~ 1, the y-axis is not visible. We need something like an `aspect` kwarg as in `plt.imshow` so that the length of each axis is determined by the plotting area and not the data range. This issue probably applies to the other animated classes.

**Comment by Akram9** [comment]
I was trying this and I don't get where this should be implemented - base or line? From what I understand, the change should be in `plot_start_image` of `line`. Is it right?
Also, from what I understand of `lineanimator`, it uses matplotlib.axes to plot the image, right? Then can't `plt.axis('auto')` be used in the command line?

**Comment by nabobalis** [comment]
Probably just get it working for lineanimator. 

I don't know the underlying code of the animator classes, so you might have to play around with it.

**Comment by nabobalis** [comment]
@MSKirk Any change of a short example?

**Comment by MSKirk** [comment]
This will replicate the bug:

```
import numpy as np
import matplotlib.pyplot as plt
from sunpy.visualization.imageanimator import LineAnimator

data_shape0 = (10, 20)
data0 = np.random.rand(*data_shape0)*10e-9
plot_axis0 = 1
slider_axis0 = 0

xdata = np.tile(np.linspace(0, 100, data_shape0[plot_axis0]), (data_shape0[slider_axis0], 1))
ani = LineAnimator(data0, plot_axis_index=plot_axis0, axis_ranges=[None, xdata])
plt.show()
```

**Comment by nabobalis** [comment]
Thanks!

**Comment by nabobalis** [comment]
So on master now with (#2986), I had to update the code (import change and the `+1` in xdata).

```
import numpy as np
import matplotlib.pyplot as plt
from sunpy.visualization.animator import LineAnimator

data_shape0 = (10, 20)
data0 = np.random.rand(*data_shape0)*10e-9
plot_axis0 = 1
slider_axis0 = 0

xdata = np.tile(np.linspace(0, 100, data_shape0[plot_axis0]+1), (data_shape0[slider_axis0], 1))
ani = LineAnimator(data0, plot_axis_index=plot_axis0, axis_ranges=[None, xdata])
plt.show()
```

The default plot is now:
![Figure_1](https://user-images.githubusercontent.com/1392107/54827689-80c42400-4caa-11e9-9698-e286fea96005.png)
