### ISSUE TITLE
Where does sunpy download data to?

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#281]
Sunpy appears to automagically download data to a directory, but I don't know where that directory is.  I tried using the lightcurve functionality, and I thought it did not work, but I think it downloaded data to /Users/ireland/sunpy/data .  There was no indication that data was being downloaded.  Also, this location is inside my git repository; I consider this a dangerous place to keep the data, as it is essentially the same place as the code.  A better location might be ~/sunpy-data.  Thanks,  Jack

**Comment by wtbarnes** [comment]
Can this be closed? The directory where sunpy downloads data can be set in the config file...

**Comment by dstansby** [comment]
I think SunPy now downloads to ~/sunpy/data by default, and shows a progress bar when downloading, which seems to fix the original issue. If anyone disagrees feel free to re-open (or maybe re-open a new issue since this one is so old).
