### ISSUE TITLE
Unexpected error on import of goes module

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#2821]
### Description

When importing the goes instr module to get two simple functions
```
from sunpy.instr.goes import flareclass_to_flux, flux_to_flareclass
```
I ran into an error because it was trying to import the `hek` module which requires a package I had not yet installed.

### Expected behavior

Given that the functions I wanted are simple and should not require the `hek`, I was not expecting to need to have a package installed to support the `hek` module.

### Actual behavior

Should have no error!

I would recommend the import of `hek` is moved into the only function that uses it which is `get_goes_event_list`.

**Comment by Cadair** [comment]
This is related to the discussion I want to have in #2807 I will do that in there.

**Comment by Akram9** [comment]
I'm not getting any error here. Just warnings about the 'lightcurve' module going out of fashion. Has this been solved?

**Comment by nabobalis** [comment]
Are you sure you are using the current version from this repository? LightCurve has been deleted.  

This issue is still open and I see no reason why it would have been solved.

**Comment by Akram9** [comment]
I'll update and try again.

**Comment by Akram9** [comment]
Ok ya, I get the error. I was on stable then. My bad.

**Comment by Akram9** [comment]
Okay, I get it. It would make sense to move `import hek` into the aforementioned function. Should I do it?

**Comment by nabobalis** [comment]
Yeah, it would probably be enough.
