### ISSUE TITLE
Provide a better __repr__ for TimeSeries/TimeSeriesMetaData

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2832]
The `astropy.table.Table. __repr__` is much better than the SunPy TimeSeries one (which is not overloaded by the looks of it).

We should look at updating the one we have.

**Comment by darthgera123** [comment]
i would like to help out with this issue. please guide

**Comment by nabobalis** [comment]
@Cadair Could you expand this?

**Comment by nabobalis** [comment]
I assume the issue is that `TimeSeries.__repr__` is either ugly in what it prints or the code itself and needs to be updated to look/behave similarly to how `astropy.table.Table. __repr__` does it.

**Comment by jiaqing23** [comment]
Hi, can I work on this issue?

**Comment by nabobalis** [comment]
Sure.
