### ISSUE TITLE
The Sample Data example should include all the timeseries data

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2834]
Currently the [sample data overview](http://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/2011_06_07_sampledata_overview.html) does not show plots of all the timeseries sample data.

So the sample data overview page has examples of GOES, RHESSI and we would like to add examples of NORH,NOAA for example.

**Comment by nabobalis** [comment]
It would seem that some of the sunpy sample data is missing from that example. 

Specifically the `sunpy.sample_data.<name>_TIMESERIES` ones. 
These would need to be plotted within that example.

**Comment by ishanisri** [comment]
So the sample data overview page has examples of GOES, RHESSI and we would like to add examples of NORH,NOAA etc?

**Comment by Akram9** [comment]
I was looking into these and I am not able to plot NOAA and EVE time series plots. Plotting them with `sunpy.timeseries.TimeSeries` gives `TypeError` while with `sunpy.map.Map` says that `txt` files are not supported yet.
All three of these files are of `txt` format.

**Comment by Akram9** [comment]
Another thing - the `TimeSeries` plots don't need a `plt.show()` to be printed from my console. `anything.peek()` does that automatically. Is it related to my system (wsl Ubuntu on Windows10) or have the docs become old?

**Comment by nabobalis** [comment]
What is the type error for TimeSeries? They don't work in Map.

I think we have an issue/bug on how peek displays plots. I would ignore that for now. I recall that peek calls plt.show while plot does not.

**Comment by Akram9** [comment]
```
>>> a = sunpy.timeseries.TimeSeries(sample_data.NOAAPREDICT_TIMESERIES)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/h/Documents/Projects/sunpy-akram/sunpy/timeseries/timeseries_factory.py", line 404, in __call__
    new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
  File "/mnt/h/Documents/Projects/sunpy-akram/sunpy/timeseries/timeseries_factory.py", line 528, in _check_registered_widgets
    data, meta, units = WidgetType._parse_file(filepath)
TypeError: cannot unpack non-iterable NotImplementedType object```

**Comment by nabobalis** [comment]
You will have to add `, source='NOAAPredictIndices')` to the call. Right now it seems that TimeSeries does not auto figure out the file for txt files.

**Comment by Akram9** [comment]
Right, it works now.

And yeah, about the `CallistoSpectrum` one? It looks like this:

![callisto_spectrum](https://user-images.githubusercontent.com/29861975/53681138-f4f25400-3d0a-11e9-84c7-b4ca4053d008.png)

**Comment by nabobalis** [comment]
Not sure, I am not sure that normally it matplotlib should aspect ratio like that. I wonder if there is something in the peek code that does that.

**Comment by dpshelio** [comment]
In the radio spectra what we do is to create pixels in between. That's expected as it is if using maps for it.

**Comment by Akram9** [comment]
I see. So if we try to make the image bigger, it looks awry?

**Comment by Krish2208** [comment]
Hello, it seems like this issue is still open.
If yes, can someone please look into my attempt to solve it?

![image](https://user-images.githubusercontent.com/32320437/160555703-cc8b8536-43ad-41ff-b5f7-ed0f26bf6b68.png)
Is this what we are looking for NoRH TimeSeries.

![image](https://user-images.githubusercontent.com/32320437/160555885-209f3015-e2f3-4f2c-9b99-b8a45d0fe324.png)
This from NoAA TimeSeries.

**Comment by nabobalis** [comment]
If that is what the sample data for both files look like, then its fine.
