### ISSUE TITLE
Remove some coordinate frames from transformation graph in docs?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2846]
Thanks to yours truly, it's now possible to create a custom coordinate transformation graph for documentation as of astropy 3.1: https://github.com/astropy/astropy/pull/7135

It might be nice to remove some of the non-solar physics coordinate systems in the current graph to make it more readable? Current graph is here: http://docs.sunpy.org/en/stable/code_ref/coordinates.html#module-sunpy.coordinates.transformations

**Comment by Cadair** [comment]
Sounds reasonable. We could have the full graph on a separate page and link to it maybe? Bonus points for adding a `other astropy coordinate frames` bubble with a link to the graph!!
