### ISSUE TITLE
Our Installing the Development Version of SunPy needs updating

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2848]
See here: http://docs.sunpy.org/en/stable/guide/installation/advanced.html#installing-the-development-version-of-sunpy this should recommend using pip and probably using the `pip install -e` method.

**Comment by Akram9** [comment]
Hey, can I contribute to this as my first PR?

**Comment by nabobalis** [comment]
Sorry @Akram9, I am already in the process of tackling this.

**Comment by Akram9** [comment]
Okay, no problem. I didn't quite get the 'assigned'  mark and therefore asked before pushing. Thanks anyway!

**Comment by nabobalis** [comment]
Yeah we normally do not enforce those or use those. But since I was in the process of doing it, I thought I would tag myself in several issues.

**Comment by Cubostar** [comment]
Is this still an issue?
