### ISSUE TITLE
Narrative documentation, one sentence per line

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2849]
I personally am not a fan that we break up sentences in our rst files. 
Not only do we break sentences in nearly random places, any change made makes the diff much larger than it needs to be.

Thus I am suggesting we move to one sentence per line in all our RST files and **only** the RST files. 

However, I probably should ask first before I butcher all the RST files.

**Comment by Cadair** [comment]
I could get on board with this.

**Comment by dstansby** [comment]
I'm 👍 for this if someone wants to put in a PR to update everything... that we should do this is already documented in our developer docs.

**Comment by dpshelio** [comment]
This [pre-pep thread about OSPL](https://discuss.python.org/t/one-sentence-per-line-for-peps-and-more/13920) and the [one above Semantic Line Breaks](https://discuss.python.org/t/semantic-line-breaks/13874) are quite interesting. I'm happy to keep it OSPL, but I'd wish there's a way to lint the RST files automatically into that, so it's not such a manual work. I did it using [an emacs function](https://stackoverflow.com/a/41638368/1087595), but I had to be careful as various reStructuredText tags were converted incorrectly.

**Comment by wtbarnes** [comment]
Having a quick look through our narrative docs, it looks like we now adhere to this.

This is now codified in the developer docs: https://docs.sunpy.org/en/latest/dev_guide/contents/documentation.html#sunpy-specific-rules so I'm going to close this. If there are specific places where this is still not the case, I would suggest we open up specific issues to address that.
