### ISSUE TITLE
The `representation` keyword/property name is deprecated in favor of `representation_type` 

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2858]
Building the docs with astropy `3.1rc1` results in lots of warnings like:
```
WARNING: AstropyDeprecationWarning: The `representation` keyword/property name is deprecated in favor of `representation_type` [astropy.coordinates.baseframe]
```
I'm guessing fixing this just requires a keyword argument name change in some places.

**Comment by Cadair** [comment]
This should be fixed in rc2 it's an astropy bug.
