### ISSUE TITLE
The purpose of the HelioviewerClient

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2860]
This arose from #2801 and general chatting.

The Helioviewer [API is quite extensive](https://api.helioviewer.org/docs/v2/) and the question arises, what do we want to support directly with our Client. What we support ties in directly with what we want our Clients purpose to be.

In my eyes we do not want to support the entire API as I think that is too much work and expands the scope of our Client too far.

I would be in favour of `getDataSources`, to access the sourceIDs. 
Also, `getJP2Image` and `getJP2Header` (maybe we could combine in to one function on our side).
Note that we currently do not support the latter right now. 
None of the video stuff. 
Therefore the "purpose" of our Client would to be access the JPEG files and meta information for them only. Anything fancier would be either to the Java Client or the website. 

This would be less features than we currently offer as we also support `takeScreenshot` call currently.

**Comment by nabobalis** [comment]
One suggestion from @Cadair: 

I wonder if we want our api to facilitate people writing fancy clients in Python?
i.e. implement a low level wrapper for all the API but only expose a little bit of it through a user-facing API in SunPy.
Which could mean we do a GSOC project for a GUI to helioviewer.

**Comment by Naman9639** [comment]
That is a very good suggestion. It will not only let the user use the API to its full extent but will also implement data abstraction

**Comment by wafels** [comment]
How about removing all the helioviewer (HV) code from SunPy and making it an affiliated package?  I think the Helioviewer API is not really part of core SunPy.  Writing a Python client for the HV API would be the start of a helioviewer.org-like GUI in Python.

**Comment by wafels** [comment]
See also #2877

**Comment by Pac23** [comment]
> How about removing all the helioviewer (HV) code from SunPy and making it an affiliated package? I think the Helioviewer API is not really part of core SunPy. Writing a Python client for the HV API would be the start of a helioviewer.org-like GUI in Python.

came across this on the gsoc page what i propose is making a pypi package of the api which anyone across the orgs,projects can import.

**Comment by nabobalis** [comment]
I believe that is the goal of the GSoC project.

**Comment by Pac23** [comment]
> I believe that is the goal of the GSoC project.

@nabobalis is there a IM or google group of sunpy ?

**Comment by nabobalis** [comment]
Both. https://chat.openastronomy.org/#/room/#sunpy:openastronomy.org
and https://groups.google.com/forum/#!forum/sunpy

**Comment by wafels** [comment]
After the discussion this week, some further ideas cropped up.

1. Remove the helioviewer client from SunPy entirely and make it its own package as suggested above.
2. Extend Fido to use the helioviewer API so it is possible to search for and download helioviewer JP2 files.
3. Maintain the ability of SunPy to read a JP2 file into a map object.

Idea 3 is an example of the notion that SunPy provides support for the reading of data in different formats **with the purpose** of representing that data in a SunPy object.

**Comment by Mihan786Chistie** [comment]
Hello, can I know the new Helioviewer repository? Is it https://github.com/Helioviewer-Project/api

**Comment by nabobalis** [comment]
> Hello, can I know the new Helioviewer repository? Is it [Helioviewer-Project/api](https://github.com/Helioviewer-Project/api)

I don't think one has been created yet. That repository I think is for the full API.

**Comment by dstansby** [comment]
Is this issue redundant now `hvpy` exists?

**Comment by nabobalis** [comment]
Yes
