### ISSUE TITLE
Increase visibility of differential rotation code in docs

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2864]
We had a report of people not knowing we had it.

**Comment by Cadair** [comment]
I am not entirely sure how we would go about doing this, it's very easy to search for and only one click into `sunpy.physics` away to the API docs. Maybe adding it to the user guide?

**Comment by wtbarnes** [comment]
Duplicate of #2565

**Comment by wtbarnes** [comment]
See also #2600

**Comment by nabobalis** [comment]
Closed in favour of #2565
