### ISSUE TITLE
Potential issues with differential rotation

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2868]
As was pointed out here https://github.com/sunpy/sunpy/pull/2706#issuecomment-409919240 there are some issues with our differential rotation implementation.

@wafels is working on updates to the differential rotation code which better handles observer positions, we should make sure those changes correct these discrepancies.

**Comment by wafels** [comment]
See https://github.com/wafels/sunpy/tree/fixsolarrotatecoordinate
