### ISSUE TITLE
Map does not support saving masks in FITS

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#2870]
Some details:

You would need to write to a new HDU for the FITS file.
The biggest issue is that `map_factory` can't handle combining FITS HDUs at the moment as it assumes a strict 1:1 HDU<> Map arrangement.

Changing this is a complex task and not for someone new to SunPy.

**Comment by Naman9639** [comment]
@wtbarnes I would like to work on this issue.

**Comment by nabobalis** [comment]
@Naman9639 Having spoken to some people, this is not a task that is straightforward and requires some good knowledge of how FITS files work and how `map_factory` works.

**Comment by Cadair** [comment]
Yeah the biggest issue here is that `MapFactory` currently has no way of combining different HDUs in the FITS file into one Map. It assumes that each HDU corresponds to a separate Map, changing that would require a fair bit of design work.

**Comment by Naman9639** [comment]
Oh ok

**Comment by dstansby** [comment]
Is there any 'official' way of storing a mask within a FITS file? A quick search of the FITS standard for 'mask' didn't return any results for me.

**Comment by kakirastern** [comment]
@dstansby How about using `astropy`'s `NDData` as a data structure?: https://docs.astropy.org/en/stable/nddata/nddata.html

**Comment by kakirastern** [comment]
Drawback is you will have to convert between the `FITS` and `NDData` formats though.

**Comment by wtbarnes** [comment]
No, I think you would have to store it as a separate image in the FITS file and then know, a priori, that that file had a separate image and then reconstruct the mask from that. I don't really see how to reasonably resolve this and it feels outside the scope of sunpy so as the author of the issue I'm fine with closing it.

**Comment by kakirastern** [comment]
Yeah, just needed to add one extra extension to the FITS file in fact if I remember correctly in the multi-extension FITS file format?: https://www.stsci.edu/itt/review/dhb_2011/Intro/intro_ch23.html
