### ISSUE TITLE
Accessing the Helioviewer sourceid with fewer keywords.

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2878]
Currently for the Helioviewer Client, two functions (`get_closest_image` and `download_jp2`) need you to specify 4 keywords to access the `source_id` dictionary. These are `observatory=None, instrument=None, detector=None, measurement=None`.

We want to be able to support a user submitting say two keywords like for example, `observatory=SDO, measurement=171` or `instrument=AIA, measurement=171`.
This is enough information in theory to get the right source_id for **most** of them.
If it can not, it should through a nice error.   

Any change would be inside our functions. This is not related to the API of Helioviewer.
Ideally where we directly index the dictionary for the `source_id`, we would replace that part with something much smarter. What? I don't know.

**Comment by pulkitsapra** [comment]
Hi Can i take this issue?

**Comment by nabobalis** [comment]
Sure. This issue partly depends on the currently open pull request #2280.  You will want to check the current structure of the source of dictionary.

I do think this problem is generic and the solution could become a function we call.

**Comment by darthgera123** [comment]
are there any preset values for the different constants?

**Comment by Naman9639** [comment]
I wish to work on this issue

**Comment by nabobalis** [comment]
Ok.

**Comment by Naman9639** [comment]
I just wanted to know that we want to access the dictionary using partial key right?

**Comment by nabobalis** [comment]
Yes.

**Comment by Naman9639** [comment]
Ok
