### ISSUE TITLE
Crash while saving sunpy Map if it has comments

### ISSUE THREAD

**Issue by harshmathur1990** [sunpy/sunpy#2879]
### Description
If a level1 fits file has comments in it, then to make it level 1.5, aiaprep is invoked, then saving the resultant Map will lead to crash throwing Value Error

### Expected behavior
The save method should run normally and save the map in FITS file.

### Actual behavior
The Map save method threw Value Error

### Steps to Reproduce

1. Download hmi.ic_nolimbdark_720s.20151217_000000_TAI.1.continuum.fits HMI 720 s Limb Darkening corrected fits file, for the given date (the fits file has comments).
2. ```fits_hdu = fits.open('hmi.ic_nolimbdark_720s.20151217_000000_TAI.1.continuum.fits')[1]```
3. ```fits_hdu.verify('fix')```
4. ```fits_hdu.header['HGLN_OBS'] = 0.0```
4. ```aia_map = sunpy.map.Map(fits_hdu.data,fits_hdu.header)```
5. ```aia_map = aiaprep(aia_map)```
6. ```aia_map.save('aiaprep/hmi.ic_nolimbdark_720s.20151217_000000_TAI.1.continuum.fits')```

### System Details

  - SunPy Version: 0.9.3
  - Python Version: 3.7.0
  - OS information: macOS Mojave

**Comment by Cadair** [comment]
Can you link or upload an example FITS file?

**Comment by harshmathur1990** [comment]
> Can you link or upload an example FITS file?

Here it is:
https://drive.google.com/open?id=1au7whkAVUBNHhl-ccRxbwDmKUG2czXiO

**Comment by nabobalis** [comment]
So if happens if you `aiaprep` the file first? 

If I open and then just save out the supplied file, we seem to have no issues with `Map.save`.
