### ISSUE TITLE
Add support for HCI and other coordinate systems In Franz & Harper (2002)

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2896]
See here for the details of the frames we want to add: http://jsoc.stanford.edu/doc/keywords/coordinates/Franz_Harper_2002.pdf

This requires understanding what a coordinate system is and the mathematics behind it.
Also how they are implemented in [Astropy.](http://docs.astropy.org/en/latest/api/astropy.coordinates.BaseCoordinateFrame.html)

The list of heliographic systems in Franz&Harper is:

3.2 Heliographic systems
- [x]  HGC (HelioGraphic Coordinates)
- [x] HEE (Heliocentric Earth Ecliptic)
- [x] HEEQ (Heliocentric Earth EQuatorial)
- [x] HCI (HelioCentric Inertial)

**Comment by darthgera123** [comment]
i would like to help with this issue. Please guide

**Comment by nabobalis** [comment]
This involves firstly reading the paper and understanding the mathematics of the coordinate frames and how they relate to other frames.

I would suggest that you try to focus on the issue you are already tackling.

**Comment by Cadair** [comment]
Yes that makes sense.

**Comment by dstansby** [comment]
The list of heliographic systems in Franz&Harper is:

3.2 Heliographic systems
- [ ]  HGC (HelioGraphic Coordinates)
- [ ] HEE (Heliocentric Earth Ecliptic)
- [ ] HEEQ (Heliocentric Earth EQuatorial)
- [ ] HCI (HelioCentric Inertial)

**Comment by ayshih** [comment]
I added a page to the wiki that lists where we stand on the primary coordinate systems from Thompson (2006) and Franz & Harper (2002).

https://github.com/sunpy/sunpy/wiki/Coordinate-systems

**Comment by ayshih** [comment]
Closing

HGC is already covered by `HeliographicCarrington`, HEEQ is already covered by `HeliographicStonyhurst` (in Cartesian representation), and HEE and HCI were added in #3212.
