### ISSUE TITLE
Tighter definition of the bottom left and top right coordinate map properties required?

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2908]
### Description

Map provides the bottom left and top right coordinates as properties. The issue is that the meaning of the positions described by these coordinates is not obvious.

### Expected behavior

The expected behavior is that the meaning of these coordinates is consistent.

### Actual behavior

It appears that map.bottom_left_coord is the position of the lower left hand vertex of that pixel, and map.top_right_coord is the position of the upper right hand vertex of that pixel.  Therefore the positions that these coordinates refer to are different relative to the pixel.  This is not explicit to the user.  There may be an implicit assumption that these positions define the extent of the map in the world.

### Steps to Reproduce

```
import numpy as np
import sunpy.data.test 
import sunpy.map
import os
import astropy.units as u

testpath = sunpy.data.test.rootdir

m = sunpy.map.Map((os.path.join(testpath, 'aia_171_level1.fits')))
m_bl = m.bottom_left_coord
m_tr = m.top_right_coord

x, y = np.meshgrid(*[np.arange(v.value) for v in m.dimensions]) * u.pix
ac = m.pixel_to_world(x, y)

ac_bl = np.nanmin(ac.Tx.value), np.nanmin(ac.Ty.value)
ac_tr = np.nanmax(ac.Tx.value), np.nanmax(ac.Ty.value)

print(m_bl, ac_bl)
print(m_tr, ac_tr)
```

### System Details

==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
System : Darwin
Processor : i386
Arch : 64bit
SunPy : 1.0.0.dev10506
SunPy_git : 10a1729ebc2c9acce33c849fe531e547a359b5fe
OS: Mac OS X 10.13.6 (i386)

###########
 Required Libraries 
###########
Python: 3.6.8
NumPy: 1.15.4
SciPy: 1.1.0
matplotlib: 3.0.2
Astropy: 3.1.1
Pandas: 0.23.4

###########
 Recommended Libraries 
###########
beautifulsoup: 4.6.3
PyQt: NOT INSTALLED
Zeep: NOT INSTALLED
Sqlalchemy: 1.2.15

**Comment by Cadair** [comment]
Hmmm. I thought all the pixel references should be centre of the pixel. I will investigate.

**Comment by wafels** [comment]
From the FITS paper -  "Coordinate values normally correspond to the center of all pixels (see Sect. 8.2);".  If that is the case then going in any axis there should be 127 pixels between centers and 1/2 pixel on either side to get the full extent of the test image.

**Comment by Cadair** [comment]
As @ehsteve has discovered, this also manifests as a half-pixel out error in `map.plot` when not using `WCSAxes`.

**Comment by wafels** [comment]
Just to record this, is the solution to change the map extent calculation?

**Comment by Cadair** [comment]
I think if we fix the top_right bottom_left hopefully extent will fall into line?
