### ISSUE TITLE
Spectrogram log y axis

### ISSUE THREAD

**Issue by segfaulthunter** [sunpy/sunpy#291]

**Comment by tdwilkinson** [comment]
Hello, I am attempting this as part of GSOC. The spectrogram class in spectrogram.py has a plot definition. I am wondering if adding logy=False as a keyword to this definition would suffice. Then, this could be added:
	if ylog:
		axes.set_yscale('log')
I am working to test this. Though, I am wondering if this would actually need to be implemented like the linear keyword, that 'stretches' the image to make the frequency axis linear. In this case, it would 'stretch' the frequency axis to be log scale, and would need more code than what's above. Thoughts?

**Comment by wafels** [comment]
Tessa,

I cobbled together some code to plot 2d images with logarithmic x and y
axes.  It can be found here:

https://github.com/wafels/rednoise/blob/perpixel/py/aia/analysis_3d_fft.py

with the most relevant lines highlighted here:

https://github.com/wafels/rednoise/blob/perpixel/py/aia/analysis_3d_fft.py#L236-L260

Hope this helps,

Jack

**Comment by dpshelio** [comment]
This issue was moved to sunpy/spectra#10
