### ISSUE TITLE
Support Observer Location and other Properties on Astropy WCS objects

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2910]
In Astropy 3.1 new APIs were added to `astropy.wcs.WCS` [1] these APIs (specifically for the context of the rest of this issue, `WCS.pixel_to_world`) make use of the existing [`wcs_to_celestial_frame`](https://github.com/astropy/astropy/blob/master/astropy/wcs/utils.py#L178) functionality in Astropy, which SunPy [extends](https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/wcs_utils.py) to convert from a `WCS` object to a coordinate frame.

These functions work by extracting information from the underlying `WCS.wcs` structure (which is implemented in `wcslib` at the C level). However, this structure does not extract the keys that are specified in [Thompson (2006) [Section 9.1]](https://ui.adsabs.harvard.edu/#abs/2006A&A...449..791T) to determine the observer location (normally `DSUN_OBS`, `HGLN_OBS`, and `HGLT_OBS`). In addition to this it is often required to extract the expected radius of the sun in meters to correctly specify the transform from the helioprojective to the heliocentric coordinate system [2]. Without these extra pieces of metadata any transformation out of the coordinate system described by the `WCS` object will be inaccurate, or flatly wrong.

SunPy currently works around this issue in `sunpy.map` by attaching [extra attributes](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L274) to the `WCS` returned by the `GenericMap` object, specifically `observer_coordinate` and `rsun`, which [`wcs_to_celestial_frame`](https://github.com/astropy/astropy/blob/master/astropy/wcs/utils.py#L178) uses when constructing the relevant coordinate frame object for the wcs. This is clearly sub-optimal for `WCS` objects created outside of `GenericMap` and is a hack at best.

The best solution to this issue would be to have `wcslib` support the `*_OBS` keywords in the wcs struct and therefore expose them to our `wcs_to_celestial_frame` function. This would require contacting Mark Calabretta (the maintainer of wcslib) and proposing this to him, something I have yet to do.

I do not have a clear picture of what workarounds we could implement in the short term to mitigate this issue without having modifications made in `wcslib`. I am open to suggestions, although I would *really* like to refrain from having to subclass `astropy.wcs.WCS`.

---

[1] http://docs.astropy.org/en/stable/wcs/wcsapi.html#wcsapi
[2] When the helioprojective system is only two dimensional and the distance dimension has to be calculated by assuming position on a sphere of given radius.

**Comment by Cadair** [comment]
wcslib 7.1 has the changes required to address this, see #3643 and astropy/astropy#9829

**Comment by dstansby** [comment]
Does this mean we need to wait for depending on astropy 4.0 to fix this issue?

**Comment by astrofrog** [comment]
https://github.com/astropy/astropy/pull/10333 adds support for accessing the solar parameters, please try it out! :)
