### ISSUE TITLE
Timeseries should encourage users to not use .data to get a dataframe

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2917]
Given that we generally want the Timeseries API to not be tied to any particular timeseries data structure, i.e pandas or Astropy Timeseries. Users should be using `to_dataframe` rather than `.data`.

**Comment by Cadair** [comment]
I propose that we deprecate `.data` and encourage people to use `to_dataframe`

**Comment by sashank27** [comment]
Hi! @nabobalis I would like to work on this. Please guide me accordingly.

**Comment by sashank27** [comment]
@dstansby @Cadair could you give more insight on this? Currently `to_dataframe` returns just `.data`.
Do I need to modify `to_dataframe` so as to convert raw data to a Pandas dataframe? Or anything else?

**Comment by dstansby** [comment]
It looks like we need to add a `.data` property, with a setter and getter, and to raise a deprecation warning when `.data` is accessed (which tells the user to use `.to_dataframe()` instead.
