### ISSUE TITLE
Add section to developer docs on running figure tests

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2925]
It's not obvious to me how to run all the figure tests; I guessed from https://docs.sunpy.org/en/latest/dev_guide/tests.html#running-unit-tests that maybe it was
```
py.test -k figure
```
but they're all skipped if I run this and I'm not sure how to get them to run.

**Comment by nabobalis** [comment]
The command should be `pytest -m "figure"` to run only the figure tests. 

I will fix this in my doc-wip.
