### ISSUE TITLE
Convert sunpy/sun/models.py to using astropy tables

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#2933]
Currently importing `sunpy.sun.models` raises the following pandas warnings:
```python
import sunpy.sun.models
/Users/dstansby/github/sunpy/sunpy/sun/models.py:63: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  'temperature': Quantity(1e6, 'K'), 'density': Quantity(1, 'g cm**-3')}
/Users/dstansby/github/sunpy/sunpy/sun/models.py:91: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  'central temperature': Quantity(1e6, 'K'), 'time': Quantity(1e9, 'year')}
```
due to e.g. the following line of code:
```python
evolution.units = {'radius': con.radius, 'luminosity': con.luminosity,
                   'central temperature': Quantity(1e6, 'K'), 'time': Quantity(1e9, 'year')}
```
where `evolution` is a DataFrame. I'm guessing the way to fix this is changing `models.py` to using astropy tables instead of pandas DataFrames.

See documentation of Astropy tables: http://docs.astropy.org/en/stable/table/index.html.
We probably want to use QTable instead of a normal Table.

**Comment by darthgera123** [comment]
i would like to work on this issue

**Comment by nabobalis** [comment]
You don't need to ask for permission to tackle any issue. But again, I would focus on ones you are already doing instead of trying to find other issues.

**Comment by AbhigyanBose** [comment]
I was looking into this, I understand how to change the DataFrames into astropy Tables.
The only part I don't understand is how to implement IndexSlicing of DataFrames in astropy Table or is it not important to implement it?

**Comment by nabobalis** [comment]
Sorry, I am not sure I quite follow.

**Comment by AbhigyanBose** [comment]
Given this DataFrame
`l1 = [1, 2, 3]
l2 = [4, 5, 6]
d = pandas.DataFrame({'coloumn 1':l1, 'coloumn 2':l2})`
How do I implement this type of indexing using astropy Tables ?
`print(d[0:2])`
Output:
`   coloumn 1  coloumn 2
0          1          4
1          2          5
`

**Comment by nabobalis** [comment]
I am not sure if you need to implement that kind of indexing. We probably need to figure out how to create the table from scratch the proper way.
