### ISSUE TITLE
No module named 'zeep'

### ISSUE THREAD

**Issue by AdityaSanthosh** [sunpy/sunpy#2935]
### Description
Testing Sunpy

### Actual behavior
![87cf638f-a6f9-4917-9515-bdcfec7f43f0 png](https://user-images.githubusercontent.com/45935479/52908251-d36b8400-3297-11e9-89bb-d0d6abc4e372.jpg)

### Steps to Reproduce
Paste the following code in terminal after installing Sun-
```
import sunpy
sunpy.self_test(online=False)
```
### System Details
 **General**
Time : Sunday, 17. February 2019 04:00AM UT
System : Windows
Processor : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
Arch : 64bit
SunPy : 1.0.dev10560
SunPy_git : 7a4f3257b460774040b266b6866e497980af1f30
OS: Windows 10 10.0.17763 (Intel64 Family 6 Model 142 Stepping 9, GenuineIntel)
  - SunPy Version: 1.0.dev10560
  - Python Version:3.6.6

**Comment by nabobalis** [comment]
Hello.  To run the tests currently you need to install all the extra packages. 

If you do pip install -e .[dev] it should install them. We have yet to update the readme about it.
