### ISSUE TITLE
Mapbase should convert crln_obs to hgln_obs if it is found in the header

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2942]
This specifically applies to HMI data which uses crln/t_obs rather than hgln/t

**Comment by Akram9** [comment]
Hey, can you help me solve this?

**Comment by nabobalis** [comment]
I am not 100% sure but you would need to add a check for `crln_obs` within the `sunpy.map.Map` meta dictionary and convert that into the key for `hgln_obs` within the meta dictionary.

Since this seems to apply only to HMI, this should be in the hmi source file and not in the generic mapbase file.

**Comment by Cadair** [comment]
Hi @Akram9 

To get started, it would be worth having a quick read of the paper on [Solar Coordinatees(https://www.aanda.org/component/article?access=bibcode&bibcode=&bibcode=2006A%2526A...449..791TFUL) just for a little background.

The Carrington coordinate system (in the header as crln and crlt) is the same as the stonyhurst system (in the header as hgln and hglt) except that the longitude (ln) is offset by a time dependant angle. So what needs to happen is that in mapbase in the [`heliographic_longitude`](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L609) property if the `hgln_obs` key is not present but the `crln_obs` key is the `crln_obs` should be converted to `hgln_obs` by getting the offset from the [`get_sun_L0`](https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/ephemeris.py#L107) function given the time from the map.

**Comment by Akram9** [comment]
Thanks, I'll check into these.

**Comment by Akram9** [comment]
@Cadair : So if I understand it right,  what you are saying is to change the first `if` condition checking the presence of `hgln_obs`, and if `crln_obs` is found, convert it to `hgln_obs`, right?

**Comment by Cadair** [comment]
What I mean is that after [this](https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L613) if statement there should be one that checks for `crln_obs`.

**Comment by Akram9** [comment]
So it needs to be something like:
`if heliographic_longitude is None:
     carrington_longitude = self.meta.get('crln_obs', None)
     if carrington_longitude is None:`

And then the change `crln_obs` to `hgln_obs` by getting the offset out of the last `if` block.
Is this good?

**Comment by Akram9** [comment]
I mean, the code should be like:


if heliographic_longitude is None:
    carrington_longitude = self.meta.get('crln_obs', None)
    if carrington_longitude is None:


*couldn't get it into the block properly

**Comment by Akram9** [comment]
* I am not able to get the tabs in the code block

**Comment by Akram9** [comment]
`if heliographic_longitude is None:`
`<tab> carrington_longitude = self.meta.get('crln_obs', None)`
`<tab> if carrington_longitude is None:`

**Comment by dodoextinct** [comment]
Hey, I was going through the issue. I did the following change. Is it okay?

`if heliographic_longitude is None:
            if self.meta.get('crln_obs', None) in not None:
                heliographic_longitude = self.meta.get('crln_obs', None) - get_sun_L0()`

[https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L609](here)

**Comment by Cadair** [comment]
Only one of you can patch this :stuck_out_tongue: 

You are clearly both understanding it. Check one then check the other, return the Stonyhurst one.

@dodoextinct your example is nearly complete but `get_sun_L0` needs to take the time from the map (I think it's the `.date` property). Also I can't remember off the top of my head if it's `+` or a `-`.

**Comment by Akram9** [comment]
Well, personally I'd like @dodoextinct's way to what I was thinking.

**Comment by dodoextinct** [comment]
> Only one of you can patch this 
> 
> You are clearly both understanding it. Check one then check the other, return the Stonyhurst one, raise the warning if you can't get either.
> 
> @dodoextinct your example is nearly complete but `get_sun_L0` needs to take the time from the map (I think it's the `.date` property). Also I can't remember off the top of my head if it's `+` or a `-`.

I have updtaed the code like this.
`if heliographic_longitude is None:
            if self.meta.get('crln_obs', None) is not None:
                heliographic_longitude = self.meta.get('crln_obs', None) - get_sun_L0(self.date)
            else:
                if self._default_heliographic_longitude is None:
                    warnings.warn_explicit(
                        "Missing metadata for heliographic longitude: "
                        "assuming longitude of 0 degrees",
                        Warning, __file__,
                        inspect.currentframe().f_back.f_lineno)
                    self._default_heliographic_longitude = 0
                heliographic_longitude = self._default_heliographic_longitude`

Also, Stonyhurst longitude and Carrington longitude are related by the equation,

Carrington longitude = Stonyhurst longitude + Carrington longitude of the central meridian
as seen from Earth

Therefore, Stonyhurst longitude = Carrington longitude - Carrington longitude of the central meridian
as seen from Earth.
ref[http://www.mssl.ucl.ac.uk/grid/iau/extra/local_copy/coordinates.pdf]

**Comment by Cadair** [comment]
:+1: looks good, open a PR!

(Also I edited your comment to use ` ``` ` for a block of code :smile: )
