### ISSUE TITLE
Improve our warnings in line with PEP 565

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2945]
See astropy/astropy#8465

**Comment by cquark7** [comment]
Hi @Cadair, I want to work on this issue. Please guide me on what changes are required to make warnigs [pep 565](https://www.python.org/dev/peps/pep-0565/) compliant in sunpy. I understand that for Python < 3.7 custom warning class should derive from `FutureWarning`. Do I have to make those changes in [exceptions.py](https://github.com/sunpy/sunpy/blob/master/sunpy/util/exceptions.py)?
Also, it seems like some Astropy contributors are not in favor of making this change, what's your take on this?

**Comment by nabobalis** [comment]
Yes, they are against that and we will probably also not follow suit. At least for now. 

What we do need to do is make sure that our `SunpyDeprecationWarning` subclasses `DeprecationWarning` in the same style that `SunpyUserWarning` does.

**Comment by cquark7** [comment]
Thanks for clarifying @nabobalis. Does that mean I shouldn't work on this issue (because no changes are required)?

**Comment by nabobalis** [comment]
Well there is a one line change we need that I mentioned in my comment but otherwise, yeah this issue could be closed.
