### ISSUE TITLE
HEC still thinks parse_time returns a datetime object.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2964]
```
sunpy/net/helio/hec.py in time_query(self, start_time, end_time, table, max_records)
111 start_time = parse_time(start_time)
112 end_time = parse_time(end_time)
--> 113 results = self.hec_client.service.TimeQuery(STARTTIME=start_time.isoformat(),
```

instead of `isoformat()` it should read `.isot`

**Comment by Cadair** [comment]
We should also add tests for this code path, because it clearly dosen't have any at the moment.

**Comment by AbhigyanBose** [comment]
Changing `start_time.isoformat()` to `start_time.isot` results in an Error
`TypeError: 'str' object is not callable`

I checked and after parsing `start_time.isot` returns the time without any error.

**Comment by cquark7** [comment]
I'm able to reproduce this bug. Astropy Time object doesn't have any attribute named `isoformat()`, although there are a number of Time attributes/formats available, `isot` is one of them:
```
list(Time.FORMATS)
['jd', 'mjd', 'decimalyear', 'unix', 'cxcsec', 'gps', 'plot_date',
'datetime', 'iso', 'isot', 'yday', 'datetime64', 'fits', 'byear',
'jyear', 'byear_str', 'jyear_str']
```
When I accessed `isot` attribute of Astropy Time object it produced a result like this:
`2005-12-03T00:00:00.000`

I'll need your help to write a test for this.

**Comment by nabobalis** [comment]
> Changing `start_time.isoformat()` to `start_time.isot` results in an Error
> `TypeError: 'str' object is not callable`
> 
> I checked and after parsing `start_time.isot` returns the time without any error.

Yes `.isot` only exists on the `astropy.time.Time` object and not the string. 

> I'm able to reproduce this bug. Astropy Time object doesn't have any attribute named `isoformat()`, although there are a number of Time attributes/formats available, `isot` is one of them:
> 
> ```
> list(Time.FORMATS)
> ['jd', 'mjd', 'decimalyear', 'unix', 'cxcsec', 'gps', 'plot_date',
> 'datetime', 'iso', 'isot', 'yday', 'datetime64', 'fits', 'byear',
> 'jyear', 'byear_str', 'jyear_str']
> ```
> When I accessed `isot` attribute of Astropy Time object it produced a result like this:
> `2005-12-03T00:00:00.000`
> 
> I'll need some guidance to write a test for this.

The first test would be just to write some tests for the `hec` code.
