### ISSUE TITLE
Increase test coverage of sunpy.net.{hek,hek2vso,helio}

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2970]
These three net submodules (hek, hek2vso, helio) need more tests written for them.

Coverage at time of writing:

* HEK: [14.85%](https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/net/hek)
* HEK2VSO: [55.38%](https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/net/hek2vso)
* HELIO: [46.15%](https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/net/helio), this is for the client file.

Also these tests should be moved to the correct folders as well.

**Comment by cquark7** [comment]
There is no test written for [net/helio/hec.py](https://github.com/sunpy/sunpy/blob/master/sunpy/net/helio/hec.py)'s function `votable_handler(xml_table)` in [net/tests/test_helio.py](https://github.com/sunpy/sunpy/blob/master/sunpy/net/tests/test_helio.py), but codecov shows those lines in green [hec.py - 46.15%](https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/net/helio/hec.py).  Why is that? 

What should I do if same remote data is required to write unit tests for multiple public functions? It would be inefficient to fetch that data inside every `test_functionName`.

**Comment by nabobalis** [comment]
It would seem to suggest that something is calling that code. I am not sure what code is doing it however. 

Are you fetching the same data each time? You could create one larger test. Otherwise, just write a test and add each one as remote-data.

**Comment by cquark7** [comment]
Zeep client is initialized by the URL of default wsdl file, that's why fetched data is same. This data is then being used in 3 different public functions (two of them are parameterless) for processing.

```python3
class HECClient(object):
    def __init__(self, link=None):
        if link is None:
            # The default wsdl file
            link = parser.wsdl_retriever()

    self.hec_client = zeep.Client(link)
```
I'm more concerned about writing *meaningful* tests for functions. It gets a bit tricky when the output of a parameterless function depends on user input. I think I have figured out how to do that.

**Comment by nabobalis** [comment]
I think for some of our other online tests, we just define client outside the tests and pass it into the tests when needed.

**Comment by jains8844** [comment]
Can I work on testing the hek2vso part ?

**Comment by nabobalis** [comment]
Sure.
