### ISSUE TITLE
No Fermi GBM Client for data download

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#2977]
### Description

In regards to using Fido for downloading data, there doesn't seem to be a FERMI GBM client for downloading data 

Is there a specific reason for this or is there scope to implement one?

**Comment by Cadair** [comment]
Well, this seems to be a glaring bug. We used to have the ability to download Fermi data back in 0.9 land through lightcurve. (https://github.com/sunpy/sunpy/blob/0.9/sunpy/lightcurve/sources/fermi_gbm.py#L97) it seems that it was never ported to Fido?

**Comment by hayesla** [comment]
I'll give this a shot

**Comment by aringlis** [comment]
@hayesla @Cadair Since we're fixing this anyway, it may be worth it to revise the client to allow the option of downloading Fermi CTIME files, as well as CSPEC files (and get rid of the re-binning of the CSPEC files while we're at it)...

**Comment by hayesla** [comment]
Yes am thinking of that too. Also I was thinking that the query should return all the detectors unless specified, does that make sense to do?

**Comment by aringlis** [comment]
@hayesla I'm not sure - it's not that likely that a (solar) user would want data from all the detectors simultaneously, given that ~half of them would show no solar emission.

**Comment by hayesla** [comment]
that's a good point, at them moment I've made a pull request for a client that downloads GBM data, with CSPEC or CTIME with the Datatype attrs, defaulting to CSPEC if none specified. It also allows you to choose you detector with the Detector attrs. If none is provided it downloads the n5 detector file as this is the detector that mostly points towards the Sun and the detector that is generally returned from the _get_closest_detector_for_date function from 0.9 lightcurve

Should we implement the detector calculation in the dataretriever source, or should this be done separately by the user so that they can then decide what file to download?
