### ISSUE TITLE
TimeSeries support for EVE/ESP level 1 data

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#2984]
### Description

Currently the timeseries source in timeseries.sources.eve.py only supports level 0CS data and cannot handle the eve_l1_esp fits files (which would be easy to implement) or the level 2 emission lines time series (see [#Issue 2407 ](https://github.com/sunpy/sunpy/issues/2407))

Should this be included in the eve.py source or a new source created for the different levels?
Would be nice to see timeseries being able to support this! :)

**Comment by aringlis** [comment]
Additionally, it may be that there is no value in the Level 0 data anymore once we are providing the Level 1 and Level 2 data instead...

**Comment by hayesla** [comment]
This has now been fixed with #3032
