### ISSUE TITLE
Create a DifferenceMap and DifferenceSequence class

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#3]
Create a DifferenceMap class which gets returned when one Map is subtracted from another.

Basic features could include:
- headers for im1 and im2
- start_date
- end_date
- duration (timedelta)
- grayscale color table

Also a more useful thing from my perspective is a difference sequence, that could be fed a difference map and then does running or from first frame differences.

**To do all of this we need coordinate aware differencing which we do not have currently inside maps, which requires we have a better WCS implementation**

**Comment by wafels** [comment]
Do we still need this?  Is this still important?

**Comment by Cadair** [comment]
Yes, but I think the best way to do it will be to implement addition and subtraction operators in `NDCube`. @DanRyanIrish

**Comment by wafels** [comment]
We used to have those, or we wanted them, back in the first days of map...

**Comment by ehsteve** [comment]
While waiting for NDCube can’t we provide a simple gallery example where we derotate Aia maps and subtract the data and create a new map?

**Comment by nabobalis** [comment]
I think we have a running or base difference example.

**Comment by dstansby** [comment]
Should this issue go up(down?)stream to NDCube?

**Comment by Cadair** [comment]
https://github.com/sunpy/ndcube/issues/74 is the related ndcube issue.

It's likely this wont get implemented until NDCube grows the underlying functionality, but I think we should also keep this open for pulling it into map when the time comes.

**Comment by wtbarnes** [comment]
I'm going to close this as (1) we have arithmetic operators on Map that allow one to easily compute differences between a map and another array (2) we have an example gallery entry that shows how to compute a difference map, and (3) we have no plans to implement a specific `DifferenceMap` class.
