### ISSUE TITLE
Tests should not make use of user config file

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3004]
### Description
Tests make use of the user provided config file but have hard coded dependencies on expectations from the default configuration. This is most easily seen in tests for time. Many tests are expecting a particular time format namely `%Y-%m-%d %H:%M:%S` but the user could have set that to another format. Those tests would then unexpectedly fail.  

### Expected behavior
I expected the tests to pass.

### Actual behavior
The tests failed.

### Steps to Reproduce
Change your default config time_format from `%Y-%m-%d %H:%M:%S` to `%Y-%m-%d %H:%M` and watch the tests fail.

**Comment by nabobalis** [comment]
Sure. Let me see if I can work around this.
