### ISSUE TITLE
Missing calculations for sunpy.sun functions

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#3021]
Three functions are missing the mathematics to calculate them.
These seem to be:

* longitude_Sun_perigee
* true_latitude 
* apparent_latitude

We need to track down what they need to calculate from sources and implement that.

**Comment by Cadair** [comment]
pinging @dpshelio and @ayshih on this I guess?

**Comment by vedang08** [comment]
Can I work on this issue @nabobalis ?

**Comment by nabobalis** [comment]
Err, probably not? Without a source of equations to implement, there is nothing to do until we get those first.
