### ISSUE TITLE
Automate uploading reference figures from master CI builds to figure repo

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3033]
Our reference images for the figure tests are stored in this repo: https://github.com/sunpy/sunpy-figure-tests

When we run a figure test build on master (currently run by circleCI) we should ensure that the figures stored in this repo are upto date.

This should be a simple bash script or similar that is run at the end of the circle build and uploads to the figure test repo with a ssh deploy key.

**Comment by nabobalis** [comment]
I think this was fixed.
