### ISSUE TITLE
Conversion from astrophysical coordinates to helio coordinate may not be correct

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3035]
It turns out that we have never really performed an accurate check on whether these transformations are actually correct. The only partial check that was performed was using eclipse images which included regulus. The limited accuracy of the ground-based photography did not allow for an accurate check.

**Comment by ayshih** [comment]
@ehsteve still needs to actually flesh out this bug report, but I believe I've nailed down the three reasons for the reported discrepancies:

- LASCO FITS headers do not have observer location (#3037)
- AIA FITS headers have inaccurate HGS coordinates (#3038)
- HPC coordinates need to factor in light travel time (#3039)

**Comment by ehsteve** [comment]
Here is an example using LASCO. One can see that the stars line up pretty well but are off by a few arcmin. This was done using a helioviewer JPG with the correct observer location added. There is the possibility that the plate scale is not appropriately corrected in this image.

[lasco_starfield.pdf](https://github.com/sunpy/sunpy/files/3107679/lasco_starfield.pdf)

**Comment by ehsteve** [comment]
The next step is to check using a STEREO coronagraph image whose header information is likely more correct and expertise exists here at Goddard to help with any potential calibration issues.

**Comment by ayshih** [comment]
I don't believe there is any evidence of any (more) flaws in the coordinate transformations, so I'm inclined to close this issue and track header/data-quality issues separately.
