### ISSUE TITLE
AIA FITS headers have inaccurate HGS coordinates

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3038]
AIA FITS headers apparently have inaccurate Heliographic Stonyhurst (HGS) coordinates (`HGLN_OBS` and `HGLT_OBS`).  For example, the distance from Earth center does not match the orbit radius.  We currently use these keywords to generate the `observer_coordinate` for an AIA map, so we provide an inaccurate observer location.

The headers also have Heliographic Aries Ecliptic (HAE) coordinates (`HAEX_OBS`, `HAEY_OBS`, and `HAEZ_OBS`), and the HAE coordinates are inconsistent with the HGS coordinates in the same header.  We have previously verified the accuracy of SunPy's transformation from HAE to HGS (e.g., https://github.com/sunpy/sunpy/issues/2445#issuecomment-364531159).   The HAE coordinates appear to be credible, and likely should be trusted over the HGS coordinates.

My recommendation is for `AIAMap` to override the generation of `observer_coordinate` to use the HAE coordinates.  Discuss.

**Comment by Cadair** [comment]
This feels like something we should get input on the AIA team from? @mbobra any suggestions on who we could talk to?

**Comment by ayshih** [comment]
To be clear, the level of discrepancy here is essentially negligible (<1 arcsecond) for typical uses of AIA data.  However, it becomes important when placing non-solar objects (e.g., Venus) relative to the Sun in helioprojective coordinates.  We'd have to talk either to someone who can check the SDO code that calculates `HGLN_OBS`/`HGLT_OBS` for the header or to someone who has analyzed their Venus-transit data to calibrate observatory pointing.

**Comment by ayshih** [comment]
I'll also note here that SunPy does not agree with the heliographic Carrington (HGC) coordinates in the AIA FITS header, regardless of whether transforming from the HGS coordinates in the header or from the HAE coordinates in the header.
