### ISSUE TITLE
HPC coordinates need to factor in light travel time

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3039]
Our coordinates code currently ignores any corrections due to light travel time when transforming into helioprojective coordinates (HPC).  It's often "okay" to ignore light travel time for typical observations of the Sun at a distance of 1 AU because in 8 minutes the Sun moves <~0.01 arcseconds in HPC.  However, there are times with light travel time is quite important, such as when determining the apparent position of a planetary body in HPC.

For comparison, Astropy's function `get_body()` – as opposed to Astropy's `get_body_barycentric()` and SunPy's `get_body_heliographic_stonyhurst()` – includes a correction for light travel time, but only for an Earth-based observer.  SunPy ought to have a generalized correction for an arbitrary observer location.

**Comment by Cadair** [comment]
Yeah I was thinking about this with regards to doing a direct HPC <> (H/I)CRS conversion the other day, I don't know if astropy has any helpers for this in ERFA.

**Comment by ayshih** [comment]
(I've edited the first post a little.)

I haven't looked for any helpers in Astropy's code, but given that their `get_body()` has an explicitly coded loop to converge on the corrected position for light travel time for an Earth-based observer, I doubt that they have something more general available elsewhere in their code base.
