### ISSUE TITLE
Cryptic error message when querying the HEK with a search that returns no results

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#3045]
### Description
Cryptic error message when querying the HEK with a search that returns no results.

### Expected behavior

Rise a more informative error message or return an empty HEKTable

### Actual behavior

Raises an unexpected error
```ValueError: Inconsistent data column lengths: set()```

### Steps to Reproduce

```
from sunpy.time import TimeRange
from sunpy.net import hek


client = hek.HEKClient()

tstart = '1985-05-03 00:00:00'
tend = '1985-05-04 00:00:00'

result = client.search(hek.attrs.Time(tstart, tend),
                       hek.attrs.EventType('FL'),
                       hek.attrs.OBS.Observatory == 'GOES')
```
### System Details

  - SunPy Version: sunpy-1.0.0.dev1274+gdc0c8cf4f.dist-info (I pip installed from master)
  - Python Version: 3.6.3
  - OS information: macOS 10.14.3

**Comment by samaloney** [comment]
I'll have a go at fixing this one should be pretty straight forward. Any preferences on:
a) raising a meaningful exception or
b) returning an empty HEKTable if that's possible?

**Comment by nabobalis** [comment]
I would go with returning an empty table, I think if Fido does not find anything, it just returns an empty response. I feel we should do the same.
