### ISSUE TITLE
Is there any preparation functionalities that sunpy offers? for example, EIT_prep for EIT .fits images. These are important and would save a lot of time working with these images.

### ISSUE THREAD

**Issue by MjdMahasneh** [sunpy/sunpy#3051]

**Comment by nabobalis** [comment]
Hi @MjdMahasneh, the only one we provide is one for SDO/AIA and SDO/HMI. 

I do not think we plan to provide Python versions of those, sorry about that!

**Comment by MjdMahasneh** [comment]
@nabobalis that's fine, thank you for your response. could you kindly point me to the name of these routines (for AIA and HMI) so that i can refer to them in the documentation?

**Comment by nabobalis** [comment]
I think the function is under `sunpy.instr.aia.aia_prep` and I recall it does or at least should work on HMI.

**Comment by MjdMahasneh** [comment]
Thank you again @nabobalis , one last question that might be out of the context, is there any documentation of how the raw .fits images are mapped into colored images? for instance, EIT 171 has a blue color (and in RGB format) while in reality these should be monochrome as they are acquired using a single wavelength. 

my question is : is there any documentation on the coloring process for EIT or AIA images?

**Comment by nabobalis** [comment]
I don't know myself or where that information would be.

I would assume that they just take the monochrome values and make them onto a blue space, like how matplotlib allows you to just use a blue colourmap when you call imshow. 

If any extra RGB information is added, I assume it would be non useful information but maybe it had to be formatted into a RGB context for something else, maybe you could overlap images with alpha values.

**Comment by MjdMahasneh** [comment]
@nabobalis The images are mapped into 3 channels (RGB) using some transformation, I will have to look more into this. I will elaborate here if I managed to find anything, it might be useful to someone. 

Thank you very much for your help and time, its very much appreciated.

**Comment by nabobalis** [comment]
Sure but the RGB conversion can be quite simple to do in theory. 

E.g (from stackoverflow):
```python
from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
data[256, 256] = [255, 0, 0]
img = Image.fromarray(data, 'RGB')
img.save('my.png')
img.show()
```
