### ISSUE TITLE
HMI FITS headers may not have accurate observer coordinates

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3057]
HMI FITS headers appear to have only heliographic Carrington (HGC) coordinates for the observer (SDO).  These appear to correspond very closely with the HGC coordinates in AIA FITS headers at the same time.  However, SunPy does not agree with the HGC longitude in the AIA FITS header at the level of arcminutes (see #3038), and part of the discrepancy is likely due to a slightly different definition of HGC longitude (see #2224).

Because the observer location for AIA files is determined using other coordinates than the HGC coordinates, it currently will not match the observer location for HMI files.

**Comment by Cadair** [comment]
I assume HMI dosen't have the same headers as AIA for the other observer coordinates?

**Comment by ayshih** [comment]
Here's a super-relevant comment from the HMI folks: https://github.com/sunpy/sunpy/issues/3735#issuecomment-582487046

**Comment by wtbarnes** [comment]
We can close this right? If I recall, this was addressed by the HMI team.

**Comment by wtbarnes** [comment]
I'm going to close this issue for the reasons stated above. Feel free to reopen if there's something we still haven't resolved.
