### ISSUE TITLE
Not reading correct time for all SOHO data for Level 0 data

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3070]
### Description

The SOHO clock drifts over time and that drift is not accounted for in the standard `DATE-OBS` fits header. The correct time is available in the FITS header under a `COMMENT` field.

**Comment by Cadair** [comment]
(ﾉ≧∇≦)ﾉ ﾐ ┸━┸

**Comment by dpshelio** [comment]
Does this apply to every instrument? Do all level-0 files have such comment? Do they follow the same date format? So many questions... (including, do I need to re-analyse the data from my Phd?)

**Comment by ehsteve** [comment]
FYI, I anecdotally heard that this may not be a problem anymore. We really need someone that is very familiar with SOHO data to chime in here.

**Comment by sudozer** [comment]
Let me touch base with some of our ESA people and see if we can at least get a better understanding of what the situation here is.  Stay tuned.

**Comment by jhourcle** [comment]
the VSO is using the times from ESA's 'SOHOCAT' data catalog ... and I have confirmed that the EIT L0 data in there is *uncorrected*.  I suspect that it would be true for all SOHO L0 data, as I believe the correction was considered to be 'calibration' so not fixed 'til L1.

**Comment by nabobalis** [comment]
Did #3067 help this problem?

**Comment by ayshih** [comment]
I don't think #3067 is relevant.

Our sample EIT file has the corrected `DATE-OBS`, but our test EIT files do not.  Presumably the test EIT files are Level-0 data?  As long as all Level-1 files have the corrected `DATE-OBS`, does SunPy need to worry about this issue?

**Comment by ehsteve** [comment]
The fix for this should be to issue a warning if reading anything below Level 1 data where this issue not fixed.

**Comment by dstansby** [comment]
Do you know how we tell if the issue is or isn't fixed in a <L1 data file?

**Comment by dstansby** [comment]
Can someone provide a sample L0 data file that has this issue?

**Comment by dstansby** [comment]
Since there's been no response, I'm going to close this as "can't fix". If someone can link to a file that has this issue feel free to comment below and/or re-open
