### ISSUE TITLE
Replace the mapsequence gallery example that calculated running and base differences

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#3073]
### Description

The example that calculated running and base difference `MapSequence`s was deleted by #2972 in order to get #2972 in master without having to worry about the gallery example.  The gallery example as written used the map differential functionality.  #2972 breaks the implicit assumption in the previous example that all the differentially rotated maps have the same number of pixels in the x and y directions.  Fixing the gallery example to take account of #2972 is relatively easy but not part of #2972.  The gallery example should be replaced.

### Additional context

See also #2864 and #2596.

**Comment by wtbarnes** [comment]
Would #3627 resolve this?
