### ISSUE TITLE
Creating a TimeSeries from a url for GOES/XRS raises a NotImplementedType error

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#3079]
### Description

Creating a TimeSeries object by passing in the URL to a GOES/XRS fits file raises an error, tested on master and 0.9.6.
### Expected behavior

A XRSTimeSeries is created
### Actual behavior

TypeError raised
```
In [3]: goes = TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/2017/go1320170103.fits')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-611d12dec7b6> in <module>
----> 1 goes = TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/2017/go1320170103.fits')

/usr/local/lib/python3.6/site-packages/sunpy/timeseries/timeseries_factory.py in __call__(self, *args, **kwargs)
    410         for filepath in filepaths:
    411             try:
--> 412                 new_ts = self._check_registered_widgets(filepath=filepath, **kwargs)
    413             except (NoMatchError, MultipleMatchError, ValidationFunctionError):
    414                 if not silence_errors:

/usr/local/lib/python3.6/site-packages/sunpy/timeseries/timeseries_factory.py in _check_registered_widgets(self, **kwargs)
    534         units = kwargs.pop('units', None)
    535         if filepath:
--> 536             data, meta, units = WidgetType._parse_file(filepath)
    537
    538         # Now return a TimeSeries from the given file.

TypeError: 'NotImplementedType' object is not iterable
```
### Steps to Reproduce

```
from sunpy.timeseries import TimeSeries
g1 = TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/1986/go06860129.fits')
# or
# g2 = TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/2017/go1320170103.fits')
```
### System Details

  - SunPy Version: master or 0.9.6
  - Python Version: python3.6
  - OS information: macOS 10.14.4 / Ubuntu strech

**Comment by nabobalis** [comment]
Is TimeSeries meant to be able to take a URL?

**Comment by nabobalis** [comment]
I think you always need to specify source but doing so leads to a different error which I think is tied to your other issue: 

```python
TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/1986/go06860129.fits',source="XRS")

/opt/miniconda/envs/sunpy/lib/python3.7/site-packages/astropy/time/core.py in _get_time_fmt(self, val, val2, format, scale, precision, in_subfmt, out_subfmt)
    485                   format.lower() in self.FORMATS):
    486             if format is None:
--> 487                 raise ValueError("No time format was given, and the input is "
    488                                  "not unique")
    489             else:

ValueError: No time format was given, and the input is not unique
```

**Comment by samaloney** [comment]
Ah ok I don’t think the docs refelect that at the moment, on mobile so hard to be sure.  Aslo it is a bit odd that depending on the source (local, or url) different errors are raised surely should be source independent?

**Comment by nabobalis** [comment]
If you have the file downloaded and open it without the source keyword, it gives you a different error?

The current error is a really bad error and it really does need to be replaced with a better message.

**Comment by samaloney** [comment]
If I have the file locally I only get the error I mentioned in #3078 with or without the source keyword. 

But if I use a URL I do get different errors with and without the keyword
`goes = TimeSeries('https://umbra.nascom.nasa.gov/goes/fits/1986/go06860129.fits')` raises `TypeError: 'NotImplementedType' object is not iterable`
while
`g = TimeSeries('../flarenet/data/goes/go06860129.fits')` raises `ValueError: No time format was given, and the input is not unique`
