### ISSUE TITLE
Tests dropped in the transition from lightcurve in 0.9 to timeseries in 1.0 

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#3082]
### Description

Some general and source specific tests seem to have been dropped during the transition from lightcurve in to timeseries. For example, there is no test covering the creation of a timeseries from a URL, so this code branch is not tested

https://github.com/sunpy/sunpy/blob/6a18e3b954031996d720a2375b6c6702cd544f8b/sunpy/timeseries/timeseries_factory.py#L341

and the GOES satellite number logic is no longer tested as it was here in 0.9

https://github.com/sunpy/sunpy/blob/249e089244b5102406aeac77148177fb2ae61077/sunpy/lightcurve/tests/test_goes.py#L89

Suggest reviewing test code coverage for the general cases and inspection of the older source specific tests to find anything that isn't now covered in the current general timeseries tests.

**Comment by dstansby** [comment]
The first path above has test coverage; `_get_goes_sat_num` is a private method that isn't used anywhere in the code base, so maybe it could be deleted? Might be worth waiting for the GOES changes that are coming soon.

**Comment by dstansby** [comment]
Pretty sure _get_goes_sat_num has been deleted now, so going to close this as fixed.
