### ISSUE TITLE
Change logger default to show INFO

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3086]
### Description

By default, user's should see information by default. Need to update docs to make sure that user's know exactly how to unsubscribe both temporarily (for a session) and permanently (through the sunpyrc).

**Comment by Cadair** [comment]
@ehsteve are you going to be able to get to this in short order? i.e before the 1.0 freeze?

**Comment by ehsteve** [comment]
Turns out our default is already to show INFO messages.
