### ISSUE TITLE
SunPy version tag incorrect

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#3091]
I recently installed SunPy on a new machine, using my remote Github branch which is in sync with sunpy/master. For some reason, the version tag is incorrect, e.g.:

    In [59]: sunpy.__version__                                                                                                                                                   
    Out[59]: '0.4.1.dev7204+g4227ebe8'

from the codebase though it's clearly the up-to-date version of SunPy.

Side note, the ```system_info()``` function also fails, e.g.:

```In [60]: sunpy.system_info()                                                                                                                                                 
==========================================================
 SunPy Installation Information

==========================================================

###########
 General
###########
Time : Friday, 03. May 2019 02:42PM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : 0.4.1.dev7204+g4227ebe8
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-60-b106e592dd4b> in <module>
----> 1 sunpy.system_info()

/anaconda3/lib/python3.7/site-packages/sunpy-0.4.1.dev7204+g4227ebe8-py3.7-macosx-10.7-x86_64.egg/sunpy/util/sysinfo.py in system_info()
    112 
    113     for sys_info in ['Time', 'System', 'Processor', 'Arch', 'SunPy', 'SunPy_git']:
--> 114         print('{0} : {1}'.format(sys_info, sys_prop[sys_info]))
    115 
    116     if sys_prop['System'] == "Linux":

KeyError: 'SunPy_git'
```

**Comment by nabobalis** [comment]
Can you try `git fetch --tags` and see if that helps?

The other issue is a bug we need to fix.

**Comment by Cadair** [comment]
That's a curious failure mode, why would it have fetched the 0.4 tag but not the `v1.0.0.dev` one?! This hopefully will happen less after we tag 1.0 :worried:

**Comment by aringlis** [comment]
@nabobalis I tried the ```git fetch --tags``` command, but it did not change anything.

**Comment by Cadair** [comment]
I am not sure I have a solution to this. It's an issue with `git describe` not having all the data it needs somehow. @aringlis Could you try and completely fresh clone and see if you can reproduce it? If so can you post the step-by-step?
