### ISSUE TITLE
Plot titles and x-labels overlapping in example

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3093]
The plot titles and labels overlap in the 3rd image of https://docs.sunpy.org/en/latest/generated/gallery/acquiring_data/2011_06_07_sampledata_overview.html#sphx-glr-generated-gallery-acquiring-data-2011-06-07-sampledata-overview-py (see below). I'm guessing the tight-layout just needs tweaking.
![sphx_glr_2011_06_07_sampledata_overview_003](https://user-images.githubusercontent.com/6197628/57301262-821da480-70d0-11e9-83aa-50838ee4e693.png)

**Comment by Cadair** [comment]
This is a bit of a flaw in the way the title is positioned, although not one I am sure is fixable. 

When you overplot a HGS grid the plotting code moves the title up more to allow space for the ticks to appear on the top of the axis if they are drawn there (when zoomed in). I don't know if we can conditionally move the title on rendering (probably not easily).

**Comment by dstansby** [comment]
Even with the title moved up, I would have thought `tight_layout()` without any arugments could deal with it. If not it might be a maptlotlib bug.

**Comment by dstansby** [comment]
It turns out `plt.tight_layout()` with a `wcs` projection actually makes things worse! I've filed a bug upstream at https://github.com/astropy/astropy/issues/8703

**Comment by Cadair** [comment]
My guess on that would be that it's related to the fact `WCSAxes` draws its own ticks rather than using the normal tick drawing in mpl, but I assume Tom will know.

We should fix this issue in the docs irrespective of the upstream issues with `tight_layout`.

**Comment by pkj-m** [comment]
@Cadair I was playing around with the padding setting in the doc build and changing it to 8.5 fixes the issue and gives us this output: 

![doc title fix 3](https://user-images.githubusercontent.com/17577971/75103527-93b14800-5621-11ea-8147-b811ca536442.png)


I can create a PR if this looks good.
