### ISSUE TITLE
map.peek() doesn't show anything in jupyter notebook w/ inline backend

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3094]
Running the following code in a jupyter notebook:
```python
%matplotlib inline
from sunpy.data.sample import AIA_193_IMAGE
import sunpy.map

aia = sunpy.map.Map(AIA_193_IMAGE)
aia.peek()
```
results in the following warning:
```
/Users/dstansby/miniconda3/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
```
and no plot shown. Adding the lines
```python
import matplotlib.pyplot as plt
fig = plt.figure()
```
before doing `.peek()` does make it work, so I suspect there's something going on in `SunPy` that isn't setting up the notebook/matplotlib properly for plotting.

- Matplotlib 3.0.3
- Sunpy master branch

**Comment by nabobalis** [comment]
DELETE PEEK?

**Comment by Cadair** [comment]
I am more interested in what ever [this](https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/visualization.py#L9) bit of insane history is all about.

**Comment by ayshih** [comment]
> I am more interested in what ever [this](https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/visualization.py#L9) bit of insane history is all about.

Heh, looks like you've re-discovered this bizarre code (see #487)!

**Comment by ayshih** [comment]
See PR #3103 for what I believe is a proper implementation of `peek()`
