### ISSUE TITLE
WCS plotting documentation and examples needed

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#3095]
### Description
Lots of examples are needed in the docs to show how WCS Axes plotting is done so that people use WCS rather than other axes. 

For example when plotting with WCS we need to describe and demonstrate converting between coord to pixel or defining frames in transform when overplotting points, lines, arrows etc. 

Also things like using set_xlim, set_ylim

See also #3018

**Comment by ehsteve** [comment]
This documentation needs to provide clear examples that shows that `WCSAxes` default to degrees. This is the actual problem in #3101.

**Comment by hayesla** [comment]
So just to give a bit more detail about what would be needed for this @Kate028:

I think for this we would want a new example to be created and put in the Example Gallery under [Plotting](https://docs.sunpy.org/en/stable/generated/gallery/index.html#plotting). I guess the idea of a descriptive example of how pixel and world coordinates work when plotting with WCSAxes. 

For example, when plotting a map, and you want to plot a point (rather than using `ax.plot_coord` with a SkyCoord) for example, you can use the `transform=` keyword. However I guess the tricky thing about it is that they points have to be given in `deg` rather than `arcsec` which can be confusing.

```
fig = plt.figure()
ax = fig.add_subplot(projection=my_map)
my_map.plot(axes=ax, clip_interval=(1, 99.9)*u.percent)

ax.scatter(500*u.arcsec.to(u.deg), 100*u.arcsec.to(u.deg), transform=ax.get_transform("world"))

ax.contour(my_map.data, levels=np.arange(0.051, 0.9, 0.01)*np.max(my_map.data),
           transform=ax.get_transform(my_map.wcs))
```
![image](https://user-images.githubusercontent.com/4620298/104011185-9f5c1d80-51a5-11eb-88ee-93fc2bf6dcd8.png)

So an example to show something like this was what I was thinking. It is actually somewhat described in [this example](https://docs.sunpy.org/en/stable/generated/gallery/plotting/wcsaxes_map_example.html#sphx-glr-generated-gallery-plotting-wcsaxes-map-example-py). 

However I think it would still be worthwhile to have a more detailed example of how pixel and world coodinates work with WCS Axes and to show how the different ways things can be plotted with WCSAxes.

**Comment by Kate028** [comment]
@hayesla Should i take "AIA_171_IMAGE" sample image for plotting or is there any other images that should be used also how many example are we supposed to insert into WCS plotting documentation.

**Comment by hayesla** [comment]
I would just use one image of the Sun, so the `AIA_171_IMAGE` from the sample data is a good one to use. You could then just show several examples of WCS plotting and some documentation on the one map, one such would be the example above. Does that make sense?

**Comment by Kate028** [comment]
yes understood, thanks!
