### ISSUE TITLE
Mask out occulting disk in coronagraph images

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3098]
### Description

It could be useful to provide the size of the occulting disk in coronagraph imagery and mask out the pixels that are inside that disk since they contain no useful data.

### Additional context

This would enable checks of wether a pixel is actual measured coronal emission or not.

**Comment by Cadair** [comment]
*points at maputils*

**Comment by wafels** [comment]
Where would you want to store the coronagraph occulter radius? Add another
property to the map via the LASCO source file?

**Comment by ehsteve** [comment]
We could add the radius information to the meta data on creation but really I was thinking that we would hand off a masked array.

**Comment by ehsteve** [comment]
If we only we had a CoronagraphMap class...

**Comment by Cadair** [comment]
no, bad Steve.

**Comment by wafels** [comment]
The LASCO mask should also include the pylon. Having that mask in the LASCO map object would be very useful.

**Comment by wafels** [comment]
The LASCO mask is already in SSWIDL. We use it in helioviewer. So we could keep it in SunPy. Or we could try to parameterize it and generate it instead of storing it.

**Comment by Cadair** [comment]
Sounds like an excellent use for #1939. I would say that this function should be in `sunpy.instr.lasco` tbh.

**Comment by Cadair** [comment]
On the topic of #1939 could you elaborate on where this mask is, how we can download it and what we should do with it? So that @vn-ki can consider doing it as part of his GSOC project?

**Comment by wafels** [comment]
The masks are here

https://hesperia.gsfc.nasa.gov/ssw/soho/lasco/idl/data/calib/

The mask you want is probably this one

c3clearmask2a.fts
<https://hesperia.gsfc.nasa.gov/ssw/soho/lasco/idl/data/calib/c3clearmask2a.fts>

I say probably because the mask processing algorithm is rather opaque.
At least this is a good place to start.

Jack

**Comment by AthKouloumvakos** [comment]
The center of the occulting disk of a coronagraph is provided (or can be calculated) from the information available in the fits header (at least for STEREO COR and SoHO LASCO [e.g. see here the CRPIXi keyword](https://hesperia.gsfc.nasa.gov/ssw/stereo/secchi/doc/FITS_keywords.pdf)). Therefore, having the center and also the radius of the occulter (which can be determined manually or from the [calibration data](https://hesperia.gsfc.nasa.gov/ssw/soho/lasco/idl/data/calib/) ) a mask can be produced for each case. I attach a sample script:
 
[occulters_test.zip](https://github.com/sunpy/sunpy/files/6994251/occulters_test.zip)

From a communication with @dstansby:

Q1. Is it not possible to assume that the center of the occulter is always the center of the image (ie. the pixel coordinate of the center is is m.data.shape / 2)?
A1: The center of the occulter is where the CRPIXi points at. If the image has been recentered with respect to this point then this can be the case, else it is not possible to assume this.

Q2. Are the width of the occulters (in pixels) always constant?
A2: Yes, I think the radius of the occulters is always constant (Lets think of it a bit more).
