### ISSUE TITLE
WCSAxes Transform does not seem to work with add_patch

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3101]
### Description

WCSAxes transform properties do not seem to be working correctly.

As described in the [WCSAxes documentation](http://docs.astropy.org/en/stable/visualization/wcsaxes/overlays.html#pixel-coordinates), the code quoted below should draw a circle centered on the Sun with a radius of 900 arcsec.

### Expected behavior

 the code quoted below should draw a circle centered on the Sun with a radius of 900 arcsec.
### Actual behavior

No circle is plotted at all which I assume means that it is being plotted off screen.

### Steps to Reproduce

```python
import sunpy.data.sample
import sunpy.map

import matplotlib.pyplot as plt
from matplotlib.patches import Circle

map1 = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(1,1,1, projection=map1)
map1.plot()

r = Circle((0, 0), 900, edgecolor='blue', facecolor='blue', transform=ax.get_transform('world'))
ax.add_patch(r)
plt.show()
```
### System Details

  - SunPy Version: 1.0.0.dev1331+gc26fa0e0e
  - Python Version: 3.6.7
  - OS information: Darwin

**Comment by Cadair** [comment]
This seems to be restricted to `add_patch` btw, it works fine with `ax.plot`:
```python
ax.plot(0,0,"bo", transform=ax.get_transform('world'))
```
works fine and plots a point at disk centre.

**Comment by Cadair** [comment]
Ok, the solution is hiding in the bottom of the `WCSAxes` documentation: http://docs.astropy.org/en/stable/visualization/wcsaxes/overlays.html#spherical-patches

what you need is this:
```python
import sunpy.data.sample
import sunpy.map

import matplotlib.pyplot as plt
from matplotlib.patches import Circle

map1 = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(1,1,1, projection=map1)
map1.plot()

r = SphericalCircle((0,0)*u.arcsec, 900*u.arcsec, edgecolor='blue', facecolor='blue', transform=ax.get_transform("world"))
ax.add_patch(r)
plt.show()
```

![Figure_2](https://user-images.githubusercontent.com/1391051/57523250-627abc00-731c-11e9-8d56-c9c0c6f422f3.png)


I am therefore going to close this in favour of #3095 as it's just another case of things not being obvious.

**Comment by ehsteve** [comment]
The actual problem here is that the transform function is expecting degrees and not arcsec. So the following, 

```python
import sunpy.data.sample
import sunpy.map

import astropy.units as u
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

map1 = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(1,1,1, projection=map1)
map1.plot()

r = Circle((0, 0), (900 * u.arcsec).to('deg').value, edgecolor='blue', facecolor='blue', transform=ax.get_transform('world'))
ax.add_patch(r)
plt.show()
```

also works and generates the following

![Figure_1](https://user-images.githubusercontent.com/739053/57797603-ca644480-7718-11e9-8752-5ad9c59775a4.png)
