### ISSUE TITLE
Add documentation explaining why/how to switch the Astropy ephemeris

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3114]
Astropy's built-in ephemeris is not as accurate as a JPL ephemeris (e.g., DE430), although the discrepancies are appreciable only when querying non-Earth planets.  Our documentation should explain how to switch the Astropy ephemeris (via `astropy.coordinates.solar_system_ephemeris`).

**Comment by ayshih** [comment]
Keep an eye on astropy/astropy#8751

**Comment by dstansby** [comment]
Is this explained anywhere in the astropy docs, that we could easily link to?

**Comment by ayshih** [comment]
The appropriate Astropy page is https://docs.astropy.org/en/v3.2.x/coordinates/solarsystem.html, but of course our docs need to provide the context.

**Comment by Jett-Code** [comment]
> Our documentation should explain how to switch the Astropy ephemeris (via `astropy.coordinates.solar_system_ephemeris`).

I'm not able to understand what this means?

**Comment by ayshih** [comment]
Please take a look at https://docs.astropy.org/en/stable/coordinates/solarsystem.html.  At the bare minimum, we would add a line to the docstring for `get_body_heliographic_stonyhurst()` that links to the Astropy page.

**Comment by Jett-Code** [comment]
So the end goal is to add a line in docs that links to https://docs.astropy.org/en/stable/coordinates/solarsystem.html ?
