### ISSUE TITLE
Improve missing metadata warning in Map

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3117]
If some of the keys for observer metadata are missing it would be good to inform the user which ones they should add. See this comment https://github.com/sunpy/sunpy/pull/3115#discussion_r285666447

**Comment by Raahul-Singh** [comment]
Is there any inherent logic for differentiating between `carrington` latitudes and longitudes and  `stonyhurst` latitudes and longitudes that may be used to figure out which ones the user may want?
If not can we not simply do a search in the meta to see what all may be missing?
From what I understand, `dsun_obs` will be the same for both and will be easy to verify if missng?

**Comment by Cadair** [comment]
The way this works is that map sources can register any keywords they like to be interpreted as observer position. See [`AIAMap`](https://github.com/sunpy/sunpy/blob/master/sunpy/map/sources/sdo.py#L61) for an example.

In `GenericMap` we would need to support finding out what keys are missing based on the `_supported_observer_coordinates` property.

**Comment by Raahul-Singh** [comment]
In your comment here you mentioned `work out what ones are missing, i.e. you could have a weird header with a mix of crln and hglt`, in this context is there some logic to discern one from the other or do we need to simply show all which may be missing?
[https://github.com/sunpy/sunpy/pull/3115#discussion_r285675087](url)

**Comment by Cadair** [comment]
So each frame has 3 keys, if none of them match, then we ignore the frame as it's clearly not there. If some but not all of them match (and none match all 3) we should tell the user that we failed to read any of the half-present frames because of a specific missing key or two.

Does that make any sense?

**Comment by Raahul-Singh** [comment]
Cool. I understand now. Thanks! :smiley:

**Comment by Raahul-Singh** [comment]
Can a frame have more than three meta?
