### ISSUE TITLE
Add narrative documentation for header creation

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3119]
#3083 needs some docs in the guide

**Comment by hayesla** [comment]
hey @Cadair - should this include a description about the different FITS keywords and WCS too? 
i.e. What is needed to actually make a map.

And then also include how to use the helper function?

Also where about should this go in the docs?

**Comment by Cadair** [comment]
When I made the issue I was more thinking we should have an example of using this to create a map rather than worrying about documenting the FITS headers themselves.

https://docs.sunpy.org/en/v1.0.0rc1/guide/data_types/maps.html#creating-custom-maps this section of the guide is probably the best place?
