### ISSUE TITLE
Map Header Helper should support rotation matrix

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3126]
I don't know how we managed to miss this the first time around but #3083 should have included the ability to specify the rotation of the pixel grid with respect to the world coordinates. (i.e with an angle or rotation matrix)

**Comment by hayesla** [comment]
what would you invision this to look like? If you give the CROTA or PCi keywords you can still make it into the header

**Comment by Cadair** [comment]
I think a keyword arg (or two) much like `Map.rotate` would be the best thing here where you can specify either a rotation angle and the rotation matrix is calculated from the angle and injected into the header as `PCi_j` or the matrix is just put in as `PCi_j`.

**Comment by hayesla** [comment]
so should we have a keywords in the `make_fitswcs_header` function such that you can call `rotate = xx` in the function call? similar to scale and reference_pixel?

**Comment by Cadair** [comment]
yeah I would think so

**Comment by hayesla** [comment]
groovy, I'll have some time today to work on this
