### ISSUE TITLE
1.0.0rc2: Tests try to import parfive when running offline

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#3127]
### Description

On Debian, we run the tests in an offline environment. We also don't have a Debian package "python-parfive" (yet).

### Expected behavior

Offline tests are skipped, and parfive is not imported since it is not used in this case

### Actual behavior

Online tests error with

```
 ERROR collecting .pybuild/cpython3_3.7_sunpy/build/sunpy/physics/tests/test_solar_rotation.py 
ImportError while importing test module '/build/sunpy-1.0.0~rc2/.pybuild/cpython3_3.7_sunpy/build/sunpy/physics/tests/test_solar_rotation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sunpy/physics/tests/test_solar_rotation.py:15: in <module>
    import sunpy.data.test
sunpy/data/__init__.py:1: in <module>
    from sunpy.data._sample import download_sample_data
sunpy/data/_sample.py:6: in <module>
    import parfive
E   ModuleNotFoundError: No module named 'parfive'
```
  - SunPy Version: 1.0.0rc2
  - Python Version: 3.7
  - OS information: Debian experimental

**Comment by nabobalis** [comment]
That is a good point.

 If you are running the offline tests, you probably don't need  the sample data (parfive). We could have a try:except block for that import in the sample data until a parfive debian package is ever created?

**Comment by olebole** [comment]
Sounds like a good idea, thanks.

**Comment by Cadair** [comment]
The quickest fix for this would be to move the parfive import into the actual function that uses it.

This does feel a little hacky though, importing parfive dosen't actually cause a connection to the internet. I would imagine you will need parfive to also run the offline tests in the `net` subdirectory as well.

**Comment by Cadair** [comment]
The more I think about this, the more I think you will not be able to run the test suite without `parfive`. Importing `net` will require it as well, we even do some offline things using parfive if the files are already downloaded for lyra etc.

**Comment by olebole** [comment]
Even in the offline case? In that case, we don't have any downloaded files.

**Comment by Cadair** [comment]
I *think* there is an edge case or two where we would use the `parfive.Results` object without ever asking the internet for anything (we might do this in the offline tests as well, but I doubt it).

Either way, the use of parfive in `net` is pretty pervasive, delaying the import till we actually needed to connect to the internet would mean a reasonable amount of shuffling things about. What's the motivation for changing this around rather than waiting for the debian package of parfive? (Also let me know if there is anything I can do to assist you in getting a parfive package sorted).

**Comment by nabobalis** [comment]
Yeah I think there are some offline mocked tests that will need it.

**Comment by olebole** [comment]
I am just trying to keep the dependencies small, to make the build process more robust. And it is a question of priorities for me: if downloading is a special task for only a few users, then packaging would have a rather low priority. However, probably the effort is not high (didn't check the package yet), so it will just take a few days longer.

> Also let me know if there is anything I can do to assist you in getting a parfive package sorted

Maybe not you personally: but since sunpy is evolving into its own package ecosystem, I would appreciate if someone would become a co-maintainer or even take over these packages (I am always looking for people who want to get involved ;-) ) -- this would improve the bus factor...

**Comment by olebole** [comment]
Closing this in favour of packaging parfive for Debian: [Debian#929438](https://bugs.debian.org/929438)

**Comment by Cadair** [comment]
Thanks a lot for your efforts @olebole :)
