### ISSUE TITLE
Files downloaded by sunpy.map.Map with URL argument should not stay on disk forever

### ISSUE THREAD

**Issue by ebuchlin** [sunpy/sunpy#3144]
### Description

When `sunpy.map.Map()` is used with a URL argument, the corresponding FITS file is [downloaded](https://github.com/sunpy/sunpy/blob/master/sunpy/map/map_factory.py#L228) to `$HOME/sunpy/data` and stays there forever with no apparent reason.

### Expected behavior

By default, the file should be deleted after use. I understand that "use" could be longer than just creating the Map object because of memory mapping (#1745), but I don't see a reason why it should be kept forever.

Such files could be used as a network cache, but:
* this doesn't seem to be the case (the same file is written on disk again and again, with different names).
* a cache should be managed properly, with cleaning of files not recently used, and a maximum size and/or retention time.

### Actual behavior

The files stay on disk forever and don't seem to be used.
On my old laptop this fills the few remaining GB of disk space very quickly, and prevents reading more than about a hundred SDO/AIA or HMI files before I need to delete the sunpy/data directory by hand.

Only data for tests are planned to be downloaded to a temporary directory (#2993, for v1.0).

### Steps to Reproduce

Assuming `$HOME/sunpy/data` is empty:

```python
In [1]: from sunpy.map import Map

In [2]: ls -sh ~/sunpy/data
total 0

In [3]: for i in range(3):
   ...:     m = Map('http://idoc-medoc.ias.u-psud.fr/sitools/datastorage/user/SUM15/D1005681501/S00004/magnetogram.fits')
   ...:     

In [4]: ls -sh ~/sunpy/data
total 41M
14M magnetogram.0.fits  14M magnetogram.1.fits  14M magnetogram.fits
```

###########
 General
###########
Time : Tuesday, 28. May 2019 11:50AM UT
System : Linux
Processor : x86_64
Arch : 64bit
SunPy : 0.9.8
SunPy_git : 953d49956eca46ca0e50471ab60ff52ac486acc4
OS: debian buster/sid  (Linux 4.18.0-20-generic x86_64)

###########
 Required Libraries 
###########
Python: 3.6.8
NumPy: 1.16.3
SciPy: 1.1.0
matplotlib: 3.0.2
Astropy: 3.1.2
Pandas: 0.23.4

###########
 Recommended Libraries 
###########
beautifulsoup: 4.6.3
PyQt: 4.11.4
SUDS: 0.6
Sqlalchemy: 1.2.15
Requests: 2.21.0

**Comment by Cadair** [comment]
Thanks for the bug report @ebuchlin this is pretty well timed as we have a summer student working on data caching this summer, so we can add this to the list of use cases in #1939
