### ISSUE TITLE
Frame-bias corrections may be needed for two `sunpy.coordinates.sun` functions

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3156]
In `sunpy.coordinates.sun`, `true_rightascension()` and `true_declination()` when asking for J2000.0 epoch (i.e., `equinox_of_date=False` is supplied) may need to include the correction for frame bias.  Figure this out.

**Comment by Cadair** [comment]
What is "frame bias" in this context?

**Comment by ayshih** [comment]
Frame bias is the (very small) difference between the pole in GCRS (or any ICRS-like frame) and the mean pole in J2000.0.  [Here's](https://github.com/astropy/astropy/blob/master/cextern/erfa/bi00.c) the function in Astropy to calculate the angles, although not in the coordinate system I'd prefer.  It needs to be corrected for, so this issue is more making sure that Astropy's GCRS is truly GCRS and didn't accidentally correct for frame bias already.

**Comment by ayshih** [comment]
I've decided that these functions, when `equinox_of_date=False` is supplied, should be returning the coordinates in ICRF/J2000.0, not in the dynamical orientation at J2000.0, so frame bias should *not* be included.  Reasons are:

- It doesn't make sense to return coordinates for the Sun in the dynamical orientation at J2000.0 unless the observation time is also J2000.0 (2000 January 1 12:00 TT), because otherwise there's an implied inconsistency for the position of Earth.
- We compare the astrometric values against what's reported elsewhere, and JPL HORIZONS reports in ICRF/2000.0.
