### ISSUE TITLE
Decide the fate  of sunpy.sun.sun or sunpy.coordinates.ephemeris

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3158]
We have two places for very similar kinds of functions, we should define what goes where to make sure we don't have duplication, and potentially move one into the other.

**Comment by ayshih** [comment]
How things are organized in 1.0:

- sunpy.coordinates.ephemeris
    - get_body_heliographic_stonyhurst
    - get_earth
    - get_sun_B0
    - get_sun_L0
    - get_sun_P
    - get_sunearth_distance
    - get_sun_orientation
    - get_horizons_coord
- sunpy.sun.sun
    - solar_semidiameter_angular_size
    - position
    - carrington_rotation_number
    - true_longitude
    - apparent_longitude
    - true_latitude
    - apparent_latitude
    - mean_obliquity_of_ecliptic
    - true_rightascension
    - true_declination
    - true_obliquity_of_ecliptic
    - apparent_rightascension
    - apparent_declination
    - print_params

**Comment by ayshih** [comment]
A draft of how things could be re-organized (including some renaming):

- sunpy.coordinates.ephemeris (import into sunpy.coordinates namespace)
    - get_body_heliographic_stonyhurst
    - get_earth
    - get_horizons_coord
- sunpy.coordinates.sun (do not import into sunpy.coordinates namespace)
    - B0
    - L0
    - P
    - earth_distance
    - orientation
    - angular_radius
    - sky_position
    - carrington_rotation_number
    - true_longitude
    - apparent_longitude
    - true_latitude
    - apparent_latitude
    - mean_obliquity_of_ecliptic
    - true_rightascension
    - true_declination
    - true_obliquity_of_ecliptic
    - apparent_rightascension
    - apparent_declination
    - print_params
- ~sunpy.sun.sun~

**Comment by Cadair** [comment]
This looks like a good plan to me.
