### ISSUE TITLE
We need a strict style guide for the gallery

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3167]
I mean really really strict so we are always consistent in how we recommend people do things. For example any of the following

* you shall import these things like this
* you will always create a plot this way
* you either shall always put spaces around operators, or you shall not put spaces around `*u.` when assigning units to a thing

**Comment by ehsteve** [comment]
This information belongs inside the [example_template.py](https://github.com/sunpy/sunpy/blob/master/examples/example_template/example_template.py) file.

**Comment by nabobalis** [comment]
Closed in favour of https://github.com/sunpy/sunpy/issues/3522

**Comment by wtbarnes** [comment]
I'm going to close this in favor of folding in the above to a comment on #3522
