### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3169]
This is a checklist of things I am putting off till tomorrow for the release

- ~~Backport #3165~~
- ~Backport #3170~
- ~Check that #3165 hasn't broken the 1.0 branch RTD build.~
- ~conda forge will not build the rc4 because Azure: https://github.com/conda-forge/sunpy-feedstock/pull/47~ 
- ~We need to make sure that Zenodo formats our rc5 tag properly: https://zenodo.org/record/3235797~
- ~Update the RELEASE.rst  and what's new with the latest statistics.~
- ~Add https://github.com/sunpy/sunpy/pull/3133#discussion_r289558944 to the zenodo json~

Then I think it's normal release stuff

**Comment by nabobalis** [comment]
Backported #3165 and #3170. Added #3133 comment to the json file. 
Conda forge does build rc4. 
RTD does not break on current 1.0 branch. 
No idea about if Zendo is nice. 

You want to update the RELEASE?
