### ISSUE TITLE
Fix automatic calculation of RSUN_OBS

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3182]
### Description

When the fits header value `RSUN_OBS` is missing, it will automatically calculate it but does not take into account the observer location but assumes Earth. This is done [here](https://github.com/sunpy/sunpy/blob/452fe3324fa36d121e2df69b6789fcbf4a26b5de/sunpy/map/mapbase.py#L552).

### Expected behavior

The calculation should populate the RSUN_OBS as observed by the observer and so should take into account the observer location and NOT assume Earth.

### Actual behavior

It assumes Earth.

### System Details

  - SunPy Version: 1.0
  - Python Version:
  - OS information:

**Comment by hayesla** [comment]
I guess it should do a check for dsun obs - and if that exists then populate the rsun_obs as
```
rsun_obs = np.arctan(constants.radius / meta['dsun_obs']).to_value(u.arcsec)
```

**Comment by ayshih** [comment]
> I guess it should do a check for dsun obs - and if that exists then populate the rsun_obs as
> 
> ```
> rsun_obs = np.arctan(constants.radius / meta['dsun_obs']).to_value(u.arcsec)
> ```

Don't rely on `DSUN_OBS` because we may know the Sun-observer distance without that keyword.  One should use the Map property `dsun`.

**Comment by ayshih** [comment]
Fixed the link in the OP so that it is a permalink.

**Comment by dstansby** [comment]
I think I fixed this in https://github.com/sunpy/sunpy/pull/4375
