### ISSUE TITLE
Slight discrepancies with the calculated position angle of the Sun

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3198]
The values from `sunpy.coordinates.sun` agree with published values in the *Astronomical Almanac* to published precision, **except for** the occasional discrepancies with position angle of the Sun (at the sub-arcmin level).  I believe this is because I'm using `PrecessedGeocentric` for a frame with the Z axis aligned with the Earth's axis of rotation, but `PrecessedGeocentric` accounts for precession but not nutation.  Look into this.

(We technically also don't quite agree with on the angular radius of the Sun, but I can't find a statement of what physical radius the *Astronomical Almanac* is using, so I'm going to give that a pass since we agree on the Sun-Earth distance.)

**Comment by ayshih** [comment]
For 2013-03-18 0h TT:

*Astronomical Almanac*: -24.88 deg

`PrecessedGeocentric`:
```python
>>> sun.P(Time('2013-03-18', scale='tt'))
<Angle -24.88654531 deg>
```

`PrecessedGeocentric` hacked to include nutation:
```python
>>> sun.P(Time('2013-03-18', scale='tt'))
<Angle -24.88509249 deg>
```

Closer, but not quite there.  Maybe something else is wrong too.

**Comment by dpshelio** [comment]
My dream would be to also include the uncertainty on all these calculations. Is the value given by the Astronomical Almanac -24.880 deg, with a +/-0.001 deg precission? o -24.88 with a 0.005 precission?

**Comment by ayshih** [comment]
"-24.88" is the published value, so +/-0.005 deg precision.  That means that the above calculation, with the hacked fix, is a very slight miss, possibly by as little as a third of an arcsecond.

I can certainly add notes to various docstrings to make it clear exactly what level of precision has been verified.  I'd be hesitant to call it "uncertainty" because our values – position angle aside – may be accurate beyond the significant figures that the *Astronomical Almanac* chooses to publish.

**Comment by ayshih** [comment]
This write-up by the *Astronomical Almanac* folks (http://asa.usno.navy.mil/static/files/sun_rotation_change.pdf) may give some hints.  I believe that, through Astropy, we are taking aberration into account, but that can be further investigated.  Note that the *Astronomical Almanac* folks appear to feel that agreement to within one unit of the least significant figure is good enough, so, it's more like +/-0.01 deg (or even 0.015 deg) is the tolerance.

**Comment by ayshih** [comment]
I just realized that I don't even need to hack `PrecessedGeocentric` (and I probably didn't do it correctly).  I ought to just use the `ITRS` coordinate frame.  See #3886.

There will still be a lingering discrepancy of up to a few arcseconds because of how *The Astronomical Almanac* treats stellar-aberration corrections, but this discrepancy will almost never be evident at the printed precision.
