### ISSUE TITLE
generate_releaserst.xsh would be useful for astropy-procedures too

### ISSUE THREAD

**Issue by pllim** [sunpy/sunpy#3211]
### Description

Please consider porting https://github.com/sunpy/sunpy/blob/master/tools/generate_releaserst.xsh upstream back to https://github.com/astropy/astropy-procedures

### Additional context

xref astropy/astropy-procedures#122

**Comment by nabobalis** [comment]
Would you just want the script moved there or ported out of xonsh?

**Comment by pllim** [comment]
I don't use xonsh myself, so something more generic in Python would be nice; is that possible? Also, @bsipocz reported that the latest version didn't really work for her in the recent `astropy` 3.2 release.

**Comment by bsipocz** [comment]
to be frank I didn't bother figuring out what goes wrong with the latest, the local copy I had and used for 3.1 worked perfectly well (except that I'm not sure it indeed worked exactly as I assumed it would regarding counting the issues/PRs, but then that doesn't really matter much either).

**Comment by dstansby** [comment]
I don't think there's much point having this issue on the sunpy repo - if there's demand from the astropy side then I think it's worth opening an issue there linking to the script you'd like to port.

**Comment by pllim** [comment]
Hmm I guess it is up to @astrofrog or @saimn since they take turns doing astropy releases now.

**Comment by astrofrog** [comment]
If the script is still used by Sunpy it would make more sense to move it to an OpenAstronomy repo if anything rather than an astropy repo?

**Comment by Cadair** [comment]
Do we have a suitable OA repo or are we going to need to make one?
