### ISSUE TITLE
Change the name of `Helioprojective.calculate_distance()`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3222]
`Helioprojective.calculate_distance()` is used to convert a 2D HPC coordinate into a 3D HPC coordinate by filling in the `distance` attribute with the distance from the observer to the surface of the Sun.  I have issues with the name of the method:

- The name suggests that it is used to calculate the distance to something user-supplied (e.g., a la `SkyCoord.separation_3d()`).
- A user might expect it to return some distance value, not a new `Helioprojective` frame.

I think a better name for this method would be along the lines of `make_3d()` or `convert_to_3d()`.  Discuss.

**Comment by ayshih** [comment]
@Cadair What exactly is our deprecation policy?  Say that we decided today that the eventual name for this method should be `make_3d()`.  That means (I think):

- In 2.0, `make_3d` is available, and `calculate_distance()` is also available but emits a deprecation warning.
- in 3.0, `make_3d` is the only method available, and `calculate_distance()` no longer exists.

What about 1.1, if anything?  Is 2.0 the first time that `make_3d` can be available and the first time that `calculate_distance()` can emit a deprecation warning?

**Comment by Cadair** [comment]
The SEP isn't merged yet, but the requirement is that we emit a deprecation warning for at least one LTS (x.0) release. So we would have to have `calculate_distance` work until 2.0 is released, we could then remove it in 2.1.
