### ISSUE TITLE
Differential rotation seems to rotate the wrong way

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3226]
### Description
This was previously raised in #3190, but I'm breaking this into a separate issue.

When warping a map using the new differential rotation code, the image is warped in the opposite direction, e.g. when rotating a map forward two days in the future, the new rotated map appears rotated "backwards in time." 

See example below, where Map A (top panel) is being rotated to the observer location of Map B (middle panel). Because Map B is in the future (by two days),  it is expected that Map A will be warped in the direction of the solar rotation. However, the opposite happens.

### Expected behavior
![image](https://user-images.githubusercontent.com/8676141/59641927-0c8b0680-915b-11e9-8b93-8be26b4b996c.png)

### Actual behavior
![fig_diff_rot_1600](https://user-images.githubusercontent.com/8676141/59641730-748d1d00-915a-11e9-93bf-5d391ebc0b1d.png)

### Steps to Reproduce

The code to reproduce this example can be found [here](https://github.com/sunpy/sunpy-1.0-paper/blob/master/figures/diff_rot_example_plot.py).

### System Details
- SunPy Version: 1.0.1
- Python Version: 3.6
- OS information: macOS

**Comment by Cadair** [comment]
@wafels you got any bright ideas on this one?
