### ISSUE TITLE
calling parse_time from irispy

### ISSUE THREAD

**Issue by davergraham** [sunpy/sunpy#3234]
### Description

Finding problems with irispy.iris_tools routines when parse_time is called. e.g in read_iris_spectrograph_level2_fits (line 504) and get_iris_response (line 179)

Here's an example when I try use it directly:

```python
>>> print(hdulist[0].header["STARTOBS"])
>>>
>>> something = parse_time(hdulist[0].header["STARTOBS"])
>>> print(something)
```
Output:
```
2015-04-09T19:24:41.920


AttributeError                            Traceback (most recent call last)
<ipython-input-30-746a285db3fa> in <module>()
      1 print(hdulist[0].header["STARTOBS"])
      2 
----> 3 something = parse_time(hdulist[0].header["STARTOBS"])

~/github_repos/sunpy_dev/sunpy/time/time.py in parse_time(time_string, format, **kwargs)
    291         rt = Time.now()
    292     else:
--> 293         rt = convert_time(time_string, format=format, **kwargs)
    294 
    295     return rt

~/anaconda3/envs/irispy-dev/lib/python3.6/functools.py in wrapper(*args, **kw)
    801 
    802     def wrapper(*args, **kw):
--> 803         return dispatch(args[0].__class__)(*args, **kw)
    804 
    805     registry[object] = func

~/github_repos/sunpy_dev/sunpy/time/time.py in convert_time_str(time_string, **kwargs)
    214             if ts is None:
    215                 continue
--> 216             return Time.strptime(ts, time_format, **kwargs) + time_delta
    217         except ValueError:
    218             pass

AttributeError: type object 'Time' has no attribute 'strptime'
```

My suspicion is this line here...
```python
--> 216             return Time.strptime(ts, time_format, **kwargs) + time_delta
```

as strptime is used in datetime elsewhere, swapping Time for datetime unfortunately didn't help.

any ideas?
thanks!

### System Details

  - SunPy Version: 1.0.1
  - Python Version: 3.6
  - OS information: mac os mojave

**Comment by nabobalis** [comment]
Hi @davergraham, can you tell me what your astropy version is?

**Comment by Cadair** [comment]
Also can you show us the value of `hdulist[0].header["STARTOBS"]`?

**Comment by ayshih** [comment]
> Also can you show us the value of `hdulist[0].header["STARTOBS"]`?

It was in the original post ("2015-04-09T19:24:41.920"), but I've edited the post so that it's more clear.

**Comment by davergraham** [comment]
Ok, my bad, astropy wasn't updated properly! I've working in an environment setup for irispy which I've been updating, but clearly not properly updating astropy outside of this. Thanks for the help!
