### ISSUE TITLE
hek client search method broken for SPoCA

### ISSUE THREAD

**Issue by WaaallEEE** [sunpy/sunpy#3238]
### Description
Under sunpy version 1.0.1 installed from conda-forge, ```hek.HEKClient().search()``` issues ```KeyError``` and ```ValueError``` using ```hek.attrs.FRM.Name == 'SPoCA'```
I do not have this issue when using ```hek.attrs.FRM.Name == 'EGSO_SFC'``` for the same dates. 

### Expected behavior
No problem under sunpy 0.9.x
Also, I had no problem  when using one of the github dev versions at 1.0.x in the last week of May, I did not retain the version number. So this bug must have been introduced a few days ago before you officially released 1.0.1 and after the version RC4. That's all I can remember. 

### Steps to Reproduce

```
from sunpy.net import hek, helioviewer
from sunpy.time import parse_time
client = hek.HEKClient()
tstart = '2013/02/01 00:00:00'
tend = '2013/02/01 23:30:00'
time_start = parse_time(tstart)
time_end = parse_time(tend)
results = client.search(hek.attrs.Time(time_start, time_end), hek.attrs.FRM.Name == 'SPoCA')
```

### System Details

  - SunPy Version: 1.0.1 and dev version 1.1.x
  - Python Version: 3.6 & 3.7
  - OS information: macOS 10.13.6

**Comment by nabobalis** [comment]
The issue appears to be that the results returned are varied such that they have different columns which is causing that error.  

I will try to work on a fix for this but I would suggest for now trying to look at specific events for now. 

You said it was introduced recently, I will try to track that down but can you tell me your astropy version?
