### ISSUE TITLE
Add an example on how to plot positions on a blank map

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3241]
### Description

It is commonly seen in papers and presentations to show hpc positions of events such as flares on a blank (white) map. Because the events usually occurred at different times no single observation is appropriate.  

### Additional context

None

**Comment by Cadair** [comment]
Should be easy enough, use the header helper to create a new map and just have an array of NaNs.

**Comment by ehsteve** [comment]
I pretty much have it done already.

**Comment by Cadair** [comment]
Same way, just set the reference coord to HGS and then set the projection to CAR or similar.

**Comment by m11dedhia** [comment]
Hey guys, can I work on this issue? Also I am a total newbie so could you please guide me as well?

**Comment by nabobalis** [comment]
Hi @m11dedhia, go ahead. 

We have a guide here: https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html that will get you setup and some overview on how to start on the example gallery: https://docs.sunpy.org/en/latest/dev_guide/contents/example_gallery.html

**Comment by m11dedhia** [comment]
Sorry to disturb you @nabobalis but can you tell me how to load a blank map? I was able to use the example map given on the website but couldn't load a blank map. I went to `sunpy/data/_sample.py` but couldn't find anything useful.

**Comment by nabobalis** [comment]
I have no idea how to load a blank map. 

You might want to look at https://docs.sunpy.org/en/stable/generated/gallery/map/map_from_numpy_array.html#sphx-glr-generated-gallery-map-map-from-numpy-array-py for ideas. 

I don't know why you went into "sunpy/data/_sample.py" but that code deals with downloading data, there is nothing useful there.

**Comment by hayesla** [comment]
Hey @m11dedhia ! 

To do this you will probably need to create a blank map and then plot it. 

To create a blank map you need a data array of zeros, and then create a header. This can be done using the `sunpy.map.make_fitswcs_header`. An example of something similar is [this](https://docs.sunpy.org/en/stable/generated/gallery/map/map_from_numpy_array.html#sphx-glr-generated-gallery-map-map-from-numpy-array-py) example that @nabobalis linked. 

i.e. you would make the data array something like `data=np.zeros((1000, 1000))` in the example. 

do you have any experience with maps and FITS keywords/WCS before? I would suggest you also have a look at https://docs.sunpy.org/en/stable/guide/data_types/maps.html#creating-maps

**Comment by m11dedhia** [comment]
Okay, I was able to plot positions  on a blank map, I just wanted to confirm that the file is supposed to be saved in `examples/plotting` right? I'll be naming it as 'plotting_blank_maps.py'.

**Comment by nabobalis** [comment]
Sounds fine.
