### ISSUE TITLE
Document default keyword argument values to coordinate frames

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3249]
For example https://docs.sunpy.org/en/latest/api/sunpy.coordinates.frames.Helioprojective.html doesn't tell you `observer=` defaults to `"earth"`.

**Comment by Cubostar** [comment]
I can work on this! Sounds like a good way to learn more about how everything work too.

**Comment by Cadair** [comment]
@Cubostar great! let us know if you need a hand. :smile:
