### ISSUE TITLE
Update user agents for search and download

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3260]
This would make it easier for services like VSO to track what versions of Python (probably already in the user agent) and SunPy and parfive etc we are using for search and or download.

We could also change the user agent for our CI jobs so those could be filtered out of any stats.

**Comment by mridullpandey** [comment]
hello sir , i want to work on it, will you please explain it

**Comment by Raahul-Singh** [comment]
Could you please give more information regarding the implementation?

**Comment by Cadair** [comment]
The stack for SunPy's file downloader is sunpy > [parfive](https://github.com/Cadair/parfive) > aiohttp you need to work out how to pass the user agent headers through that stack into aiohttp.

**Comment by Raahul-Singh** [comment]
So, here's what I plan to do. Please let me know if I have understood this properly.
I'll make an appropriate `str` that will hold the information on `sunpy`, `python`, etc.
I will then pass it to existing `parfive.Downloader.enqueue_file()` as a `kwarg` with the key as `header`.
This will then pass it on to `aiohttp.ClientSession()` object as a header. Will anything more be required?

**Comment by Cadair** [comment]
I think that would work, but my concern with doing anything at the `enqueue_file` level is that we have to do it for each client and place which downloads files, rather than in one central place. If you feel up to the extra challenge coming up with a way (in parfive probably) to specify these things in a more session based way would be cool.

**Comment by Cadair** [comment]
You can use that to get the sunpy version (although `sunpy.__version__` is probably better), the issue is parfive doesn't know if sunpy is calling it. We probably need to add a feature to parfive where you can pass `aiohttp.ClientSession` variables to the `Downloader` constructor to save us having to pass them in to `enqueue_file` each time. See https://github.com/Cadair/parfive/issues/29 for a related issue (it also needs parameters to `ClientSession`).

**Comment by nabobalis** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/4110 I think.
