### ISSUE TITLE
Helper function for creating WCS object directly from FITS header

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3268]
Is there a function for creating an `astropy.wcs.WCS` object directly from a FITS header? I'm thinking of something along the lines of `Map.wcs`, but independent of `Map`. Ideally, I'd like to be able to create the `WCS` object directly from a FITS header without having to create a `Map`.

**Comment by Cadair** [comment]
You can create a WCS object just using the astropy API. However we add a `heliographic_observer` and `rsun` attributes to the WCS to carry the extra info, so you would need to do those manually.

A large part of Map is the infrastructure that supports doing this in a source independent way, so it's not really going to be an easy thing to fix.

**Comment by wtbarnes** [comment]
Yeah after looking at the way it is constructed in `Map`, it seems like it would be quite difficult to decouple...

**Comment by Cadair** [comment]
It is something I want to do, but it's a case of creating a meta object and a lot of other stuff. Shall we close this as a wont fix?
