### ISSUE TITLE
A potential sunpy.util.config() bug

### ISSUE THREAD

**Issue by kakirastern** [sunpy/sunpy#3270]
### Description

The sunpy.util.config.load_config() method at https://github.com/sunpy/sunpy/blob/master/sunpy/util/config.py not functioning as expected.
When running it in the `get_iris_response` function (under development) to check download file (with `check_download_file`), it threw an error as follows: 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-a8a19f9084e6> in <module>
----> 1 get_iris_response(time_obs=1.0941696e+09, response_version=4)

~/sunpy_repos/irispy-git/irispy/iris_tools.py in get_iris_response(time_obs, pre_launch, response_file, response_version, force_download, *args, **kwargs)
    151         # Check response file exists in download_dir.  If not, download it.
    152         check_download_file(response_filename, IRIS_RESPONSE_REMOTE_PATH, download_dir,
--> 153                             replace=force_download)
    154         # Define response file as path + filename.
    155         response_file = os.path.join(download_dir, response_filename)

~/sunpy_repos/sunpy-git/sunpy/util/net.py in check_download_file(filename, remotepath, download_dir, remotename, replace)
    236 
    237         download_file(urljoin(remotepath, remotename),
--> 238                       download_dir, default=filename, overwrite=replace)

~/sunpy_repos/sunpy-git/sunpy/util/net.py in download_file(url, directory, default, overwrite)
    195     opn = urlopen(url)
    196     try:
--> 197         path = download_fileobj(opn, directory, url, default, overwrite)
    198     finally:
    199         opn.close()

~/sunpy_repos/sunpy-git/sunpy/util/net.py in download_fileobj(opn, directory, url, default, overwrite)
    165     if overwrite and os.path.exists(path):
    166         path = replacement_filename(path)
--> 167     with open(path, 'wb') as fd:
    168         shutil.copyfileobj(opn, fd)
    169     return path

FileNotFoundError: [Errno 2] No such file or directory: '/Users/kastern/sunpy/data/iris_sra_c_20161022.geny'
```

### Expected behavior

I would expect if the method does not generate the missing directory then it at least returns the path of an existing say working directory other than an assumed directory path that has not been created yet at the time the error was produced. 

### Actual behavior

The code assumes that some path called `/Users/kastern/sunpy/data` existed on my machine. But it didn't, since I have my sunpy dev version installed at `/Users/kastern/sunpy_repos/sunpy-git` with the corresponding `data` folder at `/Users/kastern/sunpy_repos/sunpy-git/data`.

### System Details

  - SunPy Version: 1.1.dev181+g73eb7ec9d
  - Astropy Version: 3.2.1
  - Python Version: 3.7.3
  - OS information: macOs Mojave 10.14.5

**Comment by vn-ki** [comment]
> with the corresponding data folder at /Users/kastern/sunpy_repos/sunpy-git/data.

Did you change your sunpyrc to point it to there?

**Comment by kakirastern** [comment]
@vn-ki No, I don't think I have... But according to Stuart if the `Users/kastern/sunpy/data` folder is not already there then one should have been set up. He suggested me to create this issue.

**Comment by nabobalis** [comment]
Has this happened again?

**Comment by dstansby** [comment]
Can you provide a self contained example that triggers this error? Otherwise I am minded to close this
