### ISSUE TITLE
Add a link to maintainer list to developer docs

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3272]
### Description

The developer documentation should point to the current list of package maintainers so they know who to go to for help or discussion.

### Additional context

The maintainer list PR is currently not yet accepted but is in [PR](https://github.com/sunpy/sunpy.org/pull/177).

**Comment by Cubostar** [comment]
I can work on this! Which part(s) of the developer documentation should be changed (ex. README.md, CONTRIBUTING.rst, etc)?

**Comment by nabobalis** [comment]
That's a good question. I would suggest the stability documentation page.
