### ISSUE TITLE
Units and Coordinates page of the Guide should show a world_to_pixel example.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3278]
http://docs.sunpy.org/en/stable/guide/units-coordinates.html#physical-coordinates-in-sunpy

**Comment by pkj-m** [comment]
Hey I was thinking of using the example given here https://docs.astropy.org/en/stable/wcs/wcsapi.html for the sunpy docs for adding the example for `world_to_pixel`. Does that sound good? 
@Cadair
