### ISSUE TITLE
make it easy to access the UnifiedResponse table

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3279]
if you want to access keys you should be able to get at the table

**Comment by Raahul-Singh** [comment]
Could you please elaborate? :sweat_smile:

**Comment by Cadair** [comment]
oh man, I should open better issues.

I think this is that sometimes you want to be able to get at the table we print out when you `str(results)` from a `results = Fido.search(...)`, I don't think at the moment there is any property on `UnifiedResponse` which gives you that table.

**Comment by Raahul-Singh** [comment]
Would the table as a pandas dataframe be sufficient?

**Comment by sashank27** [comment]
@Cadair as far as I understand the issue, currently `UnifiedResponse` object has no helper function by which we can access the range of values obtained on `result` for specific values i.e. something like values of `results['Source']`.
Am I right?

**Comment by sashank27** [comment]
https://github.com/sunpy/sunpy/blob/4c563d9c7498f426e43266a6733e9662ddb2a6db/sunpy/net/dataretriever/client.py#L96-L109
This already converts the response into an `astropy.table.Table`, but uses only for printing nicely. Is there a way we can utilize it?
