### ISSUE TITLE
Remove sunpy.instr.aia.aiaprep

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3282]
The `aiaprep` function should be removed from the `sunpy.instr` subpackage. Any AIA specific functionality should transition to the new [`aiapy` package](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy).

This is part of the broader goal of moving instrument-specific functionality out of the core sunpy package and into affiliated packages.

**Comment by ayshih** [comment]
We'd have to go through a deprecation period before removal.  What's the planned timeline for `aiapy`?

A related question: what about `AIAMap`?  Should `aiapy` own that?

**Comment by Cadair** [comment]
I agree this should happen. I would want a release of aiapy to exist before we do this, so that the deprecation warning can point people to the new thing.

 > A related question: what about AIAMap ? Should aiapy own that?

I am not in favour of this. I would want core to be able to open files from as many instruments as possible without needing extra packages.

**Comment by ayshih** [comment]
> > A related question: what about AIAMap ? Should aiapy own that?
> 
> I am not in favour of this. I would want core to be able to open files from as many instruments as possible without needing extra packages.

It depends on how you define "open files".  We'd always be able to open arbitrary FITS files in some default manner.  The issue is that, by retaining `AIAMap`, we take responsibility for interpreting the header properly (e.g., the whole observer-coordinate business), plus we wouldn't be able to offer users the latest orientation calibration (in the case of stale headers).

Furthermore, what if an instrument wants to own their `Map`-derived class?  What if `aiapy` wants to have a `Map` class that does stuff like auto-detect needing to run `aia_prep`?  Do they hack SunPy's `AIAMap` as they import?  Do they replace the whole class?  Do they offer an alternative class (e.g., `TrueAIAMap`)?  All of the above seem undesirable to me.

**Comment by wtbarnes** [comment]
> We'd have to go through a deprecation period before removal. What's the planned timeline for aiapy?

👍 

> I agree this should happen. I would want a release of aiapy to exist before we do this, so that the deprecation warning can point people to the new thing.

There's not really a strict timeline either for development of the package or for a formal release of `aiapy`. Tentatively I would say there will be release (v0.1) in the next six months, but it could be sooner. I will update here as I know more.

> Furthermore, what if an instrument wants to own their Map-derived class? What if aiapy wants to have a Map class that does stuff like auto-detect needing to run aia_prep? Do they hack SunPy's AIAMap as they import? Do they replace the whole class? Do they offer an alternative class (e.g., TrueAIAMap)? All of the above seem undesirable to me.

I agree that instrument-specific tweaks should not be the responsibility`sunpy` core and I can definitely envision this scenario of many alternative diverging map implementations. However, the same may happen if instrument-specific map classes are farmed out to (future) instrument-specific affiliated packages. This is a much larger discussion and really deserves its own issue(s). At least in the short term, I do not think `aiapy` should own `AIAMap`.

For what it is worth, in `aiapy`, the current preferred approach is to make all of these things (e.g. aiaprep, header fixes, etc) explicit, i.e. the user has to pass their map to a function and get a corrected map out rather than having these things done "automagically" at import. For example, see [this issue](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/issues/14).

**Comment by wtbarnes** [comment]
There's currently a PR to the aiapy repo to implement aiaprep. It is essentially the exact version that is in `sunpy/instr/aia.py` though it also addresses #3307. I suspect it will be merged within a week or less.

**Comment by wtbarnes** [comment]
In light of SEP-0009, does this mean that a deprectation warning cannot be added until v2.0 and then the actual bit of code cannot be removed until v3.0?

**Comment by Cadair** [comment]
We can add a deprecation warning at any time, and it has to be in the code for at least one LTS (i.e for the 2.0 release). So if you added it now, the deprecation warning would be in 1.1, 2.0 and then we can remove the code before 2.1 (so in ~1 year).

I wouldn't want to merge a deprecation warning until aiapy has an official release though (deprecation warnings should always present a currently available way of not getting the warning).

**Comment by wtbarnes** [comment]
Ok that sounds good.

I don't have a definite timeline for an aiapy release yet, but ideally it will happen before the end of the year. Not sure if that will be before v1.1 or not.

**Comment by Cadair** [comment]
Planning on getting 1.1 out the door no later than the end of Oct.

**Comment by ayshih** [comment]
Re-opening because `aiaprep` was only deprecated, not removed.

**Comment by ayshih** [comment]
If we don't want to keep open an issue to remind us to remove a function that has been deprecated, then change the title of this issue so it doesn't look like we've done something that we haven't.
