### ISSUE TITLE
map.rotate doesn't take scale into account when padding image

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#3285]
### Description

Scale is not taking into account when padding the image, only rotation.  This results on cropped images when using magnification.   The opposite doesn't happen if you reduce the image.  The image retains its original dimension, even though the Sun is tiny.

### Expected behavior

The image should be padded to accommodate the entire scaled image when upscaling. 

### Actual behavior

Using a magnification in which the Sun's radius ends up larger than the original field of view keeps the original image dimension and crops anything that doesn't fit the new field of view.

This is because the padding is determined using:

```
        # Calculate the shape in pixels to contain all of the image data
        extent = np.max(np.abs(np.vstack((self.data.shape @ rmatrix,
                                          self.data.shape @ rmatrix.T))), axis=0)
```

It may be necessary to pad the image based on scale, prior to rotation

### Steps to Reproduce

Open any test map and use map.rotate(scale=4)   The resulting image is visibly cropped.

**Comment by Cubostar** [comment]
I can work on this!

**Comment by Raahul-Singh** [comment]
Please let me know if I have understood this correctly,
Currently, only the central region in the image is upscaled. This is done so that whatever area of the upscaled image fits the original dimensions of the image is taken. This results in cropping. What is required is that the entire image be upscaled according to the scaling factor. This will increase the dimensions of the image dramatically. But the user will be able to view any part of the original image.

**Comment by amunozj** [comment]
Hi! Currently the image is only padded to account for rotation and rotation only.   But it should be also padded, if the user is upscaling the size. As to wether this will result in a dramatic increase of dimensions, it depends on how dramatic the user is feeling that day. Note that a clever user, with little appetite for drama, could make a submap to crop the image first and _then_ upscale. But the way the function is currently implemented would not enable that either.

**Comment by dstansby** [comment]
Could you post a short and self contained example that shows what is going wrong?

**Comment by amunozj** [comment]
Of course.  In fact here is how I deal with it.  I think it makes the problem pretty obvious:

`scale_factor = 4

MDI_fits = fits.open(hr_path.replace('HR','raw') + hr_hmi_set.loc[inx, 'filepath_hr'].replace('_HR',''), cache=False)
MDI_fits.verify('fix')


MDImap = Map(MDI_fits[1].data, MDI_fits[1].header)
MDI_fits.close()


# Pad image, if necessary
target_shape = int(4096)

# Reform map to new size if original shape is too small


new_fov = np.zeros((target_shape, target_shape)) * np.nan
new_meta = MDImap.meta

new_meta['crpix1'] = new_meta['crpix1'] - MDImap.data.shape[0] / 2 + new_fov.shape[0] / 2
new_meta['crpix2'] = new_meta['crpix2'] - MDImap.data.shape[1] / 2 + new_fov.shape[1] / 2

# Identify the indices for appending the map original FoV
i1 = int(new_fov.shape[0] / 2 - MDImap.data.shape[0] / 2)
i2 = int(new_fov.shape[0] / 2 + MDImap.data.shape[0] / 2)

# Insert original image in new field of view
new_fov[i1:i2, i1:i2] = MDImap.data[:, :]

# Assemble Sunpy map
MDImap = Map(new_fov, new_meta)
MDImap = MDImap.rotate(scale=scale_factor, recenter=True)


# # Crop HMI image to desired shape
sz_x_diff = (MDImap.data.shape[0]-target_shape)//2
sz_y_diff = (MDImap.data.shape[0]-target_shape)//2

print(MDImap.meta['crpix1'])
print(MDImap.meta['crpix2'])

MDImap.meta['crpix1'] = MDImap.meta['crpix1']-sz_x_diff
MDImap.meta['crpix2'] = MDImap.meta['crpix2']-sz_y_diff

MDImap = Map(MDImap.data[sz_x_diff:sz_x_diff+target_shape, sz_y_diff:sz_y_diff+target_shape].copy(), MDImap.meta)`
