### ISSUE TITLE
Loading libraries warning when using sunpy-dev Anaconda environment

### ISSUE THREAD

**Issue by Cubostar** [sunpy/sunpy#3289]
### Description

When running what seems to be any code in the sunpy-dev Anaconda environment, a warning about missing the openjp2 and openjpeg libraries appears.

### Expected behavior

No warning.

### Actual behavior

```
UserWarning: Neither the openjp2 nor the openjpeg library could be loaded.  
  warnings.warn(msg)
```

### Steps to Reproduce

I've tried this on different files of code. The most relevant instance is when I run this:
```
from sunpy.net.helioviewer import HelioviewerClient


def main():
    client = HelioviewerClient()
    client.download_jp2("2012/01/01", observatory="SOHO",
                        instrument="MDI", measurement="continuum")


main()

```
The progress bar remains at 0% and exits without an error message. I can not find the file that should have downloaded, so I assume that the file was not downloaded.

### System Details

  - SunPy Version: Developer version, particularly my branch `progressbar-feat`
  - Astropy Version: 3.2.1
  - Python Version: 3.7.3 64-bit
  - OS information: MacOS Mojave 10.14.6

**Comment by Cadair** [comment]
these two things should not be related. The lack of `openjp2` should only matter when you are opening a jp2 file with Map. The download should work fine irrespective of if you have the libs to read the file.
