### ISSUE TITLE
JSOCClient.search_metadata ignores jsoc.attrs.Keys

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3293]
The `search_metadata` method on `JSOCClient` returns all keys even if a list of keys is specified with `jsoc.attrs.Keys`. However, when using `search`, only the requested keys are returned.

**Comment by wtbarnes** [comment]
Well I found the reason: https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py#L769

Is there a good reason this line is there though? Why should searching the metadata only imply that we want all of the keys? At the very least, ignoring the supplied keys feels a bit odd.

**Comment by wtbarnes** [comment]
Additionally, why does `search_metadata` return a pandas DataFrame ( https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py#L840) while `search` returns an astropy Table?

**Comment by Cadair** [comment]
> why does `search_metadata` return a pandas DataFrame

We should probably cast that to a table.

**Comment by wtbarnes** [comment]
As `search_metadata` is deprecated by #4358, this change is unneeded.
