### ISSUE TITLE
TimeSeriesMetaData isn't a valid metadata type to TimeSeries factory

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3295]
Dict like objects are fine, but our own metadata object isn't!!

**Comment by sadielbartholomew** [comment]
I'll have a go at fixing this for Hacktoberfest, if that is okay?

**Comment by nabobalis** [comment]
@sadielbartholomew that is perfectly fine.

**Comment by hayesla** [comment]
hey @sadielbartholomew how did you get on with this?:)

**Comment by sadielbartholomew** [comment]
Hi there @hayesla, I didn't get onto this sadly. I'm still happy to give it a go but it will be a week or two before I can put in a PR, so if someone else wants or needs to take over I completely understand. Sorry for being a bit optimistic about how much I could do for Hacktoberfest!

**Comment by hayesla** [comment]
Hey @sadielbartholomew  - no worries just wanted to check in to see if you needed any assistance with it :)

**Comment by Raahul-Singh** [comment]
@sadielbartholomew  hi, are you still working on this?

**Comment by sadielbartholomew** [comment]
Hi, due to unanticipated events I never got to start this, sorry! Please consider me unassigned as I don't think I will have time to address this. I'll let someone else step in.

**Comment by Raahul-Singh** [comment]
Um. I have a doubt. When you say ``Dict like objects are fine, but our own metadata object isn't!!``, do you mean that the there shouldn't be a separate metadata object and we should use a simple dictionary or do you mean that there is a bug in the custom object?

**Comment by nabobalis** [comment]
The latter. It seems that we can't pass in our own metaclass to create a timesseries (how was there not a test for this?)
