### ISSUE TITLE
GenericClient could provide a much nicer interface for _can_handle_query

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3306]
Currently `_can_handle_query` takes the whole query as an argument and returns `True` or `False` as a way of determining if the client should be used for the given query.

With some work we could have a helper method on `dataretriever.GenericClient` which returns a list of attrs with which it should match. i.e. `a.Time(start, end), a.Instrument("AIA"), a.Wavelength(start, end)`.

While this would not be as flexible (it can only match the intersection of all provided) it would cover many of the usecases we have in dataretriever at the moment.

**Comment by Cadair** [comment]
@ehsteve one for the list...

**Comment by Cadair** [comment]
In much the same way, this could be integrated with https://github.com/sunpy/sunpy/blob/master/sunpy/net/attr.py#L140 to be able to introspect the values.

**Comment by DShivansh** [comment]
Please correct me if I am wrong.
@Cadair do you mean that from all the attributes that one passes, we pass each attribute from all the _can_handle_queries function implemented by each source and all the queries which return true from all the functions are put in a list and stored?
