### ISSUE TITLE
aiaprep should support additional kwargs to Map.rotate

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3307]
The `aiaprep` function in `instr/aia` is essentially just a wrapper around `Map.rotate` and should also support the following additional `kwargs` to `Map.rotate`:

* `order` The order of the interpolation scheme
* `use_scipy` Flag for using scipy for the affine transform

**Comment by larrymanley** [comment]
We should also be able to specify the plate scale (default of 0.6 for AIA; 0.5 for HMI, or 0.6 if compositing HMI and AIA).
Also `missing` `kwarg` to `Map.rotate`

**Comment by mridullpandey** [comment]
can i take this up @wtbarnes

**Comment by Cadair** [comment]
This issue is on hold pending resolution of https://github.com/sunpy/sunpy/issues/3282. It's very likely we will be deprecating `instr.aia` in the near future.

**Comment by wtbarnes** [comment]
In light of #3282,  this is no longer applicable.
