### ISSUE TITLE
Passing glob pattern to Map returns unsorted list of Maps

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3318]
When passing a glob pattern to `sunpy.map.Map`, the list of maps that it returns is not sorted, even if the filenames in the glob can be sorted, e.g. by time.

For example,

```python
from sunpy.map import Map
maps = Map('/path/to/my/files/*.fits')  # these maps are not sorted!
```

where all of the filenames in `'/path/to/my/files/'` include a timestamp such that they can be sorted sequentially. The resulting list of files, `maps`, is not sorted.

The reason for this is that [we are using `glob.glob()` to get the list of files in the case that the user passes in a pattern](https://github.com/sunpy/sunpy/blob/master/sunpy/map/map_factory.py#L214) and `glob()` does not sort the resulting list of files by default.

This can easily be solved by just wrapping a `sorted` argound `glob.glob(...)`. The question is do we want to make the choice to sort the files for the user? I find it a bit unexpected that the resulting Maps are not sorted if the filenames allow for it.

**Comment by Cadair** [comment]
I think this is probably a good idea, although I would suggest it should be thought of as a new feature rather than a bug.

**Comment by wtbarnes** [comment]
Just going to leave [this](https://www.vice.com/en_us/article/zmjwda/a-code-glitch-may-have-caused-errors-in-more-than-100-published-studies) here...

**Comment by wtbarnes** [comment]
Just to add to this, apparently whether the result of `glob.glob` is sorted or not is OS-dependent so currently the order of the Maps you get back from `Map('*')` may vary depending on whether you're on Linux or Windows...

**Comment by Cadair** [comment]
I think we should at least be consistent, so adding a `sorted` around the glob call would be a good place to start. 
I also think that it would be counter intuitive to sort over different positional arguments to `Map`, I would expect them to come back in that order if they were just filenames.
