### ISSUE TITLE
SunPy import python check uses Python 3.6 syntax

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3319]
Line 25 in `__init__.py` checks for the python version but assumes at least Python 3.6 since it uses an f-string.

```python

raise UnsupportedPythonError(f"sunpy does not support Python < {__minimum_python_version__}")
```
This means that users with versions below 3.6 will not actually see the intended output but will just get a less helpful error. This line should be able to run in Python 2.

**Comment by nabobalis** [comment]
Didn't we patch this already?
