### ISSUE TITLE
[1.0.3] test_print_config_files fails with installed sunpy

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#3329]
### Description

On Debian, we run the provided tests regularly on the installed package ("CI test") to ensure that it still works in the current environment. 
With Version 1.0.3 (or before; I didn't check 1.0 … 1.0.2), I see the following failure:

### Actual behavior
`print_test_config_files` tries to write to the installed package, which is denied for an ordinary user:
```
_____________________________________ test_print_config_files _____________________________________

undo_download_dir_patch = None

    def test_print_config_files(undo_download_dir_patch):
        # TODO: Tidy this up.
        stdout = sys.stdout
        out = io.StringIO()
        sys.stdout = out
>       print_config()

/usr/lib/python3/dist-packages/sunpy/util/tests/test_config.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3/dist-packages/sunpy/util/config.py:107: in print_config
    for file_ in _find_config_files():
/usr/lib/python3/dist-packages/sunpy/util/config.py:69: in _find_config_files
    config_path = Path(_get_user_configdir())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _get_user_configdir():
        """[…]"""
        configdir = os.environ.get('SUNPY_CONFIGDIR', CONFIG_DIR)
    
        if not _is_writable_dir(configdir):
>           raise RuntimeError(f'Could not write to SUNPY_CONFIGDIR="{configdir}"')
E           RuntimeError: Could not write to SUNPY_CONFIGDIR="/usr/lib/python3/dist-packages/sunpy/data"
```
This also happens when I explicitly set `SUNPY_CONFIGDIR` to a different directory; the path mentioned in the `RuntimeError` then still is `/usr/lib/python3/dist-packages/sunpy/data`.

### Steps to Reproduce

```
$ cd /tmp
$ SUNPY_CONFIGDIR=/tmp python3 -c "import sunpy; exit(sunpy.self_test(args=\"-k 'not figure and not online'\"))"
```

### System Details

  - SunPy Version: 1.0.3
  - Astropy Version: 3.2.1
  - Python Version: 3.7.4
  - OS information: Debian unstable

**Comment by nabobalis** [comment]
Thanks for the report, I will try figure out what seems like 2 separate bugs are here. 

The test is safe enough to skip, so if that helps, you can do that!

**Comment by olebole** [comment]
I marked it as xfail until it is fixed.

**Comment by nabobalis** [comment]
So the first problem is the test suite is setup to create a tempdir to use as the config whenever you run the tests. The pytest fixture is in our `conf_test.py`.  This was set to use the file and then a new dir instead of a tmp_dir. I changed this and with `sudo chown` to root, the test suite run and didn't fail.
