### ISSUE TITLE
Return VSO errors to the user

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3338]
Currently we hide any VSO error codes from the user at Search time. If there is a reliable way we can extract this info we should throw warnings or similar.

From #3331 we can see that under certain conditions we get an error key in the returned XML from the VSO:
```
DEBUG: VSO Response:
 <soap:Envelope xmlns:VSO="http://virtualsolar.org/VSO/VSOi" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <VSO:QueryResponse>
      <body>
        <provideritem>
          <error>VSO-D404 Bad Request -- Invalid Time Sample : contains non digit</error>
          <provider>SSC</provider>
          <version>1</version>
        </provideritem>
      </body>
    </VSO:QueryResponse>
  </soap:Body>
</soap:Envelope>
```

The question here is, is this layout consistent over all providers and error types the VSO might throw back at us, so should we be parsing this and raising it as a warning during `VSOClient.search`.

**Comment by Cadair** [comment]
From speaking to VSO folk, to parse this we should check to see if there is a `<error>` key in the `<provideritem>` and if there is return the contents of the error key. `<provider>` will only exist if the error is from the provider rather than the VSO core.

There are docs on the VSO error code (in this case `D404`), both for the [letter](https://sdac.virtualsolar.org/cgi/show_details?keyword=STATUS_TYPE) and [number](https://sdac.virtualsolar.org/cgi/show_details?keyword=STATUS_LONG)

There is also apparently sometimes a  `<warning>` key in `<provideritem>` which includes importantly if JSOC has gone into summary mode (i.e. is shipping you tar files).

**Comment by jains8844** [comment]
I would like to work upon this issue

**Comment by nabobalis** [comment]
@jains8844 go ahead, you don't need permission to work on open issues.

**Comment by jains8844** [comment]
I was going through the JSOC one. The page [https://docs.virtualsolar.org/wiki/DataProviderJSOC_SHA#no1](url) shows that JSOC provider serves data for AIA and HMI instruments.
I tried 
`client.search(vso.attrs.Time(datetime(2010, 1, 1), datetime(2010, 1, 1, 1)),vso.attrs.Instrument('aia'))` 
but it results into an `XMLParseError` from zeep client `Unexpected element 's-gensym3'` and the same thing happens on HMI too.

**Comment by jains8844** [comment]
For the VSO replacing [https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L367](https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L367) with
`resp=self.api.service.Query(
                        QueryRequest(block=block)
                    )
                for i in resp:
                    if(i['error']):
                        warnings.warn(i['error'], SunpyUserWarning)
                responses.append(
                    VSOQueryResponse(resp)
                )`
would raise a `SunpyUserWarning` of the error message received from the client. Would that be sufficient ?

**Comment by jains8844** [comment]
resp=self.api.service.Query(
                        QueryRequest(block=block)
                    )
                for i in resp:
                    if(i['error']):
                        warnings.warn(i['error'], SunpyUserWarning)
                responses.append(
                    VSOQueryResponse(resp)
                )

For VSO replacing [https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L367](https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L367) with something like the lines would raise a `SunpyUserWarning` of the error message recieved. Would it suffice ?

**Comment by jains8844** [comment]
Any comments ??

**Comment by nabobalis** [comment]
Implement it, open a PR and we can discuss it there.

**Comment by jains8844** [comment]
Okay
