### ISSUE TITLE
ImageAnimatorWCS does not preserve WCSAxes settings across animation frames

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3348]
### Description
If you run the [ImageAnimatorWCS example](http://docs.sunpy.org/en/stable/generated/gallery/plotting/imageanimatorwcs.html) the second plot that is show has custom tick placement and labels.

### Expected behavior
All the customisations take effect and remain in effect as the animation changes.

### Actual behavior
1) The axis labels are never drawn
2) When you move the slider, or change the frame, the plot reverts to default settings.

### Steps to Reproduce
Run the [ImageAnimatorWCS example](http://docs.sunpy.org/en/stable/generated/gallery/plotting/imageanimatorwcs.html).

**Comment by abhijeetmanhas** [comment]
@Cadair is this issue resolved? I guess it is.

**Comment by nabobalis** [comment]
It looks unresolved.

**Comment by abhijeetmanhas** [comment]
The examples to which links are provided are no longer available, _`imageAnimatorWCS` is deprecated since 1.1, and to be removed in 2.1_ is written in docs. Is the issue present in other animators too?

**Comment by nabobalis** [comment]
I think it was renamed to `ArrayAnimatorWCS`.

**Comment by abhijeetmanhas** [comment]
![Figure_1](https://user-images.githubusercontent.com/43112347/72200156-b3beea80-346b-11ea-85e4-10d7eb2953f9.png)
I ran the the first example in the gallery https://docs.sunpy.org/en/latest/generated/gallery/plotting/arrayanimatorwcs.html#sphx-glr-generated-gallery-plotting-arrayanimatorwcs-py , I found that axis labels are not shown, but if we define `coord_params` , then they are visible.

**Comment by nabobalis** [comment]
I think that the fact it needs coord_params to display any labels is a bug and the other bug is if you move the slider, the labels go again.

**Comment by abhijeetmanhas** [comment]
Understood now, Thanks :). I will work on it.

**Comment by Cadair** [comment]
It's possible that this is fixed in `ArrayAnimatorWCS` but I am not sure.

**Comment by nabobalis** [comment]
If I run the example now, this is fixed.
