### ISSUE TITLE
Add a mosaicing example to the gallery

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3353]
Now astropy/reproject#186 is merged, I tested it out with AIA and EUVI data. The result was awesome: https://nbviewer.jupyter.org/gist/Cadair/3e96550441433c7d7d4219f076d8b558

At some point that should be put into the example gallery.

It requires #3350 and also code currently in astropy/reproject#52

**Comment by wafels** [comment]
Why does this require the deforest reprojection function? What happens if you use an existing function?

**Comment by Cadair** [comment]
It doesn't require the deforest reprojection function, it works fine with the `reproject_interp` function, but there are some other unrelated fixes on the `deforest` branch that this example needs to work.
