### ISSUE TITLE
Implement differential rotation on the coordinate transform graph

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3357]
During my recent work on reprojection, I was pondering how we could utilise the `reproject` package with it's different algorithms for resampling to our differential rotation warping code. One way to do this is to just swap out the call to `skimage.warp` with a call to `map_coordinates` inside reporoject (i.e using the [DeForest (2003)](https://www.boulder.swri.edu/~deforest/Papers_files/Sol%20Phys%202004%20Deforest.pdf)) algorithm.

What I am suggesting here is a potential way to be able to use `reproject` directly for this. To do this we would need to add the differential rotation models to the astropy transform graph. I think we could do this as one static `DifferentialRotationHeliographic` frame, which takes the rotation model name, new obstime, and new observer as parameters and then when transforming into this frame the differential rotation model would be applied. (I think that transforming out of it to HGS wouldn't do anything but I would need to think about that).

Having done this, all that would be needed to add to reproject is a `via=` keyword argument which provides an intermediate frame to transform through when doing the `pixel_to_pixel` transform.

I think implementing this like this would also make the logic of the differential rotation code a little simpler, as the observer corrections and other transform changes would become an implicit part of the transform graph, i.e if you wanted to transform from a HGS frame to a diff rot frame with a different observer the coordinate transform graph would do:
```
HGS(observer=obs_1, obstime=time_1) -> HGS(observer=obs_2, obstime=time_2) -> DiffRot(observer=obs_2, obstime=time_2)
```

@ayshih @wafels @wtbarnes

**Comment by ayshih** [comment]
Hmm, interesting!  I worry that there are may be some thorny details as I ponder how this might be implemented, but it's worth looking into.

**Comment by Cadair** [comment]
Yeah I have been pondering it as well, I think it's unlikely to just work "out of the box" with reproject from chatting to Tom, but there are things we could do to make a middle ground work.

I think the differential rotation frame would have to have a asymmetric transform, i.e it applies differential rotation HGS -> Diffrot but not Diffrot -> HGS, then if you wanted to go the other way you could do it explicitly by doing Diffrot -> Diffrot with a negative delta t.

**Comment by wafels** [comment]
Would be nice to be able to also specify the number of pixels/cdelt for the output map.

**Comment by Cadair** [comment]
reproject works by giving it an output WCS so that would achieve that as well.
