### ISSUE TITLE
Generalise QueryResponse

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3368]
Currently each Fido client has a `QueryResponse` object.

* [VSO](https://github.com/sunpy/sunpy/blob/master/sunpy/net/vso/vso.py#L148)
* [JSOC](https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py#L34)
* [dataretriever](https://github.com/sunpy/sunpy/blob/master/sunpy/net/dataretriever/client.py#L55)

It should also be noted that the HEK client directly uses a customised version of `astropy.table`: https://github.com/sunpy/sunpy/blob/master/sunpy/net/hek/hek.py#L123

To address #3321 we need to allow each DR client to customise the columns in the `QueryResponse` object for their search, and return row metadata for each result. Providing an intermediate data structure to do this (i.e a list of dicts) seems just a complex, so it's probably easier to have the DR client return a `QueryReponse` object directly.

To facilitate this we would want the API of the `QueryReponse` object to be much cleaner than it is at the moment.

Given the use of `astropy.table` in all the `QueryReponse` objects for display and the customisation of astropy table in `HEK` I think something based closely on astropy table would be a good way of doing this.

**Comment by ehsteve** [comment]
What about solving the problem of clients being able to state what they can handle? Would that information also be held by a QueryResponse object? Perhaps the scope of this object should grow and the name should be changed?

**Comment by Cadair** [comment]
I think it's wise to keep the scope of this to strictly the output phase of search and input to fetch.

The saying what you can handle stuff would be better done using attrs imo (I think I have a half-baked proto plan for that in the back of my head as well, but am prioritising this as it's user facing)
