### ISSUE TITLE
Selftests fail with dask.array error

### ISSUE THREAD

**Issue by JimmyG-UNN** [sunpy/sunpy#3369]
### Description

Sunpy self tests fail with  --AttributeError: module 'dask.array' has no attribute 'Array'

### Expected behavior

pass selftests.

### Actual behavior

errors similar to:  See attachment for full output
[sunpy-selftest-errors.txt](https://github.com/sunpy/sunpy/files/3652916/sunpy-selftest-errors.txt)

________________________________________________________ ERROR collecting coordinates/tests/test_utils.py ________________________________________________________
/usr/local/Anaconda3-4.4.0/lib/python3.6/site-packages/sunpy/coordinates/tests/test_utils.py:9: in <module>
    import sunpy.map
/usr/local/Anaconda3-4.4.0/lib/python3.6/site-packages/sunpy/map/__init__.py:4: in <module>
    from sunpy.map import sources
/usr/local/Anaconda3-4.4.0/lib/python3.6/site-packages/sunpy/map/sources/__init__.py:11: in <module>
    from .. map_factory import Map
/usr/local/Anaconda3-4.4.0/lib/python3.6/site-packages/sunpy/map/map_factory.py:33: in <module>
    SUPPORTED_ARRAY_TYPES += (dask.array.Array,)
E   AttributeError: module 'dask.array' has no attribute 'Array'

YES - not obvious what the problem is

### Steps to Reproduce

1. Install as instructed with all requisites:
    conda config --add channels conda-forge
    conda install sunpy
    conda install numpy scipy astropy pandas parfive matplotlib sqlalchemy scikit-image glymur \
         beautifulsoup4 drms zeep tqdm asdf python-dateutil tox hypothesis pytest-astropy \
         pytest-cov pytest-mock

       Versions installed checked with:
     conda list | grep -i -e sunpy -e python -e numpy -e scipy -e astropy -e pandas -e parfive -e matplotlib -e sqlalchemy -e scikit-image -e glymur -e beautifulsoup4 -e drms -e zeep -e tqdm -e asdf -e python-dateutil -e tox -e hypothesis -e pytest-astropy -e pytest-cov -e pytest-mock

asdf                      2.3.1                      py_0    conda-forge
astropy                   3.2.1            py36h516909a_0    conda-forge
beautifulsoup4            4.8.0                    py36_0    conda-forge
drms                      0.5.7                      py_0    conda-forge
glymur                    0.8.18             pyh24bf2e0_0    conda-forge
hypothesis                4.36.2                   py36_0    conda-forge
matplotlib                3.1.1                    py36_1    conda-forge
matplotlib-base           3.1.1            py36he7580a8_1    conda-forge
msgpack-python            0.6.2            py36hc9558a2_0    conda-forge
numpy                     1.17.2           py36h95a1406_0    conda-forge
pandas                    0.25.1           py36hb3f55d8_0    conda-forge
parfive                   1.0.0                      py_1    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
pytest-mock               1.10.4                   py36_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
scikit-image              0.15.0           py36hb3f55d8_2    conda-forge
scipy                     1.3.1            py36h921218d_2    conda-forge
sqlalchemy                1.3.8            py36h516909a_0    conda-forge
sunpy                     1.0.3            py36h516909a_0    conda-forge
tox                       3.14.0                     py_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
zeep                      3.4.0                      py_0    conda-forge

2.Run Self tests:
    python
    Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
     >>> import sunpy
     >>> sunpy.self_test()

### System Details

  - SunPy Version:1.0.3
  - Astropy Version:3.2.1
  - Python Version:3.6.7
  - OS information:debian jessie/sid  (Linux 4.4.0-87-generic x86_64) - Ubuntu 14.04.5 LTS

**Comment by Cadair** [comment]
What version of dask do you have installed? Looks like they changed their API.

@wtbarnes

**Comment by JimmyG-UNN** [comment]
Hi,
I have the following versions installed.

conda list | grep -i -e dask
dask                      2.4.0                      py_0    conda-forge
dask-core                 2.4.0                      py_0    conda-forge

Regards

Jimmy

**Comment by Cadair** [comment]
Ok, so I can't reproduce this on my dev setup (which isn't using conda):

```
>>> import dask
>>> dask.__version__
'2.4.0'
>>> import dask.array
>>> print(dask.array.Array)
<class 'dask.array.core.Array'>
```

So this might be a conda specific thing, or something else.

**Comment by JimmyG-UNN** [comment]
Hi,  I've just tried your code and get the following:

``$ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask
>>> dask.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dask' has no attribute '__version__'
>>> import dask.array
>>> print(dask.array.Array)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dask.array' has no attribute 'Array'
>>> 
``

So something is obviously wrong with my installation.

Anyone any ideas what?

Regards

Jimmy

**Comment by Cadair** [comment]
that's interesting. Can you just try reinstalling dask with conda?

**Comment by JimmyG-UNN** [comment]
Just tried uninstalling and reinstalling dask.

Then ran your code with the same output!

**Comment by JimmyG-UNN** [comment]
I have to leave soon, so will get back to this tomorrow

**Comment by JimmyG-UNN** [comment]
Back on this now.

Given that my anaconda installation is screwed I decided to re-install Anaconda and start from scratch.

Ive installed Anaconda3 v 5.3.1 in a modules environment so it's easier to manage.

All has gone well and the dask test run's OK now, but reports a different version:
`# python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask
>>> dask.__version__
'0.19.1'
>>> import dask.array
>>> print(dask.array.Array)
<class 'dask.array.core.Array'>
`
No the sunpy tests has different errors:
`# python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sunpy
>>> sunpy.self_test()
Traceback (most recent call last):
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 381, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/sunpy')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 412, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/sunpy/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/_pytest/config/__init__.py", line 418, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 296, in load_module
    six.exec_(co, mod.__dict__)
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/sunpy/conftest.py", line 13, in <module>
    import sunpy.tests.helpers
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/sunpy/tests/helpers.py", line 10, in <module>
    from matplotlib.testing import compare
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 285, in <module>
    _update_converter()
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/matplotlib/testing/compare.py", line 267, in _update_converter
    mpl._get_executable_info("gs")
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/matplotlib/__init__.py", line 351, in _get_executable_info
    return impl([e, "--version"], "(.*)", "9")
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/matplotlib/__init__.py", line 333, in impl
    if min_ver is not None and version < min_ver:
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
ERROR: could not load /usr/share/modules/apps/anaconda3/5.3.1/lib/python3.7/site-packages/sunpy/conftest.py

4
>>>`

All of the pre-requisites look to be installed OK:
`conda list | grep -i -e sunpy -e python -e numpy -e scipy -e astropy -e pandas -e parfive -e matplotlib -e sqlalchemy -e scikit-image -e glymur -e beautifulsoup4 -e drms -e zeep -e tqdm -e asdf -e python-dateutil -e tox -e hypothesis -e pytest-astropy -e pytest-cov -e pytest-mock
asdf                      2.3.1                      py_0    conda-forge
astropy                   3.2.1            py37h516909a_0    conda-forge
beautifulsoup4            4.8.0                    py37_0    conda-forge
drms                      0.5.7                      py_0    conda-forge
glymur                    0.8.18             pyh24bf2e0_0    conda-forge
hypothesis                4.36.2                   py37_0    conda-forge
ipython                   6.5.0                    py37_0  
ipython_genutils          0.2.0                    py37_0  
matplotlib                3.1.1            py37h5429711_0  
msgpack-python            0.5.6            py37h6bb024c_1  
numpy                     1.15.1           py37h3b04361_0  
numpy-base                1.15.1           py37h81de0dd_0  
numpydoc                  0.8.0                    py37_0  
pandas                    0.25.1           py37hb3f55d8_0    conda-forge
parfive                   1.0.0                      py_1    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
pytest-mock               1.10.4                   py37_0    conda-forge
python                    3.7.4                h265db76_1  
python-dateutil           2.8.0                      py_0    conda-forge
scikit-image              0.14.2           py37hf484d3e_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
sqlalchemy                1.3.8            py37h516909a_0    conda-forge
sunpy                     1.0.3            py37h516909a_0    conda-forge
tox                       3.12.1                     py_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
zeep                      3.4.0                      py_0    conda-forge
`

Have you any idea how I solve this new problem?

Regards

Jimmy

**Comment by Cadair** [comment]
I am rather stumped by that, it looks like it's an error coming out of inside matplotlib (not being triggered by anything in sunpy other than the import). I think you should be ok running sunpy (it looks like that fail is just related to running the tests).

The only other suggestion I have is to follow the instructions in the documentation for conda-forge: https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge and create a new conda environment to run sunpy in (see here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands)

**Comment by JimmyG-UNN** [comment]
Hi, 

Thanks for the information.

As suggested I have installed sunpy into it's own environment, this time using miniconda instead of anaconda.

The sunpy tests now run, passing 1368 tests and only failing 10.  So this is definitely progress.

I've attached the output from the self tests.

[sunpy-selftest-miniconda-env.txt](https://github.com/sunpy/sunpy/files/3658538/sunpy-selftest-miniconda-env.txt)

Do you think I can ignore the 10 failures?

Regards

Jimmy

**Comment by Cadair** [comment]
yeah I think you can safely ignore those. They all look asdf related.

I think we probably need to update our install instructions with regards to conda, to recommend miniconda and the conda-forge instructions. cc @ehsteve 

I am glad you are up and running @JimmyG-UNN, do let us know, here, on the mailing list or in chat if you need any more advice with anything :smile:
