### ISSUE TITLE
Mangled filename when downloading MDI data from VSO using Fido

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#3372]
### Description

When downloading MDI data from VSO the files are saved with incorrect filenames, parts of the content-encoding header are being included in the file name. It looks like the headers are not being set correctly on the response sent from VSO but this may not be easily fixed so a work around may be required.

### Expected behavior

Files to be saved with the correct filename

### Actual behavior

Files are not save with the correct filename

### Steps to Reproduce

```python
results = Fido.search(a.Time('2011/1/1 01:00', '2011/1/1 01:02'), a.Instrument(hmii') | a.Instrument('mdi'))
files = Fido.fetch(results[:,0])
print(files)
['/Users/shane/sunpy/data/hmi_ic_45s_2011_01_01_01_01_30_tai_continuum.fits', '/Users/shane/sunpy/data/mdi_vw_v_9466622_9466622.tar"\\nContent-transfer-encoding: binary']
```
### System Details

  - SunPy Version: 1.0.2
  - Astropy Version: 3.2.1 
  - Python Version: 3.7.0
  - OS information: macOS 10.14.6

**Comment by Cadair** [comment]
This is really a bug with the VSO, when doing the http request to download the MDI file you get the following response:

```
$ http -v GET "http://vso3.stanford.edu/cgi-bin/drms-export-sha.cgi?series=mdi__fd_M_96m_lev182;compress=rice;record=98611-98611"                                                                                                                                                          
GET /cgi-bin/drms-export-sha.cgi?series=mdi__fd_M_96m_lev182;compress=rice;record=98611-98611 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: vso3.stanford.edu
User-Agent: HTTPie/1.0.3



HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Disposition: attachment; filename="mdi_fd_M_96m_lev182_98611_98611.tar"\nContent-transfer-encoding: binary
Content-Type: application/octet-stream
Date: Thu, 26 Sep 2019 10:15:39 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 mod_nss/1.0.14 NSS/3.28.4 mod_wsgi/3.4 Python/2.7.5
Transfer-Encoding: chunked
```

The issue is with the content disposition header:

```
Content-Disposition: attachment; filename="mdi_fd_M_96m_lev182_98611_98611.tar"\nContent-transfer-encoding: binary
```

This is an invalid content disposition header (as far as I can tell by reading [RFC 6266](https://tools.ietf.org/html/rfc6266). [parfive](https://github.com/Cadair/parfive/blob/master/parfive/utils.py#L31) uses the stdlib [`cgi.parse_header`](https://docs.python.org/3.7/library/cgi.html#cgi.parse_header) function to extract the filename from the header. I am assuming that that (very old) bit of the stdlib is pretty robust and correct.

I have reported this to the VSO folk, who are looking into fixing it.

**Comment by samaloney** [comment]
Another option might be to handle this in the vso client code specifically in`mk_filename` function in this area https://github.com/sunpy/sunpy/blob/558707fd840c47ce9f6599288b37d1aa2ed54c60/sunpy/net/vso/vso.py#L412-L419

which seems to be passed to parfive here

https://github.com/sunpy/sunpy/blob/558707fd840c47ce9f6599288b37d1aa2ed54c60/sunpy/net/vso/vso.py#L840-L843

**Comment by Cadair** [comment]
huh, yeah that's where it would need fixing, how come we didn't switch that to parfive I wonder. I am certainly happier about fixing it specifically in the VSO code.

**Comment by mbobra** [comment]
We don't have to use VSO to fetch MDI data; we can use JSOC (in the same way we use it to fetch HMI and AIA data). The path in the error message that includes `series=mdi__fd_M_96m_lev182` is referring to the drms series `mdi.fd_M_96m_lev182`.

**Comment by Cadair** [comment]
Would be interesting to double check this issue isn't present on JSOC as well, according to the VSO team the issue is in the DRMS C code.

**Comment by mbobra** [comment]
I don't think JSOC has any issues at the moment. I tried using the web interface as well as the `drms` package and both worked fine for me. @samaloney I am not exactly sure what time you are querying so I picked a random time in the code block below, which works for me (with the correct e-mail address): 

```
import drms
c = drms.Client(email='person@email.address', verbose=True)
keys, segments = c.query('mdi.fd_M_96m_lev182[2010.04.17/24h]', key='T_REC', seg='data')
segments.data[0]
mdidata = c.export('mdi.fd_M_96m_lev182[2010.04.17/24h]{data}')
mdidata.urls.url[0]
```

**Comment by Cadair** [comment]
You can also do this (arguably :wink:) with a nicer interface with Fido:
```python
Fido.search(a.Time("2010/04/17 00:00", "2010/04/18 00:00"), a.Sample(24*u.hour), a.jsoc.Series("mdi.fd_M_96m_lev182"), a.jsoc.Notify("person@email.address"))
```

**Comment by Cadair** [comment]
@mbobra your example doesn't result in a URL which specifies a filename at all, so definitely isn't subject to the bug :rofl:

**Comment by mbobra** [comment]
@Cadair Yes for sure, not trying to bash Fido 😃Glad the example checks out.

**Comment by Cadair** [comment]
I know, both do the job, just differently lol.

**Comment by samaloney** [comment]
@mbobra thanks I could have gotten the data if I really wanted to but I was just trying to get some MDI and HMI files for a quick test and the above _should_ have worked which is the issue.

@Cadair actually why doesn't Fido query JSOC as well as VSO for this as both should be able to handle this query?

A bigger question would be if it did, which would take precedence or how would this be handled.

I'm back in the office this week so should have some time to look at this again.

**Comment by vit1-irk** [comment]
The problem still persists in VSO and latest Sunpy.

Got this kind of filename: ```'mdi_fd_m_96m_lev182_39633_39633.tar"\nContent-transfer-encoding: binary'```

**Comment by Cadair** [comment]
A generic algorithm for fixing this is [here](https://github.com/Cadair/parfive/pull/28/files#diff-cf9ef7a01d30e4debe27a090444b5368L29-L36). However, the way we are currently determining the filename for the VSO download is unclear (in `mk_filename` in vso.py) so I have asked the VSO team for some advice on what the best algorithm is.
