### ISSUE TITLE
Update install instructions to be more aligned with conda-forge

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3373]
In light of #3369 and comments @ehsteve made in chat last week, we probably need to refresh our install instructions.

**Comment by wtbarnes** [comment]
I would argue that we should just remove that link that tells people to run the tests to make sure their installation is "working." On the whole, I think asking users who just want to install sunpy and load up an AIA image (e.g.) do not and should not care about running tests. If they do, great, but it should not be the first thing they do after installing.

**Comment by wtbarnes** [comment]
Also, I'm not really sure what "more aligned with conda-forge" means in this context.
