### ISSUE TITLE
Add .shape attribute to TimeSeries

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3375]
It would be useful if `TimeSeries` had a .shape attribute, that returned a tuple `(nrows, ncols)`, similarly to a numpy array or pandas dataframe.

(p.s. I may have got rows and cols the wrong way round, this needs checking...)

**Comment by hayesla** [comment]
I guess you can just do a `ts.data.shape` - so do you envision just having a simple function so that you can do a `ts.shape`? 

p.s. should give you (nrows, ncols) 👍

**Comment by dstansby** [comment]
Yeah, I think having a simple property that just returns `data.shape` would be useful (to be able to do `ts.shape`).
