### ISSUE TITLE
Upstream our figure test infrastructure into pytest-mpl

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3382]
The sunpy figure test infrastructure was designed to prevent us from having to either store images in the repo, or having to download images from elsewhere during the test run.

[pyest-mpl](https://github.com/matplotlib/pytest-mpl) is a pytest plugin used by astropy which does comparisons to existing images, because it is doing comparisons to images it allows a tolerance in the generated and test images.

We should add two new features to pytest-mpl:

1) The ability to use a local hash library rather than reference images. This would allow a workflow like ours where you don't need the images (local or remote).
2) The generation of a summary HTML page with the differences between the reference images and the generated images.

This would allow us to switch to pytest-mpl rather than maintaining our own setup. Also this would probably be of interest to astropy as well.

Other cool things we could / should do once this is done:

* Automatically upload images to the reference repo on master.
* Have a flag for validating the hashes against the reference image, and also using the current tolerance stuff in pytest-mpl to tell you *how* different they are from the reference image. (I.e. this hash is incorrect the image is 2% different from the reference).
* Show the % difference in the summary page, and show if the hash is different.

All of this would need to be extra flags to pytest-mpl.

**Comment by Cadair** [comment]
ping @dstansby

**Comment by nabobalis** [comment]
This was done
