### ISSUE TITLE
Add Python 3.8 to the CI Builds

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3409]
We should update our builds to test with Python 3.8 now that it is released.

This needs the 3.8 builds to be available on Azure, so is blocked on https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

**Comment by wtbarnes** [comment]
Just to chime in here, I recently added Python 3.8 to the tests for aiapy, but am having an issue as there does not yet seem to be a scipy wheel for 3.8 yet and the CI throws up when trying to build it from source. You can see the log from the test failure [here](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/jobs/333962704).

We do all of our install from pip as the number of dependencies is quite small, so maybe installing the deps with conda solves this problem already?

**Comment by StanczakDominik** [comment]
That's exactly what I had on PlasmaPy while doing the same thing. Meanwhile, conda-forge hasn't added python 3.8 yet: https://github.com/conda-forge/python-feedstock/pull/274

And trying to `conda create -n py38 python=3.8 scipy numpy matplotlib` results in a conflict solver popping up that's been running for a good few minutes now...

I guess what this is really stuck on is https://github.com/scipy/scipy/issues/10927 ?

**Comment by nabobalis** [comment]
> They'll be added for SciPy 1.3.2, it's on the way. 

Hopefully sooner, need to check if the CI services have updated images too.
