### ISSUE TITLE
Bad spelling in time series method name

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#3426]
Not a bug as such because nothing is breaking (as far as I can tell), but the bad spelling of the method below makes the code harder to maintain.  The fix is to spell the method correctly.

### Description

In the time series code the method `_validate_data_for_ploting` appears in several places.

### Expected behavior

I expected "ploting" to be spelled as "plotting".

### System Details

  - SunPy Version: master

The fix is super-easy - fix the spelling.

**Comment by neerajkulk** [comment]
just submitted a pull request for this:

https://github.com/sunpy/sunpy/pull/3429

let me know if it's okay / any other changes are required.
