### ISSUE TITLE
Reduce import time for `sunpy`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3445]
(I was getting annoyed by our import times, and was inspired by astropy/astropy#4598 to look deeper.)

Importing `sunpy` takes just about a second on my machine (see below).  Over half of that time is spent importing `pkg_resources` for `sunpy.version`, which seems horribly excessive.  Can we get rid of using `pkg_resources`?  (See astropy/astropy#7647 for when they re-factored out `pkg_resources` to speed up their import time.)

```
python -X importtime -c "import sunpy" 2> sunpy.log
tuna sunpy.log
```
![sunpy](https://user-images.githubusercontent.com/991759/67575349-63f14280-f70a-11e9-8bd4-7065a9809178.png)

**Comment by nabobalis** [comment]
It might be possible to replace it with something like:

```
from setuptools_scm import get_version
version = get_version(root='..', relative_to=__file__)
```
Not sure if that means adding `setuptools_scm` as an install dep tho.

**Comment by nabobalis** [comment]
Or maybe:

```
>>> from importlib.metadata import version  
>>> version('wheel')  
'0.32.3'
```
from
https://docs.python.org/3/library/importlib.metadata.html

**Comment by Cadair** [comment]
I don't think we can remove `pkg_resources` for the version and continue to use setuptools_scm, we don't want to add scm as a runtime dep, and doing what @nabobalis suggests above probably uses pkg_resources anyway!

**Comment by ayshih** [comment]
Neato, created PR #3449

**Comment by dstansby** [comment]
The bottleneck seems to be astropy and numpy now, so I guess there's not much more to be done here?
<img width="1657" alt="Screenshot 2019-11-12 at 12 00 06" src="https://user-images.githubusercontent.com/6197628/68670123-0cddd100-0544-11ea-83ec-7e1809d139a5.png">
