### ISSUE TITLE
Add labels to sliders in Animator

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#3463]
### Description

Add labels to the sliders of the Animator class to make clear what axis/physical properties they slide through.

Also, the iterator number displayed by the slider often gets hidden by the play button.  This should be moved so it is not obstructed.

**Comment by abhijeetmanhas** [comment]
I would like to work on it, do we have to do it for all classes like `wcs` `image` etc in `animator` ?
