### ISSUE TITLE
errors/warnings after clean install on Mac OS X Catalina using Conda

### ISSUE THREAD

**Issue by thepeteriley** [sunpy/sunpy#3466]
Hi, 

I received the following errors after a clean install on Mac OS X Catalina using Conda. Any suggestions to resolve would be greatly appreciated! (I previously installed on a different machine 2 months ago with no issues).  It seems to want a module "hypothesis" but I didn't want to install that in case it was the wrong one. 

Thanks, 

-Pete

----

import sunpy

sunpy.self_test()
============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/pete/anaconda3, inifile: setup.cfg
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.3.0, remotedata-0.3.1
collected 1319 items / 15 errors / 1 skipped / 1303 selected

==================================== ERRORS ====================================
_ ERROR collecting lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py:2: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
_ ERROR collecting lib/python3.7/site-packages/sunpy/database/tests/test_tables.py _
'flaky' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/instr/tests/test_fermi.py _
'flaky' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/instr/tests/test_goes.py __
'array_compare' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py:8: in <module>
    from asdf.tests.helpers import assert_roundtrip_tree
E   ModuleNotFoundError: No module named 'asdf'
_ ERROR collecting lib/python3.7/site-packages/sunpy/map/tests/test_plotting.py _
'figure' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py:10: in <module>
    from sunpy.net.tests.strategies import time_attr
../anaconda3/lib/python3.7/site-packages/sunpy/net/tests/strategies.py:7: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
_ ERROR collecting lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py:2: in <module>
    from hypothesis import given, example, settings
E   ModuleNotFoundError: No module named 'hypothesis'
_ ERROR collecting lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py:12: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
_ ERROR collecting lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py _
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py:14: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
__ ERROR collecting lib/python3.7/site-packages/sunpy/net/tests/test_fido.py ___
ImportError while importing test module '/Users/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/tests/test_fido.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../anaconda3/lib/python3.7/site-packages/sunpy/net/tests/test_fido.py:6: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
__ ERROR collecting lib/python3.7/site-packages/sunpy/net/tests/test_helio.py __
'flaky' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/physics/tests/test_differential_rotation.py _
'array_compare' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/timeseries/tests/test_timeseriesbase.py _
'figure' not found in `markers` configuration option
_ ERROR collecting lib/python3.7/site-packages/sunpy/visualization/animator/tests/test_basefuncanimator.py _
'figure' not found in `markers` configuration option
!!!!!!!!!!!!!!!!!!! Interrupted: 15 errors during collection !!!!!!!!!!!!!!!!!!!
===================== 1 skipped, 15 error in 0.97 seconds ======================
Out[3]: <ExitCode.INTERRUPTED: 2>

**Comment by nabobalis** [comment]
See https://github.com/sunpy/sunpy/issues/3467
