### ISSUE TITLE
errors on clean install of Ubuntu 19.04 for self_test()

### ISSUE THREAD

**Issue by thepeteriley** [sunpy/sunpy#3467]
Hi, 

Following up on the Mac errrors in the previous submission, here are a set from an installation of sunpy on a pristine new Ubuntu 19.04 installation:

Pete

------

>>> import sunpy
>>> sunpy.self_test()
=============================================== test session starts ================================================
platform linux -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/pete
plugins: arraydiff-0.3, remotedata-0.3.2, doctestplus-0.4.0, openfiles-0.4.0
collected 1481 items / 7 errors / 30 deselected / 1 skipped / 1443 selected                                        

====================================================== ERRORS ======================================================
_______ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py ________
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/coordinates/tests/test_offset_frame.py:2: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
_ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py _
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py:8: in <module>
    from asdf.tests.helpers import assert_roundtrip_tree
E   ModuleNotFoundError: No module named 'asdf'
______ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py ______
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_fermi_gbm.py:10: in <module>
    from sunpy.net.tests.strategies import time_attr
anaconda3/lib/python3.7/site-packages/sunpy/net/tests/strategies.py:7: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
_______ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py _______
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_goes_ud.py:2: in <module>
    from hypothesis import given, example, settings
E   ModuleNotFoundError: No module named 'hypothesis'
_______ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py _______
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_lyra_ud.py:12: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
________ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py _________
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/net/dataretriever/tests/test_norh.py:14: in <module>
    from hypothesis import given, settings
E   ModuleNotFoundError: No module named 'hypothesis'
_______________ ERROR collecting anaconda3/lib/python3.7/site-packages/sunpy/net/tests/test_fido.py ________________
ImportError while importing test module '/home/pete/anaconda3/lib/python3.7/site-packages/sunpy/net/tests/test_fido.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
anaconda3/lib/python3.7/site-packages/sunpy/net/tests/test_fido.py:6: in <module>
    import hypothesis.strategies as st
E   ModuleNotFoundError: No module named 'hypothesis'
================================================= warnings summary =================================================
anaconda3/lib/python3.7/site-packages/pywt/_utils.py:6
  /home/pete/anaconda3/lib/python3.7/site-packages/pywt/_utils.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

anaconda3/lib/python3.7/site-packages/zeep/loader.py:3
  /home/pete/anaconda3/lib/python3.7/site-packages/zeep/loader.py:3: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
    from defusedxml.lxml import fromstring

anaconda3/lib/python3.7/site-packages/html5lib/_trie/_base.py:3
  /home/pete/anaconda3/lib/python3.7/site-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
  /home/pete/anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
  /home/pete/anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.array_compare - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

anaconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:176
  /home/pete/anaconda3/lib/python3.7/site-packages/sunpy/map/mapbase.py:176: SunpyUserWarning: This file contains more than 2 dimensions. Data will be truncated to the first two dimensions.
    "Data will be truncated to the first two dimensions.", SunpyUserWarning)

anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py:292
  /home/pete/anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py:292: UserWarning: One of the data, header pairs failed to validate with: Image coordinate units for axis 1 not present in metadata.
  Image coordinate units for axis 2 not present in metadata.
  See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata` for instructions on how to add missing metadata.
    warnings.warn(f"One of the data, header pairs failed to validate with: {e}")

anaconda3/lib/python3.7/site-packages/astropy/io/fits/file.py:379
  /home/pete/anaconda3/lib/python3.7/site-packages/astropy/io/fits/file.py:379: AstropyUserWarning: File may have been truncated: actual file length (538688) is smaller than the expected size (541440)
    .format(self.size, pos), AstropyUserWarning)

anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325
  /home/pete/anaconda3/lib/python3.7/site-packages/_pytest/mark/structures.py:325: PytestUnknownMarkWarning: Unknown pytest.mark.figure - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

anaconda3/lib/python3.7/site-packages/sunpy/tests/tests/test_self_test.py:1
  /home/pete/anaconda3/lib/python3.7/site-packages/sunpy/tests/tests/test_self_test.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================= 1 skipped, 30 deselected, 13 warnings, 7 error in 7.33s ==============================
<ExitCode.INTERRUPTED: 2>
>>>

**Comment by nabobalis** [comment]
Hi @thepeteriley, unfortunately at the moment to run/pass the entire test suite means to install all of our dependencies (extra testing ones and the like). In this case at least hypothesis is missing.

Can I ask how you installed SunPy, was it by anaconda?

**Comment by thepeteriley** [comment]
Hi Nabil,

Yes, I used the exact instructions listed here:

https://docs.sunpy.org/en/stable/guide/installation/

I also ran the update too to see if that helped.

The test cases, like reading AIA images seems to work though.

Thanks, Pete

**Comment by nabobalis** [comment]
That would suggest that the conda recipe we have is missing some dependencies which we need to fix.

**Comment by nabobalis** [comment]
If its ok, I will close this and the other issue and since I've opened a tracking issue in another repo we won't forget about it!.

**Comment by thepeteriley** [comment]
Sure, no problem. I'm surprised that it seemed to break the self test on
two completely different systems. I don't think I did the self test earlier
when I installed it at work though.

**Comment by nabobalis** [comment]
Yeah we have another issue tracking this issue since its been a long standing problem that our test suite breaks without all the requirements. We plan to make the tests more robust to missing libraries but the work hasn't happened yet. This issue is more that the conda recipe lacking the requirements.

**Comment by thepeteriley** [comment]
Ah got it. It might be worth putting a disclaimer that users shouldn't
worry if the self_test fails. I thought there was a major issue until I
started running through some of the easier examples.

**Comment by thepeteriley** [comment]
Ah! I should have seen that :)

**Comment by nabobalis** [comment]
It was added recently if I recall and it is not very large.
