### ISSUE TITLE
MapFactory seems to to call `expanduser` on path-like strings

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3476]
i.e. `~/sunpy/data/aia*` doesn't work

**Comment by wtbarnes** [comment]
This happens because `glob.glob` does not have any expanduser-like functionality. Passing the pattern you mention above to `glob.glob` returns an empty list which is why it is not getting caught by the glob pattern case in the factory.

I suspect this never worked?? Even before my fix in #3416.

**Comment by Cadair** [comment]
> I suspect this never worked??

Yeah I would think so.
