### ISSUE TITLE
Input to aia_color_table should be unitful

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3480]
### Description

`aia_color_table`, the function for selecting an AIA color map, takes in a selection for the AIA wavelength. However,  the accepted input types are either a string or integer. It should be an `astropy.units.Quantity` as the channel is a wavelength and a wavelength is a physical quantity

**Comment by mridullpandey** [comment]
Hi!
I'm working on this issue.
Thanks :-)

**Comment by mridullpandey** [comment]
@wtbarnes  will you please elaborate it so that i can get this easily.Whether  unitful means unified or something else.?

**Comment by nabobalis** [comment]
Hi @mridullpandey,

To expand on the issue. 

Thee function here: https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/colormaps/color_tables.py#L84
called `aia_color_table` currently takes a parameter called `wavelength` which we allow to be an integer. We want to change this to only take in and use a `astropy.units.Quantity` as we enforce this behaviour in other functions. We have a guide on this here: https://docs.sunpy.org/en/latest/dev_guide/units_quantities.html

**Comment by mridullpandey** [comment]
Hi.
So basically,what i have to do is to  change only wavelength as astropy.units.quantity form and update docstring. Is that what i have to do or some thing else ? On tables.py  its written that wavelength is based on aia_lct.pro part of SDO/AIA on SSWIDL written by Karel Schrijver (2010/04/12).  After analysing  aia_lct.pro part i found that he had taken input in angstrom , so,whether i should take unit as angstorm or meter ?.
Sorry if i missed it... and if it was much trivial....

**Comment by nabobalis** [comment]
Well astropy.units allows you to enter both units and it will convert it to the correct unit (if it can).

For the function angstrom makes the most sense. You can see an example of this here: https://github.com/sunpy/sunpy/blob/fd5b6ac409900f889260352c1ca7abeb5ae0adb3/sunpy/map/header_helper.py#L42 and the docstring for it on L81
