### ISSUE TITLE
sunpy.map.make_fitswcs_header should allow specification of the radius of the sun in meters

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3481]
We need this to accurately specify the full coordinate transforms

**Comment by hayesla** [comment]
hmm should it not do this once an observer is given?

**Comment by Cadair** [comment]
Oh my bad, it does already read this from the observer.

**Comment by ayshih** [comment]
For posterity, it doesn't read the reference radius of the Sun from the observer – which is in Heliographic Stonyhurst and doesn't carry this information – but rather from the observer-based coordinate frame (e.g., Helioprojective) when an observer is supplied.
