### ISSUE TITLE
consistency for `.peek()`to take/not take kwargs for plotting

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#3486]
At the moment some TimeSeries sources allow for matplotlib `kwargs` in the `.peek()` while others do not. Map does allow it i.e. kwargs are allowed (i.e. any additional `imshow` keywords can be used in `map.peek()`.

Following from #3378 it seems that some TimeSeries sources allow it (i.e. noaa, lyra and eve) while others do now (i.e. the rest). 

I guess the question is which way do we want to have it - but we just have to be consistent!

Thoughts @dstansby ?

**Comment by hayesla** [comment]
also raised at #2420

**Comment by dstansby** [comment]
I think we should allow `kwargs` through to whatever matplotlib function is doing the plotting - it *shouldn't* be too hard to fix this for everything as it stands from memory.

**Comment by hayesla** [comment]
yeah I think it's actually fairly straight forward - I'll give this a go 👍

**Comment by Swixx** [comment]
@hayesla Were you able to make any progress? If not I'm willing to help out!

**Comment by hayesla** [comment]
Hey @Swixx ! oh yes, I  realized I never made a PR for this - I have most of it implemented I think but maybe a PR review would be great when I make it. Have you worked on it yourself?

**Comment by Swixx** [comment]
@hayesla No, no yet - figured I would ask if you had first!
