### ISSUE TITLE
A very minor documentation issue

### ISSUE THREAD

**Issue by mwcraig** [sunpy/sunpy#3492]
At https://github.com/sunpy/sunpy/blame/master/docs/guide/tour.rst#L52 it says that the timeseries data is random....but I don't think it is.

**Comment by Raahul-Singh** [comment]
Hi, I would like to work on this. I am a beginner. Could you please give some more information? :sweat_smile:

**Comment by nabobalis** [comment]
The RST line linked in the issue says that the data loaded in the code block that follow is random but in fact its real data from a file. That needs to be changed to reflect this.
