### ISSUE TITLE
Add map.sample_at_coords()

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3494]
Currently to sample the data in a map at a series of coordinates, one has to do (e.g. see [here](http://docs.sunpy.org/en/stable/generated/gallery/plotting/great_arc_example.html)):
```python
pixels = np.asarray(np.rint(m.world_to_pixel(great_arc.coordinates())), dtype=int)
x = pixels[0, :]
y = pixels[1, :]
intensity_along_arc = m.data[y, x]
```

It would be nice if there was a method `sample_at_coords(coords)` that automatically did this under the hood.

**Comment by Cadair** [comment]
(this would need checking for astropy 3.1 compatibility)

To make this marginally easier you should be able to do:
```python
pixels = m.wcs.world_to_pixel_array(great_arc.coordinates())
intensity_along_arc = m.data[pixels]
```

[from the top of my head]

**Comment by sashank27** [comment]
While creating the function, following the approach as suggested by @dstansby, I found that this approach fails when we pass a single coordinate, as then `np.rint` throws an error while handling  a single `PixelPair`, but works fine for a list of `PixelPair`
Any suggestions on how to handle this?

Also, the following snippet works in the same way (as suggested by @Cadair )
```python
pixels = np.asarray(np.rint(m.wcs.world_to_pixel(great_arc.coordinates())), dtype='int')
intensity_along_arc2 = m.data[pixels]
```

**Comment by Cadair** [comment]
The implementation of this function should make use of the [`world_to_array_index`](https://github.com/astropy/astropy/blob/master/astropy/wcs/wcsapi/high_level_api.py#L82) method on the WCS object. i.e.

```python
def sample_at_coords(smap, coordinates):
    return smap.data[smap.wcs.world_to_array_index(coordinates)]
```

**Comment by Cadair** [comment]
The fact that it's a one line operation does make me wonder if we actually need a helper function for it? @dstansby ?

**Comment by dstansby** [comment]
Why not? Would make code more readable, and avoid the user having to worry about the `wcs`. I would add it as a method of `GenericMap` instead of a standalone function though.

(as a slight aside, it seems like a lot of the stuff in `map_utils.py` should be methods of `GenericMap` since they just take a map as their first argument anyway)

**Comment by Cadair** [comment]
It was a deliberate choice not to put all those things as methods of `GenericMap`, all be it a rather controversial one at the time.

**Comment by nabobalis** [comment]
Was that not why utils was born?

**Comment by Cadair** [comment]
yeah it was.
