### ISSUE TITLE
Error in documentation for "Finding bright regions with ndimage" example.

### ISSUE THREAD

**Issue by neerajkulk** [sunpy/sunpy#3503]
### Description

There seems to be an error in the documentation for the "Finding bright regions with ndimage" example.

In the part where a mask is made, the surrounding text states: " We choose the criterion that the data should be at least 5% of the maximum value. " However, if you look at the code immediately below, the threshold is based off 10% the max value:
`mask = aiamap.data < aiamap.max() * 0.10`

### Expected behavior

Documentation needs to be modified to reflect that the threshold is based off a 10% threshold.

**Comment by Cadair** [comment]
Thanks for the issue @neerajkulk :smile:

**Comment by neerajkulk** [comment]
no problem :) I'll submit a PR for this in a couple days
