### ISSUE TITLE
MapSequence has poor documentation for the `sortby` keyword

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3508]
MapSequence has a `sortby` keyword which has the following code:
```python
# Optionally sort data
if sortby is not None:
    if sortby == 'date':
        self.maps.sort(key=self._sort_by_date())
    else:
        raise ValueError("Only sort by date is supported")
```

But the docstring says:
```
sortby : `datetime.datetime`
    Method by which the MapSequence should be sorted along the z-axis.
```

The problems with the docstring are:
- It doesn't state that `None` as a valid input to disable sorting
- It doesn't state that the default is `'date'`
- It doesn't state that `'date'` is the only currently supported sorting strategy
- The valid input types are `str` or `None`, not `datetime.datetime`

**Comment by Raahul-Singh** [comment]
Hi I have opened a pull request for this issue. I am a beginner and would appreciate your feedback. :sweat_smile:
