### ISSUE TITLE
HGC > HGC transformation with different frame times has non-zero change in lattitude

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3530]
### Description
When transforming from one HeliographicCarrington (HGC) frame, to another but with a different obstime, a non-zero change in latitude seems to be observerd. I would expect exactly zero change in latitude, since the difference between two HCG frames at different times is just a change in longitude.

### Steps to Reproduce
```python
from sunpy.coordinates import frames
from astropy.coordinates import SkyCoord
from astropy.time import Time
import astropy.units as u

t1 = Time('2019-01-01')
t2 = Time('2019-01-06')

frame1 = frames.HeliographicCarrington(obstime=t1)
coord1 = SkyCoord(0*u.deg, 0*u.deg, frame=frame1)
print(coord1)
# <SkyCoord (HeliographicCarrington: obstime=2019-01-01 00:00:00.000): (lon, lat, radius) in (deg, deg, km)
    (0., 0., 695700.)>

frame2 = frames.HeliographicCarrington(obstime=t2)
coord2 = coord1.transform_to(frame2)
print(coord2)
# <SkyCoord (HeliographicCarrington: obstime=2019-01-06 00:00:00.000): (lon, lat, radius) in (deg, deg, km)
    (288.58265103, -0.05073824, 696211.1121367)>
```

Note how the latitude at the end != 0.

### System Details

  - SunPy Version: 1.0.5
  - Astropy Version: 3.2.3
  - Python Version: 3.7
  - OS information: MacOS 10.15

**Comment by ayshih** [comment]
The current behavior is correct, although it can be non-intuitive.  The SkyCoord is a point in *inertial* space, and the Sun moves over time (relative to the solar-system barycenter).  Thus, a point that was on the surface of the Sun at one time will not be exactly on the surface of the Sun at other times.

**Comment by dstansby** [comment]
Thanks for clearing this up!
