### ISSUE TITLE
HGS > HGS transformation with different frame times has non-zero change in distance

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3532]
### Description
When transforming from one HeliographicStonyhurst (HGS) frame, to another but with a different obstime, a non-zero change in radius happens. I would expect exactly zero change in radius, since the difference between two HGS frames is just a rotation about the center of the Sun.

### Steps to reproduce
```python
from sunpy.coordinates import frames
from astropy.coordinates import SkyCoord
from astropy.time import Time
import astropy.units as u

t1 = Time('2019-01-01')
t2 = Time('2019-01-06')

frame1 = frames.HeliographicStonyhurst(obstime=t1)
coord1 = SkyCoord(0*u.deg, 0*u.deg, frame=frame1)
print(coord1)
# <SkyCoord (HeliographicStonyhurst: obstime=2019-01-01 00:00:00.000): (lon, lat, radius) in (deg, deg, km)
#    (0., 0., 695700.)>

frame2 = frames.HeliographicStonyhurst(obstime=t2)
coord2 = coord1.transform_to(frame2)
print(coord2)
# <SkyCoord (HeliographicStonyhurst: obstime=2019-01-06 00:00:00.000): (lon, lat, radius) in (deg, deg, km)
#    (-4.62021654, -0.05059666, 698159.27645488)>
```
Note how the radius values are not the same.

**Comment by dstansby** [comment]
Eek the difference in distance becomes larger and larger for larger time differences: with a 6 month difference a point on the surface of the Sun ends up at `r = 777179 m` instead of `695700 m`.

**Comment by ayshih** [comment]
The current behavior is correct, although it can be non-intuitive.  The SkyCoord is a point in *inertial* space, and the Sun moves over time (relative to the solar-system barycenter).  Thus, a point that was on the surface of the Sun at one time will not be exactly on the surface of the Sun at other times.

**Comment by ayshih** [comment]
Since this is very similar to #3530 and has the same underlying reason, I'm going to close this issue as a duplicate.
