### ISSUE TITLE
Failing to download Sun's orientation from sunpy.coordinates.sun

### ISSUE THREAD

**Issue by fabianme17** [sunpy/sunpy#3535]
I am trying to get Sun's orientation (solar north position) using "orientation" from sunpy.coordinates.sun -- I also tried to use  "get_sun_orientation" from "sunpy.coordinates".
`from astropy.coordinates import EarthLocation
from sunpy.coordinates.sun import orientation
#from sunpy.coordinates import get_sun_orientation as orientation
LAT, LON, ELEV = -31.799, -69.297, 2552. #CASLEO coordinates and elevation
loc = EarthLocation(lat=LAT, lon=LON, height=ELEV)
time = '2017-06-08 16:00'
SNP = orientation(loc, time)
print(SNP)` 

However, nothing happens for a while (maybe 2 minutes) an then this message show up:
`WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error timed out>;<urlopen error timed out> [astropy.utils.iers.iers]`

After another while:
`WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: HTTP Error 503: Service Unavailable;<urlopen error timed out> [astropy.utils.iers.iers]`

Then it repeats:
`WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error timed out>;<urlopen error timed out> [astropy.utils.iers.iers]
WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error timed out>;HTTP Error 503: Service Unavailable [astropy.utils.iers.iers]
-158d14m46.3686s`

I need this to correct the solar north position of a 20-year time series.

Thank you.

**Comment by fabianme17** [comment]
The code is:
`from astropy.coordinates import EarthLocation
from sunpy.coordinates.sun import orientation
#from sunpy.coordinates import get_sun_orientation as orientation
LAT, LON, ELEV = -31.799, -69.297, 2552. #CASLEO coordinates and elevation
loc = EarthLocation(lat=LAT, lon=LON, height=ELEV)
time = "2017-06-08 16:00"
SNP = orientation(loc, time) print(SNP)`

**Comment by nabobalis** [comment]
It looks like the server that hosts that file is down. Hopefully they will come back soon. Unless the URL changed.

**Comment by ayshih** [comment]
Actually, those servers are down for months.  What version of Astropy are you using?  The latest releases should have updated mirrors (see astropy/astropy#9427).  Try updating your Astropy.

**Comment by fabianme17** [comment]
I updated all Anaconda and it worked! Thanks so much!
