### ISSUE TITLE
Use nitpicky mode for building docs

### ISSUE THREAD

**Issue by astrofrog** [sunpy/sunpy#3539]
I noticed that Sunpy doesn't currently set ``nitpicky=True`` in the sphinx configuration (``conf.py``). This is a really useful option that ensures that internal and intersphinx references are not broken:

http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky

**Comment by Cadair** [comment]
We probably need #6861 to be fixed before we can easily turn this on?

**Comment by astrofrog** [comment]
Yes though you could probably also add ``optional`` to the list of nitpick exceptions.
