### ISSUE TITLE
Database search() method missing returns documentation

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3546]
See https://docs.sunpy.org/en/latest/api/sunpy.database.Database.html#sunpy.database.Database.search - the return type of `search()` is currently not documented.

**Comment by iamrajiv** [comment]
I want to work on this issue @dstansby can you help me what changes I have to make 
![11](https://user-images.githubusercontent.com/42106787/70388047-df653580-19d2-11ea-966a-75c254d46044.JPG)
means I have to make it like this `search(*query,sortby)`?

**Comment by nabobalis** [comment]
I think the issue (and dstanby will correct me if I am off the mark) is that the doc string for search has no returns section.

(Would go further and say the entire database package needs a review of its documentation strings)

**Comment by iamrajiv** [comment]
can you help me what I supposed to return is it a `list of database entries` @nabobalis

**Comment by nabobalis** [comment]
You will need to fill in the returns section of the documentation string following this style: https://numpydoc.readthedocs.io/en/latest/format.html#sections 

If you go to part 5. Returns.
