### ISSUE TITLE
What's New in 1.1

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3553]
Before the release of 1.1 we need to write the what's new section. Please add comments to this issue (or edit it if you have permissions) with the things you think we should cover in the what's new.

- Remote Data Manager (#3124)
- New coordinate frames (#3212)
- SUVI support (#3269 / #3301)
- Reduce the import time of sunpy.map by ~40%. (#3495)
- Initial support for WISPR data (#3501)

pinging @sunpy/sunpy-maintainers  and @drsophiemurray

**Comment by dstansby** [comment]
Map now accepts filenames and directories as pathlib.Path objects. (#3408) too maybe? (along with sunpy.io.write_file() now accepts Path objects as filename inputs. (#3469))

**Comment by ehsteve** [comment]
What does "initial support" for WISPR mean? Since there isn't a map source what does this really provide a user? They might think they can actually open a WISPR file. Can they?

**Comment by dstansby** [comment]
Works for me... (using the example at https://github.com/sunpy/sunpy/issues/3496 and `.peek()`:)

<img width="860" alt="Screenshot 2019-12-02 at 21 48 37" src="https://user-images.githubusercontent.com/6197628/69998096-823e2f80-154d-11ea-89f5-6367ed5e98b1.png">

**Comment by ehsteve** [comment]
So it reads it into a genericmap but no custom map yet. cool and thanks @dstansby!

**Comment by dstansby** [comment]
A good test eventually will be trying to reproduce one of the figures in their first results paper that comes out on Weds.

**Comment by Cadair** [comment]
> What does "initial support" for WISPR mean? 

More technically it means we support generating a WCS from their more complex projection information in the headers.

(but yes, reads into a generic map)
