### ISSUE TITLE
Add a method that de-rotates images.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#358]
Add a method that will de-rotate images or mapcubes to componesate for solar differential rotation.

**Comment by ayshih** [comment]
See #1281 for an implementation that de-rotates based on the center pixel as seen from Earth

**Comment by wafels** [comment]
It should be possible to *differentially rotate* an image as seen from Earth using #1281

**Comment by nabobalis** [comment]
Is this not closed by #2236?

**Comment by wafels** [comment]
Yep, this is done.  See
https://github.com/sunpy/sunpy/blob/master/sunpy/physics/differential_rotation.py#L238
