### ISSUE TITLE
Consider not deriving HeliographicCarrington from HeliographicStonyhurst

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3584]
Currently, `HeliographicCarrington` (HGC) is defined as a subclass of `HeliographicStonyhurst` (HGS), which is a straightforward way to avoid some code repetition.  However, this has the potentially surprising behavior that `isinstance()` cannot be used to check whether a frame is of a desired type: `isinstance(frame, HeliographicStonyhurst)` will return `True` even when `frame` is `HeliographicCarrington`.  `isinstance()` is used in this fashion within Astropy's `CoordinateAttribute` class, which we use for the `observer` attribute in our frames.

The solution is to define a new frame (e.g., `BaseHeliographic`) that has the common code but no defined transformations, and then have both HGS and HGC be subclasses of that new frame.  Since HGC isn't actually a version of HGS, having HGC be a subclass of HGS isn't really appropriate anyway.

**Comment by abhijeetmanhas** [comment]
I want to work on it. I found that `frames.py` file contains  class `SunPyBaseCoordinateFrame`, which is parent of HGS, so should we add the heliographic functionalities in `SunPyBaseCoordinateFrame` class itself, or create its child, `BaseHeliographic`, which will be inherited by HGS and HGC?

**Comment by ayshih** [comment]
@abhijeetmanhas Great!  A new subclass of `SunPyBaseCoordinateFrame` should be created.  You can pretty much take the existing code for `HeliographicStonyhurst` and just rename it to `BaseHeliographic`.
