### ISSUE TITLE
GenericMap should have property for unit of the stored data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3586]
As far as I can see `GenericMap` does not have a property that is the unit of the observable/data stored in the map (https://docs.sunpy.org/en/latest/api/sunpy.map.GenericMap.html for current properties). It would be good if it could have one, so it is possible to coerce the data into a `astropy.units.Quantity` object with unit information.

**Comment by Cadair** [comment]
It actually does it's `.unit` because we inherit this from [`NDData`](http://docs.astropy.org/en/stable/api/astropy.nddata.NDDataBase.html#astropy.nddata.NDDataBase.unit).

If it's not showing up in the docs we should fix that.
