### ISSUE TITLE
CEA carrington maps do not show tick labels

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3611]
A synoptic map with cylindrical equal area (CEA) projection, does not show any tick labels at the default zoom level. The following code produces the plot below, which has no tick labels. 

Zooming in eventually shows some tick labels, but I would expect labels to be shown without any zooming.

![Figure_1](https://user-images.githubusercontent.com/6197628/71721971-218d6580-2e1f-11ea-8aaf-0bafcde65031.png)

```python
from astropy.time import Time
from astropy.coordinates import SkyCoord
import astropy.units as u
import matplotlib.pyplot as plt
import numpy as np

from sunpy.map import make_fitswcs_header, Map

obstime = Time('2000-1-1')
shape = [180, 360]

frame_out = SkyCoord(
    0 * u.deg, 0 * u.deg, obstime=obstime,
    frame="heliographic_carrington")

data = np.random.rand(*shape)
# Construct header
header = make_fitswcs_header(
    data, frame_out,
    scale=[360 / shape[1],
           (180 / np.pi) * (2 / shape[0]),
           ] * u.deg / u.pix,
    projection_code="CEA")

m = Map((data, header))

fig = plt.figure()
m.plot()
plt.show()
```

The issue seems to be that the x limit (-0.5 in pixel coords) is not doing a coordinate conversion properly.

**Comment by Cadair** [comment]
This is a bug in WCSAxes, it occurs when the edge of the projection is in the last pixel in one of the dimensions. If you change the limits to match the shape of the array it should show the ticks. (If it doesn't it's another bug in WCSAxes which Tom told me he fixed :grin: )

**Comment by dstansby** [comment]
Thanks! Maybe updating astropy to 4.0 will help me then.

**Comment by Cadair** [comment]
It should make it better (or at least reduce the amount you need to zoom in). I wonder if there is an issue for this on the astropy tracker already.

**Comment by dstansby** [comment]
Hmm, the current master branch didn't help. Will see if I can conjure up an upstream issue.

**Comment by dstansby** [comment]
Okay I think my input to the fits helper was a bit wrong, which I've fixed above. Now the x-axis is plotting fine, but the y-axis is still not showing up.

**Comment by dstansby** [comment]
Upstream issue at https://github.com/astropy/astropy/issues/10441 - can be reproduced without sunpy.

**Comment by dstansby** [comment]
Fixed upstream

**Comment by Cadair** [comment]
This is going to break our figure tests isn't it :grinning:

**Comment by dstansby** [comment]
Perhaps? I can't remember off the top of my head if we have any Carrington maps in the figure tests.
