### ISSUE TITLE
Map cannot open FITS files directly retrieved from DRMS

### ISSUE THREAD

**Issue by bmorris3** [sunpy/sunpy#3622]
### Description

I'm trying to initialize a map with an output from `drms` and having some trouble.

### Expected behavior

```python
url = 'http://jsoc.stanford.edu/SUM9/D757819487/S00009/continuum.fits'
from sunpy.map import Map
m = Map(url)
```
should produce a map.

### Actual behavior

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-1ed630106a5c> in <module>
----> 5 m = Map(url)

//anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py in __call__(self, composite, sequence, silence_errors, *args, **kwargs)
    298 
    299         if not len(new_maps):
--> 300             raise RuntimeError('No maps loaded')
    301 
    302         # If the list is meant to be a sequence, instantiate a map sequence

RuntimeError: No maps loaded
```

### Steps to Reproduce

```
import drms
from astropy.io import fits

c = drms.Client()
keys, segments = c.query('hmi.Ic_45s[{0}]'.format('2015.11.02'), 
                         key=drms.const.all, seg='continuum')

# Download the file(s)
url = 'http://jsoc.stanford.edu' + segments.continuum[0]

from sunpy.map import Map

m = Map(url)
```

### System Details

  - SunPy Version: 1.0.6
  - Astropy Version: 4.1 
  - Python Version: 3.7
  - OS information: Mac OS X 10.14.6

**Comment by Cadair** [comment]
So it looks like the reason is there is no unit metadata in the file.
```
In [2]: sunpy.map.Map("continuum.fits")                                                                                                                                                                                                                        
/home/stuart/Git/sunpy/sunpy/map/map_factory.py:294: UserWarning: One of the data, header pairs failed to validate with: Image coordinate units for axis 1 not present in metadata.
Image coordinate units for axis 2 not present in metadata.
See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata` for instructions on how to add missing metadata.
  warnings.warn(f"One of the data, header pairs failed to validate with: {e}")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-f266a6e276fb> in <module>
----> 1 sunpy.map.Map("continuum.fits")

~/Git/sunpy/sunpy/map/map_factory.py in __call__(self, composite, sequence, silence_errors, *args, **kwargs)
    299 
    300         if not len(new_maps):
--> 301             raise RuntimeError('No maps loaded')
    302 
    303         # If the list is meant to be a sequence, instantiate a map sequence

RuntimeError: No maps loaded
```

I think there is still a bug here which is that we should be raising that warning as an error, so it's very obvious that it's failed for that reason.

**Comment by ayshih** [comment]
Heh, I was just looking into this too!  I'll just point out that there's virtually no metadata at all in the FITS header beyond the barest minimum.

**Comment by Cadair** [comment]
Yeah, it's a direct export from DRMS, so it wont have any header.

**Comment by ayshih** [comment]
Just yoinked this from the `drms` documentation about this approach:

> Note that FITS files which are accessed in this way, do not contain any keyword data in their headers. This is perfectly fine in many cases, because you can just use Client.query() to obtain the data of all required keywords. If you need FITS files with headers that contain all the keyword data, you need to submit an export request to JSOC, which is described in the next section.

**Comment by bmorris3** [comment]
Ah I see. That's interesting because I'm 99% sure that this command worked for me a few months ago, with older versions of the software.

**Comment by Cadair** [comment]
I think we have made our validation more strict in the last little while. The purpose of map is to have the coordinate information to generate a WCS and other structured metadata. If you don't have this metadata you really only have a numpy array in terms of the data you have.

You can make a second query to drms and get the header info and then construct the map from both.

**Comment by wtbarnes** [comment]
Should we have an example that shows how to manually construct a header and create a map from a header and a URL? This effectively circumvents the JSOC export system, but may be useful to some people.

**Comment by wtbarnes** [comment]
With #3646 merged, the original code example now raises the following exception,

```python-traceback
MapMetaValidationError: Image coordinate units for axis 1 not present in metadata.
Image coordinate units for axis 2 not present in metadata.
See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata` for instructions on how to add missing metadata.
```

I'm going to close this since the issue with the header is now stated much more explicitly. Feel free to reopen if any issues persist.
