### ISSUE TITLE
Bugs in the TimeSeriesMeta creation.

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy#3651]
### Description

When passing parameters to ``TimeSeriesMetaData``, if only ``meta`` and ``timerange`` are provided, the returned object is empty, and doesn't even store the ``meta`` or ``timerange`` passed.
The docs stating that these parameters are optional are wrong and need to be changed.
All parameters need to be passed for object creation.
### Expected behavior

When all parameters are passed, the object is created and returned. Otherwise, raise an error.
### Actual behavior

While a TimeSeriesMeta is returned when just ``meta`` or ``timerange`` is passed, it is empty, and doesn't even store the meta passed.

### Steps to Reproduce

Create the ``TimeSeriesMetaData`` object by calling  ``sunpy.timeseries.TimeSeriesMetaData()``
just passing ``meta`` and ``timerange``
### System Details

  - SunPy Version: sunpy 1.0.6
  - Astropy Version: astropy 4.0 
  - Python Version: python 3.7 
  - OS information: ububtu 18.04

As per the discussion in #3639

**Comment by nabobalis** [comment]
I don't know enough about time series or how it was designed but looking at the ``__init__`` you need to pass each argument in with the correct time otherwise it will not work. I wonder if it is actually a bug in the logic in that function.
