### ISSUE TITLE
Removing astropy_helpers section in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by abhijeetmanhas** [sunpy/sunpy#3674]
### Description

As of PR https://github.com/sunpy/sunpy/pull/3598, sunpy no longer needs `astropy_helpers`, and even it is removed from the package.
I think there should not be a section of Astropy Helpers in contribution guidelines as well.

**Comment by nabobalis** [comment]
Good point, that section and anywhere else its mentioned should be removed.
