### ISSUE TITLE
List of available sources for TimeSeries?

### ISSUE THREAD

**Issue by Laubeee** [sunpy/sunpy#3682]
The [docs](https://docs.sunpy.org/en/stable/code_ref/timeseries.html#instrument-timeseries-classes) state:

> A number of instruments are supported through subclasses of the base GenericTimeSeries class. To see Instrument TimeSeries Classes for a list of all of them.

But there is nothing there, except for the XRS example. Is there a list of supported sources? If so, could it be linked in this page?

**Comment by nabobalis** [comment]
That link is very broken, it should go to a list. I wonder what happened to it.

**Comment by nabobalis** [comment]
On 0.9, we have a list of classes but it seems to have gone on 1.0+ 
https://docs.sunpy.org/en/v0.9.9/code_ref/timeseries.html#classes

**Comment by pkj-m** [comment]
Hi, I am planning to solve this issue. Can you please provide some more context? @nabobalis

**Comment by nabobalis** [comment]
In the 0.9 docs (linked above) we used to have a list of timeseries sources. These are now gone in the latest docs and need to be added back as they were under 0.9. 

This probably means adding a automod api statement in the timeseries rst file.

**Comment by pkj-m** [comment]
The `timeseries.rst` file for both the versions ([0.9](https://github.com/sunpy/sunpy/blob/0.9/docs/code_ref/timeseries.rst) and [master](https://github.com/sunpy/sunpy/blob/master/docs/code_ref/timeseries.rst)) appears to be identical. Is there something I am missing here? @nabobalis

**Comment by nabobalis** [comment]
That I suspect is the issue. In 0.9 I recall cleaning up the namespace for timeseries and removed sources from the main init file. 

So we need to add a new automodapi block to get the timeseries sources and that hopefully fixes it.
