### ISSUE TITLE
Provide a keyword for map sequence to skip over bad files and continue loading.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3688]
When loading a map sequence, if one file fails then it kills the whole load without telling you which file it failed on.

**Comment by jmason86** [comment]
e.g., 

```
start_time = '2010-03-01T20:00:00'
end_time = '2010-03-02T04:00:00'

off_sun_earth_line_imager = (a.vso.Source('STEREO_B') &
                             a.Instrument('EUVI') &
                             a.Time(start_time, end_time))

wavelength = a.Wavelength(17 * u.nm, 18 * u.nm)
result_right = Fido.search(wavelength, off_sun_earth_line_imager)
downloaded_files_right = Fido.fetch(result_right)
maps_right = sunpy.map.Map(downloaded_files_right, sequence=True)
```
results in:
```
Traceback (most recent call last):
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/sunpy/io/fits.py", line 81, in read
    pairs.append(HDPair(hdu.data, header))
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/astropy/utils/decorators.py", line 744, in __get__
    val = self.fget(obj)
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py", line 230, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/image.py", line 697, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py", line 507, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
  File "/Users/jmason86/anaconda3/envs/cme_speed_astropy_dev/lib/python3.7/site-packages/astropy/io/fits/file.py", line 336, in readarray
    buffer=self._mmap)
TypeError: buffer is too small for requested array
```

**Comment by jmason86** [comment]
My suggestion is that it skip the broken file, complete the load, but issue a warning that includes the filename(s) that failed

**Comment by twentyse7en** [comment]
Hey , I would like to work on this issue.As I'm new to opensource contribution, it will be very helpful if someone mentor me.

**Comment by nabobalis** [comment]
Hi @twentyse7en, what would you need help with? We normally suggest people start by reading: https://docs.sunpy.org/en/latest/dev_guide/newcomers.html to get familar first.

**Comment by twentyse7en** [comment]
consider this test case :

`mymap = sunpy.map.Map(['file1.fits', 'file2.fits', 'file3.fits'])`

If  `file1.fits`  failed to load , load all others left in list and issue a warning for failed file as @jmason86 suggest.

In  `test_map_factory.py`  there is a test , If directory doesn't exist it should raise `ValueError`

So for this test case  :

`mymap = sunpy.map.Map(['file1.fits', 'file2.fits', 'file3.fits', 'directory1/'])`

If `directory1` doesn't exist  instead of loading other files , should i raise `ValueError`  or Load files and print "dir doesn't exist" ?

**Comment by nabobalis** [comment]
I would make it error, the issue here isn't that the files don't exist. It is that they do exist but are broken in some way. If I pass in made up files, I should be told that they don't exist.

**Comment by jmason86** [comment]
Does making it error also mean execution halt / code crash? That’s what I’m
really trying to avoid.

**Comment by twentyse7en** [comment]
If one map fail to load , Its name should be mentioned and raise a error.Is that it @nabobalis .
Also to avoid code crash , we could provide a optional keyword argument. If it is `True` skip error and load other map in the list. It will be default `False`, works in old way. So it satisfy @jmason86 need too.

**Comment by nabobalis** [comment]
We can start with that and see where it takes the API.

**Comment by twentyse7en** [comment]
I didn't get what you mention about API @nabobalis .
Sorry to ask , I'm new to opensource contribution.

**Comment by nabobalis** [comment]
I mean about adding the extra keyword.

**Comment by twentyse7en** [comment]
how could I implement a API.I'm stuck at that.

**Comment by nabobalis** [comment]
What do you mean?

**Comment by twentyse7en** [comment]
about the new keyword.

**Comment by nabobalis** [comment]
What about it? I don't quite follow.

**Comment by twentyse7en** [comment]
I would like to implement a parameter `skip_fail`.
`sunpy.map.Map( files, skip_fail=True)` skip the files that fail to load.

**Comment by twentyse7en** [comment]
I tried to add parameter to this `def __call__( )`  then pass to corresponding function , But I got error. What is right way for adding parameters.

**Comment by nabobalis** [comment]
Goes into `__init__`?

**Comment by twentyse7en** [comment]
This is the file I'm trying to edit `map/map_factory.py`.It doesn't have a `__init__()` in that file.

**Comment by nabobalis** [comment]
I think you want `sunpy/map/mapbase.py`

**Comment by twentyse7en** [comment]
@nabobalis Please help me on this, It was my first attempt for opensource contribution.I couldn't complete.

My first attempt is to display the file that fail to load. `_parse_args( )` function handles the reading of all files.


 ```
while loop for all argument

      try :
          "reading file"
      except Exception :
          print(f'Error reading file {arg})
          raise 
```

Is this good or better way to print the message ?

**Comment by nabobalis** [comment]
As long as it works.

**Comment by nabobalis** [comment]
Please if you have an issue with the pull request, we can discuss there and not on this issue.

**Comment by nabobalis** [comment]
So #3727 now will raise a nicer error which includes the filename.

I am not sure I am pro having it skip over a broken file and just raising a warning.

**Comment by jmason86** [comment]
Maybe no skip by default but add an optional kwarg to do so?

**Comment by SnehVachhani** [comment]
I want to start this issue please can anyone provide me some more information regarding this issue. Like which file to be modified and what to be checked?

**Comment by nabobalis** [comment]
Something like this:

1. You will need to create a similar example as the one given in the second post but using our test or sample data and then add a text file masquerading as a fits file (or something) which will cause map to break. 
2. Add a new keyword to https://github.com/sunpy/sunpy/blob/master/sunpy/map/map_factory.py#L308 to enable the feature. I think most of the work only needs to happen to this file.
3. Then work out the correct place to bypass the error checking for a map sequence load.

**Comment by hannahc243** [comment]
I came across this issue in my own workflow and would like to work on implementing a fix. Is someone working on this currently?

**Comment by nabobalis** [comment]
I am not aware that anyone is working on this.
