### ISSUE TITLE
Rethinking and rewriting sunpy.self_test

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3701]
We are currently using astropy's test runner for `sunpy.self_test` this was really designed for setup.py and is therefore very full of features which are probably not needed for self_test.

Before we (I) go deleting swathes of code as I love to do. What do we want to achieve with self test? Is a very slim wrapper around `pytest --pyargs sunpy` all we need?

**Comment by nabobalis** [comment]
Do we need even need a self test?

**Comment by Cadair** [comment]
That's a valid question. People do use it, and it's a potentially useful debugging tool.

**Comment by nabobalis** [comment]
Isn't that only because we tell them to in the guide?

**Comment by abhijeetmanhas** [comment]
> That's a valid question. People do use it, and it's a potentially useful debugging tool.

Just for sake of more info,
In issue #3369 , self test were used to know import errors with conda forge. Is there any other ways of testing that sunpy will do as expected in all environments and OS?

**Comment by dstansby** [comment]
I remember someone mentioned that `self_test()` can be used to check that a SunPy installation isn't broken.

**Comment by Cadair** [comment]
The graphs in #3818 made me think about this again. Importing the runner (which happens at `import sunpy` time, so every time) takes a decent chunk of our import time, so moving to something lighter would have a real benefit.

Underneath *layers* of stuff the astropy test runner is just calling [`pytest.main`](https://github.com/astropy/astropy/blob/master/astropy/tests/runner.py#L248). What I therefore propose is we write a function (inside `sunpy.tests` so affiliated packages can also use it) which is a very minimal `self_test`. What I mean by that is I think it should support a `online=False` option, but otherwise no other options, i.e.:

* No support for coverage.
* No figure tests.
* No support for only running subpackages (i.e. it always runs all the tests)

The command should also happily run with only the `pytest-astropy` package installed as an extra dependency for running the tests. [This is more of a generic testing policy that all tests which depend of something not installed by `pytest-astropy` should skip if they can't run?]

**Comment by nabobalis** [comment]
> * No support for only running subpackages (i.e. it always runs all the tests)

This would mean making sure that the tests fail nicely if the extra packages are not installed.

**Comment by andy6975** [comment]
Hi! I am sorry if this sound wierd but I wanted to have a look at the code related to this issue, but I couldn't find it. Could anyone please guide me towards it?

**Comment by nabobalis** [comment]
> Hi! I am sorry if this sound wierd but I wanted to have a look at the code related to this issue, but I couldn't find it. Could anyone please guide me towards it?

I think it is this file: https://github.com/sunpy/sunpy/blob/master/sunpy/tests/runner.py
