### ISSUE TITLE
Add STEREO EUVI colourmap

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3702]
It doesn't look like sunpy has a built in colourmap for STEREO EUVI: https://docs.sunpy.org/en/stable/code_ref/visualization.html#module-sunpy.visualization.colormaps - it would be good to have one added.

**Comment by abhijeetmanhas** [comment]
I would like to work on it. @dstansby what's the reference for adding color maps, from which numpy arrays in `color_tables`are formed? I googled and found this php script https://heliodocs.com/xdoc/xdoc_print.php?file=$SSW/stereo/secchi/idl/display/secchi_colors.pro .

**Comment by dstansby** [comment]
Yes, that looks right. I don't know the details myself, but maybe you could work it out by working out what's already in the sunpy code for other colormaps.

**Comment by ehsteve** [comment]
See also #3885.
