### ISSUE TITLE
SunPy and Python 3.x

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#371]
As matplotlib is now in the wild for python 3 we should make sure that we can build sunpy on 3.x. There maybe some things that wont work, but we should try and keep our code compatible.

**Comment by embray** [comment]
Just going to make some notes here while I play with SunPy on Python 3.  I'll update this comment as I go.  First thing I can point out:

* [ ] The Suds library appears to have been basically abandoned.  However there is a somewhat maintained fork of it at https://pypi.python.org/pypi/suds-jurko/0.6 which includes Python 3 support (the original Suds does not support Python 3 at all).

**Comment by Cadair** [comment]
@embray We transitioned to suds-jurko everwhere a while ago. If there are any places still installing the old suds library, I would consider that a bug.

**Comment by embray** [comment]
@Cadair Mostly just in the README it links to the original lib (which is fine, might might also be worth linking to the fork).

**Comment by Cadair** [comment]
@embray ah right ok. I will change that.

**Comment by Cadair** [comment]
closed by #1728
