### ISSUE TITLE
Automatically include Map docstring when displaying help for subclasses?

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3716]
Originally raised in #396. Ideally, the `GenericMap` docstring should also be included when using one of the source-specific maps. For example, when calling `help(sunpy.map.sources.AIAMap)`, I should see the docstring for `GenericMap` and `AIAMap`.

**Comment by asinghgaba** [comment]
Hi 👋 I think I can tackle this issue, just to be sure I was thinking of implementing the following code:
```
class Foo(object):
    """
    Foo Class.
    This class foos around.
    """
    pass

class Bar(Foo):
    """
    Bar class, children of Foo
    Use this when you want to Bar around.
    parent:
    """ 
    __doc__ += Foo.__doc__
    pass
```

We could do this for all the sources. 
(Apologies if something I said doesn't make sense, I am new to open source and still learning! :) )

**Comment by nabobalis** [comment]
Should work.

**Comment by asinghgaba** [comment]
@nabobalis should I start to work on it then?

**Comment by nabobalis** [comment]
Go ahead.

**Comment by ayshih** [comment]
I recommend implementing this in `GenericMap.__init_subclass__()` so that it's automatic for any subclass and doesn't have to be manually added.

**Comment by asinghgaba** [comment]
@ayshih @nabobalis one thing to keep in mind is that implementing this method also changes the docstrings when sphinx builds documentation, so in all the description of the sources maps, there is a GenericMap doctstring. I am not sure if this is something we want?

**Comment by ayshih** [comment]
I envision adding a stripped-down version of the `GenericMap` docstring.  Once there's a PR, we can all look at the doc build and discuss.

**Comment by asinghgaba** [comment]
sounds good, I'll make a PR now.
