### ISSUE TITLE
Enable map.plot() to do mouse over in different coords [Adding functionality to my_map.peek()]

### ISSUE THREAD

**Issue by rasteenb** [sunpy/sunpy#376]
I would like to be able to change the (x,y) coordinate display in the Qt GUI when using my_map.peek().

Currently, the coordinates are displayed as helioprojective-cartesian (X, Y in arcseconds); I'd like to use heliographic (lat/lon) for identifying the location of new spot regions in HMI Intensitygram imagery, i.e. continue to view the image in helioprojective space, but having the coordinate display (e.g., when moving the mouse cursor over the image) show you the corresponding heliographic coordinate?

**Comment by Cadair** [comment]
WCSAxes does this
