### ISSUE TITLE
Two skipped examples

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#3761]
#3760 and this commit https://github.com/sunpy/sunpy/commit/6a48d7908117a143972a1fd7cdd9499a646af942 means we now have two skipped examples that are breaking on our CI. 

Fixing these either when the remote server or the bug that is causing them is discovered and fixed would be swell.

**Comment by pkj-m** [comment]
@nabobalis I tried to run the time-series example on my local machine and it executed without any errors but gave a warning: 

```
(sunpy-dev) pankaj@predator-pt315-51:~/sunpy-git/examples/time_series$ python skip_goes_hek_m25.py 
Files Downloaded: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [02:13<00:00, 133.49s/file]
/home/pankaj/anaconda3/envs/sunpy-dev/lib/python3.7/functools.py:840: UserWarning: Discarding nonzero nanoseconds in conversion
  return dispatch(args[0].__class__)(*args, **kw)
/home/pankaj/anaconda3/envs/sunpy-dev/lib/python3.7/asyncio/base_events.py:622: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  source=self)
/home/pankaj/anaconda3/envs/sunpy-dev/lib/python3.7/asyncio/selector_events.py:668: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=7>
  source=self)
```
However, apart from that, the example worked just fine and produced this output:

![Figure_1](https://user-images.githubusercontent.com/17577971/73845231-3313c400-4848-11ea-974b-fb0be941a454.png)

I am not able to understand why this might break the build. Have I understood the issue correctly, and if so, can you suggest some other places I can take a look at to determine what's causing the issue?

**Comment by nabobalis** [comment]
Yeah it works locally for me too. The question is why not on CircleCI.

**Comment by mridullpandey** [comment]
can i take this up @nabobalis

**Comment by nabobalis** [comment]
> can i take this up @nabobalis

Sure

**Comment by mridullpandey** [comment]
@nabobalis  will you please wish to elaborate what to actually do, if possible as it will be a plus for me to tackle this more elegentaly..

**Comment by nabobalis** [comment]
You will need to rename the skipped files to remove the `skip_` from them. Run them and see if they still work. Then open the pull request and see if they still work on circleci.
