### ISSUE TITLE
Improve accessibility of the html documentation

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3767]
This issue is twinned with https://github.com/sunpy/sunpy-sphinx-theme/issues/94 to track issues in the content of the documentation.

Steps to take:
- Look at the accessibility report here: https://wave.webaim.org/report#/https://docs.sunpy.org/en/stable/code_ref/coordinates.html
- Try and fix some of the errors!

I don't think there is anything to be done here without a group of people reviewing our theme and deciding on what  to fix with it.

**Comment by amogh-jrules** [comment]
I looked into some of the errors, but they seem rather vague, for eg. there around 185 contrast errors citing that orange text on white background is not readable, where as on inspection, it looks just fine.
Please point me to specific errors you would like fixed.

**Comment by nabobalis** [comment]
Yeah, we need to decide on what and how to fix these issues. I am not sure there is much to be done here without reviewing each error/suggestion first.

**Comment by amogh-jrules** [comment]
Alright, how do we go about it?

**Comment by nabobalis** [comment]
I don't think there is anything for you to do here without a group of people reviewing our theme and deciding on what  to fix with it. I would suggest another looking at another issue.

**Comment by n1kun-j** [comment]
I think the non UI issues mentioned in  https://wave.webaim.org/report#/https://docs.sunpy.org/en/stable/code_ref/coordinates.html  are fixed. If anything's remaining, I would like to know.

**Comment by Cadair** [comment]
Some of the UI issues could probably be addressed, and it looks like there is still some contrast issues we could work on. (Also I am not sure I am 100% on board with the colour changes we applied to improve the contrast short term).

**Comment by rutujasurve94** [comment]
I would like to contribute to this issue

**Comment by nabobalis** [comment]
Hi @rutujasurve94, I would suggest trying a different issue.

**Comment by rutujasurve94** [comment]
Hi @nabobalis sure, I could take up #4082
