### ISSUE TITLE
Document t in TimeRange

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3789]
`TimeRange` had a `.__contains__` method, but this isn't well documented. We should add some more obvious documentation that one can do `t in TimeRange`.

**Comment by Cadair** [comment]
you can to `t in TimeRange()` because it has a [`__contains__`](https://github.com/sunpy/sunpy/blob/master/sunpy/time/timerange.py#L404)

**Comment by Cadair** [comment]
Maybe it needs to be better documented?

**Comment by dstansby** [comment]
Maybe, I was looking at the API here: https://docs.sunpy.org/en/stable/api/sunpy.time.TimeRange.html#sunpy.time.TimeRange - perhaps there's a way to include `__contains__` in the listing.

**Comment by nabobalis** [comment]
What if we renamed it to `contains` and see if it shows up in the docs?

**Comment by dstansby** [comment]
That would work, but we should keep `__contains__` so `t in TimeRange` still works.

**Comment by nabobalis** [comment]
Then could  we keep `__contains__``, then have `contains` call that and copy the doc string from it?

**Comment by nikita-0209** [comment]
Hi, is this issue still open? If yes, can someone guide me on what exactly is the issue?

**Comment by dstansby** [comment]
Hi, this issue is still open ! I would say adding a `Notes` section to the docstring, that says it is possible to do `t in timerange` would be a good way to document this.

**Comment by nabobalis** [comment]
What about an example as well?

**Comment by nikita-0209** [comment]
I checked the documentation of the `_contains_` function within class `TimeRange`. I notice it already contains a docstring along with example suggesting that `t in timerange` is possible.
Doesn't that solve the issue? Or have I interpreted the issue incorrectly?

**Comment by nabobalis** [comment]
What documentation? I can't find any on this page: https://docs.sunpy.org/en/stable/api/sunpy.time.TimeRange.html#sunpy.time.TimeRange

**Comment by hayesla** [comment]
https://github.com/sunpy/sunpy/blob/1.1/sunpy/time/timerange.py#L404 I guess because its __contains__ its not showing up in docs?

**Comment by nikita-0209** [comment]
Yeah I was referring to the code documentation posted by @hayesla . Is there a way I can edit https://docs.sunpy.org/en/stable/api/sunpy.time.TimeRange.html#sunpy.time.TimeRange to display a similar description under the methods table?

**Comment by hayesla** [comment]
I'm not too sure? and I don't think we want to rename it to `contains`.

One way to do this is to put it in the `Notes` section in the class description ([here](https://github.com/sunpy/sunpy/blob/1.1/sunpy/time/timerange.py#L20)) with an example that `time1 in time_range` will return a boolean answer and then maybe an example there. That should then show up in the docs under the example section. 

Is that what you had in mind @dstansby ?

**Comment by dstansby** [comment]
Why did this get closed? I don't think some `t in timerange` documentation has been added to the docstring.
