### ISSUE TITLE
top_right_coord may be off by one

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3793]
The `top_right_coord` attribute on `sunpy.map.GenericMap` is calculated as,

https://github.com/sunpy/sunpy/blob/2a3d9a5cb34ba496fcf55d861e9307e3cec783db/sunpy/map/mapbase.py#L521

While WCS indexing does begin at 1, in astropy.wcs.WCS, our origin is defined such that `(0,0)*u.pixel` corresponds to the center of the bottom left corner. This would mean that, for an `N`-by-`N` image, the top right corner should correspond to `(N-1,N-1)*u.pixel`.

Further testing is needed to determine whether this is actually the case.

**Comment by dstansby** [comment]
It does indeed seem to be off by one. The following code prints the coord as (4, 4), despite the top right of the map being at (3, 3).

```python
import numpy as np
import sunpy.map
import sunpy.coordinates
from astropy.coordinates import SkyCoord
import astropy.units as u

data = np.arange(4).reshape((2, 2))
ref_coord = SkyCoord(0, 0, frame='helioprojective', obstime='now', unit='deg')
ref_pix = [1, 1] * u.pix
scale = [2, 2] * u.arcsec / u.pix
header = sunpy.map.make_fitswcs_header(data, ref_coord, reference_pixel=ref_pix, scale=scale)

m = sunpy.map.Map(data, header)
print(m.top_right_coord)
m.peek()
```

![Figure_1](https://user-images.githubusercontent.com/6197628/81411481-50537980-913a-11ea-8ed9-59ee13ff5f73.png)
