### ISSUE TITLE
Better warning message for incomplete HMI data.

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy#3819]
Currently, on querying `SDO/HMI` data using `HelioViewer`, we get an incomplete list of `meta`
This creates a problem as certain quantities like `wavelength` are present but not `waveunit`, which makes them dimensionless.
Further, on using `map.peek()`. Following warning is shown:
```
UserWarning: Unable to treat .meta as a FITS header, assuming a simple WCS. warnings.warn("Unable to treat.metaas a FITS header, assuming a simple WCS.")
```
This behaviour is observed for `SDO/HMI` but not for `SOHO/MDI`. This leads to the assumption that the problem is with the files they have in the database. We should have a list of `essential meta` which if missing, a warning should be given to the user.

Run the following code to reproduce the problem. I tested on various observation dates.
```python
from sunpy.net.helioviewer import HelioviewerClient 
import matplotlib.pyplot as plt 

hv = HelioviewerClient() 
file = hv.download_jp2('2018-03-16 23:10:35', observatory="SDO", instrument="HMI",source_id=18) 

from sunpy.map import Map 

sunmap = Map(file) 
sunmap.peek()
```

**Comment by Cadair** [comment]
> We should have a list of essential meta which if missing, a warning should be given to the user

I think we do already have this, where errors are raised if metadata is missing, but the definition of "essential" is deliberately minimal.

The "assuming a simple WCS" warning is probably to be expected for jpeg2000 files (given they can have non-FITS keys in the headers) but I would be interested to know what we aren't stripping.

ping @wafels for helioviewer input.

**Comment by dstansby** [comment]
The error message seems good now, as it includes the reason:
```python
/Users/dstansby/github/sunpy/sunpy/map/mapbase.py:443: UserWarning: Unable to treat `.meta` as a FITS header, assuming a simple WCS. The exception raised was:
Floating point nan values are not allowed in FITS headers.
  warnings.warn("Unable to treat `.meta` as a FITS header, assuming a simple WCS. "
```

It looks like the issue is the following entries in the header: `('crder1', nan), ('crder2', nan), ('csyser1', nan), ('csyser2', nan)`.

Perhaps we want to strip nan's from the header before constructing it? That certainly seems better than throwing everything away and constructing a blank WCS.
