### ISSUE TITLE
VSO/HEK use case

### ISSUE THREAD

**Issue by khughitt** [sunpy/sunpy#382]
This isn't so much of a feature-request as it is a use-case request. A while back Michael Kirk sent me this idea for how he would like to be able to interact with VSO/HEK in SunPy:

```
I find an event say a flare at a specific date and time range. I would
like to be able to have SunPy query the VSO/HEK and return a list of
instruments that were taking observations during that time. Beyond
that, it would be nice to have a summary of they types of data that
each instrument was taking (e.g. wavelength, cadence, resolution,
type, etc...).

Then it would be fantastic to interface it with a data retrieval
system so I can select the instruments I want and have it deliver the
data into my work environment (e.g. file list, or actually in an
```

The above use case encapsulates several different features which should probably be broken up into individual Github issues for easier tracking and implementation. Mean-while we can keep this record online to help motivate the overall functionality.

Also, if other people have ideas for variations on this theme, feel free to include them in the comments.

When creating separate issues to implement parts of this use case, please be sure to link back to this issue as well.

**Comment by wafels** [comment]
Close this...!
