### ISSUE TITLE
Explain intersphinx linking in our developer guide

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3820]
Unless I'm missing something, we don't really explain how to make use of intersphinx linking in our developer guide.  The closest I can find is: https://docs.sunpy.org/en/latest/dev_guide/documentation.html.

We should explain:

- Using backticks to link to SunPy stuff as well as external stuff
- Using the tilde to hide all but the last segment
- Using prefix qualifiers such as `:func:` and `:meth:` for functions and methods, respectively, so that they are rendered with the additional parentheses.

**Comment by ayshih** [comment]
For example, something like this: https://matplotlib.org/3.1.0/devel/documenting_mpl.html#referring-to-other-code

**Comment by ayshih** [comment]
For example, something like this: https://matplotlib.org/3.1.0/devel/documenting_mpl.html#referring-to-other-code

**Comment by nabobalis** [comment]
We should either steal that page or link to it.

**Comment by amogh-jrules** [comment]
> We should either steal that page or link to it.

I would like to fix this issue, which of the above 2 approaches should I implement?

**Comment by nabobalis** [comment]
Probably need to do both. Add link with the other two links and I think we need to expand the example to cover all cases so know what the standard for our documentation is.

**Comment by amogh-jrules** [comment]
I'll start work on this

**Comment by amogh-jrules** [comment]
I was planning on creating a subheading under the section Sphinx and explaining this stuff out.
For the first 2 points mentioned in the first comment I plan on writing a small example similar to what was given in the matplotlib docs. And for the prefix qualifiers I went through the bulk of docs, to come across these :
- :func:
- :ref:
- :doc:
- :meth:
- :class:

I also read the [intersphinx docs](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping) and understood that we can create our own mappings and was thinking of including a mention of this type of usage as well.
Will this be a sufficient addition enough to solve this issue?

**Comment by amogh-jrules** [comment]
> I was planning on creating a subheading under the section Sphinx and explaining this stuff out.
> For the first 2 points mentioned in the first comment I plan on writing a small example similar to what was given in the matplotlib docs. And for the prefix qualifiers I went through the bulk of docs, to come across these :
> 
> * :func:
> * :ref:
> * :doc:
> * :meth:
> * :class:
> 
> I also read the [intersphinx docs](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping) and understood that we can create our own mappings and was thinking of including a mention of this type of usage as well.
> Will this be a sufficient addition enough to solve this issue?
Can somebody review this?

**Comment by nabobalis** [comment]
Yes, that would be a good start.

**Comment by Cadair** [comment]
We shouldn't be recommending extra markup if it has no effect, we already have the default role set [inherited here](https://github.com/astropy/sphinx-astropy/blob/master/sphinx_astropy/conf/v1.py#L77) so we don't need to use the likes of `:class:` to linkify things. @ayshih's discovery of the formatting change when using `:func:` is interesting though, so it would be interesting to know if things like `:meth:` have a effect on the output as well.

All of this (including why we recommend things) should be folded into the docs.
