### ISSUE TITLE
VSO fails to filter query response.

### ISSUE THREAD

**Issue by aribalam** [sunpy/sunpy#3833]
### Description

On playing with VSO's post search filtering code, I came across a bug that involves failure of hashing of query response blocks. 

### Expected behavior

The QueryResponse would return a filtered response according to the new attributes provided.

### Actual behavior

`filter_results` in `net/vso/attrs` returns an error. See gist link for more details. 

### Steps to Reproduce

This gist - https://gist.github.com/aribalam/e46c0647a3254ed0986eb2a689cb99ad.
Apparently specifying post search attributes using & creates this error.

### System Details
I cannot provide any more additional details. 

### Possible Solutions
We could implement a `__hash__` function in `QueryResponseBlock` class in `net/dataretriever/client`. We could also avoid converting the response list into set assuming no two QueryResponseBlock will be same.

**Comment by abhijeetmanhas** [comment]
https://github.com/mvantellingen/python-zeep/issues/1075 I created an issue on zeep repo too, showing how we can't make a set from zeep objects since they are unhashable.
