### ISSUE TITLE
FITS files downloaded from JSOC end up being empty even if the download is successful

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy#3843]
### Description

It has been observed that many times when using JSOC even if the files are downloaded successfully, they are empty.
### Expected behavior

User is notified when the downloaded file is empty or corrupt. 
### Actual behavior

Files aren't checked for being corrupt or empty.

**Comment by dstansby** [comment]
What is the error that SunPy raises when such an empty file is downloaded and then imported? I think I'm with @Cadair in https://github.com/sunpy/sunpy/pull/3842#issuecomment-593915460 that this is a JSOC bug, and as long as we have a sensible error message in SunPy we shouldn't add the overhead of checking each downloaded file.

**Comment by Raahul-Singh** [comment]
Right now there is no error message. There are no tests for downloaded files.

**Comment by Cadair** [comment]
Unless services like the JSOC provide a sensible way for us to verify the download, i.e. checksums I really don't see a reliable way we can do this. Is checking for valid FITS enough, what if some of the imaging data is corrupted, how could we verify that?

**Comment by Raahul-Singh** [comment]
Currently, I have only faced cases where the downloaded files were empty.
