### ISSUE TITLE
Non-functional links on Sunpy Newcomer's guide

### ISSUE THREAD

**Issue by amogh-jrules** [sunpy/sunpy#3845]
A couple of links in the newcomer's guide are not rendered properly
https://docs.sunpy.org/en/latest/dev_guide/newcomers.html

![image](https://user-images.githubusercontent.com/31567169/75165401-57c4d280-5748-11ea-9534-d1560e71d7cb.png)

**Comment by mridullpandey** [comment]
i am working on it
thanks:-)
