### ISSUE TITLE
Remove EVEClient from sources, as it is in VSO ?

### ISSUE THREAD

**Issue by abhijeetmanhas** [sunpy/sunpy#3851]
I think VSO provides all of the data of `eve` https://sdac.virtualsolar.org/cgi/show_details?instrument=EVE 

Do we need separate client for it, or are there some data resources not covered by VSO, but according to me, VSO covers all our `EVEClient` accessible data.

**Comment by amogh-jrules** [comment]
If a decision is made, I would like to follow through with implementation for the same

**Comment by Cadair** [comment]
I am pretty sure that the VSO doesn't include the Level 0CS data that our EVEClient provides. The 0CS data is the near real time space weather data.

**Comment by dstansby** [comment]
Closing this as above - if I've missed something, feel free to re-open or add a comment.
