### ISSUE TITLE
Remote data manager does not recover well from its database being deleted while a session is running

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3853]
### Description
You can permanently corrupt the data manager state. So nothing works.

### Expected behavior
It recovers from my abuse and fixes itself.

### Steps to Reproduce

1. Delete all your data_manager stuff so you have a clean slate.
2. Run the following code inside an interactive prompt:
```python
from sunpy.data import manager
@manager.require('test_file',
                  ['http://data.sunpy.org/sample-data/predicted-sunspot-radio-flux.txt'],
                  '4c85b04a5528aa97eb84a087450eda0421c71833820576330bba148564089b11')
def test_function():
    pass

test_function()
```
3. Observe how everything works.
4. do a rm ~/sunpy/data_manager/*
5. **Without** starting a new python session run: `test_function()`, observe the following error:
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-2-7e96d146b416> in <module>
----> 1 test_function()

~/.virtualenvs/sunpy-release/lib/python3.8/site-packages/sunpy/data/data_manager/manager.py in wrapper(*args, **kwargs)
     64                     file_path = self._cache.download(urls, redownload=True)
     65                 else:
---> 66                     details = self._cache.get_by_hash(sha_hash)
     67                     if not details:
     68                         # In case we are matching by hash and file does not exist

~/.virtualenvs/sunpy-release/lib/python3.8/site-packages/sunpy/data/data_manager/cache.py in get_by_hash(self, sha_hash)
    127             SHA-1 hash of the file.
    128         """
--> 129         details = self._storage.find_by_key('file_hash', sha_hash)
    130         return details
    131 

~/.virtualenvs/sunpy-release/lib/python3.8/site-packages/sunpy/data/data_manager/storage.py in find_by_key(self, key, value)
    161         with self.connection() as conn:
    162             cursor = conn.cursor()
--> 163             cursor.execute(f'''SELECT * FROM {self._table_name}
    164                                       WHERE {key}="{value}"''')
    165             row = cursor.fetchone()

OperationalError: no such table: cache_storage

```
6. Restart your Python session and re-run:
```python
from sunpy.data import manager
@manager.require('test_file',
                  ['http://data.sunpy.org/sample-data/predicted-sunspot-radio-flux.txt'],
                  '4c85b04a5528aa97eb84a087450eda0421c71833820576330bba148564089b11')
def test_function():
    pass

test_function()
```
7. Observe how it's still broken.

Note, that if you delete the contents of the `data_manager` dir and then *restart* your Python session before calling the data manager again it recovers fine.

### System Details

  - SunPy Version: 1.1.1
  - Python Version: 3.8

**Comment by amogh-jrules** [comment]
I can work on this, could you give a me hint on how I should go about fixing this?

**Comment by vn-ki** [comment]
@amogh-jrules 

Two ways to fix this comes to my mind,

 1. https://github.com/sunpy/sunpy/blob/c6b475659c1c366c574e8b755e7a828c31b6182f/sunpy/data/data_manager/storage.py#L150

	moving this line to init, making it an attribute of the class `self._conn` and using `self._conn` instead of `conn` should fix this issue. 

2. You can also check for the exception at every `execute` call, remove the file and call setup again.

You can open a PR with either of these and we can discuss it over there.

**Comment by amogh-jrules** [comment]
Thanks! I'll get started

**Comment by amogh-jrules** [comment]
@vn-ki I have a tiny doubt. So if I make conn an attribute of the SqliteStorage class and initialize in init, do I also connect with sqlite3 instance in init itself as in the code you mentioned?

**Comment by adwaitbhope** [comment]
Hi @Cadair, I worked on this a bit and seem to have fixed it. The tests pass locally. Creating a PR now.
