### ISSUE TITLE
CircleCI backport builds broken

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3859]
See #3857 and #3858. The circleCI builds on backport PRs are broken with the following error:

```sh
#!/bin/sh
set -e

# Workaround old docker images with incorrect $HOME
# check https://github.com/docker/docker/issues/2968 for details
if [ "${HOME}" = "/" ]
then
  export HOME=$(getent passwd $(id -un) | cut -d: -f6)
fi

mkdir -p ~/.ssh

echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
' >> ~/.ssh/known_hosts

(umask 077; touch ~/.ssh/id_rsa)
chmod 0600 ~/.ssh/id_rsa
(cat <<EOF > ~/.ssh/id_rsa
$CHECKOUT_KEY
EOF
)

# use git+ssh instead of https
git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
git config --global gc.auto 0 || true

if [ -e /root/project/.git ]
then
  cd /root/project
  git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
else
  mkdir -p /root/project
  cd /root/project
  git clone "$CIRCLE_REPOSITORY_URL" .
fi

if [ -n "$CIRCLE_TAG" ]
then
  git fetch --force origin "refs/tags/${CIRCLE_TAG}"
else
  git fetch --force origin "cherry-pick-backport-3825-to-1.1-210cf956-c138-4203-a2c8-8b07a249bb4c:remotes/origin/cherry-pick-backport-3825-to-1.1-210cf956-c138-4203-a2c8-8b07a249bb4c"
fi


if [ -n "$CIRCLE_TAG" ]
then
  git reset --hard "$CIRCLE_SHA1"
  git checkout -q "$CIRCLE_TAG"
elif [ -n "$CIRCLE_BRANCH" ]
then
  git reset --hard "$CIRCLE_SHA1"
  git checkout -q -B "$CIRCLE_BRANCH"
fi

git reset --hard "$CIRCLE_SHA1"

Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
remote: Enumerating objects: 65, done.        
remote: Counting objects: 100% (65/65), done.        
remote: Compressing objects: 100% (51/51), done.        
remote: Total 79696 (delta 48), reused 14 (delta 14), pack-reused 79631        
Receiving objects: 100% (79696/79696), 47.87 MiB | 29.96 MiB/s, done.
Resolving deltas: 100% (57991/57991), done.
fatal: Couldn't find remote ref cherry-pick-backport-3825-to-1.1-210cf956-c138-4203-a2c8-8b07a249bb4c

exit status 128

CircleCI received exit code 128
```

**Comment by lzivadinovic** [comment]
It looks like CI is using wrong wrong variable name for branches. I wonder if problem is in actual circleci or in backport app. I will look a little bit into it, we use circleci at work so im used to it. Im not promising anything, i dont know how much time i will have in the following few weeks.

(bottom line, i could write custom script for checkout to strip cherry-pick and this crazy hash at the end, but lets see)

**Comment by Cadair** [comment]
It looks like it has triggered on the wrong commit. The backport bot generates some commits as it's cherry picking which then go away once it creates the backport branch.

**Comment by nabobalis** [comment]
I assume there is no bot replacement yet? 

I dont think its worth doing any fancy circleci stuff.

**Comment by Cadair** [comment]
I am happy to talk to someone about replacing the bot, but I am not getting time to do it myself.

**Comment by nabobalis** [comment]
Sure but I don't spending time screwing around with the bot or circleci config to fix it is worth it either.

**Comment by Cadair** [comment]
Can we just exclude circle from running any branches which start with `cherry-pick`? I think that might go a long way to fixing this if it's possible.

**Comment by nabobalis** [comment]
Yeah.

**Comment by lzivadinovic** [comment]
https://github.com/sunpy/sunpy/blob/master/.circleci/config.yml#L155

All jobs should be something like

`  pip-install:
    jobs:
      - pip-install:
        branches:
          ignore:
            - /cherry-pick*/`

source: https://circleci.com/docs/2.0/configuration-reference/#branches

Should fix it.

**Comment by wtbarnes** [comment]
Is this still an issue?

**Comment by Cadair** [comment]
yeah I think so

**Comment by nabobalis** [comment]
I'm not sure what causes it in hindsight. The bot branches are called backport-something and are skipped on circleci. Where the cherry-pick branch comes from is unclear and there seems to be no link  to it from circleci.

**Comment by Cadair** [comment]
I think the `cherry-pick` branches are made and then removed again, we should be skipping those as well.
