### ISSUE TITLE
sunpy.data.manager API docs missing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3865]
https://docs.sunpy.org/en/latest/code_ref/data.html contains no docs for `sunpy.data.manager` - there should be some there, which should be linked to from https://docs.sunpy.org/en/stable/generated/gallery/remote_data_manager.html.

**Comment by Cadair** [comment]
Argh, I thought I fixed this ages ago.

**Comment by Cadair** [comment]
Oh. The docs that I expect to be there are [here](https://docs.sunpy.org/en/latest/api/sunpy.data.data_manager.DataManager.html#sunpy.data.data_manager.DataManager) `sunpy.data.manager` is an instance of that class (iirc) so much like `Map` and `Fido` is a right PITA to make sphinx document properly. What needs to happen is the links to `sunpy.data.manager` needs to be updated to the same format as the links for `Map` and `Fido` as described here: https://docs.sunpy.org/en/latest/dev_guide/documentation.html#sunpy-specific-rules

**Comment by amogh-jrules** [comment]
I'll do it 👍
