### ISSUE TITLE
Grammatical error in SunPy docs

### ISSUE THREAD

**Issue by amogh-jrules** [sunpy/sunpy#3879]
### Description

![image](https://user-images.githubusercontent.com/31567169/76287030-835bc700-62c9-11ea-82dd-84c3c26a6933.png)

**Comment by dstansby** [comment]
To clarify, this should be changed from "used to with solar data" to "used with solar data".

**Comment by amogh-jrules** [comment]
Location of typo -> https://docs.sunpy.org/en/stable/generated/gallery/index.html
