### ISSUE TITLE
Reformatting Colour Tables

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#3885]
The code (https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps) that deals with our color tables needs some reformatting to be cleaner.

Ideally we need to do:

* Change the color tables into a series of enums to allow someone to access the array's directly without the use of a function. 
* This means deprecation of most of the functions in those files.
* Move the arrays into their own file whether it be python or a plain text file.

**Comment by abhijeetmanhas** [comment]
I want to give it a go. There are many arrays in that file. Should I keep all of them in `sunpy/data` or create a folder named `sunpy/visualization/colormaps/colortables` containing all the arrays stored as `json` or python numpy arrays in it?

**Comment by nabobalis** [comment]
I would put them in the same folder as the code to start off. Moving then if we want can be done after.

**Comment by Cadair** [comment]
I would think something like csv would be best, ascii and easy to read in a text editor.

**Comment by ehsteve** [comment]
csv files also render nicely on GitHub which might be convenient.

**Comment by jeffreypaul15** [comment]
Should the conversion of the tables into enums still be done? I can give it a go if required

**Comment by nabobalis** [comment]
In theory I don't see why not.

**Comment by kakirastern** [comment]
Well said

**Comment by jeffreypaul15** [comment]
I'm a little confused as to what exactly has to be converted to enums here? Correct me if I'm wrong but the functions in color_tables.py have to be removed and replaced with them accessing the emuns which are the variables such as aia_wave_dict.

**Comment by nabobalis** [comment]
A design/API was never finalised, I would suggest seeing what you think is easier/pretty and opening that PR so we can iterate on it.

**Comment by jeffreypaul15** [comment]
```Python
The following constants in color_tables.py are the  same but part of 2 different functions, the constants c0, c1, c2 & c3 all follow the same calculations but differ in type, one is float and the other int. This might cause an issue during creation of enums, what should be done here?


c0 = np.arange(256, dtype='f')
c1 = (np.sqrt(c0) * np.sqrt(255.0)).astype('f')
c2 = (np.arange(256)**2 / 255.0).astype('f')
c3 = ((c1 + c2 / 2.0) * 255.0 / (c1.max() + c2.max() / 2.0)).astype('f')


# these are part of iris_sji_color_table() function and follow the same calculations but different datatype
c0 = np.arange(0, 256)
c1 = (np.sqrt(c0) * np.sqrt(255)).astype(np.uint8)
c2 = (c0**2 / 255.).astype(np.uint8)
c3 = ((c1 + c2 / 2.) * 255. / (np.max(c1) + np.max(c2) / 2.)).astype(
        np.uint8)

c4 = np.zeros(256).astype(np.uint8)
c4[50:256] = (1 / 165. * np.arange(0, 206)**2).astype(np.uint8)
c5 = ((1 + c1 + c3.astype(np.uint)) / 2.).astype(np.uint8)
```

**Comment by nabobalis** [comment]
I am not sure I follow, why are we creating arrays manually?

**Comment by jeffreypaul15** [comment]
These are the already existing arrays in the color_tables.py that are used in aia_wave_dict and most other functions

**Comment by nabobalis** [comment]
Do we need to rewrite them?

**Comment by jeffreypaul15** [comment]
I don't see the need to, I was just removing the functions and converting into into enums but as mentioned there are contradicting constants so I'll leave the iris_sji_color_table as it is and export it using __all__

**Comment by jeffreypaul15** [comment]
So the conversion of enums are redundant here? I shall work on something else if they are

**Comment by nabobalis** [comment]
Yeah, I think enums were an idea that had no real use here.
