### ISSUE TITLE
XORing more than 10 different dates throws HTML 500 error when requesting from JSOC 

### ISSUE THREAD

**Issue by OlfwayAdbayIgbay** [sunpy/sunpy#3897]
I'm trying to get hmi 720s data for multiple different time ranges, and I'm trying to do this by iteratively XORing the time objects like so:

```
    from sunpy.net import Fido, attrs as a

    client = jsoc.JSOCClient()

    times = a.Time(date_x_hours_before(dates[0],12), dates0])

    for t in dates[1:]:
        times |= a.Time(date_x_hours_before(t,12), t)

    res = client.search(times, a.jsoc.Series('hmi.m_720s'),
                            a.jsoc.Notify(email), a.Sample(20 * u.min))

```
Whereas "date_x_hours_before" simply modifies the date string to be 12 hours earlier.

it works if I don't use or-constructs with more than 10 time objects, but for more than 10 it throws an "urllib.error.HTTPError: HTTP Error 500: Internal Server Error".

maybe there's a better way for requesting multiple time ranges, but downloading them individually is not feasible for what I am trying to do.

**Comment by Cadair** [comment]
JSOC will get getting these requests separately, and is probably throwing the 500 because you are making too many export requests at once. (JSOC supports one request per time range).

I think what you might need to do here is to do the exports `as-is` and export the headers yourself separately to not run into these limits.

**Comment by OlfwayAdbayIgbay** [comment]
I see! Could you specify what you mean by "do the exports as-is"?

**Comment by Cadair** [comment]
I have asked for some advice from the JSOC people about exporting FITS headers when using as-is. 

There is a small section on as-is in the drms (the underlying Python library SunPy uses) here: https://docs.sunpy.org/projects/drms/en/latest/tutorial.html#url-quick-as-is

You can ask for an `as-is` export with SunPy like this:

```python
    responses = Fido.search(
        a.Time('2012/1/1T1:00:36', '2012/1/1T01:00:38'),
        a.jsoc.Series('hmi.M_45s'), a.jsoc.Notify('jsoc@cadair.com'),
        a.jsoc.Protocol('as-is'))
```

The files you export this way will not have any header information in them, so they will not load as a sunpy map. (Combining the data with the header is the thing that JSOC rate limits on export). You can use the [`search_metadata`](https://docs.sunpy.org/en/stable/api/sunpy.net.jsoc.JSOCClient.html#sunpy.net.jsoc.JSOCClient.search_metadata) method of `JSOCClient` (see https://docs.sunpy.org/en/stable/guide/acquiring_data/jsoc.html#using-jsocclient-for-complex-usage for general docs on using `JSOCClient` directly for things Fido doesn't yet support) to download the metadata, which iirc isn't a valid FITS header by default but should be able to be passed into `Map` if you want to load it into SunPy.

Hope that helps.

**Comment by OlfwayAdbayIgbay** [comment]
Thank you so much, that helped a lot! It solved my html500 error and the metadata acquisition looks to be working as well.
