### ISSUE TITLE
SunPy’s HEK module

### ISSUE THREAD

**Issue by Matteo313** [sunpy/sunpy#3898]
I'm new in Sunpy and I am tring to learn how to use the HEK module in order to obtain a list of events (for example FL ).

When I compile I obtain 
"'utf-8' codec can't decode byte 0xc5 in position 10559: invalid continuation byte",

The code used is
1. from sunpy.net import hek
2. client = hek.HEKClient()  
3. tstart = '2011/08/09 07:23:56'
4.tend = '2011/08/09 12:40:29'
5.event_type = 'FL'
6.result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type)) 

System details are:

  - SunPy Version: 1.1.1
  - Astropy Version: 4.0
  - Python Version: 3.7.6
  - OS information: Windows 10 10.0.18362 (Intel64 Family 6 Model 58 Stepping 9, GenuineIntel)

**Comment by nabobalis** [comment]
It would seem that whatever is returned from the servers is unable to be turned from bytes into a string. Why, I am unsure at the moment.

**Comment by nabobalis** [comment]
We made a fix and hopefully will come out in the next bug fix releases (hopefully soon).

**Comment by Matteo313** [comment]
Thank you for the help!

**Comment by AzimAhmadzadeh** [comment]
Can someone plz tell us when this will be fixed? @nabobalis 
And till then, what workaround we can use to query data from HEK?

**Comment by nabobalis** [comment]
Hi @AzimAhmadzadeh, this fix will be in the next bug release of sunpy 1.0.x and 1.1.x which hopefully will come out over the weekend. 

In the mean time, you have to either use HEK directly on their website or use the master version of sunpy here.

**Comment by AzimAhmadzadeh** [comment]
Thanks @nabobalis. Any hope that I can use a previous version of sunpy to avoid this issue?

**Comment by nabobalis** [comment]
I believe this a problem on all old versions of sunpy due to the nature of the change I had to make to fix it. However, I have not checked.
