### ISSUE TITLE
fido.fetch() progress bar in notebook has too many new lines

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3907]
The progress bar used in a Jupyter notebook by `Fido.fetch()` inserts a new line every time it refreshes, resulting in a very long output (see below). Ideally it would not insert these new lines, and the progress bar would stay on one line.

<img width="1080" alt="Screenshot 2020-03-20 at 14 17 37" src="https://user-images.githubusercontent.com/6197628/77172330-afd7c600-6ab5-11ea-9b32-5218a07e4c67.png">

**Comment by Cadair** [comment]
This is a parfive bug.

It's fixed in https://github.com/Cadair/parfive/pull/36

**Comment by Cadair** [comment]
I have just released parfive 1.0.1 can you double check this is now fixed please?
