### ISSUE TITLE
How to prevent Sphinx from re-downloading everytime it build_docs is called

### ISSUE THREAD

**Issue by amogh-jrules** [sunpy/sunpy#3910]
Everytime I run tox -e build_docs to manifest the changes made, Sphinx begins downloading all over again instead of just refreshing the changes.

![image](https://user-images.githubusercontent.com/31567169/77242689-f39e0d00-6c26-11ea-92d4-ea699c8d6818.png)

Is there a way to prevent this?

**Comment by nabobalis** [comment]
I'm not sure what is downloading that file but maybe that file changed?

**Comment by amogh-jrules** [comment]
> I'm not sure what is downloading that file but maybe that file changed?

No, it downloads those all files all over again whenever I run tox -e build_docs even without any changes

**Comment by nabobalis** [comment]
But that looks like one file?

**Comment by amogh-jrules** [comment]
No, it is the last of the 26 other files that it has downloaded. Check the overall progress bar above

**Comment by nabobalis** [comment]
Ah I missed that. You could try making the documentation outside of tox and hopefully that will prevent it redownloading.

**Comment by dstansby** [comment]
The trouble is that `tox` creates a new environment each time, which has to download a new copy of the files each time. You should be able to run `make html` in the `docs/` folder to avoid this - please let us know if that works!

If it does maybe we should add that as a way to build the docs to the dev docs? https://docs.sunpy.org/en/latest/dev_guide/documentation.html

**Comment by amogh-jrules** [comment]
> The trouble is that `tox` creates a new environment each time, which has to download a new copy of the files each time. You should be able to run `make html` in the `docs/` folder to avoid this - please let us know if that works!
> 
> If it does maybe we should add that as a way to build the docs to the dev docs? https://docs.sunpy.org/en/latest/dev_guide/documentation.html

Alright, I'll try that out. I'll add it to the docs as well👍🏼

**Comment by nabobalis** [comment]
This was fixed.
