### ISSUE TITLE
pip install does not cover all dependencies of SunPy

### ISSUE THREAD

**Issue by amogh-jrules** [sunpy/sunpy#3913]
### Description
Whenever you use a virtual environment/ online jupyter-notebook just writing `pip install sunpy` is not enough. To actually use certain modules and sub-modules we are required to manually install libraries for example `zeep` and `drms`. It could be useful if we add them and others to the dependency list.

**Comment by nabobalis** [comment]
This is by design, if you want all the extra dependencies you have to do `pip install sunpy[all]`

**Comment by amogh-jrules** [comment]
Oh I see, thanks!
