### ISSUE TITLE
We should cron CI builds on bugfix branches

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3916]
So it is easy to see if something is currently broken

**Comment by nabobalis** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers

**Comment by nabobalis** [comment]
https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops
