### ISSUE TITLE
Reconcile new RotatedSunFrame with differential_rotate

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3931]
Now we have #3537 in we have the ability to replace [`differential_rotate`](https://docs.sunpy.org/en/stable/api/sunpy.physics.differential_rotation.differential_rotate.html#sunpy.physics.differential_rotation.differential_rotate) with reproject + `RotatedSunFrame`.

We should pin down any differences between these two approaches and re-write `differential_rotate` to use reproject underneath.

**Comment by ayshih** [comment]
Here's the specific comment with a comparison and generating code: https://github.com/sunpy/sunpy/pull/3537#issuecomment-559194239

And the image from that comment:
![comparison](https://user-images.githubusercontent.com/991759/69748078-916c4a00-1115-11ea-8a04-7f15cc7086e3.png)

Don't focus on the differences near the old limb, but rather at the differences in the neighborhood the new meridian.

**Comment by ayshih** [comment]
I believe #4979 has satisfactorily reconciled the two approaches.  Here's a comparison.  Note that I used the WCS calculated by `differential_rotate()` as the output WCS for `RotatedSunFrame`.  Small differences still remain after #4979, but they are believably due to the difference between `skimage.transform.warp` and `reproject.reproject_interp`.

Before #4979:
![diffrot before](https://user-images.githubusercontent.com/991759/107858076-2da86c80-6e00-11eb-8137-ad1006f5b5a8.png)

After #4979:
![diffrot after](https://user-images.githubusercontent.com/991759/107858080-3731d480-6e00-11eb-85b8-6d60123b02d9.png)

Generating script:
```python
from copy import deepcopy

import matplotlib.pyplot as plt
from reproject import reproject_interp

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.map
from sunpy.coordinates import RotatedSunFrame, transform_with_sun_center
from sunpy.data.sample import AIA_171_IMAGE
from sunpy.physics.differential_rotation import differential_rotate

m = sunpy.map.Map(AIA_171_IMAGE)
rectangle = SkyCoord([-700, -650]*u.arcsec, [0, 600]*u.arcsec, frame=m.coordinate_frame)
sm = m.submap(rectangle)

# Define the new observer 6 days in the future
new_observer = m.observer_coordinate.replicate(obstime=m.date + 6*u.day)

# differential_rotate()
dm = differential_rotate(sm, new_observer)

# RotatedSunFrame, using the output WCS calculated by differential_rotate()
rot_frame = RotatedSunFrame(base=dm.coordinate_frame, rotated_time=m.date)

out_wcs = deepcopy(dm.wcs)
out_wcs.coordinate_frame = rot_frame

with transform_with_sun_center():
    arr, foot = reproject_interp(sm, out_wcs, dm.data.shape)

rm = sunpy.map.Map(arr, out_wcs)
rm.plot_settings = deepcopy(sm.plot_settings)

# Comparison plot
fig = plt.figure(figsize=(15, 4))

ax1 = fig.add_subplot(131, projection=dm)
dm.plot(vmin=300, vmax=2000, title='differential_rotate()')
dm.draw_grid(grid_spacing=2*u.deg)

ax2 = fig.add_subplot(132, projection=rm)
rm.plot(vmin=300, vmax=2000, title='RotatedSunFrame')
rm.draw_grid(grid_spacing=2*u.deg, color='black')

ax3 = fig.add_subplot(133)
plt.imshow((dm.data - rm.data) / rm.data, origin='lower', vmin=-1, vmax=1, cmap='RdBu')
plt.title('Fractional differences')
plt.colorbar()

plt.show()
```

**Comment by ayshih** [comment]
I'll note that a workaround to get agreement prior to #4979 would be to put the `differential_rotate()` call within a `transform_with_sun_center()` context.  However, the bounds of the plot would still be messed up (see #4977) because that is due to a different bug.
