### ISSUE TITLE
Move constants defined in coordinates sub-package to sun

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3934]
The sunpy.sun sub-package is the central repository for all constants so no constants should be defined outside (or locally). This ensures that different parts of sunpy can use these constants and provides a central place to audit constants and update them as needed.

**Comment by kakirastern** [comment]
Hi, I would like to try this issue. Any pointers on how to start?

**Comment by kakirastern** [comment]
I will first systematically go through the codebase starting with the `sunpy.sun` and `sunpy.coordinates` subpackages, and then the rest to get a sense of the scope of the issue, before proceeding to working on submitting a PR to audit the current use of constants in the `sunpy` package as a whole, and finally move all constants currently defined in the `coordinates` subpackage to `sun`.

**Comment by ayshih** [comment]
@kakirastern These are the specific constants at issue in `sunpy.coordinates`.  The private variables are fine, but the "magic" numbers ought to be moved to `sunpy.sun.constants`.

https://github.com/sunpy/sunpy/blob/d2088eb8dbae23eb2e54181445fbb84b538e628a/sunpy/coordinates/ephemeris.py#L264
https://github.com/sunpy/sunpy/blob/5e96fa9e904d1cca4caf17c7f3c0008c0ab70556/sunpy/coordinates/ephemeris.py#L342
https://github.com/sunpy/sunpy/blob/d2088eb8dbae23eb2e54181445fbb84b538e628a/sunpy/coordinates/sun.py#L81
https://github.com/sunpy/sunpy/blob/d2088eb8dbae23eb2e54181445fbb84b538e628a/sunpy/coordinates/sun.py#L83
https://github.com/sunpy/sunpy/blob/f4e6fc3ad03c6074c18cb7abfa84d66f4eda6155/sunpy/coordinates/transformations.py#L259
https://github.com/sunpy/sunpy/blob/d2088eb8dbae23eb2e54181445fbb84b538e628a/sunpy/coordinates/transformations.py#L511
https://github.com/sunpy/sunpy/blob/f4e6fc3ad03c6074c18cb7abfa84d66f4eda6155/sunpy/coordinates/tests/test_transformations.py#L361
https://github.com/sunpy/sunpy/blob/f4e6fc3ad03c6074c18cb7abfa84d66f4eda6155/sunpy/coordinates/tests/test_transformations.py#L364
https://github.com/sunpy/sunpy/blob/f4e6fc3ad03c6074c18cb7abfa84d66f4eda6155/sunpy/coordinates/tests/test_transformations.py#L464

**Comment by kakirastern** [comment]
Sure @ayshih Thanks for the info! Will open a PR to follow up soon.
