### ISSUE TITLE
open "questions" in sunpy.pos.pos

### ISSUE THREAD

**Issue by rhewett** [sunpy/sunpy#394]
1. should the output always be an ndarray?
2. Should we be able to return position in other coordinate systems as well?
   If so, then this function should be to something like radec, and pos() should
   accept "radec" as input and call the current function.
3. Where do all of the "magic" numbers come from? If possible document them, and
   they may be useful elsewhere, consider putting them in sunpy.constants (could
   any of them already exist there or in scipy constants?)

**Comment by nabobalis** [comment]
sunpy.pos doesn't exist?

**Comment by wafels** [comment]
not anymore.
