### ISSUE TITLE
TODO and questions in map.py

### ISSUE THREAD

**Issue by rhewett** [sunpy/sunpy#396]
## TODO
- Automatically include Map docstring when displaying help for subclasses?
## Questions
- Should we use Helioviewer or VSO's data model? (e.g. map.meas, map.wavelength
  or something else?)
- Should 'center' be renamed to 'offset' and crpix1 & 2 be used for 'center'?

**Comment by wtbarnes** [comment]
This is really three issues in one. The last has already been addressed above.

>     * Automatically include Map docstring when displaying help for subclasses?

I don't think this has ever been addressed, i.e. when I do `help(sunpy.map.sources.AIAMap)`, I only get the docstring for `AIAMap`.
 
>     * Should we use Helioviewer or VSO's data model? (e.g. map.meas, map.wavelength
>       or something else?)

`Map` now includes both `measurement` and `wavelength` attrs. I don't think this question is relevant anymore. 

I'm going to close this and open a separate issue for the first point. Feel free to reopen if there are objections.
