### ISSUE TITLE
Bugs with the message from the deprecation decorator

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3968]
Our `deprecated` decorator has some recent bugs, possibly came in with #3124:

- The "scheduled for removal" version is calculated incorrectly.  I think it's an order-of-operations bug in this line: https://github.com/sunpy/sunpy/blob/1f79409372f8bd932c8f4db978e67bff451f04a7/sunpy/util/decorators.py#L48.
- The "scheduled for removal" message is always created (https://github.com/sunpy/sunpy/blob/1f79409372f8bd932c8f4db978e67bff451f04a7/sunpy/util/decorators.py#L56), which means that the code branch to create a default message that includes pointing the user to the specified `alternative` never runs (https://github.com/sunpy/sunpy/blob/1f79409372f8bd932c8f4db978e67bff451f04a7/sunpy/util/decorators.py#L164).

**Comment by nabobalis** [comment]
Woops.
