### ISSUE TITLE
Ensure manager.override_file works correctly with windows paths

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3983]
See https://github.com/sunpy/sunpy/pull/3972#discussion_r403340654 and #3969 and https://matrix.to/#/!MeRdFpEonLoCwhoHeT:matrix.org/$1585987922316946MWjEh:matrix.org?via=cadair.com&via=matrix.org

**Comment by nabobalis** [comment]
That matrix comment being:

```python
In [2]: urlparse('C:\TEMP')             
Out[2]: ParseResult(scheme='c', netloc='', path='\\TEMP', params='', query='', fragment='')
```

**Comment by dstansby** [comment]
Can someone a description of the issue, and ideally a self contained example exhibiting the issue?
