### ISSUE TITLE
Fix compatibility with sphinx 3

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3988]
It seems that we have a few issues that sphinx 3 is raising warnings for on our docs, we should fix them.

**Comment by letmerecall** [comment]
Hey guys, interested in this project. I would like to explore this issue. Can I work on it?

**Comment by nabobalis** [comment]
Sure

**Comment by jairideout** [comment]
@letmerecall, just wanted to check if you're working on this issue. If not, is it alright if I work on it?

**Comment by nabobalis** [comment]
This was fixed but the issue wasn't linked in the pull request.
