### ISSUE TITLE
sunpy.map.Map() fails to load list of urls

### ISSUE THREAD

**Issue by fluxtransport** [sunpy/sunpy#4006]
### Description
sunpy.map.Map() fails to load list of urls. 
e.g
urls = ['http://jsoc.stanford.edu/SUM80/D136597189/S00000/image_lev1.fits'
 'http://jsoc.stanford.edu/SUM79/D136597240/S00000/image_lev1.fits'
 'http://jsoc.stanford.edu/SUM76/D136597241/S00000/image_lev1.fits'
 'http://jsoc.stanford.edu/SUM82/D136597237/S00000/image_lev1.fits'
 'http://jsoc.stanford.edu/SUM83/D136597187/S00000/image_lev1.fits'
 'http://jsoc.stanford.edu/SUM81/D136597190/S00000/image_lev1.fits']

maps = Map(urls)

### Expected behavior
Expected to return a list of maps objects. 

### Actual behavior
Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.36s/file]
Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.47s/file]
---------------------------------------------------------------------------
```python                                                                    
AttributeError                            Traceback (most recent call last)
<ipython-input-23-1a0872c98bf5> in <module>
----> 1 maps = Map(urls)

~/anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py in __call__(self, composite, sequence, silence_errors, *args, **kwargs)
    274         """
    275 
--> 276         data_header_pairs, already_maps = self._parse_args(*args, **kwargs)
    277 
    278         new_maps = list()

~/anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py in _parse_args(self, *args, **kwargs)
    215             elif isinstance(arg, str) and _is_url(arg):
    216                 url = arg
--> 217                 path = str(cache.download(url).absolute())
    218                 pairs = self._read_file(path, **kwargs)
    219                 data_header_pairs += pairs

AttributeError: 'str' object has no attribute 'absolute'
```
### Steps to Reproduce
```python
from sunpy.map import Map

urls = ['http://jsoc.stanford.edu/SUM80/D136597189/S00000/image_lev1.fits',
 'http://jsoc.stanford.edu/SUM79/D136597240/S00000/image_lev1.fits',
 'http://jsoc.stanford.edu/SUM76/D136597241/S00000/image_lev1.fits',
 'http://jsoc.stanford.edu/SUM82/D136597237/S00000/image_lev1.fits',
 'http://jsoc.stanford.edu/SUM83/D136597187/S00000/image_lev1.fits',
 'http://jsoc.stanford.edu/SUM81/D136597190/S00000/image_lev1.fits']

maps = Map(urls)
```
### System Details

Time : Wednesday, 08. April 2020 09:11PM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : 1.1.2
OS: Mac OS X 10.15.1 (i386)

NumPy: 1.17.3
SciPy: 1.1.0
matplotlib: 3.0.2
Astropy: 4.0
Pandas: 0.23.4
parfive: 1.0.0

**Comment by fluxtransport** [comment]
Sorry not sure why commas between urls were stripped in the sample code above. I do have commas between the urls in my code.

**Comment by wtbarnes** [comment]
I'm not quite sure what's happening in your example above, but when I try to open one of the files I get the following traceback, perhaps because of a problem at the JSOC? I tried this a few hours earlier and I could at least read the first two files.

```python
from urllib.request import urlopen
urlopen('http://jsoc.stanford.edu/SUM80/D136597189/S00000/image_lev1.fits')
```

```python traceback
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-30-4cd81df2daa8> in <module>
----> 1 urlopen(urls[0])

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223
    224 def install_opener(opener):

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532
    533         return response

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570
    571 # XXX probably also want an abstract factory that knows when it makes

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~/miniconda3/envs/sunpy-user/lib/python3.8/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by nabobalis** [comment]
I just tried this and got the same error as Mark. I will look into it now.

**Comment by nabobalis** [comment]
Issue seems to be:

The sunpy cache downloads each file in order using a temporary name and it has the same temporary name so it gets updated by `replacement_filename` which returns a string path instead of a Path object. Thus causing this problem if the files are not in the .cache folder.

(Should these files even be saved into the cache folder over the main sunpy downloads folder?)

**Comment by wtbarnes** [comment]
Ok so why does this work for some urls and not others then? If we are returning the wrong type, I'd expect it to fail every time.

**Comment by nabobalis** [comment]
if the file is already in the case its ok, or if the names don't conflict.

**Comment by fluxtransport** [comment]
Hi @wtbarnes and @nabobalis thanks for looking into this. If Map() was not designed to do this, let me know. This is not a feature request, but https://docs.sunpy.org/en/stable/code_ref/map.html says it can handle "Lists of any of the above [including URLs]" so that's why I created the issue. If there's a better way to download files before providing lists of filenames to Map(), please let me know. Thanks.

**Comment by nabobalis** [comment]
Oh this is a bug which we will fix.
