### ISSUE TITLE
Missing metadata warnings aren't very helpful

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4008]
I'm currently working on some code the raises a lot of Missing metadata warnings, that show up like this
```
WARNING: SunpyUserWarning: Missing metadata for observer: assuming Earth-based observer.
 [sunpy.map.mapbase]
```
This isn't very helpful though, as I don't know what line in my code, or object, is the cause of these warnings.

It would be good to add some extra information so the user knows what is causing the warnings, and therefore making them easier to diagnose and fix.

**Comment by Raahul-Singh** [comment]
It's supposed to inform the user if any meta specific to a frame is missing if there is at least one meta present from that frame. Otherwise, it is assumed that the user purposefully omitted those.
In this case, I believe that the file you're making the map with has no meta at all for any frame. Could you please verify this?

For reference, #3692

**Comment by nabobalis** [comment]
With #3692 the warning should be tell what the issue is. Can you double check that it is doing so?

**Comment by dstansby** [comment]
I think the action here was to modify the warnings to show which line of code they are being emitted by, similar to python warnings:
```python
warnings_warn.py:13: UserWarning: This is a warning message
  warnings.warn('This is a warning message')
```
I'm not sure why sunpy warnings don't do this.

**Comment by nabobalis** [comment]
Will we not just need to pass `stacklevel=2` to each `warning.warn` to get this to work?

**Comment by nabobalis** [comment]
Nope, I am wrong.
If I run:
```python
import warnings

from sunpy.util.exceptions import SunpyUserWarning

warnings.warn("ABC", UserWarning)
warnings.warn("ABC", stacklevel=2)
warnings.warn("ABC", SunpyUserWarning)
warnings.warn("ABC", SunpyUserWarning, stacklevel=2)
```
I get:
```
sunpy/timeseries/warn.py:5: UserWarning: ABC
  warnings.warn("ABC", UserWarning)
sys:1: UserWarning: ABC
WARNING: SunpyUserWarning: ABC [__main__]
WARNING: SunpyUserWarning: ABC [warnings]

```
Nothing is returned that is useful unless I replace `SunpyWarning` to inherit from `Warning` instead of `AstropyWarning`
```
sunpy/timeseries/warn.py:5: UserWarning: ABC
  warnings.warn("ABC", UserWarning)
sys:1: UserWarning: ABC
sunpy/timeseries/warn.py:7: SunpyUserWarning: ABC
  warnings.warn("ABC", SunpyUserWarning)
sys:1: SunpyUserWarning: ABC
```

**Comment by dstansby** [comment]
Maybe this is an upstream astropy issue then?

**Comment by nabobalis** [comment]
If I add
```python
warnings.warn("AstropyWarning", AstropyWarning)
warnings.warn("AstropyWarning", AstropyWarning, stacklevel=2)
```
I get
```
WARNING: AstropyWarning [__main__]
WARNING: AstropyWarning [warnings]
```
But `AstropyWarning` inherit `Warning` so I am not sure what is going on.

**Comment by dstansby** [comment]
It's because they use a custom logger, in `astropy/logger.py`

**Comment by nabobalis** [comment]
So we need to adjust our logger settings instead of changing our warning class?

**Comment by nabobalis** [comment]
So they have their own `_showwarning` that changes how it prints the warning if `isinstance(args[0], AstropyWarning)` which should explain the difference.

**Comment by nabobalis** [comment]
In astropy tables they have this block of code:
```
class TableReplaceWarning(UserWarning):
    """
    Warning class for cases when a table column is replaced via the
    Table.__setitem__ syntax e.g. t['a'] = val.
    This does not inherit from AstropyWarning because we want to use
    stacklevel=3 to show the user where the issue occurred in their code.
    """
    pass

```
Looks like they don't want to report where the warning occurred by default.
