### ISSUE TITLE
Ensuring coordinates are in an expected frame

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4016]
I am currently writing a thing where the user specifies coordinates and I want to get them into HPC (assuming this is possible given the input). I am currently struggling to work out the different permutations of this, so I brain dumped here.

## HPC - HPC

```python
sc = SkyCoord(10*u.arcsec, 10*u.arcsec, observer="mars", frame="helioprojective")
```
* **HPC SkyCoord**

works:

```python
sc.transform_to("helioprojective")
```
Works
```python
sc.transform_to(Helioprojective)
```

* **HPC Frame**

Doesn't work (expected):
```python
sc.frame.transform_to("helioprojective")
```
Doesn't work (but kinda feel like it should?):
```python
sc.frame.transform_to(Helioprojective)
```

## Non-HPC - HPC

```python
sc = SkyCoord(10*u.deg, 10*u.deg, observer="mars", frame="heliographic_stonyhurst", 
              obstime="2020-02-02")
```

* **Compatible non-HPC SkyCoord**
Works:
```python
sc.transform_to("helioprojective")
```
* **Compatible non-HPC frame**
Doesn't work (expected):
```python
sc.frame.transform_to(sunpy.coordinates.Helioprojective)
```

---

So the one thing I expect to work that doesn't is this:

```python
sc = SkyCoord(10*u.arcsec, 10*u.arcsec, observer="mars", frame="helioprojective")
sc.frame.transform_to(Helioprojective)
```

I get that you are asking to transform to a frame which doesn't have an observer, but given it's already in a HPC frame, I kinda just expect this to be a no-op?

**Comment by ayshih** [comment]
Hmm, I think it would be confusing if
```python
hpc_frame.transform_to(Helioprojective)
```
gives a different answer than
```python
hpc_frame.transform_to(Helioprojective(observer=None))
```
which should definitely error with `observer=None` is explicitly specified.

It'd also not be clear how to resolve
```python
hpc_frame.transform_to(Helioprojective())
```
(i.e., an instance rather than a class, so would have `observer=None` by default).

**Comment by Cadair** [comment]
Yeah makes sense, thanks.
