### ISSUE TITLE
Re-order and remove the deprecation on the submap and draw_rectangle parameters after the 2.0 release.

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy#4025]
### Description

As [mentioned here](https://github.com/sunpy/sunpy/pull/3677#discussion_r409606416), the new API for specifying rectangular coordinates requires keyword-only arguments.
The current implementation has a decorator for deprecating the old API which will be supported until the official 2.0 release.
This is the issue to keep track of the eventual removal of the deprecation and the reordering of the parameters to submap and draw_rectangle.

**Comment by samriddhi-dev** [comment]
Hi! I can do this. My email is: agarwal.sachin.samriddhi@gmail.com

**Comment by samriddhi-dev** [comment]
Isn't this already done? The arguments are already in order and the deprecation decorator is already removed.

**Comment by nabobalis** [comment]
If it is done, we can close this issue. 

Thanks for having a look at it @samriddhi-dev
