### ISSUE TITLE
What's new for 2.0

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4040]
The purpose of this issue is to collect text and examples we can then put into a what's new document. 
Then once we have that, someone can open a PR with all the text/examples in this issue in an rst document.

**Comment by ayshih** [comment]
Stuff that I'm responsible for:

- #3537 Coordinate frames that include solar differential rotation
- #3782 Carrington coordinates for non-Earth observers
- #3951 Added an HTML summary for Map and MapSequence

**Comment by dstansby** [comment]
Ideas from me
- Changes to Fido (registering clients/attrs)
- `sample_at_coords` to sample a map at a set of `SkyCoord` https://github.com/sunpy/sunpy/pull/3592

**Comment by nabobalis** [comment]
Attrs discovery.

**Comment by nabobalis** [comment]
aiapy/aiaprep

**Comment by nabobalis** [comment]
min version bumps?

**Comment by wtbarnes** [comment]
* #3960 aiaprep has been deprecated in favor of the functionality in aiapy

**Comment by nabobalis** [comment]
The citation update

**Comment by nabobalis** [comment]
What about Context manager to ignore the inertial motion of the Sun for transformations #3540?

**Comment by wtbarnes** [comment]
> What about Context manager to ignore the inertial motion of the Sun for transformations #3540?

I imagine that could be covered in a single blurb about differential rotation frames.

**Comment by ayshih** [comment]
I've added draft blurbs to my earlier post, with the only thing missing being including a couple of the pretty differential-rotation plots.

I don't think #3540 is significant enough to be mentioned in the what's new.

**Comment by ayshih** [comment]
I've updated the blurb for #3537 with a plot, but will require #4072 to be merged.

**Comment by Raahul-Singh** [comment]
**get_rectangle_coordinates** #3737 
A utility to get the bottom left and top right coordinates of a rectangular region of interest in longitude and latitude in a given coordinate frame.
**Parameters:** (bottom_left, top_right, width, height)
**Valid Combinations:**
(astropy.coordinates.SkyCoord, astropy.coordinates.SkyCoord, None, None) 
(astropy.coordinates.SkyCoord, None, astropy.units.deg, astropy.units.deg)
(astropy.coordinates.BaseCoordinateFrame, astropy.coordinates.BaseCoordinateFrame, None, None) 
(astropy.coordinates.BaseCoordinateFrame, None, astropy.units.deg, astropy.units.deg)
(astropy.coordinates.BaseCoordinateFrame) # of shape (2,)
(astropy.coordinates.SkyCoord) # of shape (2,)
**Returns:** (bottom_left, top_right)
**Return Types:**
(astropy.coordinates.BaseCoordinateFrame, astropy.coordinates.BaseCoordinateFrame) # if bottom_left is an instance of `astropy.coordinates.BaseCoordinateFrame`
(astropy.coordinates.SkyCoord, astropy.coordinates.SkyCoord) # if bottom_left is an instance of `astropy.coordinates.SkyCoord`

    Examples
    --------
    >>> import astropy.units as u
    >>> from astropy.coordinates import SkyCoord
    >>> from sunpy.coordinates.frames import HeliographicStonyhurst
    >>> from sunpy.coordinates.utils import get_rectangle_coordinates

    >>> # With bottom left as a SkyCoord, width and height
    >>> bottom_left = SkyCoord(0 * u.arcsec, 0 * u.arcsec, frame='heliographic_stonyhurst')
    >>> width = 10 * u.arcsec
    >>> height = 10 * u.arcsec
    >>> bottom_left, top_right = get_rectangle_coordinates(bottom_left, width=width, height=height)

    >>> # With bottom left of shape (2,)
    >>> bottom_left_vector = SkyCoord([0 * u.arcsec, 10 * u.arcsec], [0 * u.arcsec, 10 * u.arcsec], frame='heliographic_stonyhurst')
    >>> bottom_left, top_right = get_rectangle_coordinates(bottom_left_vector)

    >>> # With bottom left as a BaseCoordinateFrame instance, width and height
    >>> bottom_left =  HeliographicStonyhurst(0 * u.arcsec, 0 * u.arcsec)
    >>> width = 10 * u.arcsec
    >>> height = 10 * u.arcsec
    >>> bottom_left, top_right = get_rectangle_coordinates(bottom_left, width=width, height=height)

**Comment by Raahul-Singh** [comment]
**With the release of parfive 1.1** #3822
1) Allows passing User-Agent Headers to `aiohttp.ClientSession`
If no UA is passed explicitly, the default UA is passed.
``` 
 'User-Agent': f"parfive/{parfive.__version__} aiohttp/{aiohttp.__version__} python/{sys.version[:5]}"
```
2) Adds support for passing proxy information to `aiohttp.ClientSession`
    * Proxy URL is read from the environment variables `HTTP_PROXY` or `HTTPS_PROXY`,
            depending on the protocol of the `url` passed.
     * Proxy Authentication `proxy_auth` should be passed as a `aiohttp.BasicAuth` object, explicitly by the user.
     * Proxy Headers `proxy_headers` should be passed as `dict` object, explicitly by the user.


Examples
--------
```
$ # Setting system wide proxy in bash terminal
$ http_proxy=http://user:password@proxyserver.com:3128
$ https_proxy=https://user:password@proxyserver.com:3128
$ export http_proxy
$ export https_proxy
```
Or use the GUI
![rsz_screenshot_from_2020-05-07_18-26-54](https://user-images.githubusercontent.com/40922068/81297327-b683c200-9090-11ea-94fc-5e1552ec2d24.jpg)

These setting will be passed to `aiohttp.ClientSession` during runtime.

**Comment by Raahul-Singh** [comment]
> **With the release of parfive 1.1** #3822
> 
>     1. Allows passing User-Agent Headers to `aiohttp.ClientSession`
>        If no UA is passed explicitly, the default UA is passed.
> 
> 
> ```
>  'User-Agent': f"parfive/{parfive.__version__} aiohttp/{aiohttp.__version__} python/{sys.version[:5]}"
> ```
> 
>     1. Adds support for passing proxy information to `aiohttp.ClientSession`
>        
>        * Proxy URL is read from the environment variables `HTTP_PROXY` or `HTTPS_PROXY`,
>          depending on the protocol of the `url` passed.
>        * Proxy Authentication `proxy_auth` should be passed as a `aiohttp.BasicAuth` object, explicitly by the user.
>        * Proxy Headers `proxy_headers` should be passed as `dict` object, explicitly by the user.
> 
> 
> ## Examples
> 
> ```
> $ # Setting system wide proxy in bash terminal
> $ HTTP_PROXY=http://user:password@proxyserver.com:3128
> $ HTTPS_PROXY=https://user:password@proxyserver.com:3128
> $ export HTTP_PROXY
> $ export HTTPS_PROXY
> ```
> 
> Or use the GUI
> ![rsz_screenshot_from_2020-05-07_18-26-54](https://user-images.githubusercontent.com/40922068/81297327-b683c200-9090-11ea-94fc-5e1552ec2d24.jpg)
> 
> These setting will be passed to `aiohttp.ClientSession` during runtime.

The GUI support will only work if the parfive patch is merged and released

**Comment by wtbarnes** [comment]
From @dstansby's comment on #4175, 

> Add a fuller changelog instructing users how to change their code from 1.1 to 2.0
