### ISSUE TITLE
Constants __doc__ creation

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4041]
We currently add a list of all constants into an rst table manually:

https://github.com/sunpy/sunpy/blob/master/sunpy/sun/constants.py#L92
 
This means if a name changes and it becomes wider than the column, it will break the documentation build. We need a way to construct the table that can account for this.

**Comment by dstansby** [comment]
(thinking outloud) could we just chuck them all in an astropy table, and then render the astropy table?

**Comment by jairideout** [comment]
Can I give this one a shot? I can try out the astropy table approach first, and fall back to computing the column widths if that doesn't work.

**Comment by nabobalis** [comment]
Sure.
