### ISSUE TITLE
Improve spline option doc in Map.resample

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4042]
The [current description ](https://docs.sunpy.org/en/stable/api/sunpy.map.GenericMap.html#sunpy.map.GenericMap.resample)of the `'spline'` option to `Map.resample` is

> spline - Uses ndimage.map_coordinates

which doesn't make sense to me. There should be a better description that says what this option does, and ideally which function is used to do the spline interpolation.

**Comment by rutujasurve94** [comment]
Hi, Open PR https://github.com/sunpy/sunpy/pull/4136 for this issue.

**Comment by nabobalis** [comment]
Closed by #4136
