### ISSUE TITLE
Fido has some issues to download into current working directory

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4057]
### Description

When downloading results from a Fido search it's not intuitive on how to save to your current working directory. For example:

```
>>> from sunpy.net import Fido, attrs as a
>>> result = Fido.search(a.Time("2013-10-28", "2013-10-29"), a.Instrument("XRS"))
>>> Fido.fetch(result, path="./")

~/sunpy_dev/sunpy/sunpy/net/fido_factory.py in fetch(self, path, max_conn, progress, overwrite, downloader, *query_results, **kwargs)
    334         if path is not None:
    335             exists = list(filter(lambda p: p.exists(), Path(path).parents))
--> 336             if not os.access(exists[0], os.W_OK):
    337                 raise PermissionError('You do not have permission to write'
    338                                       f' to the directory {exists[0]}.')

IndexError: list index out of range
```
This can be fixed by including the file name from the client such that:
```
>>> Fido.fetch(result, path="./{file}")
```

Is there a reason that you have to define the file name from the client rather than just using `./`?

If so, we should raise an error that says this. Otherwise can we fix it to allow `./` to be allowed?

**Comment by Cadair** [comment]
I see no reason why that shouldn't work.

**Comment by hayesla** [comment]
The issue is in the checking the write access - the path `./` returns an empty list in here `exists = list(filter(lambda p: p.exists(), Path(path).parents))` and so breaks

Otherwise it works - (i.e. if you comment out this condition)

**Comment by Cadair** [comment]
I think that could be:
```
exists = list(filter(lambda p: p.exists(), Path(path).resolve().parents))
```

**Comment by hayesla** [comment]
Yep - that fixes it! 🥳 

Shall I make a PR to fix this?

**Comment by nabobalis** [comment]
Yeah and add a test if you can.

**Comment by hayesla** [comment]
will do!
