### ISSUE TITLE
HEK example from sunpy documentation throws JSON error

### ISSUE THREAD

**Issue by OlfwayAdbayIgbay** [sunpy/sunpy#4059]
Using the HEK example from the Documentation:

```
from sunpy.net import hek
client = hek.HEKClient()

tstart = '2011/08/09 07:23:56'
tend = '2011/08/09 12:40:29'
event_type = 'FL'
result = client.search(hek.attrs.Time(tstart,tend),hek.attrs.EventType(event_type))
```

I get this as an error: 

> Traceback (most recent call last):
>   File "<input>", line 7, in <module>
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/sunpy/net/hek/hek.py", line 98, in search
>     return self._download(ndata[0])
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/sunpy/net/hek/hek.py", line 70, in _download
>     result = json.load(reader(fd))
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/user/anaconda3/envs/pytorch/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nabobalis** [comment]
Hi @OlfwayAdbayIgbay, you can tell what your sunpy version is? 

If you do `sunpy.__version__` it should print it out.

**Comment by OlfwayAdbayIgbay** [comment]
Hi, 
The version is 1.1.1

**Comment by nabobalis** [comment]
Thanks!

If you can upgrade to 1.1.2 this bug should be fixed now. `conda update sunpy` should work.

**Comment by OlfwayAdbayIgbay** [comment]
Oh, sorry! I missed that there's a new version. It works now, thank you!

**Comment by nabobalis** [comment]
No problem!
