### ISSUE TITLE
sunpy.io.fits.header_to_fits modifies input MetaDict in place, removing 'KEYCOMMENTS` entry.

### ISSUE THREAD

**Issue by STBadman** [sunpy/sunpy#4063]
### Description

`sunpy.io.fits.header_to_fits(header)` edits `header` in place, removing the `KEYCOMMENTS` dictionary entry. This function is often called by `sunpy.map.GenericMap` methods on `self.meta` causing these functions to edit `self.meta` in place. This can then cause problems if, for example, making `GenericMap` subclasses which parse information in the 'KEYCOMMENTS' dictionary (see e.g. https://github.com/dstansby/pfsspy/issues/178)

### Expected behavior

I expected that after reading in a fits file as a `sunpy.map.Map`, it's header will remain fixed unless I call a method which explicitly transforms the map such that it's header description should change.

### Actual behavior

Instead, I found that simply calling the map, or calling methods such as `.bottom_left_coord` (which should just passively access a property of the map) edited the header, deleting the 'keycomments' dictionary entry.

As far as I can tell, this occurs for any `GenericMap` method which at some point calls `sunpy.io.fits.header_to_fits(self.meta)`, and happens because `sunpy.io.fits.header_to_fits(self.meta)` performs `.pop` on `self.meta` to isolate 'keycomments' and treat it differently when building a `astropy.fits.Header` instance.

### Steps to Reproduce

1. Higher level : `sunpy.map.GenericMap`

```python
>>> import sunpy.map 
>>> import sunpy.data.sample 
>>>  aia = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
>>> 'KEYCOMMENTS' in aia.meta # 'KEYCOMMENTS' entry exists
True
>>> aia
SunPy Map
---------
Observatory:		 SDO
Instrument:		 AIA 3
Detector:		 AIA
Measurement:		 171.0 Angstrom
Wavelength:		 171.0 Angstrom
Observation Date:	 2011-06-07 06:33:02
Exposure Time:		 0.234256 s
Dimension:		 [1024. 1024.] pix
Coordinate System:	 helioprojective
Scale:			 [2.402792 2.402792] arcsec / pix
Reference Pixel:	 [512.5 512.5] pix
Reference Coord:	 [3.22309951 1.38578135] arcsec
array([[ -95.92475  ,    7.076416 ,   -1.9656711, ..., -127.96519  ,
        -127.96519  , -127.96519  ],
       [ -96.97533  ,   -5.1167884,    0.       , ...,  -98.924576 ,
        -104.04137  , -127.919716 ],
       [ -93.99607  ,    1.0189276,   -4.0757103, ...,   -5.094638 ,
         -37.95505  , -127.87541  ],
       ...,
       [-128.01454  , -128.01454  , -128.01454  , ..., -128.01454  ,
        -128.01454  , -128.01454  ],
       [-127.899666 , -127.899666 , -127.899666 , ..., -127.899666 ,
        -127.899666 , -127.899666 ],
       [-128.03072  , -128.03072  , -128.03072  , ..., -128.03072  ,
        -128.03072  , -128.03072  ]], dtype=float32)
>>>  'KEYCOMMENTS' in aia.meta # 'KEYCOMMENTS' now deleted
False
```
2. Lower level : `astropy.io.fits.header_to_fits`

```python 
>>> import sunpy.io
>>> import sunpy.map
>>> import sunpy.data.sample
>>> aia_header = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE).meta
>>> 'KEYCOMMENTS' in aia_header # 'KEYCOMMENTS' exists
True
>>> _=sunpy.io.fits.header_to_fits(aia_header)  
>>> 'KEYCOMMENTS' in aia_header # 'KEYCOMMENTS' now deleted    
False
```

### System Details

- SunPy Version: 1.1.2
- Astropy Version: 4.0.1.post1
- Python Version: 3.7.6
- OS information: Ubuntu 18.04 bionic (Linux 4.15.0-96-generic x86_64)

**Comment by Cadair** [comment]
Thanks for the report :smile:
