### ISSUE TITLE
Improve the solar cycle example

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4082]
When https://github.com/sunpy/sunpy/pull/4061 is merged we want to update the example to address

@mbobra comments:

> Could you provide a bit more information at the beginning of the example (see, for example, the second introductory sentence in the [example template](https://github.com/sunpy/sunpy/blob/master/examples/example_template/example_template.py))? It would be nice to clarify what "possibly next solar cycle" means, explain where the data are coming from, and specifically define the difference between the variables `noaa` and `noaa2`.

**Comment by rutujasurve94** [comment]
Hi, I would like to contribute to this issue

**Comment by nabobalis** [comment]
Sure.

**Comment by rutujasurve94** [comment]
Hi, I've raised a PR here: https://github.com/sunpy/sunpy/pull/4135 for improving the example.
