### ISSUE TITLE
Log something to stdout when sample data download fails

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4091]
If we fall over to our mirrors for the sample data download we should log something. Mainly so that we can easily see it happening on the CI etc

**Comment by rutujasurve94** [comment]
Hi, I've raised PR: https://github.com/sunpy/sunpy/pull/4137 for this issue.

**Comment by nabobalis** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/4137
