### ISSUE TITLE
wcs animator tests failing with astropy 4.1

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4096]
Thought I would open a bug to track this, there are several tests currently failing with the master branch of astropy. See e.g. https://dev.azure.com/sunpy/sunpy/_build/results?buildId=7470&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=041114ed-9dec-54b1-2eeb-2bb11dee55c0&l=4655 for one of the failures.

**Comment by ayshih** [comment]
For what it's worth, when I tried to reproduce these failures on my local setup, I could not, for reasons unknown.

**Comment by dstansby** [comment]
Digging into this a bit, and the `radial_veloctiy` is being added as of https://github.com/astropy/astropy/commit/212c10cb90a787ee37d2f71e99ef54f587f3d07a#diff-68747e26b0d750b21c3464c0a76caf83R484-R492 / https://github.com/astropy/astropy/pull/10185

**Comment by Cadair** [comment]
I have done a little investigation into this and put a minimum example in astropy/astropy#10323 (it is not actually related to visualization) it's because there is a sliced out spectral coord I think, or at least something related to the spectral + spatial components.

**Comment by Cadair** [comment]
Now fixed upstream.

**Comment by dstansby** [comment]
Fixed by https://github.com/astropy/astropy/pull/10326
