### ISSUE TITLE
make_fitswcs_header indexes from 1, not 0 as claimed in docs

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4120]
Using the following toy example, I would expect the reference coordinate (0, 0) to correspond to the center of the [1, 1] pixel in the array, ie. the top right pixel. Looking at the figure below it seems like it refers to the [0, 0] pixel, which would mean `make_fitswcs_header` is indexing from 1 instead of 0.

The docstring [claims to be indexing from 0.](https://docs.sunpy.org/en/stable/api/sunpy.map.make_fitswcs_header.html#sunpy.map.make_fitswcs_header)

```python
import numpy as np
import sunpy.map
import sunpy.coordinates
from astropy.coordinates import SkyCoord
import astropy.units as u

data = np.arange(4).reshape((2, 2))
ref_coord = SkyCoord(0, 0, frame='helioprojective', obstime='now', unit='deg')
ref_pix = [1, 1] * u.pix
scale = [2, 2] * u.arcsec / u.pix
header = sunpy.map.make_fitswcs_header(data, ref_coord, reference_pixel=ref_pix, scale=scale)
print(header)

m = sunpy.map.Map(data, header)
m.peek()
```

![Figure_1](https://user-images.githubusercontent.com/6197628/81411191-f05cd300-9139-11ea-807e-3828fa12aa8d.png)

**Comment by Cadair** [comment]
You are correct, we are indexing from 1, if we were indexing from 0 we would need to be adding `+1`s here: https://github.com/sunpy/sunpy/blob/master/sunpy/map/header_helper.py#L143L144

I am not sure if it's best to change the docstring or the implementation, I lean towards changing the implementation.
