### ISSUE TITLE
Remove NOAA solar cycle data from sample data set

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#4156]
### Description

NOAA solar cycle data will always be out of date given that it is always updating. This is also true of the prediction data set. The names of these data sets are `NOAAINDICES_TIMESERIES` and `NOAAPREDICT_TIMESERIES`. Given that these are simply available as csv files, ftp://ftp.swpc.noaa.gov/pub/weekly/Predict.txt and ftp://ftp.swpc.noaa.gov/pub/weekly/RecentIndices.txt, that are easily using the existing clients [NOAAIndicesClient](https://docs.sunpy.org/en/stable/api/sunpy.net.dataretriever.NOAAIndicesClient.html#sunpy.net.dataretriever.NOAAIndicesClient) and NOAAPredictIndicesClient, I suggest that these be removed from the sample data set.

**Comment by mbobra** [comment]
Agree. I see no reason for us to host the data. We can simply download it when necessary.

**Comment by rutujasurve94** [comment]
Hi, I've updated the PR: #4135 to use live data from ftp://ftp.swpc.noaa.gov/pub/weekly/Predict.txt and ftp://ftp.swpc.noaa.gov/pub/weekly/RecentIndices.txt - changing _sample.py script to update NOAAINDICES_TIMESERIES and NOAAPREDICT_TIMESERIES to the new sources and adding a mirror URL for ftp://ftp.swpc.noaa.gov/pub/weekly/

**Comment by rutujasurve94** [comment]
I had updated _sample.py but the example script needs to be updated instead hence reverted the changes.

**Comment by ehsteve** [comment]
@rutujasurve94 I added a comment to your PR to show you how to download the data.

**Comment by rutujasurve94** [comment]
Hi, thanks a lot.
I've updated the PR #4135 to download the data and use it as time-series. Thanks a lot for the Fido snippet for downloading data.
