### ISSUE TITLE
Provide easier access to valid TimeSeries source keywords

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#4168]
### Description

I suggest that it should be shown at the top when a user inputs the command
```python
help(TimeSeries)
```

**Comment by hayesla** [comment]
I think all the supported timeseries can recognize the source from the input data file in `is_datasource_for`. 

However it would be nice to have a way to easily access them, we should also have a check to see if the source provided is valid. 

We should have a better error for things like this:

```python
>>> my_timeseries = sunpy.timeseries.TimeSeries(sunpy.data.sample.GOES_XRS_TIMESERIES, 
                                     source='lyra')
ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': ValueError('Time 07/06/2011 does not match iso format'), 'isot': ValueError('Time 07/06/2011 does not match isot format'), 'yday': ValueError('Time 07/06/2011 does not match yday format'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': ValueError('Time 07/06/2011 does not match fits format'), 'byear_str': ValueError('Time 07/06/2011 does not match byear_str format'), 'jyear_str': ValueError('Time 07/06/2011 does not match jyear_str format'), 'astropy_time': TypeError('Input values for astropy_time class must all be same astropy Time type.')}
```

as the source keyword over rights the detection from the input filename itself.

**Comment by ehsteve** [comment]
Good point! Then why do we set the source in the gallery examples explicitly? In any case, it would nice to easily look it up and not have to run to the online docs.

**Comment by hayesla** [comment]
Actually the more I think about it there is really no reason for source? Unless I'm missing something. 

Even if you made a `TimeSeries` from your own data and use `source` the data does not have to conform to the `source` data structure as far as I can tell (i.e. same column names or meta information). 

But again I could be missing something on why `source` exists ....

**Comment by hayesla** [comment]
But yes, it probably should be removed from the docs and example gallery unless someone else has a point to why its there

**Comment by hayesla** [comment]
Wait it's needed for 'NOAAIndices',  'NOAAPredictIndicesTimeSeries' and 'EVESpWxTimeSeries' - but not for the others

**Comment by hrs2203** [comment]
hey @nabobalis, I would like to start working on this issue, can I get some references for understanding.

**Comment by satyamroy001** [comment]
Do we need a function, as just I saw in the top as help(TimeSeries) that would list all the functions and commands of time series? isn't that?
Just like what we do on shell/CMD command--help @nabobalis

**Comment by nabobalis** [comment]
Hmm, I guess I would envision that when you do: `help(TimeSeries)`, I guess there would a be list of source keywords so users might know what to add if they have to.

The main holdup is that in the future we would want to remove this feature of time series, so it will auto detect all file types you pass into the class.

**Comment by satyamroy001** [comment]
!pip install h5netcdf
from inspect import getmembers, isclass
from sunpy import timeseries
def helptimeseries():
  print(getmembers(timeseries, isclass))

this will be the best approach to print all the class, then If we modily the help function to, discuss more about each class later on!! @nabobalis sir

**Comment by nabobalis** [comment]
We don't want to just print the class names, I don't think those are they keywords used for the sources. But you would have to check.

**Comment by satyamroy001** [comment]
Ok @nabobalis sir, do we have to give proper description also after printing the name of th class?

**Comment by nabobalis** [comment]
Please don't call me sir. 

No, we probably only a formatted list of allowed source keywords added to the docstring.
We can do this dynamically or we could just add it manually to the parameters section.

**Comment by hayesla** [comment]
Yes, I agree this could just be an addition to the docstring. For reference the sources currently supported are: 
`["esp", "eve", "gbmsummary", "lyra", "noaaindices", "noaapredictindices", "norh", "rhessi", "xrs"]`

**Comment by satyamroy001** [comment]
ts_eve = sunpy.timeseries.TimeSeries(sunpy.data.sample.EVE_TIMESERIES, source='EVE')
ts_goes = sunpy.timeseries.TimeSeries(sunpy.data.sample.GOES_XRS_TIMESERIES, source='XRS')
ts_lyra = sunpy.timeseries.TimeSeries(sunpy.data.sample.LYRA_LEVEL3_TIMESERIES, source='LYRA')
ts_norh = sunpy.timeseries.TimeSeries(sunpy.data.sample.NORH_TIMESERIES, source='NoRH')
ts_rhessi = sunpy.timeseries.TimeSeries(sunpy.data.sample.RHESSI_TIMESERIES, source='RHESSI')
ts_gbm = sunpy.timeseries.TimeSeries(sunpy.data.sample.GBM_TIMESERIES, source='GBMSummary')

I found this code, in docs 9 types of sources supported till now, do I have to make a help() function that will show these all 9 along with the classes? @nabobalis

**Comment by nabobalis** [comment]
I don't quite follow. You will want to add this information into the docstring for Time Series, not make a help function that will return it.

**Comment by satyamroy001** [comment]
Ok I will add them in doc-string!! Thank you ☺️

**Comment by satyamroy001** [comment]
In which file I have to put the do string @nabobalis

**Comment by nabobalis** [comment]
The string for the main timeseries class. I forgot what file that is in.

**Comment by satyamroy001** [comment]
do I put docstring on metadata.py or __init__.py in time series? @nabobalis

**Comment by nabobalis** [comment]
> do I put docstring on metadata.py or **init**.py in time series? @nabobalis

It will be in the Generic Timeseries class, that I think is in the timeseriesbase.py? You'll have to check.

**Comment by satyamroy001** [comment]
ok!!!!!!
