### ISSUE TITLE
Cannot pass sortby keyword argument through to MapSequence from Map

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4170]
`MapSequence` accepts a `sortby` keyword argument that can be used to optionally sort the maps in the sequence in different ways. However, if you try to pass this kwarg in through `Map`, eg.

```python
sunpy.map.Map(file_list, sequence=True, sortby=None)
```

you get the following exception,

```python-traceback
TypeError: __init__() got an unexpected keyword argument 'sortby'
```

Presumably, this is because `Map` does not properly deal with the `sortby` kwarg before it can be passed to `MapSequence`.

**Comment by ayshih** [comment]
I believe the list of Maps will already be sorted by filename before the `MapSequence` is created, so passing through `sortby=None` may not work the way a user wants.  I'm thinking that we should actually have a `sortby` keyword that functions at the `MapFactory` level, regardless of whether the output is a list or a `MapSequence`.  (Then, if `sequence=true`, it creates a `MapSequence` with `sortby=None` to preserve the already chosen sorting.)

**Comment by wtbarnes** [comment]
Interestingly, `sortby` works as expected if you pass a list of `Map`s to `Map` with `sequence=True`, but if you pass a list a filenames, the error is as above. I'm guessing this has to do with the way the factory handles files versus maps that have already been created.
