### ISSUE TITLE
New GOES XRS (16- 17) data will be in netcdf format 

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4173]
### Description
GOES-15 X-ray sensor is currently no longer operational (i.e no more GOES data from GOES-15). 
GOES-16 and 17 are now taking data are are being used by SWPC for flare classification. GOES-16 has actually been observing since 2017 but the XRS data has not been publicity released - but hurrah as far as I'm aware NOAA are planning to release this data next week (both the new data and the data which overlaps GOES-15) 🎉 

This data will be hosted here https://www.ngdc.noaa.gov/stp/satellite/goes-r.html and will be in netcdf format.

Similarly now NOAA has just released re-processed science quality data for GOES13-15, also in netcdf. 

There were rumblings of a netcdf reader in sunpy but is there one/a plan for one? If not we're going to need one 🌞

**Comment by wtbarnes** [comment]
#3738 is probably relevant here.

**Comment by Cadair** [comment]
It's much easier to add support for netcdf to Timeseries than Map. However, we will need to have a detailed think about adding the dependency required to read the files.

**Comment by ayshih** [comment]
As a correction, the 1-second XRS data has actually been publicly available for a while through NOAA CLASS, albeit in an extremely awkward form (in 30-second-long netCDF4 Classic files that have to be requested through a website).  netCDF4 Classic is particularly annoying because it is resistant to concatenation, so if I recall correctly, I couldn't use `pycdf` satisfactorily, and instead used `xarray`.  I hope that the new science products are not also netCDF4 Classic.

**Comment by hayesla** [comment]
Yes thats true, but its in such a pain of a format. I was using `netCDF4` which works pretty well, but never thought of xarray but that also works well. 

Unfortunately it looks like they will netCDF4 classic, this is going from the re-processed GOES 13-15 files here: https://satdat.ngdc.noaa.gov/sem/goes/data/science/xrs/goes15/gxrs-l2-irrad_science/ 

But again both netCDF4 and xrray work well

**Comment by nabobalis** [comment]
Could use https://pypi.org/project/h5netcdf/?

**Comment by hayesla** [comment]
is there a preference for h5netcdf rather than xarray? both work?

Does sunpy have a dependency h5?

**Comment by dstansby** [comment]
As discussed on the call today, making this work requires work doing to support source-dependent file loading in `sunpy.map` (similar to `sunpy.timeseries`). Any work on this should probably start by modifying `sunpy.map` in order to support source dependent file loading.

**Comment by wtbarnes** [comment]
> As discussed on the call today, making this work requires work doing to support source-dependent file loading in `sunpy.map` (similar to `sunpy.timeseries`). Any work on this should probably start by modifying `sunpy.map` in order to support source dependent file loading.

XRS data is not spatially resolved and is handled completely by `sunpy.timeseries`
