### ISSUE TITLE
Functionality for parse_time to take list as input

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4174]
### Description
It would be super handy if `sunpy.time.parse_time` could take in a list of time inputs and return a list of the `astropy.time.Time` objects.

I find myself again and again doing things like
```python

time_dt = [parse_time(x) for x in list_of_times]
```

where it would be great just to do
```python
time_dt = parse_time(list_of_times)
```

What are peoples thoughts on this?

**Comment by ayshih** [comment]
Is there a chance that something is out of date in your setup?  Currently, if you call `parse_time()` on a list of time inputs, you get back an array `astropy.time.Time` object.

Or, are you specifically requesting that it return a list of scalar `astropy.time.Time` objects *instead* of a single, array `astropy.time.Time` object?  I'd be resistant to that notion.

**Comment by ayshih** [comment]
Ah, my mistake!  It's been a while since I've worked with inputs that couldn't be directly parsed by `astropy.time.Time` (e.g., `'2001-Jan-01'` instead of `'2001-01-01'`).  This is only a problem for certain types of inputs in a list.  For example, the current behavior is:
```python
>>> parse_time(['2001-01-01', '2001-01-02'])
 <Time object: scale='utc' format='iso' value=['2001-01-01 00:00:00.000' '2001-01-02 00:00:00.000']>

>>> parse_time(['2001-Jan-01', '2001-Jan-02'])
(errors out)
```

Absolutely, `parse_time()` should be fixed so that the two examples above return the same output.

**Comment by hayesla** [comment]
oh strange! - yes I was working with `%Y-%b-%d` formats. Yes an array of `astropy.time.Time` object return is exactly what I'm looking for (rather than a list of `astropy.time.Time` objects)

I'l look into this some more for a fix

**Comment by dstansby** [comment]
I think if you pass the right time format to `parse_time` this should work fine?

**Comment by hayesla** [comment]
I think this is actually a 🐛 

For example this works:

```python
>>> time_list1 = ['2001-01-01', '2001-01-02', '2001-01-03']
>>> parse_time(time_list1[0])
        <Time object: scale='utc' format='isot' value=2001-01-01T00:00:00.000>
>>> parse_time(time_list1)
       <Time object: scale='utc' format='iso' value=['2001-01-01 00:00:00.000' '2001-01-02 00:00:00.000'
 '2001-01-03 00:00:00.000']>
```

However for a date in format %Y-%b-%d `parse_time works on it as a string but not as a list - for examples:

```python
>>> time_list2 =  ['2001-Jan-01', '2001-Jan-02', '2001-Jan-03']
>>> parse_time(time_list2[0])
      <Time object: scale='utc' format='isot' value=2001-01-01T00:00:00.000>
>>> parse_time(time_list2)
ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': ValueError('Time 2001-Jan-01 does not match iso format'), 'isot': ValueError('Time 2001-Jan-01 does not match isot format'), 'yday': ValueError('Time 2001-Jan-01 does not match yday format'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': ValueError('Time 2001-Jan-01 does not match fits format'), 'byear_str': ValueError('Time 2001-Jan-01 does not match byear_str format'), 'jyear_str': ValueError('Time 2001-Jan-01 does not match jyear_str format'), 'astropy_time': TypeError('Input values for astropy_time class must all be same astropy Time type.')}
```

So there is a wierd bug for when that format is in a list for some reason

**Comment by dstansby** [comment]
Ah, that's because for individual strings we have a lot of special case handling and (not terribly well documented) to allow for a wider range of formats, but that is only currently applied to individual strings. Have opened a PR with a fix.
