### ISSUE TITLE
Edits to map.{draw_rectangle, submap}

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4175]
To keep a list for myself, so I don't forget between now and opening a PR, my suggested edits to https://github.com/sunpy/sunpy/pull/3677 are

- Add more tests to get patch coverage to 100% (see https://codecov.io/gh/sunpy/sunpy/compare/ead9cd3c62741aaa15b35d0e836c491fc38795a0...1a3b4ac6620f794b5289bbc7c741f8081da46d07/diff)
- Add a fuller changelog instructing users how to change their code from 1.1 to 2.0
- Have consistent behaviour/erroring/warnings for when bottom_left and top_right are in the wrong order (https://github.com/sunpy/sunpy/pull/4179)

**Comment by wtbarnes** [comment]
All of these components have been separated into or added onto other issues so I'm going to close this.
