### ISSUE TITLE
Improve Map __str__

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4201]
`Map` has an nice `__repr__`, but currently `print(map)` just prints the data array. It would be nice if `print(map)` could print some extra info like in `__repr__` (maybe even the same info?).

**Comment by Cadair** [comment]
:+1: for all `__repr__`'s being `return f"{object.__repr__(self)}\n{self}"`.

**Comment by sidhu1012** [comment]
Is this issue up? I would like to work on this issue.

**Comment by nabobalis** [comment]
Should be.

**Comment by sidhu1012** [comment]
> Should be.

On it!

**Comment by sidhu1012** [comment]
@nabobalis Was not able to find any __str__ in maps,  are they present or shall I add them

**Comment by nabobalis** [comment]
They aren't present in Generic Map as far as I am aware.

**Comment by sidhu1012** [comment]
> They aren't present in Generic Map as far as I am aware.

Shall I add them , same as repr?

**Comment by nabobalis** [comment]
Yeah.

**Comment by sidhu1012** [comment]
> Yeah.

Okay😁
