### ISSUE TITLE
Add Map.shape

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4202]
Currently it's possible to do `m.size` to get the size of the data in the map. Would be nice to add `m.shape` to get the shape of the data (instead of having to do `m.data.shape`).

**Comment by mridullpandey** [comment]
can i take this up
@dstansby

**Comment by Cadair** [comment]
We already have `m.dimensions` which returns the dimensions a a `u.Quantity`. I think we picked "dimensions" to make people understand it's not the same as shape because it's a quantity

**Comment by mridullpandey** [comment]
I think it's not a beginner-friendly issue

**Comment by dstansby** [comment]
Hmm, but `m.size` works fine and returns a `Quantity` so I kind of expected `m.shape` to work too, even if it did return a `Quantity`. There's also precedence to just return `m.data.shape`, as that is what `SkyCoord` does. I think either one would be fine, but having `m.shape` would be nice to 'mimick' numpy array properties.

**Comment by dipanshu231099** [comment]
@Cadair @dstansby could you point me to the code if still the functionality is required

**Comment by wtbarnes** [comment]
I agree that having `shape` would be convenient, but it is potentially ambiguous. Is this the shape in the sense of the underlying array or in the sense of the coordinate aware map? I think one could reasonably expect either and it is not a huge burden to get it through `map.data.shape`. For the sake of not having that ambiguity, I'd be in favor of not including a `shape` attribute.

**Comment by dstansby** [comment]
Happy to recommend `map.data.shape` instead, but if we do that I think we should deprecate and remove `m.size`.

**Comment by wtbarnes** [comment]
Sounds good to me!

**Comment by wtbarnes** [comment]
Closing and moving discussion of `size` to #4337
