### ISSUE TITLE
zenodo entry missing for 1.1.3 release

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4209]
I want to cite the 1.1.3 release in a paper, but it doesn't look like the 1.1.3 release has been properly archived on zenodo. https://zenodo.org/record/3779284 lists the most recent release as 1.0.10, and the most recent 1.1.x release on zenodo is 1.1.2.

**Comment by wtbarnes** [comment]
We could just submit the 1.1.3 release by hand I guess?

**Comment by dstansby** [comment]
Now 1.1.4 is up, and there wasn't much time between 1.1.3 and 1.1.4, personally I'm not too bothered about this any more.

**Comment by wtbarnes** [comment]
Unfortunately, I just realized that, because of the order I did the releases in, Zenodo now shows the "latest" version as 1.0.11 🤦
