### ISSUE TITLE
Figure test infastructure should automatically delete unused figures

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4232]
When the figure tests are changed, merging into master automatically uploads a copy of the new figures to https://github.com/sunpy/sunpy-figure-tests/. However, if an image test is removed, the corresponding image isn't removed from that repository, e.g.: https://app.circleci.com/pipelines/github/sunpy/sunpy-figure-tests/31/workflows/f34ac1c1-6ff4-4eb0-8af7-cee458688e6a/jobs/32/steps

It would be good if the code that automatically updates figures can also automatically delete removed ones.

**Comment by Cadair** [comment]
This would require adding some additional steps to this lovely one line bash script in the circleci config: https://github.com/sunpy/sunpy/blob/master/.circleci/config.yml#L133

**Comment by dipanshu231099** [comment]
i would like to solve the issue but i am a new comer can you point me in the right direction

**Comment by nabobalis** [comment]
Hi @dipanshu231099, as cadair said above, you will need to work out the correct bash commands in order to do so and add them to https://github.com/sunpy/sunpy/blob/master/.circleci/config.yml#L133

**Comment by Cadair** [comment]
Depends how familiar you are with bash :rofl: 

Although you will also need to setup your own circleci builds to really test it, so it's not simple.

**Comment by dipanshu231099** [comment]
> Depends how familiar you are with bash rofl
> 
> Although you will also need to setup your own circleci builds to really test it, so it's not simple.

yeah i think ill keep looking for some easier issues first.

**Comment by jeffreypaul15** [comment]
Wouldn't deleting the contents of the `/home/circleci/sunpy-figure-tests/figures/$TOXENV` directory just before :
https://github.com/sunpy/sunpy/blob/1af5f60024a47827f2c50062d772a62d5da30e42/.circleci/config.yml#L77
solve this issue? As ` --mpl-generate-path=/home/circleci/sunpy-figure-tests/figures/$TOXENV` generates the new figures (including the old ones as well), stores it in this directory and the unused ones are taken care of.
