### ISSUE TITLE
SunpyDeprecationWarnings should cause the doc build to fail

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4255]
This is especially true in the gallery. I tried to set a filter in the `conf.py` file, but that didn't seem to propagate into the gallery.

**Comment by dipanshu231099** [comment]
@Cadair does this require building on my local system. If so i would like to pursue this kind of issue.

**Comment by nabobalis** [comment]
Yes, the easiest way to make sure this works is to build it locally and test it.

**Comment by dipanshu231099** [comment]
@nabobalis can you guide a little for the sources to be built.😅

**Comment by nabobalis** [comment]
You would need to create a gallery example that raises a `SunpyDeprecationWarnings` then build the documentation with the gallery and work out the correct commands in `docs/conf.py` to get that example to fail. We do not want any examples running with old sunpy commands.

**Comment by dipanshu231099** [comment]
@nabobalis has this issue been resolved or is it still open ?

**Comment by nabobalis** [comment]
The issue is still open, I have attempted to fix this in #4331 but my solution so far isn't working.

**Comment by nabobalis** [comment]
> The issue is still open, I have attempted to fix this in #4331 but my solution so far isn't working.

My attempts have failed.
