### ISSUE TITLE
make_fitswcs_header should take observer_coordinate as input

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4263]
It would be good if `make_fitswcs_header` took an observer coordinate as input, and put it into `hgln_obs` etc. keywords in the fits header.

**Comment by Cadair** [comment]
You have to specify the `observer=` property of the `coordinate=` kwarg.

i.e. (from the docstring)
```python
my_coord = SkyCoord(0*u.arcsec, 0*u.arcsec, obstime="2017-08-01",
                    observer='earth', frame=frames.Helioprojective)
my_header = sunpy.map.make_fitswcs_header(data, my_coord)
```

The reason we ended up with it being like this and not a separate kwarg is that then you don't have the confusion of worrying about if the frame should have observer or not (although with SkyCoord you can always set it anyway).

**Comment by dstansby** [comment]
Thanks! I'm going to label this as a doc update issue then, to make it a bit clearer that this is where the observer coord should go.
