### ISSUE TITLE
Move away from Package Novice and to Good First Issue

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4268]
We currently to use "Package Novice" in our documentation to direct people to issues they can start with.

But with the introduction of the "Good First Issue" label, we need to update our documentation to reflect this. We should be using this label but to do so we also need to tag issues with it.

**Comment by mridullpandey** [comment]
hi@nabobalis greetings!
I'm taking this up
suggestions are welcome.

**Comment by nabobalis** [comment]
Hi @mridullpandey, to tackle this issue requires the ability to relabel our issues which is limited to a handful of people. They will be the only ones who can do this. 

What you could do is change the places in our documentation that refer to "Package Novice" and replace it with "Good First Issue".

**Comment by mridullpandey** [comment]
okay

**Comment by kakirastern** [comment]
@mridullpandey Are you still working on this?

**Comment by nabobalis** [comment]
A PR was made that changed the contributing guide but now we need to update our issue labels.

**Comment by kakirastern** [comment]
Cool, was wondering since nothing regarding that PR is showing up in this issue. Good to know it is being handled. 👍🏼
