### ISSUE TITLE
Enable a HeliographicCarrington frame to be defined using only the Sun-observer distance

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4279]
Our `HeliographicCarrington` frame is now observer-based (#3782), and the API requires a complete coordinate for the observer.  This turns out to be awkward when wanting to create a `HeliographicCarrington` coordinate representing an observer location, because the observer coordinate is seemingly needed to define the frame for the observer coordinate.  Mathematically, the `HeliographicCarrington`->`HeliographicStonyhurst` transformation needs only the Sun-observer distance, and modifies only the longitude component, so the circular loop is solely a consequence of the implementation.

There should be a way to define a `HeliographicCarrington` frame using only the Sun-observer distance, as opposed to a complete coordinate for the observer.  Either a new frame attribute can be added or our existing `ObserverCoordinateAttribute` can be extended.

**Comment by Cadair** [comment]
Oh this is going to be a fun trip down descriptor lane.

**Comment by ayshih** [comment]
Ooh, I have an idea...

**Comment by ayshih** [comment]
I'll point out for posterity that #4659 resolves only the case with creating a HGC coordinate representing an observer location, and not the more general request that I wrote here.  I don't think anyone actually is particularly interested in the more general functionality, which is why I closed this issue.

**Comment by kakirastern** [comment]
This is important to note
