### ISSUE TITLE
HelioviewerClient downloads image with wrong date

### ISSUE THREAD

**Issue by vit1-irk** [sunpy/sunpy#4286]
### Description

Just try to run this code sample:

```python
import sunpy.map
from sunpy.net.helioviewer import HelioviewerClient

hv = HelioviewerClient()

hv_file = hv.download_jp2("2014/10/05 00:00:00",
        observatory="SOHO",
        instrument="EIT",
        measurement="171",
        progress=False)
aia_map = sunpy.map.Map(hv_file)
aia_map.plot()
print(aia_map.name)
```
![Снимок экрана 2020-06-13 в 18 26 37](https://user-images.githubusercontent.com/3207316/84566439-b8cdf000-ada3-11ea-9417-756b4913f01c.png)

### Expected behavior
Image with correct date and time is downloaded

### Actual behavior
Image with WRONG date & time was downloaded

### System Details
sunpy is the latest version from Git master branch

```
==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Saturday, 13. June 2020 10:38AM UT
System : Linux
Processor : 
Arch : 64bit
SunPy : Missing sunpy version.
OS: Arch Linux   (Linux 4.15.0-101-generic )


##################
Required Libraries
##################
Python: 3.8.3
NumPy: 1.17.4
SciPy: 1.3.3
matplotlib: 3.1.2
Astropy: 3.2.3
Pandas: 0.25.3
parfive: 1.1.0


#####################
Recommended Libraries
#####################
beautifulsoup: 4.8.1
PyQt4: NOT INSTALLED
PyQt5: 5.15.0
Zeep: 3.4.0
Sqlalchemy: 1.3.13
drms: 0.5.7
```

**Comment by vit1-irk** [comment]
Important clarification: a few months ago everything was correct about downloading
Maybe it is a server issue

**Comment by vit1-irk** [comment]
```python
hv_file = hv.get_closest_image("2017-09-07T02:05:00Z",
        observatory="SOHO",
        instrument="EIT",
        measurement="171")

print(hv_file)
```

```
{'id': '30026285', 'date': <Time object: scale='utc' format='isot' 
value=2013-08-07T13:00:13.000>, 'name': 'EIT 171', 'scale': 2.640156267194894, 'width': 1024, 'height': 1024, 'refPixelX': 506.93, 'refPixelY': 515.32, 'sunCenterOffsetParams': [], 'layeringOrder': 1}
```

**Comment by ebuchlin** [comment]
This comes from the server: `https://api.helioviewer.org/v2/getJP2Image/?date=2017-10-05T00:00:00Z&sourceId=0&jpip=true` gives `jpip://helioviewer.org:8090/EIT/2013/08/07/171/2013_08_07__13_00_13_864__SOHO_EIT_EIT_171.jp2`

But this is expected: there are no EIT images in the HV archive after 2013-08-07, as can be seen from the JPEG2000 files: `https://helioviewer.org/jp2/EIT/` (yes, there are 2 directory structures, `WWW/YYYY/MM/DD` and `YYYY/MM/DD/WWW`, this is also known).

EIT is still observing, but then it is up to the HelioViewer projet to ingest the latest data.

**Comment by wtbarnes** [comment]
This definitely seems like a Helioviewer issue on the server side but perhaps @wafels can confirm?

**Comment by vit1-irk** [comment]
@ebuchlin Yeah, looks like they don't want to store recent data (or they deleted it), despite the fact EIT is still [observing](https://umbra.nascom.nasa.gov/eit/eit_full_res.html). Maybe it is worth contacting Helioviewer staff for some explanations or providing clear error messages on Sunpy side

**Comment by wtbarnes** [comment]
Ok I'm going to close this then as this is out of scope for sunpy
