### ISSUE TITLE
Add datamanager docs to the User's guide

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4302]
I went looking through the user guide (https://docs.sunpy.org/en/stable/guide/acquiring_data/index.html) for some narrative docs on using `sunpy.data.manager`, but couldn't find any - it would be good to add some docs there to make it more discoverable.

**Comment by Cadair** [comment]
data manager largely isn't user facing API, it's developer API, so most of the documentation for it is in the developer guide: https://docs.sunpy.org/en/latest/dev_guide/remote_data.html

The only part of the API I would consider user facing is the override stuff. However, I think we need to be careful about how we document that to not confuse people. Having a section on it maybe in the code reference which could be linked from functions which are making use of the data manager might be best?

**Comment by dstansby** [comment]
If it's not user facing it probably shouldn't be the first example in the example gallery!

**Comment by dstansby** [comment]
Thanks for the link to the dev guide; in my head the dev guide was a "how to develop sunpy", as opposed to "here is sunpy API that is helpful if you are developing other packages". Indeed, I think "remote data manager" is an exception and the only section in the dev guide that is "sunpy API helpful for developing another pacakge".

**Comment by Cadair** [comment]
> If it's not user facing it probably shouldn't be the first example in the example gallery!

yeah, why is that at the top :confused: 

> Indeed, I think "remote data manager" is an exception and the only section in the dev guide that is "sunpy API helpful for developing another pacakge".

yeah that's fair, our whole docs need a reorganize, not sure it fits in the user guide either in that way?
