### ISSUE TITLE
Support for saving intermediate data products

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#431]
Is there a good way to save intermediate SunPy data products? The pickle module does not work properly on some SunPy objects at the moment (e.g. maps, where the header information gets lost).

As an example, I may want to process some data only once (maybe it's time consuming) and generate some products which I then want to work with or manipulate many times, over multiple Python sessions.

**Comment by swapsha96** [comment]
@Cadair close?

**Comment by Cadair** [comment]
This is probably a good use case for #2366
