### ISSUE TITLE
2.0: test_hgc100 fails

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#4320]
### Description

I am currently in the process of building and uploading sunpy 2.0 to Debian. During the automates build time test, I see a failure in `test_hgc100()`.

### Expected behavior

The test should pass.

### Actual behavior

```
_________________________________ test_hgc_100 _________________________________

    def test_hgc_100():
        # Test that HeliographicCarrington is populated with Earth as the observer when loading a
        # older schema (1.0.0)
        test_file = os.path.join(os.path.dirname(__file__), "hgc_100.asdf")
        with asdf.open(test_file) as input_asdf:
            hgc = input_asdf['hgc']
>           assert isinstance(hgc, frames.HeliographicCarrington)
E           AssertionError: assert False
E            +  where False = isinstance({'data': <CartesianRepresentation (x, y, z) in AU\n    (-0.78131272, -0.59475725, -0.05218885)>, 'frame_attributes': {'obstime': <Time object: scale='utc' format='isot' value=2001-01-01T00:00:00.000>}}, <class 'sunpy.coordinates.frames.HeliographicCarrington'>)
E            +    where <class 'sunpy.coordinates.frames.HeliographicCarrington'> = frames.HeliographicCarrington

sunpy/io/special/asdf/tags/tests/test_coordinate_frames.py:52: AssertionError
```

### Steps to Reproduce

Build sunpy on Debian unstable, resolving all dependencies with apt.

### System Details

- SunPy Version: 2.0
- Astropy Version: 4.0.1+post1
- Python Version: 3.8.3
- OS information: Debian unstable

Additionally (since it may be relevant): asdf version 2.6.0

**Comment by Cadair** [comment]
This looks like the entry points sunpy registers with asdf haven't worked, asdf isn't deserialising the coordinate frame to the sunpy coordinate frame class.

Does the debian packaging need to do anything special to handle entrypoints?

**Comment by olebole** [comment]
This explains it: the test is done before the package was installed anywhere (just after the build, before we install it). So, entrypoints are not installed at this moment.

I am going to close this (and to disable the test during the build). Thank you for the explanation.

**Comment by Cadair** [comment]
No worries, thanks for packaging sunpy :grin:
