### ISSUE TITLE
Should coordinates.sun.B0 return a Latitude object?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4322]
https://docs.sunpy.org/en/stable/api/sunpy.coordinates.sun.B0.html, returns "the heliographic latitude of the of the center of the disk of the Sun as seen from Earth.". Currently the return type is an `Angle`, and in a few tests both here and in `heliopy` I've had to convert this to a `Latitude` object to compare with other coordinates etc.

So should the return type of `B0` be `Latitude`? I think it should be, but thought I'd open an issue to solicit input before making a PR.

**Comment by dstansby** [comment]
Also worth noting that `L0` (https://docs.sunpy.org/en/stable/api/sunpy.coordinates.sun.L0.html#sunpy.coordinates.sun.L0) returns a `Longitude` object (as opposed to an `Angle`).

**Comment by ayshih** [comment]
Yup, the return type should probably be `Latitude`.
