### ISSUE TITLE
Fix CRDER nan values in HMI maps

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4324]
Loading a HMI map (e.g. https://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/downloading_hmi.html#sphx-glr-generated-gallery-acquiring-data-downloading-hmi-py) results in a bunch of these warnings:
```
WARNING: FITSFixedWarning: CRDER1 = 'nan ' 
a floating-point value was expected. [astropy.wcs.wcs]
WARNING: FITSFixedWarning: CRDER2 = 'nan ' 
a floating-point value was expected. [astropy.wcs.wcs]
```

It would be good to fix the header in the `HMI` map source to prevent these warnings.

**Comment by ayshih** [comment]
Related discussions: astropy/astropy#10153 and astropy/astropy#10165

In [this comment](https://github.com/astropy/astropy/pull/10165#issuecomment-616011425) from astropy/astropy#10165, @ndl303 said:
> On another note: I was speaking to the SDO HMI people and they have already started the process of making their FITS files compliant, which is probably a good thing.

Given that, we may not want to take any steps towards squelching these warnings.

**Comment by Cadair** [comment]
I think that in general exposing warnings to the user about invalid FITS is a good thing, if we always hide these people will never learn :rofl:

**Comment by dstansby** [comment]
How about warning once when loading the map and then fixing it? Currently the warning is thrown a lot, as it's every time `.wcs` is accessed on the map (I think), which can lead to a lot of warnings cluttering a terminal/notebook.

**Comment by dstansby** [comment]
More generally, should we be warning every time we change some metadata in the map source `__init__`s? Should probably have a consistent policy about how to handle stuff there 😆

**Comment by Cadair** [comment]
> Currently the warning is thrown a lot, as it's every time .wcs is accessed on the map (I think), which can lead to a lot of warnings cluttering a terminal/notebook.

Ah this would be an unintended side effect of the PSP changes to the generation of the WCS object. This is probably worth considering. (tbh I would expect these to be raised the first time you load the header out of the FITS file).

> More generally, should we be warning every time we change some metadata in the map source __init__s? Should probably have a consistent policy about how to handle stuff there

I think we did discuss this or something close to it reasonably recently. I can't remember in what context tho... :thinking:

**Comment by nabobalis** [comment]
So what do we want to fix here now?

**Comment by dstansby** [comment]
I think we just want to remove the CRDER values if they are `nan`, since `nan` isn't valid in the FITS spec.

**Comment by wtbarnes** [comment]
So when the HMI FITS file is loaded, we warn once about the `nan` values and then fix them and in the original warning we say we are fixing them. That seems sensible to me, but is that the agreed upon solution?

**Comment by wtbarnes** [comment]
Related, do we want to do this with every FITS header we read in (i.e. remove the `nan`s)? Or just target these specific keywords in the HMI source?

**Comment by dstansby** [comment]
> So when the HMI FITS file is loaded, we warn once about the `nan` values and then fix them and in the original warning we say we are fixing them. That seems sensible to me, but is that the agreed upon solution?

My vote is for this solution. I am happy and actively want to apply this to current metadata fixes. There are several points where sunpy silently assumes units are `arcsec` if they're not in the FITS header for example.

> Related, do we want to do this with every FITS header we read in (i.e. remove the nans)? Or just target these specific keywords in the HMI source?

Good point, as far as I'm aware NaN values are not valid FITS, so I think general functionality to warn and remove all NaNs would be good (if I'm right).

**Comment by dstansby** [comment]
Removing good first issue as this needs discussion/design decisions before code changes can be made.

**Comment by dstansby** [comment]
I think https://github.com/sunpy/sunpy/issues/4324 makes this issue moot, so I've marked that PR as fixing this issue.
