### ISSUE TITLE
Corrupted fits files when downloading near real time SDO AIA data.

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#4327]
### Description

Trying to download near real time SDO AIA data appears to work correctly but the fits file contains a 403 http error message and a series of null bytes.

### Expected behavior

The correct fits files to be downloaded or an exception is raised

### Actual behavior

Download seem to work but when try to load the fits file turns out to be corrupted/ not a fits file at all

### Steps to Reproduce

```python
from sunpy.map import Map
from sunpy.net import Fido, attrs as a

# I think it import the dates are for the last 24 hours or so to hit the near real time file versus standard data
query = Fido.search(a.Time('2020-06-29 00:00', '2020-06-29 01:00'), a.Instrument('AIA'))
dl = Fido.fetch(query[0,0])
m = Map(dl)

```

inspecting the file file you see something like

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /data/aia/synoptic/2020/06/29/H0000/AIA20200629_000000_0094.fits
on this server.<br />
</p>
</body></html>
```

#######
General
#######
Time : Monday, 29. June 2020 04:35PM UT
System : Darwin
Processor : i386
Arch : 64bit
SunPy : Missing sunpy version.
OS: Mac OS X 10.15.4 (i386)

##################
Required Libraries
##################
Python: 3.7.4
NumPy: 1.19.0
SciPy: 1.5.0
matplotlib: 3.2.2
Astropy: 4.0.1.post1
Pandas: 1.0.5
parfive: 1.1.0

#####################
Recommended Libraries
#####################
beautifulsoup: 4.9.1
PyQt4: NOT INSTALLED
PyQt5: NOT INSTALLED
Zeep: 3.4.0
Sqlalchemy: 1.3.17
drms: 0.5.7

**Comment by Cadair** [comment]
This seems to be related to parfive requesting ranges of bytes from the download server. VSO are investigating, and parfive should probably bubble up being able to disable this behaviour.

**Comment by dstansby** [comment]
I think this is probably the same as https://github.com/sunpy/sunpy/issues/4159

**Comment by ejm4567** [comment]
I've disabled the modsecurity rule that is causing the 403 error.

Please re-test and let us know if you still have problems.

**Comment by Cadair** [comment]
Seems to have fixed it for me, thanks @ejm4567
