### ISSUE TITLE
Deprecate map.size

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4337]
Given the discussion in #4202, we should deprecate the `size` attribute on `Map` for consistency as we do not want to add a `shape` attribute for the reasons listed in that issue.

**Comment by dipanshu231099** [comment]
@wtbarnes i have added the depreacation, can you assure me of the 'since' version I shall use.

**Comment by wtbarnes** [comment]
> @wtbarnes i have added the depreacation, can you assure me of the 'since' version I shall use.

Let's have the code discussion on #4338, but it looks like you have the right `since` there.
