### ISSUE TITLE
MapSequence Animations Slider

### ISSUE THREAD

**Issue by jamisenma** [sunpy/sunpy#4385]
Hi guys,
2 quick questions:

1. Does anyone know how to control 2 MapSequence Animations with 1 slider? I'm using sunpy.visualization.animator.MapSequenceAnimator().

2. In the picture attached below, the 2 values circled in red 0.0, 8.0 are the slider value of each animation. I looked though the sunpy and Matplotlib documentation, and I found cropped_flare_animation._sliders[0].slider.val should get it, but it keeps returning 0. Is there another way to get this value?
![Screen Shot 2020-07-17 at 12 07 09 PM](https://user-images.githubusercontent.com/43462229/87823929-306ebf00-c829-11ea-8673-7332f219467d.JPG)

**Comment by nabobalis** [comment]
Hi @jamisenma, did you make any progress on this?

**Comment by jamisenma** [comment]
I figured out how to do it, but I used a different method. I got the images using drms packages, and displayed it using the imshow function from the matplotlib library.
