### ISSUE TITLE
Showcasing sunpy for the weekly Software Survey!

### ISSUE THREAD

**Issue by vsoch** [sunpy/sunpy#4386]
hey sunpy maintainers!

This week I would like to showcase sunpy for the weekly software survey, you can see the few previous weeks [here](https://rseng.github.io/rseng/blog/). It's a larger effort to teach the community about open source software, and prompt annotation of the research software encyclopedia interface. So akin to the others, it's going to be a simple page that tells users what it is, maybe some fun or interesting facts, and then prompts them to annotate it via the research software engineering database. Do you have any quick fun facts, or generally things you'd like to say about sunpy? I also remember from the usrse job board that you were [looking for a developer](https://numfocus.org/uncategorized/scientific-software-developer-contract-basis-sunpy-project) so I can highlight that too.

Looking forward to chatting!

**Comment by vsoch** [comment]
I hope I did an okay job :) https://twitter.com/vsoch/status/1284926151530385408  Let me know if you want anything changed. Beautiful work on this project, and growing the community. Cheers!

**Comment by Cadair** [comment]
Thanks a lot  @vsoch it was a really great read :smile:
