### ISSUE TITLE
Observer-Sun distance in Yohkoh/SXT Maps?

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4395]
The Yohkoh/SXT map source performs some possibly broken handling of the observer-Sun distance, including oddly creating a new `meta['dsun_apparent']` that doesn't necessarily get used.

_Originally posted by @ayshih in https://github.com/sunpy/sunpy/pull/4391#discussion_r460910743_:

Ugh, I don't like this Yohkoh handling.  We shouldn't add a new item to the dictionary for this.

This comment appears to suggest that the Yohkoh header has the wrong information in the FITS keyword `DSUN_OBS`, which is why a custom header keyword is created:
https://github.com/sunpy/sunpy/blob/db314114f0148d16610dda10f18ea0876942cd61/sunpy/map/sources/yohkoh.py#L52-L54

But, the `dsun` property is written as if `DSUN_OBS` is accurate if present (i.e, `meta['dsun_apparent']` may not actually be used):
https://github.com/sunpy/sunpy/blob/db314114f0148d16610dda10f18ea0876942cd61/sunpy/map/sources/yohkoh.py#L67

So, is `DSUN_OBS` inaccurate or is it not defined?

It seems to me that:

- If `DSUN_OBS` is wrong, it should be fixed and the warning raised upon fixing.
- If `DSUN_OBS` is just sometimes missing, the warning should be raised on access in the `dsun` property.
- Either way, there's no reason to add a new item to the dictionary.
- The fallback should never have a path to a fixed `constants.au`, but rather we should be falling back on an Earth observer.

**Comment by ayshih** [comment]
Ping @wafels since it looks like he wrote this originally.

Also, as a quibble, I don't like that the small angle approximation is used, and the comment even acknowledges that it is "simple trigonometry":
https://github.com/sunpy/sunpy/blob/db314114f0148d16610dda10f18ea0876942cd61/sunpy/map/sources/yohkoh.py#L55-L58

I think we can afford a call to `np.sin()`!

**Comment by wafels** [comment]
Yeah this looks "incomplete" at best :/  I must have written the Map source in order to read the resulting JP2 files into Helioviewer.  However, the JP2 files were written at Montana State University (MSU).  I remember working with someone at MSU on making the JP2 files - that person wrote the code that read the Yohkoh files in and converted them to JP2.

Might be worth downloading a few FITS files from the Yohkoh Legacy Archive to see how they work with the Map source.

**Comment by wafels** [comment]
Yohkoh data can be found here: http://ylstone.physics.montana.edu/ylegacy/
