### ISSUE TITLE
Create an example showcasing how to do URL-scraping to get files for sunpy.map.Map

### ISSUE THREAD

**Issue by akirahirohito** [sunpy/sunpy#4439]
### Description

After some initial discussion on Sunpy's IRC channel, initiated by a new user's queries on how to scrape file path names based on database/archive queries, I would like to propose the introduction of an example that showcases basic web URL-scraping. The example can be added to the "Acquring Data" section of the Example Gallery at https://docs.sunpy.org/en/stable/generated/gallery/index.html#acquiring-data.

A simple example is provided here: 
```
import bs4
import urllib.parse
import urllib.request
base_url = "https://umbra.nascom.nasa.gov/pub/lasco/lastimage/level_05/200824/c2/"
index = urllib.request.urlopen(base_url)
tree = bs4.BeautifulSoup(index.read())
files = [a for a in [a.get("href") for a in tree.find_all("a")] if a.endswith("fts")]
for filename in files:
    urllib.request.urlretrieve(urllib.parse.urljoin(base_url, filename), f"/tmp/{filename}")
```

This example would need to be expanded upon adding context and trying not to be a tutorial on how to use BeautifulSoup4. We can link to websites or other tutorials.

**Comment by nabobalis** [comment]
I personally feel that making map do that is beyond the scope of map file handling. 
This might be a good example to create in our gallery instead.

**Comment by kakirastern** [comment]
Yeah, sure

**Comment by kakirastern** [comment]
Let me open a PR soon

**Comment by kakirastern** [comment]
@nabobalis Do you have any objection to me naming the example `downloading_with_url_scrapping`? Have just started working on the issue.

**Comment by kakirastern** [comment]
Was thinking it is the shortest name I can come up with (operating on the principle of a max length of about 7 words for the file name), but it can be somewhat imprecise and misleading...

**Comment by nabobalis** [comment]
No problem with it.

**Comment by kakirastern** [comment]
Good you are okay with it 🙃

**Comment by hrs2203** [comment]
Hi @nabobalis . I would like to work on this issue.

**Comment by nabobalis** [comment]
Hello @hrs2203 , you can assuming that @kakirastern has stopped working on this. I accidentally unassigned them but maybe you two can coordinate on this.

**Comment by hrs2203** [comment]
Hi @kakirastern , I went through the docs but still the part ``` how to scrape file path names based on database/archive queries efficient ``` is not clear to me. can you provide some additional context.

**Comment by akirahirohito** [comment]
I will assign it to an associate of mine who will take over working on it

**Comment by akirahirohito** [comment]
To @Godslayer201

**Comment by akirahirohito** [comment]
Will confirm the username soon

**Comment by akirahirohito** [comment]
He is applying for GSoC 2021 with OpenAstronomy/SunPy

**Comment by akirahirohito** [comment]
@hrs2203 Sorry, issue has already taken as indicated on IRC

**Comment by akirahirohito** [comment]
Please adhere to CoC and refrain from any non-conformist behaviour @hrs2203

**Comment by hrs2203** [comment]
Sorry but i didn't understand. did i make any mistake.

**Comment by akirahirohito** [comment]
Think so, and a very serious one indeed

**Comment by nabobalis** [comment]
Hi @hrs2203, please ignore this and continue working on this issue.

**Comment by akirahirohito** [comment]
I want to work on this issue still, please?

**Comment by akirahirohito** [comment]
You do not have permission to override my rights @nabobalis please

**Comment by akirahirohito** [comment]
All please adhere to COC, including administrators. Thank you.

**Comment by akirahirohito** [comment]
What is the matter with you @nabobalis?
You keep violating my rights as a member, as usual

**Comment by nabobalis** [comment]
Please take this to a private channel.

**Comment by akirahirohito** [comment]
I have already taken this to the Project Coordinators' channel, it is against COC to force someone into a private room/channel.

**Comment by akirahirohito** [comment]
@nabobalis You have just violated COC

**Comment by akirahirohito** [comment]
I have filed a complaint against you already

**Comment by akirahirohito** [comment]
Please refrain from posting on all SunPy issues and PRs for the time being, and wait until a decision has been made.

**Comment by akirahirohito** [comment]
Thank you.

**Comment by akirahirohito** [comment]
This issue will remain mine and mine only

**Comment by akirahirohito** [comment]
I have every right to assign it to anyone who ask me about it, especially while I am acting according to SunPy' COC

**Comment by akirahirohito** [comment]
https://github.com/sunpy/.github/blob/e458ad04c78084dc65c455f5fad81288ad349198/CODE_OF_CONDUCT.md
