### ISSUE TITLE
Issue with over-plotting two data sets with was axes

### ISSUE THREAD

**Issue by mm-woods** [sunpy/sunpy#4444]
Hi All! 
Apologies if this is not the right place to post this issue, but thought that this issue might be one that could effect other sunpy users and as a community you have a lot of experience with using wcs.  

I am currently trying to overlay two corresponding images (in this case an IRIS raster image and an IRIS SJI image). I have created a wcs axis for both data respectively and can plot each individually using something like the following for SJI:
```
ax = plt.subplot(projection=wcs.dropaxis(-1)) 
ax.grid(color='w', ls=':')
ax.imshow(sji.SJI['SJI_1400'].data[:, :, loc], origin='lower', vmin=-200, vmax=1000, zorder=0, aspect='auto' )
```
Output: 
<img width="432" alt="Screenshot 2020-08-27 at 10 58 57" src="https://user-images.githubusercontent.com/53914095/91472243-65bcf280-e854-11ea-8b41-642ee8c30012.png">

and for the raster:
```
ax = plt.subplot(projection=rst_wcs.dropaxis(0), slices=('y', 'x'))
ax.grid(color='w', ls=':')
ax.imshow(np.sum(sp.raster['Si IV 1403'].data,axis=2), vmin=0, vmax=10, aspect='auto')
```
Output:
<img width="413" alt="Screenshot 2020-08-27 at 10 59 09" src="https://user-images.githubusercontent.com/53914095/91472281-71101e00-e854-11ea-98f3-6db2031b0976.png">

Here the slices is required as the x and y coordinates in the IRIS raster wcs are swapped. 

I have been trying to overlay the two data in the following way:
```
rst_wcs=rst_wcs.dropaxis(0)

ax = plt.subplot(projection=wcs.dropaxis(-1))
ax.grid(color='w', ls=':')
ax.imshow(sji.SJI['SJI_1400'].data[:, :, loc], origin='lower', vmin=-200, vmax=1000, aspect='auto' )
ax.contour(np.sum(sp.raster['Si IV 1403'].data,axis=2), transform=ax.get_transform(rst_wcs.swapaxes(1, 0)), colors='white')
```
This results in the following output:
<img width="426" alt="Screenshot 2020-08-27 at 10 52 04" src="https://user-images.githubusercontent.com/53914095/91471645-97818980-e853-11ea-87fb-1872f2e1da45.png">

Which is almost correct but not quite. I suspect the issue is to do with the difference in what slices  and swapaxes do as when I plot the raster images using the swap axes method:
```
rst_wcs=rst_wcs.dropaxis(0)
ax = plt.subplot(projection=rst_wcs.swapaxes(1, 0))
ax.grid(color='w', ls=':')
ax.imshow(np.sum(sp.raster['Si IV 1403'].data,axis=2),vmin=0, vmax=10,  aspect='auto')
```
The output is similarly "off" like so:
<img width="406" alt="Screenshot 2020-08-27 at 10 58 14" src="https://user-images.githubusercontent.com/53914095/91472095-3c03cb80-e854-11ea-8809-11dda140ec8c.png">

I would be really grateful for any advice you could give, and again am sorry if this isn't the correct place to post this! 
Thanks!

**Comment by dstansby** [comment]
> Apologies if this is not the right place to post this issue

This is definitely the right place to post this!

What you're doing seems sensible, but I'm not sure what exactly is wrong - is the data from the raster offset or stretched from where you expected it to be? If the issue is swapping the WCS axes, perhaps transposing the data array instead of swapping the WCS axes will help?

**Comment by mm-woods** [comment]
Thanks for the reply David! 

So, I just realised the attached screenshots above the SJI and Raster data aren't from the same time so that explains some of the morphological differences. However, plotting the same time there is a clear offset in the x direction. 
After looking into it more I think the root of this issue is that the wcs object for the SJI images is defined at the start of the observation, and has three dimensions, x, y and time. However the positions over time don't update, so over a long observation with many rasters the reference positions on the SJI will be very different to where the really images centres are due to solar rotation. The Raster wcs objects on the other hand are defined for each raster so their reference positions update with solar rotation.  This leads to the observed x offsets that I am seeing. 
So I think my next course of action is to work out how to update the SJI wcs positions which should hopefully fix the issue. I'll also be writing up this as part of our IRIS Python analysis tutorials in ITN45 so that folk will be aware this is an issue as its not entirely obvious or intuitive at first glance... well at least it wasn't to me haha! If you think something similar could be useful for sunpy let me know and I'd be happy to help if it can!

**Comment by mm-woods** [comment]
OH additionally, Looking again at the difference between slices and swapaxes, I don't think there is an actual difference in the two images above, bar the fact that the grid lines haven't plotted in the first one which is what lead me to think they were plotting differently! Apologies for the confusion there!

**Comment by dstansby** [comment]
Fab, sounds like your issues are solved! If you think there's still a problem on the sunpy side, fell free to re-open.
