### ISSUE TITLE
SAXParseException while using VSOClient to download data

### ISSUE THREAD

**Issue by subhamoysgit** [sunpy/sunpy#4448]
### Description

**Error come from the line of code below:
qr=client.query_legacy(t_i,t_f,instrument='AIA',wave='171',sample=86400)**

**Error message:
<unknown>:12:67: XML or text declaration not at start of entity**

**Comment by nabobalis** [comment]
`query_legacy` was removed (I think) in sunpy 1.0. I would suggest replacing it with Fido.search, using this example as a basis: https://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/searching_vso.html#sphx-glr-generated-gallery-acquiring-data-searching-vso-py
