### ISSUE TITLE
Normalise images before handing them to skimage.transform.warp

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4453]
From @ayshih at https://github.com/sunpy/sunpy/pull/4452#issuecomment-686504683:

> #2041 removed the normalization code and cast everything to float64. However, I believe the removal of the normalization code should not have been done. Scikit-image's documentation is quite clear that it always assumes that floats are in the range of [0, 1]. While warp() does appear to work fine when that assumption is violated, we are currently relying on undefined behavior.

> I suggest that the normalization code be re-inserted.

I believe the work here is to normalise floating point input to `skimage.transform.warp` to the range [0, 1] in `sunpy.image.transform.affine_transform`, and then un-normalise it after the transform.

**Comment by chouhanaryan** [comment]
Hi, I'd like to take this up.
Is it as simple as just adding back the relevant normalization code that was deleted from [here](https://github.com/sunpy/sunpy/pull/2041/files#diff-9fba7e11930644e328435ce0f0ab94dfL133-L148)? I hope I'm not missing something?

**Comment by nabobalis** [comment]
Sounds like it.

**Comment by chouhanaryan** [comment]
Should I document this behavior in the `affine_transform` docstring? Even though it's an implementation detail, seems like an important one, no? 😅

**Comment by nabobalis** [comment]
It is probably worth adding a note.
