### ISSUE TITLE
Net Attrs Underlying refactor

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4484]
### Description

As we have encountered more cases with our attr registration system (such as  https://github.com/sunpy/sunpy/pull/4466), the underlying code has become more complex, slower and harder to maintain. With this in mind, I think it should be possible to refactor the underlying to be "better".

Aims:
- Less Code
- Fewer loops
- Fewer special cases

The test suite should be enough to catch any issues during the refactor.

**Comment by platipo** [comment]
Hi, I'd like to work on this issue if nobody is already doing it

**Comment by nabobalis** [comment]
No one else is working on this but this is not a straightforward task to start with.
