### ISSUE TITLE
Typo / missing functionality in TimeSeries concatenate method

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#4495]
### Description
The current method signature is `def concatenate(self, otherts, same_source=False, **kwargs):` so there is a small typo 'otherts' -> 'others' but currently the method can only take a single timeseries so should probably be 'other'. Simplest fix would be to just change 'otherts' to 'other' but I think it might be more beneficial to change to 'others' and add the missing code to handle a list/iterable of timeseries and is reference in the code comments.

### Expected vs Actual behavior
Works fine to concatenate a time series with a single other time series but doesn't work combing a list of time series.

Currently doing this type of thing quite, often where the TimeSeries are all of the same type

```python
my_timeseries = TimeSeries(listofiles)
combined_ts = my_timeseries[0]
for ts in my_timeseries[1:]:
     combined_ts = combined_ts.concatenate(bk)
```

### Steps to Reproduce
```python

```

### System Details
- SunPy Version: 2.0.1
- Astropy Version: 3.2.3
- Python Version: 3.7.0
- OS information: macOS 10.15.6

**Comment by dstansby** [comment]
I *think* the intention might have been "Other TimeSeries" > "otherts", but I can see where the confusion has come from! Not sure what our policy is on renaming arguments (ie. does it need a deprecation?), but definitely agree that we should change it.

Adding the ability to concatenate multiple TimeSeries' is a feature request, PRs welcome 😉

**Comment by chouhanaryan** [comment]
I'd like to work on this - will send in a PR soon 😃

To clarify: For now, I won't rename otherts. Based upon the type of otherts however - i.e. TimeSeries or list, I'll handle it differently, either concatenating directly or looping through the list and concatenating.

**Comment by chouhanaryan** [comment]
I've been trying to look for ways to do this and I'm unable to choose between two different approaches -
1. Simply check the type of otherts. If it is a TimeSeries object, pack it as a list and handle it as I would any other iterable (for which I'll be writing code anyway).
2. Overload the `concatenate` method using `@seconddispatch` and handle it differently depending upon the type of otherts at the expense of some code duplication.

Not sure which might be more robust. Any tips? 😅

**Comment by nabobalis** [comment]
Pick the one you prefer.

**Comment by hayesla** [comment]
I have a silly question @samaloney  - would `my_timeseries = TimeSeries(listofiles, concatenate=True)` not be the same?
