### ISSUE TITLE
Add "drawing a rectangle on a map" example

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4500]
As far as I can see there is no simple example in the gallery showing how to plot a rectangle on the map; this should have examples showing how to define the corners as pixels, and defining the corners as coordinates.

**Comment by Cadair** [comment]
:facepalm:

**Comment by chouhanaryan** [comment]
Hi, I've been working on this. I've created proper plots for `draw_rectangle(bottom_left, top_right=top_right)` and `draw_rectangle(bottom_left, width=width, height=height)`.

I'm a bit confused with plotting using pixels though. One method would be to create a submap using the pixels and then pass its `bottom_left_coord` and `top_right_coord` to `draw_rectangle`, and even though it works, it seemed a bit clunky to me so I was looking for alternatives. I saw that there is a `GenericMap.pixel_to_world(x, y origin)` method available too so technically you should be able to just do - `map.draw_rectangle(map.pixel_to_world(x, y, origin))` and that would be it, but this doesn't seem to be working as I had expected it to.

Am I on the right track?

**Comment by dstansby** [comment]
I mistakenly thought that `draw_rectangle` could take pixel input (like `submap` can), but it can't. I think an example showing what you've managed to do so far would be great 👍

**Comment by chouhanaryan** [comment]
@dstansby I've made the example but that got me thinking - wouldn't it make sense for `draw_rectangle` and `submap` to have similar interfacing? The only difference between them right now seems to be that `draw_rectangle` doesn't allow inputs to be pixels. Every other form of input is allowed for both. Maybe we could add that to it?

**Comment by kakirastern** [comment]
@chouhanaryan Apologies for the delayed response on our side... If you are still interested and trust in your own gut feelings then by all means all that to it. This will count as your official SunPy contribution still.
