### ISSUE TITLE
The gallery has no easy to read table of contents

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4501]
https://docs.sunpy.org/en/stable/generated/gallery/index.html has no easy to read table of contents, listing each of the gallery sections. Ideally I think the table of contents in the LH sidebar shouldn't have links to the specific examples, but adding a table of contents at the top would also work.

**Comment by Cadair** [comment]
I am not sure I agree with this. The point of the gallery is to be graphical, to be able to see a plot you want to make etc. The table of contents like you want is already in the side bar, putting it at the top of the index page would mean everyone has to scroll down to get to the pretty pictures.

**Comment by dstansby** [comment]
But at e.g. https://matplotlib.org/gallery/index.html, it is easy to see at a glance the different categories. My use case was going to the gallery to look at the "Plotting" related examples, but it wasn't very easy to find these without a table of contents.

**Comment by dstansby** [comment]
(and I think the sidebar table of contents is useless, as it's too verbose to actually find anything)

**Comment by wtbarnes** [comment]
Can't we just set the toc level to 1 or something like that? That way you can use the sidebar to more easily navigate to the different categories

**Comment by Cadair** [comment]
I am not 100% sure you can do that on a sub level like that in just the gallery.
