### ISSUE TITLE
LASCOMap doesn't have the correct instrument name for C3 data?

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4519]
We have a gallery example that downloads LASCO C3 files via Fido: https://docs.sunpy.org/en/latest/generated/gallery/acquiring_data/downloading_lascoC3.html

The title of the generated Map plot shows "LASCO-C2":
![sphx_glr_downloading_lascoC3_001](https://user-images.githubusercontent.com/991759/94578950-4a277c00-0246-11eb-8d75-55cb7f61c9e1.png)

We need to figure out whether we need to fix some metadata.

**Comment by Cadair** [comment]
Also that's the C2 colourmap right?

**Comment by resakra** [comment]
Could you please assign me to do this with Python for Hacktoberfest? Thanks a lot in advance

**Comment by nabobalis** [comment]
Hi @resakra, we tend to not assign anyone to issues as we always lose track of it. But since this is for Hacktoberfest fest, I think we can make an exception.

**Comment by Cadair** [comment]
Always fun to test out new workflows :grinning:

**Comment by resakra** [comment]
Thanks again Nabobalis! I appreciate it.

**Comment by wafels** [comment]
In the docs, the "2" at the start of the filenames seen from `print(downloaded_files`) indicates that the files should be LASCO C2 files.

**Comment by resakra** [comment]
@wafels You mean it should be C3 not C2 and the header should be changed?

**Comment by nabobalis** [comment]
It looks like we might have a bug in our downloader. 

For now we could change the example to be C2 data and change `detector = a.Detector.c3` to `detector = a.Detector.c2`

**Comment by resakra** [comment]
![GitHub Logo](/images/logo.png)

**Comment by resakra** [comment]
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)

**Comment by wafels** [comment]
I think there is a bug in the downloader.  I agree with @nabobalis that we should just change the docs so that acquiring and displaying a LASCO C2 image is the point of this example.  If a bug report on the download has not already been posted, I will post one.

**Comment by Cadair** [comment]
> For now we could change the example to be C2 data and change detector = a.Detector.c3 to detector = a.Detector.c2

tbh given it's broken just remove the line?

**Comment by ayshih** [comment]
Closed by #4537
