### ISSUE TITLE
get_dates() does not work when under 24hours and spans two days

### ISSUE THREAD

**Issue by RL4215** [sunpy/sunpy#4527]
### Description

When using the get_dates function spanning two days it should output both of the days that the time intervals spans. However, this function does not work when the time period is under 24 hours.
### Expected vs Actual behavior

If I have the following time interval 
starttime_correct = datetime(2020, 1, 1, 12)
endtime_correct = datetime(2020, 1, 2, 13)
then this function should output 2020/01/01 and 2020/01/02, which it does.

However, if I make this below 24 hours like so
starttime_broken = datetime(2020, 1, 1, 12)
endtime_broken = datetime(2020, 1, 2, 11)
then it only returns 2020/01/01.

### Steps to Reproduce

```python
In [2]: import sunpy.time
   ...: from datetime import datetime
   ...: #this period is above 24 hours
   ...: starttime_correct = datetime(2020, 1, 1, 12)
   ...: endtime_correct = datetime(2020, 1, 2, 13)
   ...: interval_correct = sunpy.time.TimeRange(starttime_correct, endtime_correct)
   ...: daylist_correct = interval_correct.get_dates()
   ...: 
   ...: #this period is below 24 hours
   ...: starttime_broken = datetime(2020, 1, 1, 12)
   ...: endtime_broken = datetime(2020, 1, 2, 11)
   ...: interval_broken = sunpy.time.TimeRange(starttime_broken, endtime_broken)
   ...: daylist_broken = interval_broken.get_dates()
   ...: 
   ...: print(daylist_correct)
   ...: print(daylist_broken)

[<Time object: scale='utc' format='isot' value=2020-01-01T00:00:00.000>, <Time object: scale='utc' format='isot' value=2020-01-02T00:00:00.000>]
[<Time object: scale='utc' format='isot' value=2020-01-01T00:00:00.000>]
```

### System Details

- SunPy Version: 2.0.1
- Astropy Version: 4.0.1.post1
- Python Version: 3.7.3
- OS information: Windows 10 10.0.18362 (Intel64 Family 6 Model 78 Stepping 3, GenuineIntel)

**Comment by SophieLemos** [comment]
Mind if I take this issue?

**Comment by kakirastern** [comment]
@SophieLemos Sure! We normally do not assign issues, but since it is `Hacktoberfest` 2020 we are currently making an exception. I also noticed that this issue does not come with that label. However, you are definitely more than welcome attempt it as no one has already done so.

**Comment by SophieLemos** [comment]
Thanks! I did work on solar design software so the project caught my eye. #4529

**Comment by kakirastern** [comment]
You are welcome! Someone will take a look of your PR shortly.
