### ISSUE TITLE
Latest stable release docs don't show at top of "sunpy docs" searches

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4535]
Searching for "sunpy docs" on both DuckDuckGo and google, the actual documentation landing page for the stable release does not appear (see below). Maybe there's nothing to be done, but it's worth checking that the canonical URL is set in readthedocs: https://docs.readthedocs.io/en/stable/guides/canonical.html.

![Screenshot 2020-10-02 at 11 17 40](https://user-images.githubusercontent.com/6197628/94913426-2a3fc480-04a1-11eb-9db5-636f2d1b32fd.png) ![Screenshot 2020-10-02 at 11 18 57](https://user-images.githubusercontent.com/6197628/94913436-2d3ab500-04a1-11eb-8db3-169e5f61265d.png)

**Comment by Cadair** [comment]
I don't think the canonical domain settings on RTD will help here (they are all enabled). We have even disabled a lot of these versions on the RTD project page. I am pretty much out of ideas here.

**Comment by dstansby** [comment]
https://docs.readthedocs.io/en/stable/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs - suggests setting up a custom robots.txt to stop old versions being indexed by search engines, which sounds like a good idea?

**Comment by nabobalis** [comment]
Yeah if we can make that work we should.

**Comment by Cadair** [comment]
![image](https://user-images.githubusercontent.com/1391051/94917331-409d4e80-04a8-11eb-826a-d16aa20b81ab.png)

**Comment by kakirastern** [comment]
**Quick double check**: Is it something that can be helped with the Google Search Console for setting up webpage indexing if SunPy owns the concerned URL's domain?
https://search.google.com/search-console/about

**Comment by dstansby** [comment]
Are the old versions deactivated or just hidden on readthedocs? (https://docs.readthedocs.io/en/stable/versions.html#hidden). If they're hidden but still active readthedocs should automatically add them to Disallow in `robots.txt`, but that currently isn't happening: https://sunpy.readthedocs.io/robots.txt

**Comment by Cadair** [comment]
Pretty sure we removed a bunch completely.

**Comment by Cadair** [comment]
![image](https://user-images.githubusercontent.com/1391051/94940151-03968380-04cb-11eb-8964-a1d1e91ec23c.png)

**Comment by dstansby** [comment]
Is there any way the static files could be hanging around somewhere? e.g. https://docs.sunpy.org/en/0.2.0/ still seems to be working fine.

**Comment by Cadair** [comment]
sure, I guess rtd keeps them? I have no idea.

**Comment by nabobalis** [comment]
What if we delete the entire project and start fresh?

**Comment by nabobalis** [comment]
All the versions that are inactive have public but are hidden in the edit section.

**Comment by dstansby** [comment]
I think it might just be the 0.2.0 docs that are hanging around, what is the status of that tag? Maybe could try re-activating and re-deactivating?

**Comment by nabobalis** [comment]
RTD says: "When you deactivate a version, its docs are removed."

What if I reactivate them then deactivate them?

**Comment by nabobalis** [comment]
> RTD says: "When you deactivate a version, its docs are removed."
> 
> What if I reactivate them then deactivate them?

I did just this for 0.2.0 and it didn't seem to do anything.

**Comment by dstansby** [comment]
Yes it did, https://docs.sunpy.org/en/0.2.0/ is no longer working for me

**Comment by nabobalis** [comment]
Ah I was cached.

**Comment by nabobalis** [comment]
I wonder what other versions are around, time to go fishing.

**Comment by dstansby** [comment]
The other search result that turns up is @ehsteve's fork version of the docs. @ehsteve could you deactivate all of the versions of the docs on readthedocs for your for so they don't turn up in search results?

**Comment by nabobalis** [comment]
Oh we have so many versions floating around.

**Comment by nabobalis** [comment]
I've sent an email.

**Comment by nabobalis** [comment]
Sent reply, old builds should be pruned, just need to wait for search results to update.

**Comment by nabobalis** [comment]
Do we need to do anything with the robots or are we good to close this?

**Comment by Cadair** [comment]
Can we robots to make it take stable?

**Comment by nabobalis** [comment]
Who knows.

**Comment by dstansby** [comment]
I think we did all we could to fix this? Can always re-open if is still an issue.
