### ISSUE TITLE
Rename docfix changelogs to doc

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4539]

**Comment by kots14** [comment]
Is it a task for renaming all files *docfix* under changelog directory to *doc* ?
As a beginner I'd like to start off with this. If I've understood the requirement correctly, I'd request you to assign this task to me.

**Comment by nabobalis** [comment]
Yes.

**Comment by kots14** [comment]
I've created a PR for this. Please let me know if the changes are as per your expectations or not.

**Comment by nabobalis** [comment]
Fixed by #4543
