### ISSUE TITLE
Add coordinate-system checks to maputils functions

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4546]
Lots of `sunpy/map/maputils.py` assumes that a helioprojective map is being passed. Therefore, if (e.g.) a synoptic map is passed into lots of those functions, I suspect there will be lots of unhelpful errors. We should

- Create a helper function `is_helioprojective_map` that returns `True` if a map is helioprojective, `False` otherwise
- Use this check in `maputil` functions
- Raise a user-friendly error if the check fails

**Comment by ayshih** [comment]
I changed the title of this issue to reflect its contents.  A separate issue can be created for enhancing `maputils` functions as possible to support synoptic maps.

I'll note that there are other projected coordinate systems beyond helioprojective (e.g., any equatorial-like system using RA/dec) that all `maputils` functions in principle can support.  One sticking point is that `Helioprojective` carries with it the radius of the Sun to use, and other coordinate frames do not.

**Comment by chouhanaryan** [comment]
To check if a map is helioprojective or not, is the following adequate?
```python
>>> from sunpy.coordinates import Helioprojective
>>> isinstance(map.coordinate_frame, Helioprojective)
```

**Comment by ayshih** [comment]
Yup.  One `maputils` function already has such a check:
https://github.com/sunpy/sunpy/blob/332dc4ebd91e1ae62f10253c3e7ff81c06aa04fe/sunpy/map/maputils.py#L225-L226

**Comment by chouhanaryan** [comment]
Would it be better to have the function check if the frame passed is helioprojective or not, as opposed to the map passed? As in, have the function `is_helioprojective_frame`. I'm asking because some functions require a check if the coordinates (not maps) they use are helioprojective or not. This function would then be able to handle both - frames of coordinates and maps.

**Comment by nabobalis** [comment]
What about a more generic assert function? You pass in a map/frame and the coordinate system you are after and it checks it for you and raises an error.

**Comment by chouhanaryan** [comment]
Wouldn't that force the user to pass an extra parameter/object that they're not necessarily working with directly (eg. specifying `frame='Helioprojective'/Helioprojective`)? It'd be as good as them manually checking the type using `isinstance`. I'm not too sure if that's a good thing.
In the long run, if we're supporting different types of maps then why not simply overload the function and define default behavior for when something weird is passed?
I'm an amateur when it comes to design choice so do let me know if I'm missing something.

**Comment by nabobalis** [comment]
My impression from this was that this would not be a user facing function and something to use in functions to check the frame. If this is the case, we potentially need a function for each frame or we could have one.

Overload the function?

**Comment by chouhanaryan** [comment]
Well, what I'm getting at is that if we definitely want to support all of these maputil functions for different types of maps, if we were to directly overload them, there would be no type-checking required. It wouldn't matter whether the map was synoptic or helioprojective - it would be routed to the appropriate fn. If an invalid frame was passed, the original fn would raise a TypeError. So a separate function to assert the type wouldn't be required at all.

**Comment by ayshih** [comment]
Overloading is an intriguing suggestion, but it's clearly overkill until we want to support some non-Helioprojective frames as well.  Even if we do want such support, it may still be cleaner to implement through logic branches in a single function rather than through overloading since most of the code would be redundant.

**Comment by chouhanaryan** [comment]
Right. I agree, it does seem like an overkill.

I suppose @nabobalis's suggestion works then. A more generic function would definitely be useful.
