### ISSUE TITLE
Image Resampling

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#455]
There is a paper that describes the application of image resampling methods common in computer graphics to solar physics:

De Forest, C. E., Solar Physics 219: 3–23, 2004

A general method is presented for image resampling.  One application allows for flux conservation when applying solar differential rotation.  These methods are already written in the Perl Data Language (PDL), and would be useful to have implemented in Python.  These methods would also be of use in astropy.  It may be that scikits-image already has much of what we need to implement the work of the paper above.

Abstract
Digital image data are now commonly used throughout the field of solar physics. Many steps of image data analysis, including image co-alignment, perspective reprojection of the solar surface, and compensation for solar rotation, require re-sampling original telescope image data under a distorting coordinate transformation. The most common image re-sampling methods introduce sig- nificant, unnecessary flaws into the data. More correct techniques have been known in the computer graphics community for some time but remain little known within the solar community and hence deserve further presentation. Furthermore, image distortion under specialized coordinate transform- ations is a powerful analysis technique with applications well beyond image resizing and perspective compensation. Here I give a brief overview of the mathematics of data re-sampling under arbitrary distortions, present a simple algorithm for optimized re-sampling, give some examples of distortion as an analysis tool, and introduce scientific image distortion software that is freely available over the Internet.

**Comment by Cadair** [comment]
is this: astrofrog/reproject#52

**Comment by Cadair** [comment]
This belongs in reproject.
