### ISSUE TITLE
Write a checklist for doing a feature freeze

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4571]
probably addenda to the release checklist

**Comment by Cadair** [comment]
Add milestone bot config on backport branch

**Comment by Cadair** [comment]
* Update extern
* Update zenodo / mailmap

**Comment by Cadair** [comment]
Also updating the VSO and JSOC net attrs. @nabobalis do we have a script for this?

**Comment by nabobalis** [comment]
> Also updating the VSO and JSOC net attrs. @nabobalis do we have a script for this?

I think the functions I wrote to update those files are in the clients. I would need to double check.

**Comment by kakirastern** [comment]
Sure

**Comment by SnehVachhani** [comment]
hello , 
i want to help. plzzz navigate me

**Comment by dstansby** [comment]
Thanks for the interest! Since @Cadair is already assigned to this issue, it's already being taken care of. If you're interested in other issues, the Good first issue tag is probably a good start: https://github.com/sunpy/sunpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22

**Comment by nabobalis** [comment]
Written here: https://demo.hedgedoc.org/s/TzNppNRmU

**Comment by Cadair** [comment]
Done: https://github.com/sunpy/sunpy/wiki/Home%3A-Feature-Freeze-Checklist
