### ISSUE TITLE
Using sunpy.map shouldn't require remote access libraries (e.g. aiohttp)

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4575]
I am trying to create a frozen and minimal python environment for some code I run daily to output synoptic maps and magnetic connection predictions. Installing dependencies is fine - I can just use `pip install --no-deps` to ignore sunpy's (extensive) list of dependencies that I don't actually need.

Doing `import sunpy.map` however reveals a dependency on `aiohttp` that I don't really want to have to install however. I am wondering if there is a way to remove this runtime dependency?
```python
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    import pfsspy
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/pfsspy/__init__.py", line 13, in <module>
    import sunpy.map
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/map/__init__.py", line 8, in <module>
    from sunpy.map import sources
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/map/sources/__init__.py", line 12, in <module>
    from ..map_factory import Map
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/map/map_factory.py", line 14, in <module>
    from sunpy.data import cache
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/data/__init__.py", line 5, in <module>
    from sunpy.data._sample import download_sample_data
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/data/_sample.py", line 7, in <module>
    from sunpy.util.parfive_helpers import Downloader
  File "/Users/dstansby/miniconda3/envs/connection/lib/python3.8/site-packages/sunpy/util/parfive_helpers.py", line 4, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by nabobalis** [comment]
Shouldn't that have been installed by parfive?

**Comment by dstansby** [comment]
Yeah, `--no-deps` stops that. I basically want to be able to use `sunpy.map.Map` in a minimal install, without any networking packages required at runtime.

**Comment by nabobalis** [comment]
Making `from sunpy.data import cache` not trigger the sample data should the angle here, someone will have to work out that init path and change it.

**Comment by nabobalis** [comment]
I think this counts as a bug.

**Comment by Cadair** [comment]
That import path is bad, how did that make it through our offline test suite??

**Comment by nabobalis** [comment]
> That import path is bad, how did that make it through our offline test suite??

That is a good question. How does it?

**Comment by Cadair** [comment]
There is an argument to be made for stripping the parfive stuff from the sample download so we can move parfive to just being a net dependency.

**Comment by Cadair** [comment]
I think this issue really boils down to why is [this](https://github.com/sunpy/sunpy/blob/master/sunpy/data/__init__.py#L5) import here?

**Comment by nabobalis** [comment]
For the all underneath?

**Comment by Cadair** [comment]
I used parfive initially to speed up the download but it is a reasonably large tree of deps.

**Comment by nabobalis** [comment]
Should we work at removing parfive as a core dep and move it to net?

**Comment by Cadair** [comment]
:man_shrugging:

**Comment by chouhanaryan** [comment]
> Making `from sunpy.data import cache` not trigger the sample data should the angle here, someone will have to work out that init path and change it.

@nabobalis I've been trying to solve this. Let me see if I've got this right - `cache` and `download_sample_data` are initialized in the same [`__init__`](https://github.com/sunpy/sunpy/blob/master/sunpy/data/__init__.py), so when cache is imported for Map, invariably, the other gets imported too.

I'm sorry I didn't get what you mean by figuring out the init path.. Could you please elaborate 😅

**Comment by nabobalis** [comment]
Yes that's correct. We now what is happening and have to change it to prevent the sample data import for map.

**Comment by chouhanaryan** [comment]
I think the problem might be a bit more deep-rooted. The issue is actually with `sunpy.util.parfive_helpers.Downloader`. That is what causes the `aiohttp` import. And if we follow the `sunpy.map` import, it is imported twice - via `download_sample_data` and the `ParfiveDownloader` (the tree below shows exactly where).

With respect to `download_sample_data` since it technically doesn't have any initialization code, it could maybe be removed from `__init__`? It is part of the public API but removing it from the file doesn't cause any import problems in our package, for sure. Only if someone has used `from sunpy.data import *` to import `download_sample_data` would it raise an error.

As for the `ParfiveDownloader`, I'm not sure what, if anything can be done about it. Initializing `manager` and `cache`, both,  require an object of it. Maybe moving both of them out of there into independent modules might work? But again, that tampers with the public API.

- [map/map_factory](https://github.com/sunpy/sunpy/blob/master/sunpy/map/map_factory.py#L14) - from sunpy.data import cache
    - [data/\_\_init__](https://github.com/sunpy/sunpy/blob/master/sunpy/data/__init__.py#L5) - from sunpy.data.sample import download_sample_data
        - [data/_sample](https://github.com/sunpy/sunpy/blob/master/sunpy/data/_sample.py#L7) - __from sunpy.util.parfive_helpers import Downloader__
    - [data/\_\_init__](https://github.com/sunpy/sunpy/blob/master/sunpy/data/__init__.py#L7) - from sunpy.data.data_manager.downloader import ParfiveDownloader
        - [data/data_manager/downloader](https://github.com/sunpy/sunpy/blob/master/sunpy/data/data_manager/downloader.py#L4) - __from sunpy.util.parfive_helpers import Downloader__

**Comment by Cadair** [comment]
ah yeah... maybe it's not actually possible to do this. The map factory supports downloading remote URLs, which uses the cache, which uses parfive...

**Comment by chouhanaryan** [comment]
What if we add a try-catch for the import? If map is imported and aiohttp isn't installed, a warning could be shown but the execution could be allowed to proceed nonetheless. This seems quite hacky though..

**Comment by dstansby** [comment]
Could we move one or two imports inside methods instead of at the top of some of the files in `sunpy/map`? If my request isn't that easy to fix then no worries, it's not an massive issue.

**Comment by dstansby** [comment]
Turned out I needed remote access things for other bits of my environment anyway, so will close this as won't-fix, sorry for the noise.

**Comment by Cadair** [comment]
@dstansby yeah we could probably refactor the factory to import error on trying to open a URL.
