### ISSUE TITLE
Changes to make when we depend on Astropy 4.1

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4576]
This is a list of things which we can change once we depend on Astropy 4.1+. This is a follow on from #4000

TODO

**Comment by nabobalis** [comment]
Do we plan to bump it to 4.1 for 3.0?

**Comment by ayshih** [comment]
With Astropy 4.1 being so delayed, perhaps not.  See also #3918

**Comment by nabobalis** [comment]
We never came up with anything.

**Comment by nabobalis** [comment]
I guess a new issue with ideas for the next time we bumpy astropy.

**Comment by ayshih** [comment]
Created #5291
