### ISSUE TITLE
Unexpected SunPy-rendered RHESSI colormaps

### ISSUE THREAD

**Issue by Laubeee** [sunpy/sunpy#4606]
### Description
The colormap "rhessi" as in [SunPy visualization](https://docs.sunpy.org/en/latest/code_ref/visualization.html) (blue-green-red) which appears to be the standard [matplotlib-jet colormap](https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html), is not the same as the "official" mission colormaps, when compare with the ones used on [hesperia](https://hesperia.gsfc.nasa.gov/rhessi_extras/flare_images/2002/07/05/20020705_0801_0815/CLEAN/movies/hsi_image_20020705_080420_6_12kev_contours_12_25kev.jpeg) (black, blue, purple, red, orange, green/yellow, white).

### Expected vs Actual behavior
Being able to plot the map with the expected mission colormap.

### Steps to Reproduce
```python
from sunpy.io.fits import read
from sunpy.time import parse_time
from sunpy.map import Map

url = "https://hesperia.gsfc.nasa.gov/rhessi_extras/imagecube_fits/2002/07/05/20020705_0801_0815/hsi_imagecube_clean_20020705_0801_14tx2e.fits"
f = read(url)
m = Map(f[0].data[0][0], f[0].header)
m.plot_settings['cmap'] = 'rhessi'
m.plot()
```

### System Details
- SunPy Version: 2.0
- Astropy Version: 4.0
- Python Version: 3.7.3
- OS information: Win10

**Comment by hayesla** [comment]
I dont know if RHESSI has a 'mission' colormap per say (maybe @ayshih can comment) - RHESSI map plotted in the archive  are usually plotted with `loadct 5` in IDL from here (https://www.harrisgeospatial.com/docs/LoadingDefaultColorTables.html) which is "STD GAMMA-II". 

If you wanted something close - maybe `cmap=plt.cm.CMRmap`?

**Comment by ayshih** [comment]
RHESSI *does* have a "mission" colormap; for example, it's what's used for the [quicklook images in the RHESSI Browser](http://sprg.ssl.berkeley.edu/~tohban/browser/?show=qli02&date=20020705&time=080112).  However, the HESSI color table is actually a little more difficult to load than it used to be.  This [binary file for `loadct`](https://hesperia.gsfc.nasa.gov/ssw/hessi/dbase/colors_hessi.tbl) contains it as table 41.  The HESSI color table is intended for a range that is symmetric about zero (i.e., black is at the middle of the range), whereas STD GAMMA-II is better for a range that is (mostly) all positive (i.e., black is at the start of the range).  Here's a comparison:

### HESSI color table
![hsi_qlimg_2070502_006012](https://user-images.githubusercontent.com/991759/97354204-6e896f00-186b-11eb-82f3-b8b923621f7b.png)

### STD GAMMA-II color table
![hsi_image_20020705_080420_6_12kev_contours_12_25kev](https://user-images.githubusercontent.com/991759/97354190-6af5e800-186b-11eb-8005-1b6c30107953.jpeg)

That said, `matplotlib-jet` doesn't match either of these.  It looks like @ehsteve picked that colormap in https://github.com/sunpy/sunpy/commit/07f203a9ad822dbfbb28c49003bc4003427d149a (part of #22) for SunPy 0.2, and it hasn't been given further consideration since 2011.

**Comment by kakirastern** [comment]
Is anyone working on this issue? If not I would like to take this up...

**Comment by nabobalis** [comment]
No one is working on this that am I aware of.

**Comment by kakirastern** [comment]
Let me take this issue up then. Thanks @nabobalis!

**Comment by kakirastern** [comment]
Yeah, a `blue-green-red` color scheme would not be so accessible to someone with color blindness or visual accessibility issues.

**Comment by kakirastern** [comment]
Just checked out `cmap=plt.cm.CMRma` plus other potential alternatives... Seems quite reasonable to switch over to this colormap in order to approximate the RHESSI "mission" colormap better.

**Comment by kakirastern** [comment]
@Laubeee 

**Steps to better approximate the cmap for the official RHESSI map**

from sunpy.io.fits import read
from sunpy.time import parse_time
from sunpy.map import Map

url = "https://hesperia.gsfc.nasa.gov/rhessi_extras/imagecube_fits/2002/07/05/20020705_0801_0815/hsi_imagecube_clean_20020705_0801_14tx2e.fits"
f = read(url)
m = Map(f[0].data[0][0], f[0].header)
m.plot_settings['cmap'] = 'CMRmap'
m.plot()

**Comment by kakirastern** [comment]
Am example output would be as follows:

<img width="223" alt="Screenshot 2020-11-19 at 1 56 33 AM" src="https://user-images.githubusercontent.com/26264600/99568671-aa4acb00-2a0a-11eb-946d-9c09d64bc8ec.png">

**Comment by Laubeee** [comment]
Hi @kakirastern 
Thanks for taking this up
if you like I can send you the exact 255 RGB values of above mentioned color maps, by exporting them from IDL

**Comment by kakirastern** [comment]
Sure @Laubeee 
I can take a look from there. My email address is krisastern@gmail.com...

**Comment by kakirastern** [comment]
Let me see if I can use opencv to process the IDL colormap, and engineer something useful with the color mappings you have provided to suit your purposes. Like the following: https://www.learnopencv.com/applycolormap-for-pseudocoloring-in-opencv-c-python/

**Comment by kakirastern** [comment]
Most notably this outlines my overarching scheme:

> Define a colormap : A colormap is a mapping from 0-255 values to 256 colors. In OpenCV, we need to create an 8-bit color image of size 256 x 1 to store the 256 color values.

**Comment by Laubeee** [comment]
Is it not possible to define colormaps directly in matplotlib? I would be surprised we need openCV for that..?
Anyway, this is not the first custom color map in sunpy (see link to docs in original post), so maybe someone from SunPy can point you to the place where the other custom maps are defined?

**Comment by kakirastern** [comment]
I am from SunPy

**Comment by kakirastern** [comment]
Actually to the best of my belief I have already answered your question. I.e., use `CMRmap` for the colormap.

**Comment by kakirastern** [comment]
But if you would like 100% fidelity then `opencv` could be a way to go. `Matplotlib` does not process colormaps like that for our setup.

**Comment by nabobalis** [comment]
IF we can load up the IDL color table, we should be able to define it manually with array values and add it to our supported list.

**Comment by kakirastern** [comment]
Yes, we could do that too. But I don't have IDL...

**Comment by kakirastern** [comment]
And generally we tend to discourage use of IDL. Our existence depends on its replacement.

**Comment by nabobalis** [comment]
Sure but Laubeee said they can do that for us. We also define custom color tables in CSV files here: https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data

**Comment by kakirastern** [comment]
Wait let me check it out now...

**Comment by kakirastern** [comment]
Okay, so will need to fill the RGB channels with the following provided by @Laubeee, looking like manually:

```
STD GAMMA-II
IDL>R
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 4 9 14 19 23 28 33 38 42 47 52 57 61 66 71 76 81 81 81 81 81 81 81 81 80 80 80 80 80 80 80 79 84 89 94 99 104 109
114 119 124 129 134 139 144 149 154 159 164 169 174 180 185 190 196 201 206 212 217 222 228 233 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 248 240 232 225 217 209 202 194 186
179 171 163 168 173 178 183 188 193 198 203 209 214 219 224 229 234 239 244 249 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
IDL> G
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 10 16 21 27 32 37 43 48 54 59 64 70 75 81
85 90 95 100 105 109 114 119 124 129 134 138 143 148 153 158 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163 163
163 163 163 163 163 169 175 181 187 193 199 205 212 218 224 230 236 242 248 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
IDL> B
0 5 10 15 20 26 31 36 41 46 52 57 62 67 72 78 83 88 93 98 104 109 114 119 124 130 135 140 145 150 156 161 166 171 176 182 187 192 197 202 208 213 218
223 228 234 239 244 249 255 250 245 239 234 228 223 218 212 207 201 196 190 185 180 174 169 163 158 152 147 142 136 131 125 120 114 109 104 98 93 87 82 76 71 66 60
55 49 44 38 33 28 22 17 11 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
4 9 14 19 24 28 33 38 43 48 53 57 62 67 72 77 82 77 71 65 59 53 47 41 36 30 24 18 12 6 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 3 6 9 12 16 19 22 25 29 32 35 38 41 45 48 51 54 58 61 64 67 71 74 77 80 83 87 90 93 96 100 103 106 109 112 116 119 122
125 129 132 135 138 142 145 148 151 154 158 161 164 167 171 174 177 180 183 187 190 193 196 200 203 206 209 213 216 219 222 225 229 232 235 238 242 245 248 251 255


The HESSI color table

IDL> R
127 129 131 132 134 136 138 139 141 143 145 146 148 150 152 153 155 157 159 160 162 164 166 167 169 171 173 174 176 178 180 181 183 185 187 188 190 192 194 195 197 199 201
202 204 206 208 209 211 213 215 216 218 220 222 223 225 227 229 230 232 234 236 237 239 241 243 244 246 248 250 251 253 253 253 253 253 253 253 253 253 253 254 254 254 254
254 254 254 254 254 254 254 254 254 254 254 254 254 254 255 255 255 255 255 255 255 255 255 255 249 244 238 233 227 222 216 211 205 200 194 189 183 178 172 167 161 156 150
144 139 133 128 122 117 111 106 100 95 89 84 78 73 67 62 56 61 66 71 76 81 86 91 96 101 106 111 116 121 126 131 136 141 146 150 155 160 165 170 175 180 185
190 195 200 205 210 215 220 225 230 235 240 239 237 236 235 233 232 230 229 228 226 225 224 222 221 220 218 217 216 214 213 211 210 209 207 206 205 203 202 201 199 198 196
195 194 192 191 189 186 184 181 179 177 174 172 169 167 165 162 160 157 155 153 150 148 145 143 140 138 136 133 131 128 126 124 121 119 116 114 112 109 107 104 102
IDL> G
201 200 200 199 198 197 197 196 195 194 194 193 192 191 191 190 189 188 188 187 186 185 185 184 183 182 182 181 180 179 179 178 177 176 176 175 174 175 175 176 176 177 177
178 178 179 179 180 180 181 181 182 182 183 183 184 184 185 185 186 186 187 187 188 188 189 189 190 190 191 191 192 192 194 195 197 199 201 202 204 206 207 209 211 212 214
216 218 219 221 223 224 226 228 229 231 233 235 236 238 240 241 243 245 246 248 250 252 253 255 251 247 243 239 235 231 226 222 218 214 210 206 202 198 194 190 186 182 177
173 169 165 161 157 153 149 145 141 137 133 128 124 120 116 112 108 105 102 99 97 94 91 88 85 82 79 76 74 71 68 65 62 59 56 54 51 48 45 42 39 36 34
31 28 25 22 19 16 13 11 8 5 2 4 7 9 12 14 17 19 22 24 27 29 32 34 37 39 42 44 47 49 51 54 56 59 61 64 66 69 71 74 76 79 81
84 86 89 91 91 92 92 92 92 93 93 93 94 94 94 95 95 95 95 96 96 96 97 97 97 98 98 98 98 99 99 99 100 100 100 101 101 101 101 102 102
IDL> B
127 129 132 134 136 139 141 144 146 148 151 153 155 158 160 162 165 167 170 172 174 177 179 181 184 186 188 191 193 195 198 200 203 205 207 210 212 210 208 206 203 201 199
197 195 193 190 188 186 184 182 180 177 175 173 171 169 167 164 162 160 158 156 154 151 149 147 145 143 141 138 136 134 135 135 136 136 137 137 138 138 139 139 140 140 141
141 142 142 143 143 144 144 145 145 146 146 147 147 148 148 149 149 150 150 151 151 152 152 153 154 154 155 156 156 157 157 158 159 159 160 161 161 162 163 163 164 165 165
166 166 167 168 168 169 170 170 171 172 172 173 173 174 175 175 176 175 173 172 171 169 168 167 165 164 163 161 160 159 157 156 155 153 152 151 150 148 147 146 144 143 142
140 139 138 136 135 134 132 131 130 128 127 124 121 118 115 113 110 107 104 101 98 95 92 89 87 84 81 78 75 72 69 66 63 61 58 55 52 49 46 43 40 37 35
32 29 26 23 25 27 29 32 34 36 38 40 42 44 46 49 51 53 55 57 59 61 64 66 68 70 72 74 76 79 81 83 85 87 89 91 93 96 98 100 102
```

**Comment by kakirastern** [comment]
Will take me awhile but will get there. (Like my PhD manual tasks 😅)

**Comment by kakirastern** [comment]
> Sure but Laubeee said they can do that for us. We also define custom color tables in CSV files here: https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data

Thanks @nabobalis for pointing these out... Let me figure out which channel is which next.

**Comment by Laubeee** [comment]
> Will take me awhile but will get there. (Like my PhD manual tasks 😅)

Sounds like you're about to manually copy all these values... a program/script could also read them and print/write them as CSV ;)

> Sure but Laubeee said they can do that for us. We also define custom color tables in CSV files here: https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data

that is exactly what I meant with "someone pointing to the right place " ;-)

**Comment by kakirastern** [comment]
@Laubeee Please adhere to our Code of Conduct (CoC) and mind your slighting and use of language here. Also, please submit a `.CSV` version of your output so that I can just copy and paste these data to the right place. Otherwise feel free to submit a PR yourself. This is pretty low level stuff that you should be able to do yourself without asking so many inane questions. Thank you!

**Comment by kakirastern** [comment]
Your sending a plain text file does me no service at all. For `Matplotlib` colormaps please use whatever you prefer. This is not a bug per se apparently, and is wasting us preciously volunteering time. Once again. Thank you!

**Comment by kakirastern** [comment]
Note: `Not a bug`

**Comment by kakirastern** [comment]
Also @Laubeee Sounds like from your choice of language your habit of blaming other people for your mistakes. Once again this is open-source. Instead of asking someone else to check or add new features please consider doing these yourself by becoming a contributor.

**Comment by kakirastern** [comment]
I am no longer interested in this issue or think this warrants our time and efforts. Maybe someone else can take over when they have the time to waste.

**Comment by kakirastern** [comment]
> @Laubeee
> 
> **Steps to better approximate the cmap for the official RHESSI map**
> 
> from sunpy.io.fits import read
> from sunpy.time import parse_time
> from sunpy.map import Map
> 
> url = "https://hesperia.gsfc.nasa.gov/rhessi_extras/imagecube_fits/2002/07/05/20020705_0801_0815/hsi_imagecube_clean_20020705_0801_14tx2e.fits"
> f = read(url)
> m = Map(f[0].data[0][0], f[0].header)
> m.plot_settings['cmap'] = 'CMRmap'
> m.plot()

Solution already provided here, hence issue closed.

**Comment by nabobalis** [comment]
> > Will take me awhile but will get there. (Like my PhD manual tasks 😅)
> 
> Sounds like you're about to manually copy all these values... a program/script could also read them and print/write them as CSV ;)
> 
> > Sure but Laubeee said they can do that for us. We also define custom color tables in CSV files here: [https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data](https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data?rgh-link-date=2020-11-20T14%3A02%3A24Z)
> 
> that is exactly what I meant with "someone pointing to the right place " ;-)

If you could create and upload the CSV file for us, that would be very helpful. I don't have access to IDL anymore.

**Comment by kakirastern** [comment]
> > > Will take me awhile but will get there. (Like my PhD manual tasks 😅)
> > 
> > 
> > Sounds like you're about to manually copy all these values... a program/script could also read them and print/write them as CSV ;)
> > > Sure but Laubeee said they can do that for us. We also define custom color tables in CSV files here: [https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data](https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data?rgh-link-date=2020-11-20T14%3A02%3A24Z)
> > 
> > 
> > that is exactly what I meant with "someone pointing to the right place " ;-)
> 
> If you could create and upload the CSV file for us, that would be very helpful. I don't have access to IDL anymore.

This is exactly what I meant by having to do manual tasks for this issue. 😅

**Comment by kakirastern** [comment]
Your IDL is already the `program/script` to convert your data into `.CSV` format. Most of us here at SunPy don't use IDL anymore.

**Comment by kakirastern** [comment]
I will let you take over this issue @nabobalis Thanks!

**Comment by Laubeee** [comment]
I have access to IDL, but its tedious and I'm hardly familiar with it. I was thinking about something like
```python
R = np.array([ (paste R values here) ])
G, B = ...
for i in range(len(R)):
    print(",".join([R[i],G[i],B[i]]))
```
which I did now that it's clear its needed in CSV: [colortables.zip](https://github.com/sunpy/sunpy/files/5574363/colortables.zip)  I added HESSI-bw as well since I was at it anyway. Sorry I stepped on your toe there.

@nabobalis is it ok if you take it from here? Or could you point me to the place where the csv's are loaded, then I can make a PR directly.

**Comment by dstansby** [comment]
The colormap .csv files are stored in `sunpy/vizualisation/colormaps/data`, and the code for reading them in is in `sunpy/vizualisation/colormaps/color_tables.py`. Hopefully it should be easy to copy and modify a pre-exisitng function, but let me know if you need any other pointers.

**Comment by nabobalis** [comment]
Thanks @Laubeee, I am happy to take this on if you prefer. 

Otherwise, while the files are stored here: https://github.com/sunpy/sunpy/tree/master/sunpy/visualization/colormaps/data

The actual loading and parsing happens here:
https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/colormaps/color_tables.py
You would copy one of the existing functions and modify to load the file and return a table.

Finally, we have the final definition here: https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/colormaps/cm.py 
I am not sure this is needed for RHESSI.

**Comment by Laubeee** [comment]
thanks both

I suggest to use the names Albert used, resp. [GSFC uses](https://hesperia.gsfc.nasa.gov/ssw/hessi/doc/gui/gui_help.htm), so I suggest `std_gamma_II`, `hessi` and `hessi_black_white` (if the last one even makes sense to include? I don't think it's really used in practice..)

I have no "hard" preference. You could take this one here, then I can focus on opening another PR I wanted to open for some time in sunkit-instruments :)

**Comment by hayesla** [comment]
Thanks for raising this issue @Laubeee! :) 

I'd say the `hessi` one is the best - I have a draft of this @nabobalis  if you want me to make the PR?

**Comment by nabobalis** [comment]
> Thanks for raising this issue @Laubeee! :)
> 
> I'd say the `hessi` one is the best - I have a draft of this @nabobalis if you want me to make the PR?

Go right ahead.

**Comment by Laubeee** [comment]
@hayesla In my case I'd be happy to be able to use the STD GAMMA-II as well, but HESSI could be assigned as default colormap for the RHESSIMap?

**Comment by hayesla** [comment]
I've made the PR @Laubeee  if you want to have a look over it #4665
