### ISSUE TITLE
Data access model for TimeSeries: data versus to_dataframe(). Why?

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4622]
In the [`TimeSeries` docs](https://docs.sunpy.org/en/latest/guide/data_types/timeseries.html), we tell people to access the columns of a TS using `.data` and the appropriate key name (like a `dict`). When you actually do this, you get a fun warning,

```python-traceback
WARNING: SunpyUserWarning: Using .data to access the dataframe is discouraged; use .to_dataframe() instead. [sunpy.timeseries.timeseriesbase]
```

This is obviously contradictory. Additionally, I find the use of `to_dataframe()` quite cumbersome. Or really even `.data`. I guess this sort of follows from the `Map` model, but I feel that TS, unlike `Map`, is inherently multi-dimensional and so it would be useful to be able to access these multiple dimensions as attributes directly on the TS object (even if they are just aliases to the underlying columns on `data`).

If we do actually want to discourage this, I think we should put a deprecation warning on it and remove it after the appropriate period. If we have no plans to remove it, I think we should remove the existing warning.

I suppose the larger question is: **why are we even bothering with providing a separate data type if we are telling users they need to cast it to a whole other data type (a `pandas.DataFrame`) in order to pull data out of it???** I recognize that TS is primarily useful as a factory and for pulling and combining files into a single data structure, including the metadata handling.

#3954 is also likely relevant here.

I fully realize this is sort of an open-ended rant and I don't mean to be overly critical. I'm not a frequent-user of TS so maybe I'm missing something here.

**Comment by Cadair** [comment]
The main reason to encourage the use of `to_dataframe` was to insulate users against possible changes of type for `.data`.

Direct access to columns or similar sounds like a potentially good idea.

**Comment by dstansby** [comment]
I am going to put it out there that `TimeSeries` using a `DataFrame` to store the data underneath is past the point of no return.

As long as one is not modifying columns, performing operations (e.g. rebinning, detrending etc.) on the underlying dataframe and modifying it in place is a powerful way to leverage `pandas`, and is something I personally do all the time. This was implicitly supported before using `.data` raised a warning, and I see no way that we can maintain this in a backwards compatible way if we were to migrate away from using a `dataframe` underneath. Beyond myself, anyone who uses `heliopy` uses `TimeSeries`, and a large percentage of people I know who use it via. heliopy also take advantage of being able to modify the data in place via. pandas. So I think the "should we support this?" ship sailed long ago, and there's not really a nice way to undo that support unless we migrate to another container that has as good or better timeseries functionality as pandas.

As a corollary of the above, I would support removing this warning until there are concrete plans to replace the use of pandas as a container format.

**Comment by dstansby** [comment]
Since we've decided to switch to `astropy` `TimeSeries` I think this issue can be closed. I think
> why are we even bothering with providing a separate data type if we are telling users they need to cast it to a whole other data type (a pandas.DataFrame) in order to pull data out of it???

is a really good point, but deserves a new issue ("make sure we're not using `to_dataframe()` or `.data` in the docs") if it's an issue anywhere.
