### ISSUE TITLE
Add what's new doc for 2.1

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4626]
Ideas for it:

1. Metadata fido work
2. Map data now has units
3. Can now easily get contours from maps
4. New synoptic map sources and clients
5. Coordinates have velocities
6. New GOES data
7. Various performance improvements (maputils + caching .wcs)

Put yours in the comment section below and smash that like and subscribe button.

**Comment by Cadair** [comment]
Maybe new Fido client writing functionality and docs? Do we want to add stuff for package developers to our whatsnew?

**Comment by dstansby** [comment]
Don't see why not, maybe at the bottom?
