### ISSUE TITLE
CompositeMap should use properties not getter / setter

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#463]
Python properties might be able to replace all the getter / setter methods in CompositeMap. I think, maybe.

**Comment by dstansby** [comment]
I forget what the plan is for CompositeMap, and this would be a lot of deprecations and API changes. Do we still want to do this?

**Comment by Cadair** [comment]
I think it's likely this would be part of a larger refactoring of CompositeMap now, probably folding in NDCollection and a bunch of other stuff. Not sure if this is worth keeping open in light of that as long as we have issues tracking the bigger picture.
