### ISSUE TITLE
Update Helio Code to expect str not bytes

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4631]
Astropy 4.1 changed the output of [`parse_single_table`](https://keflavich-astropy.readthedocs.io/en/latest/api/astropy.io.votable.parse_single_table.html#astropy.io.votable.parse_single_table) to return `str` not `bytes`. https://github.com/sunpy/sunpy/pull/4628 modified our code to convert it back to bytes, but this was a short term solution for the 2.0 branch, we should be forwards-compatible and change the code to always expect `str` and decode the bytes to str after the function call (and then be able to remove that code when we depend on astropy > 4.1.

**Comment by kakirastern** [comment]
Is anyone working on this? Would like to try...

**Comment by nabobalis** [comment]
No but I was planning to do this tomorrow.

**Comment by kakirastern** [comment]
No worries, I will try to find another issue then. Any recommendations?

**Comment by nabobalis** [comment]
No I try not to recommend issues to people. Nicer if they find something they would enjoy to take on.

**Comment by kakirastern** [comment]
Sure, think I might have found one...
