### ISSUE TITLE
Add Map support for Quadrangle

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4657]
Currently, the `Map` method `draw_rectangle()` can be used to overlay rectangles, which internally uses `matplotlib.patches.Rectangle`.  `astropy.visualization.wcsaxes.Quadrangle` is better for nearly all situations because it will contort with transformations, but it is only available starting with Astropy 4.2 (when released).  Possible approaches to adding support for `Quadrangle`:

- Add a `draw_quadrangle()` method.  If the user's Astropy version is <4.2, it can raise an error, or it can raise a warning and fallback to `draw_rectangle()`.
- Switch the internals of `draw_rectangle()` to use `Quadrangle` if its available.
- Defer any action until our minimum Astropy dependency is 4.2, which would nominally be in a year with the release of SunPy 3.1.
- Defer any action since there are mixed opinions on having the `draw_*` methods where they currently live in the API.

**Comment by jeffreypaul15** [comment]
Is this issue still open to work on? I've got a history of choosing wrong issues to work on so just checking beforehand xD

**Comment by nabobalis** [comment]
> Is this issue still open to work on? I've got a history of choosing wrong issues to work on so just checking beforehand xD

This issue is open to work on but only do so if you understand what the issue is asking for. This is not labeled as a good first issue for new people.

**Comment by jeffreypaul15** [comment]
Alright, so add another draw_quardrangle method which would replace draw_rectangle with all functionality, raise a warning amd fall back to draw_rectangle if the user's astropy version is < 4.2. Correct me if I'm wrong

**Comment by nabobalis** [comment]
> Alright, so add another draw_quardrangle method which would replace draw_rectangle with all functionality, raise a warning and fall back to draw_rectangle if the user's astropy version is < 4.2. Correct me if I'm wrong

Sounds correct.

**Comment by jeffreypaul15** [comment]
Alright, I'll begin working on this and open a PR soon

**Comment by jeffreypaul15** [comment]
by making a new method, `draw_quadrangle` the initial setup of the coordinates are the same as `draw_rectangle` so I was wondering if replacing the method completely and handling the situation where astropy < 4.2 is taken care of in the method was a good idea?
Or do they have to be separate methods because a few lines of code is repeated using Quadrangle from astropy.

**Comment by nabobalis** [comment]
We can't change the API between releases without prior warnings. I would create the new method and then on the PR we can discuss if we want to replace draw_rectange with it.

**Comment by jeffreypaul15** [comment]
Makes sense, I'll open PR with a separate method.

**Comment by Cadair** [comment]
I assume that a Quadrangle looks suspiciously like a rectangle for most HPC based maps? Assuming that is true I think that we should deprecate draw_rectangle for the first version we expect to be astropy 4.2+

**Comment by ayshih** [comment]
The only argument that I can think of for keeping `draw_rectangle()` around is that it might be nice to have a function that draws the rectangle-in-pixel-space region that would be returned by a `submap()` call with the same arguments.

**Comment by Cadair** [comment]
Do we accept pixel space arguments to draw_rectangle at the moment?

**Comment by ayshih** [comment]
What I mean is that `submap()` has to return a rectangle in pixel space, even with coordinate arguments.  It could be convenient to be able to visually plot that same rectangle with the same coordinate arguments.

**Comment by Cadair** [comment]
we could have a kwarg `quadrangle=True` or something?
