### ISSUE TITLE
Examples required of downloading GOES data

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4660]
### Description

Now that the new Fido GenericClient now returns all available data we should show an example of how to search by satellite number or index the query result. This may just mean updating this example https://docs.sunpy.org/en/stable/generated/gallery/time_series/goes_hek_m25.html. This example only works because there is actually only one file available for this day, but this example would break on days where multiple files were returned in teh query (e.g. GOES 13 and 15 returned). 

I'm thinking of writing an example that goes over the GOES data and explains the differences of the re-processed GOES data.

**Comment by nabobalis** [comment]
I've milestoned this for 2.1 but maybe that's a bit aggressive.

**Comment by hayesla** [comment]
> I've milestoned this for 2.1 but maybe that's a bit aggressive.

I'll try get it done by this weekend - already have a draft
