### ISSUE TITLE
Rename our `master` branch?

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4667]
`master` is no longer the recommended name for a repo's default branch due to offensive connotations.  See the [announcement from Git](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and the [README on GitHub](https://github.com/github/renaming/blob/main/README.md).  

We should discuss whether to rename `master`.  I realize that it will be a pain to make the switch, but that doesn't mean we shouldn't do it.  It should be less of a pain "later this year" when GitHub adds renaming functionality, but we'd still have to update documentation, of course.

For my fork, I have already renamed my default branch to `main` ([here are some instructions](https://dev.to/rhymu8354/git-renaming-the-master-branch-137b)).

**Comment by nabobalis** [comment]
Should we wait till support is added to GitHub? Seems like the easiest solution for now.

**Comment by Cadair** [comment]
I think it's worth waiting for GitHub to roll out the enhanced support for it, it will save a lot of pain.

**Comment by wtbarnes** [comment]
Also 👍 for this, but in favor of waiting on GH migration support

**Comment by kakirastern** [comment]
Or have an extra `main` branch in the interim period?

**Comment by kakirastern** [comment]
It's just `checkout -b` isn't it?

**Comment by dstansby** [comment]
@nabobalis is this good to close now?
