### ISSUE TITLE
Spurious printed output from Map?

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4680]
Examples in our gallery that call `sunpy.map.Map` on multiple maps are apparently printing spurious output.  They look like they might be [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code).  Here's [one case](https://docs.sunpy.org/en/latest/generated/gallery/map_transformations/reprojection_aia_euvi_mosaic.html#sphx-glr-generated-gallery-map-transformations-reprojection-aia-euvi-mosaic-py):

![ansi](https://user-images.githubusercontent.com/991759/100267722-e48ffd00-2f21-11eb-93b8-fc76b4ff53e6.png)

See also [here](https://docs.sunpy.org/en/latest/generated/gallery/map/difference_images.html#sphx-glr-generated-gallery-map-difference-images-py), [here](https://docs.sunpy.org/en/latest/generated/gallery/map_transformations/reprojection_align_aia_hmi.html#sphx-glr-generated-gallery-map-transformations-reprojection-align-aia-hmi-py), [here](https://docs.sunpy.org/en/latest/generated/gallery/units_and_coordinates/SDO_to_STEREO_Coordinate_Conversion.html#sphx-glr-generated-gallery-units-and-coordinates-sdo-to-stereo-coordinate-conversion-py), and [here](https://docs.sunpy.org/en/latest/generated/gallery/units_and_coordinates/getting_lasco_observer_location.html#sphx-glr-generated-gallery-units-and-coordinates-getting-lasco-observer-location-py).  However, not [here](https://docs.sunpy.org/en/latest/generated/gallery/units_and_coordinates/AIA_limb_STEREO.html#sphx-glr-generated-gallery-units-and-coordinates-aia-limb-stereo-py)?

**Comment by wtbarnes** [comment]
It looks like this primarily pops up when a list of files is passed to Map? Whereas your last example where this doesn't occur, each map is created from only a single file. 

Additionally, it looks like these characters are popping up in the Fido/parfive progress bar output too.

**Comment by jeffreypaul15** [comment]
Does this issue still persist? I've checked on both .ipynb and .py formats and this doesn't seem to occur.

**Comment by nabobalis** [comment]
It is still there on our live documentation.

**Comment by jeffreypaul15** [comment]
I'm a little oblivious when it comes to how sphinx works with this, will it automatically update if a change has been made? If not how does sphinx work with documentation?

**Comment by kakirastern** [comment]
Yeah, looks like the monster characters I see when I accidentally type stuff in my Terminal as the code is running on my fleet of Apple gadgets... Pretty sure it might be OS related now after @jeffreypaul15's remarks.

**Comment by nabobalis** [comment]
> I'm a little oblivious when it comes to how sphinx works with this, will it automatically update if a change has been made? If not how does sphinx work with documentation?

You have to re-run the documentation build to see any changes. The gallery example is ran once and cached so you have you clean it out if you want to see any changes.

**Comment by kakirastern** [comment]
Oh, Sphinx renders files originally in .RST format into browser-ready form like HTML under the hood iirc.

**Comment by kakirastern** [comment]
That is, Sphinx compiles...

**Comment by jeffreypaul15** [comment]
Understood, thanks! :) 
@kakirastern @nabobalis

**Comment by ayshih** [comment]
It looks like hiding the downloading-progress output for our RTD docs has also stopped this spurious output.  My guess is that this spurious output was not associated with the `Map()` call itself, but rather asynchronous downloading-progress output from the preceding downloading call that had yet to be flushed out before calling `Map()`.

Closing
