### ISSUE TITLE
Drop 32bit support?

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4683]
I think it is time for sunpy to stop "officially" supporting 32bit systems.

Currently we test for 32bit issues on our CI but we are unable to provide 32bit wheels and right now it seems that "manylinux2014_i686" does not have seem to have a 32bit build of the "HDF5-devel" library causing it to fail anyway.

@olebole you maintain the sunpy package for us on Debian's many arches, what are your thoughts on us dropping it?

**Comment by olebole** [comment]
I normally build it for 32 bit architectures: arm, mipsel, i386 are the official ones, and it currently builds fine everywhere ¹. So, I have still no problem with it. I however have no numbers of how much they are used. I guess it is not much.

I think, 32 bit is more a kind of test for clean code :-) than for a real use. Therefore I would suggest to keep it until there is an explicit reason to drop; even if you don't create binary packages for it. Maybe you don't officially "support" it anymore and decide to drop the support if a 32-bit-related bug appears that needs too much effort to fix it. But this is just my (pragmatic) opinion.

-- 
¹ I however just recognized that I don't use libhdf5-dev as build dependency; maybe I should change that? libhdf5 is [available on Debian](https://packages.debian.org/unstable/libhdf5-dev) for 32 bit as well.

**Comment by Cadair** [comment]
We have added a hdf5 dep on master, and it will be there for the 2.1 release, but not for existing releases.

This was triggered by some issues with our 32bit test, it seems that centos (base for the manylinux) hasn't build hdf5 for 32bit since centos6.

**Comment by nabobalis** [comment]
I think we will keep it around until something prevents us from testing on it.

**Comment by Cadair** [comment]
In #4705 I have given up trying to fix the CI with the 32bit image. There are various things we *could* do to keep it around, e.g. swap to debian over centos for the docker image, however all of these come at a time cost to modify the templates or build and update our own container for testing.

Given we only have a very small amount of C code which should be sensitive to being built on 32bit, hopefully it will continue to work for a long time. @olebole let me know if you feel strongly that we should be running our tests against 32bit and basically not relying on debain to test our releases against the 32bit arches.

**Comment by olebole** [comment]
@Cadair I think you can just rely on my tests; I also can backport fixes. I any case, the Debian packages are tested against a number of packages; so this is usual.

**Comment by Cadair** [comment]
Great thanks, and thanks for all your work on debian :)
