### ISSUE TITLE
Add solar orbiter colormaps

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4703]
The first Solar Orbiter data, from the EUI instrument has been released (http://soar.esac.esa.int/soar/), and it works really well with sunpy (👏 for meeting FITS standards). We should add new colormaps for the data to sunpy. Does anyone know anyone on the EUI team that we can ask to get these?

Update: we now know which colormaps to use for EUI 🎉

**Comment by wtbarnes** [comment]
Is there an example of any of these color maps being used somewhere?

**Comment by kakirastern** [comment]
@wtbarnes Yup, over at glueviz. Don't ask me why but they have the entire collection of colourmaps for most solar probes but they are searchable by Re only. I have some merged PRs over there regarding this.

**Comment by dstansby** [comment]
For reference, here's the reply I got from someone on the EUI team:

EUI color tables
---
In a research context everybody is encouraged to use the scaling and coloring that best displays the features under study.
For outreach purposes and online public display, the use of the reference color tables below is recommended:
FSI 304

We use the same color table as AIA 304, which is identical to IDL colorable 3 ('RED temperature'). In SSW this would be obtained by

aia_lct,wave=304,red,green,blue, /load  

FSI 174
We use the same color table aas AIA 171 ('gold'). In SSW this would be obtained by

aia_lct,wave=171,red,green,blue, /load  
HRIEUV

We use the same color table aas AIA 171 ('gold'). In SSW this would be obtained by

aia_lct,wave=171,red,green,blue, /load  
HRILYA

Starting from the "red temperature" color table in IDL, we add a bit of blue to make it violet

loadct, 3, rgb_table=rgb        ; 3= red temperature
factor=indgen(256)/256.
r=rgb[*,0]
g=rgb[*,1]
b=rgb[*,0]*factor
b=bytscl(b)
tvlct, r,g,b                    ; optional

**Comment by abhishekpandey1880** [comment]
I am intrested in this issue. Please can anyone guide me?

**Comment by dstansby** [comment]
Shall I close this, or leave it open for other Solar Orbiter colourmaps when the various instruments release data?

**Comment by wtbarnes** [comment]
I'm going to go ahead and close this since we have the colormaps for EUI. We can open up additional PRs for colormaps for  the other instruments as needed.
