### ISSUE TITLE
Map class for EUI instrument on Solar Orbiter

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4710]
We should probably consider adding a separate Map class for the EUI instrument on Solar Orbiter. As pointed out in #4703, the data can be loaded just fine with `GenericMap` though it would be nice to add some instrument-specific colormaps, one for each of the wavelengths (see [here](https://wwwbis.sidc.be/EUI/EUI/EUI/EUI/EUI/about/instrument) for more information).

Loading one of the level 2 EUV images, I also found that the exposure time keyword is `XPOSURE` as opposed to the expected `exptime`.

Additionally, the `bunit` keyword has `DN/s` so there will need to be a similar correction as applied to AIA here to get the units into something that is parsable by astropy.

There may be other needed corrections for the other telescope/wavelengths.

**Comment by Cadair** [comment]
Can someone link some data for people to get started with?

**Comment by kakirastern** [comment]
Yeah, may be better to spend some time and effort to compile a list of all relevant ground-based as well as satellite instruments for the new code addition(s)

**Comment by dstansby** [comment]
1. Go to http://soar.esac.esa.int/soar/#search
2. Select "EUI" under instrument
3. Select "L2" under proc level

They also have a metadata standard document here which is probably quite useful: https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/Archive+Support+Data?preview=/60885589/62824361/SP_ROB_SOEUI_19002_MetadataStandard_EUI_20201117_v1.6.pdf

**Comment by hayesla** [comment]
> 1. http://soar.esac.esa.int/soar/#search

Thanks nice - you can inspect fits header and WCS of the files :D 

We should look at making a Fido client I guess too. @dstansby do you know if there a list or observation coverage file somewhere (i.e. dates for when data is available?)

**Comment by Cadair** [comment]
I spoke to the VSO folk, they are planning on indexing the data, so we probably don't need to worry about writing a Fido client.

**Comment by ayshih** [comment]
They sure include a lot of options for spacecraft location: HGS, HGC (i.e., Carrington), HEE, HCI, HAE, HEEQ, and GSE.

The good news is that their HGS, HCI, HAE, and HEEQ options appear to be nearly consistent with our definitions, with only small differences when transforming between them.  I suggest that we use HCI over HGS because that's the only coordinate system for which they also provide the spacecraft velocity.  We don't currently make use of that, but there may come a time that we do.

The bad news is that their HGC, HEE, and GSE options are clearly not consistent.  The discrepancy with HGC is not surprising given the debate over how to calculate Carrington longitude.  The discrepancies with HEE and GSE, however, are bizarre since it feels like they've defined the ecliptic wildly wrong...  Does anyone know who's responsible for the EUI pipeline?

**Comment by dstansby** [comment]
It might be that the observer information is filled in by (or disseminated to instrument teams by) ESA - emailing Andrew Walsh or Dave Williams at ESAC might be a good place to start, and they can probably direct to the right person - @ayshih I can put you in touch via. email if you'd like to raise the coordinate issues?

Also of note, on page 40 of the [Metadata Definition for Solar Orbiter Science Data](https://issues.cosmos.esa.int/solarorbiterwiki/download/attachments/6558892/SOL-SGS-TN-0009-MetadataStandard-2.4.pdf) it says
> All ephemeris values are to be calculated at the time DATE-AVG.

so we need to be careful that we're taking the `DATE-AVG` field to fill in the observer coordinate obstime.

**Comment by ayshih** [comment]
> I can put you in touch via. email if you'd like to raise the coordinate issues?

Yes, please do!

**Comment by Cadair** [comment]
> All ephemeris values are to be calculated at the time DATE-AVG.

These people are my friends, they have read the FITS spec :heart_eyes:.

We should probably make some changes to `GenericMap` to reflect this change (and maybe one or two others) which are new in FITS 4. We should be de-prioritising `DATE-OBS` if the more tightly specified keys in FITS 4 are present.

**Comment by ayshih** [comment]
> The discrepancies with HEE and GSE, however, are bizarre since it feels like they've defined the ecliptic wildly wrong...

The Solar Orbiter folks have fixed their SPICE definitions of HEE/GSE after I tracked down exactly where the error was.  Hopefully any new files generated by the EUI pipeline will use the updated SPICE kernels.  Even then, there will still be a slight discrepancy because of #4893.
