### ISSUE TITLE
Units of arcsec/pix do not make sense for all projection codes

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4714]
### Description
`make_fitswcs_header` provides a nice interface to produce a WCS header, and allows one to specify a `projection_code`. I commonly pass `projeciton_code='CEA'`, which is a cylindrical equal area projection. The latitude axis here is evenly spaced in `sin(latitude)`, so CDELT for the latitude axis is dimensionless. `make_fitswcs_header` forces `scale` to be in units of `arcsec/pix` however, which isn't appropriate for the latitude axis of a CEA projection.

### Expected vs Actual behavior
The following code should work:

```python
from astropy.coordinates import SkyCoord
import sunpy.coordinates
import astropy.units as u
from sunpy.map import make_fitswcs_header
import numpy as np

shape_out = [180, 360]
projection_code = 'CEA'
frame_out = SkyCoord(0, 0, unit=u.deg,
                     frame="heliographic_carrington",
                     obstime='2020-01-01',
                     observer='earth')
header = make_fitswcs_header(
    shape_out, frame_out,
    scale=[180 / np.pi * 2 / shape_out[0],
           360 / shape_out[1] * u.deg / u.pix],
    projection_code=projection_code)
```
but produces the error:
```python
Traceback (most recent call last):
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 70, in _validate_arg_value
    is_equivalent = arg.unit.is_equivalent(allowed_unit,
AttributeError: 'list' object has no attribute 'unit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    header = make_fitswcs_header(
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 245, in wrapper
    _validate_arg_value(param.name, wrapped_function.__name__,
  File "/Users/dstansby/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py", line 83, in _validate_arg_value
    raise TypeError(f"Argument '{param_name}' to function '{func_name}'"
TypeError: Argument 'scale' to function 'make_fitswcs_header' has no 'unit' attribute. You should pass in an astropy Quantity instead.
```

### System Details

- SunPy Version: master
- Astropy Version: 4.1
- Python Version: 3.9
- OS information: macOS 11

**Comment by Cadair** [comment]
What happens if you multiply the scale by `u.one`?

**Comment by dstansby** [comment]
It fails the same way, since the function is expecting `scale` to be a `Quantity` instead of a list (with two different `Quantity`s inside).

**Comment by Cadair** [comment]
Oh I see, so this error is also partly that we are expecting both the CUNIT keys to have compatible units.

**Comment by Cadair** [comment]
This is pretty easy to work around? You can just override the `CUNIT` key after the function call? I wonder if it is possible for us to be really smart here and validate the units based on the projection?

**Comment by dstansby** [comment]
Yeah, definitely not a high priority bug, just a bit annoying to have to edit the header after it's created.

**Comment by dstansby** [comment]
On second thoughts (and after actually reading FITS paper 2 😆), since `scale` is interpreted as CDELT, this should always be in units of `arcsec/pix` or equivalent, because by definition this is used to transform from pixel coordinates to intermediate coordinates, which are in units of degrees (see https://www.atnf.csiro.au/people/mcalabre/WCS/ccs.pdf section 1).

The user is then left with the task choosing an appropriate CDELT such that the final celestial projection has the desired bounds. I think I got confused because the case where celestial longitude/latitude align with the pixel axes then one might naïvely think that CDELT has some meaning in word coordinates, whereas it doesn't really.

**Comment by kakirastern** [comment]
Just for our future dev and reference: https://www.aanda.org/articles/aa/full/2002/45/aah3859/aah3859.right.html

The FITS header keyword `CDELT` connotes some :
> CDELT n | coordinate increment at reference point

So when we construct say a WCS object from scratch, we could ideally specify say the following as the basic template:

> CRVAL n | coordinate value at reference point
> CRPIX n | array location of the reference point in pixels
> CDELT n | coordinate increment at reference point
> CTYPE n | axis type (8 characters)
> CROTA n | rotation from stated coordinate type.

I often omit the last, maybe coz I use the transformations `RA---TAN` and `Dec--TAN` for the projection.
