### ISSUE TITLE
Update metadata model to FITS 4

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4716]
Our metadata model needs updating regarding FITS 4. This was partially motivated by #4712. The purpose of this issue is to discuss exactly how to do this. This will probably need to be split into multiple issues and maybe become a project, but we can leave it as a single issue for now.

Some properties on `GenericMap` that need updating:

* `exposure_time` -- we currently expect `exp_time`, but `xposure` is also (more?) valid
* `date` -- we currently use `date-obs`, but we should think about adding additional properties for `date-avg`, `date-start`, and `date-end`. We can always fall back to `date-obs` for FITS 3

In particular, `date-avg` is the "more correct" obstime to use for defining our coordinate frame, but currently we use `Map.date` (which is defined using `date-obs`) everywhere, including for defining our coordinate frame and observer coordinate.

**Comment by dstansby** [comment]
See https://fits.gsfc.nasa.gov/fits_standard.html for the FITS standard document(s).

**Comment by dstansby** [comment]
I think this is done now - see above linked PRs.

**Comment by wtbarnes** [comment]
We are actually still using `exp_time` by default instead of the FITS-4 `xposure` key for exposure time.

**Comment by wtbarnes** [comment]
I'm closing this in favor of the more specific #6513
