### ISSUE TITLE
Add a dynamic z axis option to the animators

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4718]
So if your frames have a wide dynamic range the z scale changes

**Comment by SnehVachhani** [comment]
I want to start this issue please can anyone provide me some more information regarding this issue. Like which file to be modified and what to be checked?

**Comment by nabobalis** [comment]
Hi @SnehVachhani, this is not an issue I would suggest new people work on. The animators are very opaque and not great to work on. Please look at https://github.com/sunpy/sunpy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Good+First+Issue%22 instead

**Comment by jeffreypaul15** [comment]
Any resources on this issue? Would like to work on this if it's open.

**Comment by dstansby** [comment]
😆 this is a classic @Cadair one-liner issue. To add a bit more detail:

If you have a 3D dataset, the animator animates one of those dimensions. Currently the `vmin`/`vmax` for the colorbar is set to be the minimum and maximum of the whole 3D dataset, but if there is a wide range of values across the dimension being animated, it can be helpful to update the `vmin`/`vmax` to the vmin/max of the 2D slice currently being shown, and updating it again each time a new slice is shown.

**Comment by jeffreypaul15** [comment]
Alright, I'll get started reading up on this!

**Comment by jeffreypaul15** [comment]
> laughing this is a classic @Cadair one-liner issue. To add a bit more detail:
> 
> If you have a 3D dataset, the animator animates one of those dimensions. Currently the `vmin`/`vmax` for the colorbar is set to be the minimum and maximum of the whole 3D dataset, but if there is a wide range of values across the dimension being animated, it can be helpful to update the `vmin`/`vmax` to the vmin/max of the 2D slice currently being shown, and updating it again each time a new slice is shown.

Is there code for creating an animation from a 3D dataset? I can't seem to find an example that lists this out.

**Comment by nabobalis** [comment]
I believe this is an example: https://docs.sunpy.org/en/latest/generated/gallery/plotting/arrayanimatorwcs.html#sphx-glr-generated-gallery-plotting-arrayanimatorwcs-py

**Comment by jeffreypaul15** [comment]
> laughing this is a classic @Cadair one-liner issue. To add a bit more detail:
> 
> If you have a 3D dataset, the animator animates one of those dimensions. Currently the `vmin`/`vmax` for the colorbar is set to be the minimum and maximum of the whole 3D dataset, but if there is a wide range of values across the dimension being animated, it can be helpful to update the `vmin`/`vmax` to the vmin/max of the 2D slice currently being shown, and updating it again each time a new slice is shown.

The ```ArrayAnimatorWCS``` allows the user to specify a vmax by, without using this property the images have a wide range of values, is this what you are referring to?

**Comment by dstansby** [comment]
Yes, if you specify a `vmax` it is the same `vmax` for all the frames of the animation. I think a good API to fix this feature request would be allow `vmax='auto'` to be specified, which would update the `vmax` value frame by frame based on the maximum value of the data being shown in that frame.

**Comment by jeffreypaul15** [comment]
> Yes, if you specify a `vmax` it is the same `vmax` for all the frames of the animation. I think a good API to fix this feature request would be allow `vmax='auto'` to be specified, which would update the `vmax` value frame by frame based on the maximum value of the data being shown in that frame.

Yeah that makes sense, I shall get working on this and make a PR soon

**Comment by jeffreypaul15** [comment]
> Yes, if you specify a `vmax` it is the same `vmax` for all the frames of the animation. I think a good API to fix this feature request would be allow `vmax='auto'` to be specified, which would update the `vmax` value frame by frame based on the maximum value of the data being shown in that frame.

While implementing this, I was thinking if I were to set the ```vmin```/```vmax``` to a ```clip_interval=(1, 90)*u.percent``` or should the ```vmax``` be greater than 90? These seem to produce optimal results. such as 
![image](https://user-images.githubusercontent.com/50923538/108553275-74262b80-7318-11eb-8bba-dda12081c2d4.png)
and 
![image](https://user-images.githubusercontent.com/50923538/108553397-991a9e80-7318-11eb-94d6-b66d38272cd1.png)
From [this example](https://docs.sunpy.org/en/latest/generated/gallery/plotting/arrayanimatorwcs.html#sphx-glr-generated-gallery-plotting-arrayanimatorwcs-py)
