### ISSUE TITLE
Agree on solar ephemerids calculations

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#472]
@wafels said: We should unify sun_pos.py and sunpy.sun but agree on which calculation to use on PR #452

**Comment by ehsteve** [comment]
A neat new find. A web service that provides ephemeris info
Check it out!
http://sscweb.gsfc.nasa.gov/WebServices/helio/

**Comment by dpshelio** [comment]
and I've found this one today: http://bass2000.obspm.fr/ephem.php which aslo provides a [webservice](http://vo.imcce.fr/webservices/miriade/?ephemph)
They are going to be good for testing all I'm trying to write :)

**Comment by ehsteve** [comment]
@dpshelio why write anything if we can get it for free?

**Comment by dpshelio** [comment]
@ehsteve ... you may remember this comment the day Earth is hit by a solar storm and there's not internet connection around the world... and you have to calculate whether the next one coming after the first with a lot more strength will or won't hit us... then... just then you will remember the price of "free"  ;)

**Comment by ayshih** [comment]
Since I've now fallen down this rabbit hole, I'll sum up what I've found:

* `sunpy.physics.differential_rotation` is more accurate than `sunpy.sun.sun`
* `sunpy.physics.differential_rotation` has errors in the RA and declination at the level of arcseconds, comparing against the Python library Skyfield (the successor to PyEphem)
* One source of discrepancies with the JPL Horizons calculator can be because it provides RA and declination in the J2000.0 epoch rather than the requested time

**Comment by Cadair** [comment]
for solar position there is now http://docs.astropy.org/en/latest/api/astropy.coordinates.get_sun.html

**Comment by bwgref** [comment]
The one thing the astropy version doesn't do (or at least it's not documented well enough for me to find) is provide other things from the ephemeris (like solar north pole angle wrt celestial north) that are useful for conversion to heliocentric coordinates from RA/dec.

Side note: Is it ever useful to have RA/dec that's **not** in a standard (J2000) epoch? This seems like it's returning highly ambiguous data...

**Comment by Cadair** [comment]
@bwgref yes as far as I am aware there is no solar north functionality in astropy.

On a topic of RA/dec conversion, do you have information on how to do that transformation? and also any knowledge of doing anything like HPC or HG to ICRS conversions by chance?

**Comment by bwgref** [comment]
@Cadair See [the notebook here](https://github.com/NuSTAR/nustar_pysolar/blob/master/convert_to_solar/Convert_To_Solar_Example.ipynb) for the simple way to go from RA/dec (J2000 ) to HPC based on the WCS info in a FITS header. It's a combination of astropy (to get the Sun center as a function of time) and sunpy (to get solar north).

Anything more advanced (i.e. any other solar coordinate systems) is beyond my ken.

**Comment by ayshih** [comment]
@bwgref Do the Python and IDL versions of your conversion scripts agree?

**Comment by bwgref** [comment]
@ayshih Yes. This is effectively a test of whether the combination of the astropy/sunpy ephemeris/north pole matches what I get from JPL Horizons, which I was previously loading in by hand to avoid ambiguities with the SSWIDL get_sun routines. The astropy solar coordinates match Horizons, and the sunpy north pole axis matches what I get from Horizons.

**Comment by Cadair** [comment]
@bwgref Does JPL Horizons or any other source you know of give the position of solar north in ICRS or similar 'fixed' astro frame?

**Comment by Cadair** [comment]
@dpshelio and all. Do we have all the functionality we want now? Or are there still things that need implementing or checking?
