### ISSUE TITLE
Add a contains coordinate method to maputils

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4726]
This would provide a quick way to see if a world coordinate is contained within the array bounds of a Map

**Comment by ayshih** [comment]
Whoever implements this might as well fix the craziness of `maputils.contains_solar_center()` at the same time (see https://github.com/sunpy/sunpy/pull/4463#discussion_r492832186), since that would just be a special case of a more general function.

**Comment by kakirastern** [comment]
Cannot agree more

**Comment by SnehVachhani** [comment]
I am new to open source, want to start from this please can anyone provide me some more information regarding this issue. Like which file to be modified and what to be checked?

**Comment by dstansby** [comment]
Thanks for the interest! Essentially we would like a new function in `sunpy/map/maputils.py` called `contains_coordinate(smap, coord)` (or similar), which returns `True` if the `coord` is within the coordinate bounds of `smap`, and `False` otherwise.
