### ISSUE TITLE
Cleanup changelog before 2.1 final

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4733]
There are some broken links, incorrect rst syntax etc that I noticed just in the first few entries, we should do a pass and make sure it renders correctly.

**Comment by Cadair** [comment]
You mean from an editing the files perspective?

**Comment by dstansby** [comment]
Yeah, I just ran towncrier locally and found that there were 67 new broken links for 2.1(!), but I don't want to go back and edit all the individual fragment files to fix them, so it's easier to wait until `towncrier` has been run and committed to the `2.1` branch.
