### ISSUE TITLE
LASCOMap needs better handling of meta info

### ISSUE THREAD

**Issue by rhewett** [sunpy/sunpy#475]
LASCO wavelength attribute should indicate whether total B, pB, etc.  Or another keyword/attribute should be added and this info should appear in name, nickname, and probably repr

**Comment by chouhanaryan** [comment]
Hi, I'd like to take this up. From what I can gather, this involves updating two properties of the `LASCOMap` class - `measurement` and `wavelength` (inherited from `GenericMap`). This change will then propagate to str, nickname (? - doesn't this only display the name of the instrument and the detector - ?) and repr.

From where can I get the appropriate info required for this? Even though this issue might require some solar physics knowledge, I'd like to give it a try 😅
