### ISSUE TITLE
You have to specify seconds on the time string arguments to a.Time now

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4768]
I could have sworn you didn't used to have to do this.

**Comment by dstansby** [comment]
What's a reproducible example?

**Comment by Cadair** [comment]
`a.Time("2020/10/01T00:00", "2020/10/01T00:00")` no longer works when I am sure it used to.

**Comment by dstansby** [comment]
```python
from sunpy.net import attrs
attrs.Time("2020/10/01T00:00", "2020/10/01T00:00")
```
Doesn't work for me on 2.0.x, 1.1.x, or 1.0.x, so I'm going to re-label this as a feature request.

**Comment by Cadair** [comment]
I wonder if we lost this in the 1.0 time refactor then :thinking:

**Comment by dstansby** [comment]
Should be pretty easy to fix, just need to add another custom time format entry to `sunpy/time/time.py`

**Comment by abhishekpandey1880** [comment]
I am intrested in this issue and from the discussion it seems that I have to add `"%Y/%m/%dT%H:%M",  # Example 2007/05/04T21:08` in the `TIME_FORMAT_LIST` array in `sunpy/time/time.py` .

**Comment by nabobalis** [comment]
Probably should be enough.
