### ISSUE TITLE
Not an issue: 2.1.0RC1 uploaded to debian experimental, and built/tested successfully

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#4775]
### Description

I found a new RC on PyPI and uploaded it to [Debian experimental](https://packages.debian.org/experimental/python3-sunpy). It [builds on the release platforms (incl. tests)](https://buildd.debian.org/status/logs.php?pkg=sunpy&ver=2.1.0%7Erc1-2&suite=experimental) (which covers 32&64 bit, and big/little endian; mips archs still missing).

No problems where found; I thought this is also a good reason to report :100: .

Python version is 3.9.

**Comment by Cadair** [comment]
This is maybe the best issue ever :wink:

**Comment by kakirastern** [comment]
Hooray 💯

**Comment by nabobalis** [comment]
Thanks for the report Ole.
