### ISSUE TITLE
Improve __str__ of time returned from carrington_rotation_time

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4818]
### Description
If I print the time of a manually constructed astropy Time, it gives a nice human readable string:
```python
from astropy.time import Time
t = Time('2020-01-01')
print(t)
# 2020-01-01 00:00:00.000
```
However, if I try and print the output of `sunpy.coordinates.sun.carrington_rotation_time` it just gives me a number:
```python
from sunpy.coordinates.sun import carrington_rotation_time
observation_time = carrington_rotation_time(2210.8)
print(observation_time)
# 2458440.210927545
```
It would be much nicer if this printed a human-readable timestamp.

### System Details

- SunPy Version: 2.0.6
- Astropy Version: 4.2
- Python Version:
- OS information:

**Comment by ayshih** [comment]
What, you don't consider JD to be human readable? =P

Very easy to fix: just need to modify the format of the `Time` instance after it is created but before it is returned.

**Comment by ayshih** [comment]
Oh, and the scale of the time instance should probably be converted from Terrestrial Time (TT) to Coordinated Universal Time (UTC), since most solar physicists don't work with TT.
