### ISSUE TITLE
Identically sliced UnifiedResponse don't compare equal

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4820]
Consider
```python
from sunpy.net import Fido, attrs as a
import astropy.units as u

t = '2015-01-01'
result = Fido.search(a.Time(observation_time, observation_time + u.hr * 1),
                     a.Instrument('AIA'),
                     a.Wavelength(19.3 * u.nm))
print(result[0] == result[0])
# False
```
I would expect these two identically sliced results to be equal, but they are not.

sunpy version: 2.0.6

**Comment by lzivadinovic** [comment]
Im not sure how python actually compares those objects, maybe we need to implement __eq__ or something similar.

For example, if you do:
```
print(hash(result[0]) == hash(result[0])) # True
```

Some basic insights on this https://stackoverflow.com/questions/1227121/compare-object-instances-for-equality-by-their-attributes

**Comment by dstansby** [comment]
Possibly as the result of a behaviour change in astropy, the above snippet now does elementwise comparison, which I think is fine.
