### ISSUE TITLE
Add a way of specifying rotation number and longitude to carrington_rotation_time

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4821]
Currently `carrington_rotation_time` accepts a floating point number as input, which is the fractional Carrington rotation number. However, calculating this number from a rotation number and Carrington longitude is a bit confusing, because Carrington longitudes run backwards in time, going from 360 > 0. e.g.

```
2210, 90 deg > 2210.75
2210, 180 deg > 2210.5
2210, 270 deg > 2210.25
```
(note that in the order written, these numbers/coordinates are going backwards in time)

It would be nice if the API somehow allowed one to input rotation number and Longitude, so it was easy to input these values directly read from a synoptic map (e.g. https://sdo.gsfc.nasa.gov/data/synoptic/).

**Comment by ayshih** [comment]
Interesting...  I guess just add a `longitude` keyword argument?
