### ISSUE TITLE
Reduce the size of our test data

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4823]
Currently the sunpy source tree is 19Mb (uncompressed) and 12Mb of this is in `sunpy/data/test/`. We should go through that folder and reduce every file in it to around the 10kb mark, and remove any which are no longer used in the tests.

**Comment by nabobalis** [comment]
See https://github.com/sunpy/sunpy/issues/1686 as well.

**Comment by SnehVachhani** [comment]
I want to start this issue please can anyone provide me some more information regarding this issue. Like which files are to be removed and how to know which test are no longer used?

**Comment by nabobalis** [comment]
The files are here: https://github.com/sunpy/sunpy/tree/master/sunpy/data/test
You will need to rescale the larger files down and update the relevant metadata.

To find out if a file is not used, I think it is probably easier to just search for the file name and see if it pops up in a test file.

**Comment by dstansby** [comment]
What's the motivation for doing this? Unless the git history is re-written, aren't the files in there for good, and deleting them won't reduce the repo size?

**Comment by nabobalis** [comment]
Rewrite the git history on master.

**Comment by Cadair** [comment]
The motivation is to make the tarball and wheels that people download smaller.

**Comment by dstansby** [comment]
I didn't realise the test data goes into the wheels, could we just remove the test data from them?

**Comment by nabobalis** [comment]
It would make self testing a bit more complicated.

**Comment by Cadair** [comment]
Like it wouldn't work. We could either deselect the whole test suite and not package the tests at all, or we can do this to mitigate it.

**Comment by nabobalis** [comment]
> Like it wouldn't work. We could either deselect the whole test suite and not package the tests at all, or we can do this to mitigate it.

We can make it work.

**Comment by dstansby** [comment]
- Self test doesn't work anyway at the moment (as far as I can remember)
- Shouldn't be too hard to download the test data on demand when self test is run?

**Comment by Cadair** [comment]
I think if we want to discuss removing the tests from the dist then we should open a new issue.
