### ISSUE TITLE
Work out why Fido isn't finding SDO/AIA near real time (NRT) data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4841]
It takes a few days for AIA data to be processed to L1, and make it into the JSOC database, but near realtime data can be downloaded from http://jsoc2.stanford.edu/data/aia/synoptic/nrt/. It would be good if Fido could search for a download this data.

An example script that should return AIA NRT results, but currently returns nothing:
```python
import astropy.units as u
from sunpy.net import Fido, attrs as a
from datetime import datetime, timedelta
from sunpy.map import Map

dtime = datetime.now()

query = (a.Time(dtime - timedelta(days=1), dtime, dtime),
         a.Instrument('AIA'),
         a.Wavelength(193 * u.Angstrom))
result = Fido.search(*query)
print(result)
```

**Comment by ayshih** [comment]
I'll cross-reference to #3505 for an issue with the observer information in NRT files, although perhaps that has been subsequently fixed?

**Comment by Cadair** [comment]
I was under the impression that VSO indexed these data.

**Comment by ayshih** [comment]
Certainly I've gotten NRT files before via `VSOClient`, hence the issue that I cross-referenced.

**Comment by ayshih** [comment]
Heh, I'll cross-reference #4159, where @dstansby was reporting an issue with getting (unwanted) NRT files through Fido

**Comment by dstansby** [comment]
https://github.com/sunpy/sunpy/issues/4159 is related; it seems like at one point it was possible to get NRT data through the VSO, but this has stopped working at some point in the last ~6 months.

**Comment by Cadair** [comment]
I am reluctant to consider adding out own client for data indexed by the VSO, hopefully we get some info on why it's bust.

**Comment by AlisdairDavey** [comment]
We (VSO) are not aware of any problem with getting NRT images in the recent past, except since Jan 1 2021. This is because of a known issue at the MOC that the MOC team at NASA is fixing (courtesy of Art). With this we would expect NRT images to become available again once the issues are fixed.

**Comment by dstansby** [comment]
Fab, thanks for the update!

**Comment by jeffreypaul15** [comment]
> Fab, thanks for the update!

When querying why is there a need for ```near``` time when we already have ```start``` and ```end``` times? Removing this produces the required results but I'm confused as to why we use ```near```.

**Comment by dstansby** [comment]
Yep, looks like this is fixed.
