### ISSUE TITLE
Add Fido client for STEREO/SECCHI beacon data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4842]
It takes a few days for STEREO/SECCHI data to be processed to L1, but beacon data can be downloaded from e.g. https://stereo-ssc.nascom.nasa.gov/pub/beacon/ahead/secchi/img/euvi/20210107/. It would be good if Fido could search for a download this data.

An example script that could return SECCHI beacon results, but currently returns nothing:
```python
import astropy.units as u
from sunpy.net import Fido, attrs as a
from datetime import datetime, timedelta
from sunpy.map import Map

dtime = datetime.now()

query = (a.Time(dtime - timedelta(days=1), dtime, dtime),
         a.Instrument('SECCHI'))
result = Fido.search(*query)
print(result)
```

**Comment by jeffreypaul15** [comment]
I was looking into the class structure of ```Instrument```. SECCHI is a supported instrument by the VSO but I'm unable to figure out what is the reason for it not producing data. Can anyone point me in the right direction to solve this particular issue, should I be looking into ```Instrument``` with more detail and see why this isn't happening?

**Comment by nabobalis** [comment]
If this data is not being indexed by the VSO it will not show up in a Fido search.

We can ask the VSO if they would index this data or we can write a full Fido client to do so ourselves. The structure of `Instrument` is not important here.

**Comment by jeffreypaul15** [comment]
Alright, any resources regarding writing a Fido client or something along these lines I can refer to?

**Comment by nabobalis** [comment]
Nothing final, at the moment its on a draft PR here: https://github.com/sunpy/sunpy/pull/4387 

Also two PRs here that have implemented clients: 
https://github.com/sunpy/radiospectra/pull/35
and 
https://github.com/sunpy/radiospectra/pull/34

**Comment by dstansby** [comment]
For a bit more info, I think the way to go here is to implement a client that uses the scraper, and scrape files in https://stereo-ssc.nascom.nasa.gov/pub/beacon/ahead/secchi/img/euvi/20210107/ (and other directories by date).

**Comment by jeffreypaul15** [comment]
> For a bit more info, I think the way to go here is to implement a client that uses the scraper, and scrape files in https://stereo-ssc.nascom.nasa.gov/pub/beacon/ahead/secchi/img/euvi/20210107/ (and other directories by date).

All the files in the ```img``` directory or the ones in ```cal```, ```seq``` and ```summary``` as well?

**Comment by dstansby** [comment]
Just the files in the `img` directory.

**Comment by jeffreypaul15** [comment]
I've implemented this by referring to ```sunpy/net/dataretriever/sources/rhessi.py' and using the sunpy scraper Scraper. 
Should I have to hard-code the ```cor2```, ```euvi```, ```hi_1```, ```hi_2``` directories and loop through them while capturing the data?

**Comment by Cadair** [comment]
@AlisdairDavey from the VSO team has just reached out to me to say that VSO are considering indexing this data. Apparently they will decide in the next few days if they are going to do so. I therefore suggest we press pause on this for a while to see what happens.

@jeffreypaul15 if you have code already feel free to open a PR, we can then compare it to whatever (if anything) the VSO does.

**Comment by jeffreypaul15** [comment]
> It takes a few days for STEREO/SECCHI data to be processed to L1, but beacon data can be downloaded from e.g. https://stereo-ssc.nascom.nasa.gov/pub/beacon/ahead/secchi/img/euvi/20210107/. It would be good if Fido could search for a download this data.
> 
> An example script that could return SECCHI beacon results, but currently returns nothing:
> 
> ```python
> import astropy.units as u
> from sunpy.net import Fido, attrs as a
> from datetime import datetime, timedelta
> from sunpy.map import Map
> 
> dtime = datetime.now()
> 
> query = (a.Time(dtime - timedelta(days=1), dtime, dtime),
>          a.Instrument('SECCHI'))
> result = Fido.search(*query)
> print(result)
> ```

@dstansby Shouldn't it be 
```python
query = (a.Time(dtime - timedelta(days=1), dtime),
         a.Instrument('SECCHI'))
``` 
as you're passing a range right? Correct me if I'm wrong.

**Comment by dstansby** [comment]
Yeah, I think your example is better. The third argument is a "give me the result closest to this time", so my example should still return one result.

**Comment by jeffreypaul15** [comment]
> Yeah, I think your example is better. The third argument is a "give me the result closest to this time", so my example should still return one result.

Okay, and also a little confused on how to input the directories in the ```img``` directory, should I be returning data from all for sub-directories under ```img``` when a TimeRange is passed?

**Comment by nabobalis** [comment]
See VSO update here: https://github.com/sunpy/sunpy/pull/4869#issuecomment-772797409
