### ISSUE TITLE
Can the VSO client have additional keywords added?

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4861]
I've a question about VSO client - is there a way to add in additional `kwargs` that aren't necessarily `attrs` of the client. For example, in `vso_search.pro` in sswidl you can add in a `near=` keyword which will return a file closest to the time specified in that `kwarg`. 

I don't think the `near` keyword works for all clients, but does for AIA and is pretty handy. 

When looking at the results of an AIA query with Fido there is a `near` keyword in the time element of the block response:

```python
>>> res = Fido.search(a.Time("2013-10-28 00:00", "2013-10-28 01:00"), 
                               a.Instrument("AIA"), 
                               a.Wavelength(193*u.angstrom))
>>> res.get_response(0).blocks[0]["time"]
{
    'start': '20131028000006',
    'end': '20131028000007',
    'near': None
}
```

Anyway, my knowledge of how the VSO client isn't great, and maybe this is a silly question, just curious if there were a way to implement it within the client (rather than indexing the Fido query result).

**Comment by Cadair** [comment]
You can specify near with the third argument to the `a.Time` attr. (https://docs.sunpy.org/en/stable/api/sunpy.net.attrs.Time.html#sunpy.net.attrs.Time)

In theory all of the supported VSO search parameters should be in attrs somewhere, and if they aren't we should look at adding them.

**Comment by hayesla** [comment]
ah nice! thanks @Cadair ! that works nicely 🚀 

```python
>>> res = Fido.search(a.Time("2013-10-28 00:00", "2013-10-28 01:00", "2013-10-28 00:30"), 
                                       a.Instrument("AIA"), 
                                       a.Wavelength(193*u.angstrom))
>>> res 
<sunpy.net.fido_factory.UnifiedResponse object at 0x7f94d37397d0>
Results from 1 Provider:

1 Results from the VSOClient:
   Start Time [1]       End Time [1]    Source Instrument   Type   Wavelength [2]
                                                                      Angstrom   
------------------- ------------------- ------ ---------- -------- --------------
2013-10-28 00:29:54 2013-10-28 00:29:55    SDO        AIA FULLDISK 193.0 .. 193.0
```
