### ISSUE TITLE
Document that carrington_rotation_time accepts arrays as input

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4863]
https://docs.sunpy.org/en/stable/api/sunpy.coordinates.sun.carrington_rotation_time.html currently just says it accepts a `float` as input, so I thought I would have to loop through my array and call it one value at a time. I tried it with an array though, and it seemed to work fine, so we should document that arrays are also a valid input.

In addition, if there isn't already a test that uses this function with an array input, we should add one.

**Comment by SagarJC** [comment]
hey @dstansby , Mentioning that both float and array are valid input is enough know? in the docstring...

**Comment by dstansby** [comment]
Yes, that's right. It looks like this is being worked on in #4879 though, so if you're looking for an issue to tackle it is probably worth looking at another one.
