### ISSUE TITLE
Unclear which way round colourmap is in Map quicklook

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4864]
I have a map with data scaled from 0 > 1, and quicklooking it in a notebook gives me the following output:

![Screenshot 2021-01-12 at 13 36 00](https://user-images.githubusercontent.com/6197628/104321238-43fa9a00-54db-11eb-947c-12e8d08e8ce5.png)

It's not clear from looking at this (maybe I'm missing something?) whether black/white areas of the map are high/low values.

**Comment by ayshih** [comment]
Well, the white areas should be the high values and the black areas should be the low values, but there's certainly no color bar to make that clear.  A color bar can probably be integrated with the histogram plot to avoid taking up additional real estate.

(Hmm, it might not be *too* insane to consider adding Javascript handling for mousing over the image...)

**Comment by dstansby** [comment]
I've tagged this as a feature request, as I think there should be some way to work out which way round the values are from the quicklook. Maybe there's a clever way of labelling (or colouring?) the histogram.

**Comment by ayshih** [comment]
@dstansby: Can you give fad76a90a80d89f95e856dfd124361de4e94aa56 a try and see what you think?  The histogram can be clicked on.

**Comment by ayshih** [comment]
Can you try #4931 with your map?
