### ISSUE TITLE
Add a default sunpy database

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4870]
Currently in the database module one has to manually create a database, using
```python
from sunpy.database import Database
database = Database('sqlite:///sunpydata.sqlite')
```
It would be good if sunpy had a default Database object (maybe a `sunpy.database.DefaultDatabase`?), so the user doesn't have to worry about creating one with sqlite syntax as above. The actual database file could live in the sunpy data folder.

**Comment by Cadair** [comment]
I thought we already did this if you didn't pass an argument to the constructor, but if we don't then we should.

**Comment by nabobalis** [comment]
The future of database is pretty much on life support so there is no point in fixing issues for that.
