### ISSUE TITLE
Remove the need to manually commit changes to a Database

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4871]
The database guide says:

> If you are using Database objects in an interactive Python session you must not forget to call the Database.commit() method on them explicitly before quitting the Python session! Otherwise, all changes on the altered databases are lost!

This is a bit annoying from a user perspective.

It would be good to either
- Call `commit()` internally every time a change is made, or
- Call `commit()` inside a custom `__del__` method, so that commit() is run when the `DataBase` python object is garbage collected. I'm not sure if this is too clever though, and there might be cases where users would unexpectedly lose their changes.

**Comment by wtbarnes** [comment]
Given our desire to deprecate the current version of the database subpackage and rebuild it, I'm going to close this as I suspect we will remove and or significantly refactor most of the guide anyway. Feel free to reopen if you disagree.
