### ISSUE TITLE
Limit the number of rows in the BaseClient repr

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4884]
The VSOClient repr in particular is very long, it makes sense to print it all in the `__str__` method but not in `__repr__`

**Comment by nakul-shahdadpuri** [comment]
Hi @Cadair, I think the BaseClient ```__repr__``` method is extended to VSOClient. Is it okay if the ```__repr__ ``` method of the Baseclient class returns a VSOclient object instead of printing the object?
