### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by fabianme17** [sunpy/sunpy#4907]
I update all anaconda modules last week.
Since then, I got an erro when trying to run this piece of code:
`from sunpy.coordinates.sun import angular_radius`
`Traceback (most recent call last):`

`  File "<ipython-input-15-37562b618349>", line 1, in <module>`
`    from sunpy.coordinates.sun import angular_radius`

`  File "/Users/user/anaconda3/lib/python3.7/site-packages/sunpy/coordinates/__init__.py", line 23, in <module>`
`    from .ephemeris import *`

`  File "/Users/fabian/anaconda3/lib/python3.7/site-packages/sunpy/coordinates/ephemeris.py", line 15, in <module>`
`    from astropy._erfa.core import ErfaWarning`

`ModuleNotFoundError: No module named 'astropy._erfa.core'`

OS: MacOS Big Sur 11.1 (20C69)

**Comment by ayshih** [comment]
It looks like you're trying to run a rather old version of SunPy with an up-to-date version of Astropy.  What version of SunPy are you running?  My guess is 1.1.x?

**Comment by fabianme17** [comment]
It was exactly that! After an update it worked fine.
Thank you so much.

Fabian Marcel Menezes

Centro de Rádio-Astronomia e Astrofísica Mackenzie
Rua da Consolação, 896 - prédio 45 - 7º andar
São Paulo, SP, Brasil


Em seg., 25 de jan. de 2021 às 21:45, Albert Y. Shih <
notifications@github.com> escreveu:
