### ISSUE TITLE
Add explicit signatures to Fido attribute documentation

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4913]
Currently Fido attributes have a generic (`*args, **kwargs`) function signature in the docs: https://docs.sunpy.org/en/stable/code_ref/net.html#classes

It would be good to convert these to explicit function signatures, to allow users to more easily understand what arguments each attribute takes. It looks like the function signatures themselves are fine, but somehow they are being modified when sphinx is documenting them during the doc build.

**Comment by dstansby** [comment]
Detective work on element has uncovered that this is because `DataAttr` has a `__new__(*args, **kwargs)`, which overrides the `__init__` signatures defined in the sub-classes.

**Comment by dstansby** [comment]
It looks like we can configure sphinx to use `__init__` as the main docstring instead of `__new__`: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration

(and pinging @Cadair since you said you were interested in the chat)

**Comment by ayshih** [comment]
Hmm, is the problem solely wth Sphinx?  What does `help()` return?
