### ISSUE TITLE
Investigate using sphinxcontrib-towncrier

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#4946]
https://github.com/sphinx-contrib/sphinxcontrib-towncrier

**Comment by ayshih** [comment]
Is this closed now by the use of `sphinx-changelog`?

**Comment by nabobalis** [comment]
Yeah, now we have a different one, no point in looking at that one.

**Comment by Cadair** [comment]
Yeah I investigated this and decided ours was better.
