### ISSUE TITLE
TestMap.test_save on Windows

### ISSUE THREAD

**Issue by segfaulthunter** [sunpy/sunpy#495]
test_save fails on Windows because the file is locked apparently.

self = <sunpy.tests.map.test_map_factory.TestMap instance at 0x09D277B0>

```
def test_save(self):
    #Test save out
    eitmap = sunpy.Map(a_fname)
    eitmap.save("eit_save.fits", filetype='fits', clobber=True)
    backin = sunpy.Map("eit_save.fits")
    assert isinstance(backin, sunpy.map.sources.EITMap)
```

> ```
>   os.remove("eit_save.fits")
> ```
> 
> E       WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'eit_save.fits'

**Comment by ayshih** [comment]
Closing this issue because this behavior results from memory mapping in the FITS reader of PyFITS/Astropy
