### ISSUE TITLE
New test images should show up in HTML figure test report

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4958]
In https://github.com/sunpy/sunpy/pull/4929 a new figure test image was added, but it didn't show up in the figure report: https://62929-2165383-gh.circle-artifacts.com/0/.tmp/py38-figure/figure_test_images/fig_comparison.html.

It would be good if new images showed up in the html report, so it's easy to check them. I suspect this needs to go upstream to `pytest-mpl`.

**Comment by ayshih** [comment]
It doesn't show up in the comparison report because the figure test passed the hash check.  For a successful hash check, `pytest-mpl` doesn't attempt to retrieve the baseline image, so it doesn't realize that the baseline image doesn't exist.

**Comment by Cadair** [comment]
I think this is part of what I started working on here: https://github.com/matplotlib/pytest-mpl/pull/108

**Comment by dstansby** [comment]
Ideally changed test images should show up too (as I noticed on https://github.com/sunpy/sunpy/pull/5019)
