### ISSUE TITLE
Bounds determination for `differential_rotate()` not quite correct

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4977]
The example that I created for https://github.com/sunpy/sunpy/issues/3323#issuecomment-777575463 suggests that the bounds determination for `differential_rotate()` is not quite correct.  Some data is getting clipped on the left, and there's too much padding on the right.

![download (2)](https://user-images.githubusercontent.com/991759/107733652-83c6c400-6cc9-11eb-8b02-79a61eae3cf9.png)
Generating code:
```python
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE
from sunpy.physics.differential_rotation import differential_rotate

m = sunpy.map.Map(AIA_171_IMAGE)

rectangle = SkyCoord([-700, -650]*u.arcsec, [0, 600]*u.arcsec, frame=m.coordinate_frame)
sm = m.submap(rectangle)

new_observer = m.observer_coordinate.replicate(obstime=m.date + 6*u.day)
dm = differential_rotate(sm, new_observer)

fig = plt.figure(figsize=(12, 4))

ax1 = fig.add_subplot(131, projection=m)
m.plot(vmin=0, vmax=5000, title='Full map')
m.draw_rectangle(rectangle, edgecolor='red', linewidth=2)

ax2 = fig.add_subplot(132, projection=sm)
sm.plot(vmin=0, vmax=5000, title='Submap')

ax3 = fig.add_subplot(133, projection=dm)
dm.plot(vmin=0, vmax=5000, title='Diffrot of submap by 6 days')
ax3.plot_coord(dm.center, '+', color='red', label='map center')
ax3.legend()

plt.show()
```

**Comment by jeffreypaul15** [comment]
What would be the idea observation in the case of ```differential_rotate``` after 6 days? If you don't mind, can I have a go at this issue?

**Comment by Cadair** [comment]
I am not sure this is a problem worth solving, at least not in the form the code is currently in. A much more useful investment of time would be to calculate what the correct output WCS is and then use reproject to do the warp. This is obviously a reasonably similar problem to the one the current algorithm solves, but presented in quite a different way (if my memory of the current code serves).

**Comment by ayshih** [comment]
@jeffreypaul15 I've fallen down a rabbit hole with current code.  I recommend keeping far away from this issue...
