### ISSUE TITLE
Fido client for EIS level 1 data

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5050]
### Description

The EIS team now provides level 1 (i.e. they have been run through `eis_prep`) data products here: https://eis.nrl.navy.mil/, with the directory of data products here: https://eis.nrl.navy.mil/level1/. They follow a fairly straightforward directory structure of `year/month/day/`, with each filename containing the year month day as well as the observation time. I think it should be pretty straightforward to write a scraper-based client to retrieve these based on date (every file contains both channels so there is no searching on wavelength).

A few things to consider:

* Based on my understanding, the VSO provides level 0 ("unprepped") files. From a Fido perspective, we would want to return data from a client based on the value of `attrs.Level`: if 0, use VSO; if 1, use this new client; if not specified, return both.
* The level 1 data are provided in both FITS and HDF5 format. The data provider for the level 1 data recommend using the HDF5 format, but we currently don't have a way to read HDF5 files in sunpy
* These data are 3D in space-space-wavelength. Even in FITS format, we do not currently have a way to read this type of data in sunpy. Should we be providing a way to retrieve data we don't have a way to read?

**Comment by nabobalis** [comment]
If the VSO provides L0, should we ask if they would provide the L1 data?

**Comment by wtbarnes** [comment]
We could. I think that will probably have to be a higher-level conversation between the VSO and NRL.

**Comment by dstansby** [comment]
In terms of reading the data, https://github.com/MSSLSolar/EISpy has very basic functionality to read the data into an NDCube.

**Comment by wtbarnes** [comment]
There is also software being produced by the NRL group to work with these data cubes that will have some NDCube integration I believe though it has not yet been released.

I guess the question is, whether this data comes from the VSO or if we write a scraper client, are we ok with retrieving data we can't read into a sunpy data structure? I remember this issue cropping up around the new GOES netCDF files as well.

**Comment by Cadair** [comment]
I think in this case I would be ok with it, Fido already returns a bunch o'data we can't read (for instance IRIS). My concern with the netCDF goes stuff was we actually had a ts class for it, but it didn't support the new data yet.

**Comment by Cadair** [comment]
The other option here is that the NRL EIS tools implement their own Fido source.

**Comment by dstansby** [comment]
@wtbarnes given https://github.com/USNavalResearchLaboratory/eispac/pull/31, should we close this?

**Comment by wtbarnes** [comment]
Yep! I forgot this was open.
