### ISSUE TITLE
Users Guide / TimeSeries / Plotting docs need to be updated regarding peek method

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#5058]
### Description
The docs reference `TimeSeries.peek()` method returning a figure when it really returns None

https://docs.sunpy.org/en/v2.1.2/guide/data_types/timeseries.html#plotting

> The SunPy TimeSeries object has its own built-in plot methods so that it is easy to quickly view your time series. To create a  plot just type:
>
> ```import sunpy.timeseries as ts
> import sunpy.data.sample
> ts_plot = ts.TimeSeries(sunpy.data.sample.GOES_XRS_TIMESERIES, source='XRS')
> fig = ts_plot.peek()
>```
>
>This will open a matplotlib plot on your screen. The peek method provides a view on data customised for each source while >plot provides a more general plot. **Note that peek returns a matplotlib.figure.Figure object**, if you want to save this to a PNG >file you can use the savefig method:
>`>>> fig.savefig('figure.png')`  
>In addition, to enable users to modify the plot it is possible to grab the matplotlib axes object by using the plot command. This makes it possible to use the SunPy plot as the foundation for a more complicated figure. For a more information about this and some examples see Plotting in SunPy.

### Expected vs Actual behaviour

Update the docs to use `.plot()`

**Comment by varunbankar** [comment]
Hi, I'll like to take up this issue.

**Comment by dstansby** [comment]
As dicsussed on the weekly call, this still needs fixing.
