### ISSUE TITLE
Proposal: Dependency Support Policy

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5075]
Having run an informal dependency support policy for a while which seems to be working I suggest we codify the following:

All runtime dependencies of the core package (optional or required) will be updated inline with NEP 29, which means we will support all non-bugfix releases made 24 months prior the scheduled release of sunpy.

With the following exceptions which the support window will be 12 months:

* astropy
* parfive
* drms

Thoughts?

**Comment by nabobalis** [comment]
I think there should be an exception for packages that went from <1 to >1 in that window.

**Comment by ayshih** [comment]
Can you clarify what is meant by "non-bugfix releases"?  If we were to release today, I presume we wouldn't support:

- Astropy 4.0 (2019 Dec 16), non-bugfix release outside of the 12-month window
- Astropy 4.0.4 (2020 Nov 25), a bugfix release within the window for a minor version outside of the window

If Astropy 4.1.1 existed, would we have to continue supporting Astropy 4.1?

**Comment by ayshih** [comment]
xref #3918

**Comment by Cadair** [comment]
bugfix releases are ignored, so the date is the first version in that series came out.

**Comment by ayshih** [comment]
So does that mean we need to support 4.1.0 if 4.1.1 exists?

**Comment by Cadair** [comment]
No, we just have to support something in that series, so we could pin to 4.1.1 if we need a bugfix.

**Comment by Cadair** [comment]
> I think there should be an exception for packages that went from <1 to >1 in that window.

I am not sure what you mean and I don't like it as version numbers are meaningless or have different meanings per project.

**Comment by nabobalis** [comment]
> > I think there should be an exception for packages that went from <1 to >1 in that window.
> 
> I am not sure what you mean and I don't like it as version numbers are meaningless or have different meanings per project.

Pandas went from 0.25.0 to 1.0.0 and officially have a stable API.

**Comment by Cadair** [comment]
I don't really think that's a good reason to bump the dep, unless there is some major headache from the version bump. Which we should probably special case in the policy.

**Comment by nabobalis** [comment]
Add DRMS to that list as well.

**Comment by Cadair** [comment]
12 months for parfive & drms is still a lot more restrictive than what we are currently running. Is this likely to be an issue?

**Comment by nabobalis** [comment]
I want to say no, my reason is that these two packages outside of astropy we tightly integrate into net (and the sample data). I don't think we want to support a wide range of drms or parfive due to that.

**Comment by dstansby** [comment]
If we're going to have a 12-month support window for astropy, when not make our lives easier and have a 12 (not 24) month window for everything else apart from `python`, on the basis that `numpy`, `matplotlib`, `scipy` etc. are as easy to upgrade as `astropy`?

**Comment by Cadair** [comment]
From discussion at the community meeting on 2021-05-19 there was general agreement that:

* We should baseline NEP 29's 24 months, as this means managed environments using this as a guide should be mostly fine.
* Astropy is much too much of a tight dependency to be supporting a version which is (up to) 3 years old, so we shall follow our current def facto standard of 12 months.
* Parfive and drms have a large asterisk next to them as they are packages we control and might need to bump (especially drms as it's so closely coupled to JSOC)

Sponsored affiliated packages will **support the sunpy LTS version at the time of their release**.

**Comment by Cadair** [comment]
Can someone write this up in the docs?

**Comment by nabobalis** [comment]
Will do.
