### ISSUE TITLE
Add an example to the gallery of selecting pixels in a map based on a coordinate transform

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5095]
Extracting the pixel values of a region of interest defined by a box in some world coordinate space is quite a common operation. A simple example would be extracting a region of interest in HGS coordinates:

```python
import numpy as np
import astropy.units as u

import sunpy.map
from sunpy.data.sample import AIA_171_ROLL_IMAGE

smap = sunpy.map.Map(AIA_171_ROLL_IMAGE)

all_hpc = sunpy.map.all_coordinates_from_map(smap)
all_hgs = all_hpc.transform_to("heliographic_stonyhurst")

segment = np.logical_and(all_hgs.lon<10*u.deg, all_hgs.lon>0*u.deg).nonzero()
smap.data[segment] = 0
smap.peek()
```

This can be extended to more exotic transformations by using `NorthOffsetFrame` (for example the second half of [this](https://gist.github.com/Cadair/494b1d7026918cd97c57c21def52fc31) old notebook) or the newer `RotatedSunFrame`.

A good example would show off a few of these options and also present a couple of things to do with the extracted mask, for example, plotting the mask, averaging the pixel values in the mask etc.

**Comment by jeffreypaul15** [comment]
Is anyone giving this a shot? If not I could do it.

**Comment by nabobalis** [comment]
Go ahead.
