### ISSUE TITLE
Update "Masking out the solar disk" example to use maputils function

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5112]
Example: https://docs.sunpy.org/en/stable/generated/gallery/computer_vision_techniques/mask_disk.html

Update to use `sunpy.map.coordinate_is_on_solar_disk()`

**Comment by Qtty** [comment]
Hi, by saying ```Update to use sunpy.map.coordinate_is_on_solar_disk()```, do you mean remove the usage of ```sunpy.map.all_coordinates_from_map``` or use ```sunpy.map.coordinate_is_on_solar_disk()``` instead of the mask?

**Comment by ayshih** [comment]
Basically, replace the calculations to calculate the mask.  See this other example:
https://github.com/sunpy/sunpy/blob/164f57c41c6840d568dbfb211d38aa1ae83aaf65/examples/plotting/hmi_cutout.py#L35-L37
