### ISSUE TITLE
Add a rigid rotation model to the `diff_rot()`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5123]
I think it'd be useful to provide a rigid rotation model to `sunpy.physics.differential_rotation.diff_rot()`.  While, strictly speaking, it wouldn't have any differential rotation, it would allow a user to use the same machinery (e.g., `RotatedSunFrame`) with and without differential rotation to see what the differences are.  The sidereal rotation rate is available at `sunpy.sun.contants.sidereal_rotation_rate`.

**Comment by asinghgaba** [comment]
Hi 👋 I would be able to work on it, just so I understand it properly, we want to add an extra rotation type `rot_type`, namely `"rigid"`, which would calculate the longitude by:
Longitude = sidereal_rotation_rate * duration (After converting to suitable units)

**Comment by dstansby** [comment]
Hi @asinghgaba that's right - looking at the code it seems like it should be fairly easy to add another entry to `rot_params` that has an appropriate value for the first entry, and zero values for the second two. Let us know if you have any other questions!
