### ISSUE TITLE
Document `QueryResponseTable.__init__

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5137]
There is no documentation for `QueryResponseTable.__init__` (https://docs.sunpy.org/en/latest/api/sunpy.net.base_client.QueryResponseTable.html#sunpy.net.base_client.QueryResponseTable). It would be good to add some.

**Comment by Cadair** [comment]
Why does that not inherit the docstring of its parent class? There is no behaviour change in the constructor (only an astropy backport), so I expected the inherited docstring to work.

**Comment by ConorMacBride** [comment]
The inherited `__init__` method doesn't currently have a docstring, although I think you mean `QueryResponseTable.__doc__` is missing, not `QueryResponseTable.__init__.__doc__`. Should I add the following code to the top of `QueryResponseTable` to manually inherit the docstring?

```py
class QueryResponseTable(QTable):
    __doc__ = QTable.__doc__

    ...
```
That should mean that the top of https://docs.sunpy.org/en/latest/api/sunpy.net.base_client.QueryResponseTable.html contains the same text as https://docs.astropy.org/en/stable/api/astropy.table.QTable.html.

**Comment by nabobalis** [comment]
Worth a shot.

**Comment by ConorMacBride** [comment]
I opened a pull request. I guess we can't test this until documentation builds are working again, but I printed `QueryResponseTable.__doc__` before and after the update and it seems to work as expected.
