### ISSUE TITLE
Failed or interrupted downloads leave incomplete files on disk

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5139]
### Description

When downloading data with `Fido`, downloads that fail or downloads that are interrupted by the user are left as half-downloaded files. This is inconvenient, as it means one has to go through and manually delete any half-downloaded files before running a `Fido` download again, as `Fido` will see the filename and think that a file has been downloaded.

It would be good if files could be removed if they are not completely downloaded when a download is interrupted or fails.

**Comment by Cadair** [comment]
This is really a parfive bug.

**Comment by dstansby** [comment]
Reported upstream at https://github.com/Cadair/parfive/issues/67
