### ISSUE TITLE
SXTMap requires test data and tests.

### ISSUE THREAD

**Issue by jeffreypaul15** [sunpy/sunpy#5140]
### Description
Based on #3440 and the PR #2056, we don't have SXTMap data. 
Although `Map.quicklook()` bugs out, the map can be plotted by `Map.plot()`.
Tests for this file are to be added.
The map's`wavelength` is also in `str` and `GenericMap` handles `wavelnth` in `Quantity`

**Comment by jeffreypaul15** [comment]
@nabobalis the SXT's `wavelength` is in str and is `Al.1`, should this be defaulted as `0`?
All other sources have separate quantities as wavelength.

**Comment by nabobalis** [comment]
Not sure.

**Comment by ayshih** [comment]
As @wafels noted on Element, SXT takes images with different filters, with two of the filters being different thicknesses of aluminum (hence, "Al").  It'd be unclear how to convert each the filter to a quantified wavelength.  If you don't have a really good understanding of SXT data, stay away from trying to fix `SXTMap`.

**Comment by wafels** [comment]
Just so we have a note of it, information on SXT and Yohkoh can be found at http://ylstone.physics.montana.edu/ylegacy/mission_cal_papers.html
