### ISSUE TITLE
Heliocentric cylindrical returns nan for off-disk coordinates

### ISSUE THREAD

**Issue by 5tefan** [sunpy/sunpy#5153]
### Description

Heliocentric cylindrical returns nan for off-disk coordinates.

### Expected vs Actual behavior

Conversion of off-disk coordinate from Helioprojective Cartesian to Heliocentric cylindrical produces nan. Heliocentric cylindrical should be valid off-disk.

### Steps to Reproduce

```python
from sunpy.coordinates.frames import Helioprojective, Heliocentric
import astropy.units as u

hpc = Helioprojective(1254.0*u.arcsec, -448.9*u.arcsec, observer="earth", obstime="2021-03-01")
hpc.transform_to(Heliocentric(observer="earth", obstime="2021-03-01")).cylindrical

# <CylindricalRepresentation (rho, phi, z) in (AU, deg, AU)
#    (nan, nan, nan)>
```

### System Details

- SunPy Version: 2.0.1
- Astropy Version: 4.0.1.post1
- Python Version: 3.7.0
- OS information: Mac OS X 10.14

**Comment by 5tefan** [comment]
Adding @cbethge to discussion.

I thought about this a little more... maybe it makes some sense because there's ambiguity about the z value when off disk?

**Comment by 5tefan** [comment]
@ayshih we came across this following your suggestion in https://github.com/sunpy/sunpy/issues/5115#issuecomment-802533913 to use the coordinate transform framework to calculate rtheta rather than something like `np.hypot(x, y)`. Is there a way to, say, impose z=0 for points off disk so that we can still get a rho and phi using the framework?

Maybe we just have to inspect the cylindrical coordinates and fall back to `np.hypot(x, y)` after the transform if we find nans in the result?

**Comment by ayshih** [comment]
You can use [`Helioprojective.assume_spherical_screen()`](https://docs.sunpy.org/en/stable/api/sunpy.coordinates.Helioprojective.html#sunpy.coordinates.Helioprojective.assume_spherical_screen).  Let me know if you have any questions.

**Comment by 5tefan** [comment]
Oh wow, I think that's exactly what we're looking for, thanks!! Sorry for the noise. 

In case anyone is referencing this in the future, it looks like `assume_spherical_screen` is a new addition to sunpy, so we're also considering using `sunpy.coordinates.sun.earth_distance` as the distance argument for for the Helioprojective frame, to get slightly (negligible in our case) less accurate values.
