### ISSUE TITLE
Map mutates input WCS

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5165]
When creating a `Map` using `Map(array, wcs)`, the input `wcs` does not evaluate equal to the resulting `map.wcs` object. See below for an example - this is contrived to be simple, but is an issue when doing reprojection, when one wants to force two maps to have the same `wcs` so you can plot them one on top of the other.

```python
import sunpy.data.sample
import sunpy.map

map_aia = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
map_hmi = sunpy.map.Map(sunpy.data.sample.HMI_LOS_IMAGE)

map_aia = sunpy.map.Map(map_aia.data, map_hmi.wcs)
# This prints False
print(map_aia.wcs == map_hmi.wcs)
```

**Comment by Cadair** [comment]
Correct, the input WCS is converted to a header and then read through the normal map property -> WCS pipe. There almost certainly isn't a fix for this which isn't rewrite most of maps metadata handling ;)

**Comment by Cadair** [comment]
The most general way to assert if two WCS objects are equal is to run a sample of pixel locations through a pixel-world-pixel round trip and see if the output's match.

**Comment by dstansby** [comment]
I think this is probably just a floating point accuracy error since `dsun_obs` is going back and forth through at least one transformation, with a bit more digging I think this should be fixable.

**Comment by dstansby** [comment]
Here's a smaller example, showing the issue:
```python
import sunpy.data.sample
import sunpy.map

map_hmi = sunpy.map.Map(sunpy.data.sample.HMI_LOS_IMAGE)
print("{:.20f}".format(map_hmi.meta['dsun_obs']))
print("{:.20f}".format(map_hmi.wcs.wcs.aux.dsun_obs))
```
This prints:
```
151846023892.98999023437500000000
151846023892.99002075195312500000
```
ie. the two values are slightly different. I think this is because of small changes in a `HGS` > `HGC` transformation that takes place in `GenericMap.observer_coordinate`, which is used to populate the wcs keywords.

**Comment by ayshih** [comment]
> This prints:
> 
> ```
> 151846023892.98999023437500000000
> 151846023892.99002075195312500000
> ```

This slight difference (~30 microns) is the machine epsilon for IEEE-754 64-bit floats (2^-52, or 2.22e-16):

```python
>>> import numpy as np
>>> np.finfo(float).eps
2.220446049250313e-16
>>> (map_hmi.observer_coordinate.radius * np.finfo(float).eps).to('micron')
<Distance 33.71659038 micron>
```

Even the most trivial handling of floats – even multiplying by 1 – can lead to a shift at the epsilon level.

**Comment by dstansby** [comment]
I'm going to close this as won'tfix.
