### ISSUE TITLE
`make_fitswcs_header` doesn't create a `rsun_obs` keyword

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5171]
### Description
when using `make_fitswcs_header`, the `rsun_obs` keyword is no longer populated - removed in #4620.
This also makes the [`get_observer_meta()` ](https://github.com/sunpy/sunpy/blob/master/sunpy/map/header_helper.py#L199) redundant.

This is really not too much of an issue, but when you create a map from this, and then use `map.draw_limb()` it raises a warning as it calculates the `rsun_obs` assuming photospheric limb. 

However we should probably have it such that `rsun_obs` is populated with `make_fitswcs_header`, maybe to a similar way to  it was done in [`get_observer_meta()` ](https://github.com/sunpy/sunpy/blob/master/sunpy/map/header_helper.py#L199)?

**Comment by ayshih** [comment]
> This is really not too much of an issue, but when you create a map from this, and then use `map.draw_limb()` it raises a warning as it calculates the `rsun_obs` assuming photospheric limb.

#5172 should prevent this warning.

Even so, it might be useful for the helper to create the `rsun_obs` keyword explicitly.

**Comment by jeffreypaul15** [comment]
Would this require writing a helper to populate the `rsun_obs` keyword?

**Comment by Cadair** [comment]
Can this be closed?
