### ISSUE TITLE
Add an `angular_radius` convenience property to `Helioprojective`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5182]
We keep calculating the solar angular radius in various places (e.g., #5177), when we're invariably working with a `Helioprojective` coordinate.  Let's just add a convenience property to `Helioprojective` itself, since it already has all of the information it needs to calculate the solar angular radius.  This would be a natural way to replace `sunpy.map.maputils.solar_angular_radius()` as well (see #4516)

**Comment by Anubhav1107** [comment]
hey @ayshih, I was looking over this issue and is there a python file with helioprojective beacuse I am not able to find it !

**Comment by nabobalis** [comment]
Albert will correct if I am wrong but I believe it is this one: https://github.com/sunpy/sunpy/blob/master/sunpy/coordinates/frames.py#L380

**Comment by Anubhav1107** [comment]
hey @ayshih , can you take a look. If I understand, the task was to put a angular_radius function in HelioProjective.
