### ISSUE TITLE
Cannot run PyInstaller executables importing SunPy

### ISSUE THREAD

**Issue by taradrop** [sunpy/sunpy#5207]
Tested with the simple script 
```
from sunpy.coordinates.sun import earth_distance
print(earth_distance())
```
then did `pyinstaller test1.py` and it finished successfully. But starting executable I got the following:
```
Traceback (most recent call last):
  File "test1.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "sunpy/__init__.py", line 51, in <module>
  File "sunpy/__init__.py", line 41, in _get_bibtex
FileNotFoundError: [Errno 2] No such file or directory: '/home/yakob/projects/sdc/grisview.dist/tmp/dist/test1/sunpy/CITATION.rst'
[138952] Failed to execute script test1
```
Checking astropy and sunpy folders in PyInstaller dist folder, looks like sunpy is really missing files (there is only `io` folder). Copying `CITATION.rst` to the folder leads to another missing file error. Tested scripts using AstroPy and they work well with PyInstaller. Done on a 'clean' venv environment (and conda' one as well).
Python 3.8.5
AstroPy 4.2.1
SunPy 2.1.4
OS: Kubuntu 20.04

**Comment by Cadair** [comment]
Hey @taradrop thanks for opening an issue.

While I think it would be pretty easy to patch over this specific error, it appears to be a symptom of a more worrying issue which is that pyinstaller seems to not be copying the package data. This will probably cause a few less obvious things to break deeper in sunpy.

I know astropy did a fair bit of work to support pyinstaller, and added some tests to their CI to keep it working. I think it would be great for someone to do this for sunpy as well. If you are interested in doing this I would be more than happy to help you.

It seems that astropy has a reasonably complex test hook to run the tests inside a pyinstaller build:
https://github.com/astropy/astropy/blob/main/.pyinstaller/run_astropy_tests.py

Also it looks like pyinstaller has a hook for astropy: https://github.com/pyinstaller/pyinstaller/pull/4274/files

I think this probably will require a little work and a decent amount of understanding of pyinstaller that I don't have. It's possible someone from astropy could give us some advice if we get stuck.

**Comment by jeffreypaul15** [comment]
> Hey @taradrop thanks for opening an issue.
> 
> While I think it would be pretty easy to patch over this specific error, it appears to be a symptom of a more worrying issue which is that pyinstaller seems to not be copying the package data. This will probably cause a few less obvious things to break deeper in sunpy.
> 
> I know astropy did a fair bit of work to support pyinstaller, and added some tests to their CI to keep it working. I think it would be great for someone to do this for sunpy as well. If you are interested in doing this I would be more than happy to help you.
> 
> It seems that astropy has a reasonably complex test hook to run the tests inside a pyinstaller build:
> https://github.com/astropy/astropy/blob/main/.pyinstaller/run_astropy_tests.py
> 
> Also it looks like pyinstaller has a hook for astropy: https://github.com/pyinstaller/pyinstaller/pull/4274/files
> 
> I think this probably will require a little work and a decent amount of understanding of pyinstaller that I don't have. It's possible someone from astropy could give us some advice if we get stuck.

Would adding a hook for sunpy with all the hidden imports and non python files to PyInstaller be enough?

**Comment by Cadair** [comment]
I don't know, but looks likely.

**Comment by jeffreypaul15** [comment]
> I don't know, but looks likely.

I wrote a hook very similar to that of astropy's and ran it locally, it seems to be working fine with a few tests I ran.

**Comment by Cadair** [comment]
A PR with the hook and a suitable test script for the CI would be great. :rocket:

**Comment by jeffreypaul15** [comment]
> A PR with the hook and a suitable test script for the CI would be great. 🚀

The hook belongs to PyInstaller though, how would the PR be need to be made?

**Comment by Cadair** [comment]
Can you not define local hooks? Of course adding support upstream would be great as well.

**Comment by jeffreypaul15** [comment]
> Can you not define local hooks? Of course adding support upstream would be great as well.

Hooks can be added locally but I'm a bit confused on how we want the test script to be structured. Are you familiar with how Astropy's 
https://github.com/astropy/astropy/blob/b23aa47a613ce1e08ef6e7aa60dc1e9480d1d292/.pyinstaller/run_astropy_tests.py
is written?
