### ISSUE TITLE
Add a `warn_sunpy` function

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5218]
Whenever I'm adding warnings, I tend to forget to add `SunpyUserWarning` as the type, and I'm not the only one: https://github.com/sunpy/sunpy/pull/5211#discussion_r614787587

It would be nice to

- [ ] Add a `_warn_user()` function to `sunpy/util/exceptions.py` that takes a single message and emits a `SunpyUserWarning`, at an appropriate stacklevel.
- [ ] Replace all calls to `warnings.warn` with this in the main library. 
- [ ] Set up linting to raise an error if `warnings.warn` is used anywhere apart from `sunpy.util.exceptions` (this might be tricky?)

**Comment by ayshih** [comment]
> I'm not the only one

Heh, to be fair, in that PR all I did was relocate code that _you_ wrote (#4620).  So, it wasn't so much my forgetting as my not noticing your forgetting. =)

**Comment by dstansby** [comment]
🤦 apologies!

**Comment by samriddhi-dev** [comment]
Is this done? Or can I take a try in it?
