### ISSUE TITLE
Stable docs pointing to unstable version

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5225]
https://docs.sunpy.org/en/stable/ appears to have a development version number (see top left in the sidebar). It should have a stable version number.

**Comment by nabobalis** [comment]
I would wager that somehow the repo was changed on RTD causing the version number to error. 
Probably introduced somehow during the changelog update.

**Comment by dstansby** [comment]
Interestingly astropy seem to have the same issue: https://docs.astropy.org/en/stable/

**Comment by astrojuanlu** [comment]
Some comments from the chat:

- Unclear what version of `setuptools_scm` is being used, pip does not log it apparently
- Looks like the problem is older also for untagged versions, see for example https://sunpy--4178.org.readthedocs.build/en/4178/, dirty (https://github.com/sunpy/sunpy/pull/4178)
- However, other old PRs do not exhibit the behavior, see for example https://sunpy--4340.org.readthedocs.build/en/4340/, clean (https://github.com/sunpy/sunpy/pull/4340)

**Comment by astrojuanlu** [comment]
Refined the bisection.

- https://github.com/sunpy/sunpy/pull/5155/commits/fcf661c70a431831514fabc4ad5cb13e7579d498 March 30th, non dirty
- https://github.com/sunpy/sunpy/pull/5161/commits/ab2300e23cdf0ef820269d524358451ca92348f5 March 31st, dirty

Tuesdays are when RTD does deploys, so it's possible that https://docs.readthedocs.io/en/stable/changelog.html#version-5-13-0 affected the result.

**Comment by astrojuanlu** [comment]
Long story short: on March 30th the `CONDA_APPEND_CORE_REQUIREMENTS` feature flag became enabled for all projects on Read the Docs, and that causes a change in `rtd-environment.yml` which is taken by `setuptools_scm` as a dirty checkout.

With the information we have so far, this should be affecting all projects using conda and `setuptools_scm`. Therefore, unless we discover something that invalidates this, there are two things you can do:

1. Find a setuptools_scm configuration that ignores the "dirty" changes. I acknowledge that this might pose a problem if you're relying on that to avoid making dirty releases or similar.
2. Open an issue on https://github.com/readthedocs/readthedocs.org/issues/ to discuss how to disable this flag for certain projects. We would need to discuss the implications and put it somewhere in our roadmap, which might (or might not) take some time.

**Comment by nabobalis** [comment]
Would git ignoring that file be enough?

**Comment by astrojuanlu** [comment]
I just tested locally with https://github.com/astrojuanlu/sunpy/commit/6fdd9306f9e13a0c58b681e07c15e134af6b115c, and it doesn't work. The reason being: `rtd-environment.yml` is already checked in the repository, therefore `.gitignore` doesn't seem to have an effect.

```
juanlu@arion2:/tmp/git_test$ git status
On branch main
nothing to commit, working tree clean
juanlu@arion2:/tmp/git_test$ cat README 
test
juanlu@arion2:/tmp/git_test$ echo "README" > .gitignore
juanlu@arion2:/tmp/git_test$ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

nothing added to commit but untracked files present (use "git add" to track)
juanlu@arion2:/tmp/git_test$ echo "ZZZZZZZZZ" >> README
juanlu@arion2:/tmp/git_test$ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by dstansby** [comment]
I think we fixed this (at least in sunpy) with https://github.com/sunpy/sunpy/pull/5603
