### ISSUE TITLE
Prefer `Fido.search(a1 & a2)` to `Fido.search(a1, a2)` in docs?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5226]
As far as I know `Fido.search(a1, a2)` will implicitly combine all the attribute arguments using the `&` operator. I think it would be clearer if we used `Fido.search(a1 & a2)` in the docs instead, as this is more explicit, and conveys the concept of combining different attributes in a single search.

**Comment by Cadair** [comment]
The main reasons for not doing this are:

a) Operator precedence. The comma is a nice way to avoid brakes and increase legibility when mixing and's and or's.
b) Line breaks, line breaks after commas is very common. Line breaks after binary operators are less common and I find a little less legible. It would be worth considering the style we want to use if we decide to go with this: https://pep8.org/#break-before-or-after-binary-operator

**Comment by dstansby** [comment]
> a) Operator precedence. The comma is a nice way to avoid brakes and increase legibility when mixing and's and or's.

What do you mean by this, Can you give an example? I would have thought it was much clearer to use only binary operators instead of mixing them with commas.

> b) Line breaks, line breaks after commas is very common. Line breaks after binary operators are less common and I find a little less legible. It would be worth considering the style we want to use if we decide to go with this: https://pep8.org/#break-before-or-after-binary-operator

Do you think this outweighs the (substantial in my opinion) legibility improvement in explicitly using `&` instead of implicitly using `,` to mean `&`?

**Comment by Cadair** [comment]
> > a) Operator precedence. The comma is a nice way to avoid brakes and increase legibility when mixing and's and or's.
> 
> What do you mean by this, Can you give an example? I would have thought it was much clearer to use only binary operators instead of mixing them with commas.

A simple example is
```
Fido.search(a.Time(...), a.Instrument.aia | a.Instrument.hmi)
```
vs
```
Fido.search(a.Time(...) & (a.Instrument.aia | a.Instrument.hmi))
```

If you start nesting operators, it can get uglier.

In general, I think that both have their place. I also think that it's pretty intuitive to use the comma, I personally don't think the implicit `AND` is a large leap, `a.Time(), a.Instrument()` is hopefully obviously *not* an `OR`!

With regards to line breaks, I am happy to do it as long as all the examples adopt a consistent style, and preferably we use that style in the codebase as well.

**Comment by dstansby** [comment]
I think using the extra brackets helps readability 😆 

And `a.Time(), a.Instrument()` is probably obviously an AND, but what about `a.Time(), a.Time()`, where the two times have overlapping time ranges?

**Comment by dstansby** [comment]
I think we should probably solicit some other opinions at a future dev meeting.

**Comment by Cadair** [comment]
I don't think you can AND two Times together? it will just error?

**Comment by dstansby** [comment]
Indeed, it does:
```python
  File "/Users/dstansby/github/sunpy/test.py", line 3, in <module>
    res = Fido.search((a.Time('2020-01-01', '2020-01-01 00:00:10') & a.Time('2020-01-03', '2020-01-03 00:00:10')) &
TypeError: unsupported operand type(s) for &: 'Time' and 'Time'
```

I'm only +0.5 on doing this, so I'll close.
