### ISSUE TITLE
Allow for pixel input to `GenericMap.draw_quadrangle()`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5231]
`GenericMap.draw_quadrangle()` currently accepts only angular input.  We can have it accept pixel input, which would (by default) plot a rectangle on the pixel grid.

**Comment by Cadair** [comment]
If the units were in pixel the `vertex_unit` kwarg to `Quadrangle` should be `u.pix` and the `transform` argument should by default be empty.

**Comment by ayshih** [comment]
Wouldn't `transform` still need to be a "pixel"->"data" transform?

**Comment by Cadair** [comment]
WCSAxes is in pixel space by default, so I think that's the default if you don't specify one?

**Comment by jeffreypaul15** [comment]
@ayshih Skycoord can't accept `pix` as a unit right,  would the `bottom_left` coordinate have to be defined in pixels as well?

**Comment by Cadair** [comment]
Yes, rather than using a SkyCoord the pixel coordinates would be passed as Quantity objects with units of pix. There is prior art for this in the submap method if you want to use that.

**Comment by jeffreypaul15** [comment]
> Yes, rather than using a SkyCoord the pixel coordinates would be passed as Quantity objects with units of pix. There is prior art for this in the submap method if you want to use that.

Can I work on this if nobody else is?

**Comment by nabobalis** [comment]
Sure.
