### ISSUE TITLE
Map HTML repr crashes when data array is a Dask array

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5234]
If your map is backed by a Dask array (which `Map` does *nominally* support), the nifty HTML repr freaks out.

```python
import sunpy.data.sample
import sunpy.map
import dask.array
m = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
m_dask = sunpy.map.Map(dask.array.from_array(m.data),m.meta)
m_dask._repr_html_()
```

gives

```python traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-89689641455e> in <module>
----> 1 m_dask._repr_html_()

~/Documents/codes/sunpy/sunpy/map/mapbase.py in _repr_html_(self)
    356             FigureCanvasBase(fig)
    357         ax = fig.subplots()
--> 358         values, bins, patches = ax.hist(finite_data.ravel(), bins=100)
    359         norm_centers = norm(0.5 * (bins[:-1] + bins[1:])).data
    360         for c, p in zip(norm_centers, patches):

~/miniconda3/envs/sunpy-dev/lib/python3.8/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1445     def inner(ax, *args, data=None, **kwargs):
   1446         if data is None:
-> 1447             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1448
   1449         bound = new_sig.bind(ax, *args, **kwargs)

~/miniconda3/envs/sunpy-dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   6569
   6570         # Massage 'x' for processing.
-> 6571         x = cbook._reshape_2D(x, 'x')
   6572         nx = len(x)  # number of datasets
   6573

~/miniconda3/envs/sunpy-dev/lib/python3.8/site-packages/matplotlib/cbook/__init__.py in _reshape_2D(X, name)
   1373
   1374     # Iterate over list of iterables.
-> 1375     if len(X) == 0:
   1376         return [[]]
   1377

TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by ayshih** [comment]
It seems that `Axes.hist()` behaves really badly on `dask` arrays

**Comment by wtbarnes** [comment]
Potential bandaid:
```python
if isinstance(finite_data, dask.array.Array):
    finite_data = finite_data.compute()
```
The data has to be pulled into memory anyway to be plotted.

**Comment by ayshih** [comment]
Yup, that'd be the easiest short-term fix.  The question to ponder for long term is whether we'd want `_repr_html_()` to do something different (i.e., less) for `dask` arrays since triggering a full computation for just a representation somewhat defeats the purpose of using `dask`.

**Comment by sunilk747** [comment]
Hello Guys @ayshih @wtbarnes .  I am new to this repository and looking for a good first issue to contribute. If no one is working on this issue can I go ahead a submit a PR for this one.

**Comment by Cadair** [comment]
Why don't we use the really nice dask html repr as part of our html repr?

**Comment by wtbarnes** [comment]
> Why don't we use the really nice dask html repr as part of our html repr?

Yes, I think that makes the most sense. Unfortunately, by not bringing the array into memory, we lose a lot of the nice quicklook stuff that is included in the repr. 

Going this route, I think it would make the most sense to just have the metadata table and then the dask repr on the right and suppress the imshow plot and the histogram.

**Comment by ayshih** [comment]
If we go this route, I'm inclined to break the equivalence of the HTML repr and the output of `.quicklook()`.  I think a user explicitly calling `.quicklook()` should always get the plot and histogram.

**Comment by warussel** [comment]
Hey folks @wtbarnes @ayshih is this issue still in need of a fix? If so, is anybody currently working on a PR or could I submit one? This looks like a decent bug for me to tackle but I see that it has not been addressed in a long time.

**Comment by nabobalis** [comment]
I would suggest starting off in checking it still is an issue. If it still is, you can work on it if you want.

**Comment by wtbarnes** [comment]
Sure go ahead. I do not believe anyone is working on this at the moment.

I think the most sensible route is to follow @ayshih's suggestion of splitting up the HTML repr and the quicklook method and have the HTML repr show the Dask array html summary and the quicklook method pull the array into memory and plot it.

**Comment by warussel** [comment]
After some initial testing, looks like the error does still occur in my dev environment. 

For splitting up the html_repr() and quicklook() behavior, the most straightforward solution I can think of would be to pass a flag in to the html_repr() method. If set, pull the array into memory, otherwise use the dask html repr. Would this be good practice or is there another solution that I should consider? 

Something like 
`html_repr(self, compute_dask=false)`
