### ISSUE TITLE
Add ability to draw limb with just an observer coordinate

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5253]
https://github.com/sunpy/sunpy/pull/5237 has updated `GenericMap.draw_limb()` to now work "across" maps, but still requires one to have a `GenericMap` to draw the limb. In some cases it would be nice to be able to draw the limb on a map from only a given observer coordinate and not a full map. The use case I have for this is drawing one or more limbs on synoptic maps.

I am imagining an API that looks something like
```python
sunpy.visualization.plot_limb(axes, observer, rsun=None)
```

This can contain most of the limb drawing logic, which can be moved from `GenericMap.draw_limb()`.

**Comment by jeffreypaul15** [comment]
Wouldn't the limb have to be plotted on a default map though regardless of the coordinate? Can I work on this?

**Comment by dstansby** [comment]
Yes, you need a pre-existing `WCSAxes` that would be the `axes` argument in my original post. This is free to work on, but the code in `draw_limb()` is quite complicated, and it will be tricky to work out exactly what bits need to be extracted and which bits need to stay, so I'd perhaps recommend working on another issue.
