### ISSUE TITLE
Add total file size to Fido search results

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5282]
The `sunpy_soar` solar orbiter client (and I think possibly `drms`?) returns filesizes as one of the columns. This means it is theoretically possible to sum all the filesizes of a single search up, and tell the user what the total size is. This is probably quite a tricky issue, and will require good knowledge of the internals of `sunpy.net`.

**Comment by jeffreypaul15** [comment]
Wouldn't it be easier to add the total filesize from `sunpy_soar`?

**Comment by Cadair** [comment]
VSO also returns size, although not all providers populate it and I am pretty sure some are outrightly wrong. We could definately do this, but it would need to be described as "estimated size" or something.

I think it would be good to combine an estimate from each provider (which supports it) with a global estimate on the `UnifiedResponse` object. The latter part being the one which would need more standarisation.
