### ISSUE TITLE
Move solar angular radius assumption from `warning` to `log.debug`?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5285]
The following warning comes up a few times in our docs:
```python
SunpyUserWarning: Missing metadata for solar angular radius: assuming the standard radius of the photosphere as seen from the observer distance.
```
I think making this assumption is a very reasonable thing to do, and there is no standard (as far as I can tell?) that requires FITS files to contain this metadata. So I would like to propose moving it from a warning (shown by default) to a log at the DEBUG level (not shown by default, but the user can turn it on).

Thoughts?

**Comment by Cadair** [comment]
I don't see an issue with this. I assume this is just coming out of map?

**Comment by dstansby** [comment]
Yes, it's here: https://github.com/sunpy/sunpy/blob/0f93b5583dbb64e09a60d13aa60e3bc4e99330e5/sunpy/map/mapbase.py#L954-L956
