### ISSUE TITLE
Some Map methods incorrectly re-define the reference pixel/coordinate

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5289]
The reference pixel/coordinate of a Map is intimately tied to the WCS projection.  Switching from one pixel/coordinate to another pixel/coordinate will change the pixel->world mapping for the rest of the pixels in nearly all situations.  Both `GenericMap.resample()` and `GenericMap.superpixel()` re-define the reference pixel/coordinate to be the center of the Map.  This should not be done.  Instead, the new pixel location for the original reference coordinate should be calculated.  That is, `CRVAL1/2` should be preserved, and only `CRPIX1/2` should be changed.

There may be other places in our codebase that also make the same mistake.

(Incidentally, WCS FITS does have the capacity to decouple the reference coordinate from being the origin of the projection through `PVi_1`/`PVi_2` keywords, but I don't know if anyone actually uses those.  See [Section 2.5 of Calabretta and Greisen 2002](https://www.aanda.org/articles/aa/pdf/2002/45/aah3860.pdf#page=4).)

**Comment by jeffreypaul15** [comment]
Correct me if I'm wrong, but should `crval1` and `crval2` in these two methods be the same as the original map?

**Comment by Cadair** [comment]
Yes. CRPIX is the pixel location of the reference pixel, and CRVAL is the coordinate of the reference pixel in the coordinate system described by the WCS. So What needs to happen is that CRVAL shouldn't change but CRPIX should change (even if it references a pixel out of the actual array) so that the coordinates are correct.

**Comment by jeffreypaul15** [comment]
So changing this line :
https://github.com/sunpy/sunpy/blob/e99c7db009f990bfc93dd11b451db9669d862cda/sunpy/map/mapbase.py#L1419
to 
```python
new_meta['crval1'] = self.meta['crval1`]
new_meta['crval2'] = self.meta['crval2`]
``` 
Should work right? Atleast for `GenericMap.resample()`?

**Comment by dstansby** [comment]
I suspect `GenericMap.rotate()` might need the same treatment too.

**Comment by ayshih** [comment]
> I suspect `GenericMap.rotate()` might need the same treatment too.

To my checking, both `submap()` and `rotate()` are fine.

**Comment by ayshih** [comment]
@jeffreypaul15 You simply need to remove those lines because the CRVAL values are already copied.  That fixes CRVAL, but doesn't fix CRPIX.  The non-trivial effort is to correctly calculate the new CRPIX values.
