### ISSUE TITLE
EVE data as a specific case of how SunPy assigns datatypes to instrument data products

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#531]
There are  different flavours of EVE data - they are not all 1-d time-series data. The table of data products is here

http://lasp.colorado.edu/home/eve/data/

and we currently support only the top entry in this table. There are spectra as well. The fact that one instrument can create many different SunPy datatypes might be better handled by a higher level object that returns the required datatype. At the moment we assume that all EVE data are time-series. It would be better if an EVE object returned the correct datatype, rather than having to specify the datatype at the outset. For example, something like

data = sunpy.instrument.eve.get_data('2012/04/16', level='0CS')

would return a lightcurve object via existing functionality, but

data = sunpy.instrument.eve.get_data('2012/04/16', level='2-spectra')

would return a spectrum object (I think this data might actually be a time-series of spectral objects, but you get the picture).

If you are looking for a use case of an overarching data object, then the panoply of EVE data products gives you that.  This issue was originally raised in an extended comment on issue #530 and I thought it would be worthwhile excising it into a separate issue.

**Comment by agneet42** [comment]
@wafels, here do we want to check the `level` and then return the corresponding object of the same(Presently, only [this](https://github.com/sunpy/sunpy/blob/master/sunpy/lightcurve/sources/eve.py#L23) is dealt with) ? Also, what would be returned if the level is `3-merged` , for example?

**Comment by nabobalis** [comment]
If lightcurve is dead, does this need to be open? Does it affect time series?

Should I add a timeseries label?

**Comment by Cadair** [comment]
This is handled at  a lower level by Fido + timeseries, but the high level functionality is not provided. @wafels opinions?

**Comment by Cadair** [comment]
Is this now fixed on the net side? I thought we have the ability to differentiate between these types of data now?

**Comment by dstansby** [comment]
Is the action here to discourage use of `sunpy.instr.eve` via. warnings, and direct them to Fido?

**Comment by nabobalis** [comment]
I would guess so. But since we are planning to remove instr, do we need to add a warning?

**Comment by dstansby** [comment]
Ha, `sunpy.instr.eve` doesn't even exist, so I don't know what I was on about... I'm going to close this, if there are specific EVE products un-supported by Fido/Map/Timeseries please open new issues for each desired product.
