### ISSUE TITLE
Improvements to figure tests

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5331]
This issue is to track new features to the figure tests run on circleCI. The end goal is to make it possible to do everything figure test related without having to resort to local test runs.

Please add to this list of comment if you can think of anything.

- [x] Ensure a newly generated set of hashes is uploaded as an artifact for *every* figure test run on circleCI
- [x] Ensure a newly generated set of figures is uploaded artifacts for *every* figure test run on circleCI
- [x] Ensure new figure tests have both a figure and hash generated that are accessible from the circleCI run.
- [x] Ensure that if a figure is missing in the repo, it does not fail the entire test run

**Comment by dstansby** [comment]
No, I don't think they are given that PR is merged, and the three un-ticked items above are still outstanding issues. @ayshih / @wtbarnes if you are looking for suggestions for infrastructure improvements to implement this would be top of my list!

**Comment by ConorMacBride** [comment]
I believe all of the points in this issue are now covered by the pytest-mpl HTML summary.
