### ISSUE TITLE
Functionality to pass a dt (sampling frequency) to TimeRange and it would return list of astropy time objects

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5377]
### Description

It would be nice if you could pass a start and end time and a sampling frequency to TimeRange and it would return a list of astropy time objects. 

The list could be an attribute of the TimeRange class

E.g. an equivalent to something like np.linspace but for a timerange

**Comment by ajeytiwary** [comment]
`
from astropy.time import Time, TimeDatetime, TimeDelta
def datetime_range(start, end, delta):
    delta = TimeDelta(delta, format='sec')
    while start < end:
        yield start        
        start += delta
       
`
Working example 
` 
t1 = Time('2010-01-01 00:00:00')
t2 = Time('2010-03-01 05:00:00')


t_list = list(datetime_range(t1, t2,3*60*60))
`
The TimeDelta should be in seconds for this to work.

**Comment by ajeytiwary** [comment]
You mean something like this?

`from astropy.time import Time, TimeDatetime, TimeDelta`
`def datetime_range(start, end, delta):`
`    delta = TimeDelta(delta, format='sec')`
`    while start < end:`
`        yield start`        
`        start += delta`

`t1 = Time('2010-01-01 00:00:00')`
`t2 = Time('2010-03-01 05:00:00')`

`t_list = list(datetime_range(t1, t2,3*60*60))`

This works where `TimeDelta` in in seconds. In the above example the `t_list` will return a list of `Time` objects 
On a different note, how do you write `codeblocks`, is there a shortcut I am missing?

**Comment by ajeytiwary** [comment]
You mean something like this?

```
from astropy.time import Time, TimeDatetime, TimeDelta
def datetime_range(start, end, delta):
    delta = TimeDelta(delta, format='sec')
    while start < end:
        yield start        
        start += delta
        
```
```
t1 = Time('2010-01-01 00:00:00')
t2 = Time('2010-03-01 05:00:00')

t_list = list(datetime_range(t1, t2,3*60*60))
```
This works where `TimeDelta` in in seconds. In the above example the `t_list` will return a list of `Time` objects between `t1` and `t2` with a stepsize of `delta` (in sec).

**Comment by vmpyr** [comment]
Hi, I'd like to take this issue if no one's working on it

**Comment by nabobalis** [comment]
> Hi, I'd like to take this issue if no one's working on it

I am not aware that anyone is working on this issue. So please go ahead.

**Comment by Krish2208** [comment]
Can you please have a look at the PR, I added the required function to TimeRange class

**Comment by Cadair** [comment]
@dstansby points out [here](https://github.com/sunpy/sunpy/pull/6017#pullrequestreview-929192882) that 

```python
np.arange(tr.start, tr.end, delta)
```
should work.

@hayesla If that does what you expect do you think we still need our own method?

**Comment by nabobalis** [comment]
I think adding `np.arange(TimeRange.start, TimeRange.end, delta)` as an example for timerange is the way forward.
