### ISSUE TITLE
Confusion in doc examples about saving map

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5379]
### Description
If one was looking to save a map, but didn't realize there is a save method on the map class, you may go to the example gallery and look for an example of how to save a map. However under the [Saving and Loading Data](https://docs.sunpy.org/en/stable/generated/gallery/index.html#saving-and-loading-data) in the example gallery it looks like the only way to do this is by saving data to an `asdf`. Naively someone may think this is the only way to save and load data. 

I don't know what the solution is - maybe an easy example of how to save a map to a fits file and load it back in etc?

**Comment by dstansby** [comment]
Perhaps this is fixed by https://github.com/sunpy/sunpy/pull/5544 now?
