### ISSUE TITLE
Display data units to the the map quick view plots and colorbar ?

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5388]
### Description

As suggested from workshop, it would be nice to have the data units (e.g. cts, etc) printed on the .peek() histogram (pixel value plot) and maybe added to the colorbar of a map when plotted

or:

The units of a map are accessible via .unit. This is included in the peek colorbar, but not in the fancy html repr. It would be nice to include this too, maybe just as an additional entry in the table on the left.

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue. I know python, but u have never used sunpy. With guidance , i will be able to solve this issue

**Comment by nabobalis** [comment]
Hi @himanshu007-creator, welcome.

We will help you as much as we can.

**Comment by jiaqing23** [comment]
Hello @nabobalis, seems like no one is working on this issue. I would like to try it out.

**Comment by Shikharishere** [comment]
Is this issue still open?

**Comment by nabobalis** [comment]
> Is this issue still open?

Hello, I think what is left is to check that the unit appears on the colorbar and if no, add it and see if it looks nice. Otherwise this issue is finished.

**Comment by dstansby** [comment]
Just checked some of the figure tests with colorbars, and units appear below the colobar, so I'll close this.
