### ISSUE TITLE
User suggested Postel projections

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#5400]
### Description

A user at the AAS / SPD SunPy Workshop expressed the desire for Postel projections of the Sun, i.e., [https://en.wikipedia.org/wiki/Azimuthal_equidistant_projection](https://en.wikipedia.org/wiki/Azimuthal_equidistant_projection) . This issue is submitted to record this request on their behalf.

**Comment by ayshih** [comment]
Example script that can be transformed into a gallery example (currently requires the dev branch):
```python
import matplotlib.pyplot as plt
import reproject

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.wcs import WCS

import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE

# Load the sample AIA image
aia_map = sunpy.map.Map(AIA_171_IMAGE)

# Fix the plotting scale
aia_map.plot_settings['norm'].vmin = 0
aia_map.plot_settings['norm'].vmax = 10000

# Define the origin for the Postel projection
origin_hpc = SkyCoord(735*u.arcsec, -340*u.arcsec, frame=aia_map.coordinate_frame)
origin = origin_hpc.heliographic_stonyhurst

# Define the new WCS
out_shape = (750, 750)
out_header = sunpy.map.make_fitswcs_header(
    out_shape,
    origin,
    scale=[0.4, 0.4]*u.deg/u.pix,
    projection_code="ARC"
)
out_wcs = WCS(out_header)

# Reproject the AIA image to the new WCS
output, _ = reproject.reproject_interp(aia_map, out_wcs, out_shape)

# Create the reprojected Map
out_map = sunpy.map.Map(output, out_header)
out_map.plot_settings = aia_map.plot_settings

fig = plt.figure(figsize=(8, 4))

# Plot the original AIA map
ax = fig.add_subplot(1, 2, 1, projection=aia_map)
aia_map.plot(axes=ax)
aia_map.draw_grid(axes=ax, color='blue')
aia_map.draw_limb(axes=ax, color='blue')
ax.plot_coord(origin, 'o', color='red', fillstyle='none', markersize=20)

# Plot the reprojected map
ax = fig.add_subplot(1, 2, 2, projection=out_map)
out_map.plot(axes=ax, autoalign=True, annotate=False)
out_map.draw_grid(axes=ax, color='blue')
out_map.draw_limb(axes=ax, color='blue')
ax.set_xlim(-0.5, out_shape[1] - 0.5)
ax.set_ylim(-0.5, out_shape[0] - 0.5)
ax.set_title('Postel projection centered at ROI')

plt.show()
```
![postel_example](https://user-images.githubusercontent.com/991759/122277561-064bd400-ceb4-11eb-9986-f9d260a6145e.png)

**Comment by farhanabid94** [comment]
Hello,

I was wondering if I could work on this issue.

I am not entirely sure what the objective is here. Do we want to adjust the above posted script so that it can be a standalone function that is able to take existing solar map data as an argument and re-project it into a Postel projection?

-Farhan

P.S -  I am brand new to open source development and github so please let me know if at any point I am approaching the issue incorrectly or am doing anything else that appears nonsensical.

**Comment by ayshih** [comment]
The task here is not to create a function, but rather to create a new example for [the gallery](https://docs.sunpy.org/en/latest/generated/gallery/) from the script that I posted above.  There needs to be more narrative explaining the steps, particularly having to set the plot limits, and the plot labels need to be cleaned up some.

See [this example](https://docs.sunpy.org/en/latest/generated/gallery/map_transformations/reprojection_heliographic_stonyhurst.html) for a simpler reprojection example.

**Comment by farhanabid94** [comment]
Ok sounds good. I can do a write up and clean up the labels. I am guessing [this is the spot](https://github.com/sunpy/sunpy/tree/main/examples/map_transformations) in the repository that will need a new file. I'll use the examples in there as a guide.
