### ISSUE TITLE
Move `sunpy.image.coalignment` to sunkit-image?

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5425]
We don't rely on this anywhere inside core I don't think, so maybe move it out?

**Comment by Cadair** [comment]
@wafels just because he wrote it.

**Comment by dstansby** [comment]
I'm 👍 to doing this

**Comment by wtbarnes** [comment]
Do we deprecate first? Or do we just import from `sunkit-image` and add `sunkit-image` to the optional dependencies?

**Comment by Cadair** [comment]
I would rather not depend on sunkit-image, so I say deprecate and not remove.

**Comment by wafels** [comment]
What about the rest of the sunpy/image ?

**Comment by wtbarnes** [comment]
I would say no. The rest of image is basically resample and affine transform, both of which `Map` heavily depends on.
