### ISSUE TITLE
Order of arguments in `scale` input to `make_fitswcs_header` is wrong in AIA/EUVI reprojection example

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5445]
In [the AIA/EUVI reprojection mosaic example](https://docs.sunpy.org/en/latest/generated/gallery/map_transformations/reprojection_aia_euvi_mosaic.html), the ordering of the `scale` argument to `make_fitswcs_header` is incorrect. The ordering should be Cartesian (lon, lat) [according to the `make_fitswcs_header` docstring](https://docs.sunpy.org/en/stable/api/sunpy.map.make_fitswcs_header.html#sunpy.map.make_fitswcs_header), but in this example, the order is according to the array index. This actually has no effect on the example output as the scale in both directions is the same (1 deg/pix), but is potentially confusing and conflicts with the function docstring.

**Comment by RhnSharma** [comment]
I would like to take this one.

I just have to make this change `scale=[180 / shape_out[0],
 360 / shape_out[1]]` => `scale=[360 / shape_out[1],
 180 / shape_out[0]]`, right?

Or am I missing something?

**Comment by ayshih** [comment]
Same problem in this example: https://docs.sunpy.org/en/v3.0.1/generated/gallery/map_transformations/reprojection_heliographic_stonyhurst.html

**Comment by wtbarnes** [comment]
> I would like to take this one.
> 
> I just have to make this change `scale=[180 / shape_out[0], 360 / shape_out[1]] * u.deg / u.pix` => `scale=[360 / shape_out[1], 180 / shape_out[0]] * u.deg / u.pix`, right?
> 
> Am I missing something?

Yep that is correct. The `shape` parameter is ordered according to array index, but the `scale` parameter is cartesian ordered.
