### ISSUE TITLE
Wrong date being used for EUI observer coordinate

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5450]
Currently in sunpy 3.0.x, the date/time of `m.observer_coordinate` is taken from `m.date`, which is taken from the DATE-OBS FITS keyword. For Solar Orbiter (and possibly other missions), the coordinate metadata is valid at the time given by DATE-AVG however, which is different to DATE-OBS (see 3.1.1.10 of the [Metadata Definition for Solar Orbiter Science Data](https://issues.cosmos.esa.int/solarorbiterwiki/display/SOSP/Metadata+Definition+for+Solar+Orbiter+Science+Data)).

This will be fixed in 3.1 by https://github.com/sunpy/sunpy/pull/5449/files, but we should issue a fix for the 3.0.x branch in the EUI map source.

**Comment by wtbarnes** [comment]
Should `.date` on the EUI source just default to 'DATE-AVG'? That seems like the easiest fix here.

**Comment by dstansby** [comment]
Yep, I think that's the best thing to do.
