### ISSUE TITLE
Submap rounds pixel values incorrectly, sometimes leading to results which are too large.

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5461]
(I swear we have had this discussion before the other way around.)

```python
bottom_left = SkyCoord(-100, -100, unit=u.arcsec, frame=aia.coordinate_frame)
top_right = SkyCoord(600, 600, unit=u.arcsec, frame=aia.coordinate_frame)

sm = aia.submap(bottom_left, top_right=top_right)

fig = plt.figure()
ax = fig.add_subplot(projection=sm)

sm.plot()
ax.plot_coord(bottom_left, '.')
ax.plot_coord(top_right, '.')
plt.show()
```

Zooming in on the top right corner shows:

![Figure_1](https://user-images.githubusercontent.com/1391051/125801714-69212ae7-c912-49ca-a28d-0805088d3435.png)

My understanding of submap was that it should include the pixel in which the coordinate lies? This is clearly adding an extra one in the top and bottom corners (in this example).

**Comment by ayshih** [comment]
Not a bug.  Our sample AIA image has a slight rotation angle (-0.14 degrees), so what is happening is that (-100, -100) is one pixel column to the right of (-100, 600).  That's why it looks like we have one extra pixel in the bottom-left corner.
