### ISSUE TITLE
Add note about differences between `astropy.time.Time` and `anytim2tai` to the "Known Issues" page

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5500]
### Description

Once #5374 and #5489 are merged,  there should be a note on the "Known Issues" page about the differences  between `anytim2tai` and `astropy.time.Time` for dates between 1958-01-01 and 1972-01-01. Namely (partially taken from https://github.com/sunpy/sunpy/pull/5489#issuecomment-897010903):

* For dates on and after 1972-01-01 00:00:00 UTC, this format is equivalent to that returned by the `anytim2tai` routine in SSW.
* For dates between 1958-01-01 00:00:00 UTC and 1972-01-01 00:00:00 UTC, `anytim2tai` returns a constant value of 9 s difference between UTC and TAI time while `astropy.time.Time` returns a value of 0 s difference between UTC and TAI on 1958-01-01 00:00:00, with this difference increasing approximately linearly to 10 s on 1972-01-01 00:00:00, where the two approaches agree.
* UT and TAI were synchronized by definition on 1958 Jan 1 00:00:00.  `anytim2tai.pro` should return 0 at that time.
* Even if `anytim2tai.pro` is intentionally choosing to ignore the difference in lengths of UT seconds and TAI seconds prior to 1972, it should be returning 10 for pre-1972 times, not 9.  Its implementation acts as if there was a leap second added on 1972 Jan 1, but there was not.

This should include this plot or something similar:

![image](https://user-images.githubusercontent.com/8676141/129209521-c656d62b-562e-41b0-965e-3db30627a131.png)

**Comment by ayshih** [comment]
The "known issue" should be simpler than the above.  In a nutshell, SSW is known to not provide valid conversions for pre-1972 dates, and SSW folks say that they're going to add more disclaimers.  I have suggested new text in #5374.

**Comment by dstansby** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/5374 I think
