### ISSUE TITLE
Make all test maps pytest fixtures

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5504]
In the tests for the `CORMap`, `EUVIMap`, `HIMap`, `HMIMap` map sources, the map is constructed once and then reused many times in tests, e.g.:
https://github.com/sunpy/sunpy/blob/a319336bb2deb7d495e52614970a4dd26a4b31fd/sunpy/map/sources/tests/test_cor_source.py#L13-L15

We should change this to using a pytest fixture to create the map, so a new instance of the map is created for each test. This is how most of the other source tests work.

Possibly fixed by https://github.com/sunpy/sunpy/pull/5261?

**Comment by wtbarnes** [comment]
I will take care of this in #5261
