### ISSUE TITLE
Should we set the observer for HMI synoptic maps?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5505]
HMI synoptic maps, which come in a Carrington frame, do not have an observer set in their metadata. Since https://github.com/sunpy/sunpy/pull/3782 (sunpy 2.0) `HeliographicCarrington` is an observer based frame, so trying to construct the `wcs` for a HMI synoptic map results in `Missing metadata for observer: assuming Earth-based observer.`

Should we instead be manually setting the `observer_coordinate` of HMI synoptic maps to be consistent with the way the synoptic maps are constructed? My guess is that it should either be set to earth, or the surface of the Sun, but this will require some detailed investigation to get right if we choose to set it.

**Comment by ayshih** [comment]
Hmm, setting the observer location to Earth at the reference time would probably be good enough.  What you need is the correct Sun-observer distance to get the correct light travel time; the latitude/longitude is irrelevant.  Although SDO is not at Earth center, the difference is almost certainly too negligible to be seen in the synoptic maps, and if not, I'd presume that they already correct for that when constructing the synoptic map in the first place.
