### ISSUE TITLE
Support queries on exposure time in `JSOCClient`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5539]
### Description

When using `drms`, it is possible to construct queries based on the exposure time keyword `'EXPTIME'`. For example, 

```python
import drms
c = drms.Client()
q = c.query(
    'aia.lev1_euv_12s[2021-07-03T14:25:00Z-2021-07-03T14:35:00Z][? EXPTIME<2.0 AND WAVELNTH=211 ?]{image}",
    keys=['EXPTIME', 'QUALITY'],
    seg='image',
)
```

constructs a query for 211 AIA images with exposure times less than 2 s over the desired time range. Currently, this kind of query is only possible by using `drms` directly.

We should add an `ExposureTime` attr in `jsoc.net.attrs` that allows for this kind of query directly through the `JSOCClient`.

**Comment by Cadair** [comment]
Is there a more general way we can do this? Are there other things you can query on like this?

**Comment by nabobalis** [comment]
The DRMS allows us to chain operations on all keywords with filtering. 

This would be a large job and I am unclear as to the long term future of the JSOC.

**Comment by wtbarnes** [comment]
I think it's at least worth investigating. My understanding is that the JSOC will at least be around for the lifetime of SDO, i.e. ideally many years!

**Comment by Cadair** [comment]
We could have a powerful but tricky attr which let's you enter these "raw" and then a few useful ones which do it for you like exptime?

**Comment by wtbarnes** [comment]
I like that idea. That way you can still use the power of `drms` while also being able to take advantage of some of the high-level features of `JSOCClient`. This also might help to partly address #3735

**Comment by nabobalis** [comment]
Is this not done now?

**Comment by Cadair** [comment]
Was this done? I don't see any `ExposureTime` attr in the jsoc file or any PR which looks like it addresses this?

**Comment by nabobalis** [comment]
The Keyword support we added in 3.1?

**Comment by nabobalis** [comment]
https://github.com/sunpy/sunpy/pull/5566/files#diff-65667c0bcebd94eb40d0ae7c0c15467881466ea549cd1d2950a38bc16850b0c1R178
