### ISSUE TITLE
Allow figure tests to be run without figure comparison at the end

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5541]
Currently it's only possible to run figure tests in a specific environment, to make sure we have the correct version of packages to do the image comparison at the end. It would be helpful to be able to run the figure tests in other environments to check the code works, without doing the figure test at the end.

e.g., if I try and run a figure test locally that would fail because of an exception being raise (before a test image is even generated) I get:

```python
$ pytest sunpy/map/tests/test_plotting.py::test_draw_limb_heliographic_stonyhurst
/Users/dstansby/miniconda3/envs/dev/lib/python3.9/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
========================================================= test session starts ==========================================================
platform darwin -- Python 3.9.7, pytest-6.2.3, py-1.9.0, pluggy-0.13.1
Matplotlib: 3.5.0.dev2088+g876022e616
Freetype: 2.6.1
rootdir: /Users/dstansby/github/sunpy, configfile: setup.cfg
plugins: asdf-2.7.1, arraydiff-0.3, doctestplus-0.8.0, remotedata-0.3.2, hypothesis-6.0.0, filter-subpackage-0.1.1, mock-3.3.1, cov-2.10.1, profiling-1.7.0, openfiles-0.5.0, timeout-1.4.2, astropy-header-0.1.2, pep8-1.0.6, mpl-0.12
collected 1 item / 1 deselected                                                                                                        

======================================================== 1 deselected in 0.91s =========================================================
```
I would like this to error and give me an error message instead.

**Comment by ConorMacBride** [comment]
This is deselected/skipped for two reasons. Firstly, by default all tests marked `mpl_image_compare` are deselected:
https://github.com/sunpy/sunpy/blob/f7bdf22e5229a577c5851c1e05502f0d68b4b369/setup.cfg#L111

Secondly, all figure tests are marked as needing remote data, and by default, tests needing remote data are skipped. 

A local fix is to append `--remote-data -m "mpl_image_compare"` to pytest commands,

```sh
pytest sunpy/map/tests/test_plotting.py::test_draw_limb_heliographic_stonyhurst --remote-data -m "mpl_image_compare"
```

and tox commands,

```sh
tox -e py39 -- --remote-data -m "mpl_image_compare"
```

Note, that adding these will *only* run the figure tests (without comparison) and deselect all other tests. However, passing `--remote-data -m "mpl_image_compare or not mpl_image_compare"` should select all.

Would you want a new tox environment such as `-runfigures` which includes these arguments?

**Comment by dstansby** [comment]
By default could we:
- Remove the addopt that stops image tests being run (ie. always run them)
- Only do the image comparison at the end of a test if the correct set of package versions are installed
