### ISSUE TITLE
net.vso.Results does not appear in reference documentation

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#555]
The `get` method of `VSOClient` returns an instance of `Results`. The reference documentation does not show which methods or attributes the class `Results` has (docstrings are present, but not included in the reference). It has a `map_` attribute (which is a dict), but it is not explained what the meaning of the keys and values are.

**Comment by dpshelio** [comment]
Now that `get` is deprecated, does [`fetch`](http://docs.sunpy.org/en/stable/api/sunpy.net.vso.VSOClient.html#sunpy.net.vso.VSOClient.fetch) has the same problem? I think it's still undocummented - we should improve the docs on [`Result`](https://github.com/sunpy/sunpy/blob/master/sunpy/net/download.py#L184).

**Comment by Cadair** [comment]
I think this is still a problem, but will be obsoleted by #2797
