### ISSUE TITLE
QueryResponse.show not flexible enough

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#556]
It would be nice if one could change the columns that will be displayed. 

Compare the function `display_entries` of my database package to get an idea of what I imagine (implementation https://github.com/derdon/sunpy/blob/database/sunpy/database/tables.py#L547, test at https://github.com/derdon/sunpy/blob/database/sunpy/tests/database/test_tables.py#L302). 

So I'd like the signature of `QueryResponse.show` to be `self, columns=['Start time', 'End time', 'Source','Instrument', 'Type']`. This way, the default behaviour will not change to the current implementation.

**Comment by dstansby** [comment]
It would be good to have a simple self contained example that illustrates this issue.

**Comment by abhijeetmanhas** [comment]
Is this duplicate of https://github.com/sunpy/sunpy/issues/3321 ?
