### ISSUE TITLE
Teach Azure Pipelines to skip stage 2 tests when [ci skip] is in the commit message

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5589]
We need at least stage 1 to pass to merge any PR.

**Comment by ConorMacBride** [comment]
Azure [should already recognise](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits) `[ci skip]` and not run anything. I don't think this feature can be disabled such that we can process the commit message inside the pipeline to apply conditions to stages. However, it may be possible to write a GitHub app that calls the Azure API to trigger stage 1 to run if it sees a commit with `[skip ci]`.

**Comment by Cadair** [comment]
That feature doesn't work for pull requests though.

I did actually look into this a week or so ago for astropy, and to say it's not simple is an understatement.

**Comment by ConorMacBride** [comment]
If it doesn't work for pull requests the pipeline should run as usual even if a skip command is in the latest commit message of the PR, yes? So can you not just add conditions to all stages >1 to skip if `[ci skip]` is in the variable [`Build.SourceVersionMessage`](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services)?

**Comment by ConorMacBride** [comment]
The `Build.SourceVersionMessage` variable is only available in jobs so any checks need to be run in a job and then passed to the stage conditions as a dependency variable. Furthermore, `Build.SourceVersionMessage` is of the form `"Merge LAST_COMMIT_HASH into MAIN_BRANCH_HEAD_HASH"` so this needs some parsing to get the message of the last PR commit. I have this working here: https://github.com/ConorMacBride/mcalf/pull/43. Would this be a solution? The Bash script can be moved to a separate file and extended to recognise a wider range of skip commands.

**Comment by Cadair** [comment]
Nice one! Might be worth adding to the template repo somehow? It's annoying you have to resort to bash to do it though.

**Comment by ConorMacBride** [comment]
That should work. The check for the skip command can be added to a template. I think a new template (`check-skip.yml` possibly?) would be better, as this check is independent to tox. 

I can then document how the user adds conditions to other stages. Not sure if this part can be added to a template, as it would have to skip the stage (or its jobs) after the stage has started.

**Comment by Cadair** [comment]
> I think a new template

:+1: 

> Not sure if this part can be added to a template

Yeah I don't think it can.
