### ISSUE TITLE
Add a helpful error message to `GenericMap.submap()` for helioprojective-related NaNs

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5598]
It's a recurring source of confusion for users when they try to submap a helioprojective map from one observatory using 2D helioprojective coordinates from a different observatory (or the same observatory at a different time) and one of the corners is off-disk.  Even if the observer-location difference or the observation-time difference is small, formally there is no unambiguous conversion of an off-disk 2D coordinate to a different helioprojective frame because we don't know what assumption to make the coordinate 3D.  (For an on-disk 2D coordinate, we make the broadly safe assumption that the coordinate is on the solar surface in 3D space.)  The coordinate transformation of the corner point returns NaNs, and `submap()` errors ungracefully.

We should add an error message to `submap()` so that it checks if it is about to work with NaNs and tells the user that they likely want to use `Helioprojective.assume_spherical_screen()` so that the off-disk 2D coordinate can be converted to a 3D coordinate.

**Comment by ayshih** [comment]
Suggested by @nabobalis

**Comment by PaulJWright** [comment]
This would be super useful. Any progress on this?

**Comment by sha016** [comment]
I did start working on it but couldn't quickly come up with an example/test case to work with. I'll probably need to spend some more time familiarizing myself with the code base. I did get to see some images, which was cool.

**Comment by samiali12** [comment]
please assign me this issue, I will resolve it.

**Comment by ayshih** [comment]
@samiali12: On this repository, we typically don't assign issues to people.  Feel free to go ahead and work on this, and submit a (draft) PR when you're ready.

**Comment by sha016** [comment]
@samiali12 I have not started working on this again. Go for it.

**Comment by vmpyr** [comment]
@samiali12 Are you still working on the issue? If no, I'd like to take it up

**Comment by grahamasam** [comment]
hello, is this issue still unresolved? I would like to work on it if that is the case.

**Comment by nabobalis** [comment]
> hello, is this issue still unresolved? I would like to work on it if that is the case.

Go ahead.
