### ISSUE TITLE
Make sure example gallery is using the smallest possible set of data

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5632]
The example gallery currently takes a long time to build. One way we could speed this up is by making sure all of the gallery examples use a minimal set of data. As an example, both
- https://docs.sunpy.org/en/stable/generated/gallery/units_and_coordinates/SDO_to_STEREO_Coordinate_Conversion.html#sphx-glr-generated-gallery-units-and-coordinates-sdo-to-stereo-coordinate-conversion-py
- https://docs.sunpy.org/en/stable/generated/gallery/map_transformations/reprojection_different_observers.html#sphx-glr-generated-gallery-map-transformations-reprojection-different-observers-py

could use the same images and Fido search, but currently do not.

**Comment by dstansby** [comment]
I've had a look at adding some STEREO data, and if we just add an image at the same time as the existing AIA data it doesn't play well with reprojection, because the AIA maps have some very high pixel values (see discussion in https://github.com/sunpy/sunpy/issues/2726). So, options are:

- We choose another interval and completely re-do the sample data. This could allow us to choose an interval with Solar Orbiter/EUI and PSP/WISPR images which might be nice...
- We add two new maps: a STEREO and AIA map taken at the same time, but a different time to existing sample data

**Comment by Cadair** [comment]
We are never going to be able to have a single event with all the past and future satellites / instruments running. i.e. RHESSI, both stereos and PSP etc are mutually exclusive at this point. So wholesale redoing all the sample data isn't going to work, as we should keep a RHESSI & AIA pair for composite map contours over image example etc.

While I think we should keep our sample data a) not too large and b) of some kind of interesting events, I would not be adverse to adding a new event or interesting feature to the set to cover new instruments etc.

**Comment by ayshih** [comment]
> it doesn't play well with reprojection, because the AIA maps have some very high pixel values (see discussion in #2726)

It doesn't play well reprojection in a way that isn't mitigated by the `clip_interval` keyword?  I'll note that #2726 predates the addition of that functionality.

**Comment by dstansby** [comment]
The issue is with using the `match_background` setting in `reproject`. I tried masking out the high values pixels from the AIA maps, but the combined reprojected AIA + EUVI map still didn't look right. I lost my test code for this, but will try and put something together again.

**Comment by dstansby** [comment]
In `reprojection_aia_euvi_mosaic.py`, trying to use an EUVI map at the same time as the AIA map in the sample data gives:
![Screenshot 2021-11-10 at 15 35 19](https://user-images.githubusercontent.com/6197628/141143190-12043b47-4b53-416d-984b-31b80c40ee29.png)

I've tried clipping the AIA data, or replacing the high values (> 1e5) with `NaN`, but it doesn't seem to help. Here's the code I used to get the EUVI map:
```python
aia_map = sunpy.map.Map(sunpy.data.sample.AIA_193_IMAGE)
'''euvi = (a.Source('STEREO_A') &
        a.Instrument("EUVI") &
        a.Time(map_aia.date - 1*u.hour, map_aia.date + 1*u.hour, map_aia.date) &
        a.Wavelength(195 * u.Angstrom))
result = Fido.search(euvi)
euvi_file = Fido.fetch(result)[0]'''

######################################################################
# Next we create a sunpy map for each of the files.
eui_map = sunpy.map.Map('/Users/dstansby/sunpy/data/20110607_064800_n4eua.fts')
maps = sunpy.map.Map([aia_map, eui_map])
```

**Comment by dstansby** [comment]
The issue with the images at the time above is that a simple shift in values (which is what `match_background=True` does) is not sufficient to match the distribution of values across AIA and EUVI:

![Screenshot 2021-11-10 at 17 51 40](https://user-images.githubusercontent.com/6197628/141167257-9d1d71b8-7214-476a-ad84-d4c89735a37a.png)

I'm guessing this is down to differences in exposure times and instrumental details between the two telescopes. So we could add a manual (empirical) multiplying factor to get them to match up, if we want to go down the route of keeping existing AIA sample data and adding a corresponding EUVI map.

**Comment by dstansby** [comment]
I'm going to close this in favour of https://github.com/sunpy/sunpy/issues/3514
