### ISSUE TITLE
quicklook doesn't work well for some EUI maps

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5666]
![Screenshot 2021-11-02 at 21 46 23](https://user-images.githubusercontent.com/6197628/139956314-927f6bf6-25ee-4158-8ff9-897b8112ced2.png)

The issue seems to be that using histogram normalisation puts all the dynamic range in the few data values that take up most of the map, ie. off-limb. Off the top of my head, possible solutions could be:
- Respect the `vmin` and `vmax` set on the norm (in the example above I had `vmin=20` set, which affects plotting but not the quicklook)
- For maps with positive definite units, ignore < 0 values? The above map has units of counts/second.

**Comment by Cadair** [comment]
I would say the point of quicklook is to show the whole array, so I am not in favour of using vmin/max

**Comment by dstansby** [comment]
Given I haven't provided a link to the data above, closing as not reproducible
