### ISSUE TITLE
read_cdf has issues if unit string not understood

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5670]
### Description

The new functionality for reading CDF files is great! However I've come across an issue when testing with some SolO EPD files

e..g:

```python
>>> read_cdf('solo_l2_epd-step-hcad_20210728_v01.cdf')

ValueError: 'seconds' did not parse as unit: At col 0, seconds is not a valid unit. Did you mean second? If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html
```
This lies in [here](https://github.com/sunpy/sunpy/blob/main/sunpy/io/cdf.py#L65) , where if units are given in the metadata it tried to pass the string to `u.Unit`, however it seems the case that its not always recognized i.e. `seconds` vs `second`. Similarly, there are also units such as `counts/s` and `particles / (s cm^2 sr MeV)` that are also an issue for this example file. 

### System Details
- SunPy Version: 3.1.0
- Astropy Version: 4.3.1

### Steps to reproduce
```python
from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.io.cdf import read_cdf

trange = a.Time('2021/07/28', '2021/07/28')
dataset = a.cdaweb.Dataset('SOLO_L2_EPD-STEP-HCAD')
result = Fido.search(trange, dataset)
file = Fido.fetch(result[0])
read_cdf(file[0])
```

**Comment by dstansby** [comment]
I ran into this yesterday too! The issue is that there is no standard within CDF files on how to format the units and so they can be arbitrary strings 😢

For now the workaround is to define your own units in `astropy`:
```python
u.add_enabled_units([u.def_unit('seconds', represents=u.s), ...])
```

Do you have any thoughts on a more long term solution? Perhaps we could have a dictionary that converts from known unit strings to units? This is what I did in `heliopy`:
https://github.com/heliopython/heliopy/blob/384ac8eff05b8af1b2e47cb9a037ec10510e3b0e/heliopy/data/helper.py#L143-L147

**Comment by hayesla** [comment]
yeah such a pain that there's no standard! 

I think something like a dictionary like what you had in `heliopy` probably makes the most sense - maybe one that just registers known unit strings to astropy units using the `u.add_enabled_units`?

**Comment by Cadair** [comment]
My concern about using `add_enabled_units` is that it's global? when really you only want it to affect read?

**Comment by dstansby** [comment]
Yes, I'd be -1 doing a global registration. Working on a PR to just have it in the CDF reader though.
