### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [sunpy/sunpy#5695]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/SunPy/lokal -name '*.py')
```

**Comment by nabobalis** [comment]
Sure, I guess.

**Comment by elfring** [comment]
Can the chances grow that [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) will get further development interests? :thinking:

**Comment by nabobalis** [comment]
If people want it to make the changes, that's fine by me.

I don't think it requires an open issue to track it tho

**Comment by elfring** [comment]
Would you find any change possibilities challenging according to the presented transformation approach?

**Comment by nabobalis** [comment]
I'll have to see the PR but I don't think so
