### ISSUE TITLE
Azure Pipelines not running

### ISSUE THREAD

**Issue by ConorMacBride** [sunpy/sunpy#5721]
### Description

Azure Pipelines is not running anymore and all jobs give the error:

> No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

See, e.g., https://dev.azure.com/sunpy/sunpy/_build/results?buildId=21651&view=logs&s=66b58f00-c8fe-5f58-783b-c234696f175c&j=0609049e-3a2a-5217-995e-2cc283dcaa52

Can whoever has admin rights to the Azure DevOps organisation complete the form above? There may be more details here: https://dev.azure.com/sunpy/sunpy/_settings/buildqueue?_a=concurrentJobs

Azure have a [blog post](https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-public-projects/) about this change, although they say it should only affect new organisations.

**Comment by nabobalis** [comment]
I think only @Cadair has.

**Comment by Cadair** [comment]
Oh damn.

> If you are a maintainer of an open-source project, you are likely already using a GitHub repository to manage your source code. So, we strongly recommend using GitHub Actions for your CI needs. This provides a more integrated experience with your repositories.

That's *not good*.

**Comment by nabobalis** [comment]
Time to cough up?

**Comment by ConorMacBride** [comment]
Yeah I saw that. Hopefully that doesn't mean that they are dropping support for free open-source build anytime soon.

**Comment by Cadair** [comment]
I have submitted the form.

I was more concerned that they are just flatly recommending GH Actions, it means that they clearly have no intention of improving the GH integration for pipelines.

**Comment by ConorMacBride** [comment]
Thanks. I'll look into this and see if/when we should migrate to GitHub Actions. Migration might not be too difficult as they both have similar configurations. Should just be a matter of forking the pipelines templates repository and carefully translating them.

**Comment by Cadair** [comment]
Last I looked I think the configuration power of Actions wasn't as good, so it's harder to go full template and have the very minimal local config. If you want to look at it, you are obviously free to do so, I am personally still pretty happy with Azure assuming they sort this out for us.

**Comment by Cadair** [comment]
I just noticed that the blog post about the changes to the free tier was from February!

Either way form filled in and response received, we should be good to go again.

**Comment by ConorMacBride** [comment]
Azure Pipelines jobs are now running successfully again. Thanks @Cadair. I'm happy with Azure also.
