### ISSUE TITLE
Fido HECClient returns out-of-date results

### ISSUE THREAD

**Issue by alasdairwilson** [sunpy/sunpy#5724]
When trying to access HEC data through Fido HECClient, the data returned is ~1 month out of date. Looking at the current web gui for the HEC API, it returns events up to today but through Fido, the latest data is from ~ 2021-11-03

```python
from sunpy.net import Fido, attrs as a


timerange = a.Time('2021/11/01 00:00:00', '2021/12/01 00:00:00')
results_hec = Fido.search(timerange,
                           a.helio.TableName('gevloc_sxr_flare'))
results_hec                         
<sunpy.net.fido_factory.UnifiedResponse object at 0x000002B89664B730>
Results from 1 Provider:

10 Results from the HECClient:
     time_start     ...
------------------- ...
2021-11-02T02:57:00 ...
2021-11-02T07:37:00 ...
2021-11-02T12:55:00 ...
2021-11-02T21:09:00 ...
2021-11-03T00:10:00 ...
2021-11-03T00:56:00 ...
2021-11-03T08:15:00 ...
2021-11-03T14:32:00 ...
2021-11-03T14:43:00 ...
2021-11-03T15:18:00 ...

```
I have also tested with 'goes_sxr_flare' and get roughly the same time for the latest event ( 2021-11-02T21:09:00 )
You can see the expected returns from this query for both gevloc and goes_sxr here:

http://hec.helio-vo.eu/hec/hec_gui_fetch.php?y_from=2021&mo_from=11&d_from=1&y_to=2021&mo_to=12&d_to=1&radioremote=on&titlesearch2=&goes_sxr_flare=istable&gevloc_sxr_flare=istable

- SunPy Version: 3.1
- Astropy Version: 4.3.1
- Python Version: 3.8.8
- OS information: Win & WSL same issue

**Comment by nabobalis** [comment]
Sorry I took so long to look at this.

The answer is that its a default/documentation issue.

The `HECClient` by default (I don't know why) limits its responses to 10 long.

So if you do 
```
results_hec = Fido.search(timerange, a.helio.TableName('gevloc_sxr_flare'), a.helio.MaxRecords(999))
print(results_hec)
```
You get 251 results, that go to the end of the timerange as requested.

**Comment by alasdairwilson** [comment]
Thanks @nabobalis , 

>It might be time to increase the default value to something other than 10. Emitting a warning too maybe?

both sound like good changes.

**Comment by dstansby** [comment]
FWIW the max records has been around since the introduction of this code: https://github.com/sunpy/sunpy/pull/645 - perhaps we should just default to not passing max records at all? As far as I can remember that's how the HEK client works, which can result in some queries that take a long time to execute, but no suprisingly absent rows in the query.
