### ISSUE TITLE
Add `column` kwarg to all timeseries source `plot` methods

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5729]
In sunpy 3.1 I added the ability to plot a subset of the columns in a `GenericTimeseries`: https://docs.sunpy.org/en/stable/api/sunpy.timeseries.GenericTimeSeries.html#sunpy.timeseries.GenericTimeSeries.plot

It would be good to roll a similar change out to all the timeseries sources.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by dstansby** [comment]
Yes, feel free to go ahead, I don't think anyone else is working on it.

**Comment by aadityasinha-dotcom** [comment]
> Yes, feel free to go ahead, I don't think anyone else is working on it.

Can you explain me about this issue?

**Comment by nabobalis** [comment]
@dstansby will correct me if I am wrong. 

In the base class for timeseries, the plot method takes a `columns`  keyword. 
The issue is, that in all our subclasses for timeseries, not all plot methods accept or would even use a `columns` keyword.
We need to change that in these subclassed plot methods.

**Comment by aadityasinha-dotcom** [comment]
@nabobalis 
From what I have find that apart from `plot` method only `peek` method uses `columns` keyword. 
But there is one method `_validate_data_for_plotting` which does not use it.

### Screenshot :
![Screenshot from 2021-12-05 17-57-15](https://user-images.githubusercontent.com/75474786/144746510-7afcd261-cc37-466f-b5ac-e86f72be6266.png)

**Comment by nabobalis** [comment]
I don't think that function needs to take a columns keyword.

**Comment by aadityasinha-dotcom** [comment]
> I don't think that function needs to take a columns keyword.

I don't think there are any functions left which doesn't uses `columns`.

**Comment by ConorMacBride** [comment]
Hi @aadityasinha-dotcom, the classes in the `sunpy.timeseries.sources` package [listed here](https://docs.sunpy.org/en/latest/code_ref/timeseries.html#id1) are subclasses of `GenericTimeSeries`. The `columns` keyword was only added to the `GenericTimeSeries.plot` method. The subclasses which override `GenericTimeSeries.plot` by providing their own plot method (e.g. [`LYRATimeSeries.plot`](https://docs.sunpy.org/en/stable/api/sunpy.timeseries.sources.LYRATimeSeries.html#sunpy.timeseries.sources.LYRATimeSeries.plot)) should ideally also accept `columns` similar to how `GenericTimeSeries.plot` does.

**Comment by aadityasinha-dotcom** [comment]
@ConorMacBride Thanks for your reply. I got the point that I have to add the `columns` keyword in the subclasses of `GenericTimeSeries` which are in the `sunpy.timeseries.sources` package.

**Comment by vmpyr** [comment]
@aadityasinha-dotcom Are you still working on the issue? If no, I'd like to take it up please

**Comment by aadityasinha-dotcom** [comment]
@vmpyr Sure!! Go ahead.

**Comment by aadityasinha-dotcom** [comment]
@vmpyr If you need help feel free to ask.

**Comment by vmpyr** [comment]
@aadityasinha-dotcom Sure, thanks!
