### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [sunpy/sunpy#5772]
On aarch64, `pip install sunpy` build the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI. 

I built the aarch64 wheels successfully on azure pipeline but the job gets timed out during testing due to emulation.  

@nabobalis, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by nabobalis** [comment]
Sure, the timeout is an issue tho.

**Comment by dstansby** [comment]
Would https://github.com/sunpy/sunpy/pull/5776 help you at all? I *think* it would remove the need to have a C compiler installed.

**Comment by Cadair** [comment]
I wonder how tricky it would be to persuade cibuildwheel to run a subset of the tests on aarch64? Maybe just io and image?

**Comment by ConorMacBride** [comment]
> I wonder how tricky it would be to persuade cibuildwheel to run a subset of the tests on aarch64? Maybe just io and image?

It should be possible to set the `test_command` to a custom script that runs a particular pytest command depending on the `CIBW_ARCH` env var.

**Comment by dstansby** [comment]
What's the use case for aarch64 (ie. what computers have that architechture?)

**Comment by Cadair** [comment]
IIRC The raspberry pi 4  amongst other things.

**Comment by odidev** [comment]
- The Arm architecture has been available on AWS (Graviton2) for about 2 years now and has seen a lot of adoption by various organizations. The install base of Arm users is growing at a rapid pace.

- Oracle cloud will be releasing Arm based Compute Shapes in the future. Please see [here](https://www.anandtech.com/show/16100/oracle-announces-upcoming-cloud-compute-instances-ice-lake-and-milan-a100-and-altra#:~:text=OCI%E2%80%99s%20Arm%20instances%20will%20clock%20as%20high%20as,%E2%80%93%20OCI%20is%20refreshing%20its%20GPU%20compute%20instances)

- Generally, there is a lot of momentum behind various products switching to Arm based CPUs. For example, the Microsoft surface Pro X is an Arm based device.

**Comment by ConorMacBride** [comment]
I tried building aarch64 again but it's still too slow to test. However, as the only compiled part of sunpy is the ANA reader which is not essential we could release a pure python wheel (e.g. `sunpy-4.0.0-py3-none-any.whl`) which can be used by platforms without binaries such as aarch64 (or even windows).

As a test, I created a directory `wheels/` with:
- `wheels/sunpy-4.0.0.tar.gz`
- `wheels/sunpy-4.0.0-cp38-cp38-macosx_10_9_x86_64.whl`
- `wheels/sunpy-4.0.0-py3-none-any.whl`

(I moved the 4.0.0 tag and compiled with `SUNPY_NO_BUILD_ANA_EXTENSION=1 python -m build --wheel .` to get the pure python package.)

Running `pip download --no-index --find-links=wheels sunpy` prefers `./wheels/sunpy-4.0.0-cp38-cp38-macosx_10_9_x86_64.whl`.

If I then remove `wheels/sunpy-4.0.0-cp38-cp38-macosx_10_9_x86_64.whl`, and run the `pip` command again, it now prefers `./wheels/sunpy-4.0.0-py3-none-any.whl`.

So having the pure Python wheel shouldn't affect x86_64 linux or macOS.

**Comment by nabobalis** [comment]
If we can provide a pure python wheel and it won't affect  platforms that have ANA compiled and will install that version, I don't see the downside.

**Comment by Cadair** [comment]
Nice, I was meaning to look into this when chatting about #6154. If this actually works reliably (would be interesting to try and find some pip reference so that we have some confidence that it will stay working), then I am :+1: to building and uploading a pure python wheel as well.

**Comment by Cadair** [comment]
Oh we should probably document this well and maybe customise the error raised if you try and load an ana file without the extension.

**Comment by ConorMacBride** [comment]
Definitely. I have tracked down the `pip` code which decides which is preferred. In the code linked below, `cpython_tags()` yields `cp38-cp38-macosx_10_9_x86_64` (as well as others) while `compatible_tags()` yields `py3-none-any` (as well as others). As ["The tags are returned in order of preference (most preferred first)."](https://github.com/pypa/pip/blob/4306edf4b1b4ad28264a3628bded2782f39d6026/src/pip/_internal/models/target_python.py#L91), the binary is preferred as `cpython_tags()` extends the `supported` list first.
https://github.com/pypa/pip/blob/4306edf4b1b4ad28264a3628bded2782f39d6026/src/pip/_internal/utils/compatibility_tags.py#L141-L163

I can't find any documentation, but given https://github.com/pypa/pip/pull/7354#issue-523209756 there are clear reasons for this order and I doubt it will ever be changed.

(This would also mean that people using an implementation other than cpython would get the pure python wheel rather than compiling from source.)

**Comment by ConorMacBride** [comment]
I'm not sure what conda would do, but that is a separate build pipeline.

**Comment by Cadair** [comment]
Conda doesn't care, each platform gets it's own package there.

**Comment by Cadair** [comment]
Cool :+1: let's do it.
