### ISSUE TITLE
Add a helpful warning message when converting a 2D `Helioprojective` coordinate will return all NaNs

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5812]
If a 2D `Helioprojective` coordinate is off-disk, the conversion from 2D to 3D that is required for any non-trivial coordinate transformation will return all NaNs, unless something like `Helioprojective.assume_spherical_screen()` is used.  This is a recurring source of confusion for our users, particularly because they also sometimes fail to realize that they are asking for a non-trivial coordinate transformation.

We can add a helpful warning message when `Helioprojective.make_3d()` is going to turn a coordinate array that is not all NaNs into a coordinate array that is all NaNs*.  It would inform the user that a non-trivial transformation may have been requested and that a user may wish to use `Helioprojective.assume_spherical_screen()`.

\* We would not emit the warning if only some of the elements of a coordinate array turn into NaNs, because this happens all the time in mass transformations (e.g., with `reproject`).

See #5598 for a somewhat related issue

**Comment by thewindsofwinter** [comment]
I can try to do this! Do you know exactly where the offending code is? I see a transformations.py that references Helioprojective in coordinates but I'm not sure where Helioprojective itself is. Sorry, I'm a bit new at this 😅

**Comment by ayshih** [comment]
The new code needs to go near the end of this method: https://github.com/sunpy/sunpy/blob/528579df0a4c938c133bd08971ba75c131b189a7/sunpy/coordinates/frames.py#L539-L592

If `d` is all NaNs, then the warning should be emitted.

**Comment by thewindsofwinter** [comment]
Thanks! I'll be on it shortly.
