### ISSUE TITLE
Sunpy.map sign error

### ISSUE THREAD

**Issue by AlexPietrow** [sunpy/sunpy#5815]
### Description

The sunpy.map function seems to be glitching. The X and Y direction is inverted, which leads to the positive coordinates being to the left and below the center of the Sun. (see example blow with freshly downloaded HMI data) 

<img width="815" alt="Screen Shot 2022-01-13 at 2 40 22 PM" src="https://user-images.githubusercontent.com/43774903/149340728-a06d8157-8814-41b3-95c0-1e215255a117.png">

### Expected vs Actual behavior

Sign should be flipped. 

### Steps to Reproduce

```python
import sunpy.map
sim1 = sunpy.map.Map([path_to_data])
sim1.plot()
plt.show()

```

### System Details

==============================
SunPy Installation Information
==============================

#######
General
#######
Time : Thursday, 13. January 2022 01:42PM UT
System : Linux
Processor : 
Arch : 64bit
SunPy : 0.9.10
SunPy_git : a0d06b8310184cbc5d60289f1a2c89e3faafd375
OS: debian 9.6  (Linux 4.9.0-8-amd64 )

##################
Required Libraries
##################
Python: 3.5.3
NumPy: 1.16.6
SciPy: 1.2.2
matplotlib: 2.2.5
Astropy: 3.0.5
Pandas: 0.23.4

#####################
Recommended Libraries
#####################
###########
 Recommended Libraries 
###########
beautifulsoup: 4.10.0
PyQt: NOT INSTALLED
SUDS: 1.4.5.0
Sqlalchemy: NOT INSTALLED
Requests: 2.25.1

**Comment by ConorMacBride** [comment]
Hi @AlexPietrow, this effect is explained in this example: https://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/downloading_hmi.html Hope this helps.

**Comment by dstansby** [comment]
Yes, sunpy plots the data array without any scaling/rotation, and then super-imposes the correct coordinate grid on top of it for the axes. For HMI images they are provided in this rotated state, as explained in the example linked in the previous comment, so this doesn't seem to be a bug and I'll close. If you think we've missed something, feel free to comment and we can reopen this.
