### ISSUE TITLE
no way to complete JSOC query with Wavelength attribute 

### ISSUE THREAD

**Issue by elastufka** [sunpy/sunpy#5823]
### Description

In Sunpy 3.1.3 it is no longer possible to execute a JSOC query when the Wavelength attribute is specified. Therefore even the code in the [documentation](https://docs.sunpy.org/en/v3.1.3/guide/acquiring_data/jsoc.html) returns the error:

```python
from sunpy.net import Fido
from sunpy.net import attrs as a
import astropy.units as u

res = Fido.search(a.Time('2014-01-01T00:00:00', '2014-01-01T01:00:00'),
                              a.jsoc.Series('aia.lev1_euv_12s'),
                              a.Wavelength(304*u.AA))  

```
ValueError: Wavelength attribute has been passed both as a Wavelength() and PrimeKey(). Please provide any one of them or separate them by OR operator.

I had a look at _make_recordset and was extremely confused; it is assigning Wavelength to the PrimeKeys based on the query, but then checking that Wavelength attribute is empty and if it is not it raises this error. So in essence any queries with Wavelength are doomed to fail! 

It seems like a quick fix, perhaps delay the assignment of Wavelength as a prime key until after all the other if/elses have executed, and in the meantime it's extremely inconvenient to not be able to download AIA data of just one wavelength.

### System Details

- SunPy Version: 3.1.3
- Astropy Version: 4.2.1
- Python Version: 3.7
- OS information: OSX

**Comment by dstansby** [comment]
That example runs fine for me on sunpy version 3.1.3, astropy 4.2.1, python 3.9.7. Are you sure you're running it with sunpy 3.1.3, and not an older version?

**Comment by elastufka** [comment]
Hmmm, I tried it in a fresh terminal and then it executed... so maybe something was in conflict with earlier imports. I'll close this for now, hopefully it doesn't come up again!
