### ISSUE TITLE
Fixing flaky tests in `sunpy.database`

### ISSUE THREAD

**Issue by ConorMacBride** [sunpy/sunpy#5826]
### ~Make errors from `Database.fetch` available?~
~I'm trying to investigate some flaky remote data tests. A lot of the tests rely on asserting the length of the database after fetching. Would it be useful (and make sense) if there was some way to access errors from the `Downloader` in a `Database` object? If we can access the error we should be able to print which servers are failing in the test log.  In the code below `paths._errors` should contain any errors.~

~https://github.com/sunpy/sunpy/blob/bf3a54f6efd104faad4f4bb7347ba542cb2f16a2/sunpy/database/database.py#L412-L414~

### Possible bug if only some downloads fail
Also, in the above code, could there ever be a situation where `paths` and `query_result` are not paired correctly by `zip`? If there is an error downloading a file, it will not appear in `paths`. I've only seen `paths=[]` which is fine, but could you get `len(paths)==1` and `len(query_result)==2`?

---
### Specific server that's not responding consistently
From multiple networks I'm finding that `sdo7.nascom.nasa.gov` is taking a long time to respond but eventually gives a 500 internal server error. The response provides an email address to report the error. Any point doing that? See example:

```sh
curl "https://sdo7.nascom.nasa.gov/cgi-bin/drms_export.cgi?series=aia__lev1;compress=rice;record=335_1123200039-1123200039"
```

**Comment by dstansby** [comment]
1) Sounds good
2) I'm not sure?
3) Yeah, probably worth reporting the error if there's contact info.

**Comment by ConorMacBride** [comment]
Parfive was logging the failed downloads anyway, so the 1st item is no longer needed. (I just didn't see them the way I was running the tests.)

I opened a PR for the 2nd item.

I notice most of the recent download errors come from `sdo7.nascom.nasa.gov` so I will investigate that further and send them an email.
