### ISSUE TITLE
Replace use of pkg_resources with importlib.metadata

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5846]
Setuptools' `pkg_resources` is no longer recommended and from Python 3.7+ we should be using `importlib.metadata`: https://docs.python.org/3/library/importlib.metadata.html#distribution-versions

**Comment by nabobalis** [comment]
Man the API of `importlib.metadata` is garbage.

**Comment by Cadair** [comment]
Well that's upsetting.
