### ISSUE TITLE
Inheritance diagram for coordinate frames is empty

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#5857]
At the time of this post writing, the [class inheritance diagram for coordinate frames](https://docs.sunpy.org/en/latest/code_ref/coordinates/index.html#class-inheritance-diagram) is being rendered as empty:
![empty](https://user-images.githubusercontent.com/991759/151566853-d7aafce1-f66a-41ef-a0ac-3d608d9b5000.png)

This used to work fine: https://docs.sunpy.org/en/v3.1.2/code_ref/coordinates/index.html#class-inheritance-diagram

All other inheritance diagrams appear to render fine.

I suspect that the latest release for `graphviz` has a bug that affects this inheritance diagram in specific for some reason, but that would need to be confirmed.

**Comment by ayshih** [comment]
This will be fixed once we figure out how to install something other than graphviz 2.42 or 2.43 on RTD, both of which have the scaling bug

**Comment by nabobalis** [comment]
https://github.com/sunpy/sunpy/pull/6258 with the come is https://sunpy--6258.org.readthedocs.build/en/6258/code_ref/coordinates/index.html#class-inheritance-diagram

**Comment by ayshih** [comment]
Fixed by #6261
