### ISSUE TITLE
Inconsistent style for plotting maps in the example gallery

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5861]
### Provide a general description of the issue or problem.

In the example gallery, we plot a lot of `Map` objects, primarily in the "Map" and "Plotting" sections. We do this in several different ways. I've listed these below for some `Map` instance called `smap`.

1. Create a figure, but no axis
    ```python
    fig = plt.figure()
    smap.plot()
    ```
2. Create an axis, but a figure and don't pass the axis to `plot`
    ```python
    ax = fig.add_subplot(111,projection=smap)  # sometimes the 111 is excluded
    smap.plot()
    ```
3. Create a figure and an axis, but don't pass the axis to `plot`
    ```python
    fig = plt.figure()
    ax = fig.add_subplot(111,projection=smap)
    smap.plot()
    ```
4. Create a figure and an axis and pass the axis to `plot` (sometimes using the `axes=` kwarg, sometimes not)
    ```python
    fig = plt.figure()
    ax = fig.add_subplot(111,projection=smap)
    smap.plot(ax)
    ```
5. Create a figure and an axis and pass the axis to `plot` using the `axes=` keyword argument
    ```python
    fig = plt.figure()
    ax = fig.add_subplot(111,projection=smap)
    smap.plot(axes=ax)
    ```

Furthermore, sometimes when a figure and an axis are created, they are not returned to any object (i.e. they use the `pyplot` style).

Is this an issue? 
Are we OK with showing a variety of ways to create a plot of a map? Or should we standardize on a single way to create a plot of a map?
My preference is for option 5 as it is the most explicit and makes it easy to see how to build up more complex figures (i.e. with different kinds of projections in different subplots). 
If we standardize on that option, I think we should also enforce using the `axes=` keyword argument on all functions that accept it (e.g. `draw_grid`).

**Comment by Cadair** [comment]
:+1: to 5 as a pattern for the docs.

> If we standardize on that option, I think we should also enforce using the axes= keyword argument on all functions that accept it (e.g. draw_grid).

I don't think we want to change the behaviour of the methods if that's what you mean? But :+1: to using it in the docs everywhere.

**Comment by wtbarnes** [comment]
> I don't think we want to change the behaviour of the methods if that's what you mean? But 👍 to using it in the docs everywhere.

Oh no I didn't mean change the methods, just how we use them, i.e. if a method currently accepts an `axes` keyword, we should be using it in order to show explicitly that we are applying that action to that axis.

**Comment by ayshih** [comment]
Hmm.  I have feelings about this...

Standardizing on 5 might give novice users the impression that they always have to be so explicit, which could cool them on Python.

Furthermore, standardizing on 5 seems at odds with all the implicitness that pyplot provides.  If we're going to be fully explicit, why not go one step further and stop using pyplot altogether? (i.e., use `fig = Figure()`)

**Comment by dstansby** [comment]
> Furthermore, standardizing on 5 seems at odds with all the implicitness that pyplot provides. If we're going to be fully explicit, why not go one step further and stop using pyplot altogether? (i.e., use `fig = Figure()`)

pyplot provides implicit syntax for rendering figures to screen and paper (e.g. a GUI window), `plt.figure()`. Aside from choosing a plotting backend, users almost always don't need to worry about the rendering layer, making `plt.figure()` extremely useful.

On the other hand, it's much more common for users to care about which specific figures or axes are being plotted to. So I think it's reasonable and desirable to use `plt.figure()` and be implicit at a render level, but be explicit at a figure/axes creation level so users have full control.

I'm also +1 on option 5. I don't think we should apologise about being more explicit here, as it teaches users syntax that stays with them when they want to do more than plot a single axes on a single figure.

To save a line, I think another option (I haven't tested this) would be:
```python
fig, ax = plt.subplots(subplot_kw={'projection': smap})
``

**Comment by ayshih** [comment]
Standardizing on 5 seems extreme to me.  You all want even a simple example to show:
```python
fig = plt.figure()
ax = fig.add_subplot(111,projection=smap)
smap.plot(axes=ax)
```
instead of
```python
plt.figure()
smap.plot()
```
Why make the workflow appear more cumbersome than it needs to be?  If a user desires more complex plotting control, such as plotting maps side-by-side, they can look at our more complex examples.  Don't make a simple example more complex.  The following is an exaggeration, but what you're suggesting is akin to explicitly using the `u.Quantity()` constructor everywhere when working with `Quantity` instances just so a user won't be surprised in those situations when they will need to make use of the constructor.

If anything, I feel that *more* implicitness should be used.  Plotting code that can be simplified to approach 1 should be simplified accordingly.

**Comment by dstansby** [comment]
That makes sense - I agree that for simple examples where an axes isn't needed that implicit is okay. In that case can we just use a one liner `smap.peek()` instead?

**Comment by wtbarnes** [comment]
There are clearly some strong opinions on this issue and they seem to be rooted in our opinions of the implicit `pyplot` style.

> Why make the workflow appear more cumbersome than it needs to be? If a user desires more complex plotting control, such as plotting maps side-by-side, they can look at our more complex examples. Don't make a simple example more complex. 

That's a fair point. We don't want plotting code to get in the way of the thing we are trying to demonstrate (unless the example is explicitly about plotting). My main worry is that users will be stuck thinking that the implicit API is the only way to plot a map, but I guess that's what the more detailed examples are for.

I think the biggest problem here, and the main one I was trying to raise with this issue, is inconsistency. If we adopt Albert's suggestion of "minimum required verbosity", the examples still need proofreading with this in mind, e.g. don't create this axis or this figure or pass this keyword argument unless we absolutely need to.

**Comment by wtbarnes** [comment]
> That makes sense - I agree that for simple examples where an axes reference isn't needed that implicit is okay. In that case can we just use a one liner `smap.peek()` instead?

So I thought our consensus at the first coordination (nearly 2 years ago! 😱) was that we were going to shy away from `peek` because it yielded results to similar to plot but was far more limited in functionality. @ayshih can correct me if I'm wrong, but I think this was the motivation the `quicklook` method.

**Comment by wtbarnes** [comment]
> Perhaps it would be easier to start by agreeing on some styles to remove from the examples? I'd suggest as rules:
> 
>     * If an axes is explicitly created it should be passed to `smap.plot()` (rules out 2, 3 in original post)
> 
>     * It should always be passed as a keyword argument (rules out 4 in original post), as it is [not the first positional argument to plot](https://docs.sunpy.org/en/stable/api/sunpy.map.GenericMap.html?highlight=world_to_pixel#sunpy.map.GenericMap.plot)

👍 This sounds like a good plan to me. A follow up to that: should we always call `plt.figure()`? I suppose this isn't strictly necessary (e.g. in an example with only one figure), but I can see users being very confused if they already have some other `Figure` instance active and don't know to create another one and end up plotting their new data onto the previous figure.

**Comment by dstansby** [comment]
Ignore my `peek()` comment then 😉 . When using `plot()` I think it does make sense to always use `plt.figure()` beforehand.

**Comment by ayshih** [comment]
Sure, let's definitely clean up the examples (i.e., removing cases 2, 3, and 4).  Don't define variables unless you're going to use them (and use them correctly!).

I feel that we should always have `plt.figure()`.
