### ISSUE TITLE
Add test for creating a `TimeSeries` from a numpy array

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5864]
### Provide a general description of the issue or problem.

It should be possible to create a `GenericTimeseries` by passing a numpy `ndarray` to `sunpy.timeseries.TimeSeries`, where the first column of the `ndarray` is assumed to be the time index. This isn't covered by our test suite, but it should be. To do this a test needs to be added with the following steps:

- Create a numpy `ndarray` with the first column having datetime64 entries, and a second column of data
- Pass it to `sunpy.timeseries.TimeSeries`
- Check that the returned object has type `GenericTimeSeries`

**Comment by wtbarnes** [comment]
> Can I have a look at this issue? If you let me, it's gonna be my first issue. And I would like to know everything that I should as a first-time contributor.

Yes, please feel free! Re: advice for newcomers, a good place to start is [the newcomer's guide](https://docs.sunpy.org/en/latest/dev_guide/contents/newcomers.html) in the documentation. If you have questions, there is often someone around in the [chat room](https://openastronomy.element.io/#/room/#sunpy:openastronomy.org) that can help out as well.

**Comment by x249wang** [comment]
@ka3ax01 are you still planning on working on this issue? If not, I'd be happy to work on it 🙂

**Comment by nabobalis** [comment]
> @ka3ax01 are you still planning on working on this issue? If not, I'd be happy to work on it 🙂

There is already a PR open that is trying to fix this issue, it might be better to pick another one.
