### ISSUE TITLE
Review animated examples

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5881]
### Provide a general description of the issue or problem.

In https://github.com/sunpy/sunpy/pull/5870 at least one of the examples with animations was changed to show the animation in spinx gallery. We should review the all of the animated examples to make sure:

- [ ] The animations are showing up in the gallery
- [ ] The animations look good. For example, https://sunpy--5870.org.readthedocs.build/en/5870/generated/gallery/plotting/arrayanimatorwcs.html#sphx-glr-generated-gallery-plotting-arrayanimatorwcs-py doesn't look great as the second image is washed out, and there's only two images in the animation

**Comment by wtbarnes** [comment]
I am pretty sure between #5870 and #5871, I addressed the first item (I very well could've missed one).

Re: the second item, I agree. The colorbar limit issue is certainly easy enough to address. However, it seems weird to me that for the wcsanimator examples, there is an extra progress bar (the one that indicates the progression of time, but also does not seem to update). I'm guessing this just gets dropped into the png that is rendered? Is there a way to make the slider bars in the WCS animation play nicer with the matplotlib animations?
