### ISSUE TITLE
HMIMap not selected on HMI image file

### ISSUE THREAD

**Issue by dgarciabriseno** [sunpy/sunpy#5883]
### Describe the bug

When attempting to parse the latest HMI images from [LMSAL](https://sdowww.lmsal.com/sdomedia/hv_jp2kwrite/v0.8/jp2/HMI/2022/02/15/magnetogram/) HMIMap is not selected by the Map factory.

HMIMap is checking:
```python
return (str(header.get('TELESCOP', '')).endswith('HMI') and ...
```

but the data in these HMI files only shows SDO as the telescope, so GenericMap is selected.
I propose that it should change to  
```python
return str(header.get('INSTRUME', '')).startswith('HMI') and ...
```
This way it is consistent with how AIAMap is selected (AIAMap checks that instrument starts with AIA)

### To Reproduce

Use any recent HMI image from lmsal such as [this one](https://sdowww.lmsal.com/sdomedia/hv_jp2kwrite/v0.8/jp2/HMI/2022/02/15/magnetogram/2022_02_15__06_43_54_500__SDO_HMI_HMI_magnetogram.jp2)

```python
from sunpy.map import Map

hmi_map = Map('2022_02_15__06_43_54_500__SDO_HMI_HMI_magnetogram.jp2')
print(type(hmi_map)) # observe that type is GenericMap and not HMIMap
```

### What happened?

GenericMap is selected over HMIMap because the "TELESCOP" field in the fits data is only "SDO" and not "SDO/HMI" like the current HMIMap expects.

### Expected behavior

HMIMap should be selected since the file being parsed is an HMI file.

### System Details

General
#######
OS: Ubuntu (20.04, Linux 5.10.47-linuxkit)
Arch: 64bit, (x86_64)
sunpy: 3.1.3
Installation path: /root/sunpy3_venv/lib/python3.8/site-packages

Required Dependencies
#####################
astropy: 5.0.1
numpy: 1.22.2
packaging: 21.3
parfive: 1.5.1

### Installation method

pip

**Comment by dstansby** [comment]
That sounds like a good fix to make - would you be able to open a pull request with the change?

**Comment by ConorMacBride** [comment]
Do we know why this has changed? I assume this fix will also work for older HMI data? Page 9 of [this JSOC document](http://jsoc.stanford.edu/doc/keywords/JSOC_Keywords_for_metadata.pdf) lists the JSOC keywords. Also, it says AIA should start with `ATA`. I assume this is a typo, as AIAMap checks for `AIA`?

**Comment by wtbarnes** [comment]
I don't think there has been any change. Querying a recent (from 2/10/22) LOS magnetogram HMI file from the VSO, the expected instrument key is there. The files linked above appear to be JPG-2000 files (not FITS) processed specifically for Helioviewer (based on the link structure). I'm guessing its just that few people have tried reading these with sunpy.

The proposed fix should be fine though, as the HMI FITS files `INSTRUME` key also begins with "HMI".
