### ISSUE TITLE
EVE data retriever client retrieves 0CS data not 0C

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#5887]
### Describe the bug

The EVE data retriever client says that it retrieves EVE 0C data, but it actually retrieves EVE 0CS data. According to the instrument paper https://doi.org/10.1007/s11207-009-9487-6 the two are different products.

### To Reproduce

This is a documentation issue in the EVE data retriever client doc string.

### Expected behavior

The docstring and the `attrs.Level` description should explicitly say that 0CS data is downloaded by `EVEClient`.

**Comment by nabobalis** [comment]
Do we want to get both types or just one?
