### ISSUE TITLE
Replace the title of the "Downloading and plotting an HMI magnetogram" example with something more clear

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5888]
### Provide a general description of the issue or problem.

The "Downloading and plotting an HMI magnetogram" example offers an explanation of why an HMI map appears to be "upside down" when you plot it. However, there are still semi-frequent issues or mailing list posts asking this question. I think we should rename this example something far more explicit ("Why is my HMI magnetogram upside down?") that makes it immediately obvious to users that that is the example they should look at. The current title does not do that.

**Comment by nabobalis** [comment]
Lets do it.

**Comment by wtbarnes** [comment]
Alternatively, add it to the "Known Issues" page with a mini-gallery pointing to the example.

**Comment by nabobalis** [comment]
Why not both.
