### ISSUE TITLE
[3.1.4] Type error because of empty pytest.warns

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#5904]
### Describe the bug

While packagingsunpy 3.1.4 for Debian, I observerd a failure originating in a wrong call of `pytest.warns`.

### To Reproduce

Run the test suite on version 3.1.4.

### What happened?

I observed the following failure:
```
__________________ test_check_for_nonfinite_entries _____________________
    def test_check_for_nonfinite_entries():
        with warnings.catch_warnings(record=True) as warning_list:
            a = np.zeros((3, 3))
            b = np.ones((3, 3))
            check_for_nonfinite_entries(a, b)
    
        assert len(warning_list) == 0
    
        for i in range(0, 9):
            for non_number in [np.nan, np.inf]:
                a = np.ones(9)
                a[i] = non_number
                b = a.reshape(3, 3)
    
                with pytest.warns(SunpyUserWarning,
                                  match='The layer image has nonfinite entries.') as warning_list:
                    check_for_nonfinite_entries(b, np.ones((3, 3)))
    
                assert len(warning_list) == 1
    
                with pytest.warns(SunpyUserWarning,
                                  match='The template image has nonfinite entries.') as warning_list:
                    check_for_nonfinite_entries(np.ones((3, 3)), b)
    
                assert len(warning_list) == 1
    
>               with pytest.warns() as warning_list:
E               TypeError: warns() missing 1 required positional argument: 'expected_warning'

sunpy/image/tests/test_coalignment.py:104: TypeError
```

### Expected behavior

The tests should all pass. However, checking the [API of `pytest.warns`](https://docs.pytest.org/en/6.2.x/reference.html#pytest-warns), I would expect this error; I am wondering why this did not happen in the Github CI.

### System Details

* Sunpy 3.1.4
* Astropy 5.0.1
* pytest 6.2.5
* Python 3.9 and 3.10

### Installation method

pip

**Comment by dstansby** [comment]
This is probably because we are now using `pytest>=7` to test, and I don't think we have or document a minimum pytest dependency for running the tests. Would it be helpful for debian if we maintained compatability with pytest==6 for a while?

**Comment by olebole** [comment]
I don't know about the schedule of pytest in Debian. Since this is the only failure, I would propose to keep this one Py6 compatible. And checking the [pytest 7.0 API docs](https://docs.pytest.org/en/7.0.x/reference/reference.html#pytest-warns), I would assume that the `expected_warning` is required? At least, this one
```diff
index d2bcc5e..63c164e 100644
--- a/sunpy/image/tests/test_coalignment.py
+++ b/sunpy/image/tests/test_coalignment.py
@@ -101,7 +101,7 @@ def test_check_for_nonfinite_entries():
 
             assert len(warning_list) == 1
 
-            with pytest.warns() as warning_list:
+            with pytest.warns(Warning) as warning_list:
                 check_for_nonfinite_entries(b, b)
 
             assert len(warning_list) == 2
```
works for me. being a bit conservative would also help to ease backporting.

**Comment by dstansby** [comment]
Thanks for bringing this up - I've appied your fix, and when #5906 is merged we will test on the oldes pytest version released within the last 24 months (as per our dependency policy), which I imagine is fine for Debian.

**Comment by nabobalis** [comment]
In theory this is now fixed on our branches, hopefully when we do a release, you can confirm that for us!

**Comment by dstansby** [comment]
Yep, I think this is fixed. If it comes up again, feel free to comment or re-open.
