### ISSUE TITLE
Migrating to GH actions

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5913]
### Provide a general description of the issue or problem.

Since our ability to use Azure pipelines is dwindling, we've decided to re-create our CI on Github actions. This has already been started, but there is still plenty to do. Off the top of my head the list is below; **please edit/add items**!

## Tests

Write a GitHub workflow to replace the [azure pipelines tox workflow](https://github.com/OpenAstronomy/azure-pipelines-templates/blob/master/run-tox-env.yml), currently [here](https://github.com/sunpy/sunpy/blob/main/.github/workflows/python-test-workflow.yml) but ultimately should be in an openastronomy repo.

- [x] Install list of libraries
- [x] Install and execute tox
- [x] Install tox-pypi-filter
- [x] Codecov
- [x] Test inside a conda environment
- [N/A]  ~Skip CI doesn't skip required builds (if even possible)~ Don't think this is possible unless we use an alternative command such as `[sunpy skip]`.
- [x] (optional) xvfb
- [ ] (optional) Run inside docker container [32bit and python betas]

## Release

- [x] Write reusable action for building sdist & universal wheels (https://github.com/OpenAstronomy/action-build-sdist-and-wheel)
- [x] Add wheel builds using `cibuildwheel`
- [x] Write a reusable workflow which combines sdist, cibw and [pypi upload](https://github.com/marketplace/actions/pypi-publish) (https://github.com/OpenAstronomy/github-actions-workflows)
- [ ] (optional) add support for nightly builds with dev version support

## Sunpy specific things:

- [x] Cron jobs
- [x] Matrix notifications (https://github.com/KrazyKirby99999/matrix-commit)
- [x] Break the jobs up into stages like we had on Azure to fail early.
- [x] Build wheels and test them on branches (not PRs)
- [x] Implement release on successful test run on tag

**Comment by Cadair** [comment]
I had a call with Azure support today, and they were very helpful and understanding but ultimately unable to clarify what exactly was causing their automated abuse detection to shut us down, so I think we are left with few other options than to abandon ship.
