### ISSUE TITLE
Add 3-colour, tri-color or RGB example combing 3 wavelengths in one image/plot

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#5940]
### Describe the feature

Combing multi-wavelength images on a single plot is a really useful analysis tool and one way to do this is to make use of the the three RGB channels for three different wavelengths image. For example like this plot created by @Shilpi96
using code from @eoincarley

![image](https://user-images.githubusercontent.com/24570854/157230703-456c30bd-b184-4fa6-8303-b940a15de4d4.png)

### Proposed solution

Create an example showing how to to create such tri-color or RBG images combing 3 different wavelengths using sunpy Maps

**Comment by Shilpi96** [comment]
yes, this would be very useful. I would like to add an example.

**Comment by Vickyaryan33** [comment]
I want to work on this issues please assign me this issues [samaloney](https://github.com/samaloney)

**Comment by ayshih** [comment]
An example using `make_lupton_rgb()` was already added in #6459 (and then moved to the `sunkit-image` gallery in sunpy/sunkit-image#128).  Something similar can also be achieved using `mplcairo` (see #6835).

Closing this issue as completed
