### ISSUE TITLE
Fix oldesdeps build on 3.0.x branch

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5949]
### Describe the bug

On the 3.0.x branch, the `oldesdeps` build is failing with:
```python
       Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                      Cython is required to compile pandas from a development branch.
                      Please install Cython or download a release package of pandas.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pandas

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Because we pin `pandas<0.25`, I'm guessing this is because of a failed install from source (as opposed to a wheel). As a first attempt to fix perhaps installing `cython` on the `oldesdeps` build will fix this.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by ConorMacBride** [comment]
Fixed in https://github.com/sunpy/sunpy/pull/5953
