### ISSUE TITLE
IRIS SJI maps call undefined header in self.wavelength

### ISSUE THREAD

**Issue by schwarnoc** [sunpy/sunpy#5962]
### Describe the bug

When creating SJI maps by feeding data and header separately into a Map() and then doing a plot, this causes an error because it calls an undefined header.

### To Reproduce

import glob
from [astropy.io](http://astropy.io/) import fits
from [sunpy.map](http://sunpy.map/) import Map

data_file = glob.glob('IRIS/*_SJI_2832_*fits')
data_file.sort()

hdul = [fits.open](http://fits.open/)(data_file[0])
    
header = hdul[0].header
data = hdul[0].data

Map(data[0], header).plot()

### What happened?

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_73554/1651218312.py in <module>
      7 data = hdul[0].data
      8 
----> 9 Map(data[0], header).plot()

~/SunEnvironment/lib64/python3.8/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    251             # Call the original function with any equivalencies in force.
    252             with add_enabled_equivalencies(self.equivalencies):
--> 253                 return_ = wrapped_function(*func_args, **func_kwargs)
    254 
    255             valid_empty = (inspect.Signature.empty, None)

~/SunEnvironment/lib64/python3.8/site-packages/sunpy/map/mapbase.py in plot(self, annotate, axes, title, autoalign, clip_interval, **imshow_kwargs)
   2406             plot_settings_title = plot_settings.pop('title')
   2407         else:
-> 2408             plot_settings_title = self.latex_name
   2409 
   2410         # Anything left in plot_settings is given to imshow

~/SunEnvironment/lib64/python3.8/site-packages/sunpy/map/mapbase.py in latex_name(self)
    735     def latex_name(self):
    736         """LaTeX formatted description of the Map."""
--> 737         if isinstance(self.measurement, u.Quantity):
    738             return self._base_name().format(measurement=self.measurement._repr_latex_())
    739         else:

~/SunEnvironment/lib64/python3.8/site-packages/sunpy/map/mapbase.py in measurement(self)
    898         defaults to dimensionless units.
    899         """
--> 900         return self.wavelength
    901 
    902     @property

~/SunEnvironment/lib64/python3.8/site-packages/sunpy/map/sources/iris.py in wavelength(self)
     61         Taken from WAVELNTH, or if not present TWAVE1.
     62         """
---> 63         return header.get('wavelnth', header.get('twave1')) * self.waveunit
     64 
     65     @classmethod

NameError: name 'header' is not defined

### Screenshots

![image](https://user-images.githubusercontent.com/62298880/158391132-38d632bf-7ef4-41ba-b0c0-639a6da7a026.png)

### System Details

sunpy.__version__ : 3.1.3
astropy.__version__: 4.3.1

### Installation method

pip

**Comment by nabobalis** [comment]
Hello @schwarnoc,

We will get this fixed and released as soon as we can. 

I have a few questions if you don't mind.

1. What files are you using, can you link the observation? 
2. There is a new effort to get IRIS data in Python called [irispy-lmsal](https://pypi.org/project/irispy-lmsal/), it should allow you to do some analysis on the 3D cubes that the SJI and Spectra FITS files.

What are your use cases for using the IRISMap/sunpy, I want to get irispy-lmsal in a good enough state to replace sunpy and knowing what you want to do, would be helpful!
