### ISSUE TITLE
Rename `GenericMap.shift` to `GenericMap.shift_pointing`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5964]
### Provide a general description of the issue or problem.

This is a useful method that I only recently realized existed. However, I think the name is misleading. If I have a map `m` and I call `m.shift(dx,dy)`, I would naively expect the actual image data to be shifted. However, this function is not doing that. It is shifting the pointing by applying shift to the reference coordinate, thereby shifting the pointing.

I would recommend that we

* rename this function `shift_pointing`
* make `shift` an alias of `shift_pointing`
* deprecate `shift` in 4.0 so we can remove it in 4.1

Additionally, we also keep track of the modifications to the pointing by incrementing `GenericMap.shifted_value` every time `shift` is called. However, I'm not sure how useful this actually is as soon you write this map to disk, all record of this shift is lost. I'd also be inclined to deprecate `shifted_value` but I'm happy to hear arguments against it.

**Comment by dstansby** [comment]
How about being even more explicit and renaming to `shift_reference_coord`? Then it's super clear what the method does (and what it doesn't). To me `pointing` is a vague term/concept, but if others find it meaningful/well defined then I'm fine going with that 👍

**Comment by wtbarnes** [comment]
That's a good point. I usually think of "pointing" as the correspondence between `CRPIX` and `CRVAL`. `shift_pointing` might imply that you're altering both.
