### ISSUE TITLE
system_info shows that all optional dependancies are part of the extra all rather than the more specific one

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#5976]
```
>>> import sunpy
>>> sunpy.system_info()
==============================
sunpy Installation Information
==============================

General
#######
OS: Arch Linux (rolling, Linux 5.16.14-arch1-1)
Arch: 64bit, ()
sunpy: 3.1.5
Installation path: /home/stuart/.virtualenvs/sunpy-minimal/lib/python3.10/site-packages

Required Dependencies
#####################
parfive: 1.5.1
numpy: 1.22.3
astropy: 5.0.2
packaging: 21.3

Optional Dependencies
#####################
asdf: Missing, need asdf>=2.6.0; extra == "all"
beautifulsoup4: Missing, need beautifulsoup4>=4.8.0; extra == "all"
cdflib: Missing, need cdflib!=0.4.0,>=0.3.19; extra == "all"
dask: Missing, need dask[array]>=2.0.0; extra == "all"
drms: Missing, need drms>=0.6.1; extra == "all"
glymur: Missing, need glymur!=0.9.0,!=0.9.5,>=0.8.18; extra == "all"
h5netcdf: Missing, need h5netcdf>=0.8.1; extra == "all"
h5py: Missing, need h5py>=3.1.0; extra == "all"
matplotlib: Missing, need matplotlib>=3.2.0; extra == "all"
mpl-animators: Missing, need mpl-animators>=1.0.0; extra == "all"
pandas: Missing, need pandas>=1.0.0; extra == "all"
python-dateutil: Missing, need python-dateutil>=2.8.0; extra == "all"
reproject: Missing, need reproject; extra == "all"
scikit-image: Missing, need scikit-image<0.19,>=0.16.0; extra == "all"
scipy: Missing, need scipy>=1.3.0; extra == "all"
sqlalchemy: Missing, need sqlalchemy>=1.3.4; extra == "all"
tqdm: 4.63.0
zeep: Missing, need zeep>=3.4.0; extra == "all"
```

**Comment by x249wang** [comment]
Hi @Cadair 🙂 when I tried to run `sunpy.system_info()` on the development version of `sunpy` (instead of the latest release of v3.1.5), my Optional Dependencies section is a bit different:

<img width="248" alt="Screen Shot 2022-03-23 at 11 13 40 PM" src="https://user-images.githubusercontent.com/22362575/159837331-258fd2e3-2ce1-451a-8281-e5b630869865.png">

Looks like it's been updated already, but let me know if you're expecting something else than the above and I can do more digging!

**Comment by nabobalis** [comment]
Cadiar's version shows up if you not installed the optional dependencies. In your case, they are installed.

**Comment by x249wang** [comment]
Is `asdf` or `beautifulsoup4` considered an optional dependency? They just say "missing" for me, unless I'm looking at the wrong file (`sunpy/util/sysinfo.py`)?

**Comment by nabobalis** [comment]
Oh I didn't notice them, yes they are considered optional. In your case the group that needs them is not printing alongside them.

**Comment by x249wang** [comment]
With how `get_requirements` in `sysinfo.py` is currently implemented, only the package name is kept for missing packages, which was not the case in v3.1.5. Do they need to be added back, plus making the extra group more specific instead of all?

**Comment by nabobalis** [comment]
> Do they need to be added back, plus making the extra group more specific instead of all?

Yes. That is what we want.
