### ISSUE TITLE
Remove Mx/cm2 to G conversions in Map.

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#5994]
### Describe the feature

I have submitted a PR (https://github.com/astropy/astropy/pull/12975) to astropy to add Maxwell as a CGS unit. When we finally depend on that version (assuming it gets accepted), we should leave the units alone and remove any places where do do this conversion. 

In the mean time, we could add a custom unit to sunpy and use that in the mean time?

**Comment by dstansby** [comment]
+1 to adding a custom unit
