### ISSUE TITLE
Changes to make when we depend on Astropy 5.1

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#6016]
### Provide a general description of the issue or problem.

Remove the maxwell unit from Map:
https://github.com/sunpy/sunpy/pull/5998

**Comment by gmrpr321** [comment]
Hi everyone, I'm currently working on this issue and I would like to clarify the scope of the changes required. Should I simply modify the files to remove the maxwell unit from sunpy.map, or are there other parts of the code (outside map module)that I need to modify as well? This is my first time contibuting to open source and any guidance on this would be greatly appreciated. Thank you!

**Comment by Cadair** [comment]
Did this get done?

**Comment by nabobalis** [comment]
Err, yes
