### ISSUE TITLE
Use Matplotlib nightly wheels in devdeps testing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6019]
### Describe the feature

I think Matplotlib now have nightly wheels: https://github.com/matplotlib/matplotlib/pull/22733#issuecomment-1085269320. I haven't read the details, but thought I'd leave a note here that it would be good to use the nightly wheels to save a bit of time (and energy!) in our `devdeps` CI by using these instead of compiling from source.

**Comment by matthewfeickert** [comment]
:wave: In the event is helpful to whoever implements this, here are two example PRs from Scikit-HEP projects:
* https://github.com/scikit-hep/mplhep/issues/373
* https://github.com/scikit-hep/pyhf/pull/1835

**Comment by ConorMacBride** [comment]
Thanks for setting this up @matthewfeickert! This will really speed up our dev deps testing 🚀 We'll probably have to add it to the sunpy tox configuration but I think I've found a way.

**Comment by matthewfeickert** [comment]
> Thanks for setting this up @matthewfeickert! This will really speed up our dev deps testing

Sure thing! Likewise thank you for PR #6023 which taught me that you can use Azure Pipelines to basically host a package index like `astropy` does :exploding_head:! That's really interesting.

```console
$ docker run --rm -ti python:3.10 /bin/bash
root@0a0a311b1114:/# python -m venv venv && . venv/bin/activate  # avoid getting yelled at by pip
(venv) root@0a0a311b1114:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@0a0a311b1114:/# python -m pip install --upgrade --pre --extra-index-url https://pkgs.dev.azure.com/astropy-project/astropy/_packaging/nightly/pypi/simple/ astropy
(venv) root@0a0a311b1114:/# python -m pip show astropy
Name: astropy
Version: 5.1.dev781
Summary: Astronomy and astrophysics core library
Home-page: http://astropy.org
Author: The Astropy Developers
Author-email: astropy.team@gmail.com
License: BSD 3-Clause License
Location: /venv/lib/python3.10/site-packages
Requires: numpy, packaging, pyerfa, PyYAML
Required-by:
```

**Comment by ConorMacBride** [comment]
And I hadn't realised Anaconda did PyPI hosting also! I think PyPI compatible feeds are also on the (distant) roadmap for GitHub Packages.
