### ISSUE TITLE
Fix your hook over at reproject

### ISSUE THREAD

**Issue by pllim** [sunpy/sunpy#6026]
### Describe the bug

Sunpy asdf hook is causing reproject CI failure. Please fix it.

### To Reproduce

https://github.com/astropy/reproject/runs/5811289746?check_suite_focus=true

### What happened?

`astropy.io.misc.asdf` is deprecated. Use `asdf-astropy`.

### Expected behavior

`reproject` CI should pass.

### Installation method

pip

**Comment by nabobalis** [comment]
Thanks for the report, I just can't find any place where we import `astropy.io.misc.asdf`, would just adding the `asdf-astropy` as a dependency work?

**Comment by pllim** [comment]
Also, this is currently a deprecation warning, so nothing will break though it will in the future.

**Comment by Cadair** [comment]
I know what and why is happening here, I will add it to my endless list. We might want to just ignore it in reproject for now.

**Comment by pllim** [comment]
Okay, please see astropy/reproject#285
