### ISSUE TITLE
Submap having trouble returning submap if using map.bottom_left_coord and map.top_right_coord as input

### ISSUE THREAD

**Issue by amunozj** [sunpy/sunpy#6027]
### Describe the bug

Submap should in principle be able to handle plane of the sky coordinates coming from another sunpy map, but I'm getting an error when I try to use them.  I can work around them by first converting them to pixel coordinates in the map I want to crop, so there is something that can be fixed so that this is transparent to the user.

I don't always get the error, I suspect that the problem occurs when part of the field of view is offdisk.

### To Reproduce

```
from astropy.io import fits
from sunpy.map import Map


# Read an MDI magnetogram
mdi_path = 'C:/SHARPS/MDI/mdi.fd_M_96m_lev182.20110301_000000_TAI.data.fits'
MDI_fits = fits.open(mdi_path, cache=False)
MDI_fits.verify('fix')
MDImapLR = Map(MDI_fits[1].data, MDI_fits[1].header)
MDI_fits.close()
MDImapLR = MDImapLR.rotate(recenter=True)


# Read an HMI SHARP magnetogram crop
sharp_path = 'C:/SHARPS/SHARPS/hmi.sharp_720s.393.20110301_000000_TAI.magnetogram.fits'
sharp_fits = fits.open(sharp_path, cache=False)
sharp_fits.verify('fix')
sharp_map = Map(sharp_fits[1].data, sharp_fits[1].header)
sharp_fits.close()
sharp_map = sharp_map.rotate()


# Create submap and crash
MDISmapLR = MDImapLR.submap(sharp_map.bottom_left_coord, top_right=sharp_map.top_right_coord)
```

### What happened?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_68380/1515639453.py in <module>
----> 1 MDISmapLR = MDImapLR.submap(sharp_map.bottom_left_coord, top_right=sharp_map.top_right_coord)   # Input
      2 print('MDISmapLR: ', MDISmapLR.data.shape)
      3 
      4 MDISmap = MDImap.submap(sharp_map.bottom_left_coord, top_right=sharp_map.top_right_coord)       # Interpolated Input
      5 print('MDISmap: ', MDISmap.data.shape)

~\anaconda3\envs\sunpy\lib\site-packages\astropy\units\decorators.py in wrapper(*func_args, **func_kwargs)
    251             # Call the original function with any equivalencies in force.
    252             with add_enabled_equivalencies(self.equivalencies):
--> 253                 return_ = wrapped_function(*func_args, **func_kwargs)
    254 
    255             valid_empty = (inspect.Signature.empty, None)

~\anaconda3\envs\sunpy\lib\site-packages\sunpy\map\mapbase.py in submap(self, bottom_left, top_right, width, height)
   1766         # Clip pixel values to max of array, prevents negative
   1767         # indexing
-> 1768         bottom = int(np.clip(bottom, 0, self.data.shape[0]))
   1769         top = int(np.clip(top, 0, self.data.shape[0]))
   1770         left = int(np.clip(left, 0, self.data.shape[1]))

ValueError: cannot convert float NaN to integer
```

### Expected behavior

The expected behavior is that the submap would extract successfully as I know that the submap is present in the MDI magnetogram.   I can actually fix the problem with the following code:

```
import astropy.units as u

#  Convert the bottom-left and top-righ coordinates into pixel coordinates in the frame of reference of the map I want to crop
bottom_left = MDImapLR.world_to_pixel(sharp_map.bottom_left_coord)
bottom_left = [bottom_left.x.value, bottom_left.y.value]*u.pixel
top_right = MDImapLR.world_to_pixel(sharp_map.top_right_coord)
top_right = [top_right.x.value, top_right.y.value]*u.pixel

# Use them in the submap method
MDISmapLR = MDImapLR.submap(bottom_left, top_right=top_right)
```

### System Details

astropy                   4.3.1            py39h5d4886f_1    conda-forge
sunpy                     3.0.1            py39h832f523_0    conda-forge
python                    3.9.7           h7840368_3_cpython    conda-forge

OS: Windows

### Installation method

conda

**Comment by dstansby** [comment]
Sorry for taking so long to get back! This is a common issue, and we would like to improve feedback to the user when this happens; see https://github.com/sunpy/sunpy/issues/5598 for more info on that.

In a nutshell transforming an off-limb pixel from one coordinate frame to another results in an undefined coordinate with NaNs, because without knowing the 3D coordinate location in space there is no way to do the transformation. For Helioprojective coordinate systems this requires knowing not just the x/y coordinate, but the distance along the line of sight.

You can get around this by assuming a spherical screen though - something like this might work:
```python
from sunpy.coordinates import Helioprojective
with Helioprojective.assume_spherical_screen(MDImapLR.observer_coordinate):
    MDISmapLR = MDImapLR.submap(sharp_map.bottom_left_coord, top_right=sharp_map.top_right_coord)
```

Sorry I don't have time to try out a working example now, but let us know if that works or not for you!

**Comment by Cadair** [comment]
hey @amunozj did you manage to sort this out?

**Comment by nabobalis** [comment]
Hello @amunozj, if this bug is still occuring, please reopen this issue.
