### ISSUE TITLE
sunpy tests fail in future

### ISSUE THREAD

**Issue by bmwiedemann** [sunpy/sunpy#6030]
### Describe the bug

Similar to https://github.com/astropy/astropy/issues/10228 tests fail next year.

@bnavigator looked into details back then.

### To Reproduce

run sunpy tests in 2023-05-11

### What happened?

[  307s] /usr/lib64/python3.9/site-packages/astropy/time/core.py:2807: in update_leap_seconds
[  307s]     table = iers.LeapSeconds.auto_open(files)
[  307s] /usr/lib64/python3.9/site-packages/astropy/utils/iers/iers.py:1032: in auto_open
[  307s]     warn('leap-second file is expired.', IERSStaleWarning)
[  307s] E   astropy.utils.iers.iers.IERSStaleWarning: leap-second file is expired.

### Expected behavior

software should keep working independent of the date

### System Details

sunpy-3.1.5
astropy-5.0.4-1.1
python 3.8, 3.9, and 3.10
openSUSE Tumbleweed 20220403

**Comment by dstansby** [comment]
I think this is probably fine - there aren't leap second files that are valid that far into the future. For more discussion, see the linked astropy issue. Since that one has been closed, I'm going to close this one too.

**Comment by nabobalis** [comment]
I wonder since the error is raised in astropy, that needs to be fixed there? 

We could add a ignore to our test suite for that text?

**Comment by dstansby** [comment]
I didn't realise this was a packaging issue - can you provide more info on why the tests are being run "in the future"?

**Comment by nabobalis** [comment]
Adding that error message to our ignore list is easy enough if it will make packaging it easier.

I thought we had already taken care of the `ERFA function.*dubious` and the `distutils.sysconfig`.

**Comment by bnavigator** [comment]
> I didn't realise this was a packaging issue - can you provide more info on why the tests are being run "in the future"?

Quoting @bmwiedemann:
> As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
> The usual offset is +15 years, because that is how long I expect some software will be used in some places.
> This showed up failing tests in our python-astropy package build.
> See https://reproducible-builds.org/ for why this matters.

**Comment by dstansby** [comment]
I had a bit of a think, and the right solution might be to not error on warnings when packaging `sunpy`? We convert warnings to errors in development so we can catch and fix them early, but warnings don't stop `sunpy` working, so ignoring them when packaging is fine.

I don't know:
- If this is the correct solution, any opionons on this?
- If it is, how to implement it?

**Comment by bnavigator** [comment]
You remove this:

https://github.com/sunpy/sunpy/blob/419a2f95055e4f852388f9a431e25c1b3acdb2e8/setup.cfg#L129

**Comment by dstansby** [comment]
Yes, I was more wondering if it's vialbe to patch that line out when packaging 😃

**Comment by ConorMacBride** [comment]
In our build pipeline we ignore all warnings by disabling the pytest warning plugin with `-p no:warnings`:
https://github.com/sunpy/sunpy/blob/419a2f95055e4f852388f9a431e25c1b3acdb2e8/.github/workflows/ci.yml#L100
