### ISSUE TITLE
PyPi upload still not working 😢

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6042]
### Describe the bug

The PyPi upload seems to be past authentication issues, but now is giving:
https://github.com/sunpy/sunpy/runs/5854594381?check_suite_focus=true#step:4:49
```
 25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Binary wheel 'sunpy-3.0.7-cp310-cp310-linux_x86_64.whl' has an         
         unsupported platform tag 'linux_x86_64'.
```

Anyone got any guesses?

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by ConorMacBride** [comment]
Should be fixed in https://github.com/OpenAstronomy/build-python-dist/pull/9
