### ISSUE TITLE
“Dead batteries” in SunPy

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6070]
### Provide a general description of the issue or problem.

[PEP 594–Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) identifies a number of modules in the standard library to be deprecated and eventually removed. We rely on several of these in SunPy:

- cgi (via par five)
- xdrlib (in sunpy.io.special.read_genx)

Both of these have no alternative package listed and are scheduled for deprecation in 3.11 and removal in 3.13. There may be others that I’ve missed. Please edit the list above if so. 

Ideally prior to deprecation and certainly before removal, we need to think about how to deal with these changes in the standard library.

As a first cut, we should identify what functionality we are using exactly from these modules. If it is only one function, is it something we can just vendor? If it is larger, is there some alternative package we can rely on in its place?

This is more of a longer term discussion but the sooner we start thinking about this the better.

**Comment by Cadair** [comment]
cgi also in vso directly iirc.

**Comment by Cadair** [comment]
Well xdrlib we need to maintain the genx reader, so we can't not use it. Luckily it's only ~250 lines long: https://github.com/python/cpython/blob/main/Lib/xdrlib.py so we can just vendor that. Note when vendoring it, we aren't putting it in extern and just using it, we actually are going to have to put it in the main tree and have test coverage etc as we are going to be maintaining it long term.

The use of CGI is the HTTP header parser (i.e. here: https://github.com/sunpy/sunpy/blob/main/sunpy/net/vso/vso.py#L275) and exactly the same use in parfive (parfive copied VSO) luckily that function is like 30 lines total, so we could just put that in parfive, and import it from there into sunpy?

**Comment by wtbarnes** [comment]
For xdrlib, could we just create a separate sponsored package that is a full-on copy of that module? The thought of including tests for that in core does not make me feel great. 

Obviously there are downsides to maintaining it as a separate package too, but it at least provides that separation. I imagine a lot of these modules will pop up as standalone packages on pypi in the next few months so alternatively we could wait for some sufficiently reliable third party solution.

**Comment by Cadair** [comment]
It's not that complex and I bet our existing tests for genx cover a bunch of it anyway, I kinda feel like we might as well just adopt it?
