### ISSUE TITLE
asdf tests are failing on the asdf downstream tests

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6102]
### Describe the bug

The asdf and asdf-transform-schemas repos run our tests as part of their test suite. The changes we have introduced seem to have broken them. Two things are going wrong:

1) Out `@asdf_entry_points` decorator is causing the tests to be skipped.
2) The second example in the `heliographic_carrington-1.1.0.yaml` schema is failing.

My main concern here is why is it passing on our CI but not there.

**Comment by nabobalis** [comment]
https://github.com/sunpy/sunpy/pull/6103 was merged in
