### ISSUE TITLE
Document that `cmap` and `norm` can be passed to `MapSequence.plot`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6126]
In #5889, I added the ability to explicitly pass `cmap` and `norm` to `MapSequence.plot`. However, I forgot to document this. It should be explicitly stated in the docstring for `plot` that you can do this and thus override the values in `plot_settings`.

**Comment by nabobalis** [comment]
> Id like to handle this @nabobalis

Sure.
