### ISSUE TITLE
Add label for wheel building on PRs

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6130]
### Describe the feature

There are some PRs (e.g. https://github.com/sunpy/sunpy/pull/6129) where it is helpful to build wheels to check that the code change fixes or doesn't break wheel building. Matplotlib recently implemented the option to build wheels by adding a label to an issue: https://github.com/sunpy/sunpy/pull/6129 - it would be nice to replicate that here.

**Comment by Cadair** [comment]
I also would like to do this for the cron jobs as well.
