### ISSUE TITLE
add example of over plotting contour map that's off disk with `assume_spherical_screen`

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#6193]
### Describe the feature

Its come up a bit recently when over-plotting contours on-top of another map that go off-limb and needing to use `assume_spherical_screen`, an example in the gallery of this would be good.

**Comment by saumy-sh** [comment]
I would like to work on it. Can I get to know the specifics?

**Comment by wtbarnes** [comment]
Closed as duplicate of #6506
