### ISSUE TITLE
`RotatedSunFrame` should accept an `astropy.time.TimeDelta` object as `durations=` input

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6200]
### Describe the feature

If you do `map1.date - map2.date` and pass that into `durations=` you get a `TimeDelta` object which isn't a valid quantity so you have to call the `.to` method which seems silly.

**Comment by ayshih** [comment]
Sure, we could add special support for `TimeDelta`, but it might be better to go for an upstream fix for `QuantityAttribute' (and maybe use duck-typing!).

Regardless, if your `TimeDelta` is the difference between two times, your `map2.date` is almost certainly your frame time, so you should simply specify `rotated_time=map1.date` instead of specifying `duration`.

**Comment by nabobalis** [comment]
I am not sure that is quite what is required.

**Comment by Prtm2110** [comment]
one way to solve this is converting `TimeDelta` into `u.Quantity`  without making changes upstream in `QuantityAttribute`
```
if 'duration' in kwargs:
            duration = kwargs['duration']
            if isinstance(duration, TimeDelta):
                kwargs['duration'] = duration.to(u.day)
            elif isinstance(duration, u.Quantity):
                if duration.unit != u.day:
                    kwargs['duration'] = duration.to(u.day)
            else:
                raise ValueError("`duration` must be a `TimeDelta` or `Quantity` object.")
```
Should I open a PR for this? if yes converting `TimeDelta` in `u.days` is acceptable or we can go with `u.hr`?

**Comment by nabobalis** [comment]
I think an upstream fix would be a cleaner solution

**Comment by ayshih** [comment]
Upon further thought, this can't be upstreamed.  There's no general solution.  We need the `TimeDelta` object to be in the correct time scale for our specific purpose.
