### ISSUE TITLE
Better document how to save maps using compression.

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6214]
### Describe the feature

https://docs.sunpy.org/en/stable/generated/api/sunpy.map.GenericMap.html#sunpy.map.GenericMap.save should either explain how to save maps with compression, or should link to some external documentation (astropy?) that helps with this.

**Comment by mwhv2** [comment]
In the following [PyHC tutorial](https://heliopython.org/gallery/generated/gallery/retrieve_compress.html) (at the end), I show an example of compressing a Map using Astropy's [CompImageHDU](https://docs.astropy.org/en/stable/io/fits/api/images.html#compimagehdu). 

If you'd like, I'd be happy to write up a short description for the documentation.

**Comment by nabobalis** [comment]
If you could, that would be great! 

Based on your link, it would need to be compressed via the `save` method instead of using the `sunpy.io.fits module`.

**Comment by wtbarnes** [comment]
Yes, we want to direct people away from using `sunpy.io` directly (since it is now deprecated). I think you can just use the `hdu_type` kwarg to `save` to specify that you want a `CompImageHDU`.

**Comment by mwhv2** [comment]
Okay, I'll avoid using sunpy.io. Is the GenericMap.save documentation linked to above generated from the save docstring in mapbase? If so, would a PR be the best way to submit a small addition to it? (First time editing documentation)

**Comment by dstansby** [comment]
Yep, you can edit the docstring under
https://github.com/sunpy/sunpy/blob/3675d8638cb17e18aa9bddca50b145640b078a7b/sunpy/map/mapbase.py#L1477

I'd suggest adding a example using a new Examples section (see https://numpydoc.readthedocs.io/en/latest/format.html#examples), but if you'd prefer some plain text in the main body of the docstring would probably be fine too.
