### ISSUE TITLE
`make_fitswcs_header` should have an option to set the unit

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6219]
### Describe the feature

`make_fitswcs_header` provides kwargs for setting several non-WCS keywords such as wavelength, exposure time, instrument, etc. We should also provide the ability to set the unit by setting the `"BUNIT"` key. 

### Proposed solution

Add a `unit=...` kwarg that takes in either an `astropy.Unit` or a `str` that is then used to set the `"BUNIT"` key in the new header.

**Comment by dstansby** [comment]
Thoughts on restricting this to be a `Unit` and not a `str`? My thinking is that `make_fitswcs_header` is meant to be a high level interface between Python objects and strings in a FITS header, and a user can easily manually add a string if they want to.

**Comment by nabobalis** [comment]
Makes sense to me.
