### ISSUE TITLE
Map `submap()` errors with coordinate input that is not an actual `SkyCoord`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6252]
If you provide `GenericMap.submap()` with a coordinate frame with data (i.e., derived from `BaseCoordinateFrame`) rather than an actual `SkyCoord` instance, it errors when it doesn't need to:
```python
>>> import sunpy.map
>>> from sunpy.data.sample import AIA_171_IMAGE
>>> aia = sunpy.map.Map(AIA_171_IMAGE)
>>> aia.submap(aia.bottom_left_coord.frame, top_right=aia.top_right_coord.frame)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-1051101f270b> in <module>
      2 from sunpy.data.sample import AIA_171_IMAGE
      3 aia = sunpy.map.Map(AIA_171_IMAGE)
----> 4 aia.submap(aia.bottom_left_coord.frame, top_right=aia.top_right_coord.frame)

~\miniconda3\lib\site-packages\astropy\units\decorators.py in wrapper(*func_args, **func_kwargs)
    302             # Call the original function with any equivalencies in force.
    303             with add_enabled_equivalencies(self.equivalencies):
--> 304                 return_ = wrapped_function(*func_args, **func_kwargs)
    305 
    306             # Return

c:\users\ayshih\onedrive\code\sunpy\sunpy\map\mapbase.py in submap(self, bottom_left, top_right, width, height)
   1901             raise ValueError("Either top_right alone or both width and height must be specified.")
   1902         # parse input arguments
-> 1903         pixel_corners = u.Quantity(self._parse_submap_input(
   1904             bottom_left, top_right, width, height)).T
   1905 

~\miniconda3\lib\site-packages\astropy\units\quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    509             not (value.dtype.kind == 'O' and
    510                  isinstance(value.item(0), numbers.Number))):
--> 511             raise TypeError("The value must be a valid Python or "
    512                             "Numpy numeric type.")
    513 

TypeError: The value must be a valid Python or Numpy numeric type.
```

That's because the private method that handles `SkyCoord` input hasn't been made slightly more general to handle `BaseCoordinateFrame` input and registered to do so.

If for some reason we actively decide that coordinate input must be `SkyCoord`, we need to return a more helpful error message.

**Comment by ryuusama09** [comment]
I would like to try solving this issue @ayshih

**Comment by nabobalis** [comment]
> I would like to try solving this issue @ayshih

You do not need to ask people's permission to tackle an issue.

**Comment by Jett-Code** [comment]
So what are we expecting from this? To return a message whenever BaseCoordinateFrame is passed to submap?

**Comment by ayshih** [comment]
This is the existing private method to handle `SkyCoord` input:
https://github.com/sunpy/sunpy/blob/16dc3a37f7a01e37b97e59fcbab8660666a59ecb/sunpy/map/mapbase.py#L1981-L1995

This method probably already works with `BaseCoordinateFrame` input as long as this one line is changed appropriately:
https://github.com/sunpy/sunpy/blob/16dc3a37f7a01e37b97e59fcbab8660666a59ecb/sunpy/map/mapbase.py#L1988

You then should be able to register this existing method to be used for parsing `BaseCoordinateFrame` input in addition to being used for parsing `SkyCoord` input by add a second decorator to the method.

**Comment by OussCHE** [comment]
I am tackling this issue @ayshih .
