### ISSUE TITLE
Change the default scaling for EUI images to something other than linear

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6254]
Currently, the default scaling for EUI images is linear (see https://github.com/sunpy/sunpy/pull/5210#discussion_r619881522).  However, as we long ago decided for AIA (see https://github.com/sunpy/sunpy/pull/1432#issuecomment-112147204), using an inverse hyperbolic sine scaling (`AsinhStretch`) is generally more satisfying for EUV images given the typical distribution of pixel values.  Here's a comparison for recent EUI data:
![download (53)](https://user-images.githubusercontent.com/991759/173836189-69518170-a0a4-4b95-a0d8-c2df6eba30e2.png)

Unless there's a good reason to stick with the default of linear scaling, I suggest that we switch our default scaling of EUI images to match our default scaling of [AIA images](https://github.com/sunpy/sunpy/blob/7ecdcba2b8e451d5a2800c820752ba858ab84deb/sunpy/map/sources/sdo.py#L52-L53) (and [SUVI images](https://github.com/sunpy/sunpy/blob/7ecdcba2b8e451d5a2800c820752ba858ab84deb/sunpy/map/sources/suvi.py#L77-L78)).  (Curiously, our [EUVI images](https://github.com/sunpy/sunpy/blob/7ecdcba2b8e451d5a2800c820752ba858ab84deb/sunpy/map/sources/stereo.py#L37-L38) default to power-law stretching instead, for whatever reason.)

Of course, it'd be useful to know if the EUI team have a preference, which could be an entirely different scaling.

**Comment by hayesla** [comment]
I think its probably the best for them all (left plots are current linear, right plots are using `AsinhStretch`



![fsi_174_comparison](https://user-images.githubusercontent.com/4620298/174054879-f241ae94-54be-4d49-ae91-921c47a52eea.png)
![fsi_304_comparison](https://user-images.githubusercontent.com/4620298/174054898-ec615084-cf4d-4bda-ab5b-56dbc0441533.png)
![hri_174_comparison](https://user-images.githubusercontent.com/4620298/174054905-9c2efc4a-0c3d-4d6b-8644-27baabdb7119.png)
![hri_lya_comparison](https://user-images.githubusercontent.com/4620298/174054907-a74a4ae8-29bb-4cc4-bda6-c8fcbc235ec8.png)

**Comment by hayesla** [comment]
I've also just been chatting with Dave Long (on EUI team), and he said he's not aware of a preference from the team point of view, but he's going to find out what jhelioviewer uses and will let us know

**Comment by wtbarnes** [comment]
Well I really have no idea what the rationale was for choosing a linear scale.

I know that I initially tested this on images from 2020. Looking at the SOAR now, I see that the data from 2020 was archived on May of this year so maybe the data have been updated with a slightly different calibration that makes the Asinh scaling preferrable? Also, what level are these data? I believe my initial testing was on L1 data.
