### ISSUE TITLE
Bug prevents `RotatedSunFrame` instances from being pickled

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6279]
I haven't actually confirmed this, but I presume that the bug that prevents `SkyOffsetFrame` instances from pickled (astropy/astropy#9249) also means that `RotatedSunFrame` instances can't be pickled.  We should incorporate the analogous solution as astropy/astropy#13305.

We shouldn't need to fix `NorthOffsetFrame`, because that's just a wrapper to `SkyOffsetFrame`.

**Comment by EdBehn** [comment]
Is there a sunpy test that is failing due to this? It looks straight-forward to replicate the astropy fix (just a few lines of code). I'd like to be able to verify any fix.

**Comment by ayshih** [comment]
No, no existing test.  I don't think we have any pickling tests at all.

**Comment by EdBehn** [comment]
I wrote a simple unit test to see if the fix worked. Here it is:

    import pickle
    
    from astropy.coordinates import SkyCoord
    import astropy.units as u
    from sunpy.coordinates import RotatedSunFrame
    import sunpy.coordinates.frames as f
    
    def pickle_test() :
        base_frame = f.HeliographicStonyhurst(obstime="2001-01-01")
        rs_hgs = RotatedSunFrame(base=base_frame, duration=1*u.day)
        rotated_coord = SkyCoord(0*u.deg, 0*u.deg, frame=rs_hgs)
        lon = rotated_coord.transform_to(base_frame).lon
        
        return base_frame, pickle.dumps(rs_hgs), rotated_coord, lon
    
    def unpickle_test(base_frame, rs_hgs_pkl, rotated_coord, lon) :
        rs_hgs = pickle.loads(rs_hgs_pkl)
        
        assert(rotated_coord.transform_to(base_frame).lon == lon)
    
    if __name__ == '__main__' : 
        base_frame, rs_hgs_pkl, rotated_coord, lon = pickle_test()
        unpickle_test(base_frame, rs_hgs_pkl, rotated_coord, lon)

**Comment by ayshih** [comment]
The unit test ought to be more blunt:
```
def test_pickle_rotatedsunframe():
    base_coord = SkyCoord(0*u.deg, 0*u.deg, obstime="2001-01-01",
                          frame='heliographic_stonyhurst')
    rotated_coord = RotatedSunFrame(base=base_coord, duration=1*u.day)
    pickled_coord = pickle.loads(pickle.dumps(rotated_coord))
    assert pickled_coord == rotated_coord
```
