### ISSUE TITLE
Reproduce the "Where is STEREO?" plot in SunPy

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#6301]
### Describe the feature

The STEREO webpage has a handy figure showing where STEREO and other spacecraft are: https://stereo-ssc.nascom.nasa.gov/where.shtml . Given the existing examples in the SunPy gallery it seems that this should be reproducible using SunPy.

### Proposed solution

The solution would use a mix of existing examples that use the ability to get locations of spacecraft and planets.

**Comment by ayshih** [comment]
Wow, they sure are cramming a bunch of stuff into that figure now!

**Comment by ayshih** [comment]
Whoever works on this, `sunpy.coordinates.get_horizons_coord()` will be your friend

**Comment by wafels** [comment]
Part of the reason that I am interested in this is that getting the code to run that generated the STEREO webpage plot was a real pain due to IDL-related issues. My bet is the SunPy-based version of this figure would be easier to generate.

**Comment by Cadair** [comment]
http://solarmach.github.io/ does a good job of this already. Would be a good example gallery tho.

**Comment by jgieseler** [comment]
Yes, as @Cadair pointed out, **solarmach** should do what you want, or at least give you a good starting point doing this task in python using sunpy. The code of the python package can be found at https://github.com/jgieseler/solarmach

**Comment by Cadair** [comment]
The sunpy affiliated package process is documented here: https://sunpy.org/project/affiliated#open-review-process I would love to see you submit solar-mach :smile: 

Open an issue with [this template](https://github.com/sunpy/sunpy.org/issues/new?assignees=Cadair&labels=Affiliated+Package+Review&template=new_affiliated_package.md) to submit it when you are ready.

**Comment by jgieseler** [comment]
Yes, I know, it's on the agenda! But so many other things to do. 🙈 And the testing needs to be done correctly. 😬

**Comment by Jett-Code** [comment]
Hey, I've written a small code for this, can you check? 

```
import matplotlib.pyplot as plt
from astropy.time import Time
import datetime
from sunpy.coordinates import get_body_heliographic_stonyhurst

today = datetime.datetime.now()
obstime = Time(today)

from sunpy.coordinates.ephemeris import get_horizons_coord
aia = get_horizons_coord('STEREO-A', obstime)

planet_list = ['mars', 'sun', 'earth']
planet_coord = [get_body_heliographic_stonyhurst(
    this_planet, time=obstime) for this_planet in planet_list]
planet_list.append('STEREO-A')
planet_coord.append(aia)

fig = plt.figure()
ax = fig.add_subplot(projection='polar')
for this_planet, this_coord in zip(planet_list, planet_coord):
    ax.plot(this_coord.lon.to('rad'), this_coord.radius, 'o', label=this_planet)
ax.legend()
plt.show()
```
![image](https://user-images.githubusercontent.com/64737847/217342589-0fb46754-f677-4381-b06a-b94294199f2d.png)
