### ISSUE TITLE
Customise our user agent on CI

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6308]
Looking through the VSO user agent statistics it would be good to be able to exclude CI jobs.

**Comment by Cadair** [comment]
Hello @Vickyaryan33 we don't assign issues to people but you are free to work on it, please open a draft PR when you have something to share.

**Comment by jayantbhakar** [comment]
Hi, I would like to work on this issue. Can you add some more information here, to better comprehend the CI jobs to be excluded, maybe some screenshots or output of the response statistics would do. That would help a lot. Thanks.

**Comment by nabobalis** [comment]
The CI job to be exclude isn't on our side. It is to add more information to https://github.com/sunpy/sunpy/blob/main/sunpy/util/parfive_helpers.py#L15 to indicate if the sunpy test suite has made the server call or if it is a user.
