### ISSUE TITLE
Raise feedback message at first ever import of sunpy

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#6341]
### Provide a general description of the issue or problem.

The idea is that at the first ever import of sunpy, we would raise a nice message that tells users where and how to provide feedback if they have a problem.

A survey link maybe?

Features:

- Add a way to disable this via the config.
- We would write a hidden file to the sunpy/data directory to disable the message from being raised again.

**Comment by nabobalis** [comment]
@ehsteve if you have thoughts on the specific details you would like to see

**Comment by dstansby** [comment]
I think this is a really good idea!

**Comment by ConorMacBride** [comment]
Here's a relevant discussion: https://github.com/pygame/pygame/issues/1468

**Comment by nabobalis** [comment]
Unlike pygame, we will disable it after the first time.

**Comment by ConorMacBride** [comment]
Yeah, I think it's a great idea! Can we make it only show the message if a user (not a package) imports sunpy?

**Comment by nabobalis** [comment]
That is a good question, we will need to see if that's possible, otherwise I don't think we could go ahead with this?

**Comment by dstansby** [comment]
> Yeah, I think it's a great idea! Can we make it only show the message if a user (not a package) imports sunpy?

To do this I think you would need to run a check on where the file that's importing `sunpy` is located, and if that's in the site packages directory for the current Python environment. Sounds tricky, but this is Python so I bet it's possible somehow...

**Comment by Cadair** [comment]
I wonder if rather than doing that we can tell if the user has imported sunpy at an interactive prompt? i.e. the same kind of logic the display of Deprecation Warnings uses?

**Comment by ayshih** [comment]
That suggestion in specific would have trouble distinguishing between a package that isn't installed in `site-packages` (i.e., via `pip -e`) and actual user code.  Of course, one could argue that an editable install is a form of user code...

**Comment by ayshih** [comment]
@Cadair: What if a user's primarily uses sunpy by running Python scripts in a non-interactive way?

**Comment by ayshih** [comment]
As an aside, what logic is there for DeprecationWarning?  I thought they are ignored by default, and then some environments choose to expose them?

**Comment by Cadair** [comment]
https://peps.python.org/pep-0565/

**Comment by ehsteve** [comment]
I think most people after they first install manually check if they can import before running a script. I know I do. So they would see the message.

**Comment by ehsteve** [comment]
I like the idea of a survey link because then we can update the survey as needed and can make survey questions voluntary/optional so people can share whatever information they are comfortable with.

**Comment by ehsteve** [comment]
Another option, would be to maintain local statistics in a text file in the data directory of every user. Users might find it interesting to know things like how often they import sunpy on average per month, what module they use the most, etc. We could then encourage people to email that information to us if they are willing.
