### ISSUE TITLE
Header helper is bugged when creating a PCij matrix from a rotation angle for rectangular pixels

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6349]
As [noted on the mailing list](https://groups.google.com/d/msgid/sunpy/0352a093-e23d-4681-8113-e560bd2be92an%40googlegroups.com), the calculation in the header helper of a PCij matrix from a rotation angle is incorrect when working with rectangular pixels (`CDELT1` not equal to `CDELT2`) because `lam` is the inverse of what it should be:
https://github.com/sunpy/sunpy/blob/1fa82dd5e39282ab392ae1b8ac4ad3c66b6d65da/sunpy/map/header_helper.py#L156

The analogous bug was fixed in `GenericMap` in #5766, but was missed in the header helper.

**Comment by Cadair** [comment]
@ayshih Did this get fixed?

**Comment by ayshih** [comment]
Er, not as far as I'm aware?

**Comment by dstansby** [comment]
Here's a quick test that could be added along with a fix to check that header_helper and map are consistent:
```python
import sunpy.map
from sunpy.coordinates import frames
from astropy.coordinates import SkyCoord
import astropy.units as u
import numpy as np

rotation_angle = 10*u.deg
data = np.random.rand(1024, 1024)
my_coord = SkyCoord(0*u.arcsec, 0*u.arcsec, obstime="2017-08-01", observer = 'earth', frame=frames.Helioprojective)
header = sunpy.map.make_fitswcs_header(data, my_coord, rotation_angle=rotation_angle, scale=[1, 2] * u.arcsec/u.pix)
header_pc = np.array([[header['pc1_1'], header['pc1_2']], [header['pc2_1'], header['pc2_2']]])

# Create a copy that has CROTA2 instead of PCi_j matrix
header_nopc = header.copy()
for i in [1, 2]:
    for j in [1, 2]:
        del header_nopc[f'pc{i}_{j}']
header_nopc['CROTA2'] = rotation_angle.to_value(u.deg)

smap = sunpy.map.Map(data, header_nopc)

# PC matrix created with header helper and calculated by Map
# should be the same
print(smap.rotation_matrix)
print(header_pc)
```

Currently prints different matrices, verifying the bug. When fixed should print the same matrix:
```
[[ 0.98480775 -0.34729636]
 [ 0.08682409  0.98480775]]
[[ 0.98480775 -0.08682409]
 [ 0.34729636  0.98480775]]
```

**Comment by ayshih** [comment]
Heh, I don't know if I'd call the above a "quick" test, plus it only tests that the PCij calculation is consistent between `GenericMap.rotation_matrix` and `make_fitswcs_header()`.  Prior to #5766, they were consistent, but consistently wrong.

Regardless, with #6597:
```python
>>> print(smap.rotation_matrix)
[[ 0.98480775 -0.34729636]
 [ 0.08682409  0.98480775]]
>>> print(header_pc)
[[ 0.98480775 -0.34729636]
 [ 0.08682409  0.98480775]]
```
