### ISSUE TITLE
Document `sunpy.net.attr.or_` somewhere

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#6371]
### Describe the feature

The hidden feature of `sunpy.net.attr.or_` could be useful to some, should be on show somewhere

e.g. 

```python
wavelengths = [94*u.angstrom, 131*u.angstrom, 171*u.angstrom, 193*u.angstrom, 211*u.angstrom]
aia_search= Fido.search(a.Time("2022-02-15 21:40", "2022-02-15 23:00"), 
                        a.Instrument("AIA"), 
                        attr.or_(*[a.Wavelength(wav) for wav in wavelengths]))

```
### Proposed solution

add it to docs

**Comment by Cadair** [comment]
There's also `and_` but it's slightly less useful.

**Comment by dstansby** [comment]
I think this is a good candidate for a short example called something like "Searching for multiple wavelengths"

**Comment by Cadair** [comment]
I wonder if we want to take this opportunity to make this API nicer.

there's actually two ways of doing it as pointed out by @alasdairwilson in the chat:

```python
a.AttrOr([a.Wavelength(x) for x in waves])
```
Also works, which in this particular case avoids the `*` splat.

**Comment by hayesla** [comment]
oo yeah thats much nicer - I'll update the example
