### ISSUE TITLE
Private more parts of sunpy.io

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#6373]
### Provide a general description of the issue or problem.

Large parts of `sunpy.io` are used only and written for `Map` and `Timeseries`, they are not meant to be used by users to open files.

These are:

1. JPEG2000
2. CDF
3. FITS (this is already done)
4. ASDF
5. File tools

The readers we do support for users are:
1. ANA
2. GENX
3. SRS 

These should not be private.

**Comment by OussCHE** [comment]
I just read the code for FITS .If I understand correctly, you suggest to add `__all__` to the loading data classes that are used in `Map` ?

**Comment by OussCHE** [comment]
any ideas on ways to do that? looks like an interesting problem that I want to tackle.

**Comment by nabobalis** [comment]
> any ideas on ways to do that? looks like an interesting problem that I want to tackle.

I am not sure I follow. Privating this context means the removal from our public API, by adding an underscore. This was done for the FITS code in io.

A deprecation period needs to be added as well.

**Comment by gmrpr321** [comment]
I'm on this issue

**Comment by jgieseler** [comment]
I'm adding this here because it seems to be connected to this issue. In **sunpy 5.0.0rc1**, when trying to import (the in the future deprecated) `sunpy.io.read_cdf`, I get an _ModuleNotFoundError_, whereas I assume it should give a deprecation warning.

``` python
from sunpy.io.cdf import read_cdf
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from sunpy.io.cdf import read_cdf

File ~/anaconda3/envs/sunpy5rc/lib/python3.9/site-packages/sunpy/io/cdf.py:1
----> 1 from _cdf import *  # NOQA
      3 from sunpy.util.exceptions import warn_deprecated
      4 from . import _cdf

ModuleNotFoundError: No module named '_cdf'
```

The problem seems to be introduced by commit https://github.com/sunpy/sunpy/commit/21a7b5ec5b58023ca17eadb0124cde233e0db6bf

**Comment by nabobalis** [comment]
Thanks for the report. We will patch this.

**Comment by nabobalis** [comment]
> I'm adding this here because it seems to be connected to this issue. In **sunpy 5.0.0rc1** (installed via `pip install --pre sunpy==5.0.0rc1`), when trying to import (the in the future 
> NB: I still have an import of `sunpy.io.read_cdf` in [jgieseler/solo-epd-loader](https://github.com/jgieseler/solo-epd-loader) that I need to replace with the `Timeseries`. Until this is done, solo-epd-loader would be incompatible with sunpy5.0.0rc1.

You can use the read_cdf from the now private module as a temporary workaround.
