### ISSUE TITLE
The future of database

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#6374]
### Provide a general description of the issue or problem.

Currently database has several problems, among them:

1. No maintainer
2. No changes to the core code in several years
3. It has no integration with sunpy.net.fido.

The plan is to eventually replace with and we did plan but not run a GSoC project to create a replacement.

This replacement would not a drop in replacement, there would be no way to migrate from the current database, to the new version of database.

So I want to deprecate the entire package, in the following way:

1. Add a FutureWarning saying we will be removing it, email the sunpy dev mailing list if you use it.
2. Turn this FutureWarning in to a proper deprecation warning in 5.1(?)
3. Remove it in 6.0 (?)

**Comment by dstansby** [comment]
Is the goal to get a `FutureWarning` in 4.1?

**Comment by nabobalis** [comment]
I thought so.

**Comment by nabobalis** [comment]
Database is now removed from 6.0
