### ISSUE TITLE
Minigallery is not placing thumbnails on the same line

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6377]
At time of this writing, our latest documentation builds are not showing minigalleries with thumbnails on the same line.  Here's what the `stable` build [is currently showing](https://docs.sunpy.org/en/stable/code_ref/coordinates/rotatedsunframe.html):

![incorrect](https://user-images.githubusercontent.com/991759/186055747-ec6a00e0-80fd-4bbc-ae82-2fe93f474d2a.png)

when it should instead [look like this](https://docs.sunpy.org/en/v4.0.4/code_ref/coordinates/rotatedsunframe.html) (this is the `4.0.4` build):

![correct](https://user-images.githubusercontent.com/991759/186055809-082b6fbc-568b-417b-8165-ef1fdec4f229.png)

Quite possibly an upstream change in `sphinx-gallery` rather than our "fault", but needs investigation.

**Comment by ConorMacBride** [comment]
This has been fixed in the latest release of sphinx-gallery https://github.com/sphinx-gallery/sphinx-gallery/issues/992

**Comment by nabobalis** [comment]
We can upgrade the min pin version for the gallery to prevent this in future.

**Comment by dstansby** [comment]
This looks fixed now: https://docs.sunpy.org/en/stable/code_ref/coordinates/rotatedsunframe.html. Will pin sphinx-gallery in a PR
