### ISSUE TITLE
Trying to open METIS data fails

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6383]
### Describe the bug

Using data available at https://owncloud.ia2.inaf.it/index.php/s/qzgQzZKkp8hVMUT?path=%2FL2%2F2022%2F01

### To Reproduce

```python
from sunpy.map import Map
Map('solo_L2_metis-uv-image_20220101T032900_V01.fits')
```

```
Traceback (most recent call last):
  File "/Users/dstansby/Downloads/test.py", line 2, in <module>
    Map('solo_L2_metis-uv-image_20220101T032900_V01.fits')
  File "/Users/dstansby/Downloads/sunpy/map/map_factory.py", line 331, in __call__
    new_map = self._check_registered_widgets(data, meta, **kwargs)
  File "/Users/dstansby/Downloads/sunpy/map/map_factory.py", line 381, in _check_registered_widgets
    return WidgetType(data, meta, **kwargs)
  File "/Users/dstansby/Downloads/sunpy/map/mapbase.py", line 222, in __init__
    self._validate_meta()
  File "/Users/dstansby/Downloads/sunpy/map/mapbase.py", line 1367, in _validate_meta
    raise MapMetaValidationError('\n'.join(err_message))
sunpy.map.mapbase.MapMetaValidationError: Image coordinate units for axis 1 not present in metadata.
Image coordinate units for axis 2 not present in metadata.
See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata for instructions on how to add missing metadata.
```

**Comment by Cadair** [comment]
Specifically this issue is that the METIS file contains three HDUs all 2D ImageHDUs. I assume that the latter two are auxiliary info, which have insufficient metadata to be loaded as a map.

I think this is a bug in the map factory itself, where if some inputs fail to load we should return the maps which did load and throw warnings for the others.

There is an interesting issue here for better support for METIS though, there is no way to override this behaviour in a per-map source basis, so we would always end up throwing that warning for everyone opening METIS data forever.

**Comment by hayesla** [comment]
the other two HDUs contain 2D data arrays of map shape which are a quality array, and an error array, so probably useful

A source should maybe multiple the hdu[0].data *hdu[1].data (where hdi[1].data is a 1, 0 array).

**Comment by Cadair** [comment]
That's a much bigger feature request. Map has exactly 0 support for that kind of thing at the moment, both from a loading and a holding in memory issue.

**Comment by hayesla** [comment]
we should reach out to the team to see what they want the final "map" product to be?

**Comment by Cadair** [comment]
If you manually bypass the FITS loader which tries to read all the HDUs the primary HDU loads great into `GenericMap` with only one warning about `BUNIT`.

**Comment by hayesla** [comment]
so after a quick look into this and some playing around, there are 6 L2 data products

* polarised brightness (filename `solo_l2_metis_vl_pb....fits`)
* total brightness (filename `solo_l2_metis_vl_tb....fits`)
* fixed polarisation (filename `solo_l2_metis_vl_image....fits`)
* polarisation angle (filename `solo_l2_metis_vl_pol-angle....fits`)
* stokes parameters (filename `solo_l2_metis_vl_stokes....fits`)
* UV image (filename `solo_l2_metis_uv_image....fits`)

The structure of the files  (apart from the Stokes parameters one) is that there is 3 hdu's, with the WCS info in primary header:

* Primary -> image (nxn)
* extension 1 -> quality matrix (nxn)
* extension 2 -> error matrix (nxn)


The stokes files has 5 hdus
* Primary -> Stokes I
* extension 1-> Stokes Q
* extension 2-> Stokes U
* extension 3 -> quality matrix
* extension 4 -> error matrix

So I guess the question is how this should be done? Should you pass a Metis map and it will return just the primary image map? but what about the Stokes image? should it return a list of maps of the different Stokes parameters?

**Comment by hayesla** [comment]
but also the data looks a bit weird if you don't block out what *should* be blocked out (i.e. coronagraph)

without blocking out 1.6 R_sun
![metis_test](https://user-images.githubusercontent.com/4620298/186874964-8ee5034d-86b7-4ed7-8fa4-8cb2b54ed17b.png)

but if you mask it out (based on what it says it should be in the paper rather than any info in the header)
![metis_test2](https://user-images.githubusercontent.com/4620298/186875045-2dcd6c30-090a-48c4-bb53-4bc7bc1d0093.png)

**Comment by Cadair** [comment]
You can load a metis file by passing `silence_errors=True`

**Comment by hayesla** [comment]
following discussion - may be good to have custom readers in sunkit-instr at the moment and talk to instrument team

**Comment by dstansby** [comment]
I just fired an email off to the METIS team asking about this, and cc'ed @hayesla

**Comment by dstansby** [comment]
Updates from the email thread:
- The header issue (no WCS info in other HDUs) will be fixed for the official data release to the SOAR, so no sunpy action there.

For the occulting disc issue, there are two different circles, the actual physical occulter which is always centered on the Sun and the manually added image mask which is centered on the data array. Because the solar center != the array center in general the artificial image mask is smaller than the image occulter to avoid losing some coronal signal. But I think this is a choice METIS have made about how they're processing they're data, so nothing to fix here on the sunpy side. If someone wants to they can implement a function to deal with this in `sunkit_instruments`, but I don't think it's high priority or worth tracking.

So this can be closed 🎉  - thanks @hayesla for investigating.
