### ISSUE TITLE
Improve tabulation in TimeSeries repr

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6412]
### Describe the feature

The default `repr` for `TimeSeries` has some tabulation that's all over the place:
```python
SunPy TimeSeries
----------------
Observatory:                 GOES-15
Instrument:          <a href=https://www.swpc.noaa.gov/products/goes-x-ray-flux target="_blank">X-ray Detector</a>
Channel(s):          xrsa<br>xrsb
Start Date:          2011-06-07 00:00:00
End Date:            2011-06-07 23:59:58
Center Date:                 2011-06-07 11:59:58
Resolution:          2.048 s
Samples per Channel:                 42177
Data Range(s):               xrsa   3.64E-06<br>xrsb   2.54E-05
Units:               W / m2
```

It would be good to fix this so all the values on the RHS start in the same character column.

**Comment by mwhv2** [comment]
I'd be happy to fix this. I wrote this with the HTML repr in mind, and forgot to look at the default formatting.

**Comment by dstansby** [comment]
That would be great 😄

**Comment by nabobalis** [comment]
> @nabobalis , if the issue is not yet tackled , i can help with this

Sure
