### ISSUE TITLE
GOES XRS observatory attribute not parsing correctly

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#6417]
### Describe the bug

another GOES/XRS issue ...

For the GOES 13,14, 15, from what I can tell the meta information within the netcdf file does not include the GOES Satellite Number but rather gives 'GOES 1-15 X-ray Irradiance Sensor (XRS)'. The way we are parsing out the `observatory` attribute is just to read this as GOES-15 but this is the same for GOES 13 and 14. 

Hence if you read in the GOES 13 or 14 data the `observatory` attribute will give you `GOES-15`.
This is an issue for the temperature/emission measure calculation (that will very soon be PR'd to sunkit-instruments) needs to know the satellite to use the correct response. 

(not an issue for GOES 16 and 17).

### To Reproduce

```python
>>> goes_15 = ts.TimeSeries("sci_gxrs-l2-irrad_g15_d20190301_v0-0-0.nc")
>>> goes_14 = ts.TimeSeries("sci_gxrs-l2-irrad_g14_d20190301_v0-0-0.nc")


>>> goes_15.observatory
'GOES-15'
>>> goes_14.observatory 
'GOES-15'
```

I think the only way to go around this is to take the satellite number from the file name itself (for GOES 13, 14, 15).

**Comment by alasdairwilson** [comment]
This definitely worked at some point, maybe it broke before it was merged? There are multiple choices for what meta info to use here: 

        pattern_new = ("{}sci_gxrs-l2-irrad_g{SatelliteNumber:02d}_d{year:4d}{month:2d}{day:2d}_{}.nc{}")
        
Is how that era of goes was supposed to be matched but it looks like maybe the order at which the metadata was checked has been changed. I can take a look at it?

**Comment by hayesla** [comment]
yeah so it looks like it pulls the `id`  from the meta here:

https://github.com/sunpy/sunpy/blob/main/sunpy/timeseries/sources/goes.py#L133

so that it reads from the netcdf attribute `instrument` which is `GOES 1-15 X-ray Irradiance Sensor (XRS)` and then hence uses the pattern 

`pattern_inst = ("GOES 1-{SatelliteNumber:02d} {}")` which return 15

**Comment by hayesla** [comment]
But yes please have a look for sure!
