### ISSUE TITLE
Change all uses of `GenericMap.world_to_pixel/pixel_to_world` to `GenericMap.wcs.world_to_pixel/pixel_to_world`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6435]
### Provide a general description of the issue or problem.

As noted in #4701, the consensus is that we should "soft" deprecate the usage of the `pixel_to_world` and `world_to_pixel` methods directly on `GenericMap` in favor of those methods on `GenericMap.wcs`.

We should go through the entire codebase and convert all usage of `GenericMap.{pixel_to_world, world_to_pixel}` to `GenericMap.wcs.{pixel_to_world, world_to_pixel}`.

**Comment by nabobalis** [comment]
> I'd like to handle this @nabobalis

Sure.
