### ISSUE TITLE
Provide guidance on setting up a development environment with all dependencies installed through `conda`?

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6445]
Currently, our developer's guide tells users to use `conda` to set up an environment and install `pip`, and then use `pip` rather than `conda` to install all of `sunpy`'s dependencies.  If a user subsequently uses `conda` to update any dependencies in that environment, that environment may become broken for further `conda` use.

We could consider providing guidance on how to best use a local repo for `sunpy` but still use  `conda` for all of the dependencies, e.g.:
```
conda install sunpy
conda remove --force sunpy
pip install --no-build-isolation --no-deps -e .
```

**Comment by nabobalis** [comment]
The reason I didn't add that and said to use pip is that using `conda install sunpy`, you still miss out on some testing dependencies we do not add to the conda recipe. 

Tox being the main one, but if you wanted to use pytest directly, there are a set of other packages to install. 

We could add those instructions with a note telling people about that fact?

**Comment by Cadair** [comment]
In my opinion it's cleaner to install everything into a conda env with pip *and then remember you did so*. I get that that last part can be tricky though.

The other reason I am not sure this is a good idea is what Nabil said about the dev and testing dependencies.

**Comment by ayshih** [comment]
I'll note that there are packages that are significantly more straightforward to install via `conda` than other means.  As such, I myself do precisely what I've suggested in order to sustain the mix of `conda` and `pip`.  (Ideally, `conda develop` would be useful in this regard, but apparently that command is not recommended for use by `conda` folks.)  It just requires one to remember to `conda remove --force` `sunpy`/`astropy`/whatever whenever `conda` installs a release version to satisfy a dependency, which masks the editable install.

> The reason I didn't add that and said to use pip is that using `conda install sunpy`, you still miss out on some testing dependencies we do not add to the conda recipe.

It'd be straightforward to have a file in our repo (e.g., `conda_dev_dependencies.txt`) that a user could pass to `conda install --file` in order to install those additional dependencies.  In fact, we essentially already have such a list in our `tox.ini`, so we just have to move it out to a separate file (cleaning it up at the same time), and then have `tox.ini` make use of that file.

> In my opinion it's cleaner to install everything into a conda env with pip _and then remember you did so_. I get that that last part can be tricky though.

At minimum, our developer's guide should have a note that, despite the environment being created by `conda`, the use of `conda` to install packages in that environment is not encouraged, because I think that is not intuitive.  A more active option would be to name the environment with a constant reminder, e.g., `sunpy-dev-pip-only`.  An extreme option: it'd probably be possible to futz with the environment-specific configuration so that `conda` can't actually be used to install packages.

**Comment by nabobalis** [comment]
> I'll note that there are packages that are significantly more straightforward to install via `conda` than via other means. 

100%, when I used to work with climate data, there were some really strange formats that needed compiled binaries (and some python bindings) and conda installing them was so much easier. So I ended up mixing both. 

I would say however that only people who are familiar with mixing both or at the very least not new to Python should do this and for me, that means we don't suggest it in the developer guide which we point a lot of new contributors to (unless this this somewhere else in the dev docs?).

> It'd be straightforward to have a file in our repo (e.g., `conda_dev_dependencies.txt`) that a user could pass to `conda install --file` in order to install those additional dependencies. In fact, we essentially already have such a list in our `tox.ini` for the `conda` build, so we just have to move it out to a separate file (cleaning it up at the same time), and then have `tox.ini` make use of that file.

We can do this, lets do it.

> At minimum, our developer's guide should have a note that, despite the environment being created by `conda`, the use of `conda` to install packages in that environment is not encouraged, because I think that is not intuitive. A more active option would be to name the environment with a constant reminder, e.g., `sunpy-dev-pip-only`. An extreme option: it'd probably be possible to futz with the environment-specific configuration so that `conda` can't actually be used to install packages.

We can do this too.

**Comment by ayshih** [comment]
> I would say however that only people who are familiar with mixing both or at the very least not new to Python should do this and for me, that means we don't suggest it in the developer guide which we point a lot of new contributors to (unless this this somewhere else in the dev docs?).

Sure, the page in question is admittedly the newcomer's guide within the developer's guide, so the `pip`-only approach might be the best for a newcomer.  In whatever disclaimer is added to that page to notify people that using `conda` in the development environment might eventually cause issues, there can be a footnote that points to a separate page with the guidance on how to mix `conda` and editable installs.

**Comment by nabobalis** [comment]
Do we need to have a separate advanced dev guide?
