### ISSUE TITLE
Figure devdeps tests failing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6496]
### Describe the bug

Lots of devdep figure tests are failng with `E               TypeError: WCSAxes.__init__() got multiple values for argument 'wcs'`. (e.g. see https://app.circleci.com/pipelines/github/sunpy/sunpy/19257/workflows/7211a8f2-1270-4dad-a7c6-8c0bfa4b14fe/jobs/81368) I'm guessing this is an upstream issue in astropy or Matplotlib, but reporting here so we have track of it.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by dstansby** [comment]
Reported upstream at https://github.com/astropy/astropy/issues/13873

**Comment by ConorMacBride** [comment]
This was fixed in https://github.com/astropy/astropy/pull/13880
