### ISSUE TITLE
Add a gallery example showing how to use `mplcairo` for blending

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6517]
`matplotlib` itself provides only alpha-based transparency for overlaying an image on top of another image, which can be quite limiting when attempting to produce nice-looking composite images.  `mplcairo` provides the usual variety of blending operators for image overlays, so we should have a tutorial for using `mplcairo`.  As far as our documentation goes, we have to configure the backend in the way needed to get Sphinx to do what we want.

Example example:
```python
import matplotlib; matplotlib.use("module://mplcairo.qt")
import matplotlib.pyplot as plt
from mplcairo import operator_t

import astropy.units as u

import sunpy.map
import sunpy.data.sample
from sunpy.coordinates import Helioprojective

a171 = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
a131 = sunpy.map.Map(sunpy.data.sample.AIA_131_IMAGE)
with Helioprojective.assume_spherical_screen(a171.observer_coordinate):
    a131 = a131.reproject_to(a171.wcs)

fig = plt.figure()
ax = fig.add_subplot(projection=a171)

_ = a171.plot(clip_interval=(1, 99.9995)*u.percent)
im131 = a131.plot(clip_interval=(1, 99.95)*u.percent)

operator_t.SCREEN.patch_artist(im131)

ax.set_title('mplcairo composite using screen blending')

plt.show()
```
![mplcairo composite example](https://user-images.githubusercontent.com/991759/198420923-3db92465-bef9-4a0d-a5ec-913aed9e170b.png)

**Comment by Satan-Claws** [comment]
I've made additions to the /plotting folder, can someone check if this is correct?
I can't open a PR until my old PR is closed.
https://github.com/Satan-Claws/sunpy/blob/Satan-Claws-mplcairo/examples/plotting/mplcairo_blending.py

**Comment by ayshih** [comment]
> I've made additions to the /plotting folder, can someone check if this is correct?

It looks like you've simply added brief comments to my example script above, so I imagine that it produces the correct output when run from a terminal.  Stuff that needs to be done:

- Add actual narrative to the example so that it is a tutorial.
- Ensure that Sphinx (on Read the Docs) renders the example correctly.  It's possible that a different Matplotlib backend needs to be selected for the documentation build, and we need to make sure that changing the backend here in this fashion doesn't muck up the rendering elsewhere in our documentation.

> I can't open a PR until my old PR is closed.

You can have more than one PR open at a time.  You already have this modification on a separate Git branch, so you simply need to create the PR from that branch instead of your `main` branch.

**Comment by Satan-Claws** [comment]
> > I've made additions to the /plotting folder, can someone check if this is correct?
> 
> It looks like you've simply added brief comments to my example script above, so I imagine that it produces the correct output when run from a terminal.  Stuff that needs to be done:
> 
> - Add actual narrative to the example so that it is a tutorial.
> - Ensure that Sphinx (on Read the Docs) renders the example correctly.  It's possible that a different Matplotlib backend needs to be selected for the documentation build, and we need to make sure that changing the backend here in this fashion doesn't muck up the rendering elsewhere in our documentation.
> 
> > I can't open a PR until my old PR is closed.
> 
> You can have more than one PR open at a time.  You already have this modification on a separate Git branch, so you simply need to create the PR from that branch instead of your `main` branch.

Okay I'll change the text to make it more of a tutorial. I'll check again if the display fits or not and then will create a PR

**Comment by Satan-Claws** [comment]
I'm sorry I wasn't able to work on this, I was attending a festival at home.
I've re-setup everything on WSL since mplcairo has issues working in Windows (in my virtual env, works fine at base). I'll install mplcairo, look at the docs made and will open a PR as soon as I make the correct tutorial.

**Comment by Telomelonia** [comment]
@ayshih 
will it be enough if we 
- add some content about `mplcairo` in docs/intro/maps.rst 
- add this same tutorial in examples/plotting
- and maybe I can link this tutorial to docs in backend.

**Comment by Telomelonia** [comment]
@ayshih 
I've added the PR, please suggest any changes.

**Comment by nabobalis** [comment]
How do we feel about this example being in sunkit-image instead?

**Comment by ayshih** [comment]
> How do we feel about this example being in sunkit-image instead? 

For what reason?  To isolate the mplcairo dependency?  It seems silly given that the example doesn't use any sunkit-image functionality.

**Comment by Telomelonia** [comment]
@ayshih 
For using mplcairo I had to both 
- add dependency ... this I can do by adding mplcairo in setup.cfg
- update matplotlibrc confg file by adding `backend: module://mplcairo.qt`
How I can achieve this second step?

**Comment by ayshih** [comment]
> * update matplotlibrc confg file by adding `backend: module://mplcairo.qt`
>   How I can achieve this second step?

The `matplotlibrc` way of selecting `mplcairo` wouldn't work for our docs build.  If the `matplotlib.use("module://mplcairo.qt")` call does not work as intended, presumably because `pyplot` has already been imported for the relevant Python session that renders the example, then the remaining option is to set the `MPLBACKEND` environment variable.  However, we'd really want to set `MPLBACKEND` for only that one gallery example, rather than our entire docs, especially given sticking points with `mplcairo` on macOS.  This could require an enhancement to `sphinx-gallery`...

I'm thinking that this issue is far more difficult than originally estimated.
