### ISSUE TITLE
Test sponsored packages with sunpy core 4.1rc1

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6565]
### Provide a general description of the issue or problem.

This is a tracking issue to test all our sponsored packages with 4.1rc1. If you run tests of a sponsored package with 4.1rc1 please tick this list, and when they're all done we can close this issue 😄 

- [x] `sunpy-soar` https://github.com/sunpy/sunpy-soar/actions/runs/3400896420
- [x] `ndcube`
- [x] `drms`
- [x] `sunraster`
- [ ] `sunkit-image`
- [x] `sunkit-instruments`
- [x] `aiapy`

**Comment by nabobalis** [comment]
drms has no dependency on sunpy. 

It does run the JSOC unit tests from main.

**Comment by nabobalis** [comment]
On other good news, `ablog` is perfectly ok with sunpy 4.1

**Comment by nabobalis** [comment]
sunkit-image is having some test issues which I am trying to debug but I think everything is now covered and ok with 4.1.0rc1.

**Comment by nabobalis** [comment]
Fixed the CI for the two failing sponsored packages. I can see no issues with sunpy 4.1.0rc1 and these packages.

**Comment by dstansby** [comment]
Thanks for all the testing @nabobalis !
