### ISSUE TITLE
`.resample()` and `.superpixel()` modify `CDELTi`/`PCi_j` in a way that results in non-intuitive behavior

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6570]
The FITS WCS standard allows for "considerable flexibility" in the way that `CDELTi` values and the `PCi_j` matrix are defined.  You can choose any combination that multiplies to the `CDi_j` matrix that you need.  However, for 2D imagery, most users would probably expect that the `PCi_j` matrix be as close to a pure rotation matrix as possible, and the `CDELTi` values to be represent the pixel plate scales.

For whatever reason, when modifying a map that uses the `PCi_j` matrix, both `.resample()` and `.superpixel()` modify only the `PCi_j` matrix and do not modify the `CDELTi` values.  Again, this is technically permitted.  However, this has several non-intuitive consequences:

- `.scale` returns `CDELTi` values, which are no longer the pixel plate scales
- `.rotation_matrix` returns the `PCi_j` matrix, which is no longer close to a pure rotation matrix and contains scaling factors
- A de-rotating `.rotate()` call on the map leads to an unexpected resampling because it uses `.rotation_matrix`, which now has scaling factors in it

I'll work up a PR to fix this.

**Comment by ayshih** [comment]
This was encountered in the wild because a user rotated a map (which by design resulted in a map with a PCij matrix), then resampled it (which results in a map with a PCij matrix that encodes the resampled pixel plate scale), and finally rotated it again (which was expected to do nothing, but instead resulted in a resampled map with the unity pixel plate scale).

**Comment by Cadair** [comment]
> Some maps store information about the pixel plate scale using the PCij matrix

This premise is flawed. This is in violation of the fits standard. If you want to combine CDELT and PCi_j then you have to use the CDi_j matrix.

How did we end up in this situation? Do we have the data in question?

**Comment by ayshih** [comment]
Ah, you're right.  The actual issue is that we have a true bug where `.resample()` and `superpixel()` both scale the PCij matrix when they shouldn't.  I'll completely rewrite this issue soon

**Comment by ayshih** [comment]
> This premise is flawed. This is in violation of the fits standard.

Interestingly, after going back through the FITS WCS papers, what we are doing is not actually a violation of the standard.  Importantly, `CDELTi` are not literally defined to to be the size of the reference pixel, but are instead characteristic coordinate scales, which may or may or may not be exactly the same as the size of the reference pixel.  From Section 2.1.3 of Paper I:

> Equations [for the linear transformation from pixel coordinates to intermediate world coordinates] allow considerable flexibility in the way the linear transformation is partitioned between the `PCi_j` and `CDELTi`.  In the absence of any formal constraints, the normal expectation would be that the `CDELTi` be used as scaling parameters as in the past.  This is straightforward if `PCi_j` is orthogonal, i.e. defines a pure rotation or simple reflection, but not if it has an element of skewness.  In general, a reasonable approach is to choose `CDELTi` so that [the sum of the squares in each row of `PCi_j` is unity]. ... Note also that this constraint is optional, and may not be the most physically meaningful selection of the `PCi_j`.  For example, the conversion from the old `CROTAi` nomenclature to the new `PCi_j` form described in Paper II does not satisfy this constraint unless the `CDELTi` are equal.

Section 6 of Paper I also shows two possible ways for a given example header to partition `PCi_j` and `CDELTi`, depending on what one considers to be natural, and here as well, neither of the two forms satisfy the optional constraint suggested above.

That said, we definitely need to change what we are doing because it results in non-intuitive behavior.  I'm just saying that it's technically not a violation of the standard.

**Comment by ayshih** [comment]
I didn't do my usual history search on this one.  This bug was inadvertently introduced in #5786.

**Comment by Cadair** [comment]
Semi related to this, I was under the mistaken impression that we converted away from the CD matrix to the PC one everywhere, but in reality this is only true in `rotate()`. I wonder if it's worth keeping support for these alternative representations into the future?

**Comment by ayshih** [comment]
> Semi related to this, I was under the mistaken impression that we converted away from the CD matrix to the PC one everywhere, but in reality this is only true in `rotate()`.

What you may be thinking of is that our `.wcs` property does convert from the CD matrix to the PC matrix.  So, calls like `GenericMap.pixel_to_world()` essentially use CDELT*PC instead of CD.  It's a bit academic as long as you correctly calculate the PC matrix from the CD matrix.  However, if you don't – see #6573 for such a bug – then `GenericMap.pixel_to_world()` gives different answers depending on what CDELT values were stored alongside the same CD matrix.

> I wonder if it's worth keeping support for these alternative representations into the future?

I don't understand what you mean.

**Comment by Cadair** [comment]
I mean should the new header returned by `superpixel` and `resample` etc all always return in the PC formulaism to mean we only ever have to update those headers.
