### ISSUE TITLE
Issue with parse_time and formats

### ISSUE THREAD

**Issue by hannahc243** [sunpy/sunpy#6586]
### Describe the bug

I have come across this issue when trying to parse a time string using parse time, when it's in this format  "%d-%b-%Y %H:%M:%S.%f",  # Example 04-May-2007 21:08:12.999999 

In this case it works:
```python 
parse_time('30-Mar-2022 17:25:14.500')
<Time object: scale='utc' format='isot' value=2022-03-30T17:25:14.500>
```
but doesn't in this:

```python
parse_time('30-Mar-2022 17:25:14.000')
ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': ValueError('Time 30-Mar-2022 17:25:14 does not match iso format'), 'isot': ValueError('Time 30-Mar-2022 17:25:14 does not match isot format'), 'yday': ValueError('Time 30-Mar-2022 17:25:14 does not match yday format'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': ValueError('Time 30-Mar-2022 17:25:14 does not match fits format'), 'byear_str': ValueError('Time 30-Mar-2022 17:25:14 does not match byear_str format'), 'jyear_str': ValueError('Time 30-Mar-2022 17:25:14 does not match jyear_str format'), 'astropy_time': TypeError('Input values for astropy_time class must all be same astropy Time type.')}
```
Seems to be related to the zero after the decimal point.

### System Details

sunpy 4.0.6  
astropy 5.0

**Comment by ayshih** [comment]
Heh, there's already a PR under review to fix this (#6586), which will hopefully be included in the next sunpy release (4.1).

**Comment by dstansby** [comment]
Thanks for reporting, especially as your first bug report to sunpy!

**Comment by ayshih** [comment]
If you have an urgent need for things to be working and can't wait for the next release, here's a workaround for your situation that you can temporarily put in your scripts without needing to modify any `sunpy` source files:
```python
import sunpy.time
sunpy.time.time.TIME_FORMAT_LIST.append("%d-%b-%Y %H:%M:%S")
```
