### ISSUE TITLE
Enable sphinx-hoverxref in the documentation

### ISSUE THREAD

**Issue by namurphy** [sunpy/sunpy#6608]
### Describe the feature

From their docs: 

> `sphinx-hoverxref` is a [Sphinx](https://www.sphinx-doc.org/en/master/index.html) extension to show a floating window (tooltips or modal dialogues) on the cross references of the documentation embedding the content of the linked section on them. With sphinx-hoverxref, you don’t need to click a link to see what’s in there.

To see an example in use, try hovering over links to code objects on [this page in PlasmaPy's docs](https://docs.plasmapy.org/en/stable/formulary/speeds.html).  It's possible to configure this with intersphinx so that floating windows show up for Astropy & NumPy objects too.

### Proposed solution

Info on how to set this up is on their [installation](https://sphinx-hoverxref.readthedocs.io/en/latest/installation.html), [usage](https://sphinx-hoverxref.readthedocs.io/en/latest/usage.html), and [configuration](https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html) pages.  For an example of it in use, seach PlasmaPy's [`docs/conf.py`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/conf.py) for `hoverxref`.

**Comment by Cadair** [comment]
Thanks for the suggestion @namurphy this looks super cool.
