### ISSUE TITLE
Remove requirement for newline at end of json files?

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6611]
### Provide a general description of the issue or problem.

pre-commit currently complains if there isn't a newline at the end of JSON files, e.g. https://results.pre-commit.ci/run/github/2165383/1668599004.x8Z83F3FQLSl9fbjTaYcwg. This is a bit annoying because the Python JSON writer doesn't write out a newline at the end by default, so when running the scripts that update the `sunpy.net` attributes JSON files a newline has to be manually added whenver the files are re-generated.

Since this is quite annoying, I propose that we remove the requirement for JSON files to have a newline at the end of the file

**Comment by Cadair** [comment]
Yes :+1: this is also really annoying with the figure test json.
