### ISSUE TITLE
Make the landing page more friendly

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6615]
When you land on docs.sunpy.org, you're currently greeted with two boxes with bullet points. We should instead adapt what is currently in the brief tour into some sort of introduction into what sunpy can do. The user should be greeted with what sunpy can do, ideally in graphical format. This could be either in the form of actual plots or something more cartoon-y as in the glyph attached below.

![sunpy-summary-slide](https://user-images.githubusercontent.com/8676141/202766188-616336e5-6a28-4d21-9b81-58faccb517a4.svg)

**Comment by nabobalis** [comment]
> Hi, I'd like to fix this issue. Should I make the graphics myself too if that's alright?

What graphics would you create?

> One query, I should be editing [`main`/docs/index.rst](https://github.com/sunpy/sunpy/blob/main/docs/index.rst?rgh-link-date=2023-02-22T08%3A32%3A37Z) right? Does the current [docs.sunpy.org](https://docs.sunpy.org/) reflect the reStructured text?

Yes it does.

**Comment by Satan-Claws** [comment]
> What graphics would you create?

Some graphics like what @wtbarnes made but for each section

> Yes it does.

Are you sure? Because the current index.rst doesn't divide into 2 sections like mentioned but it does happen in [docs.sunpy.org](https://docs.sunpy.org/).

**Comment by nabobalis** [comment]
> > What graphics would you create?
> 
> Some graphics like what @wtbarnes made but for each section

I think we would want to use the one that Will created instead of making a new one.

> > Yes it does.
> 
> Are you sure? Because the current index.rst doesn't divide into 2 sections like mentioned but it does happen in [docs.sunpy.org](https://docs.sunpy.org/).

I am sure, you need to go to https://docs.sunpy.org/en/latest/

**Comment by Satan-Claws** [comment]
> I think we would want to use the one that Will created instead of making a new one.
 
Alright, I'll look into it.

> I am sure, you need to go to https://docs.sunpy.org/en/latest/

Oh sorry sorry, I was looking at the wrong webpage. I'll try to cut the images and put them in and will let you know

**Comment by Satan-Claws** [comment]
@nabobalis I've edited index.rst and I've added the graphics provided by @wtbarnes. Should I create a pull request? Link to my fork https://github.com/Satan-Claws/sunpy/tree/main/docs

**Comment by nabobalis** [comment]
> @nabobalis I've edited index.rst and I've added the graphics provided by @wtbarnes. Should I create a pull request? Link to my fork [Satan-Claws/sunpy@`main`/docs](https://github.com/Satan-Claws/sunpy/tree/main/docs?rgh-link-date=2023-02-22T18%3A38%3A56Z)

Yes please.
