### ISSUE TITLE
Increase test coverage for all Map Sources

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#664]
Current coverage:

https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/map/sources

**Comment by dpshelio** [comment]
Will we ever close this issue? Should be renamed to HMI if that's the main one and create one issue per source?

**Comment by Cadair** [comment]
Here is a good overview of what needs testing: https://codecov.io/gh/sunpy/sunpy/tree/master/sunpy/map/sources

**Comment by wtbarnes** [comment]
Closing as every Map source is above 95% test coverage except SXT and it looks like this is covered by #3440
