### ISSUE TITLE
Add an example gallery entry for querying SHARP data and constructing a Map

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6663]
The SHARP data series is frequently used, but we do not have an example showing how to query the data or how to construct a Map for the data.

~~Currently, our `JSOCClient` does not support this, but~~ it can be done through `drms` directly, e.g. adapting the [example here](https://docs.sunpy.org/projects/drms/en/stable/generated/gallery/plot_synoptic_mr.html)

```python
import astropy.time
import drms

c = drms.Client()
sharp_num = 377
ts = astropy.time.Time('2011-02-10 22:00:00',scale='tai')
ds = f'hmi.sharp_cea_720s[{sharp_num}][{ts.tai.isot}_TAI/10h@1h]'
results, filenames = c.query(ds, key=drms.const.all, seg=['Bp','Br','Bt'])
```

Then, to download the first file for the phi component of the field ('Bp'),

```python
import astropy.io.fits

data = astropy.io.fits.getdata(f'http://jsoc.stanford.edu{filenames["Bp"][0]}')
header = dict(results.iloc[0])
m = sunpy.map.Map(data, header)
m.peek()
```

<img width="590" alt="image" src="https://user-images.githubusercontent.com/8676141/208489503-5719b77a-0af2-48c8-bf88-d17002b89cde.png">

It may be worth looking into adding support through our JSOC client for this kind of query as well as adding support for these types of maps, either through a standalone map class or through the existing HMIMap class.

**Comment by nabobalis** [comment]
Is this not something we should add to DRMS gallery since it doesn't use Fido at all?

**Comment by wtbarnes** [comment]
We could. There is already an example of how to use drms to query the HARP series which is the thing I linked above. It would be nice to also show how to construct a map from the file and the header. My reasoning for not putting this issue under drms is that I don't think we use Map in any of the drms examples.

**Comment by Cadair** [comment]
Fido supports this:

```python
from sunpy.net import Fido, attrs as a
import astropy.units as u
import sunpy.map

results = Fido.search(a.Time("2011-02-10 22:00:00", "2011-02-10 22:30:00"),
                      a.Sample(1*u.hour),
                      a.jsoc.Series("hmi.sharp_cea_720s"), 
                      a.jsoc.PrimeKey("HARPNUM", 377),
                      a.jsoc.Notify("..."),
                      a.jsoc.Segment("Bp"))

files = Fido.fetch(results)

sharp_bp = sunpy.map.Map(files)
sharp_bp.peek()
```
![Figure_1](https://user-images.githubusercontent.com/1391051/208667404-ed3b0d0a-c473-4256-9b4c-0dbadf88434b.png)

**Comment by exitflynn** [comment]
this would go in the `plotting` section instead of `acquiring_data`, right?

**Comment by nabobalis** [comment]
I think it would go in `acquiring_data`
