### ISSUE TITLE
[4.1.0] test_coordinate_frames.py  and test_genericmap.py fail with installed package

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#6666]
### Describe the bug

When running the CI tests on the installed package with
```
python3 -m pytest --remote-data=none --pyargs sunpy -k "not figure and not online"
```
I get a number of test failures with `test_coordinate_frames.py`  and `test_genericmap.py`. They all look like

```
_____________________________ test_saveframe[HeliographicStonyhurst] __________________________
coordframe_scalar = <HeliographicStonyhurst Coordinate (obstime=2018-01-01T00:00:00.000, rsun=695700.0 km): (lon, lat) in deg
    (0.00023983, 0.00019417)>
tmpdir = local('/tmp/pytest-of-debci/pytest-0/test_saveframe_HeliographicSto0')
    @asdf_entry_points
    def test_saveframe(coordframe_scalar, tmpdir):
>       assert_round_trip_frame(coordframe_scalar)
/usr/lib/python3/dist-packages/sunpy/io/special/asdf/tests/test_coordinate_frames.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
old = <HeliographicStonyhurst Coordinate (obstime=2018-01-01T00:00:00.000, rsun=695700.0 km): (lon, lat) in deg
    (0.00023983, 0.00019417)>
    def assert_round_trip_frame(old):
        new = roundtrip_object(old)
>       assert isinstance(new, type(old))
E       AssertionError: assert False
E        +  where False = isinstance({'data': <UnitSphericalRepresentation (lon, lat) in arcsec\n    (0.86337713, 0.69902478)>, 'frame_attributes': {'obstime': <Time object: scale='utc' format='isot' value=2018-01-01T00:00:00.000>, 'rsun': <Quantity 695700. km>}}, <class 'sunpy.coordinates.frames.HeliographicStonyhurst'>)
E        +    where <class 'sunpy.coordinates.frames.HeliographicStonyhurst'> = type(<HeliographicStonyhurst Coordinate (obstime=2018-01-01T00:00:00.000, rsun=695700.0 km): (lon, lat) in deg\n    (0.00023983, 0.00019417)>)
/usr/lib/python3/dist-packages/sunpy/io/special/asdf/tests/test_coordinate_frames.py:21: AssertionError
```

Full test log [here](https://salsa.debian.org/debian-astro-team/sunpy/-/jobs/3682978).

### To Reproduce

* install sunpy
* run the commandshown above

### System Details

- sunpy 4.1.0
- astropy 5.2
- Python 3.10.9
- platform linux -- Python 3.10.9, pytest-7.2.0, pluggy-1.0.0+repack
- test plugins: filter-subpackage-0.1.2, astropy-0.10.0, astropy-header-0.2.2, openfiles-0.5.0, hypothesis-6.60.0, asdf-2.14.3, mock-3.8.2, cov-4.0.0, arraydiff-0.5.0, doctestplus-0.12.1, remotedata-0.4.0, xdist-3.1.0

### Installation method

from source (.tar.gz)

**Comment by nabobalis** [comment]
Hi @olebole, sorry for not getting back to you much sooner.

Does this still occur?

**Comment by olebole** [comment]
It does not happen anymore. I think that I forgot to include the [asdf-coordinates-schemas](https://github.com/asdf-format/asdf-coordinates-schemas) package as dependency. After installing the package, these tests pass. Sorry for confusion.

**Comment by nabobalis** [comment]
Thanks for packaging sunpy!
