### ISSUE TITLE
`manylinux` wheel builds failing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6680]
### Describe the bug

Tests on the manylinux wheel builds are failing, because they can't import `cv2`. e.g. https://github.com/sunpy/sunpy/actions/runs/3806622178/jobs/6475753826. Error is:

```python
import cv2
  E           ImportError: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/tmp.sIYIruBBDr/venv/lib/python3.8/site-packages/cv2/../opencv_python.libs/libpng16-186fce2e.so.16.37.0)
```

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by dstansby** [comment]
Looks like https://github.com/opencv/opencv-python/issues/765 is the upstream issue

**Comment by nabobalis** [comment]
Can we pin the version in our tests for now to avoid this?

**Comment by ConorMacBride** [comment]
Adding this configuration to pyproject.toml will work with the OpenAstronomy template https://cibuildwheel.readthedocs.io/en/stable/options/#test-requires

**Comment by nabobalis** [comment]
Ah I didn't know that. Thanks, I will PR something.
