### ISSUE TITLE
improve gzipped-FITS files detection

### ISSUE THREAD

**Issue by exitflynn** [sunpy/sunpy#6692]
### Describe the feature

Currently the file detection for gzipped-FITS files relies on checking if they are named in the `filename.fits.gz` format. However since this condition isn't a necessity for gzipped files, this approach misses those gzipped-FITS files which do not end with the `.gz` extension.

### Proposed solution

Use magic bytes / file signatures to check whether the file is gzipped or not. If it is, decompress and read its first few bytes to determine whether it's a FITS file.

**Comment by ConorMacBride** [comment]
Looking at the code in `sunpy.io.file_tools`, gzipped-FITS files which end in `fts` or `fits` should also work. I wonder how expensive it would be to decompress large files to check the file type? I guess we could do that just before raising a `UnrecognizedFileTypeError `. Maybe it would be good enough to also accept files that end in `fits.*` etc?

**Comment by exitflynn** [comment]
(this issue addresses the issue discovered in the discussion for #6655, thought i should link it so that future contributors know of it)

**Comment by exitflynn** [comment]
@ConorMacBride IIRC something like `gzip.open('filename','rb').read(8)` shouldn't require decompressing the entire file. Will have to make sure.

**Comment by ConorMacBride** [comment]
Ah, thank you, I missed that issue! Nice, I hadn't realised gzip files could be partially decompressed!

**Comment by exitflynn** [comment]
Also I looked it up to be sure and found that yep, they use a [BufferedReader](https://github.com/python/cpython/blob/main/Lib/gzip.py#L190) when opening compressed files in `rb` mode. Hope I'm not wrong :sweat_smile:.
