### ISSUE TITLE
Add support sqlalchemy 2.0

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#6695]
The database module uses sqlalchemy and there is a major release coming soon, 2.0. 

This is going to break something in database so we pinned the version for now.
But we should investigate how much work it will be to add support for version 2.0.

_Originally posted by @alasdairwilson in https://github.com/sunpy/sunpy/issues/6694#issuecomment-1372853864_

**Comment by ConorMacBride** [comment]
Might just need to change the imports (https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#declarative-becomes-a-first-class-api) depending on the installed version.

**Comment by nabobalis** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/6749
