### ISSUE TITLE
Add changelog entry for sqlalchemy pin

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6698]
### Describe the bug

Our users should find out about any pins we add to dependencies, so https://github.com/sunpy/sunpy/pull/6694 should have had a changelog.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by ryuusama09** [comment]
I can do this. We just hhave to update the changelog right ?

**Comment by nabobalis** [comment]
Yeah, you need to add a changelog entry about it.

**Comment by ryuusama09** [comment]
> Yeah, you need to add a changelog entry about it.

so this is ideally just a good first issue right :)

**Comment by nabobalis** [comment]
> > Yeah, you need to add a changelog entry about it.
> 
> so this is ideally just a good first issue right :)

Yeah.

**Comment by ryuusama09** [comment]
![image](https://user-images.githubusercontent.com/80237556/213086788-fbf39170-44a4-4896-a25b-4f0c66849f7e.png)
the log needs to be updated for these 4 changes

**Comment by nabobalis** [comment]
The changelog just needs to say that the version of SQLAlchemy has been pinned to be less than two while we investigate if the upcoming release of 2.0 will break the current database implementation.
