### ISSUE TITLE
XRT Maps do not include unit information

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6716]
XRT maps, from any level (as far as I can tell), do not include a `BUNIT` keyword or any equivalent keyword to encode the unit information.

However, according to Table 1.1 in [the XRT analysis guide](https://xrt.cfa.harvard.edu/resources/documents/XAG/XAG.pdf), the units for the different levels are DN for level 0 and DN/s for level 1. However, there is also a note that level 1 can be DN or DN/s, depending on which options are passed to `xrt_prep`. When level 1 data is divided by the exposure time (to be put in units of DN/s), there is a tag added to the `HISTORY` that indicates that the data have been renormalized. When pulling in the data, the source could check for this tag and set the unit appropriately and otherwise fall back to DN.

**Comment by exitflynn** [comment]
I'd like to give this a shot! :cowboy_hat_face:

**Comment by nabobalis** [comment]
Go ahead.

**Comment by wtbarnes** [comment]
There is a question of whether depending on the `HISTORY` tag when setting a property is a good idea and whether that is reliable or not. I don't think we do that in any of the other map sources. Maybe it is better to have no unit information at all than assert a particular unit with some degree of uncertainty?

**Comment by wtbarnes** [comment]
n.b. According to Section 2.11 of the XRT analysis guide, the tag added to `HISTORY` starts with "XRT_RENORMALIZE".

**Comment by exitflynn** [comment]
>  Maybe it is better to have no unit information at all than assert a particular unit with some degree of uncertainty?

um this issue should be up for discussion at the moment, right?

**Comment by nabobalis** [comment]
> > Maybe it is better to have no unit information at all than assert a particular unit with some degree of uncertainty?
> 
> um this issue should be up for discussion at the moment, right?

I don't think so?

**Comment by wtbarnes** [comment]
As I said in my previous comment, relying on particular words in the HISTORY key is perhaps questionable. Having no unit information forces the user to figure this out for themselves. Notably, I don't think our test XRT header includes this entry.

**Comment by exitflynn** [comment]
I've been trying to work on this for a while and having a little bit of trouble figuring out how to approach it. My current understanding is that I need to make changes to [`map/sources/hinode.py`](https://github.com/sunpy/sunpy/blob/main/sunpy/map/sources/hinode.py#L51). There's a test XRT file [here](https://github.com/sunpy/sunpy/blob/main/sunpy/data/test/HinodeXRT.header) with the corresponding test [`test_xrt_source.py`](https://github.com/sunpy/sunpy/blob/main/sunpy/map/sources/tests/test_xrt_source.py). I've tried tracing through the code and think the following way to test my changes on the test file should work:
```
import sunpy.data.test
m = sunpy.data.test.get_dummy_map_from_header('HinodeXRT.header')
```

but before i debugged through the errors ^this is giving me I guess I just want to know if there was perhaps a much simpler way I could've gone about this / documentation that I might have overlooked...

**Comment by nabobalis** [comment]
> As I said in my previous comment, relying on particular words in the HISTORY key is perhaps questionable.

I don't think it does, if a Mission tells us they will add processing information to the history. I think its ok to use that to add units.

**Comment by wtbarnes** [comment]
> I've been trying to work on this for a while and having a little bit of trouble figuring out how to approach it. My current understanding is that I need to make changes to [`map/sources/hinode.py`](https://github.com/sunpy/sunpy/blob/main/sunpy/map/sources/hinode.py#L51). There's a test XRT file [here](https://github.com/sunpy/sunpy/blob/main/sunpy/data/test/HinodeXRT.header) with the corresponding test [`test_xrt_source.py`](https://github.com/sunpy/sunpy/blob/main/sunpy/map/sources/tests/test_xrt_source.py). I've tried tracing through the code and think the following way to test my changes on the test file should work:
> 
> ```
> import sunpy.data.test
> m = sunpy.data.test.get_dummy_map_from_header('HinodeXRT.header')
> ```
> 
> ~but before i debugged through the errors ^this is giving me I guess I just want to know if there was perhaps a much simpler way I could've gone about this / documentation that I might have overlooked...~ nevermind, I think I got it 👍

Yep, that should work! XRT data is also nominally available via the VSO, but that particular data source is down at the moment so that test header is probably the best route.

**Comment by dstansby** [comment]
Given this is an issue with the data we're working around, I've un-tagged this as a bug.

**Comment by wtbarnes** [comment]
> Given this is an issue with the data we're working around, I've un-tagged this as a bug.

Hmm in that case, this should probably not have been backported…
