### ISSUE TITLE
XRS data (pre-16) now served at a different url 

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#6733]
### Describe the bug

as highlighted by @ianan, the GOES 13, 14, 15 reprocessed data have changed the base url for which the data is served (see issue [here](https://github.com/sunpy/sunpy/issues/6734))

The reprocessed data is now also available for data 8-15, so we can add that in here too. 

I'll get on this

**Comment by wtbarnes** [comment]
I transferred #6734 from the project repo to here. Ok if I close this one since I believe it's the same?
