### ISSUE TITLE
SOTMap Error calculating coordinate system

### ISSUE THREAD

**Issue by Hypnus1803** [sunpy/sunpy#6787]
### Describe the bug

The creation of the SOTMap is not working correctly. The coordinate system is not correct.

### To Reproduce

```python
fig = plt.figure(figsize=(14,6))
ax1 = fig.add_subplot(121,projection=sot_map)
sot_map.plot(axes=ax1)

ax2 = fig.add_subplot(122,projection=hmi_map)
hmi_map.plot(axes=ax2)
```

### Screenshots

The FOV is rougly the same in both images, but the coordinates are wrong in the SOTMap

![test_sot_hmi](https://user-images.githubusercontent.com/2066351/220295563-39320321-edbe-45f6-a37d-b42c2546acb9.jpeg)

**Comment by dstansby** [comment]
Thanks for the clear report - could you link to the SOT and HMI files you're plotting, so we can check what the FITS metadata looks like?

**Comment by Hypnus1803** [comment]
For sure, in the link below you can find both maps.
[https://drive.google.com/drive/folders/1YmewQW1MhR4PqPf8h4Kzm0yYq2Mjqgfb?usp=share_link](url)

**Comment by ayshih** [comment]
The metadata in your SOT submap appears to be incorrect, specifically the `CRPIXi` values.  The submap is 410x410 pixels, cropped down from the original 1024x1024 map, but it appears that the `CRPIXi` values were not adjusted from corresponding to the center of the original 1024x1024 map.  Was (a current version of) `sunpy` used to create that submap?

**Comment by ayshih** [comment]
To be clear, I've checked this against the full-frame SOT map downloaded from the VSO, and the `CRVALi`/`CRPIXi` values in your submap's metadata appear to be good for the full map (and thus are invariably not good for the cropped map).

**Comment by Hypnus1803** [comment]
Dear @ayshih, it seems to be a problem when  the map was cut and coaligned. I will check where the wcs data didn't work. Thanks for pointing me to that, and sorry for create an issue before to re-check the problem. I will close it because no w I am not sure where was the problem, when I finish I will let you know.
