### ISSUE TITLE
Producing Full Sun Synoptic Maps in SunPy

### ISSUE THREAD

**Issue by STBadman** [sunpy/sunpy#6793]
### Describe the feature

In the example [Creating Carrington Maps](https://docs.sunpy.org/en/stable/generated/gallery/map_transformations/reprojection_carrington.html#sphx-glr-generated-gallery-map-transformations-reprojection-carrington-py) it is demonstrated how `sunpy.map.Map` helioprojective data can be cast into heliographic coordinates within sunpy. A very simple but likely to be widely used extension of this is to allow multiple such reprojected carrington maps to be summed together over a Carrington rotation to produce a full Sun (360 deg lon x 180 deg lat) synoptic map. 

SunPy is very close to having all the capabilities to do this, the only remaining feature is something to actually sum together the lon vs lat binned data with (1) some choice of weighting, and (2) some consideration of normalization (e.g. if the use case is to use synchronous observations from STEREO EUVI and SDO AIA ). @dstansby has already implemented a function that does this summation with regards to the first consideration in the archived [SolarSynoptic](https://github.com/dstansby/solarsynoptic) package : https://github.com/dstansby/solarsynoptic/tree/main/solarsynoptic/combine . The function takes a list of `sunpy.map.Map`s  as an argument, and optionally, a weight_function which takes `sunpy.map.Map` as input and performs some operation on the data values (an example gaussian weighting function is also available in the same location). The function then returns a single `sunpy.map.Map` whose data values are combined from all the input maps, and whose metadata is set as the header from the last map in the series.

I would like to import this set of functions to sunpy, to allow it to do the same task, and extend the example [Creating Carrington Maps](https://docs.sunpy.org/en/stable/generated/gallery/map_transformations/reprojection_carrington.html#sphx-glr-generated-gallery-map-transformations-reprojection-carrington-py)  to demonstrate this.

I'm happy to work on a PR to accomplish this but first I was looking for some advice on where the new functions should live in `sunpy` before I start.

### Proposed solution

My first thought would be that [`coadd`](https://github.com/dstansby/solarsynoptic/blob/main/solarsynoptic/combine/coadd.py) could be a new method in the  `sunpy.map.MapSequence` class. It would need to check that all input maps in the sequence are in heliographic coordinates, and have the same shape, and then applying the method (with some weighting function as optional input) would return from the `MapSequence` a single `sunpy.map.Map` which is the result of applying the combining operation to all the maps in the sequence. 

Does anyone see an initial structural problem with this? I know it would add a non-functional method to all `MapSequence` instances which do not contain a stack of heliographic `Maps`, if this is a problem, maybe there's a way to have a `HeliograhhicMapSequence` subclass which adds the mthod in if its just composed of heliographic maps? 

Happy to hear if there are any other ideas of where it could live. It could just be a direct function that works on ([lists of maps] -> summed map) like in `SolarSynoptic`, and the user would be responsible for a little more legwork in that case. I'm not sure where such a standalone function would live in sunpy thought.

Thanks for any advice!

**Comment by ayshih** [comment]
Have you seen the example [Creating a Full Sun Map with AIA and EUVI](https://docs.sunpy.org/en/stable/generated/gallery/map_transformations/reprojection_aia_euvi_mosaic.html)?

**Comment by STBadman** [comment]
I have not, thanks for pointing it out! The function [`reproject.mosaicking.reproject_and_coadd`](https://reproject.readthedocs.io/en/stable/api/reproject.mosaicking.reproject_and_coadd.html#reproject.mosaicking.reproject_and_coadd) with the weights keyword is exactly the missing piece I was looking for.

Well that was easier than expected, thanks! I'll close the issue :)
