### ISSUE TITLE
Great Arc example should use `extract_along_coord`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6801]
[The example showing how to construct a Great Arc](https://docs.sunpy.org/en/stable/generated/gallery/plotting/great_arc_example.html#sphx-glr-generated-gallery-plotting-great-arc-example-py) also shows how to get the intensity along that arc. Since this example was written, we added a function for extracting the value of a map along a coordinate as shown in [this example](https://docs.sunpy.org/en/stable/generated/gallery/units_and_coordinates/map_slit_extraction.html#sphx-glr-generated-gallery-units-and-coordinates-map-slit-extraction-py). The great arc should use that functionality rather than implementing the intensity extraction itself.

**Comment by davnish** [comment]
Should I create a PR for this issue? Following the example gallery dev guidelines.
