### ISSUE TITLE
`extract_along_coord` example should compare output with `sample_at_coords`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6802]
We have [an example](https://docs.sunpy.org/en/stable/generated/gallery/units_and_coordinates/map_slit_extraction.html#sphx-glr-generated-gallery-units-and-coordinates-map-slit-extraction-py) that shows how to extract the intensity along a coordinate using the `extract_along_coord` method which finds all discrete pixel coordinates that intersect with the world coordinate and returns the intensity at those pixels.
Similarly, the function [`sample_at_coords`](https://docs.sunpy.org/en/stable/generated/api/sunpy.map.sample_at_coords.html) performs a similar operation but simply gets the value of the map at each coordinate. In this case, no effort is made to make sure all points are adequately sampled or that duplicates are not included.

The example linked above should show a comparison between the two methods and show how they are different.

**Comment by ayshih** [comment]
Tutorial, how-to guide, or explanation? =)

**Comment by yuktea** [comment]
@wtbarnes I'd like to work on this 😃

**Comment by wtbarnes** [comment]
Given that with this modification this example would show different ways to accomplish a similar task, I would put this in the "how-to guide" category.

**Comment by ayshih** [comment]
Depending on how much it goes into the "comparison between the two methods", because then it might instead be "explanation"

**Comment by davnish** [comment]
I am working on this issue but I am not able to recreate on which operations does **sample_at_coords** shows in adequate results. One of the differences I can add is we can use **sample at coords** to extract value at distinct coordinated where **extract_along_coord** is used to extract all the values connecting those coordinate.

**Comment by davnish** [comment]
Sorry I was not able to clarify my doubt, but can you please help me understand on which conditions does `sample_at_coords` gives inadequate results?

**Comment by ayshih** [comment]
@davnish: Hmm, the short answer is that I don't understand what @wtbarnes meant.

@wtbarnes: What do you mean when you say that `sample_at_coords()` does not "make sure all points are adequately sampled or that duplicates are not included"?  The two functions sample pixels in exactly the same way, and `extract_along_coord()` excludes duplicates only in the sense of repeated pixels, so is not a general exclusion.  Really, the two  functions could be (and should be) refactored into a single function.

**Comment by davnish** [comment]
I tried to duplicate the pixels, But the only difference I am able to get till now between the two functions is that 
`extract_at_coord` gives the intensity along the path, and `sample_at_coords` gives the intensity on specific coordinates given to it. Can anyone please guide me here, what am I doing wrong?

![Figure_1](https://user-images.githubusercontent.com/32027279/222906224-a93c5bb4-02b5-4c01-805c-c4a7ea52d471.png)

`import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import SkyCoord

import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE

m = sunpy.map.Map(AIA_171_IMAGE)

coords = SkyCoord(
    Tx=[715, 715 , 722] * u.arcsec,
    Ty=[-360, -348,-348] * u.arcsec,
    frame=m.coordinate_frame,
)

repeated_coords = SkyCoord(
    Tx=[722,717] * u.arcsec,
    Ty=[-348,-348] * u.arcsec,
    frame=m.coordinate_frame,
)

intens, intens_coords = sunpy.map.extract_along_coord(m, coords)
angular_separation1 = intens_coords.separation(intens_coords[0]).to(u.arcsec)

intensity = sunpy.map.sample_at_coords(m, coords)
angular_separation2 = coords.separation(coords[0]).to(u.arcsec)


print(f"{intens_coords}\n")
print(f"{coords}\n")
print(f"{angular_separation1}\n")
print(f"{angular_separation2}\n")
print(intens)
print(f"{intensity}\n")

fig = plt.figure(figsize=(13,4))
ax = fig.add_subplot(131, projection=m)
m.plot(ax)
ax.plot_coord(coords, marker='o', color='black', label="Input coords")
ax.plot_coord(intens_coords, marker='s', color='tab:purple', label="Sampled coords")
ax.plot_coord(repeated_coords, marker = '+', color='red',label="Repeated Coords")
ax.set_ylim(360, 360 + 10)
ax.set_xlim(807, 807 + 10)
ax.legend()

ax1 = fig.add_subplot(132)

ax1.scatter(angular_separation1,intens)
ax1.set_title("Using extract_along_coord")

ax2 = fig.add_subplot(133)
ax2.scatter(angular_separation2,intensity)
ax2.set_title("Using sample_at_coords")
plt.show()
`

**Comment by wtbarnes** [comment]
> @wtbarnes: What do you mean when you say that `sample_at_coords()` does not "make sure all points are adequately sampled or that duplicates are not included"? 

My initial description was sloppy. For a given coordinate, `extract_along_coord` approximates the path of the line segments of that coordinate in pixel space and then returns the value of that map at each point along that path. `sample_at_coords` just returns the value of the map at each point of the coordinate. If that coordinate is not sufficiently "dense" enough to sample each pixel, those points will be skipped when using `sample_at_coords` while `extract_along_coord` samples values along an approximation of the line segment between pixels (you can see the effect of this by comparing the current output of the Great Arc example the result of #6816). 

Conversely, if your coordinate is "over dense" when mapped into pixel space (i.e. two world coordinates map to a single array index) then `sample_at_coords` will return the same value for those two world coordinates. That is what I meant by duplicates. 

In creating this issue, I just meant that we should compare the approach of sampling a map at discrete points (just using `sample_at_coords`) versus more fully sampling the map along a curve described by those discrete points (`extract_along_coord`).

> The two functions sample pixels in exactly the same way, and `extract_along_coord()` excludes duplicates only in the sense of repeated pixels, so is not a general exclusion. Really, the two functions could be (and should be) refactored into a single function.

Yes, I agree. `extract_along_coord` should call `sample_at_coords`. Alternatively, `extract_along_coord` could be simplified (and also renamed) to just return the new coordinate constructed with Bresenham's line algorithm and then it would be on the user to then pass that new coordinate to `sample_at_coords`. From a clean code perspective (i.e. a function should do one thing), this second option is also preferable.

**Comment by wtbarnes** [comment]
Here's kind of what I had in mind for the case of an "over-sampled" coordinate (which I call "dense") and an under-sampled coordinate (which I call "sparse"). The behavior of `extract_along_coord` for the over-sampled coordinate is a bit concerning. I'm not sure what the intended behavior of Bresenham's line algorithm is when the points are so closely spaced that there are effectively no line segments defined between them (in integer pixel space).

```python
m = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
m = m.submap(SkyCoord(Tx=-50*u.arcsec, Ty=-50*u.arcsec, frame=m.coordinate_frame), width=100*u.arcsec, height=100*u.arcsec)

x_sparse = np.linspace(0, 30,5)
line_sparse = SkyCoord(Tx=x_sparse*u.arcsec,
                       Ty=(x_sparse/5)**2*u.arcsec,
                       frame=m.coordinate_frame)
x_dense = np.linspace(0, 30, 100)
line_dense = SkyCoord(Tx=x_dense*u.arcsec,
                       Ty=(x_dense/5)**2*u.arcsec,
                       frame=m.coordinate_frame)


intensity_sparse_eac, line_sparse_eac  = sunpy.map.extract_along_coord(m, line_sparse)
intensity_dense_eac, line_dense_eac = sunpy.map.extract_along_coord(m, line_dense)
intensity_sparse_sac = sunpy.map.sample_at_coords(m, line_sparse)
intensity_dense_sac = sunpy.map.sample_at_coords(m, line_dense)

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(projection=m)
m.plot(axes=ax)
ax.plot_coord(line_sparse, label='sparse')
ax.plot_coord(line_dense, label='dense')
ax.plot_coord(line_sparse_eac, label='sparse, extract_along_coord')
ax.plot_coord(line_dense_eac, label='dense, extract_along_coord')
ax.legend()

plt.figure(figsize=(15,5))
plt.plot(line_sparse_eac.separation(line_sparse_eac[0]).to('arcsec'), intensity_sparse_eac, marker='.', label='sparse, extract_along_coord')
plt.plot(line_sparse.separation(line_sparse[0]).to('arcsec'), intensity_sparse_sac, marker='.', label='sparse, sample_at_coords')
plt.plot(line_dense_eac.separation(line_dense_eac[0]).to('arcsec'), intensity_dense_eac, marker='.', label='dense, extract_along_coord')
plt.plot(line_dense.separation(line_dense[0]).to('arcsec'), intensity_dense_sac, marker='.', label='dense, sample_at_coords')
plt.legend()
```

![image](https://user-images.githubusercontent.com/8676141/222992337-e1402fa8-c03f-40a6-bc3d-607b910f91ab.png)
![image](https://user-images.githubusercontent.com/8676141/222992345-cfeff1ad-294a-4f87-904d-62cf61dd309b.png)

**Comment by ayshih** [comment]
> The behavior of `extract_along_coord` for the over-sampled coordinate is a bit concerning.

Heh, not only is the behavior of `extract_along_coord()` correct for the "dense" case, `sample_at_coords()` samples the exact same pixels in the exact same sequence, with the only difference being that there are repeated pixels.  It's not obvious because `sample_at_coords()` doesn't tell you which pixel it is returning, and your bottom plot is misleading because it plots the `sample_at_coords()` values as if they correspond to the actual coordinate rather than coordinate for the center of the nearest pixel.

For such short line segments, the choice of line algorithm is basically irrelevant.

**Comment by wtbarnes** [comment]
`extract_along_coord` is now deprecated so I'm closing this issue.
