### ISSUE TITLE
Create a function to return the map pixels that intersect with a coordinate path

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#6826]
`extract_along_coord()` extracts map-pixel values along a pixel path that approximates a coordinate path, but has a number of issues (see #6802).

We should create a new function that:
- Determines all of the pixels that intersect with the coordinate path, including accounting for coordinates that are not at pixel centers
- Returns only the coordinates for the centers of those pixels, and not the values in those pixels

We would then deprecate `extract_along_coord()`.  If the user wants the values in those pixels, they would pass the output on to `sample_at_coords()`.

**Comment by OussCHE** [comment]
@ayshih to understand better the request and resume the discussion. The task here is to simplify `extract_along_coord()` to return only pixels rather than values. Plus, we don't modify the ` _bresenham` algo as I understood the behavior of the algo is correct(according to @wtbarnes)

**Comment by ayshih** [comment]
@OussCHE Thanks for your interest, but I've actually already written up a new algorithm.  You're certainly welcome to look it over and provide feedback when I submit the PR soon.
