### ISSUE TITLE
Improve Acquiring data section of the tutorial

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6865]
### Describe the feature

Things that I've noticed that could be improved at a glance are:

- Move the database package page (and maybe delete it, since we're going to formally deprecated `sunpy.database` in sunpy 5.0)
- Move the "Downloading sample data" page to the guide section of the docs
- Move the JSOC/HEK/helioviewer pages elswhere. They are quite tutorially, so I think maybe we could:
    - Migrate the content in "Finding and downloading data" to the main Acquiring data page.
    - Have a link to the source specific tutorials at the end of the main tutorial

There might be other improvements that can be made too :globe

**Comment by wtbarnes** [comment]
I'm going to close this as looking at the acquiring data section of the tutorial, it appears that all of the items listed above have been completed.
