### ISSUE TITLE
Move "plotting" section of the tutorial to "Maps"

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6866]
### Describe the feature

Content on plotting maps is currently split between the "Plotting" and "Maps" section of the tutorial. I would suggest we get rid of the "plotting" section, and merge it with content already in the "maps" section

**Comment by hayesla** [comment]
should we remove the "Matplotlib Tutorial" part of this?

**Comment by dstansby** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/6870
