### ISSUE TITLE
Online test fails indicate return values from VSO have changed

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6883]
There are a couple of errors, one is:

```
                         row["Wavelength"] = None
                        if value['wavemin'] is not None and value['wavemax'] is not None:
                            row["Wavelength"] = u.Quantity(
>                               [float(value['wavemin']), float(value['wavemax'])],
                                unit=waveunit)
E                           ValueError: could not convert string to float: 'N/A'
```

build log here: https://github.com/sunpy/sunpy/actions/runs/4540234484/jobs/8001170239#step:10:5326

**Comment by nabobalis** [comment]
@sunpy/vso-contacts

It seems that now "wavemin" and "wavemax" now return a "N/A" string value instead of a None as it was before. Is this intended?

**Comment by dstansby** [comment]
Did these just stop failing? Can we close this now?

**Comment by nabobalis** [comment]
It was a bug in the return that was fixed by the VSO.
