### ISSUE TITLE
Colormaps

### ISSUE THREAD

**Issue by souvikita** [sunpy/sunpy#6912]
### Describe the feature

Could it be interesting to provide the reverse colormaps from the existing instruments? E.g. **'irissji1330_r'** or **'sdoaia171_r'**? At the moment, it is is perhaps not supported.

**Comment by ayshih** [comment]
It takes a bit more effort, but you can reverse any colormap by calling `.reversed()` on the actual colormap instance:
```python
import matplotlib.pyplot as plt
from matplotlib import colormaps

import astropy.units as u

import sunpy.map
from sunpy.data.sample import AIA_171_IMAGE

aia = sunpy.map.Map(AIA_171_IMAGE)

aia.plot_settings['cmap'] = colormaps.get_cmap('sdoaia171').reversed()

plt.figure()
aia.plot(clip_interval=(1, 99.9)*u.percent)
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/991759/231336800-2dcbaa68-62ef-48fb-8423-fd2d51d673b8.png)

**Comment by souvikita** [comment]
Thanks! This looks good!
