### ISSUE TITLE
Drop parfive < 2

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6940]
### Provide a general description of the issue or problem.

After the 5.0 release we can drop parfive 1.x as 2.0 was released in [July 2022](https://pypi.org/project/parfive/#history)

**Comment by dstansby** [comment]
Our policy is 24 months, so I don't think we can drop it until July 2024?

**Comment by dstansby** [comment]
Ah, actually I guess the relevant date is Sep 24th 2021, which is when 1.5.0 was released, so we probably can drop support for parfive 1.x in sunpy 5.1

**Comment by nabobalis** [comment]
I want to drop this for 5.0. We already have hit a download problem with the JSOC and supporting both versions of parfive was making that more difficult than it needs to be.
