### ISSUE TITLE
conda version of sunpy 4.1.5 installs non-working h5py version

### ISSUE THREAD

**Issue by jgieseler** [sunpy/sunpy#6945]
### Describe the bug

If sunpy 4.1.5 is installed with Anaconda (`conda install -c conda-forge sunpy`), it seems to install a non-working version of h5py, causing an error when importing h5py:
```
ImportError: [..] /lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pget_fapl_direct
```
The h5py version installed using the conda command from above is 3.7.0. As installing sunpy 4.1.5 with pip installs h5py 3.8.0, I manually updated it to 3.8.0 using conda, and that solves the problem for me (see example below). 

I don't know if the problem originates somewhere in the solver (maybe connected to something like this: https://github.com/h5py/h5py/issues/1880), and also don't know why h5py<3.8.0 doesn't work. A solution would be just to increase the required version, or find the actual problem.

### To Reproduce

$ conda create --name testsunpy python=3.9
$ conda activate testsunpy
$ conda install -c conda-forge sunpy
$ python
$ >>> from sunpy.io.cdf import read_cdf
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/sunpy/io/cdf.py", line 9, in <module>
    from sunpy.timeseries import GenericTimeSeries
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/sunpy/timeseries/__init__.py", line 2, in <module>
    from sunpy.timeseries.sources import *
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/sunpy/timeseries/sources/__init__.py", line 11, in <module>
    from sunpy.timeseries.sources.goes import XRSTimeSeries
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/sunpy/timeseries/sources/goes.py", line 7, in <module>
    import h5netcdf
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/h5netcdf/__init__.py", line 15, in <module>
    from .core import CompatibilityError, Dimension, File, Group, Variable  # noqa
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/h5netcdf/core.py", line 9, in <module>
    import h5py
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /home/gieseler/anaconda3/envs/testsunpy/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pget_fapl_direct
```
$ conda list h5py
```
# packages in environment at /home/gieseler/anaconda3/envs/testsunpy:
#
# Name                    Version                   Build  Channel
h5py                      3.7.0           nompi_py39h63b1161_100    conda-forge
```
$ conda install -c conda-forge h5py=3.8.0
$ python
$ >>> from sunpy.io.cdf import read_cdf
$ >>> read_cdf
<function read_cdf at 0x7f3945ae14c0>

### Installation method

conda

**Comment by Cadair** [comment]
Thanks @jgieseler that's... weird.

**Comment by jgieseler** [comment]
I haven't tried so far if the problem also occurs with other sunpy versions or on other computers. :thinking:

**Comment by jgieseler** [comment]
Ok, this is really strange. I just installed sunpy in a new (but identical) environment using mamba (`mamba install -c conda-forge sunpy`). That also installs h5py 3.7.0, but with that version the importing works. But according to `conda list h5py`, it installs exactly the same build of h5py as before (nompi_py39h63b1161_100 from conda-forge).

I have no idea if this is only some strange behaviour of my installation or a real issue... :shrug: It does seem similar to the issue https://github.com/h5py/h5py/issues/1880 I already mentioned, in that some dependencies to h5py sometimes are not set correctly. That probably would make it a h5py and/or conda/mamba problem.

**Comment by dstansby** [comment]
I'd be inclined to say this is a `h5py` problem? Not ideal that sunpy is pulling in a none-working `h5py` version, but I think that's due to a broken install of `h5py` independently and not through an interaction with `sunpy`. As such I'll close for now, but feel free to leave a comment if you think it should be re-opened.
