### ISSUE TITLE
Plot map error - matplotlib and astropy version incompatibility  

### ISSUE THREAD

**Issue by hpwarren** [sunpy/sunpy#6946]
### Describe the bug

A simple plot of a map (see below) is failing with this error. 

. . . 
 File "/Users/harry/anaconda3/lib/python3.10/site-packages/matplotlib/figure.py", line 743, in add_subplot
    ax = projection_class(self, *args, **pkw)
TypeError: WCSAxes.__init__() got multiple values for argument 'wcs'

### To Reproduce
```
import sunpy.map
from astropy.io import fits
import sunpy.data.sample

aia = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
aia.plot()
```

### System Details

General
#######
OS: Mac OS 12.6.3
Arch: 64bit, (arm)
sunpy: 4.1.5
Installation path: /Users/harry/anaconda3/lib/python3.10/site-packages/sunpy-4.1.5.dist-info

Required Dependencies
#####################
astropy: 5.1
numpy: 1.23.5
packaging: 22.0
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 2.15.0
asdf-astropy: 0.4.0
beautifulsoup4: 4.11.1
cdflib: Missing cdflib!=0.4.0,>=0.3.19; extra == "timeseries"
dask: 2022.7.0
drms: 0.6.3
glymur: Missing glymur!=0.9.0,!=0.9.5,>=0.8.18; extra == "jpeg2000"
h5netcdf: Missing h5netcdf>=0.8.1; extra == "timeseries"
h5py: 3.7.0
lxml: 4.9.1
matplotlib: 3.7.0
mpl-animators: 1.1.0
pandas: 1.5.3
python-dateutil: 2.8.2
reproject: 0.10.0
scikit-image: 0.19.3
scipy: 1.10.1
sqlalchemy: 1.4.39
tqdm: 4.64.1
zeep: 4.2.1

### Installation method

pip

**Comment by Cadair** [comment]
hey @hpwarren thanks for the bug report, could you paste the whole traceback for us please? (you can put it in triple backticks ```) thanks!

**Comment by Cadair** [comment]
@hpwarren I think I have figured out your issue, you have incompatible versions of matplotlib and astropy installed, not sure how you have a version of matplotlib that was released more recently than the version of astropy, but if you want to keep all your packages the same versions you can do `conda install astropy<5.2` to install the latest bug fix version of the 5.1 series of astropy releases.
 
If you aren't worried about keeping your packages the same version, I suggest you just recreate your conda env with new packages.

**Comment by Cadair** [comment]
For anyone else who comes along, I could reproduce this with a local env I made by running `pip install "sunpy[map]" astropy==5.1 matplotlib==3.7.0 numpy==1.23.5` in a python 3.10 venv.

**Comment by nabobalis** [comment]
Is there anything we can do with our own minimum dependencies?

**Comment by Cadair** [comment]
I don't think so, I don't think there is actually a bug here at all. A new version of mpl came out and astropy released patches to work around compatibility issues. It's not standard practice to pin maximal versions, and no way for pip to retroactively publish incompatible versions so we end up in a situation where you can't reliably mix older and newer packages. :shrug:

**Comment by hpwarren** [comment]
Thanks for the inputs!

Note that the error I saw this morning was from a fresh install of Anaconda and the default install of sunpy:

> sh Anaconda3-2023.03-MacOSX-arm64.sh -b
> pip install "sunpy[all]"

If I manually specify the latest versions of astropy and matplotlib with pip, then everything works.

> pip install matplotlib==3.7.1
> pip install astropy==5.2.2

**Comment by wtbarnes** [comment]
I've reopened this because if this is happening on a fresh install, we likely need to adjust our pinning of matplotlib.

**Comment by dstansby** [comment]
Could you run `pip list` after installing sunpy, and post the output? I've just created a new conda environment with Python 3.11, and `pip install 'sunpy[all]'` installs `astropy                  5.2.2` and `matplotlib               3.7.1`, which given discussion above should be compatible.

**Comment by nabobalis** [comment]
> Note that the error I saw this morning was from a fresh install of Anaconda and the default install of sunpy:
> 
> > sh Anaconda3-2023.03-MacOSX-arm64.sh -b
> > pip install "sunpy\[all\]"

Thank you for providing this

Can you tell me what `pip install "sunpy[all]"` downloaded and installed?
I am curious as to what pip had to fetch.

So I think there are two potential issues here.

1. Whatever Anaconda is shipping has a version of astropy and matplotlib that might be incompatible. I am unsure how we should debug this and report it to Anaconda themselves.

2. We actually do not support pip installing sunpy within full Anaconda environmental like you are doing here. This is for several reasons but what we normally recommend is to install miniforge (see https://docs.sunpy.org/en/latest/tutorial/installation.html). I know this isn't really a great answer to your problem but we have to restrict how we recommend installing sunpy due to the numerous possible combinations and we do not have the ability to test all of it. If you need to use a full anaconda environment, and you need sunpy, you have to add conda-forge (https://conda-forge.org/#about) and then conda install sunpy. But we highly recommend working with a new virtual environment.

**Comment by Cadair** [comment]
> > Whatever Anaconda is shipping has a version of astropy and matplotlib that might be incompatible. I am unsure how we should debug this and report it to Anaconda themselves.

According to the astropy issue cross referenced above, this mayb well actually be the case.
