### ISSUE TITLE
Our oldestdeps is failing on the 4.1 branch due to a numpy / hypothesis incompatibility

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6974]
### Describe the bug

Need to pin down hypothesis

**Comment by Cadair** [comment]
Also on 4.0 but maybe for a different reason.

**Comment by dstansby** [comment]
There's nothing in the 4.1 changelog directory, so maybe we just cut our losses and don't bother fixing this given 5.0 will be out soon?

**Comment by nabobalis** [comment]
Yeah, I am with David on this.
