### ISSUE TITLE
HMI Magnetograms not centred

### ISSUE THREAD

**Issue by JulioHC00** [sunpy/sunpy#6997]
### Describe the bug

When loading an HMI magnetogram directly from JSOC, the (0,0) Heliographic Stonyhurst point is not centred in the image. Instead, it seems to wobble over time. I'm unsure whether this is meant to happen with SDO observations, but as far as I know this isn't to be expected. JHelioviewer images don't seem to be tilted like this. Since the fits files are downloaded directly from JSOC I'm thinking it may have something to do with SunPy.

### To Reproduce

```python

import sunpy.map as smap
from sunpy.coordinates import HeliographicStonyhurst
from astropy.coordinates import SkyCoord
import matplotlib.pyplot as plt
import drms

#timestamp = '2010.05.01_00:12:00_TAI'
timestamp = '2015.06.30_00:36:00_TAI'

jsoc_request_str = f"hmi.M_720s[{timestamp}]{{magnetogram}}"
result = client.export(jsoc_request_str, method="url", protocol="fits")
url = result.urls["url"][0]

hmi_map = smap.Map(url)
rotated_hmi_map = hmi_map.rotate(order=3)

stonyhurst_centre = SkyCoord(0 * u.deg, 0 * u.deg, frame=HeliographicStonyhurst, obstime=timestamp)

fig = plt.figure()
ax = plt.subplot(projection=rotated_hmi_map)

rotated_hmi_map.plot(axes=ax)
rotated_hmi_map.draw_limb()

ax.plot_coord(stonyhurst_centre, "x", color="white")
```

### Screenshots

![image](https://user-images.githubusercontent.com/81090346/236832755-803706d1-6f4f-4428-a5e2-ae53b27be71a.png)

### System Details
```
==============================
sunpy Installation Information
==============================

General
#######
OS: Ubuntu (22.04, Linux 5.19.0-41-generic)
Arch: 64bit, (x86_64)
sunpy: 4.1.3
Installation path: [/home/julio/cmeml/env/lib/python3.9/site-packages/sunpy-4.1.3.dist-info](https://file+.vscode-resource.vscode-cdn.net/home/julio/cmeml/env/lib/python3.9/site-packages/sunpy-4.1.3.dist-info)

Required Dependencies
#####################
astropy: 5.2.1
numpy: 1.24.2
packaging: 23.0
parfive: 2.0.2

Optional Dependencies
#####################
asdf: Missing asdf>=2.8.0; extra == "asdf"
asdf-astropy: Missing asdf-astropy>=0.1.1; extra == "asdf"
beautifulsoup4: 4.11.2
cdflib: Missing cdflib!=0.4.0,>=0.3.19; extra == "timeseries"
dask: 2023.3.2
drms: 0.6.3
glymur: Missing glymur!=0.9.0,!=0.9.5,>=0.8.18; extra == "jpeg2000"
h5netcdf: Missing h5netcdf>=0.8.1; extra == "timeseries"
h5py: 3.8.0
lxml: 4.9.2
matplotlib: 3.7.1
mpl-animators: Missing mpl-animators>=1.0.0; extra == "map" or "visualization"
pandas: 1.5.3
python-dateutil: 2.8.2
reproject: 0.10.0
scikit-image: 0.20.0
scipy: 1.9.1
sqlalchemy: Missing sqlalchemy>=1.3.4; extra == "database"
tqdm: 4.65.0
zeep: 4.2.1
```
### Installation method

pip

**Comment by ayshih** [comment]
When you specify a 2D Stonyhurst heliographic coordinate (i.e., just longitude and latitude) , it is automatically promoted to a 3D Stonyhurst heliographic coordinate (i.e., longitude, latitude, and radial distance from Sun center) by assuming the coordinate is on the surface of the Sun.  That is, (0,0) becomes (0, 0, Rsun).  If you instead want the center of the Sun, you should explicitly set the radial distance to be zero.

So, the reason that Stonyhurst heliographic (0, 0) does not lie in the center of the apparent disk is because (0, 0, Rsun) does not lie in the center of the apparent disk.  At the time of your magnetogram, SDO is at 2.71 deg heliographic latitude.  So, the center of the apparent disk is Stonyhurst heliographic (0, 2.71 deg, Rsun), while (0, 0, Rsun) will be south of the center of the apparent disk.

Does that make sense?

**Comment by JulioHC00** [comment]
Thanks! I think it makes sense. Does that mean that in order to convert positions of features whose coordinates are given in Stonyhurst coordinates into pixel coordinates, one needs to know the position of SDO at the time? Or know the height of the feature?

**Comment by ayshih** [comment]
`sunpy` will use the position of SDO as stored in the FITS metadata.  If the feature is on the solar surface (e.g., an active region), you can simply use a 2D coordinate as you have above, and the transformation to pixel coordinates will be correct.

If the feature is at some height above the solar surface, you will need to explicitly specify the height when creating the `HeliographicStonyhurst` coordinate.

**Comment by JulioHC00** [comment]
Makes sense! Thanks! Just to confirm, that means that for translating HARPs bounding boxes into pixel coordinates just defining a 2D SkyCoord should provide the correct part of the image even if the centre of the image isn't (0,0) in Stonyhurst?

**Comment by ayshih** [comment]
Yup!

**Comment by wtbarnes** [comment]
@JulioHC00 I'm going to go ahead and close this as it seems like your original question has been answered but feel free to ask for any clarifications or reopen if you feel like this hasn't been resolved.

**Comment by nabobalis** [comment]
Is this worth a topic guide in the future?
