### ISSUE TITLE
Doc refactor has removed references in use by external projects

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6999]
### Describe the bug

I don't know if we just want to close this with wont fix, but @nabobalis noticed in [a dkist PR](https://github.com/DKISTDC/dkist/pull/225#issuecomment-1526073089) that we have removed the `fido_guide` anchor. I expect we have removed others that external repos could be using.

**Comment by wtbarnes** [comment]
What did that previously point to? Was it the acquiring data section of the tutorial?

**Comment by Cadair** [comment]
Specifically the finding and downloading data section: https://github.com/sunpy/sunpy/blob/4.1/docs/guide/acquiring_data/fido.rst?plain=1#L1

**Comment by wtbarnes** [comment]
I agree that we should keep this in mind when removing/changing anchors but our docs are not, at least formally, a public API (except those parts which actually are a part of the public API obviously). Also, given our reorganization of the docs, even if we kept the anchors, there would be no guarantee that those pages still contain the information an external page originally wanted to reference. In that way, I would claim a broken link is in some ways better than one that unintentionally links to the wrong page. With a broken link, you at least know something is wrong.

**Comment by dstansby** [comment]
What is the request for action here? That we try and put back broken links somewhere? Or we have better changelog entries about the links we've broken?

**Comment by dstansby** [comment]
I'm going to say the ship has sailed here and we should just close this issue?
