### ISSUE TITLE
Setting rcparams in STEREO example gallery entry globally alters plots in tutorial

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#7003]
The ["where is STEREO" plot example gallery](https://docs.sunpy.org/en/latest/generated/gallery/showcase/where_is_stereo.html#sphx-glr-generated-gallery-showcase-where-is-stereo-py) sets the `rcparams` to alter several aspects of the plot appearance. This seems to have the unintentional effect of altering the appearance of the plots in the tutorial as well. For example, see https://sunpy--6944.org.readthedocs.build/en/6944/tutorial/maps.html#basic-plotting. Instead, the rcparams in that example should be changed only in a limited context.

**Comment by dstansby** [comment]
Fixed by
