### ISSUE TITLE
make scraper clients not require a pattern string in addition to baseurl

### ISSUE THREAD

**Issue by exitflynn** [sunpy/sunpy#7073]
When writing scraper clients, we require a baseurl and a pattern, an example from the NOAA Client:
```python
baseurl = r'ftp://ftp.ngdc.noaa.gov/STP/swpc_products/daily_reports/solar_region_summaries/%Y/%m/%Y%m%dSRS.txt'
pattern = '{}/{year:4d}/{month:2d}/{year:4d}{month:2d}{day:2d}SRS.txt'
```

Instead of passing both, we should be able to merge them into just one since the pattern string is conveying information that is already available in the baseurl.

(this issue is as part of my GSoC project and I'll be working on it)

**Comment by exitflynn** [comment]
The only use for the pattern string in a scraper / generic client is to [get metadata like day, month, year](https://github.com/sunpy/sunpy/blob/main/sunpy/net/dataretriever/client.py#L239), that is the it's only use is to be used as a pattern for `parse` to get metadata from.

Now since the `baseurl` follows the `strftime` format codes, we should be able to generate the `pattern` string to use for parsing from it.

**Comment by nabobalis** [comment]
Closed by https://github.com/sunpy/sunpy/pull/7077
