### ISSUE TITLE
Re-implement `get_horizons_coord()` to not use `astroquery`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7080]
The function `sunpy.coordinates.get_horizons_coord()` internally uses `astroquery` to query JPL Horizons for the location of a wide range of solar-system bodies.  We don't use rely on any other functionality of `astroquery` (not counting the example gallery), nor do we even utilize its support for other parts of the JPL Horizons API.  We can re-implement `get_horizons_coord()` to directly query JPL Horizons in exactly the manner needed, and remove the (optional) dependency on `astroquery`.

x-ref #7066

**Comment by Jett-Code** [comment]
How can we directly query JPL Horizons?

**Comment by Cadair** [comment]
We would make a direct HTTP call to [their API](https://ssd-api.jpl.nasa.gov/doc/horizons.html) and parse the output.
