### ISSUE TITLE
Convert the draw rectangle gallery example into a how-to guide

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#7082]
The [entry in the example gallery that shows how to draw a rectangle on a map](https://docs.sunpy.org/en/stable/generated/gallery/plotting/plot_rectangle.html#sphx-glr-generated-gallery-plotting-plot-rectangle-py) is a great candidate for a how-to guide. It shows four different ways to accomplish the same task. This gallery example should be converted to a how-to guide entry.

**Comment by exitflynn** [comment]
i think this could be closed now?
