### ISSUE TITLE
Function to check whether coordinate on disk is visible from another observer

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#7117]
### Describe the feature

it would be very helpful to have a helper to check whether a coordinate from one observer is visible from another. For example, say I have the coordinate of a flare from Solar Orbiter viewpoint and I want to check if its visible from Earth. 

At the moment, it can be misleading to take that coordinate and transform it using `.transform_to(frames.Helioprojective(observer="earth", obstime='xxx')` as it will give you a Tx, Ty value that could be on disk (but larger distance away) (see figure - where the coordinate as seen from solar orbiter, shouldnt be visible from earth, but when you transform that coordinate and plot it, it looks like you are "seeing" through the Sun)

![example_issue](https://github.com/sunpy/sunpy/assets/4620298/e7d7d48e-ad34-4eaa-aac6-a1a30d80312e)

### Proposed solution

A function like `is_coordinate_visible(observer, coordinate)` would be helpful, such that you pass it a coordinate from one observer and it will check if it is visible from another passed, and return `True` or  `False`.

Or indeed, maybe a helper such that it will only make the transform if it is visible?
For larger catalogues of solar orbiter events coming online, this is going to catch people up for sure by using the typical 'transform_to' ways etc

Any ideas/suggestions?

**Comment by Cadair** [comment]
You could have the observer argument be optional and `visible_from(coordinate)` defaults to `observer='self'` and uses the `.observer` attribute of the coordinate.

I don't think throwing a warning would be a great idea, there's nothing *wrong* about doing this, all of this maths is done in 3D and the back of the sun does still exist even if you can't see it :wink:

**Comment by ayshih** [comment]
xref #4891 and discussion therein
