### ISSUE TITLE
Numeric values saved in map.meta then saved to FITS get converted to string

### ISSUE THREAD

**Issue by jmason86** [sunpy/sunpy#7128]
### Describe the bug

Unusual use case, but I want to add metadata to a map and save to a FITS file. When adding a numeric value to meta, for some reason it gets converted to string when saving to FITS. I've figured out a work around using map.fits_header instead, but regardless, this doesn't seem like the intended behavior (see To Reproduce below). 

The work around looks like this, and tells me that the underlying astropy fits functions aren't the issue. 
```python
import sunpy
from sunpy.data.sample import AIA_193_IMAGE
from astropy.io import fits

map = sunpy.map.Map(AIA_193_IMAGE)
header = map.fits_header
header.set('DET_TEMP', -10.4, 'this is an optional comment that shows up to the right in the header')
hdu = fits.PrimaryHDU(map.data, header)
hdul = fits.HDUList(hdu)
hdul.writeto('test_astropy.fits')
```
This results in exactly the expected behavior. Open up the FITS file in whatever (e.g., DS9) and this new variable is in the header with a numeric value (and bonus, the comment is there as well). 

### To Reproduce

```python
import sunpy
from sunpy.data.sample import AIA_193_IMAGE

map = sunpy.map.Map(AIA_193_IMAGE)
map.meta['DET_TEMP'] = -10.4
map.save('test.fits', filetype='fits')
```
Then open up the header of the FITS file using whatever. I did it in DS9. You'll see that it has saved DET_TEMP as a string, looking like this: DET_TEMP= '-10.4      '

### System Details

- sunpy version 4.0.1
- astropy version 5.1

### Installation method

conda

**Comment by dstansby** [comment]
Odd, the roundtrip works fine:

```python
import sunpy
from sunpy.data.sample import AIA_193_IMAGE

map = sunpy.map.Map(AIA_193_IMAGE)
map.meta['DET_TEMP'] = -10.4
map.save('test.fits', filetype='fits')
```

and it looks like it's saved as a number:
```
> fitsinfo test.fits
...
AIMGSHEN=                    4                                                  
KEYWDDOC= 'https:  '                                                            
RECNUM  =             76618223                                                  
BLANK   =               -32768                                                  
DATE_OBS= '2011-06-07T06:33:07.84'                                              
XCEN    =        2.51714057528                                                  
YCEN    =       0.126135750438                                                  
DETECTOR= 'AIA     '                                                            
DET_TEMP=                -10.4       
...
```

Is there a chance this is a DS9 issue?

**Comment by dstansby** [comment]
If I view the resulting fits header using the `fitsheader` tool from astropy, it's also showing up as a number (and not a string) using the example above. So I'm going to close this - if you find more evidence that sunpy is doing something wrong feel free to open a new issue, or re-open on this one!
