### ISSUE TITLE
Issues with installing sunpy - there's still some confusion

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#7149]
### Provide a general description of the issue or problem.

At the sunpy office hours at SPD, we came across again some issue with dependency problems with astropy/sunpy on a system using anaconda. 

I dont know what we do docs wise to fix this, but maybe we shold have a "known issues" etc. For example, the issue with the package being out of date wasnt clear (it was a wcsaxes issue when plotting), so a general user wouldnt know that this is a dependency issue thing

A lot of people may not be aware of conda defaults/forge etc

**Comment by ayshih** [comment]
Although I have suggested adding documentation to help with this, honestly the most effective solution in this case would be to exclude the known buggy version of `astropy` from our dependency requirements.  That way, when a user uses `conda` to install `sunpy`, `astropy` will get updated from `conda-forge` at the same time.

**Comment by ayshih** [comment]
And by "known buggy", I actually mean "known incompatible with recent versions of dependencies"

**Comment by nabobalis** [comment]
I think this is now fixed upstream and we do not suggest anaconda install. So I will close this.

If you think that's not a fix, we can reopen this.
