### ISSUE TITLE
Remove internal coordinate-frame docstring code now that we depend on Astropy 5.0

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7179]
We should be able to revert #5497 now that we depend on Astropy 5.0, and our documentation should not be affected.

**Comment by TanviPooranmal** [comment]
The latest PR on this issue closed months back. So, can I work on this (I know issues are not assigned)?

**Comment by nabobalis** [comment]
@TanviPooranmal go ahead.
