### ISSUE TITLE
Add a GONG map class

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#7204]
### Describe the feature

[GONG synotpic maps](https://gong.nso.edu/data/magmap/) have broken FITS metadata, and cannot be loaded using just sunpy core at the moment.

This has been fixed by pfsspy but since it is now archived, we can not ask users to install this every time.

### Proposed solution

pfsspy has a GONG map class to fix some of this metadata: https://github.com/dstansby/pfsspy/blob/f493e2cdc653e541425f01318ec2f35645ee36d0/pfsspy/map.py#L12.

Copying this class over, adding unit tests and a test header are required steps to get this into sunpy core.
 
This will allow users in future to load these type of files.

**Comment by TrestanSimon** [comment]
How should the copyleft conditions of pfsspy's GPL v3 license be handled here? Per [section 5](https://github.com/dstansby/pfsspy/blob/main/LICENSE#L211-L246), modified source versions must be released under the same license. Does this condition apply here?

I have started to adapt the code and add tests, but I have yet to open a PR.

**Comment by nabobalis** [comment]
My license knowledge is limited but I think we can ask the original copyright holder to relicense the code that we add to SunPy.

**Comment by dstansby** [comment]
As the copyright holder of that code (specifically the GONG map class) I'm happy to relicense it under the BSD-2 clause license for sunpy.
