### ISSUE TITLE
Provide a better error message when padding a rotated map of integer data with a missing value of NaN

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7215]
Rotating a map of integer data using `missing` set to NaN (which is the default value) causes NumPy to error on this call to `numpy.pad()`:
https://github.com/sunpy/sunpy/blob/c7d9712262626704a331620f4b07dd7ee6779a17/sunpy/map/mapbase.py#L1704-L1708
We should wrap this call in a `try...except` so that we can provide a useful error message to users.

Alternatively, we could debate changing the default value for `missing`, but it's probably to keep the default as NaN.

**Comment by samish55** [comment]
I've been trying understand the issue and wanted to ask can't we just add a line of code setting missing to 0 if issubclass(self.data.dtype.type ,numbers.Integeral) .

**Comment by ayshih** [comment]
Yes, of course that could be done.  However, the reason we do not do that (anymore) is that zero is likely a valid pixel value, especially for integer data, and we don't want there to be confusion between a pixel having zero because that is the actual data value and pixel having zero because there was no data.  That is, unlike NaN, zero is not a "safe" value to represent missing data.

We could use map masks instead to denote missing data, and then setting pixels missing data to zero wouldn't be so bad, but our support for map masks is clunky.

**Comment by NucleonGodX** [comment]
@ayshih kindly check #7344

**Comment by alasdairwilson** [comment]
Closed as completed via #7344
