### ISSUE TITLE
Allow `clip_interval` and `vmin/vmax` be passed to MapSequence plotting

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#7252]
### Describe the feature

Currently for MapSequence.plot(), you can pass `cmap` and `norm` for plotting a sequence following #5889 . 

However, it may be nice to also be able to pass `clip_interval` and `vmin/vmax` explicitly, such that it follows the same from `Map.plot()`

For example, currently if you do:

``` python
import sunpy.map
import sunpy.data.sample
from astropy.visualization import ImageNormalize

m_seq = sunpy.map.Map([
    sunpy.data.sample.AIA_193_CUTOUT01_IMAGE,
    sunpy.data.sample.AIA_193_CUTOUT02_IMAGE,
], sequence=True)

m_seq.plot(clip_interval=[5, 99.9]*u.percent)
```
the clipping is only applied to the first image of the sequence. This is the same for passing`vmin/vmax`,
### Proposed solution

Implement it in `MapSequence.plot()`

**Comment by ryuusama09** [comment]
@hayesla  , can I get the context of why this feature is requested . It would be easier for me to interpret all these terms !. Thank you

**Comment by nabobalis** [comment]
@ryuusama09, there is an open pull request for this issue, #7253

I would suggest looking at another issue.

**Comment by dpshelio** [comment]
Did #7253 solve this issue?

**Comment by nabobalis** [comment]
Probably
