### ISSUE TITLE
Updating VSO attrs is broken

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#7256]
### Describe the bug

Trying to update the VSO attributes, and it looks like the URL we use to get the VSO registry is throwing a 403 error. @sunpy/vso-contacts is https://vso1.nascom.nasa.gov/cgi-bin/registry_json.cgi going to be permanently down, and if so is there an alternative URL we can use to get the registry?

### To Reproduce
```python
% python tools/update_attrs_json.py 
Updating the attrs json files using sunpy 5.1.dev286+gdd37abafd...
Updating VSO json...
Traceback (most recent call last):
  File "/Users/dstansby/software/sunpy/tools/update_attrs_json.py", line 11, in <module>
    VSOClient.create_parse_vso_values()
  File "/Users/dstansby/software/sunpy/sunpy/net/vso/vso.py", line 687, in create_parse_vso_values
    response = urlopen(req)
               ^^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by AlisdairDavey** [comment]
David, can you try again please. vso1 is a new version of vso1 and it looked like we were missing a package.

**Comment by ejm4567** [comment]
What is the data being sent to the CGI script registry_json.cgi?

This may be either an SELinux issue (all SDAC machines now have SELinux enabled), or a mod_security issue.

**Comment by wtbarnes** [comment]
The script that is being run is here: https://github.com/sunpy/sunpy/blob/main/tools/update_attrs_json.py

The relevant bit of that script is actually the lines in this method: https://github.com/sunpy/sunpy/blob/de94545efd11c4146b701c795c358f098e0d85af/sunpy/net/vso/vso.py#L679-L686.

**Comment by ejm4567** [comment]
Was this update running correctly prior to Oct. 24th ?

Typing into a browser:

https://vso1.nascom.nasa.gov/cgi-bin/registry_json.cgi?fields=[%22%2Bdetector%22] 

for example, and get the expected results.

Apache access log entry:

A.B.C.D - - [26/Oct/2023:08:07:43 -0400] "GET /cgi-bin/registry_json.cgi?fields=%5B%22%2Bdetector%22%5D HTTP/1.1" 200 6180

**Comment by dstansby** [comment]
Huh, weirdly manually passing the query in the url as a string works, but passing it as `data` to a python `Request` object seems to have broke... anyway, https://github.com/sunpy/sunpy/pull/7264/commits/a8b01fe333076e944b5be0baa0d91254f204cba0 seems to fix this. Thanks for the help!

**Comment by ejm4567** [comment]
Great!   Glad that fixed it.
