### ISSUE TITLE
Documentation builds are very slow (and caching is not effective)

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#7268]
### Describe the performance issue

When i build the docs whether using `make html` or `tox -e build_docs` the build deletes previously generated files such as the api files and then have to regenerate them every time. This makes the build very slow. On my machine, it takes 5 mins for make html and half that time with tox.

Do we need to regenerate those files on every build?

### To Reproduce

make html

or 

tox -e biuld_docs

### Proposed fix

Do not regenerate those files in each build.

**Comment by Cadair** [comment]
The issue seems to be that a large number of files are getting invalidated in sphinx's cache (maybe not all of them?) when it's not clear why!

**Comment by ayshih** [comment]
Is this a recent development?  In the past, my `api` files would definitely be cached when using `make html`, which I know because I'd have to manually clear it out to see API changes that I made reflected in the docs.

`tox` does `tox` things, so I can't speak for `tox`

**Comment by ayshih** [comment]
Hmm, okay, maybe `sunpy.coordinates` API files aren't getting invalidated =)

**Comment by ayshih** [comment]
Heh, maybe it's a Mac thing!

**Comment by ayshih** [comment]
Oh, never mind then

**Comment by ayshih** [comment]
What Sphinx version?

**Comment by nabobalis** [comment]
Yeah I am interested, did they do something in a new release.

**Comment by nabobalis** [comment]
7.2.6 was the version

**Comment by ayshih** [comment]
I can definitely reproduce this now, but I'm befuddled by what has changed.  I'm pretty sure it hadn't been like this a few months ago when I was still working on fixing the inheritance-diagram links.  I tried downgrading to Sphinx 5.3.0, and it's still rebuilding everything.  Maybe something having to do with our updated theme?

**Comment by ayshih** [comment]
Perhaps there is poor caching, but I think there is something really borked with our (new) theme.  I just timed a couple of docs re-builds.  When I re-build the docs under our theme, the writing of all of the (non-cached) HTML files takes ~12 minutes(!).  If I disable our theme and use the default Sphinx theme instead, the same writing takes ~50 *seconds*.  That is a monumental difference!  What is our theme doing?!?

**Comment by nabobalis** [comment]
I wonder if it's worth asking upstream?

**Comment by wtbarnes** [comment]
What happens if you just use the plain pydata theme? That would help nail down whether it's the base theme or something specific to the sunpy one.

**Comment by ayshih** [comment]
Some timing runs of just the "writing output" phase of the docs build:

- SunPy Sphinx theme
  - Build from scratch: 12 minutes, 10 seconds
  - Re-build: 12 minutes, 20 seconds
- PyData Sphinx theme
  - Build from scratch: 5 minutes, 15 seconds
  - Re-build: 4 minutes, 55 seconds
- default Sphinx theme
  - Build from scratch: 70 seconds
  - Re-build: 50 seconds

So, yes, the PyData Sphinx theme is slow, but our theme is over twice as slow.

**Comment by dstansby** [comment]
I did some profiling, and tracked the issue down in pydata-sphinx-theme: https://github.com/pydata/pydata-sphinx-theme/issues/889#issuecomment-1820549861

**Comment by nabobalis** [comment]
This was fixed upstream and we updated our theme to use that version now.
