### ISSUE TITLE
Test failures in integration testing with astropy v6.0rc1

### ISSUE THREAD

**Issue by pllim** [sunpy/sunpy#7295]
### Describe the bug

As reported by @astrofrog at https://github.com/astropy/astropy-integration-testing/issues/13

Would be nice if we can figure it out why before astropy v6.0rc2 comes out. Or if you rather do your own testing, maybe we can remove sunpy from https://github.com/astropy/astropy-integration-testing setup? If you test yourselves, please update https://github.com/astropy/astropy/wiki/v6.0-RC-Testing accordingly. Thanks!

### To Reproduce

See log at https://github.com/astropy/astropy-integration-testing/actions/runs/6830456558/job/18578429528

### Screenshots

N/A

### System Details

See log above.

### Installation method

pip

**Comment by nabobalis** [comment]
Only @Cadair can work out what is going on and fix it for you.

**Comment by Cadair** [comment]
@braingram might have ideas given I am not working at the moment.

**Comment by Cadair** [comment]
@pllim I am curious why our astropy dev builds haven't caught this? We regularly test against the nightly wheels.

**Comment by Cadair** [comment]
Having now looked at the build output I believe that is fixed by a newer / dev version of asdf-astropy?

**Comment by pllim** [comment]
> why our astropy dev builds haven't caught this?

🤷‍♀️ 

What we do is specifically RC testing, so RC + stable dependencies only. If you been testing both astropy dev and asdf-astropy dev together and somehow asdf-astropy stable isn't compatible with astropy dev, then maybe your CI won't catch it. Does this mean asdf-astropy needs a new release?

**Comment by pllim** [comment]
@astrofrog , can we just not run doctest for sunpy over at astropy-integration-testing matrix?

**Comment by astrofrog** [comment]
Yes do you know how to turn doctest off?

**Comment by pllim** [comment]
Thanks, @WilliamJamieson . Do you have a timeline for the asdf-astropy release? 🙏

**Comment by nabobalis** [comment]
Give me write access and I can get that release out asap.

**Comment by pllim** [comment]
BTW I dunno if this is related but I also noticed sunpy job failure in asdf-astropy "downstream testing": https://github.com/astropy/asdf-astropy/actions/runs/6846292068/job/18612721714

**Comment by WilliamJamieson** [comment]
I can do one tomorrow if I have time. @braingram is welcome to do the release too.

**Comment by pllim** [comment]
This issue is fixed by:

* copying sunpy test config to integration testing repo, and
* releasing asdf-astropy 0.5;

Thanks, all!
