### ISSUE TITLE
Add an example of plotting a rectangle on a map with a rotation angle relative to the axes

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7303]
See title, would involve using `SkyOffsetFrame`

**Comment by NucleonGodX** [comment]
@ayshih this would be added in the examples/plotting/plot_rectangle.py file or a new file needs to be created?

**Comment by ayshih** [comment]
A new file

**Comment by alasdairwilson** [comment]
Closed as completed via #7348
