### ISSUE TITLE
Resampling Maps in the example gallery gives a confusing example for the superpixel method

### ISSUE THREAD

**Issue by clarafroment** [sunpy/sunpy#7315]
### Provide a general description of the issue or problem.

That's a minor thing perhaps but checking this [page](https://docs.sunpy.org/en/stable/generated/gallery/map/map_resampling_and_superpixels.html) I got confused by the example for the superpixel method. 
It says:
`new_dimensions = u.Quantity(aia_map.dimensions) / 16`
`aia_superpixel_map = aia_map.superpixel([new_dimensions]`

The first line should be instead e.g.:
`new_dimensions=[16,16]*u.pixel `

**Comment by ayshih** [comment]
Thanks for the report!  You are quite correct; the author got mixed up between `superpixel()` and `resample()`
