### ISSUE TITLE
database tests depend on data/tests dir

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#732]
Some tests for the database package depend on the files in the directory data/tests. This needs to be documented.

**Comment by Punyaslok** [comment]
@Cadair @derdon Could you tell me in which file this needs to be documented?

**Comment by theaverageguy** [comment]
@derdon The file location please. 
Thanks

**Comment by prateekiiest** [comment]
`from sunpy.data.test.waveunit import waveunitdir`

Like in this case. So it should be documented that we are using from the data directory??

**Comment by prateekiiest** [comment]
@dpshelio  #2011.
I have given some documentation. Can you tell me what more documentation is needed in this issue?

**Comment by prateekiiest** [comment]
PR #2049
