### ISSUE TITLE
Reprojecting AIA maps to HRI-EUV maps can result in NaN, depending on the HRI-EUV pixel size.

### ISSUE THREAD

**Issue by adolliou** [sunpy/sunpy#7323]
### Describe the bug

Dear all, 

I encountered an issue while trying to reproject AIA data into HRI-EUV pixel coordinates. The reprojected AIA map becomes NaN after the reprojection, despite HRI-EUV FOV beeing in the AIA FOV.
 This bug heavily depends on the output pixel size, as resampling the HRI_EUV image to larger pixel size prior to the reprojection "fixes" the problem. An intermediary resampling shows Nan pixels overlapping the reprojected map in a circular shape, as if we were looking at the Limb. I checked if the WCS values were consistent after the resampling, and I did not notice a different pointing.  The issue happens with the reproject_interp and reproject_adaptive method, but not with the reproject_exact one. The AIA data I am using are a bit special, as they belong to a 6-second cadence AIA observation. 

Thank you very much for your help. Please let me know if you require additional information.

Best regards, 

### To Reproduce

from sunpy.map import Map
import astropy.units as u
from astropy.coordinates import SkyCoord
from matplotlib import pyplot as plt
from astropy.visualization import ImageNormalize, LogStretch

## AIA reprojection to HRI-EUV frame

aiamap = Map("https://git.ias.u-psud.fr/adolliou/report_issue_github/-/raw/main/data/sunpy_reprojection_issue/aia.lev1.171.1497617052.2022-03-17T00_22_03.342Z.image_lev1.fits?ref_type=heads")
hrimap = Map("https://git.ias.u-psud.fr/adolliou/report_issue_github/-/raw/main/data/sunpy_reprojection_issue/solo_L2_eui-hrieuvopn-image_20220317T001800215_V02.fits?ref_type=heads")

bottom_left = SkyCoord(hrimap.bottom_left_coord, frame=hrimap.coordinate_frame)
top_right = SkyCoord(hrimap.top_right_coord, frame=hrimap.coordinate_frame)

norm = ImageNormalize(vmin=0, vmax=3000, stretch=LogStretch())

fig = plt.figure()
ax = fig.add_subplot(projection=aiamap)
im = aiamap.plot(axes=ax, norm=norm)
aiamap.draw_quadrangle(bottom_left=bottom_left, top_right=top_right, edgecolor="r")
fig.colorbar(im)
plt.show()

![fig1](https://github.com/sunpy/sunpy/assets/48285510/cd19c226-d158-4e7f-83e9-c1c225d06718)

aia_reprojected = aiamap.reproject_to(hrimap.wcs, algorithm="interpolation")
aia_reprojected.peek()

![fig2](https://github.com/sunpy/sunpy/assets/48285510/803a413f-fa1d-46e1-b455-338e3e2876e6)

## Binning HRI maps

print(f'{hrimap.data.shape=}')
hrimap.peek()
new_shape = [1500 , 1500]* u.pixel
hrimap_bin_1500 = hrimap.resample(new_shape)

new_shape = [600 , 600]* u.pixel
hrimap_bin_600 = hrimap.resample(new_shape)

## Reproject AIA to binned HRI maps

outmap_600 = aiamap.reproject_to(hrimap_bin_600.wcs)
outmap_600.peek()

![fig3](https://github.com/sunpy/sunpy/assets/48285510/22dcdad8-dcfb-406a-98eb-a141cb1c481e)

outmap_1500 = aiamap.reproject_to(hrimap_bin_1500.wcs)
outmap_1500.peek()

![fig4](https://github.com/sunpy/sunpy/assets/48285510/78bc8b23-a73c-4957-af3c-5876eb0184d6)

### Deforest

outmap_1500 = aiamap.reproject_to(hrimap_bin_1500.wcs, algorithm="adaptive")
outmap_1500.peek()

![fig5](https://github.com/sunpy/sunpy/assets/48285510/29c2f170-5363-4ff1-a35c-c194b014578a)

### Exact

outmap_1500 = aiamap.reproject_to(hrimap_bin_1500.wcs, algorithm="exact")
outmap_1500.peek()

![fig6](https://github.com/sunpy/sunpy/assets/48285510/f71d3d96-225a-4d61-a154-11d81c02d824)

### System Details

sunpy: 5.1.0
astropy: 6.0.0
numpy: 1.26.2 
reproject: 0.13.0

### Installation method

pip

**Comment by hayesla** [comment]
Hi @adolliou thanks for raising this issue!

I think the issue is the fact that the `rsun` is provided differently for the AIA and the HRI data, given by the `rsun_ref` in the FITS metadata. Its not too much of a difference, but enough to cause issues when reprojecting - this issue is described here: https://docs.sunpy.org/en/stable/topic_guide/rsun.html


To fix this issue, teh easiest way is just to make the `rsun_ref` the same for both.
For example, try do

```python
aiamap.meta["rsun_ref"] = hrimap.meta["rsun_ref"]
```
before any reprojections and it should work!

**Comment by adolliou** [comment]
Hi @hayesla , this solves perfectly the problem, thank you very much !

**Comment by ebuchlin** [comment]
Thanks @hayesla for the quick solution! This indeed reminds me some strange effects I already had when reprojecting to Carrington coordinates: large parts of the image disappeared in a way that is difficult to predict, depending on changes in `rsun_ref`, and sometimes changing the value back to the initial value did even not allow recovering the initial result... How can such small changes in `rsun_ref` have such large effects?
