### ISSUE TITLE
Function/Gallery example for outputting the versions of packages and their dependencies

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#7324]
### Provide a general description of the issue or problem.

Reproducibility of science results depends, in part, on using the same versions of the software packages used in the original analysis.  Does a function exist outside SunPy that can take a script or jupyter notebook and extract the packages used and their dependencies, and then priint out the versions of all of those packages?

While such a function may be beyond the scope of SunPy, a gallery example should be added showing how to use it, if it exists.

If it doesn't exist, perhaps we should create it.

**Comment by Lollyrana** [comment]
One such tool is pipreqs, which is commonly used to generate a requirements.txt file for a Python project. This file contains a list of all the packages used along with their versions.
# Example: reproduce_info_extractor.py

import os
import subprocess

def extract_reproduce_info(script_path):
    """
    Extracts package information and versions from a Python script or Jupyter notebook.

    Parameters:
    - script_path (str): Path to the Python script or Jupyter notebook.

    Returns:
    - None: Prints the package information to the console.
    """
    try:
        # Generate requirements.txt using pipreqs
        subprocess.run(['pipreqs', script_path])

        # Read and print the content of requirements.txt
        requirements_file = os.path.join(os.path.dirname(script_path), 'requirements.txt')
        with open(requirements_file, 'r') as file:
            print(file.read())
        
        # Optionally, you may want to clean up the generated requirements.txt file
        # os.remove(requirements_file)

    except Exception as e:
        print(f"Error: {e}")

# Example usage
if __name__ == "__main__":
    script_path = "path/to/your/script_or_notebook.py"
    extract_reproduce_info(script_path)

**Comment by Rjchauhan18** [comment]
Hello @DanRyanIrish  sir , if this issue is still open , so can i work on it ?

**Comment by nabobalis** [comment]
> Hello @DanRyanIrish sir , if this issue is still open , so can i work on it ?

You are free to work on this issue. 

> > While such a function may be beyond the scope of SunPy, a gallery example should be added showing how to use it, if it exists.
> 
> for gallery example in how to use it in docs.

I am not sure I follow, a gallery example I think would be the place to start with this?
