### ISSUE TITLE
Add clarifications to examples that use `os.environ["JSOC_EMAIL"]`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7327]
We have three examples that have `jsoc_email = os.environ["JSOC_EMAIL"]` (where the environment variable is defined in our `conf.py` for Sphinx).  We tell users that they should use their own (registered) email address instead, but we're not clear about how the line should actually be changed.  One user on Element replaced only `"JSOC_EMAIL"` instead of replacing `os.environ["JSOC_EMAIL"]`.  Assuming that we continue to use this (exposed) environment-variable approach, we should be more clear in the associated description.

The three examples are:
https://github.com/sunpy/sunpy/blob/42087228ff25d7e3fcd4d9c86c8af12c311d5b7d/examples/acquiring_data/downloading_cutouts.py#L38-L44
https://github.com/sunpy/sunpy/blob/42087228ff25d7e3fcd4d9c86c8af12c311d5b7d/examples/acquiring_data/fido_metadata_queries.py#L24-L26
https://github.com/sunpy/sunpy/blob/42087228ff25d7e3fcd4d9c86c8af12c311d5b7d/examples/acquiring_data/querying_and_loading_SHARP_data.py#L23-L26

**Comment by abastola0** [comment]
@ayshih  can you assign me this issue?

**Comment by nabobalis** [comment]
Hello @abastola0, we do not assign people to issues as a general rule.

**Comment by abastola0** [comment]
alright. I'll send a pr directly then.

**Comment by abastola0** [comment]
it this going to be a 'trivial' change in my commit message?

**Comment by nabobalis** [comment]
> it this going to be a 'trivial' change in my commit message?

I think a `doc` one would be good.
