### ISSUE TITLE
Add warning when importing map (or other subpackages) if mpl (or others?) are not installed,

### ISSUE THREAD

**Issue by alasdairwilson** [sunpy/sunpy#7333]
### Describe the feature

We should warn if trying to import map without having map dependencies, could also be done for all our subpackages bar coords, but map is likely the biggest.

### Proposed solution

Suggest user installs sunpy[map] or sunpy[all] in init for map.

**Comment by NucleonGodX** [comment]
can I get some idea where the changes will need to be made for this ?

**Comment by Cadair** [comment]
Don't you get an import error if you import map without mpl? I would be interested to know which of our deps are "optional" vs a requirement to import.

**Comment by ayshih** [comment]
Presumably the user would be missing subpackage (non-optional) dependencies because they typed `pip install sunpy` instead of `pip install sunpy[...]`.  So, instead of leaving such a user to play whack-a-mole until there are no more `ImportError`s, all the while cursing at `sunpy` for making them install each dependency manually, we'd catch the errors and tell them how to pip install (all) subpackage dependencies.

**Comment by NucleonGodX** [comment]
ye we do, actually after installing sunpy we can use sunpy.map only if we have installed matplotlib and scipy, which are not installed when we do basic install sunpy but can be installed by using sunpy[all] or sunpy[map], other important deps like numpy, astropy etc are installed when we do basic install sunpy. @Cadair

**Comment by alasdairwilson** [comment]
So I have this like half done but haven't revisited it since before Christmas.

The idea is that in importing a submodule we check in the init for each of the declared dependencies we check if installed and emit a warning to install sunpy[submodule] or sunpy[all] or else you might encounter errors.

At the moment if a user does pip install sunpy then e.g. map can be imported without error but then map factory will give mpl errors when used.

**Comment by ayshih** [comment]
> At the moment if a user does pip install sunpy then e.g. map can be imported without error but then map factory will give mpl errors when used.

I'm not at a computer to check this, but doesn't importing `sunpy.map` import `sunpy.map.mapbase`, which imports `matplotlib`?  I don't understand why there isn't an import error.

**Comment by NucleonGodX** [comment]
> > At the moment if a user does pip install sunpy then e.g. map can be imported without error but then map factory will give mpl errors when used.
> 
> I'm not at a computer to check this, but doesn't importing `sunpy.map` import `sunpy.map.mapbase`, which imports `matplotlib`? I don't understand why there isn't an import error.

It does give import error ig.

**Comment by alasdairwilson** [comment]
I must have been misremembering what the pyopensci  reviewer said

**Comment by nabobalis** [comment]
I think the reviewer was suggesting in the main init of each submodule we check on import if all the optional dependencies are installed. If not raise a warning with a message on what to install.

**Comment by alasdairwilson** [comment]
> I think the reviewer was suggesting in the main init of each submodule we check on import if all the optional dependencies are installed. If not raise a warning with a message on what to install.

Yeah that's fine, and what I envisioned, I thought they had said they had mpl errors when instantiating a Map rather than importing map but I was going from memory and must have been mistaken.

**Comment by nabobalis** [comment]
Oh I see. I'd have to check the review again as I forgot.
