### ISSUE TITLE
[5.1.0] test_hpc_is_visible_tolerance failure

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#7349]
### Describe the bug

When running the CI tests while rebuilding the Debian package for version 5.1.0, I get the following test failure with both Python 3.11 and 3.12:
```
___________________________________________________________________________

    def test_hpc_is_visible_tolerance():
        hpc = Helioprojective(200*u.arcsec, 0*u.arcsec,
                              observer='earth', obstime='2023-08-03').make_3d()
    
        # Due to the limitations of numerical precision, the coordinate will be computed to be slightly
        # below the solar surface, and thus invisible when the tolerance is set to zero
>       assert not hpc.is_visible(tolerance=0*u.m)
E       assert not True
E        +  where True = <bound method Helioprojective.is_visible of <Helioprojective Coordinate (obstime=2023-08-03T00:00:00.000, rsun=695700....eliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcsec, arcsec, AU)\n    (200., 0., 1.01025746)>>(tolerance=(0 * Unit("m")))
E        +    where <bound method Helioprojective.is_visible of <Helioprojective Coordinate (obstime=2023-08-03T00:00:00.000, rsun=695700....eliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcsec, arcsec, AU)\n    (200., 0., 1.01025746)>> = <Helioprojective Coordinate (obstime=2023-08-03T00:00:00.000, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcsec, arcsec, AU)\n    (200., 0., 1.01025746)>.is_visible
E        +    and   Unit("m") = u.m

sunpy/coordinates/tests/test_frames.py:264: AssertionError
```
From the comment, I would think that the test itself may be not really stable; maybe one should just remove the first asser?

### System Details

- sunpy 5.10
- astropy 6.0.0
- Python 3.11/3.12
- all installed as Debian packages in Debian unstable

### Installation method

Linux package manager

**Comment by ayshih** [comment]
Hmm, okay.  That first `assert` statement should be changed instead to a `pytest.skip()` call if the `isvisible()` call is `True` at zero tolerance.

**Comment by olebole** [comment]
You even wouldn't need to skip if the first call works; the second one should succeed in any case. I'd just keep only the "tolerant" call here.

**Comment by ayshih** [comment]
The purpose would be to have it reported as a skip in the output log, because on such a system, the test would not be able to show that the non-zerp tolerance made a difference.
