### ISSUE TITLE
Add a new category to the issue templates to add a new example to the gallery

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#7386]
### Provide a general description of the issue or problem.

It would be nice to make it easy for someone to suggest a new example for the docs.

**Comment by nabobalis** [comment]
How different would you like it be from the Anything else template?

**Comment by ehsteve** [comment]
I would suggest the following fields

- Requires sample data? yes/no
- Topics Area (e.g. acquiring data, Maps, TimeSeries, etc.)
- One line description of the example
- Is it for beginners or advanced users?
- Reason why it should be added to the gallery

**Comment by nabobalis** [comment]
I will draft one now and see what you think.
