### ISSUE TITLE
pandas will soon require pyarrow and is issuing a `DeprecationWarning` because it is not installed

### ISSUE THREAD

**Issue by braingram** [sunpy/sunpy#7390]
### Describe the bug

pandas is issuing a new `DeprecationWarning` due to `pyarrow` not being installed (the warning mentions that `pyarrow` will be a requirement in an upcoming release). This new warning will stop test runs (if warnings are turned into errors) as seen in this downstream run for asdf:
https://github.com/asdf-format/asdf/actions/runs/7607641020/job/20715325147#step:10:534

2 possible solutions to this problem are:
- require `pyarrow` as a dependency
- add a warning filter for the test runs to filter out the new warning

xref: https://github.com/pandas-dev/pandas/issues/54466

### To Reproduce

install sunpy dev, run tests (see above test run log)

**Comment by Cadair** [comment]
Don't forget that leading `\n` on the deprecation warning when writing that filter :angry:

**Comment by gjkoplik** [comment]
> Don't forget that leading `\n` on the deprecation warning when writing the filter 😠

THANK YOU for catching this, I'm not a `sunpy` user but was losing my mind trying to fix my CI elsewhere. I was just missing the `\n`.

**Comment by nabobalis** [comment]
Other choice is to do something like `(?s).*Pyarrow will become a required dependency of pandas`
