### ISSUE TITLE
pytest 8 warning `PytestRemovedIn9Warning: Marks applied to fixtures have no effect`

### ISSUE THREAD

**Issue by braingram** [sunpy/sunpy#7423]
### Describe the bug

When running the sunpy tests as part of the asdf downstream tests we encounter the following error:
```
 E   pytest.PytestRemovedIn9Warning: Marks applied to fixtures have no effect
```
See: https://github.com/asdf-format/asdf/actions/runs/7717012615/job/21035144983?pr=1745#step:10:582

The warning (turned into an error) stops test collection and appears to be caused by uses like the following:
https://github.com/sunpy/sunpy/blob/090641f28b96507b78d7e64978f7c41d1c4c717b/sunpy/io/special/asdf/tests/test_coordinate_frames.py#L28-L30
where `asdf_entry_points` is a pytest mark.

### System Details

- sunpy version: dev
- pytest version: 8.0.0

**Comment by nabobalis** [comment]
Yeah our CI is on fire due to that. We have an open PR that fixes this but it needs a bit more work.

**Comment by braingram** [comment]
Thanks! I missed that PR. A quick glance makes me think it should fix this issue.

xref: https://github.com/sunpy/sunpy/pull/7417
