### ISSUE TITLE
Turn the SunPy Project into a mono repo

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#7447]
### Provide a general description of the issue or problem.

The lead developer has decreed it: https://matrix.to/#/!MeRdFpEonLoCwhoHeT:matrix.org/$170785419358wNzYd:cadair.com?via=matrix.org&via=openastronomy.org&via=cadair.com

**Comment by Cadair** [comment]
![but_it_is_not_this_day](https://github.com/sunpy/sunpy/assets/1391051/74ef0c71-7646-4059-81c8-8bc6cbf48188)
