### ISSUE TITLE
Fix inaccuracies in `sunpy.map.maputils.py`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7478]
The following calculations in `sunpy.map.maputils.py` ought to be fixed to not use the Cartesian approximation:

https://github.com/sunpy/sunpy/blob/3939b7e56428fd6df65d8f85499ad6dbbae8ccea/sunpy/map/maputils.py#L209
https://github.com/sunpy/sunpy/blob/3939b7e56428fd6df65d8f85499ad6dbbae8ccea/sunpy/map/maputils.py#L260
https://github.com/sunpy/sunpy/blob/3939b7e56428fd6df65d8f85499ad6dbbae8ccea/sunpy/map/maputils.py#L290

**Comment by simoneferretti** [comment]
Hi, I've worked on the file and tried solving the inaccuracies using the separation method from Skycoord.
[maputils.json](https://github.com/sunpy/sunpy/files/14540510/maputils.json)

**Comment by simoneferretti** [comment]
Hi, I'd like to work on this issue

**Comment by nabobalis** [comment]
Go ahead @simoneferretti

**Comment by simoneferretti** [comment]
I've sent a pull request

**Comment by PaoloBiolghini** [comment]
I think I have found a possible solution, I'm going to open a PR asap

**Comment by nabobalis** [comment]
There is already a PR open here: https://github.com/sunpy/sunpy/pull/7489 if you could help that would be ideal than another PR.

**Comment by PaoloBiolghini** [comment]
sorry i didn't see the comment; should i remove my PR and link it to the one you pinged me?

**Comment by nabobalis** [comment]
Can you add code suggestions to the original PR that I linked to?

**Comment by ayshih** [comment]
Since multiple folks have been having difficulties making the appropriate fix, clearly it was not a "good first issue" like I had thought.  I have fixed it myself in #7512.
