### ISSUE TITLE
Document and possibly raise warning about apparent hard server side limit of 20,000 for helio client

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#7535]
### Describe the bug

Seems to be a (silent?) sever side limit on the max number of record the helio service can return. Only the soft `MaxRecords` limit is documented should probably check if a query hits the limit and raise warning?

### To Reproduce

```
query = Fido.search(a.Time('2022-01-01', '2022-02-01'),
        a.helio.TableName("gevloc_sxr_flare"), 
        a.helio.MaxRecords(99999))
len(query['hec'])
20000

query = Fido.search(a.Time('2022-01-01', '2022-01-15'), 
        a.helio.TableName("gevloc_sxr_flare"),
        a.helio.MaxRecords(99999))
len(query['hec'])
20000

query = Fido.search(a.Time('2022-01-01', '2022-01-10'), 
        a.helio.TableName("gevloc_sxr_flare"), 
        a.helio.MaxRecords(99999))
len(query['hec'])
19653
```

### System Details

```
#######
OS: Mac OS 14.3.1
Arch: 64bit, (arm)
sunpy: 5.0.0
Installation path: /Users/sm/.virtualenvs/ARCCnet/lib/python3.11/site-packages/sunpy-5.0.0.dist-info

Required Dependencies
#####################
astropy: 5.3.2
numpy: 1.25.2
packaging: 23.1
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 2.15.1
asdf-astropy: 0.4.0
beautifulsoup4: 4.12.2
cdflib: 1.1.0
dask: 2023.9.0
drms: 0.6.4
glymur: 0.12.8
h5netcdf: 1.2.0
h5py: 3.9.0
lxml: 4.9.3
matplotlib: 3.7.2
mpl-animators: 1.1.0
pandas: 2.1.0
python-dateutil: 2.8.2
reproject: 0.11.0
scikit-image: 0.21.0
scipy: 1.11.2
sqlalchemy: 2.0.20
tqdm: 4.66.1
zeep: 4.2.1
```

### Installation method

pip

**Comment by nabobalis** [comment]
We can have the MaxRecords attr issue a warning if the value is above 20000?

**Comment by samaloney** [comment]
As in you when you create it `a.helio.MaxRecords(99999)`? That will help but only in the case there query will return more than 20,000 records, I could run a query that will only return 1 record so in this case the warning wouldn't apply? Maybe raise an error if try to create `MaxRecords` above 20,000 and issue a warning if the number of returned records is equal to `MaxRecords`

**Comment by nabobalis** [comment]
That's a better idea!

**Comment by ahmedhosssam** [comment]
Hi,
I'm working on this issue right now.

**Comment by ahmedhosssam** [comment]
> Maybe raise an error if try to create `MaxRecords` above 20,000 and issue a warning if the number of returned records is equal to `MaxRecords`

You want to prevent the user from creating `MaxRecords` above 20,000, right?
If this is what should be done so I think I will first check if `max_records` is more than 20,000 to raise an error, and then check if `len(table)` equals `max_records` to issue a warning.

**Comment by samaloney** [comment]
Just for information there is something wrong with the Helio service or that particular table it is returning 1000s of flares (many duplicates) per day for early 2022.

**Comment by nabobalis** [comment]
Can we get them to fix that?
