### ISSUE TITLE
Do not replace "DN" with "ct" in `Map.unit`

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#7544]
### Provide a general description of the issue or problem.

Currently, when parsing the unit from a `Map`, we replace any use of "DN" in `Map.unit` with "ct"/"count",

https://github.com/sunpy/sunpy/blob/0886efadfb9c82b1a366ef1624826f1e0e23e6fc/sunpy/map/mapbase.py#L727-L742

The logic here is that "DN" is not a recognized unit in the FITS standard so we shouldn't allow it as a valid value for the `BUNIT` key. However, I think there are three reasons we should NOT be making this replacement:

1. We currently only cover a subset of the cases here, e.g. "DN/pix/s" results in the unit key not being parsed at all. It seems impractical to continue to try to cover all possible uses of "DN".
2. The use of "count"/"ct" is ambiguous and a confusing substitute for "DN". This can sometimes mean "electrons" or "photons", but is rarely used to denote "DN". Furthermore "DN" is commonly used throughout solar physics and it is confusing to not use this convention.
3. `astropy.io.fits` can write and read files with "DN" in the `BUNIT` key without issue.

**Comment by ayshih** [comment]
Duplicate-ish of #6566

**Comment by wtbarnes** [comment]
Well I clearly can't remember my own issues. I'm closing this and I've copied my points over to #6566.
