### ISSUE TITLE
sunpy 5.1.1 + pytest 8 on armel & mips64el error

### ISSUE THREAD

**Issue by mr-c** [sunpy/sunpy#7550]
### Describe the bug

Building sunpy 5.1.1 with Pytest 8.1.1 + https://github.com/sunpy/sunpy/pull/7429 we still get two errors:

On armel (arm32v5): `test_map_arithmetic_operations_raise_exceptions[map-warn_context0]` fails, `DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) were emitted.`

https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=armel&ver=5.1.1-4&stamp=1712238082&raw=0

On mips64el: `[doctest] sunpy.coordinates.frames.Helioprojective.assume_spherical_screen`: 
``` 
Differences (unified diff with -expected +actual):
    @@ -2,4 +2,4 @@
         [(   0., 0., 0.99660825), ( 319., 0., 0.99687244),
          ( 638., 0., 0.99778472), ( 957., 0., 1.00103285),
    -     (1276., 0., 1.00125872), (1595., 0., 1.00125872),
    -     (1914., 0., 1.00125872)]>
    +     (1276., 0.,        nan), (1595., 0.,        nan),
    +     (1914., 0.,        nan)]>
```
https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=mips64el&ver=5.1.1-4&stamp=1712238826&raw=0

Any guidance on how we shall fix this?

### To Reproduce

Here's a dockerfile, build it with `--platform=linux/arm/v5` or `--platform=linux/mips64le` 

``` Dockerfile
FROM docker.io/debian:sid-slim

WORKDIR /build

RUN apt-get update && apt-get install -y --no-install-recommends devscripts curl debian-keyring
RUN dget https://deb.debian.org/debian/pool/main/s/sunpy/sunpy_5.1.1-4.dsc
WORKDIR /build/sunpy-5.1.1
RUN apt-get -y build-dep .
RUN dpkg-buildpackage -uc -us -b
```

For reference, all the extra patches we apply to Sunpy 5.1.1 are at https://salsa.debian.org/debian-astro-team/sunpy/-/tree/master/debian/patches?ref_type=heads

### System Details

```
==============================
sunpy Installation Information
==============================

General
#######
OS: Debian GNU/Linux (trixie/sid, Linux 6.1.0-18-amd64)
Arch: 64bit, ()
sunpy: 5.1.1
Installation path: sunpy.egg-info

Required Dependencies
#####################
astropy: 6.0.1
numpy: 1.26.4
packaging: 24.0
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 3.1.0
asdf-astropy: Missing asdf-astropy>=0.1.1; extra == "asdf" or "docs" or "tests"
beautifulsoup4: 4.12.3
cdflib: Missing cdflib!=0.4.0,!=1.0.0,>=0.3.20; extra == "docs" or "tests" or "timeseries"
dask: 2023.12.1+dfsg
drms: 0.7.1
glymur: Missing glymur!=0.9.5,>=0.9.1; extra == "docs" or "jpeg2000" or "tests"
h5netcdf: 1.3.0
h5py: 3.10.0
lxml: 5.2.1
matplotlib: 3.6.3
mpl-animators: 1.1.1
pandas: 2.1.4+dfsg
python-dateutil: 2.9.0
reproject: 0.13.0
scikit-image: 0.22.0
scipy: 1.11.4
sqlalchemy: 1.4.50
tqdm: 0.0.0
zeep: 4.2.1
````

### Installation method

from source (.tar.gz)

**Comment by Cadair** [comment]
Thanks for the bug report (and testing sunpy on other platforms) we will try and take a look.

**Comment by ayshih** [comment]
> On mips64el: `[doctest] sunpy.coordinates.frames.Helioprojective.assume_spherical_screen`:
> 
> ```
> Differences (unified diff with -expected +actual):
>     @@ -2,4 +2,4 @@
>          [(   0., 0., 0.99660825), ( 319., 0., 0.99687244),
>           ( 638., 0., 0.99778472), ( 957., 0., 1.00103285),
>     -     (1276., 0., 1.00125872), (1595., 0., 1.00125872),
>     -     (1914., 0., 1.00125872)]>
>     +     (1276., 0.,        nan), (1595., 0.,        nan),
>     +     (1914., 0.,        nan)]>
> ```
> 
> https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=mips64el&ver=5.1.1-4&stamp=1712238826&raw=0

Apparently, on mips64el, `numpy.fmin()` does not behave as it should, namely ignoring NaNs (see the long discussion in https://github.com/numpy/numpy/issues/23158), and I presume that no fix was discovered for the NumPy build on debian (otherwise we wouldn't be having the problem here).  We could refactor code to avoid the problematic call in our code:

https://github.com/sunpy/sunpy/blob/386e5409c9b0b190e8b633c44d3fd9c75ee3913a/sunpy/coordinates/frames.py#L581

since in our specific case, the NaNs are from taking the square root of a negative number.

**Comment by nabobalis** [comment]
This looks to be a bug in Python, which was only fixed in https://github.com/python/cpython/pull/104202 which came out in 3.12.

**Comment by Cadair** [comment]
I have to say I don't think it would be worth us working around this for an architecture I very much doubt anyone is using SunPy on 😁

**Comment by ayshih** [comment]
> On armel (arm32v5): `test_map_arithmetic_operations_raise_exceptions[map-warn_context0]` fails, `DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) were emitted.`
> 
> https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=armel&ver=5.1.1-4&stamp=1712238082&raw=0

It looks like zero divided by zero on ARM (with software floating point?) does not raise a NumPy warning.  See https://github.com/scikit-image/scikit-image/issues/3335 for a similar-sounding issue.  We can easily change the warning catching to be a warning filtering (using `numpy.errstate()`) since the presence of a NumPy warning is not relevant to the unit test.

**Comment by ayshih** [comment]
Upon further poking, the fact that we are even dividing in that situation is a bug, so #7551 stops that from happening

**Comment by mr-c** [comment]
Thanks, @ayshih ! Oddly enough, the mips64el issue went away when I rebuilt with https://github.com/sunpy/sunpy/pull/7551 cherry-picked on top

https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=mips64el&ver=5.1.1-5&stamp=1712345380&raw=0

**Comment by ayshih** [comment]
Odd indeed!

**Comment by Cadair** [comment]
Thanks @mr-c
