### ISSUE TITLE
Build and test against numpy 2.0rc1

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#7555]
### Describe the feature

We need to bump our build deps and test against 2.0.0rc1 at runtime. https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395

We should do this before the next bugfix release.

**Comment by pllim** [comment]
FWIW, also failed here: https://github.com/astropy/astropy-integration-testing/actions/runs/8568043943/job/23485761643?pr=16

xref https://github.com/astropy/astropy-integration-testing/pull/16

**Comment by nabobalis** [comment]
PANDAS!!!!!
