### ISSUE TITLE
read_cdf/TimeSeries crashes if CDF variable doesn't have a 'FILLVAL' attribute

### ISSUE THREAD

**Issue by jgieseler** [sunpy/sunpy#7565]
### Describe the bug

Similar to https://github.com/sunpy/sunpy/issues/5907, I stumbled upon CDF files that aren't fully [complying to the CDF ISTP Metadata Guidelines](https://spdf.gsfc.nasa.gov/sp_use_of_cdf.html) by having a variable that doesn't provide a corresponding FILLVAL attribute. `read_cdf()` is expecting this attribute to exist, and otherwise crashes (and with it also `TimeSeries`):
https://github.com/sunpy/sunpy/blob/9f0a37dc0d0a543663e871a3256b147fc004db2e/sunpy/io/_cdf.py#L83-L87

But as has been mentioned in https://github.com/sunpy/sunpy/issues/5907#issuecomment-1054428488, it's not uncommon that a CDF file is not fully following the ISTP standard (these are by the way recent PSP data files, so I'll anyhow contact the instrument team). If the `FILLVAL` information isn't provided by the instrument team, one could just skip the replacement call. So I propose to change `if np.issubdtype(data.dtype, np.floating):` to something like `if np.issubdtype(data.dtype, np.floating) and 'FILLVAL' in attrs:`

### To Reproduce

Because the error message occurs in `read_cdf` when using `TimeSeries`, this is what I'm calling here directly:

``` python
import datetime as dt
from sunpy.io._cdf import read_cdf
from sunpy.net import Fido
from sunpy.net import attrs as a
from sunpy.timeseries import TimeSeries

dataset = 'PSP_SWP_SPI_SF00_L3_MOM'
trange = a.Time(dt.date(2023,3,14), dt.date(2023,3,15))
result = Fido.search(trange, a.cdaweb.Dataset(dataset))
downloaded_files = Fido.fetch(result)
# ts = TimeSeries(downloaded_files, concatenate=True)
data = read_cdf(downloaded_files.data[0])
```

### System Details

- sunpy version: 5.1.1 and 5.1.2

### Installation method

pip

**Comment by jgieseler** [comment]
I'm just noticing that the corresponding CDF variables have as the VAR_TYPE attribute 'ignore_data'. [According to the ISTP Guidelines this is a placeholder](https://spdf.gsfc.nasa.gov/istp_guide/vattributes.html#VAR_TYPE), but I'm wondering if the instrument team actually had the intention that this part should be skipped. :thinking:

**Comment by RehanChalana** [comment]
I would like to work on this issue!
any guidance on what to learn about CDF files and FILVAL attribute will be of great help and what do we want to do if if the CDF file does not provide a FILVAL attribute.

Thanks

**Comment by nabobalis** [comment]
> I would like to work on this issue! any guidance on what to learn about CDF files and FILVAL attribute will be of great help 

I am not sure you need to learn much about CDF files, we aren't going to do much that requires an understanding of the file format.

Information about the FILVAL is here: https://spdf.gsfc.nasa.gov/istp_guide/variables.html 

> and what do we want to do if if the CDF file does not provide a FILVAL attribute.

If it doesn't, we can't fill it in, we would just not crash on it being missing. 

About the placeholder data, we should look into what that data is and maybe we should skip it from being loaded but that would require some investigation.

**Comment by RehanChalana** [comment]
so for now i only need to make sure that the code does not crash if the attribute is missing?

Will it be okie

**Comment by nabobalis** [comment]
Yeah, that would be a good place to start.

**Comment by RehanChalana** [comment]
Hi,

I've fixed the crash using the following code:

` if np.issubdtype(data.dtype, np.floating) and attrs.get('FILLVAL'):`

However, I'm encountering a warning (as shown in the attached screenshot). I believe this warning might be related to files I'm not familiar with.
![image](https://github.com/sunpy/sunpy/assets/139042983/adcc1ba5-f511-4388-8c30-7b5a8de6bc9c)

Before I proceed with making a pull request, could you provide some guidance on this issue?

Thank you!

**Comment by nabobalis** [comment]
We should probably try to add support for that unit in the future
