### ISSUE TITLE
Things to fix when numpy 2.0 is out

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#7566]
In https://github.com/sunpy/sunpy/pull/7556 we skip several doc tests to handle the fact the output is different verus numpy 2.0 and numpy < 2.0

These need to be un skipped and for the oldest deps build, a conditional tweak to the doctest to either skip them on numpy <2.0

This also includes several tests that read CDF files that now fail under numpy 2.0. We need to wait for cdflib to support numpy and we can unskip those as well.

**Comment by Prtm2110** [comment]
I attempted to run the doctests with NumPy v2.1.0, but they are still failing. It appears that there's no feasible way to modify the code to conditionally skip the doctests based on the NumPy version. While using 
`if not np.__version__.startswith("2."):` could be an option, it leads to no output, which is then incorrectly compared against the expected output, resulting in test failures.

Another possibility is using a decorator, but as far as I know, decorators aren’t applicable to doctests.

Is there any other way to achieve this? I'm willing to work on it if there’s a potential solution.

**Comment by nabobalis** [comment]
What doctests are failing?

**Comment by Prtm2110** [comment]
In `sunpy/time/timeformats.py`
```
>>> from astropy.time import Time
>>> t = Time('1958-01-01T00:00:00', format='isot', scale='tai')
>>> t.tai_seconds  # doctest: +SKIP
0.0
>>> t2 = Time('2015-10-25T05:24:08', format='isot', scale='tai')
>>> t2.tai_seconds  # doctest: +SKIP
1824441848.0
>>> t3 = Time(t2.tai_seconds, format='tai_seconds')  # scale is automatically TAI
>>> t3.isot
```
`t.tai_seconds ` and `t2.tai_seconds` outputs `np.float64(1824441848.0)` and  `np.float64(1824441848.0)`

In `sunpy/docs/tutorial/units.rst`
```
>>> length.value  # doctest: +SKIP
10.0
>>> length.to_value() # doctest: +SKIP
10.0
>>> length.to_value(u.km)  # doctest: +SKIP
0.01
```
All the outputs are in float format but numpy2.0 is outputting them in `np.float64` format

**Comment by nabobalis** [comment]
The last one was changed in a new PR and I haven't checked the continuous integration but I wasn't aware that the time format was failing. 

I think as things stand now, I think this issue can be closed.
