### ISSUE TITLE
Make `get_dummy_map_from_header` useful outside of core

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#7608]
### Describe the bug

Our [`get_dummy_map_from_header`](https://github.com/sunpy/sunpy/blob/main/sunpy/data/test/__init__.py#L106) helper would be useful outside of core (I was trying to use it in sunkit-magex), but because of how it looks up the filename:

https://github.com/sunpy/sunpy/blob/5b27fef34b9f36256da4037ba27b0bece61e755a/sunpy/data/test/__init__.py#L51-L54

it doesn't work unless the file is in the sunpy repo.

**Comment by RehanChalana** [comment]
I'd like to work on this issue, but I don't have a detailed plan yet. Could someone provide some guidance on the best way to approach this? 

Thanks!

**Comment by nabobalis** [comment]
I think the goal would be add a new keyword that allows to override the `"package="sunpy.data.test",` to be set to another package name.

This would allow other packages to use this function without having to copy it.

**Comment by RehanChalana** [comment]
Great! i understood
Thank you so much

could you please assign me this issue ?

**Comment by nabobalis** [comment]
> Great! i understood Thank you so much
> 
> Here’s my proposed approach:
> 
> 1. Add a new keyword argument, `package`, to the `get_dummy_map_from_header` function with a default value of `"sunpy.data.test"`.
> 2. Modify the function to use this new `package` argument when calling `get_pkg_data_filename`.

Sounds good.
 
> could you please assign me this issue ?

We try to avoid assigning issues as a general rule.

**Comment by RehanChalana** [comment]
Understood, thanks for the information.

I'll start working on this issue.
