### ISSUE TITLE
Test failure with installed package on Debian

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#7650]
### Describe the bug

When I install the Debian package previously built, I see two new 
failures when I run the CI test:
```python
________________________ test_main_stdlib_module _____________________________________
    def test_main_stdlib_module():
        """
        This test makes sure that the module is really searched within the sunpy
        package.
        """
        with pytest.raises(ModuleNotFoundError):
>           sunpy.self_test(package='random')
/usr/lib/python3/dist-packages/sunpy/tests/tests/test_self_test.py:20: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3/dist-packages/sunpy/tests/self_test.py:52: in self_test
    printed = print_missing_dependencies_report(missing)
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
missing = {'database': defaultdict(<class 'list'>, {}), 'docs-gallery': defaultdict(<class 'list'>, {'astroquery': 'Missing astr...>, {}), 'jpeg2000': defaultdict(<class 'list'>, {'glymur': 'Missing glymur!=0.9.5,>=0.9.1; extra == "jpeg2000"'}), ...}
package = 'sunpy'
    def print_missing_dependencies_report(missing, package="sunpy"):
        printed = False
>       required_missing = missing.pop("required")
E       KeyError: 'required'
/usr/lib/python3/dist-packages/sunpy/tests/self_test.py:4: KeyError
---------------------------------------- Captured stdout call ----------------------------------------------------------------------
Starting sunpy self test...
Checking for packages needed to run sunpy:
```
(the same for **test_main_nonexisting_module**). This test did not fail during the build time test.
Full test log [here](https://salsa.debian.org/debian-astro-team/sunpy/-/jobs/5777242).
It could well be that I forgot to install something which is now required; however the failure doesn't give me a hint.

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

### System Details

* sunpy 5.1.3
* astropy 6.0.1
* Python 3.11

### Installation method

from source (.tar.gz)

**Comment by nabobalis** [comment]
I wonder what if its a difference in versions?

We use `importlib.metadata` and it returns an extra group called required which we remove.
On our CI that version is `importlib_metadata==7.1.0`, and in that CI log it is `python3-importlib-metadata all 4.12.0-1` 

It's safe to skip these or mark them xfail.

Thanks for the report!
We didn't consider older versions of importlib/packaging in our CI, maybe we should?

**Comment by olebole** [comment]
Thanks for the hint! I will just set them to xfail.
