### ISSUE TITLE
Test failure on mips64el

### ISSUE THREAD

**Issue by olebole** [sunpy/sunpy#7654]
### Describe the bug

When building the Debian package, the test during build time fails only on mips64el:
```
___________________________________________________ [doctest] sunpy.coordinates.frames.Helioprojective.assume_spherical_screen ____________________________________________________
740 
741         >>> with Helioprojective.assume_spherical_screen(h.observer):
742         ...     print(h.make_3d())
743         <Helioprojective Coordinate (obstime=2020-04-08T00:00:00.000, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate for 'earth'>): (Tx, Ty, distance) in (arcsec, arcsec, AU)
744             [(   0., 0., 1.00125872), ( 319., 0., 1.00125872),
745              ( 638., 0., 1.00125872), ( 957., 0., 1.00125872),
746              (1276., 0., 1.00125872), (1595., 0., 1.00125872),
747              (1914., 0., 1.00125872)]>
748 
749         >>> with Helioprojective.assume_spherical_screen(h.observer, only_off_disk=True):
Differences (unified diff with -expected +actual):
    @@ -2,4 +2,4 @@
         [(   0., 0., 0.99660825), ( 319., 0., 0.99687244),
          ( 638., 0., 0.99778472), ( 957., 0., 1.00103285),
    -     (1276., 0., 1.00125872), (1595., 0., 1.00125872),
    -     (1914., 0., 1.00125872)]>
    +     (1276., 0.,        nan), (1595., 0.,        nan),
    +     (1914., 0.,        nan)]>

/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_sunpy/build/sunpy/coordinates/frames.py:749: DocTestFailure
```
I am not sure why only there -- this is 64 bit, little endian. On the other platforms (arm64, x86_64, riscv64, ppc64el) it passes. I could just disable this test;  however the only thing I could imagine is a slightly different FP calculation, so this failure my indicate a not-robust calculation somewhere.

### To Reproduce

Full build log available at https://buildd.debian.org/status/fetch.php?pkg=sunpy&arch=mips64el&ver=5.1.3-2&stamp=1717087692&raw=0

### System Details

sunpy 5.1.3, astropy 6.0.1, python 3.11 and 3.12, numpy 1.26.4

### Installation method

from source (.tar.gz)

**Comment by ayshih** [comment]
See https://github.com/sunpy/sunpy/issues/7550#issuecomment-2037843084

**Comment by olebole** [comment]
OK, so I will just xfail the test. Thank you!
