### ISSUE TITLE
Add gallery example showing how to track and co-align an active region

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#7676]
### Provide a general description of the issue or problem.

A common task when dealing with AIA data (or any imaging data in time) is to track a particular region as a function of time and then create a cutout around that region and align it at each time step to get an aligned datacube. There are many ways of performing that alignment, but one  of the most common is to remove the effect of solar rotation.

These steps can easily be done using `reproject_to` and `propagate_with_solar_surface` as demonstrated in [this slide deck from my talk at SciPy in 2023](https://wtbarnes.github.io/scipy-2023-talk/#/inspecting-data-with-sunpy). We should have a gallery example that shows how to do this on a small set of AIA images spaced far enough in time that the effect of solar rotation is obvious (eg spaced out over a day at 6 h intervals). Essentially, this just boils down to choosing a WCS that represents the cutout you're interested in and reprojecting all slices to that cutout,

```python
with propagate_with_solar_surface():
  m_seq_aligned = sunpy.map.Map([m.reproject_to(m_cutout.wcs) for m in m_seq], sequence=True)
```

**Comment by Prtm2110** [comment]
I think this code should provide those images but it is not, or do we have to go extract images some other way?

```
import sunpy.map
from sunpy.net import Fido, attrs as a
from sunpy.coordinates import frames

from astropy.coordinates import SkyCoord
import astropy.units as u
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

timerange = a.Time('2023-07-01T00:00:00', '2023-07-01T18:00:00')
instrument = a.Instrument('AIA')
wavelength = a.Wavelength(171 * u.angstrom)
result = Fido.search(timerange & instrument & wavelength)

downloaded_files = Fido.fetch(result)

maps = sunpy.map.Map(downloaded_files, sequence=True)

cutout_center = SkyCoord(-500 * u.arcsec, 200 * u.arcsec, frame=frames.Helioprojective, obstime=maps[0].date)
width = 300 * u.arcsec
height = 300 * u.arcsec

cutout_frame = sunpy.map.make_fitswcs_header(
    (height, width),
    cutout_center,
    maps[0].coordinate_frame)

m_cutout = sunpy.map.Map(maps[0].data, cutout_frame)

with propagate_with_solar_surface():
    aligned_maps = sunpy.map.Map([m.reproject_to(m_cutout.wcs) for m in maps], sequence=True)

for i, amap in enumerate(aligned_maps):
    fig = plt.figure()
    ax = fig.add_subplot(projection=amap)
    amap.plot(axes=ax, annotate=False)
    plt.title(f'Time: {amap.date}')
    plt.axis('off')
    jpeg_filename = f'aligned_image_{i}.jpg'
    plt.savefig(jpeg_filename, format='jpeg', bbox_inches='tight', pad_inches=0)
    plt.close()


```

**Comment by nabobalis** [comment]
Hi @Prtm2110, what does it provide?

**Comment by Prtm2110** [comment]
Particular region in images as a function of time and then create a cutout around that region and align it at each time step to get an aligned data cubes 
(as mentioned in the issue)

**Comment by nabobalis** [comment]
You said, "I think this code should provide those images but it is not", so what is the output of the code?

**Comment by Prtm2110** [comment]
Actually it is now downloading entire dataset (which is pretty huge and unnecessary) 
I want to help on this issue how should I proceed?

**Comment by nabobalis** [comment]
Next stage is to create a gallery example and PR it to sunpy.
