### ISSUE TITLE
Add support for ASDF in Map Factory and .save method

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#7689]
### Describe the feature

@wtbarnes [asks](https://matrix.to/#/!MeRdFpEonLoCwhoHeT:matrix.org/$171907835316962pljCz:matrix.org?via=openastronomy.org&via=matrix.org&via=cadair.com):

> Is there a reason we couldn’t add asdf as a supported format in the map factory?

If we add support to map factory the questions that needs answering are how far down the asdf tree do we look for map objects to return? (Top level only? all of them?) and what do we do if we open a file with more than just the map object in? (Ignore it? Throw a warning?)

On the .save method side it would be easy enough to "if filename ends with .asdf make a tree and save it" although this would arguably move the asdf dependency into the map extra.

**Comment by Sauravroy34** [comment]
hey, can I be assigned for this feature?

1) for tree we can do a recursive search for entire ASDF tree to find map objects and maybe we have to make function to read asdf file

**Comment by Cadair** [comment]
hey @Sauravroy34 thanks for being interested in working on this. We generally don't assign issues to people, the best way to show people you are working on something is to open a draft PR as soon as you have started.

I think as a first pass we should tackle either save or load, save is probably easier, so if you aren't familiar with sunpy's code and contribution process I would start there.

**Comment by Sauravroy34** [comment]
Sure, will be sending a pr soon

**Comment by Sauravroy34** [comment]
Hey 👋, I have added a method in genric map save_asdf to save asdf specifically

**Comment by Sauravroy34** [comment]
hey, should we add a separate function in Mapbase.py for dealing with asdf files?

**Comment by Sauravroy34** [comment]
@Cadair 
Hi there , check this out #7712 
so I have  added a method in sunpy/io to save an map into asdf file using .save method can you check if that correct way to do it ?

Now,how shall I tackle the loading asdf file into map ?
