### ISSUE TITLE
Solar orientation angle accuracy improvement and support for non-disk-center target coordinates. 

### ISSUE THREAD

**Issue by tschad** [sunpy/sunpy#7693]
### Describe the bug

sunpy.coordinatess.sun.orientation calculates (according to its doc-string) "the orientation angle for the Sun from a specified Earth location and time. The orientation angle is the angle between local zenith and solar north, measured eastward from local zenith."  

Currently, the calculation applies only to a targeted coordinated centered on solar disk center; although this angle does change as a function of targeted locations away from disk center.   Therefore, an associated feature request would be to extend this calculation to non-disk-center targets. 

That said, there is likely an error in the currently implementation (even when limited to disk center).  The code calls the _sun_north_angle_to_z function that projects a few vectors into the sky and measures the angles between them.  However, the vector used for the zenith direction is always one directed from the <cartesian representation of the disk center sky coordinates> to the <zenith cartesian representation coordinates at (0,0,1)>.  Because the zenith is always defined as (0,0,1),  there is an issue when projecting this vector onto the spherical projection of the sky local to the target instead.   An improved approach would be to define a vector to the zenith direction based on a small angle difference from the target coordinates in the +Altitude direction of an AltAz frame.  The differences between these calculations can be as large as a few degrees.  

So, this ticket requests first an improved algorithm be considered for the calculation of this angle, and perhaps then an extension to non-disk center pointing.  

Note also that the docstring could be more specific in the definition of this angle and its reference direction.

## HERE IS A CODE SNIPPET TO SHOW THE ERROR AND A CANDIDATE IMPLEMENTATION OF A SOLUTION 
```

import os
import glob
import numpy as np

import matplotlib.dates as mdates
import astropy.units as u
from astropy.io import fits 
from astropy.time import Time
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord, EarthLocation, AltAz,CartesianRepresentation
from sunpy.coordinates import sun, HeliocentricInertial, Helioprojective,GeocentricEarthEquatorial
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import LogNorm
plt.rcParams.update({'figure.max_open_warning': 0})
plt.rcParams["image.origin"] = 'lower'
plt.rcParams["image.cmap"] = 'gray'
plt.rcParams["image.interpolation"] = 'nearest'

dkist = EarthLocation(lat=20.7067*u.deg, lon=203.7436*u.deg, height=3067*u.m)
obstimes = Time('2024-06-27 17:00') + np.arange(0., 12,0.1)*u.hour
sunpy_orientation = sun.orientation(location = dkist,time = obstimes).deg

sunpy_orientation[0]

results = np.zeros(len(obstimes))
for nn,t0 in enumerate(obstimes):
    frame_altaz = AltAz(obstime=t0, location=dkist)
    x,y = 0,0
    target_coords = SkyCoord(x*u.arcsec,y*u.arcsec,obstime = t0,observer = 'earth',frame = "helioprojective").transform_to(frame_altaz)
    ## coordinates of a point 1 arcsec to the solar north or boresight used to calculate the solar 
    ## orientation angle at this alt az value (note this is not the same as at disk center) 
    ptCoord = SkyCoord(x*u.arcsec,(y+1)*u.arcsec,obstime=t0, observer='earth', frame="helioprojective")
    
    ## transform to altaz frame (handling case if the point is offlimb)
    with Helioprojective.assume_spherical_screen(target_coords.observer):
        target_altaz = target_coords.transform_to(frame_altaz) 
        ptCoord_altaz = ptCoord.transform_to(frame_altaz) 
        toZenith_altaz = SkyCoord(target_altaz.az,target_altaz.alt + 1*u.arcsec,target_altaz.distance,frame = frame_altaz)
    
    # Use cross products to obtain the sky projections of the two vectors (rotated by 90 deg)
    sky_normal = target_altaz.data.to_cartesian()
    pt_normal  = ptCoord_altaz.data.to_cartesian()
    zen_normal = toZenith_altaz.data.to_cartesian()
    
    ## project zenith direction and direction to observed point into sky
    z_in_sky = zen_normal.cross(sky_normal)
    pt_in_sky = pt_normal.cross(sky_normal)
    
    # Normalize directional vectors
    sky_normal /= sky_normal.norm()
    pt_normal  /= pt_normal.norm()
    pt_in_sky  /= pt_in_sky.norm()
    z_in_sky   /= z_in_sky.norm()
    
    # Calculate the signed angle between the two projected vectors
    ## angle between to zenith and to point from center 
    cos_theta = pt_in_sky.dot(z_in_sky)
    sin_theta = pt_in_sky.cross(z_in_sky).dot(sky_normal)
    solar_orientation = np.arctan2(sin_theta, cos_theta)
    results[nn] = solar_orientation.to(u.deg).value

from mpl_toolkits.axes_grid1.inset_locator import zoomed_inset_axes,mark_inset

import pytz
HST = pytz.timezone('US/Hawaii')
plt.rcParams["timezone"] = pytz.timezone('US/Hawaii').zone

fig,ax = plt.subplots(2,1,figsize = (5,5),sharex=True)
ax[0].plot(obstimes.to_datetime(timezone=HST),sunpy_orientation,lw = 0.4,label = 'Sunpy Orientation Angle')
ax[0].plot(obstimes.to_datetime(timezone=HST),results,'k',lw = 0.4,label = 'Proposed Improvement')
myFmt = mdates.DateFormatter('%H:%M')
ax[0].xaxis.set_major_formatter(myFmt)
ax[0].set_ylim(-180,180)

ax[1].plot(obstimes.to_datetime(timezone=HST),sunpy_orientation- results,'k',label = '(Sunpy - Improved)')
ax[1].set_xlabel("Time [HST] (2024-06-27)")
ax[0].set_ylabel("Degrees")
ax[1].set_ylabel("Degrees")

axins = zoomed_inset_axes(ax[0],3.5,loc='lower right')
axins.plot(obstimes.to_datetime(timezone=HST),sunpy_orientation,lw = 0.4,label = 'Sunpy Orientation Angle')
axins.plot(obstimes.to_datetime(timezone=HST),results,'k',lw = 0.4,label = 'Proposed Improvement')
axins.set_xlim(obstimes.to_datetime(timezone=HST)[110],obstimes.to_datetime(timezone=HST)[119])
axins.set_ylim(60,85)
axins.xaxis.set_visible(False)
mark_inset(ax[0],axins,loc1=1,loc2=2)

ax[0].legend(loc = 'upper left')
ax[1].legend(loc = 'upper left')
fig.tight_layout()
fig.savefig('sunpy_orient_vs_newCalc.png',dpi = 300)


```

**Comment by Cadair** [comment]
Thanks for the report @tschad. I will let @ayshih comment on the accuracy, but extending the function to different targets seems very reasonable to me.

**Comment by ayshih** [comment]
I'll acknowledge that I've had unrelated reports that there may be an inaccuracy with the orientation calculation, but the evidence I've received so far has been merely circumstantial.  I enthusiastically encourage others to be looking at the code critically!

That said, the alternative approach you suggest is mathematically equivalent to what we currently have, yet intensely more computational and roundabout.  The reason you appear to find a discrepancy is due to a bug in your example, where you define both the disk center (`target_coords`) and the offset point (`ptCoord`) with an observer at Earth center (`observer='earth'`) rather than where the observer actually is (DKIST).  That difference in observer location entirely explains the difference in Sun orientation.

The output from your example (showing a seeming discrepancy of +/- 2 deg):
![bugged example](https://github.com/sunpy/sunpy/assets/991759/2fc6de93-0c71-4d96-b643-058805488830)

If you set `observer=SkyCoord(0*u.deg, 0*u.deg, 0*u.m, frame=frame_altaz)` (one of several ways to set the observer to DKIST), the output is instead:
![fixed example](https://github.com/sunpy/sunpy/assets/991759/ff98177b-9d27-43c6-a171-d32d686b3779)

You can see that the discrepancy is now only ~45 milliarcseconds, with a variation over the day that is sub-milliarcsecond.  The remaining discrepancy might simply be numerical noise.

**Comment by ayshih** [comment]
(I suggest creating a separate feature-request issue for the non-disk-center-target interest)

**Comment by tschad** [comment]
Indeed!  Thank you for identifying my bug.  I see now that the existing
calculation is equivalent with mine for the disk center.   I will add a
feature request shortly for the non-disk-center targets.

Thanks for your time.  Cheers!
