### ISSUE TITLE
Add the PR acceptance process to dev docs

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#770]
On #sunpy, we (@Cadair and me, @ehsteve also agreed that it's a good idea) had the idea of introducing a formal PR acceptance process. The part "Contributing to the main repo" from the dev guide needs to be adjusted so that it contains a clear list of requirements that have to be met before a pull requests is ready to be merged.

Proposed list, open for discussion:
- if the API has changed …
  - update docstrings
  - update CHANGELOG.md
- add tests (never decrease code coverage through a new PR)
- travis may not complain about anything

Anything else?

**Comment by nabobalis** [comment]
Im pretty sure we have this now.
