### ISSUE TITLE
Fido.fetch() behaving differently on Windows and MacOS?

### ISSUE THREAD

**Issue by mathewjowens** [sunpy/sunpy#7751]
### Describe the bug

When grabbing multiple files using Fido.fetch(), there appears to be some connection problems on MacOS that aren't present on Windows machine.

For example, grabbing 8 years of 1-hour OMNI data using the code below. This finds all files on two different Windows machines every time the code is run. On two different macs -- connected to the same network and using the same conda environment -- between 10 and all 106 files will be skipped. The exact number is different each time it is run. The error appears to be associated with SSL (see below).

Typical downloaded_files.result item:
https://cdaweb.gsfc.nasa.gov/sp_phys/data/omni/coho1hr_magplasma/2019/omni_coho1hr_merged_mag_plasma_20190701_v01.cdf,
Cannot connect to host cdaweb.gsfc.nasa.gov:443 ssl:default [Connect call failed ('169.154.154.65', 443)]]

It doesn't seem to obviously be a maximum rate issue - if the 8 year interval is split into annual intervals, with a delay between each year, the problem persists. 

### To Reproduce
```python
import datetime
from sunpy.net import Fido
from sunpy.net import attrs

startdate = datetime.datetime(2011, 1, 1)
stopdate = datetime.datetime(2019, 7, 1)

# Download the 1hr OMNI data from CDAweb
trange = attrs.Time(startdate, stopdate)
dataset = attrs.cdaweb.Dataset('OMNI_COHO1HR_MERGED_MAG_PLASMA')
result = Fido.search(trange, dataset)
downloaded_files = Fido.fetch(result)

print(downloaded_files.errors)
```

### System Details
```
==============================
sunpy Installation Information
==============================

General
#######
OS: Mac OS 14.5
Arch: 64bit, (i386)
sunpy: 5.1.1
Installation path: /opt/miniconda3/envs/general/lib/python3.9/site-packages/sunpy-5.1.1.dist-info

Required Dependencies
#####################
astropy: 6.0.0
numpy: 1.26.4
packaging: 23.2
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 3.1.0
asdf-astropy: 0.5.0
beautifulsoup4: 4.12.3
cdflib: 0.0.0
dask: 2024.2.1
drms: 0.6.4
glymur: 0.12.9.post1
h5netcdf: 1.3.0
h5py: 3.10.0
lxml: 5.1.0
matplotlib: 3.8.3
mpl-animators: 1.1.1
pandas: 2.2.1
python-dateutil: 2.9.0
reproject: 0.13.0
scikit-image: 0.22.0
scipy: 1.12.0
sqlalchemy: 2.0.28
tqdm: 4.66.2
zeep: 4.2.1
```
### Installation method

conda

**Comment by Cadair** [comment]
Hi @mathewjowens thanks for your bug report. I suspect this will be a little hard to run down, but I will see if I can get some of our team to test things out.

From the error you posted though, it looks like it's failing on a system-level rather than in sunpy's code itself, i.e. the connection failed when we tried to access the server over HTTPS.

**Comment by mathewjowens** [comment]
Thanks. And yeah, I agree, it does seem likely that this is not fundamentally a sunpy issue. I figured it was worth posting though, as much to see if others had encountered it.

**Comment by samaloney** [comment]
Yea I just ran the code on a Mac and it downloaded all 103 files the first time but running the code a 2nd time **withtout** deleting the files did raise error

```
downloaded_files.errors[0]
<parfive.results.Error object at 0x10559c400>
https://cdaweb.gsfc.nasa.gov/sp_phys/data/omni/coho1hr_magplasma/2015/omni_coho1hr_merged_mag_plasma_20150201_v01.cdf,
Cannot connect to host cdaweb.gsfc.nasa.gov:443 ssl:default [Connect call failed ('169.154.154.65', 443)], <parfive.results.Error object at 0x10559dcb0>
```

Looking at the error might be rate limit/security on the server side?
```
downloaded_files.errors[0].exception
aiohttp.client_exceptions.ClientConnectorError(ConnectionKey(host='cdaweb.gsfc.nasa.gov', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=35949060025301139),
                                               ConnectionRefusedError(61,
                                                                      "Connect call failed ('169.154.154.65', 443)"))
```

**Comment by mathewjowens** [comment]
Thanks all. Short of looping through each item returned by fido.search() and putting in some kind of time.sleep() command, is there a simple way to limit the rate? I tried limiting the max connections to 1, but that had no effect.

But this probably needs closing as it's not a sunpy issue, per se. Apologies on that front.

**Comment by Cadair** [comment]
It's frustrating because I think we can handle a proper HTTP 429 backoff request, but this appears to be at a firewall level server side (if >n connections over x time then block).

No worries on opening an issue about it, it's always good to check it's not something we are doing to make the server unhappy or something we can adjust.

**Comment by mathewjowens** [comment]
Righty-o! Thanks again. I'll employ some work-arounds.
