### ISSUE TITLE
Have AIA and HMI maps use T_OBS (or T_REC?) for `reference_date`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#7757]
Apparently T_OBS is the reference observation time for AIA and HMI metadata, at least for Level-1 data products.  (DATE-OBS is derived from T_OBS by subtracting half the exposure time, so would not be a reference time.)  That means that we should use T_OBS for constructing the coordinate frame and observer location.  With #7682, we can now simply override the `reference_date` property so that T_OBS is used.

For derived data products (e.g., HARP images), T_REC might be the correct keyword to use rather than T_OBS.

**Comment by nabobalis** [comment]
> For derived data products (e.g., HARP images), T_REC might be the correct keyword to use rather than T_OBS.

I think we would need to create a Map source for this?

**Comment by wtbarnes** [comment]
> > For derived data products (e.g., HARP images), T_REC might be the correct keyword to use rather than T_OBS.
> 
> I think we would need to create a Map source for this?

Well HARPs are always HMI maps right so we could just have a check in the metadata that says `if HARP then date_key="T_REC"` or something like that. Currently, one can load SHARPs data into a `Map` using just the HMI map source.

**Comment by nabobalis** [comment]
I dont think we have a test header, we should add one and check.

**Comment by wtbarnes** [comment]
Sure, I guess we should test against SHARP and HARP data in addition to the usual HMI data.

**Comment by nabobalis** [comment]
I will add them to the open PR.
