### ISSUE TITLE
Template workflow automatically add a back port label

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#7806]
### Provide a general description of the issue or problem.

We have just noticed that we are not backporting the template changes and missed some crucial updates as a result.

One way to fix this is to update the cruft workflow to auto label the PR with the backport label.

**Comment by advait-zx** [comment]
can i work on this or it requires any pre-requisite to contribute?

**Comment by Cadair** [comment]
Hi @advait-zx you are welcome to take this on.

You need to edit this part of this file: https://github.com/sunpy/sunpy/blob/main/.github/workflows/sub_package_update.yml#L69 to add the `backport 6.0` label following the docs here: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-inputs
