### ISSUE TITLE
Database should support relative file paths

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#783]
To make the database portable and support network hosted SQL databases, there should be a mechanism for storing path names relative to a base path.

i.e.

``` Python
db.fetch(path='{file}') #relative path
db.fetch(path='/my/dir/{file}.fits') #absolute path
```

The base path could be optionally stored in the `sunpyrc` config and overridden when a database is created:

``` Python
db = Database('sqlite:///', basepath='/my_network/share')
```

**Comment by wtbarnes** [comment]
Given our plans to deprecate the `database` subpackage as it currently stands, I'm going to close this.
