### ISSUE TITLE
`Fido.search` output for many results needs more detail

### ISSUE THREAD

**Issue by SolarDrew** [sunpy/sunpy#7869]
### Provide a general description of the issue or problem.

Assuming this is an issue in Fido rather than in dkist but happy to close if I'm mistaken. Technically a bug I suppose but didn't seem like it needed a full bug report.

Output of a Fido search with many results gives, eg:

```
Showing 300 of 1205 available results. Use `a.dkist.Page(2)` to show the second page of results. 
 ```
 
It's not clear (to me) _how_ to use `a.dkist.Page(2)`, I think this could do with being expanded a bit.

**Comment by Cadair** [comment]
This is a dkist issue.
