### ISSUE TITLE
astropy v7.0: This package has doctest failure in sunpy.net.cdaweb.cdaweb.CDAWEBClient

### ISSUE THREAD

**Issue by pllim** [sunpy/sunpy#7874]
### Provide a general description of the issue or problem.

According to [astropy-integration-testing run](https://github.com/astropy/astropy-integration-testing/actions/runs/11785052451/job/32825493170), there is failure with the dev version but not stable, so might be something you added after release or a regression. This package needs a fix and possibly a new release to be compatible with `astropy` v7.0. FYI.

**Comment by nabobalis** [comment]
Thanks for the report, I will get this fixed ASAP.

**Comment by pllim** [comment]
Thanks!
