### ISSUE TITLE
Issue with parse time regex dropping 0's on minutes/seconds

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#7897]
### Describe the bug

```
parse_time("202201021230")
 <Time object: scale='utc' format='isot' value=2022-01-02T12:03:00.000>

```

however, 
```
parse_time("20220102123000")
 <Time object: scale='utc' format='isot' value=2022-01-02T12:30:00.000>
```

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by Cadair** [comment]
We don't actually have a `YYYYMMDDHHMM` time format supported in [the list](https://github.com/sunpy/sunpy/blob/main/sunpy/time/time.py#L37-L69), but what must be happening here is that it gets caught in the `YYYYMMDDHHMMSS` format and mangled:

https://github.com/sunpy/sunpy/blob/b6b67b23f848119a1fd28d73e02810a98239583c/sunpy/time/time.py#L63

**Comment by nabobalis** [comment]
> @Cadair  had you worked on it?

Are you asking if he is currently working on fixing this bug?

**Comment by PredictiveManish** [comment]
> > @Cadair  had you worked on it?
> 
> Are you asking if he is currently working on fixing this bug?

yes

**Comment by PredictiveManish** [comment]
Finding a little bit difficult in testing. 
Changed the formatting issue, as it was made a choice of 1,2 for many ones. 

![Screenshot 2024-12-05 190552](https://github.com/user-attachments/assets/96b514e2-3d49-4153-ab3d-210a5aa83408)
![Screenshot 2024-12-05 190521](https://github.com/user-attachments/assets/ff9ef8a3-0f0a-484f-800e-9f5573532fad)
![Screenshot 2024-12-05 190440](https://github.com/user-attachments/assets/16b4b31d-3355-4607-947b-a6cef2237e19)

**Comment by nabobalis** [comment]
> Finding a little bit difficulty in testing.

What's the problem?

**Comment by nabobalis** [comment]
You would create a new unit test that tests the new behaviour and run it via pytest.
There is some documentaion https://docs.sunpy.org/en/latest/dev_guide/contents/tests.html

**Comment by PredictiveManish** [comment]
> You would create a new unit test that tests the new behaviour and run it via pytest. There is some documentaion https://docs.sunpy.org/en/latest/dev_guide/contents/tests.html

Thanks

**Comment by iakkhushwaha** [comment]
## The same bug also arises when


```python
parse_time('20070504T2108')
	<Time object: scale='utc' format='isot' value=2007-05-04T21:00:08.000>
```

```python
parse_time('20070504T210800')
	<Time object: scale='utc' format='isot' value=2007-05-04T21:08:00.000>
```
