### ISSUE TITLE
direct dimensionality conversion

### ISSUE THREAD

**Issue by markandey1414** [sunpy/sunpy#7927]
### Describe the feature

I checked on the [arithmetic with units](https://docs.sunpy.org/en/stable/tutorial/units.html#arithmetic-with-units) operation. It turns out that there can't be an explicit conversion to a `int` from a default `floating point` when operating on values.
Here's a test case:
```
distance_start = 10 * u.mm
distance_end = 23 * u.km
displacement = distance_end - distance_start
displacement

time = 15 * u.minute
speed = displacement / time               
int(displacement / time)
speed
```

On testing the code, it returns the value `1.5333327 km/min`. This is a float value. I want it to covert it to an integer. It can't be done presently.
When I type, say this:
```
import math
print(math.floor(speed))
```

Following error finds the way:
```
UnitConversionError                       Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/astropy/units/quantity.py](https://localhost:8080/#) in to_value(self, unit, equivalencies)
    986             try:
--> 987                 scale = self.unit._to(unit)
    988             except Exception:

9 frames
[/usr/local/lib/python3.10/dist-packages/astropy/units/core.py](https://localhost:8080/#) in _to(self, other)
   1191 
-> 1192         raise UnitConversionError(f"'{self!r}' is not a scaled version of '{other!r}'")
   1193 

UnitConversionError: 'Unit("km / min")' is not a scaled version of 'Unit(dimensionless)'
```

Or if I try to explicitly convert it, say through this:
`speed = int(displacement / time)`
or 
`speed = displacement // time`

It returns:
`UnitDimensionError`

It would be really helpful for a new feature to be added here

### Proposed solution

Now I understand Dimensionality is an important feature aspect here, especially when errors can be made when converting the units.
One way is by first calculating the scalars and then adding the dimensions to the units. Say in the above example, first I calculate the scalar values of `displacement/time`, then concatenate their dimensions to the value.
Either way this would be really helpful in lossy and long calculations when the dimensions are not being concerned with too strictly.

**Comment by ayshih** [comment]
I think your issue is that you used `math` instead of `numpy`.  Generally you should not ever use `math`.  Try this instead:
```python
>>> import numpy as np
>>> np.round(speed)
<Quantity 2. km / min>
```
