### ISSUE TITLE
Database has no Attribute Sample

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#796]
The VSO, for some instruments has an attribute `Sample` i.e. `vso.attrs.Sample(90)` which picks out data every 90 seconds. If you try and fetch a database query using this attr it explodes!

``` Python
InvalidRequestError: Entity '<class 'sunpy.database.tables.DatabaseEntry'>' has no property 'sample'
```

The database should be able to accept queries on it's contents and to the VSO (the database can call the vso client).

You can generate the error with this:

``` python
import sunpy.database
from sunpy.net import vso
import astropy.units as u

db = sunpy.database.Database()

db.query(vso.attrs.Time('2011/9/12T20:30:00', '2011/9/12T21:00:00'),
         vso.attrs.Instrument('AIA'), vso.attrs.Sample(30*u.second ))
```

It looks like you want to add a class in attrs.py and then write a sqlalchemy query around here: https://github.com/sunpy/sunpy/blob/master/sunpy%2Fdatabase%2Fattrs.py#L162

**Comment by imaculate** [comment]
@Cadair , has this been done? I would like to work on it.

**Comment by Cadair** [comment]
@imaculate I don't think so, feel free to have a go. Let me know if you need any advice. :)

**Comment by imaculate** [comment]
@Cadair , Thank you!

**Comment by imaculate** [comment]
Hi @Cadair , I took a while to setup my environment but its working now. I have noticed that whenever I include the Sample parameter no results are found, but on removing it results show up. Not sure if its something I'm doing wrong.
Here is my query:
qr = client.query(vso.attrs.Time('2011/9/12T20:30:00', '2011/9/12T21:00:00'), vso.attrs.Instrument('AIA'), vso.attrs.Sample(30*u.second ))
Also, I want to clarify: Do you a database.fetch to have a 'sample' parameter or to be able to create database  entries from queries that were made with vso.attrs.Sample parameter?

Thank you!

**Comment by Cadair** [comment]
@imaculate it is the database that needs improving, you can generate the error with this:

```python
import sunpy.database
from sunpy.net import vso
import astropy.units as u

db = sunpy.database.Database()

db.query(vso.attrs.Time('2011/9/12T20:30:00', '2011/9/12T21:00:00'),
         vso.attrs.Instrument('AIA'), vso.attrs.Sample(30*u.second ))
```

The database should be able to accept queries on it's contents and to the VSO (the database can call the vso client). Does that make any sense? Let me know if you need some more pointers.

**Comment by imaculate** [comment]
Hi @Cadair , what do you suggest is the best way to implement this?

**Comment by Cadair** [comment]
I am not really sure what is the best way to go in any great detail. @derdon Was the guy who implemented the database module. It looks like you want to add a class in `attrs.py` and then write a sqlalchemy query around here: https://github.com/sunpy/sunpy/blob/master/sunpy%2Fdatabase%2Fattrs.py#L162

**Comment by jiaqing23** [comment]
Hi, can I work on this issue?

**Comment by nabobalis** [comment]
Sure.

**Comment by jiaqing23** [comment]
When I run the code provided:
```
import sunpy.database
from sunpy.net import vso
import astropy.units as u

db = sunpy.database.Database()

db.query(vso.attrs.Time('2011/9/12T20:30:00', '2011/9/12T21:00:00'),
         vso.attrs.Instrument('AIA'), vso.attrs.Sample(30*u.second ))
```
I get this error: `AttributeError: 'Database' object has no attribute 'query'` . Was the query method been removed?

**Comment by nabobalis** [comment]
Good question, I don't think we have made any changes to the database module that I can recall in some time. 
Considering we plan to replace database with a new implementation, maybe it's best to hold off on this issue for now.
