### ISSUE TITLE
HELIO HEC breaks Python 2.7+ functionality

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#823]
`sunpy/net/helio/parser.py` uses `.getiterator()` which is a deprecated method on the boject returned from xml parsing. This is to maintain support for 2.6 + 2.6 but will not work for 3.x.

**Comment by Cadair** [comment]
one presumes this is also closed by #1728.

**Comment by Cadair** [comment]
apparently not.

**Comment by Cadair** [comment]
ping @dpshelio @bsipocz

**Comment by Cadair** [comment]
There must not be tests for this?!

**Comment by bsipocz** [comment]
Hmm, this prompts the issue that the celebration was premature. 
Checking the test coverage is not trivial as the coveralls upload is still broken (I wonder whether using the setup from the astropy package template would work out of the box?, most of the stuff is already here).

And this brings me to the second issue, that I was way too much focused on getting the tests run, so now doing a 2to3 and realize that there are still a few lines that needs some updates. 
PR for this will come soon.

**Comment by nabobalis** [comment]
Closed by #2128
