### ISSUE TITLE
docs: installation guide does not mention requirement of Python C headers

### ISSUE THREAD

**Issue by derdon** [sunpy/sunpy#866]
To be able to install SunPy together with the sunpy.image.Crotate extension, it is required to have a package such as python-dev installed (or similar name, depending on the linux distro). I think when one installs Python for Windows, the user has to select the option that it must be installed with the C headers (I'm not a Windows user, correct me if I'm wrong). I don't know about mac users, how do they install the Python C headers?

Anyway, this kind of information is missing in the docs. It might be obvious and trivial for non-beginners of Python, but for novices it's helpful to know what to do if they see some error message like "fatal error: Python.h: No such file or directory".

**Comment by thelazy** [comment]
@Cadair Please, guide me on this.

**Comment by Cadair** [comment]
@thelazy The fact you often need to install the C headers (i.e. python.h) under linux needs documenting. When you were doing your install you had to install python-dev. The exact name of the package varies from distro to distro.

**Comment by dpshelio** [comment]
Is this not already said in [here](http://sunpy.readthedocs.org/en/latest/guide/installation/linux.html)... do we want to put this more detailed?

**Comment by derdon** [comment]
@dpshelio Indeed, looks fixed to me now :)

**Comment by prateekiiest** [comment]
@Cadair , has this issue been previously referred to??
