### ISSUE TITLE
Create an observer object

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#868]
Spatial data (e.g. maps, hek events) can be rendered from different perspectives (i.e. different views) depending on the observer's perspective. We should create an observer object which defines the position of the observer. It should be a property of a map (read in from the fits file). If it is edited then the data would be "rendered" with the new view. This would mean that we need to now think of the original data and the new rendered data.

This is a placeholder for a future Sunpy Proposal for Enhancement.

**Comment by astrograzl** [comment]
If it is related to observatory position on Earth, there is [EarthLocation](http://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html#astropy.coordinates.EarthLocation) object in [astropy.coordinates](http://docs.astropy.org/en/stable/coordinates/index.html) submodule.

**Comment by Cadair** [comment]
@astrograzl Thanks for the pointer. We have a more complex requirement in that we are describing satellite location in the solar system. I have been meaning to look at the `EarthLocation` class for inspiration though.

**Comment by Cadair** [comment]
This is being closed by #1975 in that our observer location is being represented by a `HeliographicStonyhurstFrame`.
