### ISSUE TITLE
EVELightCurve dynamic values display

### ISSUE THREAD

**Issue by larrymanley** [sunpy/sunpy#953]
![eve](https://cloud.githubusercontent.com/assets/1042961/2793219/39b9dc24-cbdd-11e3-9606-d016368caed4.png)

**Comment by abit2** [comment]
@Cadair @larrymanley Can you give the steps to generate this figure

**Comment by nabobalis** [comment]
If lightcurve is dead, does this need to be open? Does it affect time series?

Should I add a timeseries label?

**Comment by Cadair** [comment]
yes this still applies to timeseries.

**Comment by wtbarnes** [comment]
There is no description here. What is the purpose of this issue?

**Comment by dstansby** [comment]
I'm going to close since I too don't actually know what this issue describes - feel free to re-open with a description.
