### ISSUE TITLE
Interaction with ChiantiPy a GPL project

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#981]
From issue #969 we've got the first use case to need to interact with [ChiantiPy](http://chiantipy.sourceforge.net/), and this will not be the only one, once we get spectra data in sunpy ChiantiPy will be more and more needed.  ChiantiPy is a GPL project and therefore seems that there may be some incompatibilities to use it with our current BSD3.

Let's use this issue to keep a record on how we solved this and to link to all the useful information we may find.

**Comment by Cadair** [comment]
ChiantiPy is not GPL anymore...
