### ISSUE TITLE
Use `astropy.time`

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#993]
We should switch to using `astropy.time` instead of `datetime` as much as possible.

One reason is that `astropy.time` can handle leap seconds, while `datetime` ignores them.  For the most recently added leap second, which was 23:59:60 on 2012 June 30:

``` python
>>> import datetime
>>> datetime.datetime(2012, 6, 30, 23, 59, 60)
ERROR: ValueError: second must be in 0..59 [unknown]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: second must be in 0..59

>>> from astropy.time import Time, TimeDelta

>>> t1 = Time('1958-01-01', scale='tai') + TimeDelta(1719792035, format='sec')
>>> t1.utc
<Time object: scale='utc' format='iso' value=2012-07-01 00:00:00.000>
>>> t1.utc.datetime
datetime.datetime(2012, 7, 1, 0, 0)

>>> t2 = Time('1958-01-01', scale='tai') + TimeDelta(1719792034, format='sec')
>>> t2.utc
<Time object: scale='utc' format='iso' value=2012-06-30 23:59:60.000>
>>> t2.utc.datetime
ERROR: ValueError: second must be in 0..59 [astropy.time.core]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\astropy\time\core.py", line 561, in __getattr__
    out = tm._time.value[0]
  File "c:\Python27\lib\site-packages\astropy\time\core.py", line 1348, in value
    int(ihr), int(imin), int(isec), int(ifracsec))
ValueError: second must be in 0..59
```

**Comment by wafels** [comment]
0.7 or 0.8?  If we are working on lightcurves, would it also make sense to fix time?

**Comment by Cadair** [comment]
@wafels The time representation in LightCurve is separate from the standalone representation.

 I think we need to leave this until we have someone with time to work on time. (ya see what I did there!?)

**Comment by wafels** [comment]
Are you referring to the fact LightCurve uses pandas DatetimeIndex?

**Comment by Cadair** [comment]
yes

**Comment by Cadair** [comment]
On the topic of Pandas Dataframes, and Astropy Time, see: https://github.com/astropy/astropy/pull/3915

Which would add the functionality we need to replace dataframe with Astropy Table as our internal representation of the data. That however is a discussion for a separate place.

**Comment by wafels** [comment]
Well, that would make things easier with respect to time, but more
difficult with respect to manipulation.
