### ISSUE TITLE
How does sunpy maintain and update downloaded data files?

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunpy#998]
Some of the discussions regarding the GOES data files have brought up a wider issue of how sunpy generally maintains and updates data files.  The philosophy at the moment seems to be to host data files somewhere and have them downloaded to the user's download directory the first time they are needed.  Relevant functions can then access them locally.  However, such data files may be updated over time.  The question therefore is should, and if so how should, sunpy ensure that the data files in the user's download directory are the most up-to-date versions.

**Comment by wtbarnes** [comment]
I think the issue of versioning ancillary data files like response function tables, calibration data, etc. is addressed by the remote data manager (#3124). However, I'm not so sure about the tracking of regular "science" data files.

**Comment by Cadair** [comment]
I think in theory we have this covered now, remote data manager does the ancillary side and the database subpackage *should* do the science data side.
